-- =============================================================================
-- Historial local de envíos de errores y registro de su mantenimiento
-- =============================================================================
CREATE TABLE IF NOT EXISTS `fza_errores_envios` (
  `ID_ERENV` bigint unsigned NOT NULL AUTO_INCREMENT,
  `INSTANTE_ERROR_ERENV` datetime NOT NULL,
  `INSTANTE_ENVIO_ERENV` datetime NOT NULL,
  `URL_SERVICIO_ERENV` varchar(500) NOT NULL,
  `URL_SEGUIMIENTO_ERENV` varchar(1000) NULL DEFAULT NULL,
  `URL_ESTADO_ERENV` varchar(1000) NULL DEFAULT NULL,
  `REFERENCIA_ERENV` varchar(40) NULL DEFAULT NULL,
  `TOKEN_SEGUIMIENTO_ERENV` varchar(100) NULL DEFAULT NULL,
  `ESTADO_ERENV` varchar(30) NOT NULL DEFAULT 'ERROR_ENVIO',
  `CODIGO_HTTP_ERENV` int NOT NULL DEFAULT 0,
  `CLASE_ERROR_ERENV` varchar(255) NOT NULL,
  `MENSAJE_ERROR_ERENV` text NOT NULL,
  `DETALLE_ERROR_ERENV` mediumtext NOT NULL,
  `MENSAJE_ENVIO_ERENV` text NULL DEFAULT NULL,
  `EMAIL_CONTACTO_ERENV` varchar(254) NOT NULL,
  `TELEFONO_CONTACTO_ERENV` varchar(50) NOT NULL,
  `DESCRIPCION_ERENV` text NULL DEFAULT NULL,
  `COMENTARIO_TECNICO_ERENV` text NULL DEFAULT NULL,
  `COMUNICACIONES_ERENV` mediumtext NULL DEFAULT NULL,
  `INSTANTE_COMENTARIO_ERENV` datetime NULL DEFAULT NULL,
  `INSTANTE_CONSULTA_ERENV` datetime NULL DEFAULT NULL,
  `MENSAJE_CONSULTA_ERENV` varchar(1000) NULL DEFAULT NULL,
  `ID_SCRIPT_REMOTO_ERENV` bigint unsigned NULL DEFAULT NULL,
  `DESCRIPCION_SCRIPT_ERENV` varchar(500) NULL DEFAULT NULL,
  `SCRIPT_SQL_ERENV` mediumtext NULL DEFAULT NULL,
  `SHA256_SCRIPT_ERENV` char(64) NULL DEFAULT NULL,
  `ESTADO_SCRIPT_ERENV` varchar(30) NULL DEFAULT NULL,
  `ID_EJECUTABLE_REMOTO_ERENV` bigint unsigned NULL DEFAULT NULL,
  `DESCRIPCION_EJECUTABLE_ERENV` varchar(500) NULL DEFAULT NULL,
  `VERSION_EJECUTABLE_ERENV` varchar(50) NULL DEFAULT NULL,
  `URL_EJECUTABLE_ERENV` varchar(1000) NULL DEFAULT NULL,
  `NOMBRE_EJECUTABLE_ERENV` varchar(255) NULL DEFAULT NULL,
  `CANTIDAD_BYTES_EJECUTABLE_ERENV` bigint unsigned NULL DEFAULT NULL,
  `SHA256_EJECUTABLE_ERENV` char(64) NULL DEFAULT NULL,
  `ESTADO_EJECUTABLE_ERENV` varchar(30) NULL DEFAULT NULL,
  `INSTANTE_ALTA` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `INSTANTE_MODIF` datetime NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `USUARIO_ALTA` varchar(100) NOT NULL,
  `USUARIO_MODIF` varchar(100) NULL DEFAULT NULL,
  PRIMARY KEY (`ID_ERENV`),
  KEY `IDX_ERENV_ESTADO_INSTANTE` (`ESTADO_ERENV`, `INSTANTE_ERROR_ERENV`),
  KEY `IDX_ERENV_REFERENCIA` (`REFERENCIA_ERENV`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
INSERT INTO `fza_winforms`
  (`CALL_WINF`, `CAPTION_WINF`, `MENUITEM_WINF`, `UNITF_WINF`,
   `SHORTCUT_WINF`, `DATAMODULE_WINF`, `NUM_VENTANAS_WINF`)
SELECT 'ErroresEnvios',
       'Envío de errores',
       'mnuErroresEnvios',
       'inMtoErroresEnvios.TfrmMtoErroresEnvios',
       '',
       'UniDataErroresEnvios.TdmErroresEnvios',
       5
 WHERE NOT EXISTS (
   SELECT 1 FROM `fza_winforms`
    WHERE `CALL_WINF` = 'ErroresEnvios'
 );
INSERT INTO `fza_permisos`
  (`USUARIO_GRUPO_PERM`, `CODIGO_PERM`, `VALOR_PERM`, `DESCRIPCION_PERM`,
   `INSTANTE_ALTA`, `USUARIO_ALTA`)
SELECT 'Todos', 'menu.ErroresEnvios', 'S', 'Envío de errores',
       CURRENT_TIMESTAMP, 'SISTEMA'
 WHERE NOT EXISTS (
   SELECT 1 FROM `fza_permisos`
    WHERE `USUARIO_GRUPO_PERM` = 'Todos'
      AND `CODIGO_PERM` = 'menu.ErroresEnvios'
 );
