-- Facturacion por periodo de operaciones TPV VE y TA.
-- CFPER: documento interno de periodo.
-- CFOP: version procesada de una operacion de caja.
-- CFLIN: snapshot y delta de una linea de operacion.
CREATE TABLE IF NOT EXISTS fza_caja_facturaciones_periodo (
  ID_CFPER bigint(20) NOT NULL AUTO_INCREMENT,
  CLAVE_DOCUMENTO_CFPER char(36) NOT NULL,
  TIPO_OPERACION_CFPER varchar(2) NOT NULL,
  CODIGO_EMP_ORIGEN_CFPER varchar(10) NOT NULL,
  CODIGO_EMP_DESTINO_CFPER varchar(10) NULL DEFAULT NULL,
  CODIGO_ALM_CFPER varchar(10) NOT NULL,
  CODIGO_CAJA_CFPER varchar(10) NOT NULL,
  FECHA_DESDE_CFPER date NOT NULL,
  FECHA_HASTA_CFPER date NOT NULL,
  FECHA_DOCUMENTO_CFPER date NOT NULL,
  SERIE_DOCUMENTO_CFPER varchar(20) NULL DEFAULT NULL,
  NUMERO_DOCUMENTO_CFPER varchar(20) NULL DEFAULT NULL,
  ESTADO_PROCESO_CFPER varchar(20) NOT NULL DEFAULT 'PROCESANDO',
  ESTADO_FISCAL_CFPER varchar(20) NOT NULL DEFAULT 'NO_APLICA',
  ESAJUSTE_CFPER varchar(1) NOT NULL DEFAULT 'N',
  ID_CFPER_ORIGEN_CFPER bigint(20) NULL DEFAULT NULL,
  TOTAL_BASE_CFPER decimal(19,6) NOT NULL DEFAULT 0,
  TOTAL_IVA_CFPER decimal(19,6) NOT NULL DEFAULT 0,
  TOTAL_DOCUMENTO_CFPER decimal(19,6) NOT NULL DEFAULT 0,
  MENSAJE_ERROR_CFPER varchar(1000) NULL DEFAULT NULL,
  INSTANTE_ALTA datetime NOT NULL,
  INSTANTE_MODIF datetime NULL DEFAULT NULL,
  USUARIO_ALTA varchar(100) NOT NULL,
  USUARIO_MODIF varchar(100) NOT NULL,
  PRIMARY KEY (ID_CFPER),
  UNIQUE INDEX UQ_CFPER_CLAVE (CLAVE_DOCUMENTO_CFPER),
  INDEX IDX_CFPER_PERIODO (
    CODIGO_EMP_ORIGEN_CFPER,
    CODIGO_ALM_CFPER,
    CODIGO_CAJA_CFPER,
    FECHA_DESDE_CFPER,
    FECHA_HASTA_CFPER
  ),
  INDEX IDX_CFPER_DOCUMENTO (
    SERIE_DOCUMENTO_CFPER,
    NUMERO_DOCUMENTO_CFPER
  ),
  INDEX IDX_CFPER_ORIGEN (ID_CFPER_ORIGEN_CFPER)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_spanish_ci;
CREATE TABLE IF NOT EXISTS fza_caja_facturacion_operaciones (
  ID_CFOP bigint(20) NOT NULL AUTO_INCREMENT,
  ID_CFPER_CFOP bigint(20) NOT NULL,
  ID_OPCAJA_CFOP bigint(20) NOT NULL,
  ID_CFOP_ORIGEN_CFOP bigint(20) NULL DEFAULT NULL,
  TIPO_APUNTE_CFOP varchar(20) NOT NULL,
  HUELLA_ORIGEN_CFOP char(64) NOT NULL,
  CLAVE_IDEMPOTENCIA_CFOP char(64) NOT NULL,
  INSTANTE_OPERACION_CFOP datetime NOT NULL,
  IMPORTE_ORIGEN_CFOP decimal(19,6) NOT NULL DEFAULT 0,
  IMPORTE_DOCUMENTO_CFOP decimal(19,6) NOT NULL DEFAULT 0,
  INSTANTE_ALTA datetime NOT NULL,
  INSTANTE_MODIF datetime NULL DEFAULT NULL,
  USUARIO_ALTA varchar(100) NOT NULL,
  USUARIO_MODIF varchar(100) NOT NULL,
  PRIMARY KEY (ID_CFOP),
  UNIQUE INDEX UQ_CFOP_IDEMPOTENCIA (CLAVE_IDEMPOTENCIA_CFOP),
  INDEX IDX_CFOP_DOCUMENTO (ID_CFPER_CFOP),
  INDEX IDX_CFOP_OPERACION (ID_OPCAJA_CFOP, ID_CFOP),
  INDEX IDX_CFOP_ORIGEN (ID_CFOP_ORIGEN_CFOP)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_spanish_ci;
CREATE TABLE IF NOT EXISTS fza_caja_facturacion_lineas (
  ID_CFLIN bigint(20) NOT NULL AUTO_INCREMENT,
  ID_CFOP_CFLIN bigint(20) NOT NULL,
  CLAVE_LINEA_ORIGEN_CFLIN varchar(100) NOT NULL,
  LINEA_ORIGEN_CFLIN varchar(20) NULL DEFAULT NULL,
  NUMERO_MOV_ORIGEN_CFLIN varchar(20) NULL DEFAULT NULL,
  CODIGO_ART_CFLIN varchar(20) NULL DEFAULT NULL,
  CODIGO_UNIDAD_CFLIN varchar(50) NULL DEFAULT NULL,
  DESCRIPCION_CFLIN varchar(200) NULL DEFAULT NULL,
  CANTIDAD_ORIGEN_CFLIN decimal(19,6) NOT NULL DEFAULT 0,
  CANTIDAD_DOCUMENTO_CFLIN decimal(19,6) NOT NULL DEFAULT 0,
  PRECIO_UNITARIO_BASE_CFLIN decimal(19,6) NOT NULL DEFAULT 0,
  TIPO_IVA_CFLIN varchar(2) NOT NULL DEFAULT 'NA',
  PORCENTAJE_IVA_CFLIN decimal(19,6) NOT NULL DEFAULT 0,
  TOTAL_ORIGEN_BASE_CFLIN decimal(19,6) NOT NULL DEFAULT 0,
  TOTAL_ORIGEN_IVA_CFLIN decimal(19,6) NOT NULL DEFAULT 0,
  TOTAL_ORIGEN_CFLIN decimal(19,6) NOT NULL DEFAULT 0,
  TOTAL_BASE_CFLIN decimal(19,6) NOT NULL DEFAULT 0,
  TOTAL_IVA_CFLIN decimal(19,6) NOT NULL DEFAULT 0,
  TOTAL_LINEA_CFLIN decimal(19,6) NOT NULL DEFAULT 0,
  INSTANTE_ALTA datetime NOT NULL,
  INSTANTE_MODIF datetime NULL DEFAULT NULL,
  USUARIO_ALTA varchar(100) NOT NULL,
  USUARIO_MODIF varchar(100) NOT NULL,
  PRIMARY KEY (ID_CFLIN),
  UNIQUE INDEX UQ_CFLIN_ORIGEN (
    ID_CFOP_CFLIN,
    CLAVE_LINEA_ORIGEN_CFLIN
  ),
  INDEX IDX_CFLIN_ARTICULO (CODIGO_ART_CFLIN, CODIGO_UNIDAD_CFLIN)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_spanish_ci;
INSERT INTO fza_tipos_documentos (
  CODIGO_TIPO_DOCUMENTO_TD,
  DESCRIPCION_TIPO_DOCUMENTO_TD,
  TABLA_ORIGEN_TIPO_DOCUMENTO_TD
)
SELECT 'PI', 'PROFORMA INTERNA VENTA CONTADO',
       'fza_caja_facturaciones_periodo'
WHERE NOT EXISTS (
  SELECT 1
    FROM fza_tipos_documentos
   WHERE CODIGO_TIPO_DOCUMENTO_TD = 'PI'
);
INSERT INTO fza_tipos_documentos (
  CODIGO_TIPO_DOCUMENTO_TD,
  DESCRIPCION_TIPO_DOCUMENTO_TD,
  TABLA_ORIGEN_TIPO_DOCUMENTO_TD
)
SELECT 'TA', 'TRASPASO ENTRE EMPRESAS', 'fza_caja_operaciones'
WHERE NOT EXISTS (
  SELECT 1
    FROM fza_tipos_documentos
   WHERE CODIGO_TIPO_DOCUMENTO_TD = 'TA'
);
