-- ============================================================================
-- Facturacion periodica de operaciones de caja VE y TA
-- ============================================================================
-- VE se materializa como proforma interna no fiscal. TA genera una factura
-- normal y esta tabla auxiliar conserva el vinculo con cada operacion.
-- Las lineas AJUSTE compensan una VE incluida que despues fue rectificada o
-- sustituida. El script es idempotente y no modifica el dump modelo.
-- ============================================================================
CREATE TABLE IF NOT EXISTS `fza_facturacion_caja_periodos` (
  `ID_FACPER` bigint(20) NOT NULL AUTO_INCREMENT,
  `MODALIDAD_FACPER` varchar(2) NOT NULL,
  `CODIGO_EMP_ORIGEN_FACPER` varchar(10) NULL DEFAULT NULL,
  `CODIGO_EMP_DESTINO_FACPER` varchar(10) NOT NULL,
  `FECHA_DESDE_FACPER` date NOT NULL,
  `FECHA_HASTA_FACPER` date NOT NULL,
  `ESTADO_FACPER` varchar(20) NOT NULL DEFAULT 'ABIERTO',
  `CANTIDAD_DOCUMENTOS_FACPER` int(11) NOT NULL DEFAULT '0',
  `CANTIDAD_OPERACIONES_FACPER` int(11) NOT NULL DEFAULT '0',
  `CANTIDAD_AJUSTES_FACPER` int(11) NOT NULL DEFAULT '0',
  `INSTANTE_ALTA` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `INSTANTE_MODIF` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
    ON UPDATE CURRENT_TIMESTAMP,
  `USUARIO_ALTA` varchar(100) NOT NULL,
  `USUARIO_MODIF` varchar(100) NOT NULL,
  PRIMARY KEY (`ID_FACPER`),
  INDEX `IDX_FACPER_REVISION` (
    `MODALIDAD_FACPER`, `CODIGO_EMP_ORIGEN_FACPER`,
    `CODIGO_EMP_DESTINO_FACPER`,
    `FECHA_DESDE_FACPER`, `FECHA_HASTA_FACPER`),
  INDEX `IDX_FACPER_ESTADO` (`ESTADO_FACPER`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_spanish_ci;
CREATE TABLE IF NOT EXISTS `fza_proformas_caja` (
  `ID_PROCAJ` bigint(20) NOT NULL AUTO_INCREMENT,
  `ID_FACPER_PROCAJ` bigint(20) NOT NULL,
  `NUMERO_PROCAJ` varchar(20) NOT NULL,
  `SERIE_PROCAJ` varchar(20) NOT NULL,
  `FECHA_PROCAJ` date NOT NULL,
  `FECHA_DESDE_PROCAJ` date NOT NULL,
  `FECHA_HASTA_PROCAJ` date NOT NULL,
  `TIPO_PROCAJ` varchar(2) NOT NULL DEFAULT 'VE',
  `ESTADO_PROCAJ` varchar(20) NOT NULL DEFAULT 'EMITIDA',
  `CODIGO_EMP_PROCAJ` varchar(10) NOT NULL,
  `RAZON_SOCIAL_EMPRESA_PROCAJ` varchar(200) NULL DEFAULT NULL,
  `NIF_EMPRESA_PROCAJ` varchar(50) NULL DEFAULT NULL,
  `DIRECCION1_EMPRESA_PROCAJ` varchar(200) NULL DEFAULT NULL,
  `DIRECCION2_EMPRESA_PROCAJ` varchar(200) NULL DEFAULT NULL,
  `CODIGO_POSTAL_EMPRESA_PROCAJ` varchar(15) NULL DEFAULT NULL,
  `POBLACION_EMPRESA_PROCAJ` varchar(200) NULL DEFAULT NULL,
  `PROVINCIA_EMPRESA_PROCAJ` varchar(200) NULL DEFAULT NULL,
  `CODIGO_PAI_EMPRESA_PROCAJ` varchar(3) NULL DEFAULT NULL,
  `NOMBRE_PAI_EMPRESA_PROCAJ` varchar(150) NULL DEFAULT NULL,
  `CODIGO_CLI_PROCAJ` varchar(20) NOT NULL DEFAULT '0',
  `RAZON_SOCIAL_CLIENTE_PROCAJ` varchar(200) NOT NULL DEFAULT 'VENTA CONTADO',
  `TOTAL_BASE_PROCAJ` decimal(19,6) NOT NULL DEFAULT '0.000000',
  `TOTAL_IMPUESTOS_PROCAJ` decimal(19,6) NOT NULL DEFAULT '0.000000',
  `TOTAL_PROCAJ` decimal(19,6) NOT NULL DEFAULT '0.000000',
  `INSTANTE_ALTA` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `INSTANTE_MODIF` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
    ON UPDATE CURRENT_TIMESTAMP,
  `USUARIO_ALTA` varchar(100) NOT NULL,
  `USUARIO_MODIF` varchar(100) NOT NULL,
  PRIMARY KEY (`ID_PROCAJ`),
  UNIQUE INDEX `UQ_PROCAJ_DOCUMENTO` (
    `CODIGO_EMP_PROCAJ`, `SERIE_PROCAJ`, `NUMERO_PROCAJ`),
  INDEX `IDX_PROCAJ_PERIODO_REG` (`ID_FACPER_PROCAJ`),
  INDEX `IDX_PROCAJ_EMP_FECHA` (`CODIGO_EMP_PROCAJ`, `FECHA_PROCAJ`),
  INDEX `IDX_PROCAJ_PERIODO` (`FECHA_DESDE_PROCAJ`, `FECHA_HASTA_PROCAJ`),
  INDEX `IDX_PROCAJ_ESTADO` (`ESTADO_PROCAJ`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_spanish_ci;
CREATE TABLE IF NOT EXISTS `fza_proformas_caja_lineas` (
  `ID_PROCAJ_PROCLIN` bigint(20) NOT NULL,
  `LINEA_PROCLIN` varchar(8) NOT NULL,
  `ID_OPCAJA_PROCLIN` bigint(20) NOT NULL,
  `TIPO_VINCULO_PROCLIN` varchar(10) NOT NULL DEFAULT 'ORIGEN',
  `ID_PROCAJ_ORIGEN_PROCLIN` bigint(20) NULL DEFAULT NULL,
  `LINEA_PROCAJ_ORIGEN_PROCLIN` varchar(8) NULL DEFAULT NULL,
  `SERIE_FAC_ORIGEN_PROCLIN` varchar(20) NOT NULL,
  `NUMERO_FAC_ORIGEN_PROCLIN` varchar(20) NOT NULL,
  `LINEA_FAC_ORIGEN_PROCLIN` varchar(4) NOT NULL,
  `NUMERO_OPERACION_PROCLIN` varchar(20) NOT NULL,
  `FECHA_OPERACION_PROCLIN` date NOT NULL,
  `CODIGO_ART_PROCLIN` varchar(20) NULL DEFAULT NULL,
  `CODIGO_UNIDAD_PROCLIN` varchar(50) NULL DEFAULT NULL,
  `DESCRIPCION_ARTICULO_PROCLIN` varchar(200) NULL DEFAULT NULL,
  `TIPO_IVA_PROCLIN` varchar(2) NULL DEFAULT NULL,
  `CANTIDAD_PROCLIN` decimal(19,6) NOT NULL DEFAULT '0.000000',
  `PRECIO_SIVA_PROCLIN` decimal(19,6) NOT NULL DEFAULT '0.000000',
  `PORCENTAJE_IVA_PROCLIN` decimal(19,6) NOT NULL DEFAULT '0.000000',
  `TOTAL_SIVA_PROCLIN` decimal(19,6) NOT NULL DEFAULT '0.000000',
  `TOTAL_PROCLIN` decimal(19,6) NOT NULL DEFAULT '0.000000',
  `INSTANTE_ALTA` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `INSTANTE_MODIF` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
    ON UPDATE CURRENT_TIMESTAMP,
  `USUARIO_ALTA` varchar(100) NOT NULL,
  `USUARIO_MODIF` varchar(100) NOT NULL,
  PRIMARY KEY (`ID_PROCAJ_PROCLIN`, `LINEA_PROCLIN`),
  UNIQUE INDEX `UQ_PROCLIN_ORIGEN` (
    `ID_OPCAJA_PROCLIN`, `TIPO_VINCULO_PROCLIN`,
    `SERIE_FAC_ORIGEN_PROCLIN`, `NUMERO_FAC_ORIGEN_PROCLIN`,
    `LINEA_FAC_ORIGEN_PROCLIN`),
  INDEX `IDX_PROCLIN_OPERACION` (`ID_OPCAJA_PROCLIN`),
  INDEX `IDX_PROCLIN_PROFORMA_ORIGEN` (
    `ID_PROCAJ_ORIGEN_PROCLIN`, `LINEA_PROCAJ_ORIGEN_PROCLIN`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_spanish_ci;
CREATE TABLE IF NOT EXISTS `fza_facturas_operaciones_caja` (
  `ID_FACOP` bigint(20) NOT NULL AUTO_INCREMENT,
  `ID_FACPER_FACOP` bigint(20) NOT NULL,
  `ID_OPCAJA_FACOP` bigint(20) NOT NULL,
  `SERIE_FAC_FACOP` varchar(20) NOT NULL,
  `NUMERO_FAC_FACOP` varchar(20) NOT NULL,
  `CODIGO_EMP_ORIGEN_FACOP` varchar(10) NOT NULL,
  `CODIGO_EMP_DESTINO_FACOP` varchar(10) NOT NULL,
  `NUMERO_OPERACION_FACOP` varchar(20) NOT NULL,
  `FECHA_OPERACION_FACOP` date NOT NULL,
  `IMPORTE_OPERACION_FACOP` decimal(19,6) NOT NULL DEFAULT '0.000000',
  `ESTADO_FACOP` varchar(20) NOT NULL DEFAULT 'FACTURADA',
  `INSTANTE_ALTA` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `INSTANTE_MODIF` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
    ON UPDATE CURRENT_TIMESTAMP,
  `USUARIO_ALTA` varchar(100) NOT NULL,
  `USUARIO_MODIF` varchar(100) NOT NULL,
  PRIMARY KEY (`ID_FACOP`),
  UNIQUE INDEX `UQ_FACOP_OPERACION` (`ID_OPCAJA_FACOP`),
  INDEX `IDX_FACOP_PERIODO` (`ID_FACPER_FACOP`),
  INDEX `IDX_FACOP_FACTURA` (`SERIE_FAC_FACOP`, `NUMERO_FAC_FACOP`),
  INDEX `IDX_FACOP_EMPRESAS` (
    `CODIGO_EMP_ORIGEN_FACOP`, `CODIGO_EMP_DESTINO_FACOP`),
  INDEX `IDX_FACOP_ESTADO` (`ESTADO_FACOP`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_spanish_ci;
SET @sExisteCol = (
  SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS
   WHERE TABLE_SCHEMA = DATABASE()
     AND TABLE_NAME = 'fza_facturacion_caja_periodos'
     AND COLUMN_NAME = 'CODIGO_EMP_ORIGEN_FACPER');
SET @sSql = IF(@sExisteCol = 0,
  'ALTER TABLE fza_facturacion_caja_periodos
     ADD COLUMN CODIGO_EMP_ORIGEN_FACPER varchar(10) NULL DEFAULT NULL
     AFTER MODALIDAD_FACPER',
  'SELECT 1');
PREPARE stmt FROM @sSql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;
-- En VE el unico codigo de empresa historico era, de hecho, el emisor.
UPDATE fza_facturacion_caja_periodos
   SET CODIGO_EMP_ORIGEN_FACPER = CODIGO_EMP_DESTINO_FACPER
 WHERE CODIGO_EMP_ORIGEN_FACPER IS NULL
   AND MODALIDAD_FACPER = 'VE';
SET @sColumnasIdx = (
  SELECT GROUP_CONCAT(COLUMN_NAME ORDER BY SEQ_IN_INDEX SEPARATOR ',')
    FROM INFORMATION_SCHEMA.STATISTICS
   WHERE TABLE_SCHEMA = DATABASE()
     AND TABLE_NAME = 'fza_facturacion_caja_periodos'
     AND INDEX_NAME = 'IDX_FACPER_REVISION');
SET @sSql = IF(
  @sColumnasIdx IS NOT NULL
  AND @sColumnasIdx <> CONCAT(
    'MODALIDAD_FACPER,CODIGO_EMP_ORIGEN_FACPER,',
    'CODIGO_EMP_DESTINO_FACPER,FECHA_DESDE_FACPER,FECHA_HASTA_FACPER'),
  'ALTER TABLE fza_facturacion_caja_periodos
     DROP INDEX IDX_FACPER_REVISION',
  'SELECT 1');
PREPARE stmt FROM @sSql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;
SET @sExisteIdx = (
  SELECT COUNT(*) FROM INFORMATION_SCHEMA.STATISTICS
   WHERE TABLE_SCHEMA = DATABASE()
     AND TABLE_NAME = 'fza_facturacion_caja_periodos'
     AND INDEX_NAME = 'IDX_FACPER_REVISION');
SET @sSql = IF(@sExisteIdx = 0,
  'ALTER TABLE fza_facturacion_caja_periodos
     ADD INDEX IDX_FACPER_REVISION
       (MODALIDAD_FACPER, CODIGO_EMP_ORIGEN_FACPER,
        CODIGO_EMP_DESTINO_FACPER, FECHA_DESDE_FACPER,
        FECHA_HASTA_FACPER)',
  'SELECT 1');
PREPARE stmt FROM @sSql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;
SET @sExisteCol = (
  SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS
   WHERE TABLE_SCHEMA = DATABASE()
     AND TABLE_NAME = 'fza_proformas_caja'
     AND COLUMN_NAME = 'ID_FACPER_PROCAJ');
SET @sSql = IF(@sExisteCol = 0,
  'ALTER TABLE fza_proformas_caja
     ADD COLUMN ID_FACPER_PROCAJ bigint(20) NULL DEFAULT NULL
     AFTER ID_PROCAJ',
  'SELECT 1');
PREPARE stmt FROM @sSql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;
SET @sColumnasIdx = (
  SELECT GROUP_CONCAT(COLUMN_NAME ORDER BY SEQ_IN_INDEX SEPARATOR ',')
    FROM INFORMATION_SCHEMA.STATISTICS
   WHERE TABLE_SCHEMA = DATABASE()
     AND TABLE_NAME = 'fza_proformas_caja'
     AND INDEX_NAME = 'UQ_PROCAJ_DOCUMENTO');
SET @sSql = IF(
  @sColumnasIdx IS NOT NULL
  AND @sColumnasIdx <>
    'CODIGO_EMP_PROCAJ,SERIE_PROCAJ,NUMERO_PROCAJ',
  'ALTER TABLE fza_proformas_caja DROP INDEX UQ_PROCAJ_DOCUMENTO',
  'SELECT 1');
PREPARE stmt FROM @sSql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;
SET @sExisteIdx = (
  SELECT COUNT(*) FROM INFORMATION_SCHEMA.STATISTICS
   WHERE TABLE_SCHEMA = DATABASE()
     AND TABLE_NAME = 'fza_proformas_caja'
     AND INDEX_NAME = 'UQ_PROCAJ_DOCUMENTO');
SET @sSql = IF(@sExisteIdx = 0,
  'ALTER TABLE fza_proformas_caja
     ADD UNIQUE INDEX UQ_PROCAJ_DOCUMENTO
       (CODIGO_EMP_PROCAJ, SERIE_PROCAJ, NUMERO_PROCAJ)',
  'SELECT 1');
PREPARE stmt FROM @sSql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;
SET @sExisteIdx = (
  SELECT COUNT(*) FROM INFORMATION_SCHEMA.STATISTICS
   WHERE TABLE_SCHEMA = DATABASE()
     AND TABLE_NAME = 'fza_proformas_caja'
     AND INDEX_NAME = 'IDX_PROCAJ_PERIODO_REG');
SET @sSql = IF(@sExisteIdx = 0,
  'ALTER TABLE fza_proformas_caja
     ADD INDEX IDX_PROCAJ_PERIODO_REG (ID_FACPER_PROCAJ)',
  'SELECT 1');
PREPARE stmt FROM @sSql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;
SET @sExisteCol = (
  SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS
   WHERE TABLE_SCHEMA = DATABASE()
     AND TABLE_NAME = 'fza_facturas_operaciones_caja'
     AND COLUMN_NAME = 'ID_FACPER_FACOP');
SET @sSql = IF(@sExisteCol = 0,
  'ALTER TABLE fza_facturas_operaciones_caja
     ADD COLUMN ID_FACPER_FACOP bigint(20) NULL DEFAULT NULL
     AFTER ID_FACOP',
  'SELECT 1');
PREPARE stmt FROM @sSql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;
-- Un TA legado podia reunir varias emisoras en un mismo periodo. Solo se
-- rellena el origen singular; NULL conserva el significado VARIAS/SIN RASTRO.
UPDATE fza_facturacion_caja_periodos P
JOIN (
  SELECT ID_FACPER_FACOP,
         MIN(CODIGO_EMP_ORIGEN_FACOP) AS CODIGO_EMP_ORIGEN
    FROM fza_facturas_operaciones_caja
   WHERE ID_FACPER_FACOP IS NOT NULL
   GROUP BY ID_FACPER_FACOP
  HAVING COUNT(DISTINCT CODIGO_EMP_ORIGEN_FACOP) = 1
) O ON O.ID_FACPER_FACOP = P.ID_FACPER
   SET P.CODIGO_EMP_ORIGEN_FACPER = O.CODIGO_EMP_ORIGEN
 WHERE P.MODALIDAD_FACPER = 'TA'
   AND P.CODIGO_EMP_ORIGEN_FACPER IS NULL;
SET @sExisteIdx = (
  SELECT COUNT(*) FROM INFORMATION_SCHEMA.STATISTICS
   WHERE TABLE_SCHEMA = DATABASE()
     AND TABLE_NAME = 'fza_facturas_operaciones_caja'
     AND INDEX_NAME = 'IDX_FACOP_PERIODO');
SET @sSql = IF(@sExisteIdx = 0,
  'ALTER TABLE fza_facturas_operaciones_caja
     ADD INDEX IDX_FACOP_PERIODO (ID_FACPER_FACOP)',
  'SELECT 1');
PREPARE stmt FROM @sSql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;
INSERT INTO `fza_winforms` (
  `CALL_WINF`, `CAPTION_WINF`, `MENUITEM_WINF`, `UNITF_WINF`,
  `SHORTCUT_WINF`, `DATAMODULE_WINF`, `NUM_VENTANAS_WINF`)
VALUES (
  'FacturasProforma', 'Facturas proforma', 'mnuFacturasProforma',
  'inMtoFacturasProforma.TfrmMtoFacturasProforma', '',
  'UniDataFacturasProforma.TdmFacturasProforma', 1)
ON DUPLICATE KEY UPDATE
  `CAPTION_WINF` = VALUES(`CAPTION_WINF`),
  `MENUITEM_WINF` = VALUES(`MENUITEM_WINF`),
  `UNITF_WINF` = VALUES(`UNITF_WINF`),
  `DATAMODULE_WINF` = VALUES(`DATAMODULE_WINF`),
  `NUM_VENTANAS_WINF` = VALUES(`NUM_VENTANAS_WINF`);
