-- ============================================================================
-- Facturacion periodica de operaciones de caja VE y TA
-- ============================================================================
-- VE se materializa como proforma interna no fiscal. TA genera una factura
-- normal y esta tabla auxiliar conserva el vinculo con cada operacion.
-- Las lineas AJUSTE compensan una VE incluida que despues fue rectificada o
-- sustituida. El script es idempotente y no modifica el dump modelo.
-- ============================================================================
CREATE TABLE IF NOT EXISTS `fza_proformas_caja` (
  `ID_PROCAJ` bigint(20) NOT NULL AUTO_INCREMENT,
  `NUMERO_PROCAJ` varchar(20) NOT NULL,
  `SERIE_PROCAJ` varchar(20) NOT NULL,
  `FECHA_PROCAJ` date NOT NULL,
  `FECHA_DESDE_PROCAJ` date NOT NULL,
  `FECHA_HASTA_PROCAJ` date NOT NULL,
  `TIPO_PROCAJ` varchar(2) NOT NULL DEFAULT 'VE',
  `ESTADO_PROCAJ` varchar(20) NOT NULL DEFAULT 'EMITIDA',
  `CODIGO_EMP_PROCAJ` varchar(10) NOT NULL,
  `RAZON_SOCIAL_EMPRESA_PROCAJ` varchar(200) NULL DEFAULT NULL,
  `NIF_EMPRESA_PROCAJ` varchar(50) NULL DEFAULT NULL,
  `DIRECCION1_EMPRESA_PROCAJ` varchar(200) NULL DEFAULT NULL,
  `DIRECCION2_EMPRESA_PROCAJ` varchar(200) NULL DEFAULT NULL,
  `CODIGO_POSTAL_EMPRESA_PROCAJ` varchar(15) NULL DEFAULT NULL,
  `POBLACION_EMPRESA_PROCAJ` varchar(200) NULL DEFAULT NULL,
  `PROVINCIA_EMPRESA_PROCAJ` varchar(200) NULL DEFAULT NULL,
  `CODIGO_PAI_EMPRESA_PROCAJ` varchar(3) NULL DEFAULT NULL,
  `NOMBRE_PAI_EMPRESA_PROCAJ` varchar(150) NULL DEFAULT NULL,
  `CODIGO_CLI_PROCAJ` varchar(20) NOT NULL DEFAULT '0',
  `RAZON_SOCIAL_CLIENTE_PROCAJ` varchar(200) NOT NULL DEFAULT 'VENTA CONTADO',
  `TOTAL_BASE_PROCAJ` decimal(19,6) NOT NULL DEFAULT '0.000000',
  `TOTAL_IMPUESTOS_PROCAJ` decimal(19,6) NOT NULL DEFAULT '0.000000',
  `TOTAL_PROCAJ` decimal(19,6) NOT NULL DEFAULT '0.000000',
  `INSTANTE_ALTA` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `INSTANTE_MODIF` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
    ON UPDATE CURRENT_TIMESTAMP,
  `USUARIO_ALTA` varchar(100) NOT NULL,
  `USUARIO_MODIF` varchar(100) NOT NULL,
  PRIMARY KEY (`ID_PROCAJ`),
  UNIQUE INDEX `UQ_PROCAJ_DOCUMENTO` (`SERIE_PROCAJ`, `NUMERO_PROCAJ`),
  INDEX `IDX_PROCAJ_EMP_FECHA` (`CODIGO_EMP_PROCAJ`, `FECHA_PROCAJ`),
  INDEX `IDX_PROCAJ_PERIODO` (`FECHA_DESDE_PROCAJ`, `FECHA_HASTA_PROCAJ`),
  INDEX `IDX_PROCAJ_ESTADO` (`ESTADO_PROCAJ`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_spanish_ci;
CREATE TABLE IF NOT EXISTS `fza_proformas_caja_lineas` (
  `ID_PROCAJ_PROCLIN` bigint(20) NOT NULL,
  `LINEA_PROCLIN` varchar(8) NOT NULL,
  `ID_OPCAJA_PROCLIN` bigint(20) NOT NULL,
  `TIPO_VINCULO_PROCLIN` varchar(10) NOT NULL DEFAULT 'ORIGEN',
  `ID_PROCAJ_ORIGEN_PROCLIN` bigint(20) NULL DEFAULT NULL,
  `LINEA_PROCAJ_ORIGEN_PROCLIN` varchar(8) NULL DEFAULT NULL,
  `SERIE_FAC_ORIGEN_PROCLIN` varchar(20) NOT NULL,
  `NUMERO_FAC_ORIGEN_PROCLIN` varchar(20) NOT NULL,
  `LINEA_FAC_ORIGEN_PROCLIN` varchar(4) NOT NULL,
  `NUMERO_OPERACION_PROCLIN` varchar(20) NOT NULL,
  `FECHA_OPERACION_PROCLIN` date NOT NULL,
  `CODIGO_ART_PROCLIN` varchar(20) NULL DEFAULT NULL,
  `CODIGO_UNIDAD_PROCLIN` varchar(50) NULL DEFAULT NULL,
  `DESCRIPCION_ARTICULO_PROCLIN` varchar(200) NULL DEFAULT NULL,
  `TIPO_IVA_PROCLIN` varchar(2) NULL DEFAULT NULL,
  `CANTIDAD_PROCLIN` decimal(19,6) NOT NULL DEFAULT '0.000000',
  `PRECIO_SIVA_PROCLIN` decimal(19,6) NOT NULL DEFAULT '0.000000',
  `PORCENTAJE_IVA_PROCLIN` decimal(19,6) NOT NULL DEFAULT '0.000000',
  `TOTAL_SIVA_PROCLIN` decimal(19,6) NOT NULL DEFAULT '0.000000',
  `TOTAL_PROCLIN` decimal(19,6) NOT NULL DEFAULT '0.000000',
  `INSTANTE_ALTA` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `INSTANTE_MODIF` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
    ON UPDATE CURRENT_TIMESTAMP,
  `USUARIO_ALTA` varchar(100) NOT NULL,
  `USUARIO_MODIF` varchar(100) NOT NULL,
  PRIMARY KEY (`ID_PROCAJ_PROCLIN`, `LINEA_PROCLIN`),
  UNIQUE INDEX `UQ_PROCLIN_ORIGEN` (
    `ID_OPCAJA_PROCLIN`, `TIPO_VINCULO_PROCLIN`,
    `SERIE_FAC_ORIGEN_PROCLIN`, `NUMERO_FAC_ORIGEN_PROCLIN`,
    `LINEA_FAC_ORIGEN_PROCLIN`),
  INDEX `IDX_PROCLIN_OPERACION` (`ID_OPCAJA_PROCLIN`),
  INDEX `IDX_PROCLIN_PROFORMA_ORIGEN` (
    `ID_PROCAJ_ORIGEN_PROCLIN`, `LINEA_PROCAJ_ORIGEN_PROCLIN`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_spanish_ci;
CREATE TABLE IF NOT EXISTS `fza_facturas_operaciones_caja` (
  `ID_FACOP` bigint(20) NOT NULL AUTO_INCREMENT,
  `ID_OPCAJA_FACOP` bigint(20) NOT NULL,
  `SERIE_FAC_FACOP` varchar(20) NOT NULL,
  `NUMERO_FAC_FACOP` varchar(20) NOT NULL,
  `CODIGO_EMP_ORIGEN_FACOP` varchar(10) NOT NULL,
  `CODIGO_EMP_DESTINO_FACOP` varchar(10) NOT NULL,
  `NUMERO_OPERACION_FACOP` varchar(20) NOT NULL,
  `FECHA_OPERACION_FACOP` date NOT NULL,
  `IMPORTE_OPERACION_FACOP` decimal(19,6) NOT NULL DEFAULT '0.000000',
  `ESTADO_FACOP` varchar(20) NOT NULL DEFAULT 'FACTURADA',
  `INSTANTE_ALTA` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `INSTANTE_MODIF` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
    ON UPDATE CURRENT_TIMESTAMP,
  `USUARIO_ALTA` varchar(100) NOT NULL,
  `USUARIO_MODIF` varchar(100) NOT NULL,
  PRIMARY KEY (`ID_FACOP`),
  UNIQUE INDEX `UQ_FACOP_OPERACION` (`ID_OPCAJA_FACOP`),
  INDEX `IDX_FACOP_FACTURA` (`SERIE_FAC_FACOP`, `NUMERO_FAC_FACOP`),
  INDEX `IDX_FACOP_EMPRESAS` (
    `CODIGO_EMP_ORIGEN_FACOP`, `CODIGO_EMP_DESTINO_FACOP`),
  INDEX `IDX_FACOP_ESTADO` (`ESTADO_FACOP`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_spanish_ci;
INSERT INTO `fza_winforms` (
  `CALL_WINF`, `CAPTION_WINF`, `MENUITEM_WINF`, `UNITF_WINF`,
  `SHORTCUT_WINF`, `DATAMODULE_WINF`, `NUM_VENTANAS_WINF`)
VALUES (
  'FacturasProforma', 'Facturas proforma', 'mnuFacturasProforma',
  'inMtoFacturasProforma.TfrmMtoFacturasProforma', '',
  'UniDataFacturasProforma.TdmFacturasProforma', 1)
ON DUPLICATE KEY UPDATE
  `CAPTION_WINF` = VALUES(`CAPTION_WINF`),
  `MENUITEM_WINF` = VALUES(`MENUITEM_WINF`),
  `UNITF_WINF` = VALUES(`UNITF_WINF`),
  `DATAMODULE_WINF` = VALUES(`DATAMODULE_WINF`),
  `NUM_VENTANAS_WINF` = VALUES(`NUM_VENTANAS_WINF`);
