DROP PROCEDURE IF EXISTS PRC_PED_CREAR_ALBARAN_FIN;

DELIMITER //

CREATE PROCEDURE PRC_PED_CREAR_ALBARAN_FIN(
  IN p_NUMERO_ALB varchar(20),
  IN p_SERIE_ALB varchar(20),
  IN p_NUMERO_PED varchar(20),
  IN p_SERIE_PED varchar(20),
  IN p_USUARIO varchar(100))
BEGIN
  DECLARE v_total_base decimal(18,6) DEFAULT 0;
  DECLARE v_total_iva decimal(18,6) DEFAULT 0;
  DECLARE v_pendientes int DEFAULT 0;
  SELECT IFNULL(SUM(CANTIDAD_ALBLIN *
                    PRECIO_VENTA_SIVA_ARTICULO_ALBLIN), 0),
         IFNULL(SUM(CANTIDAD_ALBLIN *
              (PRECIO_VENTA_CIVA_ARTICULO_ALBLIN -
               PRECIO_VENTA_SIVA_ARTICULO_ALBLIN)), 0)
    INTO v_total_base, v_total_iva
    FROM fza_albaranes_lineas
   WHERE NUMERO_ALB_ALBLIN = p_NUMERO_ALB
     AND SERIE_ALB_ALBLIN = p_SERIE_ALB;
  UPDATE fza_albaranes
     SET TOTAL_BASES_ALB = v_total_base,
         TOTAL_IMPUESTOS_ALB = v_total_iva,
         TOTAL_LIQUIDO_ALB = v_total_base + v_total_iva,
         INSTANTE_MODIF = NOW(),
         USUARIO_MODIF = p_USUARIO
   WHERE NUMERO_ALB = p_NUMERO_ALB
     AND SERIE_ALB = p_SERIE_ALB;
  SELECT COUNT(*)
    INTO v_pendientes
    FROM fza_pedidos_lineas
   WHERE NUMERO_PED_PEDLIN = p_NUMERO_PED
     AND SERIE_PED_PEDLIN = p_SERIE_PED
     AND IFNULL(ESENTREGADA_PEDLIN, 'N') <> 'S';
  IF v_pendientes = 0 THEN
    UPDATE fza_pedidos
       SET ESTADO_PED = 'ENTREGADO',
           INSTANTE_MODIF = NOW(),
           USUARIO_MODIF = p_USUARIO
     WHERE NUMERO_PED = p_NUMERO_PED
       AND SERIE_PED = p_SERIE_PED;
  ELSE
    UPDATE fza_pedidos
       SET ESTADO_PED = 'PARCIAL',
           INSTANTE_MODIF = NOW(),
           USUARIO_MODIF = p_USUARIO
     WHERE NUMERO_PED = p_NUMERO_PED
       AND SERIE_PED = p_SERIE_PED;
  END IF;
END//

DELIMITER ;

DROP PROCEDURE IF EXISTS PRC_PED_CREAR_ALBARAN_INICIO;

DELIMITER //

CREATE PROCEDURE PRC_PED_CREAR_ALBARAN_INICIO(
  IN p_NUMERO_PED varchar(20),
  IN p_SERIE_PED varchar(20),
  IN p_USUARIO varchar(100),
  OUT p_NUMERO_ALB varchar(20),
  OUT p_SERIE_ALB varchar(20))
BEGIN
  DECLARE v_serie varchar(20);
  DECLARE v_numero varchar(20);
  SELECT SERIE_PED
    INTO v_serie
    FROM fza_pedidos
   WHERE NUMERO_PED = p_NUMERO_PED
     AND SERIE_PED = p_SERIE_PED;
  SELECT LPAD(IFNULL(MAX(CAST(NUMERO_ALB AS UNSIGNED)), 0) + 1, 6, '0')
    INTO v_numero
    FROM fza_albaranes
   WHERE SERIE_ALB = v_serie;
  INSERT INTO fza_albaranes (
    NUMERO_ALB, SERIE_ALB, FECHA_ALB, ESTADO_ALB,
    NUMERO_PED_ALB, SERIE_PED_ALB,
    CODIGO_EMP_ALB, CODIGO_ALM_ALB,
    RAZON_SOCIAL_EMPRESA_ALB, NIF_EMPRESA_ALB,
    MOVIL_EMPRESA_ALB, EMAIL_EMPRESA_ALB,
    DIRECCION1_EMPRESA_ALB, DIRECCION2_EMPRESA_ALB,
    POBLACION_EMPRESA_ALB, PROVINCIA_EMPRESA_ALB,
    CODIGO_PAI_EMPRESA_ALB, NOMBRE_PAI_EMPRESA_ALB,
    CODIGO_POSTAL_EMPRESA_ALB, GRUPO_ZONA_IVA_EMPRESA_ALB,
    CODIGO_CLI_ALB, RAZON_SOCIAL_CLIENTE_ALB,
    NIF_CLIENTE_ALB, MOVIL_CLIENTE_ALB, EMAIL_CLIENTE_ALB,
    DIRECCION1_CLIENTE_ALB, DIRECCION2_CLIENTE_ALB,
    POBLACION_CLIENTE_ALB, PROVINCIA_CLIENTE_ALB,
    CODIGO_POSTAL_CLIENTE_ALB, CODIGO_PAI_CLIENTE_ALB,
    NOMBRE_PAI_CLIENTE_ALB, NOMBRE_CLI_ENVIO_ALB,
    MOVIL_CLIENTE_ENVIO_ALB, DIRECCION1_CLIENTE_ENVIO_ALB,
    DIRECCION2_CLIENTE_ENVIO_ALB, POBLACION_CLIENTE_ENVIO_ALB,
    PROVINCIA_CLIENTE_ENVIO_ALB, CODIGO_POSTAL_CLIENTE_ENVIO_ALB,
    CODIGO_PAI_CLIENTE_ENVIO_ALB, NOMBRE_PAI_CLIENTE_ENVIO_ALB,
    TRANSPORTISTA_ALB, CODIGO_IVA_ALB,
    ESIVA_RECARGO_CLIENTE_ALB, ESIVA_EXENTO_CLIENTE_ALB,
    ESINTRACOMUNITARIO_CLIENTE_ALB, TARIFA_ARTICULO_CLIENTE_ALB,
    ESIMP_INCL_TARIFA_CLIENTE_ALB, PORCENTAJE_IVAN_ALB,
    PORCENTAJE_IVAR_ALB, PORCENTAJE_IVAS_ALB, PORCENTAJE_IVAE_ALB,
    FORMA_PAGO_ALB, CONTADOR_LINEAS_ALB,
    INSTANTE_ALTA, USUARIO_ALTA, USUARIO_MODIF)
  SELECT v_numero, v_serie, CURRENT_DATE(), 'ABIERTO',
         p_NUMERO_PED, p_SERIE_PED,
         P.CODIGO_EMP_PED, P.CODIGO_ALM_PED,
         P.RAZON_SOCIAL_EMPRESA_PED, P.NIF_EMPRESA_PED,
         P.MOVIL_EMPRESA_PED, P.EMAIL_EMPRESA_PED,
         P.DIRECCION1_EMPRESA_PED, P.DIRECCION2_EMPRESA_PED,
         P.POBLACION_EMPRESA_PED, P.PROVINCIA_EMPRESA_PED,
         P.CODIGO_PAI_EMPRESA_PED, P.NOMBRE_PAI_EMPRESA_PED,
         P.CODIGO_POSTAL_EMPRESA_PED, P.GRUPO_ZONA_IVA_EMPRESA_PED,
         P.CODIGO_CLI_PED, P.RAZON_SOCIAL_CLIENTE_FISCAL_PED,
         P.NIF_CLIENTE_PED, P.MOVIL_CLIENTE_FISCAL_PED,
         P.EMAIL_CLIENTE_PED, P.DIRECCION1_CLIENTE_FISCAL_PED,
         P.DIRECCION2_CLIENTE_FISCAL_PED,
         P.POBLACION_CLIENTE_FISCAL_PED,
         P.PROVINCIA_CLIENTE_FISCAL_PED,
         P.CODIGO_POSTAL_CLIENTE_FISCAL_PED,
         P.CODIGO_PAI_CLIENTE_FISCAL_PED,
         P.NOMBRE_PAI_CLIENTE_FISCAL_PED,
         P.NOMBRE_CLI_ENVIO_PED, P.MOVIL_CLIENTE_ENVIO_PED,
         P.DIRECCION1_CLIENTE_ENVIO_PED,
         P.DIRECCION2_CLIENTE_ENVIO_PED,
         P.POBLACION_CLIENTE_ENVIO_PED,
         P.PROVINCIA_CLIENTE_ENVIO_PED,
         P.CODIGO_POSTAL_CLIENTE_ENVIO_PED,
         P.CODIGO_PAI_CLIENTE_ENVIO_PED,
         P.NOMBRE_PAI_CLIENTE_ENVIO_PED,
         P.TRANSPORTISTAPS_PED, P.CODIGO_IVA_PED,
         P.ESIVA_RECARGO_CLIENTE_PED, P.ESIVA_EXENTO_CLIENTE_PED,
         P.ESINTRACOMUNITARIO_CLIENTE_PED,
         P.TARIFA_ARTICULO_CLIENTE_PED,
         P.ESIMP_INCL_TARIFA_CLIENTE_PED, P.PORCENTAJE_IVAN_PED,
         P.PORCENTAJE_IVAR_PED, P.PORCENTAJE_IVAS_PED,
         P.PORCENTAJE_IVAE_PED, P.FORMA_PAGO_PED, '0',
         NOW(), p_USUARIO, p_USUARIO
    FROM fza_pedidos P
   WHERE P.NUMERO_PED = p_NUMERO_PED
     AND P.SERIE_PED = p_SERIE_PED;
  SET p_NUMERO_ALB = v_numero;
  SET p_SERIE_ALB = v_serie;
END//

DELIMITER ;

DROP PROCEDURE IF EXISTS PRC_PED_CREAR_ALBARAN_LINEA;

DELIMITER //

CREATE PROCEDURE PRC_PED_CREAR_ALBARAN_LINEA(
  IN p_NUMERO_ALB varchar(20),
  IN p_SERIE_ALB varchar(20),
  IN p_NUMERO_PED varchar(20),
  IN p_SERIE_PED varchar(20),
  IN p_LINEA_PED varchar(4),
  IN p_CANTIDAD decimal(19,6),
  IN p_CODIGO_ALM varchar(10),
  IN p_USUARIO varchar(100))
PRC: BEGIN
  DECLARE v_linea varchar(4);
  DECLARE v_pedida decimal(19,6) DEFAULT 0;
  DECLARE v_albaranada decimal(19,6) DEFAULT 0;
  DECLARE v_objetivo decimal(19,6) DEFAULT 0;
  DECLARE v_pendiente decimal(19,6) DEFAULT 0;
  DECLARE v_cantidad decimal(19,6) DEFAULT 0;
  SELECT IFNULL(CANTIDAD_PEDLIN, 0)
    INTO v_pedida
    FROM fza_pedidos_lineas
   WHERE NUMERO_PED_PEDLIN = p_NUMERO_PED
     AND SERIE_PED_PEDLIN = p_SERIE_PED
     AND LINEA_PEDLIN = p_LINEA_PED;
  SELECT IFNULL(SUM(CANTIDAD_ALBLIN), 0)
    INTO v_albaranada
    FROM fza_albaranes_lineas
   WHERE NUMERO_PED_ALBLIN = p_NUMERO_PED
     AND SERIE_PED_ALBLIN = p_SERIE_PED
     AND LINEA_PED_ALBLIN = p_LINEA_PED;
  SET v_objetivo = LEAST(IFNULL(p_CANTIDAD, 0), v_pedida);
  SET v_pendiente = v_pedida - v_albaranada;
  SET v_cantidad = v_objetivo - v_albaranada;
  IF v_pedida <= 0 OR v_pendiente <= 0 OR v_cantidad <= 0 THEN
    LEAVE PRC;
  END IF;
  IF v_cantidad > v_pendiente THEN
    SET v_cantidad = v_pendiente;
  END IF;
  UPDATE fza_albaranes
     SET CONTADOR_LINEAS_ALB = LPAD(LAST_INSERT_ID(
           IFNULL(CAST(NULLIF(CONTADOR_LINEAS_ALB, '')
           AS UNSIGNED), 0) + 10), 8, '0')
   WHERE NUMERO_ALB = p_NUMERO_ALB
     AND SERIE_ALB = p_SERIE_ALB;
  IF ROW_COUNT() = 0 THEN
    LEAVE PRC;
  END IF;
  SET v_linea = LPAD(LAST_INSERT_ID(), 4, '0');
  INSERT INTO fza_albaranes_lineas (
    NUMERO_ALB_ALBLIN, SERIE_ALB_ALBLIN, LINEA_ALBLIN,
    NUMERO_PED_ALBLIN, SERIE_PED_ALBLIN, LINEA_PED_ALBLIN,
    CODIGO_ART_ALBLIN, CODIGO_UNIDAD_ALBLIN,
    CODIGO_FAM_ALBLIN, NOMBRE_FAM_ALBLIN,
    DESCRIPCION_ARTICULO_ALBLIN, TIPO_CANTIDAD_ARTICULO_ALBLIN,
    CANTIDAD_ALBLIN, CODIGO_TAR_ALBLIN, ESIMP_INCL_TARIFA_ALBLIN,
    TIPO_IVA_ARTICULO_ALBLIN, PORCENTAJE_IVA_ALBLIN,
    PRECIO_VENTA_SIVA_ARTICULO_ALBLIN,
    PRECIO_VENTA_CIVA_ARTICULO_ALBLIN, TOTAL_ALBLIN,
    CODIGO_ALMACEN_ALBLIN, INSTANTE_ALTA, USUARIO_ALTA,
    USUARIO_MODIF)
  SELECT p_NUMERO_ALB, p_SERIE_ALB, v_linea,
         p_NUMERO_PED, p_SERIE_PED, p_LINEA_PED,
         PL.CODIGO_ART_PEDLIN,
         COALESCE(NULLIF(PL.CODIGOPRODPS_PEDLIN, ''),
                  NULLIF(PL.CODIGO_UNIDAD_PEDLIN, ''),
                  PL.CODIGO_ART_PEDLIN),
         PL.CODIGO_FAM_PEDLIN, PL.NOMBRE_FAM_PEDLIN,
         PL.DESCRIPCION_ARTICULO_PEDLIN,
         PL.TIPO_CANTIDAD_ARTICULO_PEDLIN,
         v_cantidad, PL.CODIGO_TAR_PEDLIN,
         PL.ESIMP_INCL_TARIFA_PEDLIN,
         PL.TIPO_IVA_ARTICULO_PEDLIN, PL.PORCENTAJE_IVA_PEDLIN,
         PL.PRECIO_VENTA_SIVA_ARTICULO_PEDLIN,
         PL.PRECIO_VENTA_CIVA_ARTICULO_PEDLIN,
         v_cantidad * PL.PRECIO_VENTA_SIVA_ARTICULO_PEDLIN,
         COALESCE(NULLIF(p_CODIGO_ALM, ''),
                  PL.CODIGO_ALMACEN_PEDLIN),
         NOW(), p_USUARIO, p_USUARIO
    FROM fza_pedidos_lineas PL
   WHERE PL.NUMERO_PED_PEDLIN = p_NUMERO_PED
     AND PL.SERIE_PED_PEDLIN = p_SERIE_PED
     AND PL.LINEA_PEDLIN = p_LINEA_PED;
  UPDATE fza_pedidos_lineas
     SET CANTIDAD_ENTREGADA_PEDLIN = v_albaranada + v_cantidad,
         CANTIDAD_PENDIENTE_PEDLIN =
           GREATEST(CANTIDAD_PEDLIN -
                    (v_albaranada + v_cantidad), 0),
         ESENTREGADA_PEDLIN = CASE
           WHEN CANTIDAD_PEDLIN <= v_albaranada + v_cantidad
           THEN 'S' ELSE 'N' END,
         INSTANTE_MODIF = NOW(),
         USUARIO_MODIF = p_USUARIO
   WHERE NUMERO_PED_PEDLIN = p_NUMERO_PED
     AND SERIE_PED_PEDLIN = p_SERIE_PED
     AND LINEA_PEDLIN = p_LINEA_PED;
END//

DELIMITER ;
