-- Pruebas estructurales de la migración de instantes efectivos de stock.
DROP PROCEDURE IF EXISTS PRC_PRUEBA_DOCUMENTOS_INSTANTE_MOVIMIENTO;
DELIMITER ;;
CREATE PROCEDURE PRC_PRUEBA_DOCUMENTOS_INSTANTE_MOVIMIENTO()
BEGIN
  DECLARE v_ERRORES int DEFAULT 0;
  SELECT COUNT(*)
    INTO v_ERRORES
    FROM INFORMATION_SCHEMA.COLUMNS
   WHERE TABLE_SCHEMA = DATABASE()
     AND ((TABLE_NAME = 'fza_albaranes'
           AND COLUMN_NAME = 'INSTANTE_MOVIMIENTO_ALB'
           AND DATA_TYPE = 'datetime')
       OR (TABLE_NAME = 'fza_albaranes_compra'
           AND COLUMN_NAME = 'INSTANTE_MOVIMIENTO_ALBC'
           AND DATA_TYPE = 'datetime')
       OR (TABLE_NAME = 'fza_devoluciones_compra'
           AND COLUMN_NAME = 'INSTANTE_MOVIMIENTO_DEVC'
           AND DATA_TYPE = 'datetime'));
  IF v_ERRORES <> 3 THEN
    SIGNAL SQLSTATE '45000'
      SET MESSAGE_TEXT = 'Faltan columnas datetime de instante de stock';
  END IF;
  SELECT COUNT(*)
    INTO v_ERRORES
    FROM fza_albaranes
   WHERE FECHA_ALB IS NOT NULL
     AND INSTANTE_MOVIMIENTO_ALB IS NULL;
  IF v_ERRORES <> 0 THEN
    SIGNAL SQLSTATE '45000'
      SET MESSAGE_TEXT = 'Hay albaranes de venta sin instante de stock';
  END IF;
  SELECT COUNT(*)
    INTO v_ERRORES
    FROM fza_albaranes_compra
   WHERE FECHA_ALBC IS NOT NULL
     AND INSTANTE_MOVIMIENTO_ALBC IS NULL;
  IF v_ERRORES <> 0 THEN
    SIGNAL SQLSTATE '45000'
      SET MESSAGE_TEXT = 'Hay albaranes de compra sin instante de stock';
  END IF;
  SELECT COUNT(*)
    INTO v_ERRORES
    FROM fza_devoluciones_compra
   WHERE FECHA_DEVC IS NOT NULL
     AND INSTANTE_MOVIMIENTO_DEVC IS NULL;
  IF v_ERRORES <> 0 THEN
    SIGNAL SQLSTATE '45000'
      SET MESSAGE_TEXT = 'Hay devoluciones sin instante de stock';
  END IF;
  SELECT 'OK instantes efectivos de stock' AS RESULTADO;
END;;
DELIMITER ;
CALL PRC_PRUEBA_DOCUMENTOS_INSTANTE_MOVIMIENTO();
DROP PROCEDURE IF EXISTS PRC_PRUEBA_DOCUMENTOS_INSTANTE_MOVIMIENTO;
