-- =============================================================================
-- BBDD central del servicio de errores de Factuzam
-- =============================================================================
-- Este esquema pertenece al webservice, no a la BBDD operativa del cliente.
-- Por eso las tablas no usan el prefijo fza_ ni entran en el normalizador.
-- Idempotente: las cuatro tablas se pueden crear repetidamente.
-- =============================================================================
CREATE TABLE IF NOT EXISTS soporte_errores (
  ID_ERROR bigint unsigned NOT NULL AUTO_INCREMENT,
  REFERENCIA_ERROR varchar(40) NOT NULL,
  TOKEN_SEGUIMIENTO_HASH char(64) NOT NULL,
  REFERENCIA_CLIENTE varchar(120) NULL DEFAULT NULL,
  APLICACION varchar(80) NOT NULL,
  VERSION_APLICACION varchar(40) NOT NULL,
  USUARIO_CLIENTE varchar(100) NULL DEFAULT NULL,
  GRUPO_CLIENTE varchar(100) NULL DEFAULT NULL,
  EMPRESA_CLIENTE varchar(100) NULL DEFAULT NULL,
  ALMACEN_CLIENTE varchar(100) NULL DEFAULT NULL,
  CAJA_CLIENTE varchar(100) NULL DEFAULT NULL,
  EQUIPO_CLIENTE varchar(255) NULL DEFAULT NULL,
  MODO_LICENCIA varchar(20) NOT NULL DEFAULT 'DEMO',
  ESTADO_LICENCIA varchar(30) NOT NULL DEFAULT 'DESCONOCIDA',
  EMAIL_CONTACTO varchar(254) NOT NULL,
  TELEFONO_CONTACTO varchar(50) NOT NULL,
  DESCRIPCION_CLIENTE text NULL DEFAULT NULL,
  CLASE_ERROR varchar(255) NOT NULL,
  MENSAJE_ERROR text NOT NULL,
  DETALLE_ERROR mediumtext NOT NULL,
  ESLOG_SQL varchar(1) NOT NULL DEFAULT 'N',
  ESLOG_RENDIMIENTO varchar(1) NOT NULL DEFAULT 'N',
  ESLOG_AVANZADO varchar(1) NOT NULL DEFAULT 'N',
  ESLOG_COMPLETO varchar(1) NOT NULL DEFAULT 'N',
  ESTADO_ERROR varchar(30) NOT NULL DEFAULT 'NUEVO',
  IP_ORIGEN varchar(45) NULL DEFAULT NULL,
  USER_AGENT varchar(500) NULL DEFAULT NULL,
  INSTANTE_ALTA datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INSTANTE_MODIF datetime NOT NULL DEFAULT CURRENT_TIMESTAMP
    ON UPDATE CURRENT_TIMESTAMP,
  USUARIO_ALTA varchar(100) NOT NULL DEFAULT 'CLIENTE',
  USUARIO_MODIF varchar(100) NOT NULL DEFAULT 'CLIENTE',
  PRIMARY KEY (ID_ERROR),
  UNIQUE KEY UQ_SERROR_REFERENCIA (REFERENCIA_ERROR),
  UNIQUE KEY UQ_SERROR_TOKEN (TOKEN_SEGUIMIENTO_HASH),
  KEY IDX_SERROR_ESTADO_INSTANTE (ESTADO_ERROR, INSTANTE_ALTA),
  KEY IDX_SERROR_CLIENTE (REFERENCIA_CLIENTE),
  KEY IDX_SERROR_IP_INSTANTE (IP_ORIGEN, INSTANTE_ALTA)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS soporte_error_adjuntos (
  ID_ADJUNTO bigint unsigned NOT NULL AUTO_INCREMENT,
  ID_ERROR bigint unsigned NOT NULL,
  TIPO_ADJUNTO varchar(20) NOT NULL,
  NOMBRE_ORIGINAL varchar(255) NOT NULL,
  RUTA_PRIVADA varchar(500) NOT NULL,
  TIPO_MIME varchar(100) NOT NULL,
  TAMANO_BYTES bigint unsigned NOT NULL,
  SHA256_ADJUNTO char(64) NOT NULL,
  INSTANTE_ALTA datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INSTANTE_MODIF datetime NOT NULL DEFAULT CURRENT_TIMESTAMP
    ON UPDATE CURRENT_TIMESTAMP,
  USUARIO_ALTA varchar(100) NOT NULL DEFAULT 'CLIENTE',
  USUARIO_MODIF varchar(100) NOT NULL DEFAULT 'CLIENTE',
  PRIMARY KEY (ID_ADJUNTO),
  KEY IDX_SEADJ_ERROR (ID_ERROR)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS soporte_error_comunicaciones (
  ID_COMUNICACION bigint unsigned NOT NULL AUTO_INCREMENT,
  ID_ERROR bigint unsigned NOT NULL,
  ORIGEN_COMUNICACION varchar(20) NOT NULL,
  MENSAJE_COMUNICACION text NOT NULL,
  ESEMAIL_ENVIADO varchar(1) NOT NULL DEFAULT 'N',
  EMAIL_DESTINO varchar(254) NULL DEFAULT NULL,
  INSTANTE_ALTA datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INSTANTE_MODIF datetime NOT NULL DEFAULT CURRENT_TIMESTAMP
    ON UPDATE CURRENT_TIMESTAMP,
  USUARIO_ALTA varchar(100) NOT NULL,
  USUARIO_MODIF varchar(100) NOT NULL,
  PRIMARY KEY (ID_COMUNICACION),
  KEY IDX_SECOM_ERROR_INSTANTE (ID_ERROR, INSTANTE_ALTA)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS soporte_error_estados (
  ID_ESTADO bigint unsigned NOT NULL AUTO_INCREMENT,
  ID_ERROR bigint unsigned NOT NULL,
  ESTADO_ANTERIOR varchar(30) NULL DEFAULT NULL,
  ESTADO_NUEVO varchar(30) NOT NULL,
  OBSERVACIONES_ESTADO varchar(500) NULL DEFAULT NULL,
  INSTANTE_ALTA datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INSTANTE_MODIF datetime NOT NULL DEFAULT CURRENT_TIMESTAMP
    ON UPDATE CURRENT_TIMESTAMP,
  USUARIO_ALTA varchar(100) NOT NULL,
  USUARIO_MODIF varchar(100) NOT NULL,
  PRIMARY KEY (ID_ESTADO),
  KEY IDX_SEEST_ERROR_INSTANTE (ID_ERROR, INSTANTE_ALTA)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
