-- =============================================================================
-- Sesiones de cambios de tarifa
-- =============================================================================
-- Permite preparar cambios de precio en memoria de trabajo, revisar lineas
-- calculadas y aplicar explicitamente a fza_articulos_tarifas.
--
-- Idempotente:
--   - CREATE TABLE IF NOT EXISTS para cabecera y lineas.
--   - Indices comprobados en INFORMATION_SCHEMA.STATISTICS.
--   - Registro de pantalla con ON DUPLICATE KEY UPDATE.
--
-- NO toca factuzam_original.sql.
-- =============================================================================

CREATE TABLE IF NOT EXISTS `fza_tarifas_cambios` (
  `CODIGO_TARC` int(11) NOT NULL AUTO_INCREMENT,
  `NOMBRE_TARC` varchar(100) NOT NULL,
  `FECHA_TARC` date NOT NULL,
  `ESTADO_TARC` varchar(20) NOT NULL DEFAULT 'BORRADOR',
  `CODIGO_TAR_ORIGEN_TARC` varchar(10) NULL DEFAULT NULL,
  `CODIGO_TAR_DESTINO_TARC` varchar(10) NOT NULL,
  `CAMPO_ORIGEN_TARC` varchar(30) NOT NULL DEFAULT 'PRECIO_ORIGEN',
  `CAMPO_DESTINO_TARC` varchar(30) NOT NULL DEFAULT 'AMBOS',
  `TIPO_APLICACION_TARC` varchar(30) NOT NULL DEFAULT 'COPIAR',
  `VALOR_APLICACION_TARC` decimal(19,6) NOT NULL DEFAULT 0,
  `VALOR_REDONDEO_TARC` decimal(19,6) NOT NULL DEFAULT 0.01,
  `VALOR_MENOS_AJUSTE_TARC` decimal(19,6) NOT NULL DEFAULT 0,
  `ESREDONDEAR_ARRIBA_TARC` varchar(1) NOT NULL DEFAULT 'S',
  `FECHA_DESDE_TARC` date NULL DEFAULT NULL,
  `FECHA_HASTA_TARC` date NULL DEFAULT NULL,
  `INSTANTE_APLICACION_TARC` datetime NULL DEFAULT NULL,
  `USUARIO_APLICACION_TARC` varchar(100) NULL DEFAULT NULL,
  `NOTAS_TARC` varchar(500) NULL DEFAULT NULL,
  `INSTANTE_ALTA` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `USUARIO_ALTA` varchar(100) NOT NULL,
  `INSTANTE_MODIF` datetime NULL DEFAULT NULL,
  `USUARIO_MODIF` varchar(100) NULL DEFAULT NULL,
  PRIMARY KEY (`CODIGO_TARC`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_spanish_ci;

CREATE TABLE IF NOT EXISTS `fza_tarifas_cambios_lineas` (
  `ID_TARCLIN` int(11) NOT NULL AUTO_INCREMENT,
  `CODIGO_TARC_TARCLIN` int(11) NOT NULL,
  `CODIGO_ART_TARCLIN` varchar(20) NOT NULL,
  `CODIGO_UNIDAD_SKU_TARCLIN` varchar(50) NOT NULL DEFAULT '',
  `CODIGO_TAR_ORIGEN_TARCLIN` varchar(10) NULL DEFAULT NULL,
  `CODIGO_TAR_DESTINO_TARCLIN` varchar(10) NOT NULL,
  `PRECIO_ORIGEN_TARCLIN` decimal(19,6) NULL DEFAULT NULL,
  `PRECIO_COSTE_TARCLIN` decimal(19,6) NULL DEFAULT NULL,
  `PRECIO_SALIDA_ACTUAL_TARCLIN` decimal(19,6) NULL DEFAULT NULL,
  `PRECIO_FINAL_ACTUAL_TARCLIN` decimal(19,6) NULL DEFAULT NULL,
  `PRECIO_DTO_ACTUAL_TARCLIN` decimal(19,6) NULL DEFAULT NULL,
  `PORCENTAJE_DTO_ACTUAL_TARCLIN` decimal(19,6) NULL DEFAULT NULL,
  `PRECIO_NUEVO_TARCLIN` decimal(19,6) NULL DEFAULT NULL,
  `PRECIO_FINAL_NUEVO_TARCLIN` decimal(19,6) NULL DEFAULT NULL,
  `PRECIO_DTO_NUEVO_TARCLIN` decimal(19,6) NULL DEFAULT NULL,
  `PORCENTAJE_DTO_NUEVO_TARCLIN` decimal(19,6) NULL DEFAULT NULL,
  `ESAPLICAR_TARCLIN` varchar(1) NOT NULL DEFAULT 'S',
  `ESTADO_TARCLIN` varchar(20) NOT NULL DEFAULT 'PENDIENTE',
  `MENSAJE_TARCLIN` varchar(300) NULL DEFAULT NULL,
  `CODIGO_UNICO_ARTTAR_TARCLIN` int(11) NULL DEFAULT NULL,
  `INSTANTE_APLICACION_TARCLIN` datetime NULL DEFAULT NULL,
  `INSTANTE_ALTA` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `USUARIO_ALTA` varchar(100) NOT NULL,
  `INSTANTE_MODIF` datetime NULL DEFAULT NULL,
  `USUARIO_MODIF` varchar(100) NULL DEFAULT NULL,
  PRIMARY KEY (`ID_TARCLIN`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_spanish_ci;

SET @idx_exists := (
  SELECT COUNT(*)
    FROM INFORMATION_SCHEMA.STATISTICS
   WHERE TABLE_SCHEMA = DATABASE()
     AND TABLE_NAME = 'fza_tarifas_cambios_lineas'
     AND INDEX_NAME = 'UQ_TARCLIN_TARC_ART_SKU'
);
SET @ddl := IF(@idx_exists = 0,
  'ALTER TABLE `fza_tarifas_cambios_lineas`
     ADD UNIQUE INDEX `UQ_TARCLIN_TARC_ART_SKU`
       (`CODIGO_TARC_TARCLIN`, `CODIGO_ART_TARCLIN`,
        `CODIGO_UNIDAD_SKU_TARCLIN`)',
  'SELECT ''UQ_TARCLIN_TARC_ART_SKU ya existe'' AS info'
);
PREPARE stmt FROM @ddl;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @idx_exists := (
  SELECT COUNT(*)
    FROM INFORMATION_SCHEMA.STATISTICS
   WHERE TABLE_SCHEMA = DATABASE()
     AND TABLE_NAME = 'fza_tarifas_cambios_lineas'
     AND INDEX_NAME = 'IDX_TARCLIN_TAR_DEST'
);
SET @ddl := IF(@idx_exists = 0,
  'ALTER TABLE `fza_tarifas_cambios_lineas`
     ADD INDEX `IDX_TARCLIN_TAR_DEST`
       (`CODIGO_TAR_DESTINO_TARCLIN`)',
  'SELECT ''IDX_TARCLIN_TAR_DEST ya existe'' AS info'
);
PREPARE stmt FROM @ddl;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

INSERT INTO fza_winforms
  (CALL_WINF, CAPTION_WINF, MENUITEM_WINF, UNITF_WINF,
   SHORTCUT_WINF, DATAMODULE_WINF, NUM_VENTANAS_WINF)
VALUES
  ('TarifasCambios',
   'Sesiones cambios tarifa',
   '',
   'inMtoTarifasCambios.TfrmMtoTarifasCambios',
   '',
   'UniDataTarifasCambios.TdmTarifasCambios',
   5)
ON DUPLICATE KEY UPDATE
  CAPTION_WINF      = VALUES(CAPTION_WINF),
  MENUITEM_WINF     = VALUES(MENUITEM_WINF),
  UNITF_WINF        = VALUES(UNITF_WINF),
  SHORTCUT_WINF     = VALUES(SHORTCUT_WINF),
  DATAMODULE_WINF   = VALUES(DATAMODULE_WINF),
  NUM_VENTANAS_WINF = VALUES(NUM_VENTANAS_WINF);
