-- Catálogo de textos españoles extraídos de los DFM.
-- Generado por generar_traducciones_dfm.ps1.
INSERT INTO `fza_traducciones` (
  `CLAVE_TRAD`, `IDIOMA_TRAD`, `TEXTO_TRAD`, `CONTEXTO_TRAD`,
  `ESACTIVO_TRAD`, `INSTANTE_ALTA`, `USUARIO_ALTA`
) VALUES
  ('inMtoVerifactuCola.TfrmMtoVerifactuCola.Caption',
   'es-ES',
   'Verifactu - Cola de Envíos',
   'src/verifactu/inMtoVerifactuCola.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoVerifactuCola.TfrmMtoVerifactuCola.cxGrdDBTabPrinID_VFCOLA.Caption',
   'es-ES',
   'Id',
   'src/verifactu/inMtoVerifactuCola.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoVerifactuCola.TfrmMtoVerifactuCola.cxGrdDBTabPrinSERIE_FAC_VFCOLA',
     '.Caption'
   ),
   'es-ES',
   'Serie',
   'src/verifactu/inMtoVerifactuCola.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoVerifactuCola.TfrmMtoVerifactuCola.cxGrdDBTabPrinNUMERO_FAC_VFCOL',
     'A.Caption'
   ),
   'es-ES',
   'Número',
   'src/verifactu/inMtoVerifactuCola.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoVerifactuCola.TfrmMtoVerifactuCola.cxGrdDBTabPrinTIPO_OPERACION_V',
     'FCOLA.Caption'
   ),
   'es-ES',
   'Operación',
   'src/verifactu/inMtoVerifactuCola.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoVerifactuCola.TfrmMtoVerifactuCola.cxGrdDBTabPrinESTADO_VFCOLA.Ca',
     'ption'
   ),
   'es-ES',
   'Estado',
   'src/verifactu/inMtoVerifactuCola.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoVerifactuCola.TfrmMtoVerifactuCola.cxGrdDBTabPrinCONTADOR_INTENTO',
     'S_VFCOLA.Caption'
   ),
   'es-ES',
   'Intentos',
   'src/verifactu/inMtoVerifactuCola.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoVerifactuCola.TfrmMtoVerifactuCola.cxGrdDBTabPrinINSTANTE_PROXIMO',
     '_INTENTO_VFCOLA.Caption'
   ),
   'es-ES',
   'Próximo intento',
   'src/verifactu/inMtoVerifactuCola.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoVerifactuCola.TfrmMtoVerifactuCola.cxGrdDBTabPrinINSTANTE_ENVIO_V',
     'FCOLA.Caption'
   ),
   'es-ES',
   'Enviada',
   'src/verifactu/inMtoVerifactuCola.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoVerifactuCola.TfrmMtoVerifactuCola.cxGrdDBTabPrinMENSAJE_ERROR_VF',
     'COLA.Caption'
   ),
   'es-ES',
   'Mensaje de error',
   'src/verifactu/inMtoVerifactuCola.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoVerifactuCola.TfrmMtoVerifactuCola.cxGrdDBTabPrinINSTANTEALTA.Caption',
   'es-ES',
   'Encolada',
   'src/verifactu/inMtoVerifactuCola.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoVerifactuCola.TfrmMtoVerifactuCola.cxGrdDBTabPrinUSUARIOALTA.Caption',
   'es-ES',
   'Usuario alta',
   'src/verifactu/inMtoVerifactuCola.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoVerifactuCola.TfrmMtoVerifactuCola.cxGrdDBTabPrinINSTANTEMODIF.Ca',
     'ption'
   ),
   'es-ES',
   'Modificada',
   'src/verifactu/inMtoVerifactuCola.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoVerifactuCola.TfrmMtoVerifactuCola.cxGrdDBTabPrinUSUARIOMODIF.Caption',
   'es-ES',
   'Usuario modif.',
   'src/verifactu/inMtoVerifactuCola.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoVerifactuCola.TfrmMtoVerifactuCola.btnIrADocumento.Caption',
   'es-ES',
   'Ir a &Documento',
   'src/verifactu/inMtoVerifactuCola.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoVerifactuLog.TfrmMtoVerifactuLog.Caption',
   'es-ES',
   'Verifactu - Log',
   'src/verifactu/inMtoVerifactuLog.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoVerifactuLog.TfrmMtoVerifactuLog.cxGrdDBTabPrinID_LOG.Caption',
   'es-ES',
   'Id',
   'src/verifactu/inMtoVerifactuLog.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoVerifactuLog.TfrmMtoVerifactuLog.cxGrdDBTabPrinTIMESTAMP_LOG.Caption',
   'es-ES',
   'Fecha Hora',
   'src/verifactu/inMtoVerifactuLog.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoVerifactuLog.TfrmMtoVerifactuLog.cxGrdDBTabPrinTIPO_EVENTO_LOG.Ca',
     'ption'
   ),
   'es-ES',
   'Tipo',
   'src/verifactu/inMtoVerifactuLog.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoVerifactuLog.TfrmMtoVerifactuLog.cxGrdDBTabPrinDESCRIPCION_LOG.Ca',
     'ption'
   ),
   'es-ES',
   'Evento',
   'src/verifactu/inMtoVerifactuLog.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoVerifactuLog.TfrmMtoVerifactuLog.cxGrdDBTabPrinDATOS_ADICIONALES_',
     'LOG.Caption'
   ),
   'es-ES',
   'Datos adicionales',
   'src/verifactu/inMtoVerifactuLog.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoVerifactuLog.TfrmMtoVerifactuLog.cxGrdDBTabPrinSERIE_FAC_LOG.Caption',
   'es-ES',
   'Serie',
   'src/verifactu/inMtoVerifactuLog.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoVerifactuLog.TfrmMtoVerifactuLog.cxGrdDBTabPrinNUMERO_FAC_LOG.Caption',
   'es-ES',
   'Número',
   'src/verifactu/inMtoVerifactuLog.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoVerifactuLog.TfrmMtoVerifactuLog.cxGrdDBTabPrinUSUARIO_LOG.Caption',
   'es-ES',
   'Usuario',
   'src/verifactu/inMtoVerifactuLog.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoVerifactuLog.TfrmMtoVerifactuLog.cxGrdDBTabPrinVERSION_LOG.Caption',
   'es-ES',
   'Versión',
   'src/verifactu/inMtoVerifactuLog.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoVerifactuLog.TfrmMtoVerifactuLog.cxGrdDBTabPrinHASH_ANTERIOR_LOG.',
     'Caption'
   ),
   'es-ES',
   'Hash anterior',
   'src/verifactu/inMtoVerifactuLog.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoVerifactuLog.TfrmMtoVerifactuLog.cxGrdDBTabPrinHASH_PROPIO_LOG.Ca',
     'ption'
   ),
   'es-ES',
   'Hash propio',
   'src/verifactu/inMtoVerifactuLog.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoVerifactuLog.TfrmMtoVerifactuLog.cxGrdDBTabPrinFIRMA_DIGITAL_LOG.',
     'Caption'
   ),
   'es-ES',
   'Firma',
   'src/verifactu/inMtoVerifactuLog.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoVerifactuLog.TfrmMtoVerifactuLog.btnIrADocumento.Caption',
   'es-ES',
   'Ir a &Documento',
   'src/verifactu/inMtoVerifactuLog.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoVerifactuLog.TfrmMtoVerifactuLog.btnExportarNoVerifactu.Caption',
   'es-ES',
   'Exportar NO*VF',
   'src/verifactu/inMtoVerifactuLog.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoVerifactuLog.TfrmMtoVerifactuLog.btnVerificarNoVerifactu.Caption',
   'es-ES',
   'Verificar NO*VF',
   'src/verifactu/inMtoVerifactuLog.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema')
ON DUPLICATE KEY UPDATE
  `TEXTO_TRAD` = VALUES(`TEXTO_TRAD`),
  `CONTEXTO_TRAD` = VALUES(`CONTEXTO_TRAD`),
  `ESACTIVO_TRAD` = VALUES(`ESACTIVO_TRAD`),
  `INSTANTE_MODIF` = CURRENT_TIMESTAMP,
  `USUARIO_MODIF` = VALUES(`USUARIO_ALTA`);
