-- Catálogo de textos españoles extraídos de los DFM.
-- Generado por generar_traducciones_dfm.ps1.
INSERT INTO `fza_traducciones` (
  `CLAVE_TRAD`, `IDIOMA_TRAD`, `TEXTO_TRAD`, `CONTEXTO_TRAD`,
  `ESACTIVO_TRAD`, `INSTANTE_ALTA`, `USUARIO_ALTA`
) VALUES
  ('inMtoRemesasCompra.TfrmMtoRemesasCompra.Caption',
   'es-ES',
   'Remesas de Pago',
   'src/Forms/inMtoRemesasCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoRemesasCompra.TfrmMtoRemesasCompra.dbcGrdDBTabPrinNUMERO_REMC.Caption',
   'es-ES',
   'Número',
   'src/Forms/inMtoRemesasCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoRemesasCompra.TfrmMtoRemesasCompra.dbcGrdDBTabPrinSERIE_REMC.Caption',
   'es-ES',
   'Serie',
   'src/Forms/inMtoRemesasCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoRemesasCompra.TfrmMtoRemesasCompra.dbcGrdDBTabPrinFECHA_REMC.Caption',
   'es-ES',
   'Fecha',
   'src/Forms/inMtoRemesasCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoRemesasCompra.TfrmMtoRemesasCompra.dbcGrdDBTabPrinESTADO_REMC.Caption',
   'es-ES',
   'Estado',
   'src/Forms/inMtoRemesasCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoRemesasCompra.TfrmMtoRemesasCompra.dbcGrdDBTabPrinCODIGO_EMP_REMC',
     '.Caption'
   ),
   'es-ES',
   'Empresa',
   'src/Forms/inMtoRemesasCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoRemesasCompra.TfrmMtoRemesasCompra.dbcGrdDBTabPrinRAZON_SOCIAL_EM',
     'PRESA_VIEW_REMC.Caption'
   ),
   'es-ES',
   'Razón Social',
   'src/Forms/inMtoRemesasCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoRemesasCompra.TfrmMtoRemesasCompra.dbcGrdDBTabPrinCONTADOR_EFECTO',
     'S_REMC.Caption'
   ),
   'es-ES',
   'Nº efectos',
   'src/Forms/inMtoRemesasCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoRemesasCompra.TfrmMtoRemesasCompra.dbcGrdDBTabPrinTOTAL_REMC.Caption',
   'es-ES',
   'Total',
   'src/Forms/inMtoRemesasCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoRemesasCompra.TfrmMtoRemesasCompra.dbcGrdDBTabPrinTOTAL_CARGADO_R',
     'EMC.Caption'
   ),
   'es-ES',
   'Cargo realizado',
   'src/Forms/inMtoRemesasCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoRemesasCompra.TfrmMtoRemesasCompra.dbcGrdDBTabPrinTOTAL_PENDIENTE',
     '_REMC.Caption'
   ),
   'es-ES',
   'Pendiente',
   'src/Forms/inMtoRemesasCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoRemesasCompra.TfrmMtoRemesasCompra.dbcGrdDBTabPrinFECHA_CARGO_REM',
     'C.Caption'
   ),
   'es-ES',
   'F. cargo',
   'src/Forms/inMtoRemesasCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoRemesasCompra.TfrmMtoRemesasCompra.dbcGrdDBTabPrinIBAN_REMC.Caption',
   'es-ES',
   'IBAN',
   'src/Forms/inMtoRemesasCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoRemesasCompra.TfrmMtoRemesasCompra.lblNumero.Caption',
   'es-ES',
   'Número',
   'src/Forms/inMtoRemesasCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoRemesasCompra.TfrmMtoRemesasCompra.lblSerie.Caption',
   'es-ES',
   'Serie',
   'src/Forms/inMtoRemesasCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoRemesasCompra.TfrmMtoRemesasCompra.lblFecha.Caption',
   'es-ES',
   'Fecha',
   'src/Forms/inMtoRemesasCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoRemesasCompra.TfrmMtoRemesasCompra.lblEstado.Caption',
   'es-ES',
   'Estado',
   'src/Forms/inMtoRemesasCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoRemesasCompra.TfrmMtoRemesasCompra.lblEmpresa.Caption',
   'es-ES',
   'Empresa',
   'src/Forms/inMtoRemesasCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoRemesasCompra.TfrmMtoRemesasCompra.lblRazonSocial.Caption',
   'es-ES',
   'Razón social',
   'src/Forms/inMtoRemesasCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoRemesasCompra.TfrmMtoRemesasCompra.lblTotal.Caption',
   'es-ES',
   'Total',
   'src/Forms/inMtoRemesasCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoRemesasCompra.TfrmMtoRemesasCompra.lblContadorEfectos.Caption',
   'es-ES',
   'Efectos',
   'src/Forms/inMtoRemesasCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoRemesasCompra.TfrmMtoRemesasCompra.lblFechaCargo.Caption',
   'es-ES',
   'F. cargo',
   'src/Forms/inMtoRemesasCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoRemesasCompra.TfrmMtoRemesasCompra.lblIBAN.Caption',
   'es-ES',
   'IBAN',
   'src/Forms/inMtoRemesasCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoRemesasCompra.TfrmMtoRemesasCompra.lblCargoRealizado.Caption',
   'es-ES',
   'Cargo realizado',
   'src/Forms/inMtoRemesasCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoRemesasCompra.TfrmMtoRemesasCompra.lblPendienteCargo.Caption',
   'es-ES',
   'Pendiente',
   'src/Forms/inMtoRemesasCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoRemesasCompra.TfrmMtoRemesasCompra.lblBancoPago.Caption',
   'es-ES',
   'Banco pago',
   'src/Forms/inMtoRemesasCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoRemesasCompra.TfrmMtoRemesasCompra.lblObservaciones.Caption',
   'es-ES',
   'Observaciones',
   'src/Forms/inMtoRemesasCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoRemesasCompra.TfrmMtoRemesasCompra.lblEfectosRemesa.Caption',
   'es-ES',
   'Efectos asignados a la remesa',
   'src/Forms/inMtoRemesasCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoRemesasCompra.TfrmMtoRemesasCompra.tvEfectosRemesaNUMERO_FACC_EFE',
     'C.Caption'
   ),
   'es-ES',
   'Factura',
   'src/Forms/inMtoRemesasCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoRemesasCompra.TfrmMtoRemesasCompra.tvEfectosRemesaSERIE_FACC_EFEC',
     '.Caption'
   ),
   'es-ES',
   'Serie',
   'src/Forms/inMtoRemesasCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoRemesasCompra.TfrmMtoRemesasCompra.tvEfectosRemesaNUMERO_EFEC.Caption',
   'es-ES',
   'Efecto',
   'src/Forms/inMtoRemesasCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoRemesasCompra.TfrmMtoRemesasCompra.tvEfectosRemesaPROVEEDOR_VIEW_',
     'EFEC.Caption'
   ),
   'es-ES',
   'Proveedor',
   'src/Forms/inMtoRemesasCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoRemesasCompra.TfrmMtoRemesasCompra.tvEfectosRemesaDESCRIPCION_TEF',
     'E_VIEW_EFEC.Caption'
   ),
   'es-ES',
   'Tipo',
   'src/Forms/inMtoRemesasCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoRemesasCompra.TfrmMtoRemesasCompra.tvEfectosRemesaFECHA_VENCIMIEN',
     'TO_EFEC.Caption'
   ),
   'es-ES',
   'Vencimiento',
   'src/Forms/inMtoRemesasCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoRemesasCompra.TfrmMtoRemesasCompra.tvEfectosRemesaIMPORTE_EFEC.Ca',
     'ption'
   ),
   'es-ES',
   'Importe',
   'src/Forms/inMtoRemesasCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoRemesasCompra.TfrmMtoRemesasCompra.tvEfectosRemesaIMPORTE_PAGADO_',
     'EFEC.Caption'
   ),
   'es-ES',
   'Pagado',
   'src/Forms/inMtoRemesasCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoRemesasCompra.TfrmMtoRemesasCompra.tvEfectosRemesaIMPORTE_PENDIEN',
     'TE_EFEC.Caption'
   ),
   'es-ES',
   'Pendiente',
   'src/Forms/inMtoRemesasCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoRemesasCompra.TfrmMtoRemesasCompra.tvEfectosRemesaESTADO_EFEC.Caption',
   'es-ES',
   'Estado',
   'src/Forms/inMtoRemesasCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoRemesasCompra.TfrmMtoRemesasCompra.tvEfectosRemesaREFERENCIA_DOCU',
     'MENTO_EFEC.Caption'
   ),
   'es-ES',
   'Ref. doc.',
   'src/Forms/inMtoRemesasCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoRemesasCompra.TfrmMtoRemesasCompra.tvEfectosRemesaFECHA_PAGO_EFEC',
     '.Caption'
   ),
   'es-ES',
   'F. pago',
   'src/Forms/inMtoRemesasCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoRemesasCompra.TfrmMtoRemesasCompra.tvEfectosRemesaDOC_EXTERNO_EFE',
     'C.Caption'
   ),
   'es-ES',
   'Doc. proveedor',
   'src/Forms/inMtoRemesasCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoRemesasCompra.TfrmMtoRemesasCompra.btnAnadirEfecto.Caption',
   'es-ES',
   'Añadir efecto',
   'src/Forms/inMtoRemesasCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoRemesasCompra.TfrmMtoRemesasCompra.btnQuitarEfecto.Caption',
   'es-ES',
   'Quitar efecto',
   'src/Forms/inMtoRemesasCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoRemesasCompra.TfrmMtoRemesasCompra.btnPagarEfecto.Caption',
   'es-ES',
   'Conciliar efecto',
   'src/Forms/inMtoRemesasCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoRemesasCompra.TfrmMtoRemesasCompra.btnPagarRemesa.Caption',
   'es-ES',
   'Conciliar remesa',
   'src/Forms/inMtoRemesasCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoRemesasCompra.TfrmMtoRemesasCompra.btnAsignarBanco.Caption',
   'es-ES',
   'Asignar banco',
   'src/Forms/inMtoRemesasCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoRemesasCompra.TfrmMtoRemesasCompra.btnFechaCargo.Caption',
   'es-ES',
   'Fecha cargo',
   'src/Forms/inMtoRemesasCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoRemesasVenta.TfrmMtoRemesasVenta.Caption',
   'es-ES',
   'Remesas de Cobro',
   'src/Forms/inMtoRemesasVenta.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoRemesasVenta.TfrmMtoRemesasVenta.dbcGrdDBTabPrinNUMERO_REMV.Caption',
   'es-ES',
   'Número',
   'src/Forms/inMtoRemesasVenta.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoRemesasVenta.TfrmMtoRemesasVenta.dbcGrdDBTabPrinSERIE_REMV.Caption',
   'es-ES',
   'Serie',
   'src/Forms/inMtoRemesasVenta.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoRemesasVenta.TfrmMtoRemesasVenta.dbcGrdDBTabPrinFECHA_REMV.Caption',
   'es-ES',
   'Fecha',
   'src/Forms/inMtoRemesasVenta.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoRemesasVenta.TfrmMtoRemesasVenta.dbcGrdDBTabPrinESTADO_REMV.Caption',
   'es-ES',
   'Estado',
   'src/Forms/inMtoRemesasVenta.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoRemesasVenta.TfrmMtoRemesasVenta.dbcGrdDBTabPrinCODIGO_EMP_REMV.C',
     'aption'
   ),
   'es-ES',
   'Empresa',
   'src/Forms/inMtoRemesasVenta.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoRemesasVenta.TfrmMtoRemesasVenta.dbcGrdDBTabPrinRAZON_SOCIAL_EMPR',
     'ESA_VIEW_REMV.Caption'
   ),
   'es-ES',
   'Razón Social',
   'src/Forms/inMtoRemesasVenta.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoRemesasVenta.TfrmMtoRemesasVenta.dbcGrdDBTabPrinCONTADOR_EFECTOS_',
     'REMV.Caption'
   ),
   'es-ES',
   'Nº efectos',
   'src/Forms/inMtoRemesasVenta.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoRemesasVenta.TfrmMtoRemesasVenta.dbcGrdDBTabPrinTOTAL_REMV.Caption',
   'es-ES',
   'Total',
   'src/Forms/inMtoRemesasVenta.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoRemesasVenta.TfrmMtoRemesasVenta.dbcGrdDBTabPrinTOTAL_COBRADO_REM',
     'V.Caption'
   ),
   'es-ES',
   'Cobro realizado',
   'src/Forms/inMtoRemesasVenta.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoRemesasVenta.TfrmMtoRemesasVenta.dbcGrdDBTabPrinTOTAL_PENDIENTE_R',
     'EMV.Caption'
   ),
   'es-ES',
   'Pendiente',
   'src/Forms/inMtoRemesasVenta.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoRemesasVenta.TfrmMtoRemesasVenta.dbcGrdDBTabPrinFECHA_CARGO_REMV.',
     'Caption'
   ),
   'es-ES',
   'F. cobro',
   'src/Forms/inMtoRemesasVenta.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoRemesasVenta.TfrmMtoRemesasVenta.dbcGrdDBTabPrinIBAN_REMV.Caption',
   'es-ES',
   'IBAN',
   'src/Forms/inMtoRemesasVenta.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoRemesasVenta.TfrmMtoRemesasVenta.lblNumero.Caption',
   'es-ES',
   'Número',
   'src/Forms/inMtoRemesasVenta.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoRemesasVenta.TfrmMtoRemesasVenta.lblSerie.Caption',
   'es-ES',
   'Serie',
   'src/Forms/inMtoRemesasVenta.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoRemesasVenta.TfrmMtoRemesasVenta.lblFecha.Caption',
   'es-ES',
   'Fecha',
   'src/Forms/inMtoRemesasVenta.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoRemesasVenta.TfrmMtoRemesasVenta.lblEstado.Caption',
   'es-ES',
   'Estado',
   'src/Forms/inMtoRemesasVenta.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoRemesasVenta.TfrmMtoRemesasVenta.lblEmpresa.Caption',
   'es-ES',
   'Empresa',
   'src/Forms/inMtoRemesasVenta.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoRemesasVenta.TfrmMtoRemesasVenta.lblRazonSocial.Caption',
   'es-ES',
   'Razón social',
   'src/Forms/inMtoRemesasVenta.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoRemesasVenta.TfrmMtoRemesasVenta.lblTotal.Caption',
   'es-ES',
   'Total',
   'src/Forms/inMtoRemesasVenta.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoRemesasVenta.TfrmMtoRemesasVenta.lblContadorEfectos.Caption',
   'es-ES',
   'Efectos',
   'src/Forms/inMtoRemesasVenta.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoRemesasVenta.TfrmMtoRemesasVenta.lblFechaCobro.Caption',
   'es-ES',
   'F. cobro',
   'src/Forms/inMtoRemesasVenta.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoRemesasVenta.TfrmMtoRemesasVenta.lblIBAN.Caption',
   'es-ES',
   'IBAN',
   'src/Forms/inMtoRemesasVenta.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoRemesasVenta.TfrmMtoRemesasVenta.lblCobroRealizado.Caption',
   'es-ES',
   'Cobro realizado',
   'src/Forms/inMtoRemesasVenta.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoRemesasVenta.TfrmMtoRemesasVenta.lblPendienteCobro.Caption',
   'es-ES',
   'Pendiente',
   'src/Forms/inMtoRemesasVenta.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoRemesasVenta.TfrmMtoRemesasVenta.lblBancoCobro.Caption',
   'es-ES',
   'Banco cobro',
   'src/Forms/inMtoRemesasVenta.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoRemesasVenta.TfrmMtoRemesasVenta.lblObservaciones.Caption',
   'es-ES',
   'Observaciones',
   'src/Forms/inMtoRemesasVenta.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoRemesasVenta.TfrmMtoRemesasVenta.lblEfectosRemesa.Caption',
   'es-ES',
   'Efectos asignados a la remesa',
   'src/Forms/inMtoRemesasVenta.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoRemesasVenta.TfrmMtoRemesasVenta.tvEfectosRemesaNUMERO_FAC_EFV.Ca',
     'ption'
   ),
   'es-ES',
   'Factura',
   'src/Forms/inMtoRemesasVenta.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoRemesasVenta.TfrmMtoRemesasVenta.tvEfectosRemesaSERIE_FAC_EFV.Caption',
   'es-ES',
   'Serie',
   'src/Forms/inMtoRemesasVenta.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoRemesasVenta.TfrmMtoRemesasVenta.tvEfectosRemesaNUMERO_EFV.Caption',
   'es-ES',
   'Efecto',
   'src/Forms/inMtoRemesasVenta.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoRemesasVenta.TfrmMtoRemesasVenta.tvEfectosRemesaCLIENTE_VIEW_EFV.',
     'Caption'
   ),
   'es-ES',
   'Cliente',
   'src/Forms/inMtoRemesasVenta.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoRemesasVenta.TfrmMtoRemesasVenta.tvEfectosRemesaDESCRIPCION_TEFE_',
     'VIEW_EFV.Caption'
   ),
   'es-ES',
   'Tipo',
   'src/Forms/inMtoRemesasVenta.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoRemesasVenta.TfrmMtoRemesasVenta.tvEfectosRemesaFECHA_VENCIMIENTO',
     '_EFV.Caption'
   ),
   'es-ES',
   'Vencimiento',
   'src/Forms/inMtoRemesasVenta.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoRemesasVenta.TfrmMtoRemesasVenta.tvEfectosRemesaIMPORTE_EFV.Caption',
   'es-ES',
   'Importe',
   'src/Forms/inMtoRemesasVenta.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoRemesasVenta.TfrmMtoRemesasVenta.tvEfectosRemesaIMPORTE_COBRADO_E',
     'FV.Caption'
   ),
   'es-ES',
   'Cobrado',
   'src/Forms/inMtoRemesasVenta.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoRemesasVenta.TfrmMtoRemesasVenta.tvEfectosRemesaIMPORTE_PENDIENTE',
     '_EFV.Caption'
   ),
   'es-ES',
   'Pendiente',
   'src/Forms/inMtoRemesasVenta.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoRemesasVenta.TfrmMtoRemesasVenta.tvEfectosRemesaESTADO_EFV.Caption',
   'es-ES',
   'Estado',
   'src/Forms/inMtoRemesasVenta.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoRemesasVenta.TfrmMtoRemesasVenta.tvEfectosRemesaREFERENCIA_DOCUME',
     'NTO_EFV.Caption'
   ),
   'es-ES',
   'Ref. doc.',
   'src/Forms/inMtoRemesasVenta.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoRemesasVenta.TfrmMtoRemesasVenta.tvEfectosRemesaFECHA_COBRO_EFV.C',
     'aption'
   ),
   'es-ES',
   'F. cobro',
   'src/Forms/inMtoRemesasVenta.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoRemesasVenta.TfrmMtoRemesasVenta.tvEfectosRemesaDOC_EXTERNO_EFV.C',
     'aption'
   ),
   'es-ES',
   'Doc. cliente',
   'src/Forms/inMtoRemesasVenta.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoRemesasVenta.TfrmMtoRemesasVenta.btnAnadirEfecto.Caption',
   'es-ES',
   'Añadir efecto',
   'src/Forms/inMtoRemesasVenta.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoRemesasVenta.TfrmMtoRemesasVenta.btnQuitarEfecto.Caption',
   'es-ES',
   'Quitar efecto',
   'src/Forms/inMtoRemesasVenta.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoRemesasVenta.TfrmMtoRemesasVenta.btnCobrarEfecto.Caption',
   'es-ES',
   'Conciliar efecto',
   'src/Forms/inMtoRemesasVenta.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoRemesasVenta.TfrmMtoRemesasVenta.btnCobrarRemesa.Caption',
   'es-ES',
   'Conciliar remesa',
   'src/Forms/inMtoRemesasVenta.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoRemesasVenta.TfrmMtoRemesasVenta.btnAsignarBanco.Caption',
   'es-ES',
   'Asignar banco',
   'src/Forms/inMtoRemesasVenta.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoRemesasVenta.TfrmMtoRemesasVenta.btnFechaCobro.Caption',
   'es-ES',
   'Fecha cobro',
   'src/Forms/inMtoRemesasVenta.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoRemesasVenta.TfrmMtoRemesasVenta.btnGenerarSepa.Caption',
   'es-ES',
   'Generar SEPA',
   'src/Forms/inMtoRemesasVenta.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoStockConsulta.TfrmStockConsulta.Caption',
   'es-ES',
   'Consulta de stock (Ctrl+U)',
   'src/Forms/inMtoStockConsulta.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoStockConsulta.TfrmStockConsulta.btnOperacionesCaja.Hint',
   'es-ES',
   'Muestra las operaciones de caja de la talla seleccionada',
   'src/Forms/inMtoStockConsulta.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoStockConsulta.TfrmStockConsulta.btnOperacionesCaja.Caption',
   'es-ES',
   'Op de Caja',
   'src/Forms/inMtoStockConsulta.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoStockConsulta.TfrmStockConsulta.lblArt.Caption',
   'es-ES',
   'Artículo',
   'src/Forms/inMtoStockConsulta.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoStockConsulta.TfrmStockConsulta.lblLetreroTemp.Caption',
   'es-ES',
   ' ',
   'src/Forms/inMtoStockConsulta.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoStockConsulta.TfrmStockConsulta.lblEstado.Caption',
   'es-ES',
   'Estado del stock',
   'src/Forms/inMtoStockConsulta.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoStockConsulta.TfrmStockConsulta.tsColores.Caption',
   'es-ES',
   '1 Colores',
   'src/Forms/inMtoStockConsulta.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoStockConsulta.TfrmStockConsulta.lblColores.Caption',
   'es-ES',
   'Colores del artículo',
   'src/Forms/inMtoStockConsulta.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoStockConsulta.TfrmStockConsulta.tsAlmacenes.Caption',
   'es-ES',
   '2 Almacenes',
   'src/Forms/inMtoStockConsulta.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoStockConsulta.TfrmStockConsulta.lblAlmacenes.Caption',
   'es-ES',
   'Almacenes',
   'src/Forms/inMtoStockConsulta.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoStockConsulta.TfrmStockConsulta.tsPorAlmacen.Caption',
   'es-ES',
   '3 Por almacenes',
   'src/Forms/inMtoStockConsulta.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoStockConsulta.TfrmStockConsulta.tsPorColor.Caption',
   'es-ES',
   '4 Por colores',
   'src/Forms/inMtoStockConsulta.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoTarifas.TfrmMtoTarifas.Caption',
   'es-ES',
   'Tarifas',
   'src/Forms/inMtoTarifas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoTarifas.TfrmMtoTarifas.cxgrdbclmnGrdDBTabPrinCODIGO_TARIFA.Caption',
   'es-ES',
   'Código Tarifa',
   'src/Forms/inMtoTarifas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoTarifas.TfrmMtoTarifas.cxgrdbclmnGrdDBTabPrinNOMBRE_TARIFA.Caption',
   'es-ES',
   'Nombre Tarifa',
   'src/Forms/inMtoTarifas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoTarifas.TfrmMtoTarifas.cxgrdbclmnGrdDBTabPrinACTIVO_TARIFA.Caption',
   'es-ES',
   'Activa',
   'src/Forms/inMtoTarifas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoTarifas.TfrmMtoTarifas.cxgrdbclmnGrdDBTabPrinESIMP_INCL_TARIFA.Ca',
     'ption'
   ),
   'es-ES',
   'Impuestos incl.',
   'src/Forms/inMtoTarifas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoTarifas.TfrmMtoTarifas.lblCodigo.Caption',
   'es-ES',
   'Código',
   'src/Forms/inMtoTarifas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoTarifas.TfrmMtoTarifas.lblNombre.Caption',
   'es-ES',
   'Nombre',
   'src/Forms/inMtoTarifas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoTarifas.TfrmMtoTarifas.chkActivo.Caption',
   'es-ES',
   'Activo',
   'src/Forms/inMtoTarifas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoTarifas.TfrmMtoTarifas.cxdbchckbxACTIVO_TARIFA.Caption',
   'es-ES',
   'Impuestos incluídos en el precio final',
   'src/Forms/inMtoTarifas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoTarifas.TfrmMtoTarifas.tsArticulos.Caption',
   'es-ES',
   '&1_Artículos',
   'src/Forms/inMtoTarifas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoTarifas.TfrmMtoTarifas.btnIraArticulo.Caption',
   'es-ES',
   'Ir a Artículo',
   'src/Forms/inMtoTarifas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoTarifas.TfrmMtoTarifas.btnAddBlock.Caption',
   'es-ES',
   'Añadir Bloque',
   'src/Forms/inMtoTarifas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoTarifas.TfrmMtoTarifas.cxgrdbclmnArticulosACTIVO_TARIFA.Caption',
   'es-ES',
   'Precio Activo',
   'src/Forms/inMtoTarifas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoTarifas.TfrmMtoTarifas.cxgrdbclmnArticulosCODIGO_ARTICULO_TARIFA.',
     'Caption'
   ),
   'es-ES',
   'Código Artículo',
   'src/Forms/inMtoTarifas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoTarifas.TfrmMtoTarifas.tvArticulosCODIGO_UNICO_TARIFA_SKU.Caption',
   'es-ES',
   'SKU',
   'src/Forms/inMtoTarifas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoTarifas.TfrmMtoTarifas.cxgrdbclmnArticulosDESCRIPCION_ARTICULO.Ca',
     'ption'
   ),
   'es-ES',
   'Descripción Artículo',
   'src/Forms/inMtoTarifas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoTarifas.TfrmMtoTarifas.cxgrdbclmnArticulosCODIGO_FAMILIA_ARTICULO',
     '.Caption'
   ),
   'es-ES',
   'Código Familia',
   'src/Forms/inMtoTarifas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoTarifas.TfrmMtoTarifas.cxgrdbclmnArticulosDESCRIPCION_FAMILIA.Caption',
   'es-ES',
   'Descripción Familia',
   'src/Forms/inMtoTarifas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoTarifas.TfrmMtoTarifas.cxgrdbclmnArticulosCODIGO_PROVEEDOR.Caption',
   'es-ES',
   'Código Proveedor',
   'src/Forms/inMtoTarifas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoTarifas.TfrmMtoTarifas.cxgrdbclmnArticulosRAZONSOCIAL_PROVEEDOR.C',
     'aption'
   ),
   'es-ES',
   'Nombre Proveedor',
   'src/Forms/inMtoTarifas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoTarifas.TfrmMtoTarifas.cxgrdbclmnArticulosTIPOIVA_ARTICULO.Caption',
   'es-ES',
   'Tipo de IVA',
   'src/Forms/inMtoTarifas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoTarifas.TfrmMtoTarifas.cxgrdbclmnArticulosFECHA_DESDE_TARIFA.Caption',
   'es-ES',
   'Precio desde Fecha',
   'src/Forms/inMtoTarifas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoTarifas.TfrmMtoTarifas.cxgrdbclmnArticulosFECHA_HASTA_TARIFA.Caption',
   'es-ES',
   'Precio Hasta Fecha',
   'src/Forms/inMtoTarifas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoTarifas.TfrmMtoTarifas.cxgrdbclmnArticulosTIPO_CANTIDAD_ARTICULO.',
     'Caption'
   ),
   'es-ES',
   'Tipo Cantidad',
   'src/Forms/inMtoTarifas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoTarifas.TfrmMtoTarifas.cxgrdbclmnArticulosPRECIO_ULT_COMPRA.Caption',
   'es-ES',
   'Precio Última Compra',
   'src/Forms/inMtoTarifas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoTarifas.TfrmMtoTarifas.cxgrdbclmnArticulosFECHA_VALIDEZ.Caption',
   'es-ES',
   'Fecha Última Compra',
   'src/Forms/inMtoTarifas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoTarifas.TfrmMtoTarifas.cxgrdbclmnArticulosPRECIOFINAL.Caption',
   'es-ES',
   'Precio Salida',
   'src/Forms/inMtoTarifas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoTarifas.TfrmMtoTarifas.tvArticulosORIGEN_PRECIO.Caption',
   'es-ES',
   'Origen',
   'src/Forms/inMtoTarifas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoTarifas.TfrmMtoTarifas.tvArticulosPRECIOSALIDA_TARIFA.Caption',
   'es-ES',
   'Precio Salida',
   'src/Forms/inMtoTarifas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoTarifas.TfrmMtoTarifas.tvArticulosPORCEN_DTO_TARIFA.Caption',
   'es-ES',
   '% Dto',
   'src/Forms/inMtoTarifas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoTarifas.TfrmMtoTarifas.tvArticulosPRECIO_DTO_TARIFA.Caption',
   'es-ES',
   'Precio Dto',
   'src/Forms/inMtoTarifas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoTarifas.TfrmMtoTarifas.tvArticulosPRECIOFINAL_TARIFA.Caption',
   'es-ES',
   'Precio Final',
   'src/Forms/inMtoTarifas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoTarifas.TfrmMtoTarifas.tvArticulosTIPO_IVA_ARTICULO.Caption',
   'es-ES',
   'Tipo IVA',
   'src/Forms/inMtoTarifas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoTarifas.TfrmMtoTarifas.cxgrdbclmncxgrdbtblvwcxgrd1DBTableView1COD',
     'IGO_ARTICULO_LINEA.Caption'
   ),
   'es-ES',
   'Código Tratamiento',
   'src/Forms/inMtoTarifas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoTarifas.TfrmMtoTarifas.cxgrdbclmncxgrdbtblvwcxgrd1DBTableView1DES',
     'CRIPCION_ARTICULO_LINEA.Caption'
   ),
   'es-ES',
   'Descripción Tratamiento',
   'src/Forms/inMtoTarifas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoTarifas.TfrmMtoTarifas.cxgrdbclmncxgrdbtblvwcxgrd1DBTableView1CAN',
     'TIDAD_LINEA.Caption'
   ),
   'es-ES',
   'Cantidad',
   'src/Forms/inMtoTarifas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoTarifas.TfrmMtoTarifas.cxgrdbclmnLineasFacturacionPORCEN_IVA_FACT',
     'URA_LINEA.Caption'
   ),
   'es-ES',
   'Porcentaje IVA',
   'src/Forms/inMtoTarifas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoTarifas.TfrmMtoTarifas.cxgrdbclmncxgrdbtblvwcxgrd1DBTableView1PRE',
     'CIOVENTA_ARTICULO_LINEA.Caption'
   ),
   'es-ES',
   'Precio',
   'src/Forms/inMtoTarifas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoTarifas.TfrmMtoTarifas.cxgrdbclmncxgrdbtblvwcxgrd1DBTableView1SUM',
     '_TOTAL_LINEA.Caption'
   ),
   'es-ES',
   'Total',
   'src/Forms/inMtoTarifas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoTarifas.TfrmMtoTarifas.cxgrdbclmnLineasFacturacionFECHA_ENTREGA_F',
     'ACTURA_LINEA.Caption'
   ),
   'es-ES',
   'Fecha de Entrega',
   'src/Forms/inMtoTarifas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoTarifas.TfrmMtoTarifas.tsOtros.Caption',
   'es-ES',
   '&2_Otros',
   'src/Forms/inMtoTarifas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoTarifas.TfrmMtoTarifas.lblUsuarioAlta.Caption',
   'es-ES',
   'Usuario Alta',
   'src/Forms/inMtoTarifas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoTarifas.TfrmMtoTarifas.lblInstanteAlta.Caption',
   'es-ES',
   'Instante Alta',
   'src/Forms/inMtoTarifas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoTarifas.TfrmMtoTarifas.lblInstanteModif.Caption',
   'es-ES',
   'Instante Modificación',
   'src/Forms/inMtoTarifas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoTarifas.TfrmMtoTarifas.lblUsuarioModif.Caption',
   'es-ES',
   'Us. Últ. Modif.',
   'src/Forms/inMtoTarifas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoTarifas.TfrmMtoTarifas.lblDtoDesde.Caption',
   'es-ES',
   'Dto. desde',
   'src/Forms/inMtoTarifas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoTarifas.TfrmMtoTarifas.lblDtoHasta.Caption',
   'es-ES',
   'Dto. hasta',
   'src/Forms/inMtoTarifas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoTarifas.TfrmMtoTarifas.actArticulos.Caption',
   'es-ES',
   'Articulos',
   'src/Forms/inMtoTarifas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoTarifas.TfrmMtoTarifas.actFamilias.Caption',
   'es-ES',
   'Familias',
   'src/Forms/inMtoTarifas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoTarifas.TfrmMtoTarifas.actProveedores.Caption',
   'es-ES',
   'actProveedores',
   'src/Forms/inMtoTarifas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoTarifasCambios.TfrmMtoTarifasCambios.Caption',
   'es-ES',
   'Sesiones cambios tarifa',
   'src/Forms/inMtoTarifasCambios.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoUnidadesMedida.TfrmMtoUnidadesMedida.Caption',
   'es-ES',
   'Unidades de Medida',
   'src/Forms/inMtoUnidadesMedida.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoUnidadesMedida.TfrmMtoUnidadesMedida.dbcGrdDBTabPrinCODIGO_UNIMED',
     '.Caption'
   ),
   'es-ES',
   'Código',
   'src/Forms/inMtoUnidadesMedida.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoUnidadesMedida.TfrmMtoUnidadesMedida.dbcGrdDBTabPrinDESCRIPCION_U',
     'NIMED.Caption'
   ),
   'es-ES',
   'Descripción',
   'src/Forms/inMtoUnidadesMedida.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoUnidadesMedida.TfrmMtoUnidadesMedida.dbcGrdDBTabPrinDECIMALES_UNI',
     'MED.Caption'
   ),
   'es-ES',
   'Decimales',
   'src/Forms/inMtoUnidadesMedida.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoUnidadesMedida.TfrmMtoUnidadesMedida.dbcGrdDBTabPrinMAGNITUD_UNIM',
     'ED.Caption'
   ),
   'es-ES',
   'Magnitud',
   'src/Forms/inMtoUnidadesMedida.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoUnidadesMedida.TfrmMtoUnidadesMedida.dbcGrdDBTabPrinESBASE_UNIMED',
     '.Caption'
   ),
   'es-ES',
   'Es Base',
   'src/Forms/inMtoUnidadesMedida.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoUnidadesMedida.TfrmMtoUnidadesMedida.dbcGrdDBTabPrinFACTOR_BASE_U',
     'NIMED.Caption'
   ),
   'es-ES',
   'Factor a Base',
   'src/Forms/inMtoUnidadesMedida.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoUnidadesMedida.TfrmMtoUnidadesMedida.dbcGrdDBTabPrinORDEN_UNIMED.',
     'Caption'
   ),
   'es-ES',
   'Orden',
   'src/Forms/inMtoUnidadesMedida.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoUnidadesMedida.TfrmMtoUnidadesMedida.dbcGrdDBTabPrinESACTIVO_UNIM',
     'ED.Caption'
   ),
   'es-ES',
   'Activo',
   'src/Forms/inMtoUnidadesMedida.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoUsuarios.TfrmMtoUsuarios.Caption',
   'es-ES',
   'Usuarios',
   'src/Forms/inMtoUsuarios.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoUsuarios.TfrmMtoUsuarios.cxGrdDBTabPrinUSUARIO_USUARIO.Caption',
   'es-ES',
   'Nombre de Usuario',
   'src/Forms/inMtoUsuarios.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoUsuarios.TfrmMtoUsuarios.cxGrdDBTabPrinGRUPO_USUARIO.Caption',
   'es-ES',
   'Grupo',
   'src/Forms/inMtoUsuarios.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoUsuarios.TfrmMtoUsuarios.cxgrdbclmnGrdDBTabPrinESGRUPOADMINISTRAD',
     'OR_GRUPO.Caption'
   ),
   'es-ES',
   'Es Administrador',
   'src/Forms/inMtoUsuarios.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoUsuarios.TfrmMtoUsuarios.cxGrdDBTabPrinEMPRESADEF_USUARIO.Caption',
   'es-ES',
   'Empresa por defecto en documentos',
   'src/Forms/inMtoUsuarios.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoUsuarios.TfrmMtoUsuarios.cxgrdbclmnGrdDBTabPrinRAZONSOCIAL_EMPRES',
     'A.Caption'
   ),
   'es-ES',
   'Razón Social Empresa',
   'src/Forms/inMtoUsuarios.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoUsuarios.TfrmMtoUsuarios.cxGrdDBTabPrinESACTIVO_USUARIO.Caption',
   'es-ES',
   'Activo',
   'src/Forms/inMtoUsuarios.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoUsuarios.TfrmMtoUsuarios.cxGrdDBTabPrinALMACENDEF_USUARIO.Caption',
   'es-ES',
   'Almacén por defecto',
   'src/Forms/inMtoUsuarios.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoUsuarios.TfrmMtoUsuarios.cxGrdDBTabPrinCAJADEF_USUARIO.Caption',
   'es-ES',
   'Caja por defecto',
   'src/Forms/inMtoUsuarios.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoUsuarios.TfrmMtoUsuarios.cxGrdDBTabPrinPASSWORD_USUARIO.Caption',
   'es-ES',
   'Password Encriptado',
   'src/Forms/inMtoUsuarios.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoUsuarios.TfrmMtoUsuarios.cxGrdDBTabPrinULTIMOLOGIN_USUARIO.Caption',
   'es-ES',
   'Última Conexión',
   'src/Forms/inMtoUsuarios.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoUsuarios.TfrmMtoUsuarios.btnSetPass.Caption',
   'es-ES',
   'Cambiar &Contraseña',
   'src/Forms/inMtoUsuarios.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoUsuarios.TfrmMtoUsuarios.btnSetCaja.Caption',
   'es-ES',
   'Almacén / Caja',
   'src/Forms/inMtoUsuarios.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoUsuariosPerfiles.TfrmMtoUsuariosPerfiles.Caption',
   'es-ES',
   'UsuariosPerfiles',
   'src/Forms/inMtoUsuariosPerfiles.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoVariaciones.TfrmMtoVariaciones.Caption',
   'es-ES',
   'Tipos de Variaciones',
   'src/Forms/inMtoVariaciones.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoVariaciones.TfrmMtoVariaciones.cxGrdDBTabPrinCODIGO_VAR.Caption',
   'es-ES',
   'Código',
   'src/Forms/inMtoVariaciones.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoVariaciones.TfrmMtoVariaciones.cxGrdDBTabPrinNOMBRE_VAR.Caption',
   'es-ES',
   'Nombre',
   'src/Forms/inMtoVariaciones.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoVariaciones.TfrmMtoVariaciones.cxGrdDBTabPrinESACTIVO_VAR.Caption',
   'es-ES',
   'Activo',
   'src/Forms/inMtoVariaciones.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoVariaciones.TfrmMtoVariaciones.cxGrdDBTabPrinORDEN_VAR.Caption',
   'es-ES',
   'Orden',
   'src/Forms/inMtoVariaciones.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoVariaciones.TfrmMtoVariaciones.cxGrdDBTabPrinINSTANTEALTA.Caption',
   'es-ES',
   'Instante Alta',
   'src/Forms/inMtoVariaciones.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoVariaciones.TfrmMtoVariaciones.cxGrdDBTabPrinINSTANTEMODIF.Caption',
   'es-ES',
   'Instante Modif',
   'src/Forms/inMtoVariaciones.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoVariaciones.TfrmMtoVariaciones.cxGrdDBTabPrinUSUARIOALTA.Caption',
   'es-ES',
   'Usuario Alta',
   'src/Forms/inMtoVariaciones.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoVariaciones.TfrmMtoVariaciones.cxGrdDBTabPrinUSUARIOMODIF.Caption',
   'es-ES',
   'Usuario Modif',
   'src/Forms/inMtoVariaciones.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoVariaciones.TfrmMtoVariaciones.lblCodigo.Caption',
   'es-ES',
   'Código',
   'src/Forms/inMtoVariaciones.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoVariaciones.TfrmMtoVariaciones.lblNombre.Caption',
   'es-ES',
   'Nombre',
   'src/Forms/inMtoVariaciones.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoVariaciones.TfrmMtoVariaciones.chkESACTIVO_VAR.Caption',
   'es-ES',
   'Activo',
   'src/Forms/inMtoVariaciones.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoVariaciones.TfrmMtoVariaciones.lblOrden.Caption',
   'es-ES',
   'Orden',
   'src/Forms/inMtoVariaciones.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoVariaciones.TfrmMtoVariaciones.tsAtributos.Caption',
   'es-ES',
   '&1_Atributos',
   'src/Forms/inMtoVariaciones.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoVariaciones.TfrmMtoVariaciones.tvAtributosID_VAR_VA.Caption',
   'es-ES',
   'Código Variación',
   'src/Forms/inMtoVariaciones.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoVariaciones.TfrmMtoVariaciones.tvAtributosID_ATB_VA.Caption',
   'es-ES',
   'Código Atributo',
   'src/Forms/inMtoVariaciones.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoVariaciones.TfrmMtoVariaciones.tvAtributosNOMBRE_VA.Caption',
   'es-ES',
   'Nombre',
   'src/Forms/inMtoVariaciones.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoVariaciones.TfrmMtoVariaciones.tvAtributosORDEN_VA.Caption',
   'es-ES',
   'Orden',
   'src/Forms/inMtoVariaciones.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoVariaciones.TfrmMtoVariaciones.tsArticulos.Caption',
   'es-ES',
   '&2_Artículos',
   'src/Forms/inMtoVariaciones.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoVariaciones.TfrmMtoVariaciones.tvArticulosCODIGO_ART_ART.Caption',
   'es-ES',
   'Código Artículo',
   'src/Forms/inMtoVariaciones.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoVariaciones.TfrmMtoVariaciones.tvArticulosDESCRIPCION_ART.Caption',
   'es-ES',
   'Descripción',
   'src/Forms/inMtoVariaciones.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoVariaciones.TfrmMtoVariaciones.tvArticulosESACTIVO_ART.Caption',
   'es-ES',
   'Activo',
   'src/Forms/inMtoVariaciones.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoVariaciones.TfrmMtoVariaciones.tvArticulosCODIGO_FAM_ART.Caption',
   'es-ES',
   'Código Familia',
   'src/Forms/inMtoVariaciones.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoVariaciones.TfrmMtoVariaciones.tvArticulosNOMBRE_FAM_FAM.Caption',
   'es-ES',
   'Familia',
   'src/Forms/inMtoVariaciones.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoVariaciones.TfrmMtoVariaciones.tvArticulosESVARIACION_ART.Caption',
   'es-ES',
   'Tiene Variaciones',
   'src/Forms/inMtoVariaciones.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoVariaciones.TfrmMtoVariaciones.tvSkusCODIGO_UNIDAD_SKU.Caption',
   'es-ES',
   'Código SKU',
   'src/Forms/inMtoVariaciones.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoVariaciones.TfrmMtoVariaciones.tvSkusCODIGO_ART_SKU.Caption',
   'es-ES',
   'Código Artículo',
   'src/Forms/inMtoVariaciones.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoVariaciones.TfrmMtoVariaciones.tvSkusCODIGO_VAR_SKU.Caption',
   'es-ES',
   'Código Variación',
   'src/Forms/inMtoVariaciones.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoVariaciones.TfrmMtoVariaciones.tvSkusESACTIVO_SKU.Caption',
   'es-ES',
   'Activo',
   'src/Forms/inMtoVariaciones.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoVariaciones.TfrmMtoVariaciones.tsAuditoria.Caption',
   'es-ES',
   '&3_Otros',
   'src/Forms/inMtoVariaciones.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoVariaciones.TfrmMtoVariaciones.lblUsuarioAlta.Caption',
   'es-ES',
   'Usuario Alta',
   'src/Forms/inMtoVariaciones.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoVariaciones.TfrmMtoVariaciones.lblInstanteAlta.Caption',
   'es-ES',
   'Instante Alta',
   'src/Forms/inMtoVariaciones.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoVariaciones.TfrmMtoVariaciones.lblUsuarioModif.Caption',
   'es-ES',
   'Usuario Modificación',
   'src/Forms/inMtoVariaciones.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoVariaciones.TfrmMtoVariaciones.lblInstanteModif.Caption',
   'es-ES',
   'Instante Modificación',
   'src/Forms/inMtoVariaciones.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema')
ON DUPLICATE KEY UPDATE
  `TEXTO_TRAD` = VALUES(`TEXTO_TRAD`),
  `CONTEXTO_TRAD` = VALUES(`CONTEXTO_TRAD`),
  `ESACTIVO_TRAD` = VALUES(`ESACTIVO_TRAD`),
  `INSTANTE_MODIF` = CURRENT_TIMESTAMP,
  `USUARIO_MODIF` = VALUES(`USUARIO_ALTA`);
