-- Catálogo de textos españoles extraídos de los DFM.
-- Generado por generar_traducciones_dfm.ps1.
INSERT INTO `fza_traducciones` (
  `CLAVE_TRAD`, `IDIOMA_TRAD`, `TEXTO_TRAD`, `CONTEXTO_TRAD`,
  `ESACTIVO_TRAD`, `INSTANTE_ALTA`, `USUARIO_ALTA`
) VALUES
  ('inMtoModalAceptCancel.TfrmModalAceptCancel.btnCancelar.Caption',
   'es-ES',
   '&Cancelar (ESC)',
   'src/Modals/inMtoModalAceptCancel.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalAceptCancel.TfrmModalAceptCancel.btnAceptar.Caption',
   'es-ES',
   '&Aceptar (F12)',
   'src/Modals/inMtoModalAceptCancel.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalAceptCancel.TfrmModalAceptCancel.Action1.Caption',
   'es-ES',
   'Action1',
   'src/Modals/inMtoModalAceptCancel.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalAceptCancel.TfrmModalAceptCancel.Action2.Caption',
   'es-ES',
   'Action2',
   'src/Modals/inMtoModalAceptCancel.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalAddBlockBase.TfrmModalAddBlockBase.Caption',
   'es-ES',
   'Carga masiva con filtros',
   'src/Modals/inMtoModalAddBlockBase.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalAddBlockBase.TfrmModalAddBlockBase.pnlCabeceraExtra.Caption',
   'es-ES',
   ' ',
   'src/Modals/inMtoModalAddBlockBase.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalAddBlockBase.TfrmModalAddBlockBase.chkSoloActivos.Caption',
   'es-ES',
   'Sólo artículos activos',
   'src/Modals/inMtoModalAddBlockBase.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalAddBlockBase.TfrmModalAddBlockBase.chkExcluirYaCargados.Caption',
   'es-ES',
   'Excluir artículos ya cargados',
   'src/Modals/inMtoModalAddBlockBase.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalAddBlockBase.TfrmModalAddBlockBase.chkSoloConStock.Caption',
   'es-ES',
   'Sólo artículos con stock',
   'src/Modals/inMtoModalAddBlockBase.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalAddBlockBase.TfrmModalAddBlockBase.btnPrevisualizar.Caption',
   'es-ES',
   'Previsualizar',
   'src/Modals/inMtoModalAddBlockBase.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalAddBlockBase.TfrmModalAddBlockBase.btnLimpiarFiltros.Caption',
   'es-ES',
   'Limpiar',
   'src/Modals/inMtoModalAddBlockBase.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalAddBlockBase.TfrmModalAddBlockBase.tsFamilias.Caption',
   'es-ES',
   '&1_Familias',
   'src/Modals/inMtoModalAddBlockBase.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalAddBlockBase.TfrmModalAddBlockBase.chkPropagarHijos.Caption',
   'es-ES',
   'Propagar selección a subfamilias',
   'src/Modals/inMtoModalAddBlockBase.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalAddBlockBase.TfrmModalAddBlockBase.btnExpandirFamilias.Caption',
   'es-ES',
   'Expandir',
   'src/Modals/inMtoModalAddBlockBase.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalAddBlockBase.TfrmModalAddBlockBase.btnContraerFamilias.Caption',
   'es-ES',
   'Contraer',
   'src/Modals/inMtoModalAddBlockBase.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalAddBlockBase.TfrmModalAddBlockBase.btnQuitarSelFamilias.Caption',
   'es-ES',
   'Quitar selección',
   'src/Modals/inMtoModalAddBlockBase.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalAddBlockBase.TfrmModalAddBlockBase.lblSelFamilias.Caption',
   'es-ES',
   '(0 sel.)',
   'src/Modals/inMtoModalAddBlockBase.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalAddBlockBase.TfrmModalAddBlockBase.tsProveedores.Caption',
   'es-ES',
   '&2_Proveedores',
   'src/Modals/inMtoModalAddBlockBase.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalAddBlockBase.TfrmModalAddBlockBase.chkSoloPrincipal.Caption',
   'es-ES',
   'Sólo proveedores principales',
   'src/Modals/inMtoModalAddBlockBase.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoModalAddBlockBase.TfrmModalAddBlockBase.btnQuitarSelProveedores.C',
     'aption'
   ),
   'es-ES',
   'Quitar selección',
   'src/Modals/inMtoModalAddBlockBase.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalAddBlockBase.TfrmModalAddBlockBase.lblSelProveedores.Caption',
   'es-ES',
   '(0 sel.)',
   'src/Modals/inMtoModalAddBlockBase.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalAddBlockBase.TfrmModalAddBlockBase.tsPropiedades.Caption',
   'es-ES',
   '&3_Propiedades (incluye temporada)',
   'src/Modals/inMtoModalAddBlockBase.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalAddBlockBase.TfrmModalAddBlockBase.lblPropiedad.Caption',
   'es-ES',
   'Filtrar propiedad:',
   'src/Modals/inMtoModalAddBlockBase.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoModalAddBlockBase.TfrmModalAddBlockBase.btnQuitarSelPropiedades.C',
     'aption'
   ),
   'es-ES',
   'Quitar selección',
   'src/Modals/inMtoModalAddBlockBase.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalAddBlockBase.TfrmModalAddBlockBase.lblSelPropiedades.Caption',
   'es-ES',
   '(0 sel.)',
   'src/Modals/inMtoModalAddBlockBase.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalAddBlockBase.TfrmModalAddBlockBase.colPropPropiedad.Caption',
   'es-ES',
   'Propiedad',
   'src/Modals/inMtoModalAddBlockBase.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalAddBlockBase.TfrmModalAddBlockBase.colPropValor.Caption',
   'es-ES',
   'Valor',
   'src/Modals/inMtoModalAddBlockBase.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalAddBlockBase.TfrmModalAddBlockBase.tsAlmacenes.Caption',
   'es-ES',
   '&4_Almacenes (para filtro de stock)',
   'src/Modals/inMtoModalAddBlockBase.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalAddBlockBase.TfrmModalAddBlockBase.lblAlmacenInfo.Caption',
   'es-ES',
   CONCAT(
     'Marca uno o varios almacenes para acotar el filtro "Sólo con stock". ',
     'Si no marcas ninguno y activas el filtro, no se incluirá ningún ',
     'artículo.'
   ),
   'src/Modals/inMtoModalAddBlockBase.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalAddBlockBase.TfrmModalAddBlockBase.rgStockCombinacion.Caption',
   'es-ES',
   ' Combinación entre almacenes ',
   'src/Modals/inMtoModalAddBlockBase.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoModalAddBlockBase.TfrmModalAddBlockBase.rgStockCombinacion.Proper',
     'ties.Items[0].Caption'
   ),
   'es-ES',
   'Stock > 0 en cualquiera (OR)',
   'src/Modals/inMtoModalAddBlockBase.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoModalAddBlockBase.TfrmModalAddBlockBase.rgStockCombinacion.Proper',
     'ties.Items[1].Caption'
   ),
   'es-ES',
   'Stock > 0 en todos (AND)',
   'src/Modals/inMtoModalAddBlockBase.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoModalAddBlockBase.TfrmModalAddBlockBase.rgStockCombinacion.Proper',
     'ties.Items[2].Caption'
   ),
   'es-ES',
   'Suma total > 0',
   'src/Modals/inMtoModalAddBlockBase.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalAddBlockBase.TfrmModalAddBlockBase.btnMarcarTodosAlm.Caption',
   'es-ES',
   'Marcar todos',
   'src/Modals/inMtoModalAddBlockBase.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalAddBlockBase.TfrmModalAddBlockBase.btnDesmarcarTodosAlm.Caption',
   'es-ES',
   'Desmarcar todos',
   'src/Modals/inMtoModalAddBlockBase.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalAddBlockBase.TfrmModalAddBlockBase.lblSelAlmacenes.Caption',
   'es-ES',
   '(0 sel.)',
   'src/Modals/inMtoModalAddBlockBase.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalAddBlockBase.TfrmModalAddBlockBase.tsFechaAlta.Caption',
   'es-ES',
   '&5_Fecha alta',
   'src/Modals/inMtoModalAddBlockBase.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalAddBlockBase.TfrmModalAddBlockBase.chkAplicarFechaAlta.Caption',
   'es-ES',
   'Filtrar por fecha de alta del artículo',
   'src/Modals/inMtoModalAddBlockBase.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalAddBlockBase.TfrmModalAddBlockBase.lblAltaDesde.Caption',
   'es-ES',
   'Desde:',
   'src/Modals/inMtoModalAddBlockBase.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalAddBlockBase.TfrmModalAddBlockBase.lblAltaHasta.Caption',
   'es-ES',
   'Hasta:',
   'src/Modals/inMtoModalAddBlockBase.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalAddBlockBase.TfrmModalAddBlockBase.tsVentas.Caption',
   'es-ES',
   '&6_Ventas',
   'src/Modals/inMtoModalAddBlockBase.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalAddBlockBase.TfrmModalAddBlockBase.chkConVenta.Caption',
   'es-ES',
   'Filtrar según histórico de ventas',
   'src/Modals/inMtoModalAddBlockBase.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalAddBlockBase.TfrmModalAddBlockBase.lblVtaDesde.Caption',
   'es-ES',
   'Periodo desde:',
   'src/Modals/inMtoModalAddBlockBase.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalAddBlockBase.TfrmModalAddBlockBase.lblVtaHasta.Caption',
   'es-ES',
   'Periodo hasta:',
   'src/Modals/inMtoModalAddBlockBase.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalAddBlockBase.TfrmModalAddBlockBase.rgConSinVenta.Caption',
   'es-ES',
   ' Tipo ',
   'src/Modals/inMtoModalAddBlockBase.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoModalAddBlockBase.TfrmModalAddBlockBase.rgConSinVenta.Properties.',
     'Items[0].Caption'
   ),
   'es-ES',
   'Artículos CON ventas en el periodo',
   'src/Modals/inMtoModalAddBlockBase.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoModalAddBlockBase.TfrmModalAddBlockBase.rgConSinVenta.Properties.',
     'Items[1].Caption'
   ),
   'es-ES',
   'Artículos SIN ventas en el periodo',
   'src/Modals/inMtoModalAddBlockBase.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalAddBlockBase.TfrmModalAddBlockBase.lblNumMinVtas.Caption',
   'es-ES',
   'Número mínimo de ventas:',
   'src/Modals/inMtoModalAddBlockBase.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalAddBlockBase.TfrmModalAddBlockBase.lblPreviewInfo.Caption',
   'es-ES',
   '0 artículos',
   'src/Modals/inMtoModalAddBlockBase.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalAddBlockBase.TfrmModalAddBlockBase.colPrevStock.Caption',
   'es-ES',
   'Stock',
   'src/Modals/inMtoModalAddBlockBase.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalAddBlockBase.TfrmModalAddBlockBase.colPrevYaCargado.Caption',
   'es-ES',
   'Ya cargado',
   'src/Modals/inMtoModalAddBlockBase.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalAddBlockBase.TfrmModalAddBlockBase.btnAceptar.Caption',
   'es-ES',
   '&Aceptar',
   'src/Modals/inMtoModalAddBlockBase.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalAddBlockBase.TfrmModalAddBlockBase.btnCancelar.Caption',
   'es-ES',
   '&Cancelar',
   'src/Modals/inMtoModalAddBlockBase.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoModalAddBlockDocumentoTrabajo.TfrmModalAddBlockDocumentoTrabajo.C',
     'aption'
   ),
   'es-ES',
   'Añadir Bloque - Documento de Trabajo',
   'src/Modals/inMtoModalAddBlockDocumentoTrabajo.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoModalAddBlockDocumentoTrabajo.TfrmModalAddBlockDocumentoTrabajo.l',
     'blDocumentoInfo.Caption'
   ),
   'es-ES',
   'Documento destino',
   'src/Modals/inMtoModalAddBlockDocumentoTrabajo.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoModalAddBlockDocumentoTrabajo.TfrmModalAddBlockDocumentoTrabajo.l',
     'blNotaCarga.Caption'
   ),
   'es-ES',
   CONCAT(
     'Se añadirá una línea por cada SKU con stock positivo en los almacenes ',
     'seleccionados. La cantidad operativa quedará a 1.'
   ),
   'src/Modals/inMtoModalAddBlockDocumentoTrabajo.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalAddBlockInventario.TfrmModalAddBlockInventario.Caption',
   'es-ES',
   'Añadir Bloque - Carga masiva en Inventario',
   'src/Modals/inMtoModalAddBlockInventario.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoModalAddBlockInventario.TfrmModalAddBlockInventario.lblInventario',
     'Info.Caption'
   ),
   'es-ES',
   'Inventario destino',
   'src/Modals/inMtoModalAddBlockInventario.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoModalAddBlockInventario.TfrmModalAddBlockInventario.lblNotaCarga.',
     'Caption'
   ),
   'es-ES',
   CONCAT(
     'Se añadirá una línea por cada SKU con stock>0 en el almacén del ',
     'inventario. Las cantidades teóricas se calcularán después pulsando ',
     '"Recalcular teórico/PMP".'
   ),
   'src/Modals/inMtoModalAddBlockInventario.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoModalAddBlockInventario.TfrmModalAddBlockInventario.colPrevSkusCo',
     'nStock.Caption'
   ),
   'es-ES',
   'SKUs c/ stock',
   'src/Modals/inMtoModalAddBlockInventario.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoModalAddBlockInventario.TfrmModalAddBlockInventario.colPrevPMPAct',
     'ual.Caption'
   ),
   'es-ES',
   'PMP medio',
   'src/Modals/inMtoModalAddBlockInventario.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalAddBlockTarifa.TfrmModalAddBlockTarifa.Caption',
   'es-ES',
   'Añadir Bloque - Carga masiva en Tarifa',
   'src/Modals/inMtoModalAddBlockTarifa.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalAddBlockTarifa.TfrmModalAddBlockTarifa.lblTarifa.Caption',
   'es-ES',
   'Tarifa destino:',
   'src/Modals/inMtoModalAddBlockTarifa.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalAddBlockTarifa.TfrmModalAddBlockTarifa.lblFechaDesde.Caption',
   'es-ES',
   'Fecha desde:',
   'src/Modals/inMtoModalAddBlockTarifa.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalAddBlockTarifa.TfrmModalAddBlockTarifa.chkConFechaHasta.Caption',
   'es-ES',
   'Fecha hasta:',
   'src/Modals/inMtoModalAddBlockTarifa.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalAddBlockTarifa.TfrmModalAddBlockTarifa.lblPorcenDto.Caption',
   'es-ES',
   '% Dto:',
   'src/Modals/inMtoModalAddBlockTarifa.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalAddBlockTarifa.TfrmModalAddBlockTarifa.chkAjustarPrecio.Caption',
   'es-ES',
   'Ajustar precio',
   'src/Modals/inMtoModalAddBlockTarifa.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalAddBlockTarifa.TfrmModalAddBlockTarifa.lblMultiplo.Caption',
   'es-ES',
   'Múltiplo:',
   'src/Modals/inMtoModalAddBlockTarifa.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalAddBlockTarifa.TfrmModalAddBlockTarifa.lblRestar.Caption',
   'es-ES',
   'Menos:',
   'src/Modals/inMtoModalAddBlockTarifa.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalAddBlockTarifa.TfrmModalAddBlockTarifa.rgAjusteAlcance.Caption',
   'es-ES',
   ' Aplicar ajuste a ',
   'src/Modals/inMtoModalAddBlockTarifa.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoModalAddBlockTarifa.TfrmModalAddBlockTarifa.rgAjusteAlcance.Prope',
     'rties.Items[0].Caption'
   ),
   'es-ES',
   'Final',
   'src/Modals/inMtoModalAddBlockTarifa.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoModalAddBlockTarifa.TfrmModalAddBlockTarifa.rgAjusteAlcance.Prope',
     'rties.Items[1].Caption'
   ),
   'es-ES',
   'Salida',
   'src/Modals/inMtoModalAddBlockTarifa.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoModalAddBlockTarifa.TfrmModalAddBlockTarifa.rgAjusteAlcance.Prope',
     'rties.Items[2].Caption'
   ),
   'es-ES',
   'Ambos',
   'src/Modals/inMtoModalAddBlockTarifa.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalAddBlockTarifa.TfrmModalAddBlockTarifa.chkCopiarDeTarifa.Caption',
   'es-ES',
   'Copiar precios de tarifa',
   'src/Modals/inMtoModalAddBlockTarifa.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalAddBlockTarifa.TfrmModalAddBlockTarifa.tsProveedores.Caption',
   'es-ES',
   '&2_Proveedores ',
   'src/Modals/inMtoModalAddBlockTarifa.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalAddBlockTarifa.TfrmModalAddBlockTarifa.tsPropiedades.Caption',
   'es-ES',
   '&3_Propiedades ',
   'src/Modals/inMtoModalAddBlockTarifa.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalAddBlockTarifa.TfrmModalAddBlockTarifa.tsFechaAlta.Caption',
   'es-ES',
   '&5_Fecha alta ',
   'src/Modals/inMtoModalAddBlockTarifa.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalAddBlockTarifa.TfrmModalAddBlockTarifa.tsVentas.Caption',
   'es-ES',
   '&6_Ventas ',
   'src/Modals/inMtoModalAddBlockTarifa.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoModalAddBlockTarifa.TfrmModalAddBlockTarifa.colPrevPrecioSalidaOr',
     'ig.Caption'
   ),
   'es-ES',
   'P. Salida orig.',
   'src/Modals/inMtoModalAddBlockTarifa.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoModalAddBlockTarifa.TfrmModalAddBlockTarifa.colPrevPrecioFinalOri',
     'g.Caption'
   ),
   'es-ES',
   'P. Final orig.',
   'src/Modals/inMtoModalAddBlockTarifa.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalAddPreciosTar.TfrmMtoModalAddPreciosTar.Caption',
   'es-ES',
   'Añadir precios a Tarifas',
   'src/Modals/inMtoModalAddPreciosTar.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalAddPreciosTar.TfrmMtoModalAddPreciosTar.lblSkus.Caption',
   'es-ES',
   ' 1. Seleccione los SKUs:',
   'src/Modals/inMtoModalAddPreciosTar.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalAddPreciosTar.TfrmMtoModalAddPreciosTar.lblTarifas.Caption',
   'es-ES',
   ' 2. Seleccione las Tarifas:',
   'src/Modals/inMtoModalAddPreciosTar.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalAddPreciosTar.TfrmMtoModalAddPreciosTar.lblDesde.Caption',
   'es-ES',
   'Vigente desde:',
   'src/Modals/inMtoModalAddPreciosTar.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalAddPreciosTar.TfrmMtoModalAddPreciosTar.lblHasta.Caption',
   'es-ES',
   'Hasta (opcional):',
   'src/Modals/inMtoModalAddPreciosTar.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalAltaRapida.TfrmMtoModalAltaRapida.Caption',
   'es-ES',
   'Alta rápida',
   'src/Modals/inMtoModalAltaRapida.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalAltaRapida.TfrmMtoModalAltaRapida.lblCod.Caption',
   'es-ES',
   'Código:',
   'src/Modals/inMtoModalAltaRapida.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalAltaRapida.TfrmMtoModalAltaRapida.lblDesc.Caption',
   'es-ES',
   'Descripción:',
   'src/Modals/inMtoModalAltaRapida.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalAltaRapida.TfrmMtoModalAltaRapida.btnOk.Caption',
   'es-ES',
   '&Guardar',
   'src/Modals/inMtoModalAltaRapida.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalAltaRapida.TfrmMtoModalAltaRapida.btnCancel.Caption',
   'es-ES',
   '&Cancelar',
   'src/Modals/inMtoModalAltaRapida.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalArtTar.TfrmMtoModalArtTar.Caption',
   'es-ES',
   'Seleccionar Tarifas',
   'src/Modals/inMtoModalArtTar.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalArtTar.TfrmMtoModalArtTar.btnCancelar1.Caption',
   'es-ES',
   '&Cancelar',
   'src/Modals/inMtoModalArtTar.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalArtTar.TfrmMtoModalArtTar.btnAceptar.Caption',
   'es-ES',
   '&Aceptar',
   'src/Modals/inMtoModalArtTar.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalArtTar.TfrmMtoModalArtTar.lstTarifas.Columns[0].Caption',
   'es-ES',
   'Código Tarifa',
   'src/Modals/inMtoModalArtTar.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalArtTar.TfrmMtoModalArtTar.lstTarifas.Columns[1].Caption',
   'es-ES',
   'Nombre Tarifa',
   'src/Modals/inMtoModalArtTar.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalCajDef.TfrmMtoModalCajDef.Caption',
   'es-ES',
   'Seleccionar Caja',
   'src/Modals/inMtoModalCajDef.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalCajDef.TfrmMtoModalCajDef.btnCancelar1.Caption',
   'es-ES',
   '&Cancelar',
   'src/Modals/inMtoModalCajDef.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalCajDef.TfrmMtoModalCajDef.btnAceptar.Caption',
   'es-ES',
   '&Aceptar',
   'src/Modals/inMtoModalCajDef.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalCajDef.TfrmMtoModalCajDef.Action1.Caption',
   'es-ES',
   'Action1',
   'src/Modals/inMtoModalCajDef.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalCajDef.TfrmMtoModalCajDef.Action2.Caption',
   'es-ES',
   'Action2',
   'src/Modals/inMtoModalCajDef.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalCalcularMargen.TfrmModalCalcularMargen.Caption',
   'es-ES',
   'Calcular margen comercial',
   'src/Modals/inMtoModalCalcularMargen.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalCalcularMargen.TfrmModalCalcularMargen.lblArticulo.Caption',
   'es-ES',
   'Artículo',
   'src/Modals/inMtoModalCalcularMargen.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalCalcularMargen.TfrmModalCalcularMargen.lblTarifa.Caption',
   'es-ES',
   'Tarifa',
   'src/Modals/inMtoModalCalcularMargen.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalCalcularMargen.TfrmModalCalcularMargen.lblSku.Caption',
   'es-ES',
   'SKU',
   'src/Modals/inMtoModalCalcularMargen.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalCalcularMargen.TfrmModalCalcularMargen.lblCoste.Caption',
   'es-ES',
   'Precio coste',
   'src/Modals/inMtoModalCalcularMargen.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalCalcularMargen.TfrmModalCalcularMargen.lblMargen.Caption',
   'es-ES',
   'Margen %',
   'src/Modals/inMtoModalCalcularMargen.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalCalcularMargen.TfrmModalCalcularMargen.lblAjuste.Caption',
   'es-ES',
   'Ajuste (siguiente múltiplo)',
   'src/Modals/inMtoModalCalcularMargen.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalCalcularMargen.TfrmModalCalcularMargen.lblMenos.Caption',
   'es-ES',
   'Menos (resta al final)',
   'src/Modals/inMtoModalCalcularMargen.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalCalcularMargen.TfrmModalCalcularMargen.lblPrecioActual.Caption',
   'es-ES',
   'Precio salida actual',
   'src/Modals/inMtoModalCalcularMargen.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalCalcularMargen.TfrmModalCalcularMargen.lblPrecioCalc.Caption',
   'es-ES',
   'Precio salida calculado',
   'src/Modals/inMtoModalCalcularMargen.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalCalcularMargen.TfrmModalCalcularMargen.lblFormula.Caption',
   'es-ES',
   'precio = ceil(coste×margen/100 / ajuste)×ajuste − menos',
   'src/Modals/inMtoModalCalcularMargen.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalCalcularMargen.TfrmModalCalcularMargen.btnCancelar.Caption',
   'es-ES',
   '&Cancelar (ESC)',
   'src/Modals/inMtoModalCalcularMargen.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalCalcularMargen.TfrmModalCalcularMargen.btnAceptar.Caption',
   'es-ES',
   '&Aceptar (F12)',
   'src/Modals/inMtoModalCalcularMargen.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalCargarEfectosRemesa.TfrmModalCargarEfectosRemesa.Caption',
   'es-ES',
   'Cargar efectos en remesa',
   'src/Modals/inMtoModalCargarEfectosRemesa.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoModalCargarEfectosRemesa.TfrmModalCargarEfectosRemesa.lblEmpresa.',
     'Caption'
   ),
   'es-ES',
   'Empresa',
   'src/Modals/inMtoModalCargarEfectosRemesa.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoModalCargarEfectosRemesa.TfrmModalCargarEfectosRemesa.lblHasta.Ca',
     'ption'
   ),
   'es-ES',
   'Vto. hasta',
   'src/Modals/inMtoModalCargarEfectosRemesa.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoModalCargarEfectosRemesa.TfrmModalCargarEfectosRemesa.btnBuscar.C',
     'aption'
   ),
   'es-ES',
   'Buscar efectos',
   'src/Modals/inMtoModalCargarEfectosRemesa.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalCargarEfectosRemesa.TfrmModalCargarEfectosRemesa.rgModo.Caption',
   'es-ES',
   ' Modo ',
   'src/Modals/inMtoModalCargarEfectosRemesa.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoModalCargarEfectosRemesa.TfrmModalCargarEfectosRemesa.rgModo.Prop',
     'erties.Items[0].Caption'
   ),
   'es-ES',
   'Crear remesa nueva',
   'src/Modals/inMtoModalCargarEfectosRemesa.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoModalCargarEfectosRemesa.TfrmModalCargarEfectosRemesa.rgModo.Prop',
     'erties.Items[1].Caption'
   ),
   'es-ES',
   'Anadir a una remesa existente',
   'src/Modals/inMtoModalCargarEfectosRemesa.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoModalCargarEfectosRemesa.TfrmModalCargarEfectosRemesa.lblRemExist',
     'ente.Caption'
   ),
   'es-ES',
   'Remesa existente',
   'src/Modals/inMtoModalCargarEfectosRemesa.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoModalCargarEfectosRemesa.TfrmModalCargarEfectosRemesa.colSerieFac',
     '.Caption'
   ),
   'es-ES',
   'Serie fra',
   'src/Modals/inMtoModalCargarEfectosRemesa.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoModalCargarEfectosRemesa.TfrmModalCargarEfectosRemesa.colNumFac.C',
     'aption'
   ),
   'es-ES',
   'Nro fra',
   'src/Modals/inMtoModalCargarEfectosRemesa.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoModalCargarEfectosRemesa.TfrmModalCargarEfectosRemesa.colNumEfe.C',
     'aption'
   ),
   'es-ES',
   'Efecto',
   'src/Modals/inMtoModalCargarEfectosRemesa.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoModalCargarEfectosRemesa.TfrmModalCargarEfectosRemesa.colTercero.',
     'Caption'
   ),
   'es-ES',
   'Proveedor',
   'src/Modals/inMtoModalCargarEfectosRemesa.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalCargarEfectosRemesa.TfrmModalCargarEfectosRemesa.colVto.Caption',
   'es-ES',
   'Vencimiento',
   'src/Modals/inMtoModalCargarEfectosRemesa.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalCargarEfectosRemesa.TfrmModalCargarEfectosRemesa.colPend.Caption',
   'es-ES',
   'Pendiente',
   'src/Modals/inMtoModalCargarEfectosRemesa.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoModalCargarEfectosRemesa.TfrmModalCargarEfectosRemesa.colEstado.C',
     'aption'
   ),
   'es-ES',
   'Estado',
   'src/Modals/inMtoModalCargarEfectosRemesa.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoModalCargarEfectosRemesa.TfrmModalCargarEfectosRemesa.btnSalir.Ca',
     'ption'
   ),
   'es-ES',
   '&Salir',
   'src/Modals/inMtoModalCargarEfectosRemesa.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoModalCargarEfectosRemesa.TfrmModalCargarEfectosRemesa.btnRemesar.',
     'Caption'
   ),
   'es-ES',
   '&Cargar en remesa',
   'src/Modals/inMtoModalCargarEfectosRemesa.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalCargarSesionTarifa.TfrmModalCargarSesionTarifa.Caption',
   'es-ES',
   'Cargar articulos en sesion de tarifas',
   'src/Modals/inMtoModalCargarSesionTarifa.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalCliEti.TfrmPrintCliEti.Caption',
   'es-ES',
   'Impresión de Etiquetas',
   'src/Modals/inMtoModalCliEti.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalCliEti.TfrmPrintCliEti.cxRadioGroup1.Caption',
   'es-ES',
   'Opciones',
   'src/Modals/inMtoModalCliEti.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalCliEti.TfrmPrintCliEti.cxlbl2.Caption',
   'es-ES',
   'Dejar espacios en blanco antes de imprimir etiqueta',
   'src/Modals/inMtoModalCliEti.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalCliEti.TfrmPrintCliEti.cxLabel1.Caption',
   'es-ES',
   'Código de Cliente: ',
   'src/Modals/inMtoModalCliEti.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalContrasenaCopia.TfrmModalContrasenaCopia.Caption',
   'es-ES',
   'Contraseña de copia',
   'src/Modals/inMtoModalContrasenaCopia.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalContrasenaCopia.TfrmModalContrasenaCopia.lblExplicacion.Caption',
   'es-ES',
   'Introduzca la contraseña de la copia.',
   'src/Modals/inMtoModalContrasenaCopia.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalContrasenaCopia.TfrmModalContrasenaCopia.lblContrasena.Caption',
   'es-ES',
   'Contraseña',
   'src/Modals/inMtoModalContrasenaCopia.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalContrasenaCopia.TfrmModalContrasenaCopia.lblConfirmacion.Caption',
   'es-ES',
   'Repita la contraseña',
   'src/Modals/inMtoModalContrasenaCopia.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalContrasenaCopia.TfrmModalContrasenaCopia.btnAceptar.Caption',
   'es-ES',
   '&Aceptar',
   'src/Modals/inMtoModalContrasenaCopia.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalContrasenaCopia.TfrmModalContrasenaCopia.btnCancelar.Caption',
   'es-ES',
   '&Cancelar',
   'src/Modals/inMtoModalContrasenaCopia.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalCrearAlbaranSesion.TfrmModalCrearAlbaranSesion.Caption',
   'es-ES',
   'Crear artículos y albarán / pedido',
   'src/Modals/inMtoModalCrearAlbaranSesion.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalCrearAlbaranSesion.TfrmModalCrearAlbaranSesion.lblTitulo.Caption',
   'es-ES',
   'Confirma los datos del documento a generar:',
   'src/Modals/inMtoModalCrearAlbaranSesion.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoModalCrearAlbaranSesion.TfrmModalCrearAlbaranSesion.chkGenAlbaran',
     '.Caption'
   ),
   'es-ES',
   'Generar albarán (mueve stock)',
   'src/Modals/inMtoModalCrearAlbaranSesion.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoModalCrearAlbaranSesion.TfrmModalCrearAlbaranSesion.lblSerieAlb.C',
     'aption'
   ),
   'es-ES',
   'Serie albarán',
   'src/Modals/inMtoModalCrearAlbaranSesion.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoModalCrearAlbaranSesion.TfrmModalCrearAlbaranSesion.chkGenPedido.',
     'Caption'
   ),
   'es-ES',
   'Generar pedido (pdte. de recibir)',
   'src/Modals/inMtoModalCrearAlbaranSesion.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoModalCrearAlbaranSesion.TfrmModalCrearAlbaranSesion.lblSeriePed.C',
     'aption'
   ),
   'es-ES',
   'Serie pedido',
   'src/Modals/inMtoModalCrearAlbaranSesion.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalCrearAlbaranSesion.TfrmModalCrearAlbaranSesion.lblFecha.Caption',
   'es-ES',
   'Fecha',
   'src/Modals/inMtoModalCrearAlbaranSesion.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoModalCrearAlbaranSesion.TfrmModalCrearAlbaranSesion.lblAlmacen.Ca',
     'ption'
   ),
   'es-ES',
   'Almacén destino',
   'src/Modals/inMtoModalCrearAlbaranSesion.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoModalCrearAlbaranSesion.TfrmModalCrearAlbaranSesion.cbbAlmacen.Pr',
     'operties.ListColumns[0].Caption'
   ),
   'es-ES',
   'Código',
   'src/Modals/inMtoModalCrearAlbaranSesion.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoModalCrearAlbaranSesion.TfrmModalCrearAlbaranSesion.cbbAlmacen.Pr',
     'operties.ListColumns[1].Caption'
   ),
   'es-ES',
   'Almacén',
   'src/Modals/inMtoModalCrearAlbaranSesion.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalCrearAlbaranSesion.TfrmModalCrearAlbaranSesion.lblTarifa.Caption',
   'es-ES',
   'Tarifa venta',
   'src/Modals/inMtoModalCrearAlbaranSesion.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoModalCrearAlbaranSesion.TfrmModalCrearAlbaranSesion.cbbTarifa.Pro',
     'perties.ListColumns[0].Caption'
   ),
   'es-ES',
   'Tarifa',
   'src/Modals/inMtoModalCrearAlbaranSesion.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoModalCrearAlbaranSesion.TfrmModalCrearAlbaranSesion.lblTemporada.',
     'Caption'
   ),
   'es-ES',
   'Temporada',
   'src/Modals/inMtoModalCrearAlbaranSesion.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoModalCrearAlbaranSesion.TfrmModalCrearAlbaranSesion.cbbTemporada.',
     'Properties.ListColumns[0].Caption'
   ),
   'es-ES',
   'Temporada',
   'src/Modals/inMtoModalCrearAlbaranSesion.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalCrearAlbaranSesion.TfrmModalCrearAlbaranSesion.lblRefPrv.Caption',
   'es-ES',
   'Ref. documento proveedor',
   'src/Modals/inMtoModalCrearAlbaranSesion.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoModalCrearAlbaranSesion.TfrmModalCrearAlbaranSesion.rgAgrupacion.',
     'Caption'
   ),
   'es-ES',
   ' Agrupación almacén (formato distribuido) ',
   'src/Modals/inMtoModalCrearAlbaranSesion.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoModalCrearAlbaranSesion.TfrmModalCrearAlbaranSesion.rgAgrupacion.',
     'Properties.Items[0].Caption'
   ),
   'es-ES',
   'Agrupar todos los almacenes en un solo documento',
   'src/Modals/inMtoModalCrearAlbaranSesion.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoModalCrearAlbaranSesion.TfrmModalCrearAlbaranSesion.rgAgrupacion.',
     'Properties.Items[1].Caption'
   ),
   'es-ES',
   'Generar un documento por almacén (con la serie de su almacén)',
   'src/Modals/inMtoModalCrearAlbaranSesion.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalCrearAlbaranSesion.TfrmModalCrearAlbaranSesion.btnSalir.Caption',
   'es-ES',
   '&Salir',
   'src/Modals/inMtoModalCrearAlbaranSesion.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoModalCrearAlbaranSesion.TfrmModalCrearAlbaranSesion.btnGenerar.Ca',
     'ption'
   ),
   'es-ES',
   '&Generar',
   'src/Modals/inMtoModalCrearAlbaranSesion.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalDistribuidor.TfrmModalDistribuidor.Caption',
   'es-ES',
   'Distribuidor por almacén / talla',
   'src/Modals/inMtoModalDistribuidor.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalDistribuidor.TfrmModalDistribuidor.lblTitulo.Caption',
   'es-ES',
   'Distribución almacén / talla',
   'src/Modals/inMtoModalDistribuidor.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalDistribuidor.TfrmModalDistribuidor.lblLinea.Caption',
   'es-ES',
   'Línea:',
   'src/Modals/inMtoModalDistribuidor.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalDistribuidor.TfrmModalDistribuidor.btnKitTodos.Caption',
   'es-ES',
   'Aplicar kit en todos los almacenes',
   'src/Modals/inMtoModalDistribuidor.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalDocsCreados.TfrmModalDocsCreados.Caption',
   'es-ES',
   'Documentos creados',
   'src/Modals/inMtoModalDocsCreados.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalDocsCreados.TfrmModalDocsCreados.btnCancelar.Caption',
   'es-ES',
   '&Cerrar (ESC)',
   'src/Modals/inMtoModalDocsCreados.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalDocsCreados.TfrmModalDocsCreados.btnAceptar.Caption',
   'es-ES',
   '&Ir a documento (F12)',
   'src/Modals/inMtoModalDocsCreados.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalDocsCreados.TfrmModalDocsCreados.lblTitulo.Caption',
   'es-ES',
   'Documentos creados al materializar la sesión',
   'src/Modals/inMtoModalDocsCreados.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalEmpCer.TfrmMtoModalEmpCer.Caption',
   'es-ES',
   'Seleccionar Certificado',
   'src/Modals/inMtoModalEmpCer.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalEmpCer.TfrmMtoModalEmpCer.btnCancelar1.Caption',
   'es-ES',
   '&Cancelar',
   'src/Modals/inMtoModalEmpCer.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalEmpCer.TfrmMtoModalEmpCer.btnAceptar.Caption',
   'es-ES',
   '&Aceptar',
   'src/Modals/inMtoModalEmpCer.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalEmpCer.TfrmMtoModalEmpCer.colTipoCertificado.Caption',
   'es-ES',
   'Tipo',
   'src/Modals/inMtoModalEmpCer.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalEmpCer.TfrmMtoModalEmpCer.colTitularCertificado.Caption',
   'es-ES',
   'Titular/Empresa',
   'src/Modals/inMtoModalEmpCer.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalEmpCer.TfrmMtoModalEmpCer.colNombreCertificado.Caption',
   'es-ES',
   'Nombre',
   'src/Modals/inMtoModalEmpCer.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalEmpCer.TfrmMtoModalEmpCer.colEmisorCertificado.Caption',
   'es-ES',
   'Emisor',
   'src/Modals/inMtoModalEmpCer.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalEmpCer.TfrmMtoModalEmpCer.colFechaHastaCertificado.Caption',
   'es-ES',
   'Válido hasta',
   'src/Modals/inMtoModalEmpCer.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalEmpCer.TfrmMtoModalEmpCer.colNumeroSerieCertificado.Caption',
   'es-ES',
   'Número de serie',
   'src/Modals/inMtoModalEmpCer.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalEntradaCambio.TfrmModalEntradaCambio.Caption',
   'es-ES',
   'Entrada de Cambio (F6)',
   'src/Modals/inMtoModalEntradaCambio.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalEntradaCambio.TfrmModalEntradaCambio.lblTitulo.Caption',
   'es-ES',
   'Introduzca el efectivo que entra en caja',
   'src/Modals/inMtoModalEntradaCambio.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalEntradaCambio.TfrmModalEntradaCambio.lblEmpleadoLbl.Caption',
   'es-ES',
   'Empleado:',
   'src/Modals/inMtoModalEntradaCambio.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalEntradaCambio.TfrmModalEntradaCambio.lblImporteLbl.Caption',
   'es-ES',
   'Importe:',
   'src/Modals/inMtoModalEntradaCambio.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalEntradaCambio.TfrmModalEntradaCambio.lblConceptoLbl.Caption',
   'es-ES',
   'Concepto:',
   'src/Modals/inMtoModalEntradaCambio.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalEntradaCambio.TfrmModalEntradaCambio.actAceptar.Caption',
   'es-ES',
   'Aceptar (F12)',
   'src/Modals/inMtoModalEntradaCambio.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalEntradaCambio.TfrmModalEntradaCambio.actCancelar.Caption',
   'es-ES',
   'Cancelar (ESC)',
   'src/Modals/inMtoModalEntradaCambio.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalEnviarDestino.TfrmModalEnviarDestino.Caption',
   'es-ES',
   'Enviar a...',
   'src/Modals/inMtoModalEnviarDestino.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalEnviarDestino.TfrmModalEnviarDestino.lblAlmacen.Caption',
   'es-ES',
   'Almacén',
   'src/Modals/inMtoModalEnviarDestino.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalEnviarDestino.TfrmModalEnviarDestino.lblSerie.Caption',
   'es-ES',
   'Serie',
   'src/Modals/inMtoModalEnviarDestino.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalEnviarDestino.TfrmModalEnviarDestino.lblNumero.Caption',
   'es-ES',
   'Número',
   'src/Modals/inMtoModalEnviarDestino.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalEnviarDestino.TfrmModalEnviarDestino.btnAceptar.Caption',
   'es-ES',
   'Aceptar',
   'src/Modals/inMtoModalEnviarDestino.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalEnviarDestino.TfrmModalEnviarDestino.btnCancelar.Caption',
   'es-ES',
   'Cancelar',
   'src/Modals/inMtoModalEnviarDestino.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalEtiqAlb.TfrmPrintEtiqAlb.Caption',
   'es-ES',
   'Impresión de Etiquetas de Albarán',
   'src/Modals/inMtoModalEtiqAlb.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalEtiqAlb.TfrmPrintEtiqAlb.cxlblAlbaran.Caption',
   'es-ES',
   'Albarán:',
   'src/Modals/inMtoModalEtiqAlb.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalEtiqAlb.TfrmPrintEtiqAlb.cxlblTarifa.Caption',
   'es-ES',
   'Tarifa:',
   'src/Modals/inMtoModalEtiqAlb.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalEtiqAlb.TfrmPrintEtiqAlb.cxlblFecha.Caption',
   'es-ES',
   'Fecha de aplicación:',
   'src/Modals/inMtoModalEtiqAlb.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalEtiqAlb.TfrmPrintEtiqAlb.cxlblAlmacenes.Caption',
   'es-ES',
   'Almacenes del albarán (marque uno o varios):',
   'src/Modals/inMtoModalEtiqAlb.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalEtiqAlb.TfrmPrintEtiqAlb.lvAlmacenes.Columns[0].Caption',
   'es-ES',
   'Código',
   'src/Modals/inMtoModalEtiqAlb.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalEtiqAlb.TfrmPrintEtiqAlb.lvAlmacenes.Columns[1].Caption',
   'es-ES',
   'Almacén',
   'src/Modals/inMtoModalEtiqAlb.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalEtiqArt.TfrmPrintEtiqArt.Caption',
   'es-ES',
   'Impresión de Etiquetas de Artículo',
   'src/Modals/inMtoModalEtiqArt.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalEtiqArt.TfrmPrintEtiqArt.cxlblArticulo.Caption',
   'es-ES',
   'Código de Artículo:',
   'src/Modals/inMtoModalEtiqArt.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalEtiqArt.TfrmPrintEtiqArt.chkSoloEsteArt.Caption',
   'es-ES',
   'Imprimir sólo este artículo',
   'src/Modals/inMtoModalEtiqArt.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalEtiqArt.TfrmPrintEtiqArt.cxlblTarifa.Caption',
   'es-ES',
   'Tarifa:',
   'src/Modals/inMtoModalEtiqArt.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalEtiqArt.TfrmPrintEtiqArt.cxlblFecha.Caption',
   'es-ES',
   'Fecha de aplicación:',
   'src/Modals/inMtoModalEtiqArt.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalEtiqArt.TfrmPrintEtiqArt.cxlblAlmacenes.Caption',
   'es-ES',
   'Almacenes (marque uno o varios):',
   'src/Modals/inMtoModalEtiqArt.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalEtiqArt.TfrmPrintEtiqArt.lvAlmacenes.Columns[0].Caption',
   'es-ES',
   'Código',
   'src/Modals/inMtoModalEtiqArt.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalEtiqArt.TfrmPrintEtiqArt.lvAlmacenes.Columns[1].Caption',
   'es-ES',
   'Nombre',
   'src/Modals/inMtoModalEtiqArt.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalEtiqDev.TfrmPrintEtiqDev.Caption',
   'es-ES',
   'Impresión de Etiquetas de Albarán',
   'src/Modals/inMtoModalEtiqDev.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalEtiqDev.TfrmPrintEtiqDev.cxlblDevolucion.Caption',
   'es-ES',
   'Albarán:',
   'src/Modals/inMtoModalEtiqDev.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalEtiqDev.TfrmPrintEtiqDev.cxlblTarifa.Caption',
   'es-ES',
   'Tarifa:',
   'src/Modals/inMtoModalEtiqDev.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalEtiqDev.TfrmPrintEtiqDev.cxlblFecha.Caption',
   'es-ES',
   'Fecha de aplicación:',
   'src/Modals/inMtoModalEtiqDev.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalEtiqDev.TfrmPrintEtiqDev.cxlblAlmacenes.Caption',
   'es-ES',
   'Almacenes del albarán (marque uno o varios):',
   'src/Modals/inMtoModalEtiqDev.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalEtiqDev.TfrmPrintEtiqDev.lvAlmacenes.Columns[0].Caption',
   'es-ES',
   'Código',
   'src/Modals/inMtoModalEtiqDev.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalEtiqDev.TfrmPrintEtiqDev.lvAlmacenes.Columns[1].Caption',
   'es-ES',
   'Almacén',
   'src/Modals/inMtoModalEtiqDev.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalEtiqPed.TfrmPrintEtiqPed.Caption',
   'es-ES',
   'Impresión de Etiquetas de Pedido',
   'src/Modals/inMtoModalEtiqPed.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalEtiqPed.TfrmPrintEtiqPed.cxlblPedido.Caption',
   'es-ES',
   'Pedido:',
   'src/Modals/inMtoModalEtiqPed.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalEtiqPed.TfrmPrintEtiqPed.cxlblTarifa.Caption',
   'es-ES',
   'Tarifa:',
   'src/Modals/inMtoModalEtiqPed.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalEtiqPed.TfrmPrintEtiqPed.cxlblFecha.Caption',
   'es-ES',
   'Fecha de aplicación:',
   'src/Modals/inMtoModalEtiqPed.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalEtiqPed.TfrmPrintEtiqPed.cxlblAlmacenes.Caption',
   'es-ES',
   'Almacenes del pedido (marque uno o varios):',
   'src/Modals/inMtoModalEtiqPed.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalEtiqPed.TfrmPrintEtiqPed.lvAlmacenes.Columns[0].Caption',
   'es-ES',
   'Código',
   'src/Modals/inMtoModalEtiqPed.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalEtiqPed.TfrmPrintEtiqPed.lvAlmacenes.Columns[1].Caption',
   'es-ES',
   'Almacén',
   'src/Modals/inMtoModalEtiqPed.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalFacRec.TfrmGenFacRec.Caption',
   'es-ES',
   'Duplicar/Abonar Borrador',
   'src/Modals/inMtoModalFacRec.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalFacRec.TfrmGenFacRec.cxlbl1.Caption',
   'es-ES',
   'Borrador Origen Número',
   'src/Modals/inMtoModalFacRec.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalFacRec.TfrmGenFacRec.btn3.Caption',
   'es-ES',
   'Salir',
   'src/Modals/inMtoModalFacRec.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalFacRec.TfrmGenFacRec.btnGenerar.Caption',
   'es-ES',
   'Generar',
   'src/Modals/inMtoModalFacRec.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalFacRec.TfrmGenFacRec.chkAbonar.Caption',
   'es-ES',
   'Generar Borrador de Abono',
   'src/Modals/inMtoModalFacRec.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalFacRec.TfrmGenFacRec.cxgrpbx1.Caption',
   'es-ES',
   'Borrador Generado',
   'src/Modals/inMtoModalFacRec.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalFacRec.TfrmGenFacRec.chkDuplicar.Caption',
   'es-ES',
   'Duplicar Borrador',
   'src/Modals/inMtoModalFacRec.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalFacRec.TfrmGenFacRec.cxlbl8.Caption',
   'es-ES',
   'Serie Borrador Destino',
   'src/Modals/inMtoModalFacRec.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalFacRec.TfrmGenFacRec.cxlbl2.Caption',
   'es-ES',
   'Fecha Borrador Destino',
   'src/Modals/inMtoModalFacRec.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalFacturarAlbaranes.TfrmModalFacturarAlbaranes.Caption',
   'es-ES',
   'Crear borradores de compra',
   'src/Modals/inMtoModalFacturarAlbaranes.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalFacturarAlbaranes.TfrmModalFacturarAlbaranes.lblEmpresa.Caption',
   'es-ES',
   'Empresa',
   'src/Modals/inMtoModalFacturarAlbaranes.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoModalFacturarAlbaranes.TfrmModalFacturarAlbaranes.lblProveedor.Ca',
     'ption'
   ),
   'es-ES',
   'Proveedor',
   'src/Modals/inMtoModalFacturarAlbaranes.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalFacturarAlbaranes.TfrmModalFacturarAlbaranes.btnCargar.Caption',
   'es-ES',
   'Cargar',
   'src/Modals/inMtoModalFacturarAlbaranes.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoModalFacturarAlbaranes.TfrmModalFacturarAlbaranes.lblNombrePrv.Ca',
     'ption'
   ),
   'es-ES',
   ' ',
   'src/Modals/inMtoModalFacturarAlbaranes.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalFacturarAlbaranes.TfrmModalFacturarAlbaranes.rgModo.Caption',
   'es-ES',
   ' Modo ',
   'src/Modals/inMtoModalFacturarAlbaranes.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoModalFacturarAlbaranes.TfrmModalFacturarAlbaranes.rgModo.Properti',
     'es.Items[0].Caption'
   ),
   'es-ES',
   'Crear borrador nuevo',
   'src/Modals/inMtoModalFacturarAlbaranes.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoModalFacturarAlbaranes.TfrmModalFacturarAlbaranes.rgModo.Properti',
     'es.Items[1].Caption'
   ),
   'es-ES',
   'Incorporar a un borrador existente',
   'src/Modals/inMtoModalFacturarAlbaranes.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoModalFacturarAlbaranes.TfrmModalFacturarAlbaranes.lblFacExistente',
     '.Caption'
   ),
   'es-ES',
   'Borrador existente',
   'src/Modals/inMtoModalFacturarAlbaranes.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoModalFacturarAlbaranes.TfrmModalFacturarAlbaranes.colAlbNumero.Ca',
     'ption'
   ),
   'es-ES',
   'Numero',
   'src/Modals/inMtoModalFacturarAlbaranes.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalFacturarAlbaranes.TfrmModalFacturarAlbaranes.colAlbSerie.Caption',
   'es-ES',
   'Serie',
   'src/Modals/inMtoModalFacturarAlbaranes.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalFacturarAlbaranes.TfrmModalFacturarAlbaranes.colAlbFecha.Caption',
   'es-ES',
   'Fecha',
   'src/Modals/inMtoModalFacturarAlbaranes.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoModalFacturarAlbaranes.TfrmModalFacturarAlbaranes.colAlbRefPrv.Ca',
     'ption'
   ),
   'es-ES',
   'Ref. proveedor',
   'src/Modals/inMtoModalFacturarAlbaranes.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalFacturarAlbaranes.TfrmModalFacturarAlbaranes.colAlbTotal.Caption',
   'es-ES',
   'Total liquido',
   'src/Modals/inMtoModalFacturarAlbaranes.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalFacturarAlbaranes.TfrmModalFacturarAlbaranes.btnSalir.Caption',
   'es-ES',
   '&Salir',
   'src/Modals/inMtoModalFacturarAlbaranes.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalFacturarAlbaranes.TfrmModalFacturarAlbaranes.btnFacturar.Caption',
   'es-ES',
   '&Crear borradores',
   'src/Modals/inMtoModalFacturarAlbaranes.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalFacturarAlbaranesFechas.TfrmModalFacturarAlbaranesFechas.Caption',
   'es-ES',
   'Crear borradores por fechas / serie',
   'src/Modals/inMtoModalFacturarAlbaranesFechas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoModalFacturarAlbaranesFechas.TfrmModalFacturarAlbaranesFechas.lbl',
     'Serie.Caption'
   ),
   'es-ES',
   'Serie albarán',
   'src/Modals/inMtoModalFacturarAlbaranesFechas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoModalFacturarAlbaranesFechas.TfrmModalFacturarAlbaranesFechas.lbl',
     'FechaDesde.Caption'
   ),
   'es-ES',
   'Fecha desde',
   'src/Modals/inMtoModalFacturarAlbaranesFechas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoModalFacturarAlbaranesFechas.TfrmModalFacturarAlbaranesFechas.lbl',
     'FechaHasta.Caption'
   ),
   'es-ES',
   'Fecha hasta',
   'src/Modals/inMtoModalFacturarAlbaranesFechas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoModalFacturarAlbaranesFechas.TfrmModalFacturarAlbaranesFechas.chk',
     'AgruparPorCliente.Caption'
   ),
   'es-ES',
   'Un borrador por cliente (consolidar)',
   'src/Modals/inMtoModalFacturarAlbaranesFechas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoModalFacturarAlbaranesFechas.TfrmModalFacturarAlbaranesFechas.btn',
     'Buscar.Caption'
   ),
   'es-ES',
   'Buscar',
   'src/Modals/inMtoModalFacturarAlbaranesFechas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoModalFacturarAlbaranesFechas.TfrmModalFacturarAlbaranesFechas.col',
     'Sel.Caption'
   ),
   'es-ES',
   'Sel.',
   'src/Modals/inMtoModalFacturarAlbaranesFechas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoModalFacturarAlbaranesFechas.TfrmModalFacturarAlbaranesFechas.col',
     'Numero.Caption'
   ),
   'es-ES',
   'Número',
   'src/Modals/inMtoModalFacturarAlbaranesFechas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoModalFacturarAlbaranesFechas.TfrmModalFacturarAlbaranesFechas.col',
     'Serie.Caption'
   ),
   'es-ES',
   'Serie',
   'src/Modals/inMtoModalFacturarAlbaranesFechas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoModalFacturarAlbaranesFechas.TfrmModalFacturarAlbaranesFechas.col',
     'Fecha.Caption'
   ),
   'es-ES',
   'Fecha',
   'src/Modals/inMtoModalFacturarAlbaranesFechas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoModalFacturarAlbaranesFechas.TfrmModalFacturarAlbaranesFechas.col',
     'Cliente.Caption'
   ),
   'es-ES',
   'Cód. Cliente',
   'src/Modals/inMtoModalFacturarAlbaranesFechas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoModalFacturarAlbaranesFechas.TfrmModalFacturarAlbaranesFechas.col',
     'RazonSocial.Caption'
   ),
   'es-ES',
   'Razón Social',
   'src/Modals/inMtoModalFacturarAlbaranesFechas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoModalFacturarAlbaranesFechas.TfrmModalFacturarAlbaranesFechas.col',
     'Total.Caption'
   ),
   'es-ES',
   'Total',
   'src/Modals/inMtoModalFacturarAlbaranesFechas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoModalFacturarAlbaranesFechas.TfrmModalFacturarAlbaranesFechas.lbl',
     'Estado.Caption'
   ),
   'es-ES',
   'Listo',
   'src/Modals/inMtoModalFacturarAlbaranesFechas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoModalFacturarAlbaranesFechas.TfrmModalFacturarAlbaranesFechas.btn',
     'SeleccionarTodos.Caption'
   ),
   'es-ES',
   'Marcar / Desmarcar',
   'src/Modals/inMtoModalFacturarAlbaranesFechas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoModalFacturarAlbaranesFechas.TfrmModalFacturarAlbaranesFechas.btn',
     'Facturar.Caption'
   ),
   'es-ES',
   'Generar borradores',
   'src/Modals/inMtoModalFacturarAlbaranesFechas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoModalFacturarAlbaranesFechas.TfrmModalFacturarAlbaranesFechas.btn',
     'Cerrar.Caption'
   ),
   'es-ES',
   'Cerrar',
   'src/Modals/inMtoModalFacturarAlbaranesFechas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalFacturarTicket.TfrmModalFacturarTicket.Caption',
   'es-ES',
   'Crear borrador normal del ticket',
   'src/Modals/inMtoModalFacturarTicket.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalFacturarTicket.TfrmModalFacturarTicket.lblTicket.Caption',
   'es-ES',
   'Ticket:',
   'src/Modals/inMtoModalFacturarTicket.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalFacturarTicket.TfrmModalFacturarTicket.lblCliente.Caption',
   'es-ES',
   'Cliente:',
   'src/Modals/inMtoModalFacturarTicket.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalFacturarTicket.TfrmModalFacturarTicket.lblSerie.Caption',
   'es-ES',
   'Serie borrador:',
   'src/Modals/inMtoModalFacturarTicket.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoModalFacturarTicket.TfrmModalFacturarTicket.cbbSerie.Properties.L',
     'istColumns[0].Caption'
   ),
   'es-ES',
   'Serie',
   'src/Modals/inMtoModalFacturarTicket.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalFacturarTicket.TfrmModalFacturarTicket.lblFecha.Caption',
   'es-ES',
   'Fecha borrador:',
   'src/Modals/inMtoModalFacturarTicket.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalFacturarTicket.TfrmModalFacturarTicket.btnCancelar.Caption',
   'es-ES',
   '&Cancelar (ESC)',
   'src/Modals/inMtoModalFacturarTicket.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalFacturarTicket.TfrmModalFacturarTicket.btnGenerar.Caption',
   'es-ES',
   '&Generar borrador',
   'src/Modals/inMtoModalFacturarTicket.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema')
ON DUPLICATE KEY UPDATE
  `TEXTO_TRAD` = VALUES(`TEXTO_TRAD`),
  `CONTEXTO_TRAD` = VALUES(`CONTEXTO_TRAD`),
  `ESACTIVO_TRAD` = VALUES(`ESACTIVO_TRAD`),
  `INSTANTE_MODIF` = CURRENT_TIMESTAMP,
  `USUARIO_MODIF` = VALUES(`USUARIO_ALTA`);
