-- Catálogo de textos españoles extraídos de los DFM.
-- Generado por generar_traducciones_dfm.ps1.
INSERT INTO `fza_traducciones` (
  `CLAVE_TRAD`, `IDIOMA_TRAD`, `TEXTO_TRAD`, `CONTEXTO_TRAD`,
  `ESACTIVO_TRAD`, `INSTANTE_ALTA`, `USUARIO_ALTA`
) VALUES
  ('inMtoAppParam.TfrmMtoAppParam.Caption',
   'es-ES',
   'Parámetros Generales de la Aplicación',
   'src/Core/inMtoAppParam.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAppParam.TfrmMtoAppParam.btnGuardar.Caption',
   'es-ES',
   '&Guardar (F12)',
   'src/Core/inMtoAppParam.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAppParam.TfrmMtoAppParam.actGuardar.Caption',
   'es-ES',
   'Guardar',
   'src/Core/inMtoAppParam.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAppParam.TfrmMtoAppParam.actSalir.Caption',
   'es-ES',
   'Salir',
   'src/Core/inMtoAppParam.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAppParam.TfrmMtoAppParam.actGuardarLayout.Caption',
   'es-ES',
   'Guardar Layout',
   'src/Core/inMtoAppParam.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoFrmBase.TfrmBase.Caption',
   'es-ES',
   'frmBase',
   'src/Core/inMtoFrmBase.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoLogon.TfrmLogon.Caption',
   'es-ES',
   'Login FactuZam',
   'src/Core/inMtoLogon.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoLogon.TfrmLogon.lblUsuario.Caption',
   'es-ES',
   'Usuario',
   'src/Core/inMtoLogon.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoLogon.TfrmLogon.lblContrasena.Caption',
   'es-ES',
   'Contraseña',
   'src/Core/inMtoLogon.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoLogon.TfrmLogon.chkRememberUser.Caption',
   'es-ES',
   'Recordar Usuario',
   'src/Core/inMtoLogon.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoLogon.TfrmLogon.chkRememberPassword.Caption',
   'es-ES',
   'Recordar Contraseña',
   'src/Core/inMtoLogon.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoLogon.TfrmLogon.btnAceptar.Caption',
   'es-ES',
   '&Aceptar (F12)',
   'src/Core/inMtoLogon.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoLogon.TfrmLogon.btnSalir.Caption',
   'es-ES',
   '&Salir (Esc)',
   'src/Core/inMtoLogon.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoLogon.TfrmLogon.chkAuto.Caption',
   'es-ES',
   'Arranque sin login',
   'src/Core/inMtoLogon.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoLogon.TfrmLogon.btnConf.Caption',
   'es-ES',
   'Configurar &Base de Datos ->',
   'src/Core/inMtoLogon.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoLogon.TfrmLogon.lblBBDDConfig.Caption',
   'es-ES',
   'Configuración BBDD',
   'src/Core/inMtoLogon.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoLogon.TfrmLogon.lblHostBBDD.Caption',
   'es-ES',
   'Host:',
   'src/Core/inMtoLogon.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoLogon.TfrmLogon.lblPortHost.Caption',
   'es-ES',
   'Puerto:',
   'src/Core/inMtoLogon.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoLogon.TfrmLogon.lblNomBBDD.Caption',
   'es-ES',
   'Nombre BD:',
   'src/Core/inMtoLogon.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoLogon.TfrmLogon.lblUserBBDD.Caption',
   'es-ES',
   'Usuario:',
   'src/Core/inMtoLogon.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoLogon.TfrmLogon.btnTest.Caption',
   'es-ES',
   'Proba&r Conexión',
   'src/Core/inMtoLogon.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoLogon.TfrmLogon.btnSubirScript.Caption',
   'es-ES',
   '&Subir script',
   'src/Core/inMtoLogon.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoLogon.TfrmLogon.btnCopiaSeguridad.Caption',
   'es-ES',
   '&Copia seguridad',
   'src/Core/inMtoLogon.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoLogon.TfrmLogon.btnRecover.Caption',
   'es-ES',
   '&Restaurar Copia',
   'src/Core/inMtoLogon.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPreviewExcel.TfrmMtoPreviewExcel.Caption',
   'es-ES',
   'Previsualización Excel',
   'src/Core/inMtoPreviewExcel.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPreviewExcel.TfrmMtoPreviewExcel.btnGuardar.Caption',
   'es-ES',
   'Guardar Excel',
   'src/Core/inMtoPreviewExcel.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPreviewExcel.TfrmMtoPreviewExcel.btnCerrar.Caption',
   'es-ES',
   'Cerrar (ESC)',
   'src/Core/inMtoPreviewExcel.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPreviewExcel.TfrmMtoPreviewExcel.DialogoGuardar.Title',
   'es-ES',
   'Guardar Excel',
   'src/Core/inMtoPreviewExcel.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPreviewExcel.TfrmMtoPreviewExcel.actSalir.Caption',
   'es-ES',
   'Salir',
   'src/Core/inMtoPreviewExcel.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPreviewTicket.TFormVisualizador.Caption',
   'es-ES',
   'Ticket  |  F8 Imprimir  |  F7 PDF  |  F6 PNG  |  ESC Salir',
   'src/Core/inMtoPreviewTicket.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPreviewTicket.TFormVisualizador.btnCerrar.Caption',
   'es-ES',
   'ESC Cerrar',
   'src/Core/inMtoPreviewTicket.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPreviewTicket.TFormVisualizador.btnImprimir.Caption',
   'es-ES',
   'F8 Imprimir',
   'src/Core/inMtoPreviewTicket.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPreviewTicket.TFormVisualizador.btnPDF.Caption',
   'es-ES',
   'F7 PDF',
   'src/Core/inMtoPreviewTicket.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPreviewTicket.TFormVisualizador.btnPNG.Caption',
   'es-ES',
   'F6 PNG',
   'src/Core/inMtoPreviewTicket.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPreviewTicket.TFormVisualizador.btnImprimirTicket.Caption',
   'es-ES',
   'F5 Imprimir Ticket',
   'src/Core/inMtoPreviewTicket.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPrincipal.TfrmMtoPrincipal.Caption',
   'es-ES',
   'Fzam',
   'src/Core/inMtoPrincipal.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPrincipal.TfrmMtoPrincipal.Archivo1.Caption',
   'es-ES',
   'Archivo',
   'src/Core/inMtoPrincipal.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPrincipal.TfrmMtoPrincipal.mnuEmpresas.Caption',
   'es-ES',
   'Empresas',
   'src/Core/inMtoPrincipal.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPrincipal.TfrmMtoPrincipal.mnuAlmacenes.Caption',
   'es-ES',
   '&Almacenes',
   'src/Core/inMtoPrincipal.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPrincipal.TfrmMtoPrincipal.mnuClientes.Caption',
   'es-ES',
   'Clientes',
   'src/Core/inMtoPrincipal.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPrincipal.TfrmMtoPrincipal.mnuProveedores.Caption',
   'es-ES',
   'Proveedores',
   'src/Core/inMtoPrincipal.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPrincipal.TfrmMtoPrincipal.mnuArticulos.Caption',
   'es-ES',
   'Artículos',
   'src/Core/inMtoPrincipal.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPrincipal.TfrmMtoPrincipal.ablasAuxiliares1.Caption',
   'es-ES',
   'Tablas Auxiliares',
   'src/Core/inMtoPrincipal.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPrincipal.TfrmMtoPrincipal.mnuTarifas.Caption',
   'es-ES',
   'Tarifas',
   'src/Core/inMtoPrincipal.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPrincipal.TfrmMtoPrincipal.mnuFamilias.Caption',
   'es-ES',
   'Familias',
   'src/Core/inMtoPrincipal.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPrincipal.TfrmMtoPrincipal.mnuPaises.Caption',
   'es-ES',
   'Paises',
   'src/Core/inMtoPrincipal.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPrincipal.TfrmMtoPrincipal.mnuUnidadesMedida.Caption',
   'es-ES',
   'Unidades de Medida',
   'src/Core/inMtoPrincipal.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPrincipal.TfrmMtoPrincipal.mnuPropiedades.Caption',
   'es-ES',
   'Propiedades',
   'src/Core/inMtoPrincipal.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPrincipal.TfrmMtoPrincipal.mnuVariaciones.Caption',
   'es-ES',
   'Tipos de Variaciones',
   'src/Core/inMtoPrincipal.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPrincipal.TfrmMtoPrincipal.mnuAtributosConjuntos.Caption',
   'es-ES',
   'Colecciones de Atributos',
   'src/Core/inMtoPrincipal.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPrincipal.TfrmMtoPrincipal.mnuAtributosBasicos.Caption',
   'es-ES',
   'Atributos básicos',
   'src/Core/inMtoPrincipal.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPrincipal.TfrmMtoPrincipal.mnuInvocarLogin.Caption',
   'es-ES',
   'Invocar login',
   'src/Core/inMtoPrincipal.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPrincipal.TfrmMtoPrincipal.Salir1.Caption',
   'es-ES',
   'Salir',
   'src/Core/inMtoPrincipal.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPrincipal.TfrmMtoPrincipal.Compras1.Caption',
   'es-ES',
   'Compras',
   'src/Core/inMtoPrincipal.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPrincipal.TfrmMtoPrincipal.Sesiones1.Caption',
   'es-ES',
   'Sesiones',
   'src/Core/inMtoPrincipal.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPrincipal.TfrmMtoPrincipal.mnuCrearArtculosyunpedidoounalbarn.Caption',
   'es-ES',
   'Crear artículos y un pedido o un albarán',
   'src/Core/inMtoPrincipal.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPrincipal.TfrmMtoPrincipal.Pedidos1.Caption',
   'es-ES',
   'Pedidos',
   'src/Core/inMtoPrincipal.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPrincipal.TfrmMtoPrincipal.Albaranes1.Caption',
   'es-ES',
   'Albaranes',
   'src/Core/inMtoPrincipal.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPrincipal.TfrmMtoPrincipal.Devoluciones1.Caption',
   'es-ES',
   'Devoluciones a Proveedor',
   'src/Core/inMtoPrincipal.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPrincipal.TfrmMtoPrincipal.FacturarAlbaranes1.Caption',
   'es-ES',
   'Crear borradores de albaranes...',
   'src/Core/inMtoPrincipal.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPrincipal.TfrmMtoPrincipal.Facturas1.Caption',
   'es-ES',
   'Borradores',
   'src/Core/inMtoPrincipal.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPrincipal.TfrmMtoPrincipal.EfectosCompra1.Caption',
   'es-ES',
   'Efectos de pago',
   'src/Core/inMtoPrincipal.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPrincipal.TfrmMtoPrincipal.RemesasCompra1.Caption',
   'es-ES',
   'Remesas de pago',
   'src/Core/inMtoPrincipal.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPrincipal.TfrmMtoPrincipal.CargarEfectos1.Caption',
   'es-ES',
   'Cargar efectos en remesa...',
   'src/Core/inMtoPrincipal.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPrincipal.TfrmMtoPrincipal.mnuComprasListados.Caption',
   'es-ES',
   'Listados',
   'src/Core/inMtoPrincipal.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPrincipal.TfrmMtoPrincipal.mnuListadoDocsProveedor.Caption',
   'es-ES',
   'Listado de documentos proveedor',
   'src/Core/inMtoPrincipal.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPrincipal.TfrmMtoPrincipal.mnuListadoEfectosPago.Caption',
   'es-ES',
   'Listado de efectos de pago',
   'src/Core/inMtoPrincipal.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPrincipal.TfrmMtoPrincipal.Ventas1.Caption',
   'es-ES',
   'Ventas Mayor',
   'src/Core/inMtoPrincipal.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPrincipal.TfrmMtoPrincipal.mnuPedidosVenta.Caption',
   'es-ES',
   '&Pedidos',
   'src/Core/inMtoPrincipal.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPrincipal.TfrmMtoPrincipal.mnuAlbaranesVenta.Caption',
   'es-ES',
   '&Albaranes',
   'src/Core/inMtoPrincipal.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPrincipal.TfrmMtoPrincipal.mnuFacturas.Caption',
   'es-ES',
   'Borradores',
   'src/Core/inMtoPrincipal.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPrincipal.TfrmMtoPrincipal.EfectosVenta1.Caption',
   'es-ES',
   'Efectos de cobro',
   'src/Core/inMtoPrincipal.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPrincipal.TfrmMtoPrincipal.RemesasVenta1.Caption',
   'es-ES',
   'Remesas de cobro',
   'src/Core/inMtoPrincipal.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPrincipal.TfrmMtoPrincipal.CargarEfectosVenta1.Caption',
   'es-ES',
   'Cargar efectos en remesa...',
   'src/Core/inMtoPrincipal.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPrincipal.TfrmMtoPrincipal.Listados1.Caption',
   'es-ES',
   'Listados',
   'src/Core/inMtoPrincipal.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPrincipal.TfrmMtoPrincipal.mnuLisVentas.Caption',
   'es-ES',
   '&Ventas',
   'src/Core/inMtoPrincipal.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPrincipal.TfrmMtoPrincipal.mnuCaja.Caption',
   'es-ES',
   '&TPV',
   'src/Core/inMtoPrincipal.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPrincipal.TfrmMtoPrincipal.mnuMenuCaja.Caption',
   'es-ES',
   'Menú de Caja',
   'src/Core/inMtoPrincipal.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPrincipal.TfrmMtoPrincipal.mnuTPVListados.Caption',
   'es-ES',
   'Listados',
   'src/Core/inMtoPrincipal.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPrincipal.TfrmMtoPrincipal.mnuListadoOperacionesVenta.Caption',
   'es-ES',
   'Listado de operaciones de venta',
   'src/Core/inMtoPrincipal.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPrincipal.TfrmMtoPrincipal.mnuCajaParam.Caption',
   'es-ES',
   '&Parámetros de Caja',
   'src/Core/inMtoPrincipal.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPrincipal.TfrmMtoPrincipal.FormasdePagoCaja1.Caption',
   'es-ES',
   'Formas de Pago Caja',
   'src/Core/inMtoPrincipal.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPrincipal.TfrmMtoPrincipal.mnuDepositosCliente.Caption',
   'es-ES',
   'Depósitos de Clientes',
   'src/Core/inMtoPrincipal.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPrincipal.TfrmMtoPrincipal.mnuCajaPagosHist.Caption',
   'es-ES',
   'Histórico de Pagos de Caja',
   'src/Core/inMtoPrincipal.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPrincipal.TfrmMtoPrincipal.mnuCajaValesHist.Caption',
   'es-ES',
   'Histórico de Vales',
   'src/Core/inMtoPrincipal.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPrincipal.TfrmMtoPrincipal.mnuCajaOperacionesHist.Caption',
   'es-ES',
   'Histórico de Operaciones',
   'src/Core/inMtoPrincipal.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPrincipal.TfrmMtoPrincipal.mnuCajaArqueosHist.Caption',
   'es-ES',
   'Histórico de Arqueos',
   'src/Core/inMtoPrincipal.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPrincipal.TfrmMtoPrincipal.mnuFacturasSimplif.Caption',
   'es-ES',
   'Borradores Simplificados',
   'src/Core/inMtoPrincipal.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPrincipal.TfrmMtoPrincipal.mnuAlmacen.Caption',
   'es-ES',
   'Almacén',
   'src/Core/inMtoPrincipal.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPrincipal.TfrmMtoPrincipal.Movimientosdealmacn1.Caption',
   'es-ES',
   'Movimientos de almacén',
   'src/Core/inMtoPrincipal.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPrincipal.TfrmMtoPrincipal.mnuInventarios.Caption',
   'es-ES',
   'Inventarios',
   'src/Core/inMtoPrincipal.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPrincipal.TfrmMtoPrincipal.mnuDocumentosTrabajo.Caption',
   'es-ES',
   'Documentos de Trabajo',
   'src/Core/inMtoPrincipal.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPrincipal.TfrmMtoPrincipal.mnuAlmacenInformes.Caption',
   'es-ES',
   'Informes',
   'src/Core/inMtoPrincipal.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPrincipal.TfrmMtoPrincipal.mnuBalanceAlmacenHorizontal.Caption',
   'es-ES',
   'Balance de Almacén Horizontal',
   'src/Core/inMtoPrincipal.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPrincipal.TfrmMtoPrincipal.mnuBalanceAlmacenSinTallas.Caption',
   'es-ES',
   'Balance de Almacén sin tallas',
   'src/Core/inMtoPrincipal.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPrincipal.TfrmMtoPrincipal.mnuMovVentasArt.Caption',
   'es-ES',
   'Movimientos de ventas por artículos y fechas',
   'src/Core/inMtoPrincipal.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPrincipal.TfrmMtoPrincipal.Utilidades1.Caption',
   'es-ES',
   'Otros',
   'src/Core/inMtoPrincipal.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPrincipal.TfrmMtoPrincipal.mnuParmetrosdeEntorno.Caption',
   'es-ES',
   'Parámetros del entorno',
   'src/Core/inMtoPrincipal.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPrincipal.TfrmMtoPrincipal.mnuGruposdeIVA.Caption',
   'es-ES',
   'Grupos de IVA',
   'src/Core/inMtoPrincipal.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPrincipal.TfrmMtoPrincipal.mnuIvas.Caption',
   'es-ES',
   'Impuesto IVA',
   'src/Core/inMtoPrincipal.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPrincipal.TfrmMtoPrincipal.mnuContadores.Caption',
   'es-ES',
   'Contadores',
   'src/Core/inMtoPrincipal.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPrincipal.TfrmMtoPrincipal.Formasdepago2.Caption',
   'es-ES',
   'Formas de pago documentos',
   'src/Core/inMtoPrincipal.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPrincipal.TfrmMtoPrincipal.UsuariosGruposyPerfiles1.Caption',
   'es-ES',
   'Usuarios, Grupos y Perfiles',
   'src/Core/inMtoPrincipal.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPrincipal.TfrmMtoPrincipal.mnuUsuarios.Caption',
   'es-ES',
   'Usuarios',
   'src/Core/inMtoPrincipal.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPrincipal.TfrmMtoPrincipal.mnuEmpleados.Caption',
   'es-ES',
   'Empleados',
   'src/Core/inMtoPrincipal.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPrincipal.TfrmMtoPrincipal.mnuGrupos.Caption',
   'es-ES',
   'Grupos',
   'src/Core/inMtoPrincipal.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPrincipal.TfrmMtoPrincipal.mnuPerfiles.Caption',
   'es-ES',
   'Perfiles',
   'src/Core/inMtoPrincipal.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPrincipal.TfrmMtoPrincipal.mnuPermisos.Caption',
   'es-ES',
   'Permisos',
   'src/Core/inMtoPrincipal.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPrincipal.TfrmMtoPrincipal.mnuPermisosTabla.Caption',
   'es-ES',
   'Permisos (tabla)',
   'src/Core/inMtoPrincipal.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPrincipal.TfrmMtoPrincipal.HacerCopiadeSeguridad1.Caption',
   'es-ES',
   'Hacer Copia de Seguridad',
   'src/Core/inMtoPrincipal.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPrincipal.TfrmMtoPrincipal.mnuEjecutarScript.Caption',
   'es-ES',
   'Recuperar Copia de Seguridad',
   'src/Core/inMtoPrincipal.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPrincipal.TfrmMtoPrincipal.mnuGeneradorProcesos.Caption',
   'es-ES',
   'Generador de Procesos',
   'src/Core/inMtoPrincipal.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPrincipal.TfrmMtoPrincipal.mnuVerifactu.Caption',
   'es-ES',
   '&Verifactu',
   'src/Core/inMtoPrincipal.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPrincipal.TfrmMtoPrincipal.mnuVerifactuDeclaracion.Caption',
   'es-ES',
   'Declaración Responsable',
   'src/Core/inMtoPrincipal.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPrincipal.TfrmMtoPrincipal.mnuVerifactuCola.Caption',
   'es-ES',
   'Cola de Envíos',
   'src/Core/inMtoPrincipal.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPrincipal.TfrmMtoPrincipal.mnuVerifactuLog.Caption',
   'es-ES',
   'Verifactu Log',
   'src/Core/inMtoPrincipal.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPrincipal.TfrmMtoPrincipal.Ayuda1.Caption',
   'es-ES',
   'Ayuda',
   'src/Core/inMtoPrincipal.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPrincipal.TfrmMtoPrincipal.mnuConsultaStocks.Caption',
   'es-ES',
   'Consulta de stocks',
   'src/Core/inMtoPrincipal.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPrincipal.TfrmMtoPrincipal.mnuArticulosSimilares.Caption',
   'es-ES',
   'Consulta de artículos similares',
   'src/Core/inMtoPrincipal.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPrincipal.TfrmMtoPrincipal.mnuManualWeb.Caption',
   'es-ES',
   'Manual web',
   'src/Core/inMtoPrincipal.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPrincipal.TfrmMtoPrincipal.mnuForoSoporte.Caption',
   'es-ES',
   'Foro de soporte',
   'src/Core/inMtoPrincipal.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPrincipal.TfrmMtoPrincipal.Acercade1.Caption',
   'es-ES',
   'Acerca de',
   'src/Core/inMtoPrincipal.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoSplash.TfrmSplash.cxLabel1.Caption',
   'es-ES',
   CONCAT(
     'Dedicado a mis hermanas, a mi mentor y maestro en programación ',
     'J.F.Criado, a mi compañera Ana M. y un especial agradecimiento a  la ',
     'Biblioteca Pública de Zamora.'
   ),
   'src/Core/inMtoSplash.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoSplash.TfrmSplash.cxLabel2.Caption',
   'es-ES',
   'Contacto con el autor',
   'src/Core/inMtoSplash.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoSplash.TfrmSplash.btnAceptar.Caption',
   'es-ES',
   'Aceptar',
   'src/Core/inMtoSplash.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema')
ON DUPLICATE KEY UPDATE
  `TEXTO_TRAD` = VALUES(`TEXTO_TRAD`),
  `CONTEXTO_TRAD` = VALUES(`CONTEXTO_TRAD`),
  `ESACTIVO_TRAD` = VALUES(`ESACTIVO_TRAD`),
  `INSTANTE_MODIF` = CURRENT_TIMESTAMP,
  `USUARIO_MODIF` = VALUES(`USUARIO_ALTA`);
