-- D24: textos dinámicos del inspector de parámetros generales.
-- Los idiomas nuevos se añaden al catálogo sin cambiar el formulario.
INSERT INTO `fza_traducciones` (
  `CLAVE_TRAD`, `IDIOMA_TRAD`, `TEXTO_TRAD`, `CONTEXTO_TRAD`,
  `ESACTIVO_TRAD`, `INSTANTE_ALTA`, `USUARIO_ALTA`
) VALUES
  ('inMtoAppParam.Parametros.Categoria.Directorios',
   'es-ES', 'Directorios',
   'src/Core/inMtoAppParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoAppParam.Parametros.Categoria.Directorios',
   'ca-ES', 'Directoris',
   'src/Core/inMtoAppParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoAppParam.Parametros.Categoria.Directorios',
   'en-GB', 'Directories',
   'src/Core/inMtoAppParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoAppParam.Parametros.Categoria.Fotos',
   'es-ES', 'Fotos',
   'src/Core/inMtoAppParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoAppParam.Parametros.Categoria.Fotos',
   'ca-ES', 'Fotos',
   'src/Core/inMtoAppParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoAppParam.Parametros.Categoria.Fotos',
   'en-GB', 'Photos',
   'src/Core/inMtoAppParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoAppParam.Parametros.Categoria.Serviciosweb',
   'es-ES', 'Servicios web',
   'src/Core/inMtoAppParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoAppParam.Parametros.Categoria.Serviciosweb',
   'ca-ES', 'Serveis web',
   'src/Core/inMtoAppParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoAppParam.Parametros.Categoria.Serviciosweb',
   'en-GB', 'Web Services',
   'src/Core/inMtoAppParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoAppParam.Parametros.Categoria.Impresion',
   'es-ES', 'Impresión',
   'src/Core/inMtoAppParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoAppParam.Parametros.Categoria.Impresion',
   'ca-ES', 'Impressió',
   'src/Core/inMtoAppParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoAppParam.Parametros.Categoria.Impresion',
   'en-GB', 'Printing',
   'src/Core/inMtoAppParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoAppParam.Parametros.Categoria.Exportacion',
   'es-ES', 'Exportación',
   'src/Core/inMtoAppParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoAppParam.Parametros.Categoria.Exportacion',
   'ca-ES', 'Exportació',
   'src/Core/inMtoAppParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoAppParam.Parametros.Categoria.Exportacion',
   'en-GB', 'Export',
   'src/Core/inMtoAppParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoAppParam.Parametros.Categoria.Apariencia',
   'es-ES', 'Apariencia',
   'src/Core/inMtoAppParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoAppParam.Parametros.Categoria.Apariencia',
   'ca-ES', 'Aparença',
   'src/Core/inMtoAppParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoAppParam.Parametros.Categoria.Apariencia',
   'en-GB', 'Appearance',
   'src/Core/inMtoAppParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoAppParam.Parametros.Categoria.ConsultadeStock',
   'es-ES', 'Consulta de Stock',
   'src/Core/inMtoAppParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoAppParam.Parametros.Categoria.ConsultadeStock',
   'ca-ES', 'Consulta d''estoc',
   'src/Core/inMtoAppParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoAppParam.Parametros.Categoria.ConsultadeStock',
   'en-GB', 'Stock Query',
   'src/Core/inMtoAppParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoAppParam.Parametros.Categoria.Valorespordefecto',
   'es-ES', 'Valores por defecto',
   'src/Core/inMtoAppParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoAppParam.Parametros.Categoria.Valorespordefecto',
   'ca-ES', 'Valors per defecte',
   'src/Core/inMtoAppParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoAppParam.Parametros.Categoria.Valorespordefecto',
   'en-GB', 'Default Values',
   'src/Core/inMtoAppParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoAppParam.Parametros.Categoria.Seguridad',
   'es-ES', 'Seguridad',
   'src/Core/inMtoAppParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoAppParam.Parametros.Categoria.Seguridad',
   'ca-ES', 'Seguretat',
   'src/Core/inMtoAppParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoAppParam.Parametros.Categoria.Seguridad',
   'en-GB', 'Security',
   'src/Core/inMtoAppParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoAppParam.Parametros.Categoria.Arranque',
   'es-ES', 'Arranque',
   'src/Core/inMtoAppParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoAppParam.Parametros.Categoria.Arranque',
   'ca-ES', 'Inici',
   'src/Core/inMtoAppParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoAppParam.Parametros.Categoria.Arranque',
   'en-GB', 'Startup',
   'src/Core/inMtoAppParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoAppParam.Parametros.Categoria.Verifactu',
   'es-ES', 'Verifactu',
   'src/Core/inMtoAppParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoAppParam.Parametros.Categoria.Verifactu',
   'ca-ES', 'Verifactu',
   'src/Core/inMtoAppParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoAppParam.Parametros.Categoria.Verifactu',
   'en-GB', 'Verifactu',
   'src/Core/inMtoAppParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoAppParam.Parametros.Categoria.Log',
   'es-ES', 'Log',
   'src/Core/inMtoAppParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoAppParam.Parametros.Categoria.Log',
   'ca-ES', 'Registre',
   'src/Core/inMtoAppParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoAppParam.Parametros.Categoria.Log',
   'en-GB', 'Log',
   'src/Core/inMtoAppParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoAppParam.Parametros.appDirPDF.Descripcion',
   'es-ES', 'Carpeta donde se guardan los PDFs',
   'src/Core/inMtoAppParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoAppParam.Parametros.appDirPDF.Descripcion',
   'ca-ES', 'Carpeta on es desen els PDF',
   'src/Core/inMtoAppParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoAppParam.Parametros.appDirPDF.Descripcion',
   'en-GB', 'Folder where PDF files are saved',
   'src/Core/inMtoAppParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoAppParam.Parametros.appDirExcel.Descripcion',
   'es-ES', 'Carpeta donde se guardan los Excels',
   'src/Core/inMtoAppParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoAppParam.Parametros.appDirExcel.Descripcion',
   'ca-ES', 'Carpeta on es desen els fitxers Excel',
   'src/Core/inMtoAppParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoAppParam.Parametros.appDirExcel.Descripcion',
   'en-GB', 'Folder where Excel files are saved',
   'src/Core/inMtoAppParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoAppParam.Parametros.appDirCopiasSeguridad.Descripcion',
   'es-ES', 'Carpeta de Copias de seguridad',
   'src/Core/inMtoAppParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoAppParam.Parametros.appDirCopiasSeguridad.Descripcion',
   'ca-ES', 'Carpeta de còpies de seguretat',
   'src/Core/inMtoAppParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoAppParam.Parametros.appDirCopiasSeguridad.Descripcion',
   'en-GB', 'Backup folder',
   'src/Core/inMtoAppParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoAppParam.Parametros.appDirHistoricoCaja.Descripcion',
   'es-ES', 'Carpeta de Histórico de Caja',
   'src/Core/inMtoAppParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoAppParam.Parametros.appDirHistoricoCaja.Descripcion',
   'ca-ES', 'Carpeta de l''històric de caixa',
   'src/Core/inMtoAppParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoAppParam.Parametros.appDirHistoricoCaja.Descripcion',
   'en-GB', 'Register history folder',
   'src/Core/inMtoAppParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoAppParam.Parametros.appDirFotos.Descripcion',
   'es-ES', 'Carpeta de Fotos de Artículos / SKUs',
   'src/Core/inMtoAppParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoAppParam.Parametros.appDirFotos.Descripcion',
   'ca-ES', 'Carpeta de fotos d''articles / SKU',
   'src/Core/inMtoAppParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoAppParam.Parametros.appDirFotos.Descripcion',
   'en-GB', 'Item / SKU photo folder',
   'src/Core/inMtoAppParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoAppParam.Parametros.appNumAtributosFoto.Descripcion',
   'es-ES',
   'Atributos del SKU que componen la clave de foto (0 = solo artículo)',
   'src/Core/inMtoAppParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoAppParam.Parametros.appNumAtributosFoto.Descripcion',
   'ca-ES',
   'Atributs de l''SKU que componen la clau de foto (0 = només article)',
   'src/Core/inMtoAppParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoAppParam.Parametros.appNumAtributosFoto.Descripcion',
   'en-GB',
   'SKU attributes making up the photo key (0 = item only)',
   'src/Core/inMtoAppParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoAppParam.Parametros.appApiUrl.Descripcion',
   'es-ES', 'URL general del servicio web',
   'src/Core/inMtoAppParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoAppParam.Parametros.appApiUrl.Descripcion',
   'ca-ES', 'URL general del servei web',
   'src/Core/inMtoAppParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoAppParam.Parametros.appApiUrl.Descripcion',
   'en-GB', 'General web service URL',
   'src/Core/inMtoAppParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoAppParam.Parametros.appApiToken.Descripcion',
   'es-ES', 'API key / token de la instalación',
   'src/Core/inMtoAppParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoAppParam.Parametros.appApiToken.Descripcion',
   'ca-ES', 'Clau API / token de la instal·lació',
   'src/Core/inMtoAppParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoAppParam.Parametros.appApiToken.Descripcion',
   'en-GB', 'Installation API key / token',
   'src/Core/inMtoAppParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoAppParam.Parametros.appApiReferencia.Descripcion',
   'es-ES', 'Referencia global de la instalación',
   'src/Core/inMtoAppParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoAppParam.Parametros.appApiReferencia.Descripcion',
   'ca-ES', 'Referència global de la instal·lació',
   'src/Core/inMtoAppParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoAppParam.Parametros.appApiReferencia.Descripcion',
   'en-GB', 'Global installation reference',
   'src/Core/inMtoAppParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoAppParam.Parametros.appVentasWsSegundosCiclo.Descripcion',
   'es-ES', 'Segundos entre ciclos de la cola de ventas',
   'src/Core/inMtoAppParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoAppParam.Parametros.appVentasWsSegundosCiclo.Descripcion',
   'ca-ES', 'Segons entre cicles de la cua de vendes',
   'src/Core/inMtoAppParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoAppParam.Parametros.appVentasWsSegundosCiclo.Descripcion',
   'en-GB', 'Seconds between sales queue cycles',
   'src/Core/inMtoAppParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoAppParam.Parametros.appVentasWsMaxIntentos.Descripcion',
   'es-ES',
   'Reintentos antes de marcar un envío de venta en ERROR',
   'src/Core/inMtoAppParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoAppParam.Parametros.appVentasWsMaxIntentos.Descripcion',
   'ca-ES',
   'Reintents abans de marcar un enviament de venda com a ERROR',
   'src/Core/inMtoAppParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoAppParam.Parametros.appVentasWsMaxIntentos.Descripcion',
   'en-GB',
   'Retries before marking a sale submission as ERROR',
   'src/Core/inMtoAppParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoAppParam.Parametros.appImpresoraInformes.Descripcion',
   'es-ES', 'Impresora para informes',
   'src/Core/inMtoAppParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoAppParam.Parametros.appImpresoraInformes.Descripcion',
   'ca-ES', 'Impressora per als informes',
   'src/Core/inMtoAppParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoAppParam.Parametros.appImpresoraInformes.Descripcion',
   'en-GB', 'Report printer',
   'src/Core/inMtoAppParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoAppParam.Parametros.appFormatoHojaCalculo.Descripcion',
   'es-ES',
   'Formato al guardar hojas de cálculo: xlsx o xls',
   'src/Core/inMtoAppParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoAppParam.Parametros.appFormatoHojaCalculo.Descripcion',
   'ca-ES',
   'Format en desar fulls de càlcul: xlsx o xls',
   'src/Core/inMtoAppParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoAppParam.Parametros.appFormatoHojaCalculo.Descripcion',
   'en-GB',
   'Spreadsheet save format: xlsx or xls',
   'src/Core/inMtoAppParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoAppParam.Parametros.appTema.Descripcion',
   'es-ES', 'Tema de interfaz (DevExpress)',
   'src/Core/inMtoAppParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoAppParam.Parametros.appTema.Descripcion',
   'ca-ES', 'Tema de la interfície (DevExpress)',
   'src/Core/inMtoAppParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoAppParam.Parametros.appTema.Descripcion',
   'en-GB', 'Interface theme (DevExpress)',
   'src/Core/inMtoAppParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoAppParam.Parametros.appPaleta.Descripcion',
   'es-ES', 'Paleta de color del tema',
   'src/Core/inMtoAppParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoAppParam.Parametros.appPaleta.Descripcion',
   'ca-ES', 'Paleta de colors del tema',
   'src/Core/inMtoAppParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoAppParam.Parametros.appPaleta.Descripcion',
   'en-GB', 'Theme colour palette',
   'src/Core/inMtoAppParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoAppParam.Parametros.appIdioma.Descripcion',
   'es-ES',
   'Idioma de la interfaz (p. ej. es-ES, en-GB o ca-ES; '
   'qps-ploc para pruebas)',
   'src/Core/inMtoAppParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoAppParam.Parametros.appIdioma.Descripcion',
   'ca-ES',
   'Idioma de la interfície (p. ex. es-ES, en-GB o ca-ES; '
   'qps-ploc per a proves)',
   'src/Core/inMtoAppParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoAppParam.Parametros.appIdioma.Descripcion',
   'en-GB',
   'Interface language (e.g. es-ES, en-GB or ca-ES; '
   'qps-ploc for testing)',
   'src/Core/inMtoAppParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoAppParam.Parametros.appStockOcultarCeros.Descripcion',
   'es-ES',
   'Ocultar líneas a cero en las consultas de stock',
   'src/Core/inMtoAppParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoAppParam.Parametros.appStockOcultarCeros.Descripcion',
   'ca-ES',
   'Ocultar les línies a zero en les consultes d''estoc',
   'src/Core/inMtoAppParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoAppParam.Parametros.appStockOcultarCeros.Descripcion',
   'en-GB',
   'Hide zero-value lines in stock queries',
   'src/Core/inMtoAppParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoAppParam.Parametros.appTemporadaDefecto.Descripcion',
   'es-ES',
   'Temporada por defecto (ID de fza_propiedades_valores)',
   'src/Core/inMtoAppParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoAppParam.Parametros.appTemporadaDefecto.Descripcion',
   'ca-ES',
   'Temporada per defecte (ID de fza_propiedades_valores)',
   'src/Core/inMtoAppParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoAppParam.Parametros.appTemporadaDefecto.Descripcion',
   'en-GB',
   'Default season (fza_propiedades_valores ID)',
   'src/Core/inMtoAppParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoAppParam.Parametros.appRestringirEmpAlmCaja.Descripcion',
   'es-ES',
   'Restringir consultas a la empresa/almacén/caja del usuario',
   'src/Core/inMtoAppParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoAppParam.Parametros.appRestringirEmpAlmCaja.Descripcion',
   'ca-ES',
   'Restringir les consultes a l''empresa/magatzem/caixa de l''usuari',
   'src/Core/inMtoAppParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoAppParam.Parametros.appRestringirEmpAlmCaja.Descripcion',
   'en-GB',
   'Restrict queries to the user company/warehouse/register',
   'src/Core/inMtoAppParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoAppParam.Parametros.appArranqueEnParalelo.Descripcion',
   'es-ES',
   'Precargar las caches de login en paralelo (experimental, normalmente '
   'más lento; dejar en False salvo BBDD de muy alta latencia)',
   'src/Core/inMtoAppParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoAppParam.Parametros.appArranqueEnParalelo.Descripcion',
   'ca-ES',
   'Precarregar les memòries cau d''inici de sessió en paral·lel '
   '(experimental, normalment més lent; deixar en False excepte si la BBDD '
   'té una latència molt alta)',
   'src/Core/inMtoAppParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoAppParam.Parametros.appArranqueEnParalelo.Descripcion',
   'en-GB',
   'Preload login caches in parallel (experimental, normally slower; leave '
   'False unless the database has very high latency)',
   'src/Core/inMtoAppParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoAppParam.Parametros.appVerifactuModo.Descripcion',
   'es-ES', 'Modo fiscal: SIN, VERIFACTU o NO_VERIFACTU',
   'src/Core/inMtoAppParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoAppParam.Parametros.appVerifactuModo.Descripcion',
   'ca-ES', 'Mode fiscal: SIN, VERIFACTU o NO_VERIFACTU',
   'src/Core/inMtoAppParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoAppParam.Parametros.appVerifactuModo.Descripcion',
   'en-GB', 'Tax mode: SIN, VERIFACTU or NO_VERIFACTU',
   'src/Core/inMtoAppParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoAppParam.Parametros.appVerifactuActivo.Descripcion',
   'es-ES', 'Activar SIF (False fuerza modo SIN y no imprime QR)',
   'src/Core/inMtoAppParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoAppParam.Parametros.appVerifactuActivo.Descripcion',
   'ca-ES', 'Activar el SIF (False força el mode SIN i no imprimeix el QR)',
   'src/Core/inMtoAppParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoAppParam.Parametros.appVerifactuActivo.Descripcion',
   'en-GB', 'Enable SIF (False forces SIN mode and does not print a QR)',
   'src/Core/inMtoAppParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoAppParam.Parametros.appVerifactuFirmaCertificado.Descripcion',
   'es-ES',
   'Firmar registros y eventos con certificado de empresa',
   'src/Core/inMtoAppParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoAppParam.Parametros.appVerifactuFirmaCertificado.Descripcion',
   'ca-ES',
   'Signar registres i esdeveniments amb el certificat de l''empresa',
   'src/Core/inMtoAppParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoAppParam.Parametros.appVerifactuFirmaCertificado.Descripcion',
   'en-GB',
   'Sign records and events with the company certificate',
   'src/Core/inMtoAppParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoAppParam.Parametros.appVerifactuNtpServidores.Descripcion',
   'es-ES',
   'Servidores NTP para validar el reloj fiscal NO VERI*FACTU',
   'src/Core/inMtoAppParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoAppParam.Parametros.appVerifactuNtpServidores.Descripcion',
   'ca-ES',
   'Servidors NTP per validar el rellotge fiscal NO VERI*FACTU',
   'src/Core/inMtoAppParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoAppParam.Parametros.appVerifactuNtpServidores.Descripcion',
   'en-GB',
   'NTP servers used to validate the NO VERI*FACTU tax clock',
   'src/Core/inMtoAppParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoAppParam.Parametros.appVerifactuNtpTimeoutMs.Descripcion',
   'es-ES',
   'Timeout por servidor NTP para control del reloj fiscal',
   'src/Core/inMtoAppParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoAppParam.Parametros.appVerifactuNtpTimeoutMs.Descripcion',
   'ca-ES',
   'Temps d''espera per servidor NTP per controlar el rellotge fiscal',
   'src/Core/inMtoAppParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoAppParam.Parametros.appVerifactuNtpTimeoutMs.Descripcion',
   'en-GB',
   'Timeout per NTP server for tax clock control',
   'src/Core/inMtoAppParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoAppParam.Parametros.appVerifactuNtpMargenSegundos.Descripcion',
   'es-ES',
   'Margen máximo admitido del reloj fiscal en segundos',
   'src/Core/inMtoAppParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoAppParam.Parametros.appVerifactuNtpMargenSegundos.Descripcion',
   'ca-ES',
   'Marge màxim admès del rellotge fiscal en segons',
   'src/Core/inMtoAppParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoAppParam.Parametros.appVerifactuNtpMargenSegundos.Descripcion',
   'en-GB',
   'Maximum permitted tax clock offset in seconds',
   'src/Core/inMtoAppParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoAppParam.Parametros.appVerifactuEntorno.Descripcion',
   'es-ES',
   'Entorno AEAT: PRE (pruebas) o PRO (producción)',
   'src/Core/inMtoAppParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoAppParam.Parametros.appVerifactuEntorno.Descripcion',
   'ca-ES',
   'Entorn AEAT: PRE (proves) o PRO (producció)',
   'src/Core/inMtoAppParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoAppParam.Parametros.appVerifactuEntorno.Descripcion',
   'en-GB',
   'AEAT environment: PRE (testing) or PRO (production)',
   'src/Core/inMtoAppParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoAppParam.Parametros.appVerifactuUrlQRPre.Descripcion',
   'es-ES', 'URL de cotejo del QR en preproducción',
   'src/Core/inMtoAppParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoAppParam.Parametros.appVerifactuUrlQRPre.Descripcion',
   'ca-ES', 'URL de comprovació del QR en preproducció',
   'src/Core/inMtoAppParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoAppParam.Parametros.appVerifactuUrlQRPre.Descripcion',
   'en-GB', 'QR verification URL in pre-production',
   'src/Core/inMtoAppParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoAppParam.Parametros.appVerifactuUrlQRPro.Descripcion',
   'es-ES', 'URL de cotejo del QR en producción',
   'src/Core/inMtoAppParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoAppParam.Parametros.appVerifactuUrlQRPro.Descripcion',
   'ca-ES', 'URL de comprovació del QR en producció',
   'src/Core/inMtoAppParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoAppParam.Parametros.appVerifactuUrlQRPro.Descripcion',
   'en-GB', 'QR verification URL in production',
   'src/Core/inMtoAppParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoAppParam.Parametros.appNoVerifactuUrlQRPre.Descripcion',
   'es-ES',
   'URL de remisión del QR NO VERI*FACTU en preproducción',
   'src/Core/inMtoAppParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoAppParam.Parametros.appNoVerifactuUrlQRPre.Descripcion',
   'ca-ES',
   'URL de remissió del QR NO VERI*FACTU en preproducció',
   'src/Core/inMtoAppParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoAppParam.Parametros.appNoVerifactuUrlQRPre.Descripcion',
   'en-GB',
   'NO VERI*FACTU QR submission URL in pre-production',
   'src/Core/inMtoAppParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoAppParam.Parametros.appNoVerifactuUrlQRPro.Descripcion',
   'es-ES',
   'URL de remisión del QR NO VERI*FACTU en producción',
   'src/Core/inMtoAppParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoAppParam.Parametros.appNoVerifactuUrlQRPro.Descripcion',
   'ca-ES',
   'URL de remissió del QR NO VERI*FACTU en producció',
   'src/Core/inMtoAppParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoAppParam.Parametros.appNoVerifactuUrlQRPro.Descripcion',
   'en-GB',
   'NO VERI*FACTU QR submission URL in production',
   'src/Core/inMtoAppParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoAppParam.Parametros.appVerifactuSegundosCiclo.Descripcion',
   'es-ES',
   'Segundos entre ciclos del hilo de la cola Verifactu',
   'src/Core/inMtoAppParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoAppParam.Parametros.appVerifactuSegundosCiclo.Descripcion',
   'ca-ES',
   'Segons entre cicles del fil de la cua Verifactu',
   'src/Core/inMtoAppParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoAppParam.Parametros.appVerifactuSegundosCiclo.Descripcion',
   'en-GB',
   'Seconds between Verifactu queue thread cycles',
   'src/Core/inMtoAppParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoAppParam.Parametros.appVerifactuMaxIntentos.Descripcion',
   'es-ES',
   'Reintentos de envío antes de marcar ERROR definitivo',
   'src/Core/inMtoAppParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoAppParam.Parametros.appVerifactuMaxIntentos.Descripcion',
   'ca-ES',
   'Reintents d''enviament abans de marcar ERROR definitiu',
   'src/Core/inMtoAppParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoAppParam.Parametros.appVerifactuMaxIntentos.Descripcion',
   'en-GB',
   'Submission retries before marking a permanent ERROR',
   'src/Core/inMtoAppParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoAppParam.Parametros.appVerifactuUrlEnvioPre.Descripcion',
   'es-ES',
   'URL del servicio SOAP de envío en preproducción',
   'src/Core/inMtoAppParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoAppParam.Parametros.appVerifactuUrlEnvioPre.Descripcion',
   'ca-ES',
   'URL del servei SOAP d''enviament en preproducció',
   'src/Core/inMtoAppParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoAppParam.Parametros.appVerifactuUrlEnvioPre.Descripcion',
   'en-GB',
   'SOAP submission service URL in pre-production',
   'src/Core/inMtoAppParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoAppParam.Parametros.appVerifactuUrlEnvioPro.Descripcion',
   'es-ES',
   'URL del servicio SOAP de envío en producción',
   'src/Core/inMtoAppParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoAppParam.Parametros.appVerifactuUrlEnvioPro.Descripcion',
   'ca-ES',
   'URL del servei SOAP d''enviament en producció',
   'src/Core/inMtoAppParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoAppParam.Parametros.appVerifactuUrlEnvioPro.Descripcion',
   'en-GB',
   'SOAP submission service URL in production',
   'src/Core/inMtoAppParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoAppParam.Parametros.appVerifactuSifNombreRazon.Descripcion',
   'es-ES',
   'Productor del software (SistemaInformatico.NombreRazon)',
   'src/Core/inMtoAppParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoAppParam.Parametros.appVerifactuSifNombreRazon.Descripcion',
   'ca-ES',
   'Productor del programari (SistemaInformatico.NombreRazon)',
   'src/Core/inMtoAppParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoAppParam.Parametros.appVerifactuSifNombreRazon.Descripcion',
   'en-GB',
   'Software producer (SistemaInformatico.NombreRazon)',
   'src/Core/inMtoAppParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoAppParam.Parametros.appVerifactuSifNif.Descripcion',
   'es-ES',
   'NIF del productor del software (SistemaInformatico.NIF)',
   'src/Core/inMtoAppParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoAppParam.Parametros.appVerifactuSifNif.Descripcion',
   'ca-ES',
   'NIF del productor del programari (SistemaInformatico.NIF)',
   'src/Core/inMtoAppParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoAppParam.Parametros.appVerifactuSifNif.Descripcion',
   'en-GB',
   'Software producer NIF (SistemaInformatico.NIF)',
   'src/Core/inMtoAppParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoAppParam.Parametros.appVerifactuSifDireccion.Descripcion',
   'es-ES', 'Dirección postal del productor del software',
   'src/Core/inMtoAppParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoAppParam.Parametros.appVerifactuSifDireccion.Descripcion',
   'ca-ES', 'Adreça postal del productor del programari',
   'src/Core/inMtoAppParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoAppParam.Parametros.appVerifactuSifDireccion.Descripcion',
   'en-GB', 'Software producer postal address',
   'src/Core/inMtoAppParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoAppParam.Parametros.appVerifactuDeclaracionLugar.Descripcion',
   'es-ES',
   'Lugar de suscripción de la declaración responsable',
   'src/Core/inMtoAppParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoAppParam.Parametros.appVerifactuDeclaracionLugar.Descripcion',
   'ca-ES',
   'Lloc de subscripció de la declaració responsable',
   'src/Core/inMtoAppParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoAppParam.Parametros.appVerifactuDeclaracionLugar.Descripcion',
   'en-GB',
   'Place where the declaration of responsibility was signed',
   'src/Core/inMtoAppParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoAppParam.Parametros.appVerifactuDeclaracionFecha.Descripcion',
   'es-ES',
   'Fecha de suscripción de la declaración responsable',
   'src/Core/inMtoAppParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoAppParam.Parametros.appVerifactuDeclaracionFecha.Descripcion',
   'ca-ES',
   'Data de subscripció de la declaració responsable',
   'src/Core/inMtoAppParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoAppParam.Parametros.appVerifactuDeclaracionFecha.Descripcion',
   'en-GB',
   'Date when the declaration of responsibility was signed',
   'src/Core/inMtoAppParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoAppParam.Parametros.appVerifactuDescripcionOpe.Descripcion',
   'es-ES',
   'Texto de DescripcionOperacion del registro de alta',
   'src/Core/inMtoAppParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoAppParam.Parametros.appVerifactuDescripcionOpe.Descripcion',
   'ca-ES',
   'Text de DescripcionOperacion del registre d''alta',
   'src/Core/inMtoAppParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoAppParam.Parametros.appVerifactuDescripcionOpe.Descripcion',
   'en-GB',
   'DescripcionOperacion text for the registration record',
   'src/Core/inMtoAppParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoAppParam.Parametros.appModoDebug.Descripcion',
   'es-ES',
   'Modo debug (cronómetros LogPerf + trazado SQL + detalles MySQL)',
   'src/Core/inMtoAppParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoAppParam.Parametros.appModoDebug.Descripcion',
   'ca-ES',
   'Mode de depuració (cronòmetres LogPerf + traça SQL + detalls MySQL)',
   'src/Core/inMtoAppParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoAppParam.Parametros.appModoDebug.Descripcion',
   'en-GB',
   'Debug mode (LogPerf timers + SQL tracing + MySQL details)',
   'src/Core/inMtoAppParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoAppParam.Parametros.appModoDebugSQL.Descripcion',
   'es-ES',
   'Modo debug SQL (traza todas las sentencias en el log)',
   'src/Core/inMtoAppParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoAppParam.Parametros.appModoDebugSQL.Descripcion',
   'ca-ES',
   'Mode de depuració SQL (traça totes les sentències al registre)',
   'src/Core/inMtoAppParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoAppParam.Parametros.appModoDebugSQL.Descripcion',
   'en-GB',
   'SQL debug mode (traces all statements in the log)',
   'src/Core/inMtoAppParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoAppParam.Parametros.appLogSQL.Descripcion',
   'es-ES',
   'Log SQL (consultas, tiempo de ejecución, filas y parámetros)',
   'src/Core/inMtoAppParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoAppParam.Parametros.appLogSQL.Descripcion',
   'ca-ES',
   'Registre SQL (consultes, temps d''execució, files i paràmetres)',
   'src/Core/inMtoAppParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoAppParam.Parametros.appLogSQL.Descripcion',
   'en-GB',
   'SQL log (queries, execution time, rows and parameters)',
   'src/Core/inMtoAppParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoAppParam.Parametros.appLogAvanzado.Descripcion',
   'es-ES',
   'Log avanzado (eventos de usuario: unidad, objeto, evento)',
   'src/Core/inMtoAppParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoAppParam.Parametros.appLogAvanzado.Descripcion',
   'ca-ES',
   'Registre avançat (esdeveniments d''usuari: unitat, objecte, '
   'esdeveniment)',
   'src/Core/inMtoAppParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoAppParam.Parametros.appLogAvanzado.Descripcion',
   'en-GB',
   'Advanced log (user events: unit, object, event)',
   'src/Core/inMtoAppParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inLibMsgConfiguracion.SDescripcionParametroIdioma',
   'es-ES',
   'Idioma de la interfaz (p. ej. es-ES, en-GB o ca-ES; '
   'qps-ploc para pruebas)',
   'src/Lib/inLibMsgConfiguracion.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inLibMsgConfiguracion.SDescripcionParametroIdioma',
   'ca-ES',
   'Idioma de la interfície (p. ex. es-ES, en-GB o ca-ES; '
   'qps-ploc per a proves)',
   'src/Lib/inLibMsgConfiguracion.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inLibMsgConfiguracion.SDescripcionParametroIdioma',
   'en-GB',
   'Interface language (e.g. es-ES, en-GB or ca-ES; '
   'qps-ploc for testing)',
   'src/Lib/inLibMsgConfiguracion.pas',
   'S', CURRENT_TIMESTAMP, 'D24')
ON DUPLICATE KEY UPDATE
  `TEXTO_TRAD` = VALUES(`TEXTO_TRAD`),
  `CONTEXTO_TRAD` = VALUES(`CONTEXTO_TRAD`),
  `ESACTIVO_TRAD` = VALUES(`ESACTIVO_TRAD`),
  `INSTANTE_MODIF` = CURRENT_TIMESTAMP,
  `USUARIO_MODIF` = VALUES(`USUARIO_ALTA`);
-- Verifica que las 57 claves dinámicas tienen los tres idiomas.
SELECT COUNT(*) AS `PENDIENTES_PARAMETROS_GENERALES`
  FROM (
    SELECT `CLAVE_TRAD`
      FROM `fza_traducciones`
     WHERE `CLAVE_TRAD` LIKE 'inMtoAppParam.Parametros.%'
       AND `IDIOMA_TRAD` IN ('es-ES', 'ca-ES', 'en-GB')
       AND `ESACTIVO_TRAD` = 'S'
     GROUP BY `CLAVE_TRAD`
    HAVING COUNT(DISTINCT `IDIOMA_TRAD`) <> 3
  ) AS `PENDIENTES`;
