-- Catálogo de textos españoles extraídos de los DFM.
-- Generado por generar_traducciones_dfm.ps1.
INSERT INTO `fza_traducciones` (
  `CLAVE_TRAD`, `IDIOMA_TRAD`, `TEXTO_TRAD`, `CONTEXTO_TRAD`,
  `ESACTIVO_TRAD`, `INSTANTE_ALTA`, `USUARIO_ALTA`
) VALUES
  ('inMtoModalOperacionesCajaSku.TfrmModalOperacionesCajaSku.Caption',
   'es-ES',
   'Operaciones de caja',
   'src/Modals/inMtoModalOperacionesCajaSku.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalOperacionesCajaSku.TfrmModalOperacionesCajaSku.lblTitulo.Caption',
   'es-ES',
   'Operaciones de caja',
   'src/Modals/inMtoModalOperacionesCajaSku.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalOperacionesCajaSku.TfrmModalOperacionesCajaSku.lblAyuda.Caption',
   'es-ES',
   'DE = préstamo   DV = devolución   VE = venta',
   'src/Modals/inMtoModalOperacionesCajaSku.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoModalOperacionesCajaSku.TfrmModalOperacionesCajaSku.tvOperaciones',
     'TIPO_OPERACION.Caption'
   ),
   'es-ES',
   'Tipo',
   'src/Modals/inMtoModalOperacionesCajaSku.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoModalOperacionesCajaSku.TfrmModalOperacionesCajaSku.tvOperaciones',
     'NUMERO_OPERACION.Caption'
   ),
   'es-ES',
   'Número operación',
   'src/Modals/inMtoModalOperacionesCajaSku.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoModalOperacionesCajaSku.TfrmModalOperacionesCajaSku.tvOperaciones',
     'FECHA_OPERACION.Caption'
   ),
   'es-ES',
   'Fecha',
   'src/Modals/inMtoModalOperacionesCajaSku.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoModalOperacionesCajaSku.TfrmModalOperacionesCajaSku.tvOperaciones',
     'FACTURA.Caption'
   ),
   'es-ES',
   'Nº factura',
   'src/Modals/inMtoModalOperacionesCajaSku.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoModalOperacionesCajaSku.TfrmModalOperacionesCajaSku.tvOperaciones',
     'DESCRIPCION_ARTICULO.Caption'
   ),
   'es-ES',
   'Descripción del artículo',
   'src/Modals/inMtoModalOperacionesCajaSku.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoModalOperacionesCajaSku.TfrmModalOperacionesCajaSku.tvOperaciones',
     'PRECIO_VENTA.Caption'
   ),
   'es-ES',
   'Precio venta',
   'src/Modals/inMtoModalOperacionesCajaSku.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoModalOperacionesCajaSku.TfrmModalOperacionesCajaSku.tvOperaciones',
     'DESCUENTO.Caption'
   ),
   'es-ES',
   'Descuento',
   'src/Modals/inMtoModalOperacionesCajaSku.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoModalOperacionesCajaSku.TfrmModalOperacionesCajaSku.lblResultado.',
     'Caption'
   ),
   'es-ES',
   '0 operaciones',
   'src/Modals/inMtoModalOperacionesCajaSku.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalOperacionesCajaSku.TfrmModalOperacionesCajaSku.btnCerrar.Caption',
   'es-ES',
   'Cerrar (ESC)',
   'src/Modals/inMtoModalOperacionesCajaSku.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoModalOperacionesCajaSku.TfrmModalOperacionesCajaSku.btnIrOperacio',
     'n.Caption'
   ),
   'es-ES',
   'Ir a operación',
   'src/Modals/inMtoModalOperacionesCajaSku.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoModalOperacionesCajaSku.TfrmModalOperacionesCajaSku.btnIrFacturaS',
     'implificada.Caption'
   ),
   'es-ES',
   'Ir a factura simplificada',
   'src/Modals/inMtoModalOperacionesCajaSku.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalRegistrarPago.TfrmModalRegistrarPago.Caption',
   'es-ES',
   'Conciliar efecto',
   'src/Modals/inMtoModalRegistrarPago.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalRegistrarPago.TfrmModalRegistrarPago.lblInfo.Caption',
   'es-ES',
   ' ',
   'src/Modals/inMtoModalRegistrarPago.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalRegistrarPago.TfrmModalRegistrarPago.lblFecha.Caption',
   'es-ES',
   'Fecha',
   'src/Modals/inMtoModalRegistrarPago.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalRegistrarPago.TfrmModalRegistrarPago.lblImporte.Caption',
   'es-ES',
   'Importe conciliado',
   'src/Modals/inMtoModalRegistrarPago.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalRegistrarPago.TfrmModalRegistrarPago.lblTipo.Caption',
   'es-ES',
   'Tipo',
   'src/Modals/inMtoModalRegistrarPago.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalRegistrarPago.TfrmModalRegistrarPago.lblReferencia.Caption',
   'es-ES',
   'Referencia',
   'src/Modals/inMtoModalRegistrarPago.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalRegistrarPago.TfrmModalRegistrarPago.btnCancelar.Caption',
   'es-ES',
   '&Cancelar',
   'src/Modals/inMtoModalRegistrarPago.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalRegistrarPago.TfrmModalRegistrarPago.btnAceptar.Caption',
   'es-ES',
   '&Aceptar',
   'src/Modals/inMtoModalRegistrarPago.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalRepetirModelo.TfrmModalRepetirModelo.Caption',
   'es-ES',
   'Modelo repetido en la sesión',
   'src/Modals/inMtoModalRepetirModelo.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalRepetirModelo.TfrmModalRepetirModelo.btnCancelar.Caption',
   'es-ES',
   '&Cancelar (ESC)',
   'src/Modals/inMtoModalRepetirModelo.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalRepetirModelo.TfrmModalRepetirModelo.btnOtroPrecio.Caption',
   'es-ES',
   'Otro rango de &precios',
   'src/Modals/inMtoModalRepetirModelo.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalRepetirModelo.TfrmModalRepetirModelo.btnOtroColor.Caption',
   'es-ES',
   'Repetir en otro &color',
   'src/Modals/inMtoModalRepetirModelo.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalRepetirModelo.TfrmModalRepetirModelo.lblMensaje.Caption',
   'es-ES',
   'El modelo ya está en otra línea de esta sesión.',
   'src/Modals/inMtoModalRepetirModelo.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalRepetirModelo.TfrmModalRepetirModelo.lblOpcionColor.Caption',
   'es-ES',
   CONCAT(
     '- Otro color: copia toda la línea (cantidades por talla incluidas) y ',
     'deja el color vacío.'
   ),
   'src/Modals/inMtoModalRepetirModelo.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalRepetirModelo.TfrmModalRepetirModelo.lblOpcionPrecio.Caption',
   'es-ES',
   CONCAT(
     '- Otro rango de precios: copia la línea con su color, sin cantidades; ',
     'coste y PVP vacíos (otras tallas).'
   ),
   'src/Modals/inMtoModalRepetirModelo.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalRepetirModelo.TfrmModalRepetirModelo.lblOpcionCancelar.Caption',
   'es-ES',
   CONCAT(
     '- Cancelar: la línea solo hereda los datos del modelo, sin cantidades ',
     'ni color.'
   ),
   'src/Modals/inMtoModalRepetirModelo.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalRepetirModelo.TfrmModalRepetirModelo.actCancelar.Caption',
   'es-ES',
   'actCancelar',
   'src/Modals/inMtoModalRepetirModelo.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalScriptLog.TfrmMtoModalScriptLog.Caption',
   'es-ES',
   'Progreso de Ejecución del Script',
   'src/Modals/inMtoModalScriptLog.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalScriptLog.TfrmMtoModalScriptLog.btnGuardarComo.Caption',
   'es-ES',
   'Guardar como...',
   'src/Modals/inMtoModalScriptLog.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalSelAlmacenAlbaran.TfrmModalSelAlmacenAlbaran.Caption',
   'es-ES',
   'Crear albarán desde pedido',
   'src/Modals/inMtoModalSelAlmacenAlbaran.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalSelAlmacenAlbaran.TfrmModalSelAlmacenAlbaran.btnCancelar.Caption',
   'es-ES',
   '&Cancelar (ESC)',
   'src/Modals/inMtoModalSelAlmacenAlbaran.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalSelAlmacenAlbaran.TfrmModalSelAlmacenAlbaran.btnAceptar.Caption',
   'es-ES',
   '&Aceptar (F12)',
   'src/Modals/inMtoModalSelAlmacenAlbaran.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalSelAlmacenAlbaran.TfrmModalSelAlmacenAlbaran.lblPedido.Caption',
   'es-ES',
   'lblPedido',
   'src/Modals/inMtoModalSelAlmacenAlbaran.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoModalSelAlmacenAlbaran.TfrmModalSelAlmacenAlbaran.chkAnadirExiste',
     'nte.Caption'
   ),
   'es-ES',
   'Añadir a un albarán ya existente de este pedido',
   'src/Modals/inMtoModalSelAlmacenAlbaran.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalSelAlmacenAlbaran.TfrmModalSelAlmacenAlbaran.lblAlbaran.Caption',
   'es-ES',
   'Albarán destino:',
   'src/Modals/inMtoModalSelAlmacenAlbaran.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoModalSelAlmacenAlbaran.TfrmModalSelAlmacenAlbaran.cbbAlbaran.Prop',
     'erties.ListColumns[0].Caption'
   ),
   'es-ES',
   'Número',
   'src/Modals/inMtoModalSelAlmacenAlbaran.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoModalSelAlmacenAlbaran.TfrmModalSelAlmacenAlbaran.cbbAlbaran.Prop',
     'erties.ListColumns[1].Caption'
   ),
   'es-ES',
   'Serie',
   'src/Modals/inMtoModalSelAlmacenAlbaran.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoModalSelAlmacenAlbaran.TfrmModalSelAlmacenAlbaran.cbbAlbaran.Prop',
     'erties.ListColumns[2].Caption'
   ),
   'es-ES',
   'Fecha',
   'src/Modals/inMtoModalSelAlmacenAlbaran.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoModalSelAlmacenAlbaran.TfrmModalSelAlmacenAlbaran.cbbAlbaran.Prop',
     'erties.ListColumns[3].Caption'
   ),
   'es-ES',
   'Estado',
   'src/Modals/inMtoModalSelAlmacenAlbaran.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoModalSelAlmacenAlbaran.TfrmModalSelAlmacenAlbaran.cbbAlbaran.Prop',
     'erties.ListColumns[4].Caption'
   ),
   'es-ES',
   'Total',
   'src/Modals/inMtoModalSelAlmacenAlbaran.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalSelAlmacenAlbaran.TfrmModalSelAlmacenAlbaran.lblAlmacen.Caption',
   'es-ES',
   'Almacén del albarán:',
   'src/Modals/inMtoModalSelAlmacenAlbaran.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoModalSelAlmacenAlbaran.TfrmModalSelAlmacenAlbaran.cbbAlmacen.Prop',
     'erties.ListColumns[0].Caption'
   ),
   'es-ES',
   'Código',
   'src/Modals/inMtoModalSelAlmacenAlbaran.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoModalSelAlmacenAlbaran.TfrmModalSelAlmacenAlbaran.cbbAlmacen.Prop',
     'erties.ListColumns[1].Caption'
   ),
   'es-ES',
   'Almacén',
   'src/Modals/inMtoModalSelAlmacenAlbaran.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalSelAlmacenAlbaran.TfrmModalSelAlmacenAlbaran.actAceptar.Caption',
   'es-ES',
   'Aceptar',
   'src/Modals/inMtoModalSelAlmacenAlbaran.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalSelAlmacenPedido.TfrmModalSelAlmacenPedido.Caption',
   'es-ES',
   'Crear albarán desde pedido',
   'src/Modals/inMtoModalSelAlmacenPedido.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalSelAlmacenPedido.TfrmModalSelAlmacenPedido.btnCancelar.Caption',
   'es-ES',
   '&Cancelar (ESC)',
   'src/Modals/inMtoModalSelAlmacenPedido.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalSelAlmacenPedido.TfrmModalSelAlmacenPedido.btnAceptar.Caption',
   'es-ES',
   '&Aceptar (F12)',
   'src/Modals/inMtoModalSelAlmacenPedido.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalSelAlmacenPedido.TfrmModalSelAlmacenPedido.lblPedido.Caption',
   'es-ES',
   'lblPedido',
   'src/Modals/inMtoModalSelAlmacenPedido.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalSelAlmacenPedido.TfrmModalSelAlmacenPedido.lblAlmacen.Caption',
   'es-ES',
   'Almacén destino (sólo se reciben las líneas de este almacén):',
   'src/Modals/inMtoModalSelAlmacenPedido.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoModalSelAlmacenPedido.TfrmModalSelAlmacenPedido.cbbAlmacen.Proper',
     'ties.ListColumns[0].Caption'
   ),
   'es-ES',
   'Código',
   'src/Modals/inMtoModalSelAlmacenPedido.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoModalSelAlmacenPedido.TfrmModalSelAlmacenPedido.cbbAlmacen.Proper',
     'ties.ListColumns[1].Caption'
   ),
   'es-ES',
   'Almacén',
   'src/Modals/inMtoModalSelAlmacenPedido.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalSelAlmacenPedido.TfrmModalSelAlmacenPedido.chkIncorporar.Caption',
   'es-ES',
   'Incorporar a un albarán ya existente de este pedido',
   'src/Modals/inMtoModalSelAlmacenPedido.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoModalSelAlmacenPedido.TfrmModalSelAlmacenPedido.colAlbExistNUMERO',
     '.Caption'
   ),
   'es-ES',
   'Número',
   'src/Modals/inMtoModalSelAlmacenPedido.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoModalSelAlmacenPedido.TfrmModalSelAlmacenPedido.colAlbExistSERIE.',
     'Caption'
   ),
   'es-ES',
   'Serie',
   'src/Modals/inMtoModalSelAlmacenPedido.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoModalSelAlmacenPedido.TfrmModalSelAlmacenPedido.colAlbExistFECHA.',
     'Caption'
   ),
   'es-ES',
   'Fecha',
   'src/Modals/inMtoModalSelAlmacenPedido.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoModalSelAlmacenPedido.TfrmModalSelAlmacenPedido.colAlbExistESTADO',
     '.Caption'
   ),
   'es-ES',
   'Estado',
   'src/Modals/inMtoModalSelAlmacenPedido.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoModalSelAlmacenPedido.TfrmModalSelAlmacenPedido.colAlbExistTOTAL.',
     'Caption'
   ),
   'es-ES',
   'Total',
   'src/Modals/inMtoModalSelAlmacenPedido.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalSelAlmacenPedido.TfrmModalSelAlmacenPedido.lblSerieAlb.Caption',
   'es-ES',
   'Serie del albarán',
   'src/Modals/inMtoModalSelAlmacenPedido.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalSelAlmacenPedido.TfrmModalSelAlmacenPedido.lblRefPrv.Caption',
   'es-ES',
   'Ref. proveedor',
   'src/Modals/inMtoModalSelAlmacenPedido.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalSelAlmacenPedido.TfrmModalSelAlmacenPedido.lblFecha.Caption',
   'es-ES',
   'Fecha recepción',
   'src/Modals/inMtoModalSelAlmacenPedido.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalSelAlmacenPedido.TfrmModalSelAlmacenPedido.lblTemporada.Caption',
   'es-ES',
   'Temporada',
   'src/Modals/inMtoModalSelAlmacenPedido.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalSelAlmacenPedido.TfrmModalSelAlmacenPedido.actAceptar.Caption',
   'es-ES',
   'Aceptar',
   'src/Modals/inMtoModalSelAlmacenPedido.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalSelAlmacenPedido.TfrmModalSelAlmacenPedido.actCancelar.Caption',
   'es-ES',
   'Cancelar',
   'src/Modals/inMtoModalSelAlmacenPedido.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalSeleccionarBanco.TfrmModalSeleccionarBanco.Caption',
   'es-ES',
   'Seleccionar banco de la empresa',
   'src/Modals/inMtoModalSeleccionarBanco.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalSeleccionarBanco.TfrmModalSeleccionarBanco.lblInfo.Caption',
   'es-ES',
   'Cuenta de la empresa:',
   'src/Modals/inMtoModalSeleccionarBanco.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalSeleccionarBanco.TfrmModalSeleccionarBanco.colNombre.Caption',
   'es-ES',
   'Nombre cuenta',
   'src/Modals/inMtoModalSeleccionarBanco.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalSeleccionarBanco.TfrmModalSeleccionarBanco.colIban.Caption',
   'es-ES',
   'IBAN',
   'src/Modals/inMtoModalSeleccionarBanco.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalSeleccionarBanco.TfrmModalSeleccionarBanco.colBanco.Caption',
   'es-ES',
   'Banco',
   'src/Modals/inMtoModalSeleccionarBanco.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalSeleccionarBanco.TfrmModalSeleccionarBanco.colCobro.Caption',
   'es-ES',
   'Def. Cobro',
   'src/Modals/inMtoModalSeleccionarBanco.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalSeleccionarBanco.TfrmModalSeleccionarBanco.colPago.Caption',
   'es-ES',
   'Def. Pago',
   'src/Modals/inMtoModalSeleccionarBanco.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalSeleccionarBanco.TfrmModalSeleccionarBanco.btnCancelar.Caption',
   'es-ES',
   '&Cancelar',
   'src/Modals/inMtoModalSeleccionarBanco.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalSeleccionarBanco.TfrmModalSeleccionarBanco.btnAceptar.Caption',
   'es-ES',
   '&Aceptar',
   'src/Modals/inMtoModalSeleccionarBanco.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalSelFamilia.TfrmModalSelFamilia.Caption',
   'es-ES',
   'Seleccionar familia',
   'src/Modals/inMtoModalSelFamilia.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalSelFamilia.TfrmModalSelFamilia.lblFiltro.Caption',
   'es-ES',
   'Filtro',
   'src/Modals/inMtoModalSelFamilia.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalSelFamilia.TfrmModalSelFamilia.btnCancelar.Caption',
   'es-ES',
   '&Cancelar (ESC)',
   'src/Modals/inMtoModalSelFamilia.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalSelFamilia.TfrmModalSelFamilia.btnAceptar.Caption',
   'es-ES',
   '&Aceptar (F12 / Enter)',
   'src/Modals/inMtoModalSelFamilia.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalSelFamilia.TfrmModalSelFamilia.actAceptar.Caption',
   'es-ES',
   'Aceptar',
   'src/Modals/inMtoModalSelFamilia.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalSelFamilia.TfrmModalSelFamilia.actCancelar.Caption',
   'es-ES',
   'Cancelar',
   'src/Modals/inMtoModalSelFamilia.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalSerieFechaFactura.TfrmModalSerieFechaFactura.Caption',
   'es-ES',
   'Borrador normal: serie y fecha',
   'src/Modals/inMtoModalSerieFechaFactura.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalSerieFechaFactura.TfrmModalSerieFechaFactura.lblSerie.Caption',
   'es-ES',
   'Serie borrador:',
   'src/Modals/inMtoModalSerieFechaFactura.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoModalSerieFechaFactura.TfrmModalSerieFechaFactura.cbbSerie.Proper',
     'ties.ListColumns[0].Caption'
   ),
   'es-ES',
   'Serie',
   'src/Modals/inMtoModalSerieFechaFactura.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalSerieFechaFactura.TfrmModalSerieFechaFactura.lblFecha.Caption',
   'es-ES',
   'Fecha borrador:',
   'src/Modals/inMtoModalSerieFechaFactura.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalSerieFechaFactura.TfrmModalSerieFechaFactura.btnCancelar.Caption',
   'es-ES',
   '&Cancelar (ESC)',
   'src/Modals/inMtoModalSerieFechaFactura.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalSerieFechaFactura.TfrmModalSerieFechaFactura.btnAceptar.Caption',
   'es-ES',
   '&Aceptar',
   'src/Modals/inMtoModalSerieFechaFactura.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalSeriesDocumentos.TfrmModalSeriesDocumentos.Caption',
   'es-ES',
   'Añadir serie a todos',
   'src/Modals/inMtoModalSeriesDocumentos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalSeriesDocumentos.TfrmModalSeriesDocumentos.lblTitulo.Caption',
   'es-ES',
   'Serie común para todos los documentos',
   'src/Modals/inMtoModalSeriesDocumentos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalSeriesDocumentos.TfrmModalSeriesDocumentos.lblSerie.Caption',
   'es-ES',
   'Serie',
   'src/Modals/inMtoModalSeriesDocumentos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalSeriesDocumentos.TfrmModalSeriesDocumentos.lblFechaDesde.Caption',
   'es-ES',
   'Fecha inicio',
   'src/Modals/inMtoModalSeriesDocumentos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalSeriesDocumentos.TfrmModalSeriesDocumentos.lblFechaHasta.Caption',
   'es-ES',
   'Fecha fin',
   'src/Modals/inMtoModalSeriesDocumentos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalSeriesDocumentos.TfrmModalSeriesDocumentos.actAceptar.Caption',
   'es-ES',
   'Aceptar (F12)',
   'src/Modals/inMtoModalSeriesDocumentos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalSeriesDocumentos.TfrmModalSeriesDocumentos.actCancelar.Caption',
   'es-ES',
   'Cancelar (ESC)',
   'src/Modals/inMtoModalSeriesDocumentos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalSesionDuplicado.TfrmModalSesionDuplicado.Caption',
   'es-ES',
   'Código de artículo duplicado',
   'src/Modals/inMtoModalSesionDuplicado.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalSesionDuplicado.TfrmModalSesionDuplicado.lblTitulo.Caption',
   'es-ES',
   'El código de artículo ya existe en el catálogo',
   'src/Modals/inMtoModalSesionDuplicado.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoModalSesionDuplicado.TfrmModalSesionDuplicado.lblCodigoExistente.',
     'Caption'
   ),
   'es-ES',
   'Código existente:',
   'src/Modals/inMtoModalSesionDuplicado.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalSesionDuplicado.TfrmModalSesionDuplicado.rgAccion.Caption',
   'es-ES',
   ' Acción ',
   'src/Modals/inMtoModalSesionDuplicado.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoModalSesionDuplicado.TfrmModalSesionDuplicado.rgAccion.Properties',
     '.Items[0].Caption'
   ),
   'es-ES',
   'Reusar el artículo existente (no se creará uno nuevo)',
   'src/Modals/inMtoModalSesionDuplicado.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoModalSesionDuplicado.TfrmModalSesionDuplicado.rgAccion.Properties',
     '.Items[1].Caption'
   ),
   'es-ES',
   'Renombrar el código en esta sesión',
   'src/Modals/inMtoModalSesionDuplicado.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalSesionDuplicado.TfrmModalSesionDuplicado.btnCancelar.Caption',
   'es-ES',
   '&Cancelar (ESC)',
   'src/Modals/inMtoModalSesionDuplicado.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalSesionDuplicado.TfrmModalSesionDuplicado.btnAceptar.Caption',
   'es-ES',
   '&Aceptar (F12)',
   'src/Modals/inMtoModalSesionDuplicado.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalSesionDuplicado.TfrmModalSesionDuplicado.actAceptar.Caption',
   'es-ES',
   'Aceptar',
   'src/Modals/inMtoModalSesionDuplicado.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalSesionDuplicado.TfrmModalSesionDuplicado.actCancelar.Caption',
   'es-ES',
   'Cancelar',
   'src/Modals/inMtoModalSesionDuplicado.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalSesionMaterializar.TfrmModalSesionMaterializar.Caption',
   'es-ES',
   'Materializar sesión de compra',
   'src/Modals/inMtoModalSesionMaterializar.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalSesionMaterializar.TfrmModalSesionMaterializar.lblTitulo.Caption',
   'es-ES',
   'Atención: esta acción no se puede deshacer.',
   'src/Modals/inMtoModalSesionMaterializar.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoModalSesionMaterializar.TfrmModalSesionMaterializar.lblResumen.Ca',
     'ption'
   ),
   'es-ES',
   CONCAT(
     'Se van a crear los artículos, SKUs, códigos de barras y enlaces al ',
     'proveedor según el detalle de la sesión.'
   ),
   'src/Modals/inMtoModalSesionMaterializar.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalSesionMaterializar.TfrmModalSesionMaterializar.chkPedido.Caption',
   'es-ES',
   'Generar pedido de compra (no mueve stock)',
   'src/Modals/inMtoModalSesionMaterializar.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoModalSesionMaterializar.TfrmModalSesionMaterializar.chkAlbaran.Ca',
     'ption'
   ),
   'es-ES',
   'Generar albarán de compra (entra stock en el almacén destino)',
   'src/Modals/inMtoModalSesionMaterializar.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalSesionMaterializar.TfrmModalSesionMaterializar.lblAviso.Caption',
   'es-ES',
   CONCAT(
     'Si ambos documentos están marcados se generan en orden: pedido ',
     'primero, luego albarán.'
   ),
   'src/Modals/inMtoModalSesionMaterializar.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoModalSesionMaterializar.TfrmModalSesionMaterializar.btnCancelar.C',
     'aption'
   ),
   'es-ES',
   '&Cancelar (ESC)',
   'src/Modals/inMtoModalSesionMaterializar.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoModalSesionMaterializar.TfrmModalSesionMaterializar.btnAceptar.Ca',
     'ption'
   ),
   'es-ES',
   '&Confirmar (F12)',
   'src/Modals/inMtoModalSesionMaterializar.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoModalSesionMaterializar.TfrmModalSesionMaterializar.actAceptar.Ca',
     'ption'
   ),
   'es-ES',
   'Aceptar',
   'src/Modals/inMtoModalSesionMaterializar.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoModalSesionMaterializar.TfrmModalSesionMaterializar.actCancelar.C',
     'aption'
   ),
   'es-ES',
   'Cancelar',
   'src/Modals/inMtoModalSesionMaterializar.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalVerifactuDecl.TfrmModalVerifactuDecl.Caption',
   'es-ES',
   'Declaración Responsable - Verifactu',
   'src/Modals/inMtoModalVerifactuDecl.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoModalVerifactuDecl.TfrmModalVerifactuDecl.lblInstalacionTitulo.Ca',
     'ption'
   ),
   'es-ES',
   'Número de instalación SIF',
   'src/Modals/inMtoModalVerifactuDecl.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoModalVerifactuDecl.TfrmModalVerifactuDecl.lblInstalacionNumero.Ca',
     'ption'
   ),
   'es-ES',
   'Número: (pendiente)',
   'src/Modals/inMtoModalVerifactuDecl.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoModalVerifactuDecl.TfrmModalVerifactuDecl.btnGenerarInstalacion.C',
     'aption'
   ),
   'es-ES',
   'Generar número',
   'src/Modals/inMtoModalVerifactuDecl.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalVerifactuDecl.TfrmModalVerifactuDecl.btnImprimir.Caption',
   'es-ES',
   '&Imprimir',
   'src/Modals/inMtoModalVerifactuDecl.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalVerifactuDecl.TfrmModalVerifactuDecl.btnAceptar.Caption',
   'es-ES',
   '&Aceptar',
   'src/Modals/inMtoModalVerifactuDecl.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalWizardEditar.TfrmModalWizardEditar.Caption',
   'es-ES',
   'Editar informe',
   'src/Modals/inMtoModalWizardEditar.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalWizardEditar.TfrmModalWizardEditar.lblOrigen.Caption',
   'es-ES',
   'Informe',
   'src/Modals/inMtoModalWizardEditar.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalWizardEditar.TfrmModalWizardEditar.lblFormato.Caption',
   'es-ES',
   'Formato',
   'src/Modals/inMtoModalWizardEditar.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalWizardEditar.TfrmModalWizardEditar.lblNombreNuevo.Caption',
   'es-ES',
   'Nombre nuevo',
   'src/Modals/inMtoModalWizardEditar.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalWizardEditar.TfrmModalWizardEditar.lblScope.Caption',
   'es-ES',
   'Permiso (scope)',
   'src/Modals/inMtoModalWizardEditar.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalWizardEditar.TfrmModalWizardEditar.lblAyudaPaso1.Caption',
   'es-ES',
   CONCAT(
     'En el siguiente paso podrás ver los datasets del informe (cabecera y ',
     'detalle) y configurar las guías de datos que se ligarán a este ',
     'formato.'
   ),
   'src/Modals/inMtoModalWizardEditar.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalWizardEditar.TfrmModalWizardEditar.lblTituloGuias.Caption',
   'es-ES',
   'Guías',
   'src/Modals/inMtoModalWizardEditar.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalWizardEditar.TfrmModalWizardEditar.lblDatasets.Caption',
   'es-ES',
   '1. Dataset master',
   'src/Modals/inMtoModalWizardEditar.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalWizardEditar.TfrmModalWizardEditar.lblCampos.Caption',
   'es-ES',
   '2. Master fields (uno o varios)',
   'src/Modals/inMtoModalWizardEditar.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalWizardEditar.TfrmModalWizardEditar.lblTablas.Caption',
   'es-ES',
   '3. Tabla o vista externa',
   'src/Modals/inMtoModalWizardEditar.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalWizardEditar.TfrmModalWizardEditar.lblCamposTabla.Caption',
   'es-ES',
   '4. Campo de unión (PK marcada con *)',
   'src/Modals/inMtoModalWizardEditar.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalWizardEditar.TfrmModalWizardEditar.lblCodigoNuevo.Caption',
   'es-ES',
   CONCAT(
     '5. Los campos de la tabla externa se añaden al master (UserName se ',
     'mantiene). Colisiones -> sufijo 1,2,...'
   ),
   'src/Modals/inMtoModalWizardEditar.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalWizardEditar.TfrmModalWizardEditar.btnAddGuia.Caption',
   'es-ES',
   '+ Añadir guía con esta configuración',
   'src/Modals/inMtoModalWizardEditar.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalWizardEditar.TfrmModalWizardEditar.tvGuiasCODIGO.Caption',
   'es-ES',
   'Código (UserName)',
   'src/Modals/inMtoModalWizardEditar.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalWizardEditar.TfrmModalWizardEditar.tvGuiasTIPO.Caption',
   'es-ES',
   'Tipo',
   'src/Modals/inMtoModalWizardEditar.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalWizardEditar.TfrmModalWizardEditar.tvGuiasTABLA.Caption',
   'es-ES',
   'Tabla',
   'src/Modals/inMtoModalWizardEditar.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalWizardEditar.TfrmModalWizardEditar.tvGuiasSQL.Caption',
   'es-ES',
   'SQL libre',
   'src/Modals/inMtoModalWizardEditar.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalWizardEditar.TfrmModalWizardEditar.tvGuiasMASTER_FIELDS.Caption',
   'es-ES',
   'Master fields',
   'src/Modals/inMtoModalWizardEditar.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalWizardEditar.TfrmModalWizardEditar.tvGuiasDETAIL_FIELDS.Caption',
   'es-ES',
   'Detail fields',
   'src/Modals/inMtoModalWizardEditar.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalWizardEditar.TfrmModalWizardEditar.tvGuiasORDEN.Caption',
   'es-ES',
   'Orden',
   'src/Modals/inMtoModalWizardEditar.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalWizardEditar.TfrmModalWizardEditar.tvGuiasACTIVO.Caption',
   'es-ES',
   'Activo',
   'src/Modals/inMtoModalWizardEditar.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalWizardEditar.TfrmModalWizardEditar.actCancelar.Caption',
   'es-ES',
   'Cancelar',
   'src/Modals/inMtoModalWizardEditar.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema')
ON DUPLICATE KEY UPDATE
  `TEXTO_TRAD` = VALUES(`TEXTO_TRAD`),
  `CONTEXTO_TRAD` = VALUES(`CONTEXTO_TRAD`),
  `ESACTIVO_TRAD` = VALUES(`ESACTIVO_TRAD`),
  `INSTANTE_MODIF` = CURRENT_TIMESTAMP,
  `USUARIO_MODIF` = VALUES(`USUARIO_ALTA`);
