-- Catálogo de textos españoles extraídos de los DFM.
-- Generado por generar_traducciones_dfm.ps1.
INSERT INTO `fza_traducciones` (
  `CLAVE_TRAD`, `IDIOMA_TRAD`, `TEXTO_TRAD`, `CONTEXTO_TRAD`,
  `ESACTIVO_TRAD`, `INSTANTE_ALTA`, `USUARIO_ALTA`
) VALUES
  ('inMtoDepositosCliente.TfrmMtoDepositosCliente.Caption',
   'es-ES',
   'Depósitos de Clientes',
   'src/Forms/inMtoDepositosCliente.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoDepositosCliente.TfrmMtoDepositosCliente.cxGrdDBTabPrinID_DEPOSIT',
     'O_DEP.Caption'
   ),
   'es-ES',
   'ID Depósito',
   'src/Forms/inMtoDepositosCliente.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoDepositosCliente.TfrmMtoDepositosCliente.cxGrdDBTabPrinCODIGO_EMP',
     'RESA_DEP.Caption'
   ),
   'es-ES',
   'Empresa',
   'src/Forms/inMtoDepositosCliente.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoDepositosCliente.TfrmMtoDepositosCliente.cxGrdDBTabPrinCODIGO_CLI',
     'ENTE_DEP.Caption'
   ),
   'es-ES',
   'Cliente',
   'src/Forms/inMtoDepositosCliente.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoDepositosCliente.TfrmMtoDepositosCliente.cxGrdDBTabPrinCODIGO_ART',
     'ICULO_DEP.Caption'
   ),
   'es-ES',
   'Artículo',
   'src/Forms/inMtoDepositosCliente.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoDepositosCliente.TfrmMtoDepositosCliente.cxGrdDBTabPrinCODIGO_UNI',
     'DAD_DEP.Caption'
   ),
   'es-ES',
   'SKU/Unidad',
   'src/Forms/inMtoDepositosCliente.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoDepositosCliente.TfrmMtoDepositosCliente.cxGrdDBTabPrinPRECIO_VEN',
     'TA_DEP.Caption'
   ),
   'es-ES',
   'Precio Venta',
   'src/Forms/inMtoDepositosCliente.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoDepositosCliente.TfrmMtoDepositosCliente.cxGrdDBTabPrinIMPORTE_AN',
     'TICIPO_DEP.Caption'
   ),
   'es-ES',
   'Anticipo',
   'src/Forms/inMtoDepositosCliente.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoDepositosCliente.TfrmMtoDepositosCliente.cxGrdDBTabPrinESTADO_DEP',
     '.Caption'
   ),
   'es-ES',
   'Estado',
   'src/Forms/inMtoDepositosCliente.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoDepositosCliente.TfrmMtoDepositosCliente.cxGrdDBTabPrinFECHA_CREA',
     'CION_DEP.Caption'
   ),
   'es-ES',
   'F. Creación',
   'src/Forms/inMtoDepositosCliente.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoDepositosCliente.TfrmMtoDepositosCliente.cxGrdDBTabPrinFECHA_ENTR',
     'EGA_DEP.Caption'
   ),
   'es-ES',
   'F. Entrega',
   'src/Forms/inMtoDepositosCliente.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoDepositosCliente.TfrmMtoDepositosCliente.cxGrdDBTabPrinCANTIDAD_P',
     'ENDIENTE_DEP.Caption'
   ),
   'es-ES',
   'Cant. Pendiente',
   'src/Forms/inMtoDepositosCliente.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoDepositosCliente.TfrmMtoDepositosCliente.cxGrdDBTabPrinTIPO_IVA_D',
     'EP.Caption'
   ),
   'es-ES',
   'Tipo IVA',
   'src/Forms/inMtoDepositosCliente.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoDepositosCliente.TfrmMtoDepositosCliente.cxGrdDBTabPrinPORCEN_IVA',
     '_DEP.Caption'
   ),
   'es-ES',
   '% IVA',
   'src/Forms/inMtoDepositosCliente.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoDepositosCliente.TfrmMtoDepositosCliente.cxGrdDBTabPrinESIMP_INCL',
     '_DEP.Caption'
   ),
   'es-ES',
   'IVA Incl.',
   'src/Forms/inMtoDepositosCliente.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoDepositosCliente.TfrmMtoDepositosCliente.cxGrdDBTabPrinINSTANTEAL',
     'TA.Caption'
   ),
   'es-ES',
   'Instante Alta',
   'src/Forms/inMtoDepositosCliente.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoDepositosCliente.TfrmMtoDepositosCliente.cxGrdDBTabPrinINSTANTEMO',
     'DIF.Caption'
   ),
   'es-ES',
   'Instante Modif',
   'src/Forms/inMtoDepositosCliente.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoDepositosCliente.TfrmMtoDepositosCliente.cxGrdDBTabPrinUSUARIOALT',
     'A.Caption'
   ),
   'es-ES',
   'Usuario Alta',
   'src/Forms/inMtoDepositosCliente.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoDepositosCliente.TfrmMtoDepositosCliente.cxGrdDBTabPrinUSUARIOMOD',
     'IF.Caption'
   ),
   'es-ES',
   'Usuario Modif',
   'src/Forms/inMtoDepositosCliente.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoDepositosCliente.TfrmMtoDepositosCliente.btnImprimirInforme.Caption',
   'es-ES',
   'Imprimir Informe A4',
   'src/Forms/inMtoDepositosCliente.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoDevolucionesCompra.TfrmMtoDevolucionesCompra.Caption',
   'es-ES',
   'Mantenimiento de Devoluciones a Proveedor',
   'src/Forms/inMtoDevolucionesCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoDevolucionesCompra.TfrmMtoDevolucionesCompra.dbcGrdDevcNUMERO_DEV',
     'C.Caption'
   ),
   'es-ES',
   'Número',
   'src/Forms/inMtoDevolucionesCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoDevolucionesCompra.TfrmMtoDevolucionesCompra.dbcGrdDevcSERIE_DEVC',
     '.Caption'
   ),
   'es-ES',
   'Serie',
   'src/Forms/inMtoDevolucionesCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoDevolucionesCompra.TfrmMtoDevolucionesCompra.dbcGrdDevcFECHA_DEVC',
     '.Caption'
   ),
   'es-ES',
   'Fecha',
   'src/Forms/inMtoDevolucionesCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoDevolucionesCompra.TfrmMtoDevolucionesCompra.dbcGrdDevcCODIGO_EMP',
     '_DEVC.Caption'
   ),
   'es-ES',
   'Empresa',
   'src/Forms/inMtoDevolucionesCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoDevolucionesCompra.TfrmMtoDevolucionesCompra.dbcGrdDevcCODIGO_PRV',
     '_DEVC.Caption'
   ),
   'es-ES',
   'Proveedor',
   'src/Forms/inMtoDevolucionesCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoDevolucionesCompra.TfrmMtoDevolucionesCompra.dbcGrdDevcRSPRV_DEVC',
     '.Caption'
   ),
   'es-ES',
   'Razón Social Proveedor',
   'src/Forms/inMtoDevolucionesCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoDevolucionesCompra.TfrmMtoDevolucionesCompra.dbcGrdDevcREF_PROVEE',
     'DOR_DEVC.Caption'
   ),
   'es-ES',
   'Ref. proveedor',
   'src/Forms/inMtoDevolucionesCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoDevolucionesCompra.TfrmMtoDevolucionesCompra.dbcGrdDevcCODIGO_ALM',
     '_DEVC.Caption'
   ),
   'es-ES',
   'Almacén',
   'src/Forms/inMtoDevolucionesCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoDevolucionesCompra.TfrmMtoDevolucionesCompra.dbcGrdDevcTOTAL_PREN',
     'DAS_DEVC.Caption'
   ),
   'es-ES',
   'Nº de prendas',
   'src/Forms/inMtoDevolucionesCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoDevolucionesCompra.TfrmMtoDevolucionesCompra.dbcGrdDevcTOTAL_LIQU',
     'IDO_DEVC.Caption'
   ),
   'es-ES',
   'Total líquido',
   'src/Forms/inMtoDevolucionesCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoDevolucionesCompra.TfrmMtoDevolucionesCompra.tsCabecera.Caption',
   'es-ES',
   'Cabecera',
   'src/Forms/inMtoDevolucionesCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoDevolucionesCompra.TfrmMtoDevolucionesCompra.lblNroDevolucion.Caption',
   'es-ES',
   'Número',
   'src/Forms/inMtoDevolucionesCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoDevolucionesCompra.TfrmMtoDevolucionesCompra.lblSerieDevolucion.C',
     'aption'
   ),
   'es-ES',
   'Serie',
   'src/Forms/inMtoDevolucionesCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoDevolucionesCompra.TfrmMtoDevolucionesCompra.lblFechaDevolucion.C',
     'aption'
   ),
   'es-ES',
   'Fecha',
   'src/Forms/inMtoDevolucionesCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoDevolucionesCompra.TfrmMtoDevolucionesCompra.lblCabTotalPrendas.C',
     'aption'
   ),
   'es-ES',
   'Nº de prendas',
   'src/Forms/inMtoDevolucionesCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoDevolucionesCompra.TfrmMtoDevolucionesCompra.lblCabTotalPrendasVa',
     'lor.Caption'
   ),
   'es-ES',
   '0',
   'src/Forms/inMtoDevolucionesCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoDevolucionesCompra.TfrmMtoDevolucionesCompra.lblCodigoEmpresa.Caption',
   'es-ES',
   'Empresa',
   'src/Forms/inMtoDevolucionesCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoDevolucionesCompra.TfrmMtoDevolucionesCompra.lblCodigoProveedor.C',
     'aption'
   ),
   'es-ES',
   'Proveedor',
   'src/Forms/inMtoDevolucionesCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoDevolucionesCompra.TfrmMtoDevolucionesCompra.cbbCODIGO_PRV_DEVC.P',
     'roperties.ListColumns[0].Caption'
   ),
   'es-ES',
   'Código',
   'src/Forms/inMtoDevolucionesCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoDevolucionesCompra.TfrmMtoDevolucionesCompra.cbbCODIGO_PRV_DEVC.P',
     'roperties.ListColumns[1].Caption'
   ),
   'es-ES',
   'Proveedor',
   'src/Forms/inMtoDevolucionesCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoDevolucionesCompra.TfrmMtoDevolucionesCompra.lblRefProveedor.Caption',
   'es-ES',
   'Ref. proveedor',
   'src/Forms/inMtoDevolucionesCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoDevolucionesCompra.TfrmMtoDevolucionesCompra.lblCodigoAlmacen.Caption',
   'es-ES',
   'Almacén salida',
   'src/Forms/inMtoDevolucionesCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoDevolucionesCompra.TfrmMtoDevolucionesCompra.cbbCODIGO_ALM_DEVC.P',
     'roperties.ListColumns[0].Caption'
   ),
   'es-ES',
   'Código',
   'src/Forms/inMtoDevolucionesCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoDevolucionesCompra.TfrmMtoDevolucionesCompra.cbbCODIGO_ALM_DEVC.P',
     'roperties.ListColumns[1].Caption'
   ),
   'es-ES',
   'Almacén',
   'src/Forms/inMtoDevolucionesCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoDevolucionesCompra.TfrmMtoDevolucionesCompra.btnAnadirLinea.Caption',
   'es-ES',
   'Añadir línea',
   'src/Forms/inMtoDevolucionesCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoDevolucionesCompra.TfrmMtoDevolucionesCompra.btnBorrarLinea.Caption',
   'es-ES',
   'Borrar línea',
   'src/Forms/inMtoDevolucionesCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoDevolucionesCompra.TfrmMtoDevolucionesCompra.btnTallasHorizontal.',
     'Caption'
   ),
   'es-ES',
   'Tallas en horizontal',
   'src/Forms/inMtoDevolucionesCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoDevolucionesCompra.TfrmMtoDevolucionesCompra.btnAtributosColumna.',
     'Caption'
   ),
   'es-ES',
   'Atributo por columna',
   'src/Forms/inMtoDevolucionesCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoDevolucionesCompra.TfrmMtoDevolucionesCompra.btnDevolverTodoStock',
     '.Caption'
   ),
   'es-ES',
   'Devolver fila',
   'src/Forms/inMtoDevolucionesCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoDevolucionesCompra.TfrmMtoDevolucionesCompra.tsLineasDevolucion.C',
     'aption'
   ),
   'es-ES',
   '&1_Líneas',
   'src/Forms/inMtoDevolucionesCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoDevolucionesCompra.TfrmMtoDevolucionesCompra.colLineaDevcLINEA.Ca',
     'ption'
   ),
   'es-ES',
   'Línea',
   'src/Forms/inMtoDevolucionesCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoDevolucionesCompra.TfrmMtoDevolucionesCompra.colLineaDevcCODIGO_A',
     'RT.Caption'
   ),
   'es-ES',
   'Artículo',
   'src/Forms/inMtoDevolucionesCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoDevolucionesCompra.TfrmMtoDevolucionesCompra.colLineaDevcCODIGO_U',
     'NIDAD.Caption'
   ),
   'es-ES',
   'SKU',
   'src/Forms/inMtoDevolucionesCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoDevolucionesCompra.TfrmMtoDevolucionesCompra.colLineaDevcREF_PRV.',
     'Caption'
   ),
   'es-ES',
   'Modelo prov.',
   'src/Forms/inMtoDevolucionesCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoDevolucionesCompra.TfrmMtoDevolucionesCompra.colLineaDevcDESCRIPC',
     'ION.Caption'
   ),
   'es-ES',
   'Descripción',
   'src/Forms/inMtoDevolucionesCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoDevolucionesCompra.TfrmMtoDevolucionesCompra.colLineaDevcCANTIDAD',
     '.Caption'
   ),
   'es-ES',
   'Cantidad',
   'src/Forms/inMtoDevolucionesCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoDevolucionesCompra.TfrmMtoDevolucionesCompra.colLineaDevcPRECIO_C',
     'OMPRA.Caption'
   ),
   'es-ES',
   'Precio compra',
   'src/Forms/inMtoDevolucionesCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoDevolucionesCompra.TfrmMtoDevolucionesCompra.colLineaDevcPORCENTA',
     'JE_IVA.Caption'
   ),
   'es-ES',
   '% IVA',
   'src/Forms/inMtoDevolucionesCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoDevolucionesCompra.TfrmMtoDevolucionesCompra.colLineaDevcTOTAL.Ca',
     'ption'
   ),
   'es-ES',
   'Total',
   'src/Forms/inMtoDevolucionesCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoDevolucionesCompra.TfrmMtoDevolucionesCompra.colLineaDevcALMACEN.',
     'Caption'
   ),
   'es-ES',
   'Almacén',
   'src/Forms/inMtoDevolucionesCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoDevolucionesCompra.TfrmMtoDevolucionesCompra.tsTotales.Caption',
   'es-ES',
   '&2_Totales',
   'src/Forms/inMtoDevolucionesCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoDevolucionesCompra.TfrmMtoDevolucionesCompra.lblTotalesTotalBase.',
     'Caption'
   ),
   'es-ES',
   'Total Base Imponible',
   'src/Forms/inMtoDevolucionesCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoDevolucionesCompra.TfrmMtoDevolucionesCompra.lblTotalesTotalImpue',
     'stos.Caption'
   ),
   'es-ES',
   'Total Impuestos',
   'src/Forms/inMtoDevolucionesCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoDevolucionesCompra.TfrmMtoDevolucionesCompra.lblTotalesPorcRetenc',
     'ion.Caption'
   ),
   'es-ES',
   '% Retención',
   'src/Forms/inMtoDevolucionesCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoDevolucionesCompra.TfrmMtoDevolucionesCompra.lblTotalesTotalReten',
     'cion.Caption'
   ),
   'es-ES',
   'Total Retención',
   'src/Forms/inMtoDevolucionesCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoDevolucionesCompra.TfrmMtoDevolucionesCompra.lblTotalesTotalPagar',
     '.Caption'
   ),
   'es-ES',
   'Total a pagar',
   'src/Forms/inMtoDevolucionesCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoDevolucionesCompra.TfrmMtoDevolucionesCompra.lblTotalesFormaPago.',
     'Caption'
   ),
   'es-ES',
   'Forma de Pago',
   'src/Forms/inMtoDevolucionesCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoDevolucionesCompra.TfrmMtoDevolucionesCompra.chkTotalesESIVA_RECA',
     'RGO_COMPRAS_DEVC.Caption'
   ),
   'es-ES',
   'Recargo equivalencia compras',
   'src/Forms/inMtoDevolucionesCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoDevolucionesCompra.TfrmMtoDevolucionesCompra.lblTotalesDtoComerci',
     'al.Caption'
   ),
   'es-ES',
   'Dto. comercial',
   'src/Forms/inMtoDevolucionesCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoDevolucionesCompra.TfrmMtoDevolucionesCompra.lblTotalesDtoFinanci',
     'ero.Caption'
   ),
   'es-ES',
   'Dto. financiero',
   'src/Forms/inMtoDevolucionesCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoDevolucionesCompra.TfrmMtoDevolucionesCompra.grpDesgloseImpuestos',
     '.Caption'
   ),
   'es-ES',
   'Desglose Impuestos',
   'src/Forms/inMtoDevolucionesCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoDevolucionesCompra.TfrmMtoDevolucionesCompra.lblTotalesTotalRe.Ca',
     'ption'
   ),
   'es-ES',
   'Total R.E.',
   'src/Forms/inMtoDevolucionesCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoDevolucionesCompra.TfrmMtoDevolucionesCompra.lblTotalesPorRe.Caption',
   'es-ES',
   '%R.E.',
   'src/Forms/inMtoDevolucionesCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoDevolucionesCompra.TfrmMtoDevolucionesCompra.lblTotalesTotalIva.C',
     'aption'
   ),
   'es-ES',
   'Total IVA',
   'src/Forms/inMtoDevolucionesCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoDevolucionesCompra.TfrmMtoDevolucionesCompra.lblTotalesPorIva.Caption',
   'es-ES',
   '%IVA',
   'src/Forms/inMtoDevolucionesCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoDevolucionesCompra.TfrmMtoDevolucionesCompra.lblTotalesBaseNeta.C',
     'aption'
   ),
   'es-ES',
   'BaseNeta',
   'src/Forms/inMtoDevolucionesCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoDevolucionesCompra.TfrmMtoDevolucionesCompra.lblTotalesIVAN.Caption',
   'es-ES',
   'Normal',
   'src/Forms/inMtoDevolucionesCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoDevolucionesCompra.TfrmMtoDevolucionesCompra.lblTotalesIVAR.Caption',
   'es-ES',
   'Reducido',
   'src/Forms/inMtoDevolucionesCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoDevolucionesCompra.TfrmMtoDevolucionesCompra.lblTotalesIVAS.Caption',
   'es-ES',
   'Súper Reducido',
   'src/Forms/inMtoDevolucionesCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoDevolucionesCompra.TfrmMtoDevolucionesCompra.lblTotalesIVAE.Caption',
   'es-ES',
   'Exento',
   'src/Forms/inMtoDevolucionesCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoDevolucionesCompra.TfrmMtoDevolucionesCompra.tsProveedor.Caption',
   'es-ES',
   '&3_Movimientos',
   'src/Forms/inMtoDevolucionesCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoDevolucionesCompra.TfrmMtoDevolucionesCompra.colMovProvDevcNUMERO',
     '_MOV.Caption'
   ),
   'es-ES',
   'Número Mov.',
   'src/Forms/inMtoDevolucionesCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoDevolucionesCompra.TfrmMtoDevolucionesCompra.colMovProvDevcFECHA_',
     'MOV.Caption'
   ),
   'es-ES',
   'Fecha',
   'src/Forms/inMtoDevolucionesCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoDevolucionesCompra.TfrmMtoDevolucionesCompra.colMovProvDevcLINEA_',
     'MOV.Caption'
   ),
   'es-ES',
   'Línea',
   'src/Forms/inMtoDevolucionesCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoDevolucionesCompra.TfrmMtoDevolucionesCompra.colMovProvDevcALMACE',
     'N.Caption'
   ),
   'es-ES',
   'Almacén',
   'src/Forms/inMtoDevolucionesCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoDevolucionesCompra.TfrmMtoDevolucionesCompra.colMovProvDevcARTICU',
     'LO.Caption'
   ),
   'es-ES',
   'Artículo',
   'src/Forms/inMtoDevolucionesCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoDevolucionesCompra.TfrmMtoDevolucionesCompra.colMovProvDevcSKU.Ca',
     'ption'
   ),
   'es-ES',
   'SKU',
   'src/Forms/inMtoDevolucionesCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoDevolucionesCompra.TfrmMtoDevolucionesCompra.colMovProvDevcDESCRI',
     'PCION.Caption'
   ),
   'es-ES',
   'Descripción',
   'src/Forms/inMtoDevolucionesCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoDevolucionesCompra.TfrmMtoDevolucionesCompra.colMovProvDevcTIPO.C',
     'aption'
   ),
   'es-ES',
   'Tipo',
   'src/Forms/inMtoDevolucionesCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoDevolucionesCompra.TfrmMtoDevolucionesCompra.colMovProvDevcCANTID',
     'AD.Caption'
   ),
   'es-ES',
   'Cantidad',
   'src/Forms/inMtoDevolucionesCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoDevolucionesCompra.TfrmMtoDevolucionesCompra.colMovProvDevcPMP.Ca',
     'ption'
   ),
   'es-ES',
   'PMP',
   'src/Forms/inMtoDevolucionesCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoDevolucionesCompra.TfrmMtoDevolucionesCompra.colMovProvDevcTOTAL.',
     'Caption'
   ),
   'es-ES',
   'Total coste',
   'src/Forms/inMtoDevolucionesCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoDevolucionesCompra.TfrmMtoDevolucionesCompra.tsObservaciones.Caption',
   'es-ES',
   '&4_Observaciones',
   'src/Forms/inMtoDevolucionesCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoDevolucionesCompra.TfrmMtoDevolucionesCompra.lblTotalBases.Caption',
   'es-ES',
   'Total bases',
   'src/Forms/inMtoDevolucionesCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoDevolucionesCompra.TfrmMtoDevolucionesCompra.lblTotalImpuestos.Ca',
     'ption'
   ),
   'es-ES',
   'Total impuestos',
   'src/Forms/inMtoDevolucionesCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoDevolucionesCompra.TfrmMtoDevolucionesCompra.lblTotalLiquido.Caption',
   'es-ES',
   'Total líquido',
   'src/Forms/inMtoDevolucionesCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoDevolucionesCompra.TfrmMtoDevolucionesCompra.btnImprimirH.Caption',
   'es-ES',
   'Imprimir hor.',
   'src/Forms/inMtoDevolucionesCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoDevolucionesCompra.TfrmMtoDevolucionesCompra.btnImprimirV.Caption',
   'es-ES',
   'Imprimir vert.',
   'src/Forms/inMtoDevolucionesCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoDevolucionesCompra.TfrmMtoDevolucionesCompra.btnPegatinas.Caption',
   'es-ES',
   'Etiquetas',
   'src/Forms/inMtoDevolucionesCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoDevolucionesCompra.TfrmMtoDevolucionesCompra.actArticulos.Caption',
   'es-ES',
   'actArticulos',
   'src/Forms/inMtoDevolucionesCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoDevolucionesCompra.TfrmMtoDevolucionesCompra.actIrProveedor.Caption',
   'es-ES',
   'Ir a proveedor',
   'src/Forms/inMtoDevolucionesCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoDocumentosTrabajo.TfrmMtoDocumentosTrabajo.Caption',
   'es-ES',
   'Documentos de Trabajo',
   'src/Forms/inMtoDocumentosTrabajo.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoDocumentosTrabajo.TfrmMtoDocumentosTrabajo.tsAmbitoPropiosDTR.Caption',
   'es-ES',
   'Mis documentos',
   'src/Forms/inMtoDocumentosTrabajo.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoDocumentosTrabajo.TfrmMtoDocumentosTrabajo.tsAmbitoCompartidosDTR',
     '.Caption'
   ),
   'es-ES',
   'Compartidos conmigo',
   'src/Forms/inMtoDocumentosTrabajo.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoDocumentosTrabajo.TfrmMtoDocumentosTrabajo.colDtrId.Caption',
   'es-ES',
   'ID',
   'src/Forms/inMtoDocumentosTrabajo.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoDocumentosTrabajo.TfrmMtoDocumentosTrabajo.colDtrTitulo.Caption',
   'es-ES',
   'Titulo',
   'src/Forms/inMtoDocumentosTrabajo.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoDocumentosTrabajo.TfrmMtoDocumentosTrabajo.colDtrTipo.Caption',
   'es-ES',
   'Tipo',
   'src/Forms/inMtoDocumentosTrabajo.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoDocumentosTrabajo.TfrmMtoDocumentosTrabajo.colDtrEstado.Caption',
   'es-ES',
   'Estado',
   'src/Forms/inMtoDocumentosTrabajo.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoDocumentosTrabajo.TfrmMtoDocumentosTrabajo.colDtrUsuario.Caption',
   'es-ES',
   'Propietario',
   'src/Forms/inMtoDocumentosTrabajo.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoDocumentosTrabajo.TfrmMtoDocumentosTrabajo.colDtrInstante.Caption',
   'es-ES',
   'Fecha',
   'src/Forms/inMtoDocumentosTrabajo.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoDocumentosTrabajo.TfrmMtoDocumentosTrabajo.colDtrEmpresa.Caption',
   'es-ES',
   'Empresa',
   'src/Forms/inMtoDocumentosTrabajo.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoDocumentosTrabajo.TfrmMtoDocumentosTrabajo.colDtrAlmacen.Caption',
   'es-ES',
   'Almacen',
   'src/Forms/inMtoDocumentosTrabajo.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoDocumentosTrabajo.TfrmMtoDocumentosTrabajo.lblLineasDTR.Caption',
   'es-ES',
   'Detalle',
   'src/Forms/inMtoDocumentosTrabajo.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoDocumentosTrabajo.TfrmMtoDocumentosTrabajo.btnListadoDTR.Caption',
   'es-ES',
   'Listado',
   'src/Forms/inMtoDocumentosTrabajo.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoDocumentosTrabajo.TfrmMtoDocumentosTrabajo.btnEnviarADTR.Caption',
   'es-ES',
   'Enviar a...',
   'src/Forms/inMtoDocumentosTrabajo.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoDocumentosTrabajo.TfrmMtoDocumentosTrabajo.btnCargarFiltrosDTR.Ca',
     'ption'
   ),
   'es-ES',
   'Cargar articulos...',
   'src/Forms/inMtoDocumentosTrabajo.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoDocumentosTrabajo.TfrmMtoDocumentosTrabajo.btnCompartirDTR.Caption',
   'es-ES',
   'Compartir...',
   'src/Forms/inMtoDocumentosTrabajo.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoDocumentosTrabajo.TfrmMtoDocumentosTrabajo.btnImprimirEtiquetasDT',
     'R.Caption'
   ),
   'es-ES',
   'Imprimir etiquetas',
   'src/Forms/inMtoDocumentosTrabajo.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoDocumentosTrabajo.TfrmMtoDocumentosTrabajo.tsLineasDTR.Caption',
   'es-ES',
   'Lineas',
   'src/Forms/inMtoDocumentosTrabajo.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoDocumentosTrabajo.TfrmMtoDocumentosTrabajo.colDtlLinea.Caption',
   'es-ES',
   'Linea',
   'src/Forms/inMtoDocumentosTrabajo.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoDocumentosTrabajo.TfrmMtoDocumentosTrabajo.colDtlArticulo.Caption',
   'es-ES',
   'Articulo',
   'src/Forms/inMtoDocumentosTrabajo.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoDocumentosTrabajo.TfrmMtoDocumentosTrabajo.colDtlSku.Caption',
   'es-ES',
   'SKU',
   'src/Forms/inMtoDocumentosTrabajo.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoDocumentosTrabajo.TfrmMtoDocumentosTrabajo.colDtlAlmacen.Caption',
   'es-ES',
   'Almacen',
   'src/Forms/inMtoDocumentosTrabajo.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoDocumentosTrabajo.TfrmMtoDocumentosTrabajo.colDtlDescripcionArtic',
     'ulo.Caption'
   ),
   'es-ES',
   'Descripcion articulo',
   'src/Forms/inMtoDocumentosTrabajo.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoDocumentosTrabajo.TfrmMtoDocumentosTrabajo.colDtlModelo.Caption',
   'es-ES',
   'Modelo',
   'src/Forms/inMtoDocumentosTrabajo.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoDocumentosTrabajo.TfrmMtoDocumentosTrabajo.colDtlFamilia.Caption',
   'es-ES',
   'Familia',
   'src/Forms/inMtoDocumentosTrabajo.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoDocumentosTrabajo.TfrmMtoDocumentosTrabajo.colDtlProveedor.Caption',
   'es-ES',
   'Proveedor',
   'src/Forms/inMtoDocumentosTrabajo.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoDocumentosTrabajo.TfrmMtoDocumentosTrabajo.colDtlTemporada.Caption',
   'es-ES',
   'Temporada',
   'src/Forms/inMtoDocumentosTrabajo.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoDocumentosTrabajo.TfrmMtoDocumentosTrabajo.colDtlDescripcionSku.C',
     'aption'
   ),
   'es-ES',
   'Descripcion unidad',
   'src/Forms/inMtoDocumentosTrabajo.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoDocumentosTrabajo.TfrmMtoDocumentosTrabajo.colDtlCantidadStock.Ca',
     'ption'
   ),
   'es-ES',
   'Stock',
   'src/Forms/inMtoDocumentosTrabajo.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoDocumentosTrabajo.TfrmMtoDocumentosTrabajo.colDtlCantidad.Caption',
   'es-ES',
   'Cantidad',
   'src/Forms/inMtoDocumentosTrabajo.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoDocumentosTrabajo.TfrmMtoDocumentosTrabajo.colDtlOrigen.Caption',
   'es-ES',
   'Origen',
   'src/Forms/inMtoDocumentosTrabajo.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoDocumentosTrabajo.TfrmMtoDocumentosTrabajo.colDtlInstanteStock.Ca',
     'ption'
   ),
   'es-ES',
   'Instante stock',
   'src/Forms/inMtoDocumentosTrabajo.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoDocumentosTrabajo.TfrmMtoDocumentosTrabajo.tsCompartirDTR.Caption',
   'es-ES',
   'Compartido con',
   'src/Forms/inMtoDocumentosTrabajo.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoDocumentosTrabajo.TfrmMtoDocumentosTrabajo.colDtcTipoDestino.Caption',
   'es-ES',
   'Tipo',
   'src/Forms/inMtoDocumentosTrabajo.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoDocumentosTrabajo.TfrmMtoDocumentosTrabajo.colDtcUsuarioGrupo.Caption',
   'es-ES',
   'Usuario / grupo',
   'src/Forms/inMtoDocumentosTrabajo.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoDocumentosTrabajo.TfrmMtoDocumentosTrabajo.colDtcPermiso.Caption',
   'es-ES',
   'Permiso',
   'src/Forms/inMtoDocumentosTrabajo.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoDocumentosTrabajo.TfrmMtoDocumentosTrabajo.colDtcAlta.Caption',
   'es-ES',
   'Alta',
   'src/Forms/inMtoDocumentosTrabajo.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoDocumentosTrabajo.TfrmMtoDocumentosTrabajo.miEnviarAlbaranDTR.Caption',
   'es-ES',
   'Albarán de venta (mayor)...',
   'src/Forms/inMtoDocumentosTrabajo.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoDocumentosTrabajo.TfrmMtoDocumentosTrabajo.',
     'miEnviarFacturaVentaDTR.Caption'
   ),
   'es-ES',
   'Factura de venta (mayor)...',
   'src/Forms/inMtoDocumentosTrabajo.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoDocumentosTrabajo.TfrmMtoDocumentosTrabajo.miEnviarTpvDTR.Caption',
   'es-ES',
   'Venta TPV',
   'src/Forms/inMtoDocumentosTrabajo.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoDocumentosTrabajo.TfrmMtoDocumentosTrabajo.',
     'miEnviarPedidoCompraDTR.Caption'
   ),
   'es-ES',
   'Pedido de compra...',
   'src/Forms/inMtoDocumentosTrabajo.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoDocumentosTrabajo.TfrmMtoDocumentosTrabajo.',
     'miEnviarTraspasoCajaDTR.Caption'
   ),
   'es-ES',
   'Traspaso de caja...',
   'src/Forms/inMtoDocumentosTrabajo.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoDocumentosTrabajo.TfrmMtoDocumentosTrabajo.',
     'miEnviarPeticionTraspasoDTR.Caption'
   ),
   'es-ES',
   'Petición de traspaso...',
   'src/Forms/inMtoDocumentosTrabajo.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoDocumentosTrabajo.TfrmMtoDocumentosTrabajo.miEnviarInventarioDTR.',
     'Caption'
   ),
   'es-ES',
   'Inventario...',
   'src/Forms/inMtoDocumentosTrabajo.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoDocumentosTrabajo.TfrmMtoDocumentosTrabajo.miEnviarTarifasDTR.Caption',
   'es-ES',
   'Sesión de cambio de tarifas',
   'src/Forms/inMtoDocumentosTrabajo.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoEfectosCompra.TfrmMtoEfectosCompra.Caption',
   'es-ES',
   'Efectos de Pago a Proveedor',
   'src/Forms/inMtoEfectosCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoEfectosCompra.TfrmMtoEfectosCompra.dbcGrdDBTabPrinNUMERO_FACC_EFE',
     'C.Caption'
   ),
   'es-ES',
   'Borrador',
   'src/Forms/inMtoEfectosCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoEfectosCompra.TfrmMtoEfectosCompra.dbcGrdDBTabPrinSERIE_FACC_EFEC',
     '.Caption'
   ),
   'es-ES',
   'Serie',
   'src/Forms/inMtoEfectosCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoEfectosCompra.TfrmMtoEfectosCompra.dbcGrdDBTabPrinNUMERO_EFEC.Caption',
   'es-ES',
   'Efecto',
   'src/Forms/inMtoEfectosCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoEfectosCompra.TfrmMtoEfectosCompra.dbcGrdDBTabPrinNOMBRE_PRV_VIEW',
     '_EFEC.Caption'
   ),
   'es-ES',
   'Proveedor',
   'src/Forms/inMtoEfectosCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoEfectosCompra.TfrmMtoEfectosCompra.dbcGrdDBTabPrinDESCRIPCION_TEF',
     'E_VIEW_EFEC.Caption'
   ),
   'es-ES',
   'Tipo',
   'src/Forms/inMtoEfectosCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoEfectosCompra.TfrmMtoEfectosCompra.dbcGrdDBTabPrinFECHA_VENCIMIEN',
     'TO_EFEC.Caption'
   ),
   'es-ES',
   'Vencimiento',
   'src/Forms/inMtoEfectosCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoEfectosCompra.TfrmMtoEfectosCompra.dbcGrdDBTabPrinIMPORTE_EFEC.Ca',
     'ption'
   ),
   'es-ES',
   'Importe',
   'src/Forms/inMtoEfectosCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoEfectosCompra.TfrmMtoEfectosCompra.dbcGrdDBTabPrinIMPORTE_PENDIEN',
     'TE_EFEC.Caption'
   ),
   'es-ES',
   'Pendiente',
   'src/Forms/inMtoEfectosCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoEfectosCompra.TfrmMtoEfectosCompra.dbcGrdDBTabPrinESTADO_EFEC.Caption',
   'es-ES',
   'Estado',
   'src/Forms/inMtoEfectosCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoEfectosCompra.TfrmMtoEfectosCompra.dbcGrdDBTabPrinREFERENCIA_DOCU',
     'MENTO_EFEC.Caption'
   ),
   'es-ES',
   'Ref. doc.',
   'src/Forms/inMtoEfectosCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoEfectosCompra.TfrmMtoEfectosCompra.dbcGrdDBTabPrinFECHA_PAGO_EFEC',
     '.Caption'
   ),
   'es-ES',
   'F. pago',
   'src/Forms/inMtoEfectosCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoEfectosCompra.TfrmMtoEfectosCompra.dbcGrdDBTabPrinNUMERO_REMC_EFE',
     'C.Caption'
   ),
   'es-ES',
   'Remesa',
   'src/Forms/inMtoEfectosCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoEfectosCompra.TfrmMtoEfectosCompra.btnRegistrarPago.Caption',
   'es-ES',
   'Conciliar efecto',
   'src/Forms/inMtoEfectosCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoEfectosCompra.TfrmMtoEfectosCompra.btnFusionarEfectos.Caption',
   'es-ES',
   'Fusionar efectos',
   'src/Forms/inMtoEfectosCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoEfectosVenta.TfrmMtoEfectosVenta.Caption',
   'es-ES',
   'Efectos de Cobro a Cliente',
   'src/Forms/inMtoEfectosVenta.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoEfectosVenta.TfrmMtoEfectosVenta.dbcGrdDBTabPrinNUMERO_FAC_EFV.Ca',
     'ption'
   ),
   'es-ES',
   'Borrador',
   'src/Forms/inMtoEfectosVenta.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoEfectosVenta.TfrmMtoEfectosVenta.dbcGrdDBTabPrinSERIE_FAC_EFV.Caption',
   'es-ES',
   'Serie',
   'src/Forms/inMtoEfectosVenta.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoEfectosVenta.TfrmMtoEfectosVenta.dbcGrdDBTabPrinNUMERO_EFV.Caption',
   'es-ES',
   'Efecto',
   'src/Forms/inMtoEfectosVenta.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoEfectosVenta.TfrmMtoEfectosVenta.dbcGrdDBTabPrinNOMBRE_CLI_VIEW_E',
     'FV.Caption'
   ),
   'es-ES',
   'Cliente',
   'src/Forms/inMtoEfectosVenta.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoEfectosVenta.TfrmMtoEfectosVenta.dbcGrdDBTabPrinDESCRIPCION_TEFE_',
     'VIEW_EFV.Caption'
   ),
   'es-ES',
   'Tipo',
   'src/Forms/inMtoEfectosVenta.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoEfectosVenta.TfrmMtoEfectosVenta.dbcGrdDBTabPrinFECHA_VENCIMIENTO',
     '_EFV.Caption'
   ),
   'es-ES',
   'Vencimiento',
   'src/Forms/inMtoEfectosVenta.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoEfectosVenta.TfrmMtoEfectosVenta.dbcGrdDBTabPrinIMPORTE_EFV.Caption',
   'es-ES',
   'Importe',
   'src/Forms/inMtoEfectosVenta.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoEfectosVenta.TfrmMtoEfectosVenta.dbcGrdDBTabPrinIMPORTE_PENDIENTE',
     '_EFV.Caption'
   ),
   'es-ES',
   'Pendiente',
   'src/Forms/inMtoEfectosVenta.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoEfectosVenta.TfrmMtoEfectosVenta.dbcGrdDBTabPrinESTADO_EFV.Caption',
   'es-ES',
   'Estado',
   'src/Forms/inMtoEfectosVenta.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoEfectosVenta.TfrmMtoEfectosVenta.dbcGrdDBTabPrinREFERENCIA_DOCUME',
     'NTO_EFV.Caption'
   ),
   'es-ES',
   'Ref. doc.',
   'src/Forms/inMtoEfectosVenta.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoEfectosVenta.TfrmMtoEfectosVenta.dbcGrdDBTabPrinFECHA_COBRO_EFV.C',
     'aption'
   ),
   'es-ES',
   'F. cobro',
   'src/Forms/inMtoEfectosVenta.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoEfectosVenta.TfrmMtoEfectosVenta.dbcGrdDBTabPrinNUMERO_REMV_EFV.C',
     'aption'
   ),
   'es-ES',
   'Remesa',
   'src/Forms/inMtoEfectosVenta.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoEfectosVenta.TfrmMtoEfectosVenta.btnRegistrarCobro.Caption',
   'es-ES',
   'Conciliar efecto',
   'src/Forms/inMtoEfectosVenta.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoEfectosVenta.TfrmMtoEfectosVenta.btnFusionarEfectos.Caption',
   'es-ES',
   'Fusionar efectos',
   'src/Forms/inMtoEfectosVenta.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoEmpleados.TfrmMtoEmpleados.Caption',
   'es-ES',
   'Empleados',
   'src/Forms/inMtoEmpleados.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoEmpleados.TfrmMtoEmpleados.cxGrdDBTabPrinCODIGO_EMPL.Caption',
   'es-ES',
   'Código Empleado',
   'src/Forms/inMtoEmpleados.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoEmpleados.TfrmMtoEmpleados.cxGrdDBTabPrinNOMBRE_EMPL.Caption',
   'es-ES',
   'Nombre',
   'src/Forms/inMtoEmpleados.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoEmpleados.TfrmMtoEmpleados.cxGrdDBTabPrinRAZON_SOCIAL_EMPL.Caption',
   'es-ES',
   'Razón Social',
   'src/Forms/inMtoEmpleados.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoEmpleados.TfrmMtoEmpleados.cxGrdDBTabPrinNIF_EMPL.Caption',
   'es-ES',
   'NIF',
   'src/Forms/inMtoEmpleados.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoEmpleados.TfrmMtoEmpleados.cxGrdDBTabPrinDIRECCION_EMPL.Caption',
   'es-ES',
   'Dirección 1',
   'src/Forms/inMtoEmpleados.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoEmpleados.TfrmMtoEmpleados.cxGrdDBTabPrinDIRECCION2_EMPL.Caption',
   'es-ES',
   'Dirección 2',
   'src/Forms/inMtoEmpleados.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoEmpleados.TfrmMtoEmpleados.cxGrdDBTabPrinCODIGO_POSTAL_EMPL.Caption',
   'es-ES',
   'C.P.',
   'src/Forms/inMtoEmpleados.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoEmpleados.TfrmMtoEmpleados.cxGrdDBTabPrinPOBLACION_EMPL.Caption',
   'es-ES',
   'Población',
   'src/Forms/inMtoEmpleados.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoEmpleados.TfrmMtoEmpleados.cxGrdDBTabPrinPROVINCIA_EMPL.Caption',
   'es-ES',
   'Provincia',
   'src/Forms/inMtoEmpleados.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoEmpleados.TfrmMtoEmpleados.cxGrdDBTabPrinTELEFONO_EMPL.Caption',
   'es-ES',
   'Teléfono 1',
   'src/Forms/inMtoEmpleados.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoEmpleados.TfrmMtoEmpleados.cxGrdDBTabPrinTELEFONO2_EMPL.Caption',
   'es-ES',
   'Teléfono 2',
   'src/Forms/inMtoEmpleados.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoEmpleados.TfrmMtoEmpleados.cxGrdDBTabPrinFAX_EMPL.Caption',
   'es-ES',
   'Fax',
   'src/Forms/inMtoEmpleados.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoEmpleados.TfrmMtoEmpleados.cxGrdDBTabPrinEMAIL_EMPL.Caption',
   'es-ES',
   'Email',
   'src/Forms/inMtoEmpleados.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoEmpleados.TfrmMtoEmpleados.cxGrdDBTabPrinWEB_EMPL.Caption',
   'es-ES',
   'Web',
   'src/Forms/inMtoEmpleados.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoEmpleados.TfrmMtoEmpleados.cxGrdDBTabPrinIBAN_EMPL.Caption',
   'es-ES',
   'IBAN',
   'src/Forms/inMtoEmpleados.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoEmpleados.TfrmMtoEmpleados.cxGrdDBTabPrinBIC_EMPL.Caption',
   'es-ES',
   'BIC',
   'src/Forms/inMtoEmpleados.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoEmpleados.TfrmMtoEmpleados.cxGrdDBTabPrinDIMINUTIVO_TICKET_EMPL.C',
     'aption'
   ),
   'es-ES',
   'Diminutivo Caja',
   'src/Forms/inMtoEmpleados.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoEmpleados.TfrmMtoEmpleados.cxGrdDBTabPrinESACTIVO_EMPL.Caption',
   'es-ES',
   'Activo',
   'src/Forms/inMtoEmpleados.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoEmpresas.TfrmMtoEmpresas.Caption',
   'es-ES',
   'Empresas',
   'src/Forms/inMtoEmpresas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoEmpresas.TfrmMtoEmpresas.cxgrdbclmnGrdDBTabPrinCODIGO_EMPRESA.Caption',
   'es-ES',
   'Código',
   'src/Forms/inMtoEmpresas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoEmpresas.TfrmMtoEmpresas.cxgrdbclmnGrdDBTabPrinORDEN_EMPRESA.Caption',
   'es-ES',
   'Orden',
   'src/Forms/inMtoEmpresas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoEmpresas.TfrmMtoEmpresas.cxgrdbclmnGrdDBTabPrinACTIVA_EMPRESA.Caption',
   'es-ES',
   'Activo',
   'src/Forms/inMtoEmpresas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoEmpresas.TfrmMtoEmpresas.cxgrdbclmnGrdDBTabPrinRAZONSOCIAL_EMPRES',
     'A.Caption'
   ),
   'es-ES',
   'Razón Social',
   'src/Forms/inMtoEmpresas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoEmpresas.TfrmMtoEmpresas.cxgrdbclmnGrdDBTabPrinNIF_EMPRESA.Caption',
   'es-ES',
   'Nif',
   'src/Forms/inMtoEmpresas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoEmpresas.TfrmMtoEmpresas.cxgrdbclmnGrdDBTabPrinMOVIL_EMPRESA.Caption',
   'es-ES',
   'Móvil',
   'src/Forms/inMtoEmpresas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoEmpresas.TfrmMtoEmpresas.cxgrdbclmnGrdDBTabPrinEMAIL_EMPRESA.Caption',
   'es-ES',
   'Email',
   'src/Forms/inMtoEmpresas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoEmpresas.TfrmMtoEmpresas.cxgrdbclmnGrdDBTabPrinDIRECCION1_EMPRESA',
     '.Caption'
   ),
   'es-ES',
   'Direción',
   'src/Forms/inMtoEmpresas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoEmpresas.TfrmMtoEmpresas.cxgrdbclmnGrdDBTabPrinDIRECCION2_EMPRESA',
     '.Caption'
   ),
   'es-ES',
   'Más Dirección',
   'src/Forms/inMtoEmpresas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoEmpresas.TfrmMtoEmpresas.cxgrdbclmnGrdDBTabPrinPOBLACION_EMPRESA.',
     'Caption'
   ),
   'es-ES',
   'Población',
   'src/Forms/inMtoEmpresas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoEmpresas.TfrmMtoEmpresas.cxgrdbclmnGrdDBTabPrinPROVINCIA_EMPRESA.',
     'Caption'
   ),
   'es-ES',
   'Provincia',
   'src/Forms/inMtoEmpresas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoEmpresas.TfrmMtoEmpresas.cxgrdbclmnGrdDBTabPrinCPOSTAL_EMPRESA.Ca',
     'ption'
   ),
   'es-ES',
   'Código Postal',
   'src/Forms/inMtoEmpresas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoEmpresas.TfrmMtoEmpresas.cxGrdDBTabPrinDESCRIPCION_ZONA_IVA.Caption',
   'es-ES',
   'Zona de IVA principal',
   'src/Forms/inMtoEmpresas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoEmpresas.TfrmMtoEmpresas.cxgrdbclmnGrdDBTabPrin_ESREGIMENESPECIAL',
     'AGRICOLA_EMPRESA.Caption'
   ),
   'es-ES',
   'Es REAGP',
   'src/Forms/inMtoEmpresas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoEmpresas.TfrmMtoEmpresas.cxgrdbclmnGrdDBTabPrinESRETENCIONES_EMPR',
     'ESA.Caption'
   ),
   'es-ES',
   'Aplica Retenciones',
   'src/Forms/inMtoEmpresas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoEmpresas.TfrmMtoEmpresas.cxgrdbclmnGrdDBTabPrinESIVA_RECARGO_COMP',
     'RAS_EMPRESA.Caption'
   ),
   'es-ES',
   'R.E. compras',
   'src/Forms/inMtoEmpresas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoEmpresas.TfrmMtoEmpresas.cxgrdbclmnGrdDBTabPrinTEXTO_LEGAL_FACTUR',
     'A_EMPRESA.Caption'
   ),
   'es-ES',
   'Texto en Borrador',
   'src/Forms/inMtoEmpresas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoEmpresas.TfrmMtoEmpresas.tsMasDatos.Caption',
   'es-ES',
   '&1_Más Datos',
   'src/Forms/inMtoEmpresas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoEmpresas.TfrmMtoEmpresas.lblMovil.Caption',
   'es-ES',
   'Móvil',
   'src/Forms/inMtoEmpresas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoEmpresas.TfrmMtoEmpresas.lblEmail.Caption',
   'es-ES',
   'Email',
   'src/Forms/inMtoEmpresas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoEmpresas.TfrmMtoEmpresas.lblDireccion.Caption',
   'es-ES',
   'Dirección',
   'src/Forms/inMtoEmpresas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoEmpresas.TfrmMtoEmpresas.lblPoblacion.Caption',
   'es-ES',
   'Población',
   'src/Forms/inMtoEmpresas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoEmpresas.TfrmMtoEmpresas.lblProvincia.Caption',
   'es-ES',
   'Provincia',
   'src/Forms/inMtoEmpresas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoEmpresas.TfrmMtoEmpresas.chkRegimenEspecial.Caption',
   'es-ES',
   'Régimen especial agricola/ganadero/pesca',
   'src/Forms/inMtoEmpresas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoEmpresas.TfrmMtoEmpresas.lblCodPostal.Caption',
   'es-ES',
   'Cód Postal',
   'src/Forms/inMtoEmpresas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoEmpresas.TfrmMtoEmpresas.lblIBAN.Caption',
   'es-ES',
   'IBAN',
   'src/Forms/inMtoEmpresas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoEmpresas.TfrmMtoEmpresas.btnValidar.Caption',
   'es-ES',
   'Vali&dar',
   'src/Forms/inMtoEmpresas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoEmpresas.TfrmMtoEmpresas.lblProvincia1.Caption',
   'es-ES',
   'País',
   'src/Forms/inMtoEmpresas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoEmpresas.TfrmMtoEmpresas.cbbPaises.Properties.ListColumns[0].Caption',
   'es-ES',
   'Nombre Pais',
   'src/Forms/inMtoEmpresas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoEmpresas.TfrmMtoEmpresas.chkRecargoEquivalenciaCompras.Caption',
   'es-ES',
   'Recargo equivalencia compras',
   'src/Forms/inMtoEmpresas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoEmpresas.TfrmMtoEmpresas.tsRetenciones.Caption',
   'es-ES',
   '&2_Retenciones',
   'src/Forms/inMtoEmpresas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoEmpresas.TfrmMtoEmpresas.btnAddIRPF.Caption',
   'es-ES',
   '&Añadir IRPF',
   'src/Forms/inMtoEmpresas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoEmpresas.TfrmMtoEmpresas.cxgrdbclmntv1CODIGO_RETENCION.Caption',
   'es-ES',
   'Código Retención',
   'src/Forms/inMtoEmpresas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoEmpresas.TfrmMtoEmpresas.tvRetencionesPORCENRETENCION_RETENCION.C',
     'aption'
   ),
   'es-ES',
   '% Retención',
   'src/Forms/inMtoEmpresas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoEmpresas.TfrmMtoEmpresas.cxgrdbclmntv1FECHA_DESDE_RETENCION.Caption',
   'es-ES',
   'Fecha Aplicación desde',
   'src/Forms/inMtoEmpresas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoEmpresas.TfrmMtoEmpresas.cxgrdbclmntv1FECHA_HASTA_RETENCION.Caption',
   'es-ES',
   'Fecha Aplicación hasta',
   'src/Forms/inMtoEmpresas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoEmpresas.TfrmMtoEmpresas.tsHistoriaFacturacion.Caption',
   'es-ES',
   '&3_Histórico Borradores',
   'src/Forms/inMtoEmpresas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoEmpresas.TfrmMtoEmpresas.tvFacturacionFECHA_FACTURA.Caption',
   'es-ES',
   'Fecha',
   'src/Forms/inMtoEmpresas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoEmpresas.TfrmMtoEmpresas.tvFacturacionNRO_FACTURA.Caption',
   'es-ES',
   'Nro',
   'src/Forms/inMtoEmpresas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoEmpresas.TfrmMtoEmpresas.tvFacturacionSERIE_FACTURA.Caption',
   'es-ES',
   'Serie',
   'src/Forms/inMtoEmpresas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoEmpresas.TfrmMtoEmpresas.tvFacturacionTOTAL_LIQUIDO_FACTURA.Caption',
   'es-ES',
   'Total a Pagar',
   'src/Forms/inMtoEmpresas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoEmpresas.TfrmMtoEmpresas.tvFacturacionPORCEN_RETENCION_FACTURA.Ca',
     'ption'
   ),
   'es-ES',
   '% IRPF',
   'src/Forms/inMtoEmpresas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoEmpresas.TfrmMtoEmpresas.tvFacturacionTOTAL_RETENCION_FACTURA.Caption',
   'es-ES',
   'Total IRPF',
   'src/Forms/inMtoEmpresas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoEmpresas.TfrmMtoEmpresas.tvFacturacionTOTAL_BASES_FACTURA.Caption',
   'es-ES',
   'Total Bases Imponibles',
   'src/Forms/inMtoEmpresas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoEmpresas.TfrmMtoEmpresas.tvFacturacionTOTAL_IMPUESTOS_FACTURA.Caption',
   'es-ES',
   'IVA + RE',
   'src/Forms/inMtoEmpresas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoEmpresas.TfrmMtoEmpresas.tvFacturacionFORMA_PAGO_FACTURA.Caption',
   'es-ES',
   'Forma de Pago',
   'src/Forms/inMtoEmpresas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoEmpresas.TfrmMtoEmpresas.tvFacturacionDESCRIPCION_FORMAPAGO.Caption',
   'es-ES',
   'Descripción Forma Pago',
   'src/Forms/inMtoEmpresas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoEmpresas.TfrmMtoEmpresas.tvFacturacionCODIGO_CLIENTE_FACTURA.Caption',
   'es-ES',
   'Código Cliente',
   'src/Forms/inMtoEmpresas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoEmpresas.TfrmMtoEmpresas.tvFacturacionRAZONSOCIAL_CLIENTE_FACTURA',
     '.Caption'
   ),
   'es-ES',
   'Razón Social Clietne',
   'src/Forms/inMtoEmpresas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoEmpresas.TfrmMtoEmpresas.tvFacturacionNIF_CLIENTE_FACTURA.Caption',
   'es-ES',
   'Nif Cliente',
   'src/Forms/inMtoEmpresas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoEmpresas.TfrmMtoEmpresas.tvFacturacionMOVIL_CLIENTE_FACTURA.Caption',
   'es-ES',
   'Móvil Cliente',
   'src/Forms/inMtoEmpresas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoEmpresas.TfrmMtoEmpresas.tvFacturacionEMAIL_CLIENTE_FACTURA.Caption',
   'es-ES',
   'Email Cliente',
   'src/Forms/inMtoEmpresas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoEmpresas.TfrmMtoEmpresas.tvFacturacionDIRECCION1_CLIENTE_FACTURA.',
     'Caption'
   ),
   'es-ES',
   'Dirección1 Cliente',
   'src/Forms/inMtoEmpresas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoEmpresas.TfrmMtoEmpresas.tvFacturacionDIRECCION2_CLIENTE_FACTURA.',
     'Caption'
   ),
   'es-ES',
   'Dirección2 Cliente',
   'src/Forms/inMtoEmpresas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoEmpresas.TfrmMtoEmpresas.tvFacturacionCPOSTAL_CLIENTE_FACTURA.Caption',
   'es-ES',
   'CPostal Cliente',
   'src/Forms/inMtoEmpresas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoEmpresas.TfrmMtoEmpresas.tvFacturacionPOBLACION_CLIENTE_FACTURA.C',
     'aption'
   ),
   'es-ES',
   'Población Cliente',
   'src/Forms/inMtoEmpresas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoEmpresas.TfrmMtoEmpresas.tvFacturacionPROVINCIA_CLIENTE_FACTURA.C',
     'aption'
   ),
   'es-ES',
   'Provincia Cliente',
   'src/Forms/inMtoEmpresas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoEmpresas.TfrmMtoEmpresas.tvFacturacionPAIS_CLIENTE_FACTURA.Caption',
   'es-ES',
   'País Cliente',
   'src/Forms/inMtoEmpresas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoEmpresas.TfrmMtoEmpresas.tvFacturacionESIVA_RECARGO_CLIENTE_FACTU',
     'RA.Caption'
   ),
   'es-ES',
   'Tiene RE Cliente',
   'src/Forms/inMtoEmpresas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoEmpresas.TfrmMtoEmpresas.tvFacturacionESIVA_EXENTO_CLIENTE_FACTUR',
     'A.Caption'
   ),
   'es-ES',
   'IVA Exento Cliente',
   'src/Forms/inMtoEmpresas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoEmpresas.TfrmMtoEmpresas.tvFacturacionESREGIMENESPECIALAGRICOLA_C',
     'LIENTE_FACTURA.Caption'
   ),
   'es-ES',
   'REAGP Cliente',
   'src/Forms/inMtoEmpresas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoEmpresas.TfrmMtoEmpresas.tvFacturacionESRETENCIONES_CLIENTE_FACTU',
     'RA.Caption'
   ),
   'es-ES',
   'Tiene IRPF Cliente',
   'src/Forms/inMtoEmpresas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoEmpresas.TfrmMtoEmpresas.tvFacturacionNOMBRE_TARIFA_CLIENTE.Caption',
   'es-ES',
   'Tarifa Cliente',
   'src/Forms/inMtoEmpresas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoEmpresas.TfrmMtoEmpresas.tvFacturacionESIMP_INCL_TARIFA_CLIENTE_F',
     'ACTURA.Caption'
   ),
   'es-ES',
   'Tarifa tiene Imp Incl',
   'src/Forms/inMtoEmpresas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoEmpresas.TfrmMtoEmpresas.tvFacturacionESINTRACOMUNITARIO_CLIENTE_',
     'FACTURA.Caption'
   ),
   'es-ES',
   'Es Cliente Intracomunitario',
   'src/Forms/inMtoEmpresas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoEmpresas.TfrmMtoEmpresas.tvFacturacionESIVAAGRICOLA_ZONA_IVA_FACT',
     'URA.Caption'
   ),
   'es-ES',
   'IVA Agrícola',
   'src/Forms/inMtoEmpresas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoEmpresas.TfrmMtoEmpresas.tvFacturacionDESCRIPCION_ZONA_IVA.Caption',
   'es-ES',
   'Zona IVA',
   'src/Forms/inMtoEmpresas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoEmpresas.TfrmMtoEmpresas.tvFacturacionPORCEN_IVAN_FACTURA.Caption',
   'es-ES',
   '% IVA Normal',
   'src/Forms/inMtoEmpresas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoEmpresas.TfrmMtoEmpresas.tvFacturacionTOTAL_IVAN_FACTURA.Caption',
   'es-ES',
   'IVA Normal',
   'src/Forms/inMtoEmpresas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoEmpresas.TfrmMtoEmpresas.tvFacturacionPORCEN_REN_FACTURA.Caption',
   'es-ES',
   '% RE Normal',
   'src/Forms/inMtoEmpresas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoEmpresas.TfrmMtoEmpresas.tvFacturacionTOTAL_REN_FACTURA.Caption',
   'es-ES',
   'RE Normal',
   'src/Forms/inMtoEmpresas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoEmpresas.TfrmMtoEmpresas.tvFacturacionTOTAL_BASEI_IVAN_FACTURA.Ca',
     'ption'
   ),
   'es-ES',
   'Base Imp Normal',
   'src/Forms/inMtoEmpresas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoEmpresas.TfrmMtoEmpresas.tvFacturacionPORCEN_IVAR_FACTURA.Caption',
   'es-ES',
   '% IVA Reducido',
   'src/Forms/inMtoEmpresas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoEmpresas.TfrmMtoEmpresas.tvFacturacionTOTAL_IVAR_FACTURA.Caption',
   'es-ES',
   'IVA Reducido',
   'src/Forms/inMtoEmpresas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoEmpresas.TfrmMtoEmpresas.tvFacturacionPORCEN_RER_FACTURA.Caption',
   'es-ES',
   '% RE Reducido',
   'src/Forms/inMtoEmpresas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoEmpresas.TfrmMtoEmpresas.tvFacturacionTOTAL_RER_FACTURA.Caption',
   'es-ES',
   'RE Reducido',
   'src/Forms/inMtoEmpresas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoEmpresas.TfrmMtoEmpresas.tvFacturacionTOTAL_BASEI_IVAR_FACTURA.Ca',
     'ption'
   ),
   'es-ES',
   'Base Imp Reducido',
   'src/Forms/inMtoEmpresas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoEmpresas.TfrmMtoEmpresas.tvFacturacionPORCEN_IVAS_FACTURA.Caption',
   'es-ES',
   '% IVA SúperReducido',
   'src/Forms/inMtoEmpresas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoEmpresas.TfrmMtoEmpresas.tvFacturacionTOTAL_IVAS_FACTURA.Caption',
   'es-ES',
   'IVA SúperReducido',
   'src/Forms/inMtoEmpresas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoEmpresas.TfrmMtoEmpresas.tvFacturacionPORCEN_RES_FACTURA.Caption',
   'es-ES',
   '% RE SúperReducido',
   'src/Forms/inMtoEmpresas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoEmpresas.TfrmMtoEmpresas.tvFacturacionTOTAL_RES_FACTURA.Caption',
   'es-ES',
   'RE SúperReducido',
   'src/Forms/inMtoEmpresas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoEmpresas.TfrmMtoEmpresas.tvFacturacionTOTAL_BASEI_IVAS_FACTURA.Ca',
     'ption'
   ),
   'es-ES',
   'Base Imp SúperReducido',
   'src/Forms/inMtoEmpresas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoEmpresas.TfrmMtoEmpresas.tvFacturacionPORCEN_IVAE_FACTURA.Caption',
   'es-ES',
   '% IVA Exento',
   'src/Forms/inMtoEmpresas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoEmpresas.TfrmMtoEmpresas.tvFacturacionTOTAL_IVAE_FACTURA.Caption',
   'es-ES',
   'IVA Exento',
   'src/Forms/inMtoEmpresas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoEmpresas.TfrmMtoEmpresas.tvFacturacionPORCEN_REE_FACTURA.Caption',
   'es-ES',
   'RE Exento',
   'src/Forms/inMtoEmpresas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoEmpresas.TfrmMtoEmpresas.tvFacturacionTOTAL_REE_FACTURA.Caption',
   'es-ES',
   'RE Exento',
   'src/Forms/inMtoEmpresas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoEmpresas.TfrmMtoEmpresas.tvFacturacionTOTAL_BASEI_IVAE_FACTURA.Ca',
     'ption'
   ),
   'es-ES',
   'Base Imp Exento',
   'src/Forms/inMtoEmpresas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoEmpresas.TfrmMtoEmpresas.tvLineasFacturacionLINEA_LINEA.Caption',
   'es-ES',
   'Nro Linea',
   'src/Forms/inMtoEmpresas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoEmpresas.TfrmMtoEmpresas.tvLineasFacturacionCODIGO_ARTICULO_LINEA',
     '.Caption'
   ),
   'es-ES',
   'Código Artículo',
   'src/Forms/inMtoEmpresas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoEmpresas.TfrmMtoEmpresas.tvLineasFacturacionDESCRIPCION_ARTICULO_',
     'LINEA.Caption'
   ),
   'es-ES',
   'Descripción',
   'src/Forms/inMtoEmpresas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoEmpresas.TfrmMtoEmpresas.tvLineasFacturacionCANTIDAD_LINEA.Caption',
   'es-ES',
   'Cantidad',
   'src/Forms/inMtoEmpresas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoEmpresas.TfrmMtoEmpresas.tvLineasFacturacionTIPO_CANTIDAD_ARTICUL',
     'O_FACTURA_LINEA.Caption'
   ),
   'es-ES',
   'Tipo Cantidad',
   'src/Forms/inMtoEmpresas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoEmpresas.TfrmMtoEmpresas.tvLineasFacturacionPRECIOVENTA_SIVA_ARTI',
     'CULO_FACTURA_LINEA.Caption'
   ),
   'es-ES',
   'Precio SIVA',
   'src/Forms/inMtoEmpresas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoEmpresas.TfrmMtoEmpresas.tvLineasFacturacionPORCEN_IVA_FACTURA_LI',
     'NEA.Caption'
   ),
   'es-ES',
   'Porcentaje IVA',
   'src/Forms/inMtoEmpresas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoEmpresas.TfrmMtoEmpresas.tvLineasFacturacionPRECIOVENTA_ARTICULO_',
     'LINEA.Caption'
   ),
   'es-ES',
   'Precio CIVA',
   'src/Forms/inMtoEmpresas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoEmpresas.TfrmMtoEmpresas.tvLineasFacturacionSUM_TOTAL_LINEA.Caption',
   'es-ES',
   'Total',
   'src/Forms/inMtoEmpresas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoEmpresas.TfrmMtoEmpresas.tvLineasFacturacionFECHA_ENTREGA_FACTURA',
     '_LINEA.Caption'
   ),
   'es-ES',
   'Fecha de Entrega',
   'src/Forms/inMtoEmpresas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoEmpresas.TfrmMtoEmpresas.btnIraFactura.Caption',
   'es-ES',
   '&Ir a Borrador',
   'src/Forms/inMtoEmpresas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoEmpresas.TfrmMtoEmpresas.btnIraCliente.Caption',
   'es-ES',
   'I&r a Cliente',
   'src/Forms/inMtoEmpresas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoEmpresas.TfrmMtoEmpresas.btnExportarExcel.Caption',
   'es-ES',
   'Exp. Excel',
   'src/Forms/inMtoEmpresas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoEmpresas.TfrmMtoEmpresas.btnIraArticulo.Caption',
   'es-ES',
   'I&r a Artículo',
   'src/Forms/inMtoEmpresas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoEmpresas.TfrmMtoEmpresas.tsSeries.Caption',
   'es-ES',
   '&4_Series',
   'src/Forms/inMtoEmpresas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoEmpresas.TfrmMtoEmpresas.btnAddSerie.Caption',
   'es-ES',
   'Añadir Serie',
   'src/Forms/inMtoEmpresas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoEmpresas.TfrmMtoEmpresas.btnCrearSeriesDoc.Caption',
   'es-ES',
   'Añadir serie a todos',
   'src/Forms/inMtoEmpresas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoEmpresas.TfrmMtoEmpresas.dbmSeriesCODIGO_ALMACEN_SERIE.Caption',
   'es-ES',
   'Almacén',
   'src/Forms/inMtoEmpresas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoEmpresas.TfrmMtoEmpresas.dbmSeriesCODIGO_CAJA_SERIE.Caption',
   'es-ES',
   'Caja',
   'src/Forms/inMtoEmpresas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoEmpresas.TfrmMtoEmpresas.dbmSeriesSERIE_SERIE.Caption',
   'es-ES',
   'Serie',
   'src/Forms/inMtoEmpresas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoEmpresas.TfrmMtoEmpresas.dbmSeriesTIPODOC_SERIE.Caption',
   'es-ES',
   'Tipo Doc',
   'src/Forms/inMtoEmpresas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoEmpresas.TfrmMtoEmpresas.dbmSeriesSUBITPO_SERIE.Caption',
   'es-ES',
   'Subtipo',
   'src/Forms/inMtoEmpresas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoEmpresas.TfrmMtoEmpresas.dbmSeriesFECHA_DESDE_SERIE.Caption',
   'es-ES',
   'Fecha Desde',
   'src/Forms/inMtoEmpresas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoEmpresas.TfrmMtoEmpresas.dbmSeriesFECHA_HASTA_SERIE.Caption',
   'es-ES',
   'Fecha Hasta',
   'src/Forms/inMtoEmpresas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoEmpresas.TfrmMtoEmpresas.tsBancos.Caption',
   'es-ES',
   '&7_Bancos',
   'src/Forms/inMtoEmpresas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoEmpresas.TfrmMtoEmpresas.btnAddBanco.Caption',
   'es-ES',
   'Añadir Banco',
   'src/Forms/inMtoEmpresas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoEmpresas.TfrmMtoEmpresas.tvBancosNOMBRE_EMPBAN.Caption',
   'es-ES',
   'Nombre cuenta',
   'src/Forms/inMtoEmpresas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoEmpresas.TfrmMtoEmpresas.tvBancosIBAN_EMPBAN.Caption',
   'es-ES',
   'IBAN',
   'src/Forms/inMtoEmpresas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoEmpresas.TfrmMtoEmpresas.tvBancosNOMBRE_BAN.Caption',
   'es-ES',
   'Banco',
   'src/Forms/inMtoEmpresas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoEmpresas.TfrmMtoEmpresas.tvBancosESDEFECTO_COBRO_EMPBAN.Caption',
   'es-ES',
   'Def. Cobro',
   'src/Forms/inMtoEmpresas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoEmpresas.TfrmMtoEmpresas.tvBancosESDEFECTO_PAGO_EMPBAN.Caption',
   'es-ES',
   'Def. Pago',
   'src/Forms/inMtoEmpresas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoEmpresas.TfrmMtoEmpresas.tvBancosESACTIVO_EMPBAN.Caption',
   'es-ES',
   'Activo',
   'src/Forms/inMtoEmpresas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoEmpresas.TfrmMtoEmpresas.tsPieTicketCaja.Caption',
   'es-ES',
   '&5_Pie Ticket Caja',
   'src/Forms/inMtoEmpresas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoEmpresas.TfrmMtoEmpresas.lblPieTicketCaja1.Caption',
   'es-ES',
   'Línea 1',
   'src/Forms/inMtoEmpresas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoEmpresas.TfrmMtoEmpresas.lblPieTicketCaja2.Caption',
   'es-ES',
   'Línea 2',
   'src/Forms/inMtoEmpresas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoEmpresas.TfrmMtoEmpresas.lblPieTicketCaja3.Caption',
   'es-ES',
   'Línea 3',
   'src/Forms/inMtoEmpresas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoEmpresas.TfrmMtoEmpresas.lblPieTicketCaja4.Caption',
   'es-ES',
   'Línea 4',
   'src/Forms/inMtoEmpresas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoEmpresas.TfrmMtoEmpresas.tsOtros.Caption',
   'es-ES',
   '&6_Otros',
   'src/Forms/inMtoEmpresas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoEmpresas.TfrmMtoEmpresas.lblUsuarioAlta.Caption',
   'es-ES',
   'Usuario Alta',
   'src/Forms/inMtoEmpresas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoEmpresas.TfrmMtoEmpresas.lblInstanteAlta.Caption',
   'es-ES',
   'Instante Alta',
   'src/Forms/inMtoEmpresas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoEmpresas.TfrmMtoEmpresas.lblInstanteModif.Caption',
   'es-ES',
   'Instante Modificación',
   'src/Forms/inMtoEmpresas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoEmpresas.TfrmMtoEmpresas.lblUsuarioModif.Caption',
   'es-ES',
   'Usuario Última Modificación',
   'src/Forms/inMtoEmpresas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoEmpresas.TfrmMtoEmpresas.lblTextoLegal.Caption',
   'es-ES',
   'Texto legal en Borradores',
   'src/Forms/inMtoEmpresas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoEmpresas.TfrmMtoEmpresas.lblOrden.Caption',
   'es-ES',
   'Orden en Listados',
   'src/Forms/inMtoEmpresas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoEmpresas.TfrmMtoEmpresas.lblTextoLegal1.Caption',
   'es-ES',
   'Firma electrónica en Borradores',
   'src/Forms/inMtoEmpresas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoEmpresas.TfrmMtoEmpresas.lblNumSerie.Caption',
   'es-ES',
   'Número de Serie',
   'src/Forms/inMtoEmpresas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoEmpresas.TfrmMtoEmpresas.lblTipoCertificado.Caption',
   'es-ES',
   'Tipo de Certificado',
   'src/Forms/inMtoEmpresas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoEmpresas.TfrmMtoEmpresas.lblTitular.Caption',
   'es-ES',
   'Titular',
   'src/Forms/inMtoEmpresas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoEmpresas.TfrmMtoEmpresas.btnSeleccionarCer.Caption',
   'es-ES',
   '&Seleccionar certificado de Almacén',
   'src/Forms/inMtoEmpresas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoEmpresas.TfrmMtoEmpresas.lblFechaCaducidad.Caption',
   'es-ES',
   'FechaCaducidad',
   'src/Forms/inMtoEmpresas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoEmpresas.TfrmMtoEmpresas.lblFormatoDocumento.Caption',
   'es-ES',
   'Formato documentos',
   'src/Forms/inMtoEmpresas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoEmpresas.TfrmMtoEmpresas.lblFormatoDocumentoAyuda.Caption',
   'es-ES',
   CONCAT(
     'Tokens: Serie y NroDocumento. Ej.: Serie.NroDocumento o ',
     'NroDocumento.Serie'
   ),
   'src/Forms/inMtoEmpresas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoEmpresas.TfrmMtoEmpresas.cxTabSheet1.Caption',
   'es-ES',
   '&7_Verifactu',
   'src/Forms/inMtoEmpresas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoEmpresas.TfrmMtoEmpresas.lblNumeroInstalacionSif.Caption',
   'es-ES',
   'Nº instalación SIF',
   'src/Forms/inMtoEmpresas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoEmpresas.TfrmMtoEmpresas.lblVersionInstalacionSif.Caption',
   'es-ES',
   'Versión SIF',
   'src/Forms/inMtoEmpresas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoEmpresas.TfrmMtoEmpresas.btnGenerarInstalacionSif.Caption',
   'es-ES',
   'Generar / actualizar número SIF',
   'src/Forms/inMtoEmpresas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoEmpresas.TfrmMtoEmpresas.lblCodigo.Caption',
   'es-ES',
   'Código',
   'src/Forms/inMtoEmpresas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoEmpresas.TfrmMtoEmpresas.lblNif.Caption',
   'es-ES',
   'Nif',
   'src/Forms/inMtoEmpresas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoEmpresas.TfrmMtoEmpresas.lblNombre.Caption',
   'es-ES',
   'Razón Social',
   'src/Forms/inMtoEmpresas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoEmpresas.TfrmMtoEmpresas.chkActivo.Caption',
   'es-ES',
   'Activo',
   'src/Forms/inMtoEmpresas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoEmpresas.TfrmMtoEmpresas.chkAplicaRetenciones.Caption',
   'es-ES',
   'Retiene IRPF',
   'src/Forms/inMtoEmpresas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoEmpresas.TfrmMtoEmpresas.lblCanalIVA.Caption',
   'es-ES',
   'Canal de IVA',
   'src/Forms/inMtoEmpresas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoEmpresas.TfrmMtoEmpresas.btnNuevaEmpresa.Caption',
   'es-ES',
   '&Nueva Empresa',
   'src/Forms/inMtoEmpresas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoEmpresas.TfrmMtoEmpresas.actClientes.Caption',
   'es-ES',
   'Clientes',
   'src/Forms/inMtoEmpresas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoEmpresas.TfrmMtoEmpresas.actArticulos.Caption',
   'es-ES',
   'actArticulos',
   'src/Forms/inMtoEmpresas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoEmpresas.TfrmMtoEmpresas.actFacturas.Caption',
   'es-ES',
   'actBorradores',
   'src/Forms/inMtoEmpresas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema')
ON DUPLICATE KEY UPDATE
  `TEXTO_TRAD` = VALUES(`TEXTO_TRAD`),
  `CONTEXTO_TRAD` = VALUES(`CONTEXTO_TRAD`),
  `ESACTIVO_TRAD` = VALUES(`ESACTIVO_TRAD`),
  `INSTANTE_MODIF` = CURRENT_TIMESTAMP,
  `USUARIO_MODIF` = VALUES(`USUARIO_ALTA`);
