-- Catálogo de textos españoles extraídos de los DFM.
-- Generado por generar_traducciones_dfm.ps1.
INSERT INTO `fza_traducciones` (
  `CLAVE_TRAD`, `IDIOMA_TRAD`, `TEXTO_TRAD`, `CONTEXTO_TRAD`,
  `ESACTIVO_TRAD`, `INSTANTE_ALTA`, `USUARIO_ALTA`
) VALUES
  ('inMtoAlbaranes.TfrmMtoAlbaranes.Caption',
   'es-ES',
   'Mantenimiento de Albaranes',
   'src/Forms/inMtoAlbaranes.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlbaranes.TfrmMtoAlbaranes.dbcGrdAlbNUMERO_ALB.Caption',
   'es-ES',
   'Número',
   'src/Forms/inMtoAlbaranes.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlbaranes.TfrmMtoAlbaranes.dbcGrdAlbSERIE_ALB.Caption',
   'es-ES',
   'Serie',
   'src/Forms/inMtoAlbaranes.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlbaranes.TfrmMtoAlbaranes.dbcGrdAlbFECHA_ALB.Caption',
   'es-ES',
   'Fecha',
   'src/Forms/inMtoAlbaranes.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlbaranes.TfrmMtoAlbaranes.dbcGrdAlbESTADO_ALB.Caption',
   'es-ES',
   'Estado',
   'src/Forms/inMtoAlbaranes.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlbaranes.TfrmMtoAlbaranes.dbcGrdAlbCODIGO_EMP_ALB.Caption',
   'es-ES',
   'Empresa',
   'src/Forms/inMtoAlbaranes.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlbaranes.TfrmMtoAlbaranes.dbcGrdAlbRSEMP_ALB.Caption',
   'es-ES',
   'Razón Social Empresa',
   'src/Forms/inMtoAlbaranes.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlbaranes.TfrmMtoAlbaranes.dbcGrdAlbNOMBRE_ALM_ALB.Caption',
   'es-ES',
   'Almacén',
   'src/Forms/inMtoAlbaranes.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlbaranes.TfrmMtoAlbaranes.dbcGrdAlbCODIGO_CLI_ALB.Caption',
   'es-ES',
   'Cliente',
   'src/Forms/inMtoAlbaranes.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlbaranes.TfrmMtoAlbaranes.dbcGrdAlbRSCLI_ALB.Caption',
   'es-ES',
   'Razón Social Cliente',
   'src/Forms/inMtoAlbaranes.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlbaranes.TfrmMtoAlbaranes.dbcGrdAlbNUMERO_PED_ALB.Caption',
   'es-ES',
   'Pedido',
   'src/Forms/inMtoAlbaranes.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlbaranes.TfrmMtoAlbaranes.dbcGrdAlbSERIE_PED_ALB.Caption',
   'es-ES',
   'Serie Pedido',
   'src/Forms/inMtoAlbaranes.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlbaranes.TfrmMtoAlbaranes.dbcGrdAlbNUMERO_FAC_ALB.Caption',
   'es-ES',
   'Borrador',
   'src/Forms/inMtoAlbaranes.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlbaranes.TfrmMtoAlbaranes.dbcGrdAlbSERIE_FAC_ALB.Caption',
   'es-ES',
   'Serie Borrador',
   'src/Forms/inMtoAlbaranes.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlbaranes.TfrmMtoAlbaranes.dbcGrdAlbTOTAL_LIQUIDO_ALB.Caption',
   'es-ES',
   'Total',
   'src/Forms/inMtoAlbaranes.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlbaranes.TfrmMtoAlbaranes.tsCabecera.Caption',
   'es-ES',
   'Cabecera',
   'src/Forms/inMtoAlbaranes.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlbaranes.TfrmMtoAlbaranes.lblNroAlbaran.Caption',
   'es-ES',
   'Número',
   'src/Forms/inMtoAlbaranes.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlbaranes.TfrmMtoAlbaranes.lblSerieAlbaran.Caption',
   'es-ES',
   'Serie',
   'src/Forms/inMtoAlbaranes.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlbaranes.TfrmMtoAlbaranes.lblFechaAlbaran.Caption',
   'es-ES',
   'Fecha',
   'src/Forms/inMtoAlbaranes.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlbaranes.TfrmMtoAlbaranes.lblEstadoAlbaran.Caption',
   'es-ES',
   'Estado',
   'src/Forms/inMtoAlbaranes.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlbaranes.TfrmMtoAlbaranes.lblPedidoOrigen.Caption',
   'es-ES',
   'Pedido origen (Número / Serie)',
   'src/Forms/inMtoAlbaranes.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlbaranes.TfrmMtoAlbaranes.lblFacturaDestino.Caption',
   'es-ES',
   'Borrador (Número / Serie)',
   'src/Forms/inMtoAlbaranes.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlbaranes.TfrmMtoAlbaranes.lblCodigoEmpresa.Caption',
   'es-ES',
   'Empresa Emisora',
   'src/Forms/inMtoAlbaranes.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlbaranes.TfrmMtoAlbaranes.lblCodigoAlmacen.Caption',
   'es-ES',
   'Almacén salida',
   'src/Forms/inMtoAlbaranes.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoAlbaranes.TfrmMtoAlbaranes.cbbCODIGO_ALM_ALB.Properties.ListColum',
     'ns[0].Caption'
   ),
   'es-ES',
   'Código',
   'src/Forms/inMtoAlbaranes.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoAlbaranes.TfrmMtoAlbaranes.cbbCODIGO_ALM_ALB.Properties.ListColum',
     'ns[1].Caption'
   ),
   'es-ES',
   'Almacén',
   'src/Forms/inMtoAlbaranes.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoAlbaranes.TfrmMtoAlbaranes.cbbCODIGO_ALM_ALB.Properties.ListColum',
     'ns[2].Caption'
   ),
   'es-ES',
   'Empresa',
   'src/Forms/inMtoAlbaranes.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlbaranes.TfrmMtoAlbaranes.lblCodigoCliente.Caption',
   'es-ES',
   'Cliente',
   'src/Forms/inMtoAlbaranes.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlbaranes.TfrmMtoAlbaranes.lblTarifaAlbaran.Caption',
   'es-ES',
   'Tarifa',
   'src/Forms/inMtoAlbaranes.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoAlbaranes.TfrmMtoAlbaranes.cbbTarifaAlbaran.Properties.ListColumn',
     's[0].Caption'
   ),
   'es-ES',
   'Tarifa',
   'src/Forms/inMtoAlbaranes.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoAlbaranes.TfrmMtoAlbaranes.cbbTarifaAlbaran.Properties.ListColumn',
     's[1].Caption'
   ),
   'es-ES',
   'Imp. incl.',
   'src/Forms/inMtoAlbaranes.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlbaranes.TfrmMtoAlbaranes.chkTarifaImpuestosIncluidosAlbaran.Caption',
   'es-ES',
   'Imp. incl.',
   'src/Forms/inMtoAlbaranes.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlbaranes.TfrmMtoAlbaranes.tsEmpresa.Caption',
   'es-ES',
   'Empresa',
   'src/Forms/inMtoAlbaranes.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlbaranes.TfrmMtoAlbaranes.grpEmpresa.Caption',
   'es-ES',
   'Datos Empresa Emisora',
   'src/Forms/inMtoAlbaranes.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlbaranes.TfrmMtoAlbaranes.lblNIFEmp.Caption',
   'es-ES',
   'NIF',
   'src/Forms/inMtoAlbaranes.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlbaranes.TfrmMtoAlbaranes.lblMovEmp.Caption',
   'es-ES',
   'Móvil',
   'src/Forms/inMtoAlbaranes.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlbaranes.TfrmMtoAlbaranes.lblEmailEmp.Caption',
   'es-ES',
   'Email',
   'src/Forms/inMtoAlbaranes.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlbaranes.TfrmMtoAlbaranes.tsDatosCliente.Caption',
   'es-ES',
   'Cliente Fiscal',
   'src/Forms/inMtoAlbaranes.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlbaranes.TfrmMtoAlbaranes.grpClienteFiscal.Caption',
   'es-ES',
   'Datos Cliente Fiscal',
   'src/Forms/inMtoAlbaranes.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlbaranes.TfrmMtoAlbaranes.tsEnvio.Caption',
   'es-ES',
   'Dirección Envío',
   'src/Forms/inMtoAlbaranes.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlbaranes.TfrmMtoAlbaranes.grpClienteEnvio.Caption',
   'es-ES',
   'Datos Cliente Envío',
   'src/Forms/inMtoAlbaranes.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlbaranes.TfrmMtoAlbaranes.btnAnadirLinea.Caption',
   'es-ES',
   'Añadir línea',
   'src/Forms/inMtoAlbaranes.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlbaranes.TfrmMtoAlbaranes.btnBorrarLinea.Caption',
   'es-ES',
   'Borrar línea',
   'src/Forms/inMtoAlbaranes.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlbaranes.TfrmMtoAlbaranes.btnFacturarSeleccionadas.Caption',
   'es-ES',
   'Crear borr. líneas selec.',
   'src/Forms/inMtoAlbaranes.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlbaranes.TfrmMtoAlbaranes.btnFacturarTodo.Caption',
   'es-ES',
   'Crear borr albarán',
   'src/Forms/inMtoAlbaranes.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlbaranes.TfrmMtoAlbaranes.btnFacturarPorFechas.Caption',
   'es-ES',
   'Crear borr por fechas / serie',
   'src/Forms/inMtoAlbaranes.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlbaranes.TfrmMtoAlbaranes.tsLineasAlbaran.Caption',
   'es-ES',
   '&1_Líneas Albarán',
   'src/Forms/inMtoAlbaranes.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlbaranes.TfrmMtoAlbaranes.cxgrdcLineaAlb.Caption',
   'es-ES',
   'Línea',
   'src/Forms/inMtoAlbaranes.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlbaranes.TfrmMtoAlbaranes.cxgrdcArtAlb.Caption',
   'es-ES',
   'Código Artículo',
   'src/Forms/inMtoAlbaranes.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlbaranes.TfrmMtoAlbaranes.cxgrdcSkuAlb.Caption',
   'es-ES',
   'SKU',
   'src/Forms/inMtoAlbaranes.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlbaranes.TfrmMtoAlbaranes.cxgrdcVarAlb.Caption',
   'es-ES',
   'Variación',
   'src/Forms/inMtoAlbaranes.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlbaranes.TfrmMtoAlbaranes.cxgrdcDescrAlb.Caption',
   'es-ES',
   'Descripción',
   'src/Forms/inMtoAlbaranes.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlbaranes.TfrmMtoAlbaranes.cxgrdcLoteAlb.Caption',
   'es-ES',
   'Lote',
   'src/Forms/inMtoAlbaranes.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlbaranes.TfrmMtoAlbaranes.cxgrdcCadAlb.Caption',
   'es-ES',
   'Caducidad',
   'src/Forms/inMtoAlbaranes.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlbaranes.TfrmMtoAlbaranes.cxgrdcCantAlb.Caption',
   'es-ES',
   'Cantidad',
   'src/Forms/inMtoAlbaranes.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlbaranes.TfrmMtoAlbaranes.cxgrdcPSivaAlb.Caption',
   'es-ES',
   'PVP S/IVA',
   'src/Forms/inMtoAlbaranes.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlbaranes.TfrmMtoAlbaranes.cxgrdcPCivaAlb.Caption',
   'es-ES',
   'PVP C/IVA',
   'src/Forms/inMtoAlbaranes.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlbaranes.TfrmMtoAlbaranes.cxgrdcTotalAlb.Caption',
   'es-ES',
   'Total',
   'src/Forms/inMtoAlbaranes.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlbaranes.TfrmMtoAlbaranes.cxgrdcEsFactAlb.Caption',
   'es-ES',
   'Con borrador?',
   'src/Forms/inMtoAlbaranes.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlbaranes.TfrmMtoAlbaranes.cxgrdcNumFacAlb.Caption',
   'es-ES',
   'Borrador',
   'src/Forms/inMtoAlbaranes.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlbaranes.TfrmMtoAlbaranes.cxgrdcSerFacAlb.Caption',
   'es-ES',
   'Serie Fac.',
   'src/Forms/inMtoAlbaranes.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlbaranes.TfrmMtoAlbaranes.cxgrdcPedAlb.Caption',
   'es-ES',
   'Línea Pedido',
   'src/Forms/inMtoAlbaranes.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlbaranes.TfrmMtoAlbaranes.tsTotales.Caption',
   'es-ES',
   '&2_Totales',
   'src/Forms/inMtoAlbaranes.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlbaranes.TfrmMtoAlbaranes.lblTotalesTotalBase.Caption',
   'es-ES',
   'Total Base Imponible',
   'src/Forms/inMtoAlbaranes.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlbaranes.TfrmMtoAlbaranes.lblTotalesTotalImpuestos.Caption',
   'es-ES',
   'Total Impuestos',
   'src/Forms/inMtoAlbaranes.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlbaranes.TfrmMtoAlbaranes.lblTotalesTotalPagar.Caption',
   'es-ES',
   'Total a pagar',
   'src/Forms/inMtoAlbaranes.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlbaranes.TfrmMtoAlbaranes.lblTotalesFormaPago.Caption',
   'es-ES',
   'Forma de Pago',
   'src/Forms/inMtoAlbaranes.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoAlbaranes.TfrmMtoAlbaranes.cbbTotalesFORMA_PAGO_ALB.Properties.Li',
     'stColumns[0].Caption'
   ),
   'es-ES',
   'Código',
   'src/Forms/inMtoAlbaranes.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoAlbaranes.TfrmMtoAlbaranes.cbbTotalesFORMA_PAGO_ALB.Properties.Li',
     'stColumns[1].Caption'
   ),
   'es-ES',
   'Descripción',
   'src/Forms/inMtoAlbaranes.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoAlbaranes.TfrmMtoAlbaranes.chkTotalesESIVA_RECARGO_CLIENTE_ALB.Ca',
     'ption'
   ),
   'es-ES',
   'Recargo equivalencia cliente',
   'src/Forms/inMtoAlbaranes.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlbaranes.TfrmMtoAlbaranes.lblTotalesTotalPrendas.Caption',
   'es-ES',
   'Nº de prendas',
   'src/Forms/inMtoAlbaranes.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlbaranes.TfrmMtoAlbaranes.lblTotalPrendasAlb.Caption',
   'es-ES',
   '0',
   'src/Forms/inMtoAlbaranes.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlbaranes.TfrmMtoAlbaranes.grpDesgloseImpuestos.Caption',
   'es-ES',
   'Desglose IVA',
   'src/Forms/inMtoAlbaranes.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlbaranes.TfrmMtoAlbaranes.lblTotalesTotalIva.Caption',
   'es-ES',
   'Total IVA',
   'src/Forms/inMtoAlbaranes.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlbaranes.TfrmMtoAlbaranes.lblTotalesPorIva.Caption',
   'es-ES',
   '%IVA',
   'src/Forms/inMtoAlbaranes.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlbaranes.TfrmMtoAlbaranes.lblTotalesIVAN.Caption',
   'es-ES',
   'Normal',
   'src/Forms/inMtoAlbaranes.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlbaranes.TfrmMtoAlbaranes.lblTotalesIVAR.Caption',
   'es-ES',
   'Reducido',
   'src/Forms/inMtoAlbaranes.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlbaranes.TfrmMtoAlbaranes.lblTotalesIVAS.Caption',
   'es-ES',
   'Súper Reducido',
   'src/Forms/inMtoAlbaranes.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlbaranes.TfrmMtoAlbaranes.lblTotalesIVAE.Caption',
   'es-ES',
   'Exento',
   'src/Forms/inMtoAlbaranes.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlbaranes.TfrmMtoAlbaranes.tsFacturas.Caption',
   'es-ES',
   '&3_Borradores',
   'src/Forms/inMtoAlbaranes.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlbaranes.TfrmMtoAlbaranes.cxgrdcFacNum.Caption',
   'es-ES',
   'Número',
   'src/Forms/inMtoAlbaranes.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlbaranes.TfrmMtoAlbaranes.cxgrdcFacSer.Caption',
   'es-ES',
   'Serie',
   'src/Forms/inMtoAlbaranes.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlbaranes.TfrmMtoAlbaranes.cxgrdcFacFec.Caption',
   'es-ES',
   'Fecha',
   'src/Forms/inMtoAlbaranes.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlbaranes.TfrmMtoAlbaranes.cxgrdcFacFase.Caption',
   'es-ES',
   'Fase',
   'src/Forms/inMtoAlbaranes.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlbaranes.TfrmMtoAlbaranes.cxgrdcFacTot.Caption',
   'es-ES',
   'Total',
   'src/Forms/inMtoAlbaranes.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlbaranes.TfrmMtoAlbaranes.tsMovimientos.Caption',
   'es-ES',
   '&4_Movimientos',
   'src/Forms/inMtoAlbaranes.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlbaranes.TfrmMtoAlbaranes.cxgrdcMovNum.Caption',
   'es-ES',
   'Número Mov.',
   'src/Forms/inMtoAlbaranes.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlbaranes.TfrmMtoAlbaranes.cxgrdcMovFec.Caption',
   'es-ES',
   'Fecha',
   'src/Forms/inMtoAlbaranes.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlbaranes.TfrmMtoAlbaranes.cxgrdcMovLin.Caption',
   'es-ES',
   'Línea',
   'src/Forms/inMtoAlbaranes.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlbaranes.TfrmMtoAlbaranes.cxgrdcMovAlm.Caption',
   'es-ES',
   'Almacén',
   'src/Forms/inMtoAlbaranes.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlbaranes.TfrmMtoAlbaranes.cxgrdcMovArt.Caption',
   'es-ES',
   'Artículo',
   'src/Forms/inMtoAlbaranes.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlbaranes.TfrmMtoAlbaranes.cxgrdcMovSku.Caption',
   'es-ES',
   'SKU',
   'src/Forms/inMtoAlbaranes.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlbaranes.TfrmMtoAlbaranes.cxgrdcMovDescr.Caption',
   'es-ES',
   'Descripción',
   'src/Forms/inMtoAlbaranes.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlbaranes.TfrmMtoAlbaranes.cxgrdcMovTipo.Caption',
   'es-ES',
   'Tipo',
   'src/Forms/inMtoAlbaranes.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlbaranes.TfrmMtoAlbaranes.cxgrdcMovCant.Caption',
   'es-ES',
   'Cantidad',
   'src/Forms/inMtoAlbaranes.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlbaranes.TfrmMtoAlbaranes.cxgrdcMovPMP.Caption',
   'es-ES',
   'PMP',
   'src/Forms/inMtoAlbaranes.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlbaranes.TfrmMtoAlbaranes.cxgrdcMovTot.Caption',
   'es-ES',
   'Total Coste',
   'src/Forms/inMtoAlbaranes.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlbaranes.TfrmMtoAlbaranes.tsObservaciones.Caption',
   'es-ES',
   '&5_Observaciones',
   'src/Forms/inMtoAlbaranes.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlbaranes.TfrmMtoAlbaranes.lblTotalBases.Caption',
   'es-ES',
   'Bases',
   'src/Forms/inMtoAlbaranes.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlbaranes.TfrmMtoAlbaranes.lblTotalImpuestos.Caption',
   'es-ES',
   'IVA',
   'src/Forms/inMtoAlbaranes.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlbaranes.TfrmMtoAlbaranes.lblTotalLiquido.Caption',
   'es-ES',
   'TOTAL',
   'src/Forms/inMtoAlbaranes.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlbaranes.TfrmMtoAlbaranes.btnImprimir.Caption',
   'es-ES',
   'Imprimir',
   'src/Forms/inMtoAlbaranes.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlbaranes.TfrmMtoAlbaranes.actIrDocumento.Caption',
   'es-ES',
   'Ir a documento (Ctrl+May+A)',
   'src/Forms/inMtoAlbaranes.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlbaranes.TfrmMtoAlbaranes.actIrFacturaCreada.Caption',
   'es-ES',
   'Ir a borrador',
   'src/Forms/inMtoAlbaranes.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlbaranesCompra.TfrmMtoAlbaranesCompra.Caption',
   'es-ES',
   'Mantenimiento de Albaranes de Compra',
   'src/Forms/inMtoAlbaranesCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoAlbaranesCompra.TfrmMtoAlbaranesCompra.dbcGrdAlbcCODIGO_EMP_ALBC.',
     'Caption'
   ),
   'es-ES',
   'Empresa',
   'src/Forms/inMtoAlbaranesCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlbaranesCompra.TfrmMtoAlbaranesCompra.dbcGrdAlbcSERIE_ALBC.Caption',
   'es-ES',
   'Serie',
   'src/Forms/inMtoAlbaranesCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlbaranesCompra.TfrmMtoAlbaranesCompra.dbcGrdAlbcNUMERO_ALBC.Caption',
   'es-ES',
   'Número',
   'src/Forms/inMtoAlbaranesCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlbaranesCompra.TfrmMtoAlbaranesCompra.dbcGrdAlbcFECHA_ALBC.Caption',
   'es-ES',
   'Fecha',
   'src/Forms/inMtoAlbaranesCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoAlbaranesCompra.TfrmMtoAlbaranesCompra.dbcGrdAlbcCODIGO_ALM_ALBC.',
     'Caption'
   ),
   'es-ES',
   'Almacén',
   'src/Forms/inMtoAlbaranesCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoAlbaranesCompra.TfrmMtoAlbaranesCompra.dbcGrdAlbcTEMPORADA_ALBC.C',
     'aption'
   ),
   'es-ES',
   'Temporada',
   'src/Forms/inMtoAlbaranesCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoAlbaranesCompra.TfrmMtoAlbaranesCompra.dbcGrdAlbcREF_PROVEEDOR_AL',
     'BC.Caption'
   ),
   'es-ES',
   'Ref. proveedor',
   'src/Forms/inMtoAlbaranesCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoAlbaranesCompra.TfrmMtoAlbaranesCompra.dbcGrdAlbcCODIGO_PRV_ALBC.',
     'Caption'
   ),
   'es-ES',
   'Proveedor',
   'src/Forms/inMtoAlbaranesCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlbaranesCompra.TfrmMtoAlbaranesCompra.dbcGrdAlbcRSPRV_ALBC.Caption',
   'es-ES',
   'Razón Social Proveedor',
   'src/Forms/inMtoAlbaranesCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoAlbaranesCompra.TfrmMtoAlbaranesCompra.dbcGrdAlbcTOTAL_PRENDAS_AL',
     'BC.Caption'
   ),
   'es-ES',
   'Prendas',
   'src/Forms/inMtoAlbaranesCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoAlbaranesCompra.TfrmMtoAlbaranesCompra.dbcGrdAlbcTOTAL_LINEAS_ALB',
     'C.Caption'
   ),
   'es-ES',
   'Neto lineas',
   'src/Forms/inMtoAlbaranesCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoAlbaranesCompra.TfrmMtoAlbaranesCompra.dbcGrdAlbcTOTAL_LIQUIDO_AL',
     'BC.Caption'
   ),
   'es-ES',
   'Total líquido',
   'src/Forms/inMtoAlbaranesCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoAlbaranesCompra.TfrmMtoAlbaranesCompra.dbcGrdAlbcNUMERO_PED_ALBC.',
     'Caption'
   ),
   'es-ES',
   'Pedido origen',
   'src/Forms/inMtoAlbaranesCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoAlbaranesCompra.TfrmMtoAlbaranesCompra.dbcGrdAlbcSERIE_PED_ALBC.C',
     'aption'
   ),
   'es-ES',
   'Serie pedido',
   'src/Forms/inMtoAlbaranesCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoAlbaranesCompra.TfrmMtoAlbaranesCompra.dbcGrdAlbcNUMERO_FAC_ALBC.',
     'Caption'
   ),
   'es-ES',
   'Factura creada',
   'src/Forms/inMtoAlbaranesCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoAlbaranesCompra.TfrmMtoAlbaranesCompra.dbcGrdAlbcSERIE_FAC_ALBC.C',
     'aption'
   ),
   'es-ES',
   'Serie factura',
   'src/Forms/inMtoAlbaranesCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoAlbaranesCompra.TfrmMtoAlbaranesCompra.dbcGrdAlbcESDEPOSITO_ALBC.',
     'Caption'
   ),
   'es-ES',
   'Depósito',
   'src/Forms/inMtoAlbaranesCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlbaranesCompra.TfrmMtoAlbaranesCompra.tsCabecera.Caption',
   'es-ES',
   'Cabecera',
   'src/Forms/inMtoAlbaranesCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlbaranesCompra.TfrmMtoAlbaranesCompra.lblNroAlbaran.Caption',
   'es-ES',
   'Número',
   'src/Forms/inMtoAlbaranesCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlbaranesCompra.TfrmMtoAlbaranesCompra.lblSerieAlbaran.Caption',
   'es-ES',
   'Serie',
   'src/Forms/inMtoAlbaranesCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlbaranesCompra.TfrmMtoAlbaranesCompra.lblFechaAlbaran.Caption',
   'es-ES',
   'Fecha',
   'src/Forms/inMtoAlbaranesCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlbaranesCompra.TfrmMtoAlbaranesCompra.lblTemporadaAlbaran.Caption',
   'es-ES',
   'Temporada',
   'src/Forms/inMtoAlbaranesCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoAlbaranesCompra.TfrmMtoAlbaranesCompra.cbbTemporadaAlbc.Propertie',
     's.ListColumns[0].Caption'
   ),
   'es-ES',
   'Temporada',
   'src/Forms/inMtoAlbaranesCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlbaranesCompra.TfrmMtoAlbaranesCompra.lblPedidoOrigen.Caption',
   'es-ES',
   'Pedido origen (Número / Serie)',
   'src/Forms/inMtoAlbaranesCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlbaranesCompra.TfrmMtoAlbaranesCompra.btnIrDocumento.Caption',
   'es-ES',
   'Ir a pedido origen',
   'src/Forms/inMtoAlbaranesCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlbaranesCompra.TfrmMtoAlbaranesCompra.lblFacturaDestino.Caption',
   'es-ES',
   'Factura creada (Número / Serie)',
   'src/Forms/inMtoAlbaranesCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlbaranesCompra.TfrmMtoAlbaranesCompra.lblCodigoEmpresa.Caption',
   'es-ES',
   'Empresa',
   'src/Forms/inMtoAlbaranesCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlbaranesCompra.TfrmMtoAlbaranesCompra.lblCodigoProveedor.Caption',
   'es-ES',
   'Proveedor',
   'src/Forms/inMtoAlbaranesCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoAlbaranesCompra.TfrmMtoAlbaranesCompra.cbbCODIGO_PRV_ALBC.Propert',
     'ies.ListColumns[0].Caption'
   ),
   'es-ES',
   'Código',
   'src/Forms/inMtoAlbaranesCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoAlbaranesCompra.TfrmMtoAlbaranesCompra.cbbCODIGO_PRV_ALBC.Propert',
     'ies.ListColumns[1].Caption'
   ),
   'es-ES',
   'Proveedor',
   'src/Forms/inMtoAlbaranesCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlbaranesCompra.TfrmMtoAlbaranesCompra.lblRefProveedor.Caption',
   'es-ES',
   'Ref. proveedor',
   'src/Forms/inMtoAlbaranesCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlbaranesCompra.TfrmMtoAlbaranesCompra.lblCodigoAlmacen.Caption',
   'es-ES',
   'Almacén destino',
   'src/Forms/inMtoAlbaranesCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoAlbaranesCompra.TfrmMtoAlbaranesCompra.cbbCODIGO_ALM_ALBC.Propert',
     'ies.ListColumns[0].Caption'
   ),
   'es-ES',
   'Código',
   'src/Forms/inMtoAlbaranesCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoAlbaranesCompra.TfrmMtoAlbaranesCompra.cbbCODIGO_ALM_ALBC.Propert',
     'ies.ListColumns[1].Caption'
   ),
   'es-ES',
   'Almacén',
   'src/Forms/inMtoAlbaranesCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoAlbaranesCompra.TfrmMtoAlbaranesCompra.cbbCODIGO_ALM_ALBC.Propert',
     'ies.ListColumns[2].Caption'
   ),
   'es-ES',
   'Empresa',
   'src/Forms/inMtoAlbaranesCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlbaranesCompra.TfrmMtoAlbaranesCompra.chkESDEPOSITO_ALBC.Caption',
   'es-ES',
   'Depósito',
   'src/Forms/inMtoAlbaranesCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlbaranesCompra.TfrmMtoAlbaranesCompra.lblTotalesTotalPrendas.Caption',
   'es-ES',
   'Nº de prendas',
   'src/Forms/inMtoAlbaranesCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlbaranesCompra.TfrmMtoAlbaranesCompra.btnAnadirLinea.Caption',
   'es-ES',
   'Añadir línea',
   'src/Forms/inMtoAlbaranesCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlbaranesCompra.TfrmMtoAlbaranesCompra.btnBorrarLinea.Caption',
   'es-ES',
   'Borrar línea',
   'src/Forms/inMtoAlbaranesCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlbaranesCompra.TfrmMtoAlbaranesCompra.btnTallasHorizontal.Caption',
   'es-ES',
   'Tallas en horizontal',
   'src/Forms/inMtoAlbaranesCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlbaranesCompra.TfrmMtoAlbaranesCompra.btnAtributosColumna.Caption',
   'es-ES',
   'Atributo por columna',
   'src/Forms/inMtoAlbaranesCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlbaranesCompra.TfrmMtoAlbaranesCompra.tsLineasAlbaran.Caption',
   'es-ES',
   '&1_Líneas ',
   'src/Forms/inMtoAlbaranesCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlbaranesCompra.TfrmMtoAlbaranesCompra.colLineaAlbcLINEA.Caption',
   'es-ES',
   'Línea',
   'src/Forms/inMtoAlbaranesCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlbaranesCompra.TfrmMtoAlbaranesCompra.colLineaAlbcCODIGO_ART.Caption',
   'es-ES',
   'Artículo',
   'src/Forms/inMtoAlbaranesCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoAlbaranesCompra.TfrmMtoAlbaranesCompra.colLineaAlbcCODIGO_UNIDAD.',
     'Caption'
   ),
   'es-ES',
   'SKU',
   'src/Forms/inMtoAlbaranesCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlbaranesCompra.TfrmMtoAlbaranesCompra.colLineaAlbcREF_PRV.Caption',
   'es-ES',
   'Modelo prov.',
   'src/Forms/inMtoAlbaranesCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoAlbaranesCompra.TfrmMtoAlbaranesCompra.colLineaAlbcDESCRIPCION.Ca',
     'ption'
   ),
   'es-ES',
   'Descripción',
   'src/Forms/inMtoAlbaranesCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlbaranesCompra.TfrmMtoAlbaranesCompra.colLineaAlbcCANTIDAD.Caption',
   'es-ES',
   'Cantidad',
   'src/Forms/inMtoAlbaranesCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoAlbaranesCompra.TfrmMtoAlbaranesCompra.colLineaAlbcPRECIO_COMPRA.',
     'Caption'
   ),
   'es-ES',
   'Precio compra',
   'src/Forms/inMtoAlbaranesCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoAlbaranesCompra.TfrmMtoAlbaranesCompra.colLineaAlbcPORCENTAJE_IVA',
     '.Caption'
   ),
   'es-ES',
   '% IVA',
   'src/Forms/inMtoAlbaranesCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlbaranesCompra.TfrmMtoAlbaranesCompra.colLineaAlbcTOTAL.Caption',
   'es-ES',
   'Total',
   'src/Forms/inMtoAlbaranesCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlbaranesCompra.TfrmMtoAlbaranesCompra.colLineaAlbcALMACEN.Caption',
   'es-ES',
   'Almacén',
   'src/Forms/inMtoAlbaranesCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlbaranesCompra.TfrmMtoAlbaranesCompra.tsProveedor.Caption',
   'es-ES',
   '&2_Movimientos ',
   'src/Forms/inMtoAlbaranesCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoAlbaranesCompra.TfrmMtoAlbaranesCompra.colMovProvAlbcNUMERO_MOV.C',
     'aption'
   ),
   'es-ES',
   'Número Mov.',
   'src/Forms/inMtoAlbaranesCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoAlbaranesCompra.TfrmMtoAlbaranesCompra.colMovProvAlbcFECHA_MOV.Ca',
     'ption'
   ),
   'es-ES',
   'Fecha',
   'src/Forms/inMtoAlbaranesCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoAlbaranesCompra.TfrmMtoAlbaranesCompra.colMovProvAlbcLINEA_MOV.Ca',
     'ption'
   ),
   'es-ES',
   'Línea',
   'src/Forms/inMtoAlbaranesCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlbaranesCompra.TfrmMtoAlbaranesCompra.colMovProvAlbcALMACEN.Caption',
   'es-ES',
   'Almacén',
   'src/Forms/inMtoAlbaranesCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlbaranesCompra.TfrmMtoAlbaranesCompra.colMovProvAlbcARTICULO.Caption',
   'es-ES',
   'Artículo',
   'src/Forms/inMtoAlbaranesCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlbaranesCompra.TfrmMtoAlbaranesCompra.colMovProvAlbcSKU.Caption',
   'es-ES',
   'SKU',
   'src/Forms/inMtoAlbaranesCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoAlbaranesCompra.TfrmMtoAlbaranesCompra.colMovProvAlbcDESCRIPCION.',
     'Caption'
   ),
   'es-ES',
   'Descripción',
   'src/Forms/inMtoAlbaranesCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlbaranesCompra.TfrmMtoAlbaranesCompra.colMovProvAlbcTIPO.Caption',
   'es-ES',
   'Tipo',
   'src/Forms/inMtoAlbaranesCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlbaranesCompra.TfrmMtoAlbaranesCompra.colMovProvAlbcCANTIDAD.Caption',
   'es-ES',
   'Cantidad',
   'src/Forms/inMtoAlbaranesCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlbaranesCompra.TfrmMtoAlbaranesCompra.colMovProvAlbcPMP.Caption',
   'es-ES',
   'PMP',
   'src/Forms/inMtoAlbaranesCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlbaranesCompra.TfrmMtoAlbaranesCompra.colMovProvAlbcTOTAL.Caption',
   'es-ES',
   'Total coste',
   'src/Forms/inMtoAlbaranesCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlbaranesCompra.TfrmMtoAlbaranesCompra.tsTotales.Caption',
   'es-ES',
   '&3_Totales',
   'src/Forms/inMtoAlbaranesCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlbaranesCompra.TfrmMtoAlbaranesCompra.lblTotalesTotalBase.Caption',
   'es-ES',
   'Total Base Imponible',
   'src/Forms/inMtoAlbaranesCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoAlbaranesCompra.TfrmMtoAlbaranesCompra.lblTotalesTotalImpuestos.C',
     'aption'
   ),
   'es-ES',
   'Total Impuestos',
   'src/Forms/inMtoAlbaranesCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoAlbaranesCompra.TfrmMtoAlbaranesCompra.lblTotalesPorcRetencion.Ca',
     'ption'
   ),
   'es-ES',
   '% Retención',
   'src/Forms/inMtoAlbaranesCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoAlbaranesCompra.TfrmMtoAlbaranesCompra.lblTotalesTotalRetencion.C',
     'aption'
   ),
   'es-ES',
   'Total Retención',
   'src/Forms/inMtoAlbaranesCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlbaranesCompra.TfrmMtoAlbaranesCompra.lblTotalesTotalPagar.Caption',
   'es-ES',
   'Total a pagar',
   'src/Forms/inMtoAlbaranesCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlbaranesCompra.TfrmMtoAlbaranesCompra.lblTotalesFormaPago.Caption',
   'es-ES',
   'Forma de Pago',
   'src/Forms/inMtoAlbaranesCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoAlbaranesCompra.TfrmMtoAlbaranesCompra.cbbTotalesFORMA_PAGO_ALBC.',
     'Properties.ListColumns[0].Caption'
   ),
   'es-ES',
   'Código',
   'src/Forms/inMtoAlbaranesCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoAlbaranesCompra.TfrmMtoAlbaranesCompra.cbbTotalesFORMA_PAGO_ALBC.',
     'Properties.ListColumns[1].Caption'
   ),
   'es-ES',
   'Descripción',
   'src/Forms/inMtoAlbaranesCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoAlbaranesCompra.TfrmMtoAlbaranesCompra.chkTotalesESIVA_RECARGO_CO',
     'MPRAS_ALBC.Caption'
   ),
   'es-ES',
   'Recargo equivalencia compras',
   'src/Forms/inMtoAlbaranesCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlbaranesCompra.TfrmMtoAlbaranesCompra.lblTotalesDtoComercial.Caption',
   'es-ES',
   'Dto. comercial',
   'src/Forms/inMtoAlbaranesCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoAlbaranesCompra.TfrmMtoAlbaranesCompra.lblTotalesDtoFinanciero.Ca',
     'ption'
   ),
   'es-ES',
   'Dto. financiero',
   'src/Forms/inMtoAlbaranesCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlbaranesCompra.TfrmMtoAlbaranesCompra.grpDesgloseImpuestos.Caption',
   'es-ES',
   'Desglose Impuestos',
   'src/Forms/inMtoAlbaranesCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlbaranesCompra.TfrmMtoAlbaranesCompra.lblTotalesTotalRe.Caption',
   'es-ES',
   'Total R.E.',
   'src/Forms/inMtoAlbaranesCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlbaranesCompra.TfrmMtoAlbaranesCompra.lblTotalesPorRe.Caption',
   'es-ES',
   '%R.E.',
   'src/Forms/inMtoAlbaranesCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlbaranesCompra.TfrmMtoAlbaranesCompra.lblTotalesTotalIva.Caption',
   'es-ES',
   'Total IVA',
   'src/Forms/inMtoAlbaranesCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlbaranesCompra.TfrmMtoAlbaranesCompra.lblTotalesPorIva.Caption',
   'es-ES',
   '%IVA',
   'src/Forms/inMtoAlbaranesCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlbaranesCompra.TfrmMtoAlbaranesCompra.lblTotalesBaseNeta.Caption',
   'es-ES',
   'BaseNeta',
   'src/Forms/inMtoAlbaranesCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlbaranesCompra.TfrmMtoAlbaranesCompra.lblTotalesIVAN.Caption',
   'es-ES',
   'Normal',
   'src/Forms/inMtoAlbaranesCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlbaranesCompra.TfrmMtoAlbaranesCompra.lblTotalesIVAR.Caption',
   'es-ES',
   'Reducido',
   'src/Forms/inMtoAlbaranesCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlbaranesCompra.TfrmMtoAlbaranesCompra.lblTotalesIVAS.Caption',
   'es-ES',
   'Súper Reducido',
   'src/Forms/inMtoAlbaranesCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlbaranesCompra.TfrmMtoAlbaranesCompra.lblTotalesIVAE.Caption',
   'es-ES',
   'Exento',
   'src/Forms/inMtoAlbaranesCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlbaranesCompra.TfrmMtoAlbaranesCompra.tsObservaciones.Caption',
   'es-ES',
   '&4_Observaciones',
   'src/Forms/inMtoAlbaranesCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlbaranesCompra.TfrmMtoAlbaranesCompra.lblTotalBases.Caption',
   'es-ES',
   'Total bases',
   'src/Forms/inMtoAlbaranesCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlbaranesCompra.TfrmMtoAlbaranesCompra.lblTotalImpuestos.Caption',
   'es-ES',
   'Total impuestos',
   'src/Forms/inMtoAlbaranesCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlbaranesCompra.TfrmMtoAlbaranesCompra.lblTotalLiquido.Caption',
   'es-ES',
   'Total líquido',
   'src/Forms/inMtoAlbaranesCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlbaranesCompra.TfrmMtoAlbaranesCompra.btnImprimirH.Caption',
   'es-ES',
   'Imprimir hor.',
   'src/Forms/inMtoAlbaranesCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlbaranesCompra.TfrmMtoAlbaranesCompra.btnImprimirV.Caption',
   'es-ES',
   'Imprimir vert.',
   'src/Forms/inMtoAlbaranesCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlbaranesCompra.TfrmMtoAlbaranesCompra.btnPegatinas.Caption',
   'es-ES',
   'Etiquetas',
   'src/Forms/inMtoAlbaranesCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlbaranesCompra.TfrmMtoAlbaranesCompra.actArticulos.Caption',
   'es-ES',
   'actArticulos',
   'src/Forms/inMtoAlbaranesCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlbaranesCompra.TfrmMtoAlbaranesCompra.actIrDocumento.Caption',
   'es-ES',
   'Ir a documento (Ctrl+May+A)',
   'src/Forms/inMtoAlbaranesCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlbaranesCompra.TfrmMtoAlbaranesCompra.actIrFacturaCreada.Caption',
   'es-ES',
   'Ir a factura creada',
   'src/Forms/inMtoAlbaranesCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlbaranesCompra.TfrmMtoAlbaranesCompra.actIrProveedor.Caption',
   'es-ES',
   'Ir a proveedor',
   'src/Forms/inMtoAlbaranesCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlmacenes.TfrmMtoAlmacenes.Caption',
   'es-ES',
   'Almacenes',
   'src/Forms/inMtoAlmacenes.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlmacenes.TfrmMtoAlmacenes.dbcGrdDBTabPrinCODIGO_ALMACEN_ALM.Caption',
   'es-ES',
   'Código Almacén',
   'src/Forms/inMtoAlmacenes.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlmacenes.TfrmMtoAlmacenes.dbcGrdDBTabPrinCODIGO_PADRE_ALM.Caption',
   'es-ES',
   'Código Padre',
   'src/Forms/inMtoAlmacenes.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlmacenes.TfrmMtoAlmacenes.dbcGrdDBTabPrinCODIGO_EMPRESA_ALM.Caption',
   'es-ES',
   'Código Empresa',
   'src/Forms/inMtoAlmacenes.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlmacenes.TfrmMtoAlmacenes.dbcGrdDBTabPrinNOMBRE_ALMACEN_ALM.Caption',
   'es-ES',
   'Nombre Almacén',
   'src/Forms/inMtoAlmacenes.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlmacenes.TfrmMtoAlmacenes.dbcGrdDBTabPrinESACTIVO_ALM.Caption',
   'es-ES',
   'Activo',
   'src/Forms/inMtoAlmacenes.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlmacenes.TfrmMtoAlmacenes.dbcGrdDBTabPrinESFISICO_ALM.Caption',
   'es-ES',
   'Es Físico',
   'src/Forms/inMtoAlmacenes.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlmacenes.TfrmMtoAlmacenes.dbcGrdDBTabPrinTIPO_USO_ALM.Caption',
   'es-ES',
   'Tipo Uso',
   'src/Forms/inMtoAlmacenes.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlmacenes.TfrmMtoAlmacenes.dbcGrdDBTabPrinDIRECCION_ALM.Caption',
   'es-ES',
   'Dirección',
   'src/Forms/inMtoAlmacenes.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlmacenes.TfrmMtoAlmacenes.dbcGrdDBTabPrinPOBLACION_ALM.Caption',
   'es-ES',
   'Población',
   'src/Forms/inMtoAlmacenes.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlmacenes.TfrmMtoAlmacenes.dbcGrdDBTabPrinCODIGO_POSTAL_ALM.Caption',
   'es-ES',
   'Código Postal',
   'src/Forms/inMtoAlmacenes.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlmacenes.TfrmMtoAlmacenes.dbcGrdDBTabPrinTELEFONO_ALM.Caption',
   'es-ES',
   'Teléfono',
   'src/Forms/inMtoAlmacenes.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlmacenes.TfrmMtoAlmacenes.dbcGrdDBTabPrinEMAIL_ALM.Caption',
   'es-ES',
   'Email',
   'src/Forms/inMtoAlmacenes.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlmacenes.TfrmMtoAlmacenes.dbcGrdDBTabPrinCODIGO_CLIENTE_ALM.Caption',
   'es-ES',
   'Código Cliente',
   'src/Forms/inMtoAlmacenes.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoAlmacenes.TfrmMtoAlmacenes.dbcGrdDBTabPrinALMACEN_DESTINO_ACTUAL_',
     'ALM.Caption'
   ),
   'es-ES',
   'Almacén Destino',
   'src/Forms/inMtoAlmacenes.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoAlmacenes.TfrmMtoAlmacenes.dbcGrdDBTabPrinALMACEN_ORIGEN_ACTUAL_A',
     'LM.Caption'
   ),
   'es-ES',
   'Almacén Origen',
   'src/Forms/inMtoAlmacenes.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlmacenes.TfrmMtoAlmacenes.dbcGrdDBTabPrinORDEN_ALM.Caption',
   'es-ES',
   'Orden',
   'src/Forms/inMtoAlmacenes.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlmacenes.TfrmMtoAlmacenes.lblCodigo.Caption',
   'es-ES',
   'Código Almacén',
   'src/Forms/inMtoAlmacenes.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlmacenes.TfrmMtoAlmacenes.lblCodigoEmpresa.Caption',
   'es-ES',
   'Código Empresa',
   'src/Forms/inMtoAlmacenes.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlmacenes.TfrmMtoAlmacenes.lblNombre.Caption',
   'es-ES',
   'Nombre Almacén',
   'src/Forms/inMtoAlmacenes.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlmacenes.TfrmMtoAlmacenes.chkESACTIVO_ALM.Caption',
   'es-ES',
   'Activo',
   'src/Forms/inMtoAlmacenes.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlmacenes.TfrmMtoAlmacenes.chkESFISICO_ALM.Caption',
   'es-ES',
   'Es Físico',
   'src/Forms/inMtoAlmacenes.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlmacenes.TfrmMtoAlmacenes.lblOrden.Caption',
   'es-ES',
   'Orden',
   'src/Forms/inMtoAlmacenes.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlmacenes.TfrmMtoAlmacenes.tsDireccion.Caption',
   'es-ES',
   '&0_Dirección física',
   'src/Forms/inMtoAlmacenes.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlmacenes.TfrmMtoAlmacenes.lblTelefono.Caption',
   'es-ES',
   'Teléfono',
   'src/Forms/inMtoAlmacenes.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlmacenes.TfrmMtoAlmacenes.lblEmail.Caption',
   'es-ES',
   'Email',
   'src/Forms/inMtoAlmacenes.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlmacenes.TfrmMtoAlmacenes.lblPoblacion.Caption',
   'es-ES',
   'Población',
   'src/Forms/inMtoAlmacenes.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlmacenes.TfrmMtoAlmacenes.lblDireccion.Caption',
   'es-ES',
   'Dirección',
   'src/Forms/inMtoAlmacenes.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlmacenes.TfrmMtoAlmacenes.lblProvincia.Caption',
   'es-ES',
   'Provincia',
   'src/Forms/inMtoAlmacenes.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlmacenes.TfrmMtoAlmacenes.tsCajas.Caption',
   'es-ES',
   '&1 Cajas de Venta',
   'src/Forms/inMtoAlmacenes.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoAlmacenes.TfrmMtoAlmacenes.dbmAlmacenesCajasCODIGO_ALMACEN_ALMCAJ',
     '.Caption'
   ),
   'es-ES',
   'Código Almacén',
   'src/Forms/inMtoAlmacenes.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoAlmacenes.TfrmMtoAlmacenes.dbmAlmacenesCajasCODIGO_CAJA_ALMCAJ.Ca',
     'ption'
   ),
   'es-ES',
   'Código Caja',
   'src/Forms/inMtoAlmacenes.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoAlmacenes.TfrmMtoAlmacenes.dbmAlmacenesCajasDESCRIPCION_ALMCAJ.Ca',
     'ption'
   ),
   'es-ES',
   'Descripción',
   'src/Forms/inMtoAlmacenes.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlmacenes.TfrmMtoAlmacenes.tsUsosAlmacen.Caption',
   'es-ES',
   '&2_Usos Almacén',
   'src/Forms/inMtoAlmacenes.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlmacenes.TfrmMtoAlmacenes.lblAlmacenDestino.Caption',
   'es-ES',
   'Almacén Destino',
   'src/Forms/inMtoAlmacenes.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlmacenes.TfrmMtoAlmacenes.lblAlmacenOrigen.Caption',
   'es-ES',
   'Almacén Origen',
   'src/Forms/inMtoAlmacenes.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlmacenes.TfrmMtoAlmacenes.lblTipoUso.Caption',
   'es-ES',
   'Tipo de Uso',
   'src/Forms/inMtoAlmacenes.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlmacenes.TfrmMtoAlmacenes.lblCodigoPadre.Caption',
   'es-ES',
   'Código Padre',
   'src/Forms/inMtoAlmacenes.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlmacenes.TfrmMtoAlmacenes.lblCodigoCliente.Caption',
   'es-ES',
   'Código Cliente',
   'src/Forms/inMtoAlmacenes.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlmacenes.TfrmMtoAlmacenes.tsAuditoria.Caption',
   'es-ES',
   '&3_Otros',
   'src/Forms/inMtoAlmacenes.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlmacenes.TfrmMtoAlmacenes.lblUsuarioAlta.Caption',
   'es-ES',
   'Usuario Alta',
   'src/Forms/inMtoAlmacenes.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlmacenes.TfrmMtoAlmacenes.lblInstanteAlta.Caption',
   'es-ES',
   'Instante Alta',
   'src/Forms/inMtoAlmacenes.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlmacenes.TfrmMtoAlmacenes.lblUsuarioModif.Caption',
   'es-ES',
   'Usuario Modificación',
   'src/Forms/inMtoAlmacenes.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAlmacenes.TfrmMtoAlmacenes.lblInstanteModif.Caption',
   'es-ES',
   'Instante Modificación',
   'src/Forms/inMtoAlmacenes.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoArticulos.TfrmMtoArticulos.Caption',
   'es-ES',
   'Articulos',
   'src/Forms/inMtoArticulos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoArticulos.TfrmMtoArticulos.cxgrdbclmnGrdDBTabPrinCODIGO_ARTICULO.',
     'Caption'
   ),
   'es-ES',
   'Código Artículo',
   'src/Forms/inMtoArticulos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoArticulos.TfrmMtoArticulos.cxgrdbclmnGrdDBTabPrinACTIVO_ARTICULO.',
     'Caption'
   ),
   'es-ES',
   'Activo',
   'src/Forms/inMtoArticulos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoArticulos.TfrmMtoArticulos.cxgrdbclmnGrdDBTabPrinDESCRIPCION_ARTI',
     'CULO.Caption'
   ),
   'es-ES',
   'Descripción',
   'src/Forms/inMtoArticulos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoArticulos.TfrmMtoArticulos.cxgrdbclmnGrdDBTabPrinCODIGO_FAMILIA_A',
     'RTICULO.Caption'
   ),
   'es-ES',
   'Código Familia',
   'src/Forms/inMtoArticulos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoArticulos.TfrmMtoArticulos.cxgrdbclmnGrdDBTabPrinDESCRIPCION_FAMI',
     'LIA.Caption'
   ),
   'es-ES',
   'Descripción Familia',
   'src/Forms/inMtoArticulos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoArticulos.TfrmMtoArticulos.cxgrdbclmnGrdDBTabPrinTIPOIVA_ARTICULO',
     '.Caption'
   ),
   'es-ES',
   'Tipo IVA',
   'src/Forms/inMtoArticulos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoArticulos.TfrmMtoArticulos.cxgrdbclmnGrdDBTabPrinREF_PROVEEDOR.Ca',
     'ption'
   ),
   'es-ES',
   'Modelo Proveedor',
   'src/Forms/inMtoArticulos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoArticulos.TfrmMtoArticulos.cxgrdbclmnGrdDBTabPrinNOMBRE_PRV.Caption',
   'es-ES',
   'Proveedor',
   'src/Forms/inMtoArticulos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoArticulos.TfrmMtoArticulos.cxgrdbclmnGrdDBTabPrinTEMPORADA_ART.Ca',
     'ption'
   ),
   'es-ES',
   'Temporada',
   'src/Forms/inMtoArticulos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoArticulos.TfrmMtoArticulos.btnToggleFiltrosArt.Caption',
   'es-ES',
   '▶  Filtros de carga',
   'src/Forms/inMtoArticulos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoArticulos.TfrmMtoArticulos.lblFiltroEstadoArt.Caption',
   'es-ES',
   'Estado:',
   'src/Forms/inMtoArticulos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoArticulos.TfrmMtoArticulos.chkFiltroConStockArt.Caption',
   'es-ES',
   'Sólo con stock',
   'src/Forms/inMtoArticulos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoArticulos.TfrmMtoArticulos.lblFiltroTemporadaArt.Caption',
   'es-ES',
   'Temporadas:',
   'src/Forms/inMtoArticulos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoArticulos.TfrmMtoArticulos.btnCargarAhoraArt.Caption',
   'es-ES',
   'Cargar ahora',
   'src/Forms/inMtoArticulos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoArticulos.TfrmMtoArticulos.btnGuardarPrecargaArt.Caption',
   'es-ES',
   'Guardar precarga',
   'src/Forms/inMtoArticulos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoArticulos.TfrmMtoArticulos.lblCodigo.Caption',
   'es-ES',
   'Código',
   'src/Forms/inMtoArticulos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoArticulos.TfrmMtoArticulos.lblNombre.Caption',
   'es-ES',
   'Nombre',
   'src/Forms/inMtoArticulos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoArticulos.TfrmMtoArticulos.chkActivo.Caption',
   'es-ES',
   'Activo',
   'src/Forms/inMtoArticulos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoArticulos.TfrmMtoArticulos.lblFamilia.Caption',
   'es-ES',
   'Familia',
   'src/Forms/inMtoArticulos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoArticulos.TfrmMtoArticulos.tsGeneral.Caption',
   'es-ES',
   '&1_General',
   'src/Forms/inMtoArticulos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoArticulos.TfrmMtoArticulos.rgTipoIVA.Caption',
   'es-ES',
   'Tipo de IVA',
   'src/Forms/inMtoArticulos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoArticulos.TfrmMtoArticulos.rgTipoIVA.Properties.Items[0].Caption',
   'es-ES',
   'Normal',
   'src/Forms/inMtoArticulos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoArticulos.TfrmMtoArticulos.rgTipoIVA.Properties.Items[1].Caption',
   'es-ES',
   'Reducido',
   'src/Forms/inMtoArticulos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoArticulos.TfrmMtoArticulos.rgTipoIVA.Properties.Items[2].Caption',
   'es-ES',
   'Súper Reducido',
   'src/Forms/inMtoArticulos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoArticulos.TfrmMtoArticulos.rgTipoIVA.Properties.Items[3].Caption',
   'es-ES',
   'Exento',
   'src/Forms/inMtoArticulos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoArticulos.TfrmMtoArticulos.cxGroupBox2.Caption',
   'es-ES',
   'Tipología',
   'src/Forms/inMtoArticulos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoArticulos.TfrmMtoArticulos.lblNombre1.Caption',
   'es-ES',
   'Tipo de Cantidad',
   'src/Forms/inMtoArticulos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoArticulos.TfrmMtoArticulos.lblTipoArticulo.Caption',
   'es-ES',
   'Tipo de Artículo',
   'src/Forms/inMtoArticulos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoArticulos.TfrmMtoArticulos.chkESVARIACION_ART.Caption',
   'es-ES',
   'Tiene Variaciones/SKU múltiple',
   'src/Forms/inMtoArticulos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoArticulos.TfrmMtoArticulos.chkESTRAZABLE_ART.Caption',
   'es-ES',
   'Trazabilidad/Serialización por unidad y/o LOTE/Fecha de Caducidad',
   'src/Forms/inMtoArticulos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoArticulos.TfrmMtoArticulos.tsSkuMto.Caption',
   'es-ES',
   '&2_SKUs',
   'src/Forms/inMtoArticulos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoArticulos.TfrmMtoArticulos.addSkuAll.Caption',
   'es-ES',
   '&Añadir SKU',
   'src/Forms/inMtoArticulos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoArticulos.TfrmMtoArticulos.btnColorSkus.Caption',
   'es-ES',
   'Activar/Desact. color',
   'src/Forms/inMtoArticulos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoArticulos.TfrmMtoArticulos.tvSkuMtoCODIGO_UNIDAD_SKU.Caption',
   'es-ES',
   'Código SKU',
   'src/Forms/inMtoArticulos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoArticulos.TfrmMtoArticulos.tvSkuMtoCODIGO_VAR_SKU.Caption',
   'es-ES',
   'Variación',
   'src/Forms/inMtoArticulos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoArticulos.TfrmMtoArticulos.tvSkuMtoESACTIVO_SKU.Caption',
   'es-ES',
   'Activo',
   'src/Forms/inMtoArticulos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoArticulos.TfrmMtoArticulos.tvSkuMtoPRECIO_ULT_COMPRA_SKUC.Caption',
   'es-ES',
   'Precio Últ Compra',
   'src/Forms/inMtoArticulos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoArticulos.TfrmMtoArticulos.tvSkuMtoFECHA_ULT_COMPRA_SKUC.Caption',
   'es-ES',
   'Fecha Últ Compra',
   'src/Forms/inMtoArticulos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoArticulos.TfrmMtoArticulos.gbSkuAtributosBasicos.Caption',
   'es-ES',
   ' Atributos del SKU + Atributo básico (helper) ',
   'src/Forms/inMtoArticulos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoArticulos.TfrmMtoArticulos.tvSkuAtributosBasicosID_VA_AV.Caption',
   'es-ES',
   'Atributo',
   'src/Forms/inMtoArticulos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoArticulos.TfrmMtoArticulos.tvSkuAtributosBasicosNOMBRE_ATRIBUTO.C',
     'aption'
   ),
   'es-ES',
   'Nombre atributo',
   'src/Forms/inMtoArticulos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoArticulos.TfrmMtoArticulos.tvSkuAtributosBasicosVALOR_AV.Caption',
   'es-ES',
   'Color proveedor',
   'src/Forms/inMtoArticulos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoArticulos.TfrmMtoArticulos.tvSkuAtributosBasicosID_ATB_AV.Caption',
   'es-ES',
   'Color básico',
   'src/Forms/inMtoArticulos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoArticulos.TfrmMtoArticulos.tvSkuAtributosBasicosID_ATB_AV.Propert',
     'ies.ListColumns[0].Caption'
   ),
   'es-ES',
   'Código',
   'src/Forms/inMtoArticulos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoArticulos.TfrmMtoArticulos.tvSkuAtributosBasicosID_ATB_AV.Propert',
     'ies.ListColumns[1].Caption'
   ),
   'es-ES',
   'Nombre',
   'src/Forms/inMtoArticulos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoArticulos.TfrmMtoArticulos.tvSkuAtributosBasicosID_ATB_AV.Propert',
     'ies.ListColumns[2].Caption'
   ),
   'es-ES',
   'Paleta',
   'src/Forms/inMtoArticulos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoArticulos.TfrmMtoArticulos.tvSkuAtributosBasicosID_ATB_AV.Propert',
     'ies.ListColumns[3].Caption'
   ),
   'es-ES',
   'Medida',
   'src/Forms/inMtoArticulos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoArticulos.TfrmMtoArticulos.tvSkuAtributosBasicosID_ATB_AV.Propert',
     'ies.ListColumns[4].Caption'
   ),
   'es-ES',
   'Ud',
   'src/Forms/inMtoArticulos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoArticulos.TfrmMtoArticulos.tvSkuAtributosBasicosDESCRIPCION_AAB.C',
     'aption'
   ),
   'es-ES',
   'Descripción del color',
   'src/Forms/inMtoArticulos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoArticulos.TfrmMtoArticulos.tvSkuAtributosBasicosNOMBRE_ATB.Caption',
   'es-ES',
   'Nombre básico',
   'src/Forms/inMtoArticulos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoArticulos.TfrmMtoArticulos.tvSkuAtributosBasicosHEX_ATB.Caption',
   'es-ES',
   'Paleta',
   'src/Forms/inMtoArticulos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoArticulos.TfrmMtoArticulos.tvSkuAtributosBasicosVALOR_NUM_ATB.Caption',
   'es-ES',
   'Valor básico',
   'src/Forms/inMtoArticulos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoArticulos.TfrmMtoArticulos.tvSkuAtributosBasicosUNIDAD_ATB.Caption',
   'es-ES',
   'Unidad',
   'src/Forms/inMtoArticulos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoArticulos.TfrmMtoArticulos.tvSkuAtributosBasicosETIQUETA_BASICO.C',
     'aption'
   ),
   'es-ES',
   'Equivalencia',
   'src/Forms/inMtoArticulos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoArticulos.TfrmMtoArticulos.tvSkuAtributosBasicosFUENTE_ATB.Caption',
   'es-ES',
   'Fuente',
   'src/Forms/inMtoArticulos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoArticulos.TfrmMtoArticulos.tsPropiedades.Caption',
   'es-ES',
   '&3_Propiedades',
   'src/Forms/inMtoArticulos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoArticulos.TfrmMtoArticulos.tsSKUs.Caption',
   'es-ES',
   '&4_CB',
   'src/Forms/inMtoArticulos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoArticulos.TfrmMtoArticulos.btnExportarExcelCB.Caption',
   'es-ES',
   '&Exp Excel',
   'src/Forms/inMtoArticulos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoArticulos.TfrmMtoArticulos.btnGenerarCB.Caption',
   'es-ES',
   '&Generar CB',
   'src/Forms/inMtoArticulos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoArticulos.TfrmMtoArticulos.btnVerificarCB.Caption',
   'es-ES',
   '&Verificar CB',
   'src/Forms/inMtoArticulos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoArticulos.TfrmMtoArticulos.tvSkusCODIGO_UNIDAD_SKU.Caption',
   'es-ES',
   'Código SKU',
   'src/Forms/inMtoArticulos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoArticulos.TfrmMtoArticulos.tvSkusESACTIVO_SKU.Caption',
   'es-ES',
   'Activo',
   'src/Forms/inMtoArticulos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoArticulos.TfrmMtoArticulos.tvSkusCODIGO_BARRAS_CB.Caption',
   'es-ES',
   'Código de Barras',
   'src/Forms/inMtoArticulos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoArticulos.TfrmMtoArticulos.tvSkusTIPO_CODIGO_CB.Caption',
   'es-ES',
   'Tipo',
   'src/Forms/inMtoArticulos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoArticulos.TfrmMtoArticulos.tvSkusESPRINCIPAL_CB.Caption',
   'es-ES',
   'Etiqueta',
   'src/Forms/inMtoArticulos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoArticulos.TfrmMtoArticulos.tvSkusSTOCK_TOTAL.Caption',
   'es-ES',
   'Stock Total',
   'src/Forms/inMtoArticulos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoArticulos.TfrmMtoArticulos.tsTarifas.Caption',
   'es-ES',
   '&5_Tarifas',
   'src/Forms/inMtoArticulos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoArticulos.TfrmMtoArticulos.cxgrdbclmnTarifasCODIGO_TARIFA.Caption',
   'es-ES',
   'Código Tarifa',
   'src/Forms/inMtoArticulos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoArticulos.TfrmMtoArticulos.cxgrdbclmnTarifasNOMBRE_TARIFA.Caption',
   'es-ES',
   'Nombre Tarifa',
   'src/Forms/inMtoArticulos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoArticulos.TfrmMtoArticulos.dbcTarifasESIMP_INCL_TARIFA.Caption',
   'es-ES',
   'Imp. Incl.',
   'src/Forms/inMtoArticulos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoArticulos.TfrmMtoArticulos.cxgrdbclmnTarifasCODIGO_ARTICULO_TARIF',
     'A.Caption'
   ),
   'es-ES',
   'Código Artículo',
   'src/Forms/inMtoArticulos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoArticulos.TfrmMtoArticulos.tvTarifasCODIGO_UNIDAD_TARIFA.Caption',
   'es-ES',
   'Sku',
   'src/Forms/inMtoArticulos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoArticulos.TfrmMtoArticulos.cxgrdbclmnTarifasDESCRIPCION_ARTICULO.',
     'Caption'
   ),
   'es-ES',
   'Descripción',
   'src/Forms/inMtoArticulos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoArticulos.TfrmMtoArticulos.cxgrdbclmnTarifasTIPO_CANTIDAD_ARTICUL',
     'O.Caption'
   ),
   'es-ES',
   'Tipo Cantidad',
   'src/Forms/inMtoArticulos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoArticulos.TfrmMtoArticulos.dbcTarifasPRECIOSALIDA.Caption',
   'es-ES',
   'Precio Salida',
   'src/Forms/inMtoArticulos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoArticulos.TfrmMtoArticulos.dbcTarifasPORCEN_DTO_TARIFA.Caption',
   'es-ES',
   '% Descuento',
   'src/Forms/inMtoArticulos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoArticulos.TfrmMtoArticulos.dbcTarifasPRECIO_DTO_TARIFA.Caption',
   'es-ES',
   'Euros descuento',
   'src/Forms/inMtoArticulos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoArticulos.TfrmMtoArticulos.dbcTarifasPRECIOFINAL.Caption',
   'es-ES',
   'Precio Final',
   'src/Forms/inMtoArticulos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoArticulos.TfrmMtoArticulos.dbcTarifasMARGEN.Caption',
   'es-ES',
   'Margen',
   'src/Forms/inMtoArticulos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoArticulos.TfrmMtoArticulos.cxgrdbclmnTarifasTIPO_IVA_ARTICULO.Caption',
   'es-ES',
   'Tipo IVA',
   'src/Forms/inMtoArticulos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoArticulos.TfrmMtoArticulos.cxgrdbclmnTarifasACTIVO_TARIFA.Caption',
   'es-ES',
   'Tarifa Activa',
   'src/Forms/inMtoArticulos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoArticulos.TfrmMtoArticulos.cxgrdbclmnTarifasFECHA_DESDE_TARIFA.Ca',
     'ption'
   ),
   'es-ES',
   'Fecha Desde',
   'src/Forms/inMtoArticulos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoArticulos.TfrmMtoArticulos.cxgrdbclmnTarifasFECHA_HASTA_TARIFA.Ca',
     'ption'
   ),
   'es-ES',
   'Fecha Hasta',
   'src/Forms/inMtoArticulos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoArticulos.TfrmMtoArticulos.cxgrdbclmnTarifasCODIGO_PROVEEDOR.Caption',
   'es-ES',
   'Código Proveedor',
   'src/Forms/inMtoArticulos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoArticulos.TfrmMtoArticulos.cxgrdbclmnTarifasRAZONSOCIAL_PROVEEDOR',
     '.Caption'
   ),
   'es-ES',
   'Nombre Proveedor',
   'src/Forms/inMtoArticulos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoArticulos.TfrmMtoArticulos.cxgrdbclmnTarifasPRECIO_ULT_COMPRA.Caption',
   'es-ES',
   'Precio Últ Compra',
   'src/Forms/inMtoArticulos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoArticulos.TfrmMtoArticulos.cxgrdbclmnTarifasFECHA_VALIDEZ.Caption',
   'es-ES',
   'Fecha Validez',
   'src/Forms/inMtoArticulos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoArticulos.TfrmMtoArticulos.cxgrdbclmnTarifasCODIGO_FAMILIA_ARTICU',
     'LO.Caption'
   ),
   'es-ES',
   'Familia',
   'src/Forms/inMtoArticulos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoArticulos.TfrmMtoArticulos.cxgrdbclmnTarifasDESCRIPCION_FAMILIA.C',
     'aption'
   ),
   'es-ES',
   'Descripción Familia',
   'src/Forms/inMtoArticulos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoArticulos.TfrmMtoArticulos.cxgrdbclmnTarifasINSTANTEALTA.Caption',
   'es-ES',
   'Fecha Alta',
   'src/Forms/inMtoArticulos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoArticulos.TfrmMtoArticulos.cxgrdbclmnTarifasINSTANTEMODIF.Caption',
   'es-ES',
   'Fecha Modif.',
   'src/Forms/inMtoArticulos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoArticulos.TfrmMtoArticulos.cxgrdbclmnTarifasUSUARIOALTA.Caption',
   'es-ES',
   'Usuario Alta',
   'src/Forms/inMtoArticulos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoArticulos.TfrmMtoArticulos.cxgrdbclmnTarifasUSUARIOMODIF.Caption',
   'es-ES',
   'Usuario Modif.',
   'src/Forms/inMtoArticulos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoArticulos.TfrmMtoArticulos.dbcTarifasCODIGO_UNICO_TARIFA.Caption',
   'es-ES',
   'Cód. Único',
   'src/Forms/inMtoArticulos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoArticulos.TfrmMtoArticulos.tvTarifasESVARIACION_ARTICULO.Caption',
   'es-ES',
   'Variación',
   'src/Forms/inMtoArticulos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoArticulos.TfrmMtoArticulos.tvTarifasNUM_ATRIBUTOS_REQ.Caption',
   'es-ES',
   'Nº Atributos',
   'src/Forms/inMtoArticulos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoArticulos.TfrmMtoArticulos.btnIraTarifa.Caption',
   'es-ES',
   'Ir a &Tarifa',
   'src/Forms/inMtoArticulos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoArticulos.TfrmMtoArticulos.btnExportarTarifa.Caption',
   'es-ES',
   '&Exp Excel',
   'src/Forms/inMtoArticulos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoArticulos.TfrmMtoArticulos.btnAddSKU.Caption',
   'es-ES',
   'A&ñadir precio',
   'src/Forms/inMtoArticulos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoArticulos.TfrmMtoArticulos.tsProveedores.Caption',
   'es-ES',
   '&6_Proveedores',
   'src/Forms/inMtoArticulos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoArticulos.TfrmMtoArticulos.cxgrdbclmnProveedoresESPROVEEDORPRINCI',
     'PAL.Caption'
   ),
   'es-ES',
   'Principal',
   'src/Forms/inMtoArticulos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoArticulos.TfrmMtoArticulos.tvProveedoresREF_PROVEEDOR.Caption',
   'es-ES',
   'Modelo Proveedor',
   'src/Forms/inMtoArticulos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoArticulos.TfrmMtoArticulos.cxgrdbclmnProveedoresCODIGO_PROVEEDOR.',
     'Caption'
   ),
   'es-ES',
   'Código Proveedor',
   'src/Forms/inMtoArticulos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoArticulos.TfrmMtoArticulos.cxgrdbclmnProveedoresRAZONSOCIAL_PROVE',
     'EDOR.Caption'
   ),
   'es-ES',
   'Razón Social Proveedor',
   'src/Forms/inMtoArticulos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoArticulos.TfrmMtoArticulos.cxgrdbclmnProveedoresPRECIO_ULT_COMPRA',
     '.Caption'
   ),
   'es-ES',
   'Precio Última Compra',
   'src/Forms/inMtoArticulos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoArticulos.TfrmMtoArticulos.cxgrdbclmnProveedoresFECHA_VALIDEZ.Caption',
   'es-ES',
   'Fecha último Precio',
   'src/Forms/inMtoArticulos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoArticulos.TfrmMtoArticulos.btnIraProveedor.Caption',
   'es-ES',
   '&Ir a Proveedor',
   'src/Forms/inMtoArticulos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoArticulos.TfrmMtoArticulos.btnExportarProveedor.Caption',
   'es-ES',
   '&Exp Excel',
   'src/Forms/inMtoArticulos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoArticulos.TfrmMtoArticulos.btnAddProveedor.Caption',
   'es-ES',
   '&Añadir',
   'src/Forms/inMtoArticulos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoArticulos.TfrmMtoArticulos.tsLineasFactura.Caption',
   'es-ES',
   '&7_Lineas de Venta - ',
   'src/Forms/inMtoArticulos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoArticulos.TfrmMtoArticulos.tvLinFacFECHA_FAC.Caption',
   'es-ES',
   'Fecha',
   'src/Forms/inMtoArticulos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoArticulos.TfrmMtoArticulos.cxgrdbclmnLinFacSERIE_FACTURA_LINEA.Ca',
     'ption'
   ),
   'es-ES',
   'Serie',
   'src/Forms/inMtoArticulos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoArticulos.TfrmMtoArticulos.cxgrdbclmnLinFacNRO_FACTURA_LINEA.Caption',
   'es-ES',
   'Nro',
   'src/Forms/inMtoArticulos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoArticulos.TfrmMtoArticulos.cxgrdbclmnLinFacLINEA_FACTURA_LINEA.Ca',
     'ption'
   ),
   'es-ES',
   'Nro Linea',
   'src/Forms/inMtoArticulos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoArticulos.TfrmMtoArticulos.cxgrdbclmnLinFacTIPO_CANTIDAD_ARTICULO',
     '_FACTURA_LINEA.Caption'
   ),
   'es-ES',
   'Tipo Cantidad',
   'src/Forms/inMtoArticulos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoArticulos.TfrmMtoArticulos.cxgrdbclmnLinFacCANTIDAD_FACTURA_LINEA',
     '.Caption'
   ),
   'es-ES',
   'Cantidad',
   'src/Forms/inMtoArticulos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoArticulos.TfrmMtoArticulos.cxgrdbclmnLinFacDESCRIPCION_ARTICULO_F',
     'ACTURA_LINEA.Caption'
   ),
   'es-ES',
   'Descripción Linea',
   'src/Forms/inMtoArticulos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoArticulos.TfrmMtoArticulos.cxgrdbclmnLinFacNOMBRE_TARIFA.Caption',
   'es-ES',
   'Tarifa Aplicada',
   'src/Forms/inMtoArticulos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoArticulos.TfrmMtoArticulos.cxgrdbclmnLinFacESIMP_INCL_TARIFA_FACT',
     'URA_LINEA.Caption'
   ),
   'es-ES',
   'Precio Imp. Incl.',
   'src/Forms/inMtoArticulos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoArticulos.TfrmMtoArticulos.cxgrdbclmnLinFacPRECIOVENTA_SIVA_ARTIC',
     'ULO_FACTURA_LINEA.Caption'
   ),
   'es-ES',
   'Precio sin IVA',
   'src/Forms/inMtoArticulos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoArticulos.TfrmMtoArticulos.cxgrdbclmnLinFacTIPOIVA_ARTICULO_FACTU',
     'RA_LINEA.Caption'
   ),
   'es-ES',
   'Tipo IVA',
   'src/Forms/inMtoArticulos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoArticulos.TfrmMtoArticulos.cxgrdbclmnLinFacPORCEN_IVA_FACTURA_LIN',
     'EA.Caption'
   ),
   'es-ES',
   '% IVA',
   'src/Forms/inMtoArticulos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoArticulos.TfrmMtoArticulos.cxgrdbclmnLinFacPRECIOVENTA_CIVA_ARTIC',
     'ULO_FACTURA_LINEA.Caption'
   ),
   'es-ES',
   'Precio Con IVA',
   'src/Forms/inMtoArticulos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoArticulos.TfrmMtoArticulos.cxgrdbclmnLinFacTOTAL_FACTURA_LINEA.Ca',
     'ption'
   ),
   'es-ES',
   'Total Linea',
   'src/Forms/inMtoArticulos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoArticulos.TfrmMtoArticulos.cxgrdbclmnLinFacFECHA_ENTREGA_FACTURA_',
     'LINEA.Caption'
   ),
   'es-ES',
   'Fecha Entrega',
   'src/Forms/inMtoArticulos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoArticulos.TfrmMtoArticulos.btnIraFactura.Caption',
   'es-ES',
   'Ir a F&',
   'src/Forms/inMtoArticulos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoArticulos.TfrmMtoArticulos.btnIraEmpresa.Caption',
   'es-ES',
   'Ir a &Empr.',
   'src/Forms/inMtoArticulos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoArticulos.TfrmMtoArticulos.btnExportarLineas.Caption',
   'es-ES',
   '&Exp Excel',
   'src/Forms/inMtoArticulos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoArticulos.TfrmMtoArticulos.btnIraCliente.Caption',
   'es-ES',
   'Ir a C&liente',
   'src/Forms/inMtoArticulos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoArticulos.TfrmMtoArticulos.cxTabSheet3.Caption',
   'es-ES',
   '&8_Stock',
   'src/Forms/inMtoArticulos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoArticulos.TfrmMtoArticulos.btnStockExportarExcel.Caption',
   'es-ES',
   '&Exp Excel',
   'src/Forms/inMtoArticulos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoArticulos.TfrmMtoArticulos.btnReconstruirStock.Caption',
   'es-ES',
   '&Reconstruir Stock',
   'src/Forms/inMtoArticulos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoArticulos.TfrmMtoArticulos.btnImprimirEtiquetas.Caption',
   'es-ES',
   'Imprimir &Etiquetas',
   'src/Forms/inMtoArticulos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoArticulos.TfrmMtoArticulos.tsMovimientos.Caption',
   'es-ES',
   '&9_Movimientos',
   'src/Forms/inMtoArticulos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoArticulos.TfrmMtoArticulos.tvMovimientosCODIGO_UNIDAD_MOV.Caption',
   'es-ES',
   'Sku',
   'src/Forms/inMtoArticulos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoArticulos.TfrmMtoArticulos.tvMovimientosCANTIDAD_MOV.Caption',
   'es-ES',
   'Ctd',
   'src/Forms/inMtoArticulos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoArticulos.TfrmMtoArticulos.tvMovimientosCODIGO_EMPRESA_MOV.Caption',
   'es-ES',
   'Cód Empresa',
   'src/Forms/inMtoArticulos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoArticulos.TfrmMtoArticulos.tvMovimientosCODIGO_ALMACEN_MOV.Caption',
   'es-ES',
   'Alm Origen',
   'src/Forms/inMtoArticulos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoArticulos.TfrmMtoArticulos.tvMovimientosNUMERO_MOV.Caption',
   'es-ES',
   'Nro. Mov',
   'src/Forms/inMtoArticulos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoArticulos.TfrmMtoArticulos.tvMovimientosTIPO_DOC_MOV.Caption',
   'es-ES',
   'Tipo',
   'src/Forms/inMtoArticulos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoArticulos.TfrmMtoArticulos.tvMovimientosTIPO_MOVIMIENTO_MOV.Caption',
   'es-ES',
   'E/S',
   'src/Forms/inMtoArticulos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoArticulos.TfrmMtoArticulos.tvMovimientosSERIE_DOC_MOV.Caption',
   'es-ES',
   'Serie',
   'src/Forms/inMtoArticulos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoArticulos.TfrmMtoArticulos.tvMovimientosNRO_DOC_MOV.Caption',
   'es-ES',
   'Nro Doc',
   'src/Forms/inMtoArticulos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoArticulos.TfrmMtoArticulos.tvMovimientosLINEA_MOV.Caption',
   'es-ES',
   'NroLinea',
   'src/Forms/inMtoArticulos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoArticulos.TfrmMtoArticulos.tvMovimientosFECHA_MOV.Caption',
   'es-ES',
   'Fecha Hora',
   'src/Forms/inMtoArticulos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoArticulos.TfrmMtoArticulos.tvMovimientosCODIGO_ARTICULO_MOV.Caption',
   'es-ES',
   'Cód Art.',
   'src/Forms/inMtoArticulos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoArticulos.TfrmMtoArticulos.tvMovimientosPRECIO_COSTE_UNITARIO_MOV',
     '.Caption'
   ),
   'es-ES',
   'Coste Ud',
   'src/Forms/inMtoArticulos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoArticulos.TfrmMtoArticulos.tvMovimientosTOTAL_COSTE_MOV.Caption',
   'es-ES',
   'Total Coste',
   'src/Forms/inMtoArticulos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoArticulos.TfrmMtoArticulos.tvMovimientosPRECIO_MEDIO_MOV.Caption',
   'es-ES',
   'Precio MP',
   'src/Forms/inMtoArticulos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoArticulos.TfrmMtoArticulos.tvMovimientosCODIGO_ALMACEN_CONTRA_MOV',
     '.Caption'
   ),
   'es-ES',
   'Almacén Dest',
   'src/Forms/inMtoArticulos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoArticulos.TfrmMtoArticulos.tvMovimientosCODIGO_CLIENTE_MOV.Caption',
   'es-ES',
   'Código Cliente',
   'src/Forms/inMtoArticulos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoArticulos.TfrmMtoArticulos.tvMovimientosCODIGO_PROVEEDOR_MOV.Caption',
   'es-ES',
   'Código Prov',
   'src/Forms/inMtoArticulos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoArticulos.TfrmMtoArticulos.tvMovimientosESACTIVO_MOV.Caption',
   'es-ES',
   'Activo',
   'src/Forms/inMtoArticulos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoArticulos.TfrmMtoArticulos.btnExportarExcelStock.Caption',
   'es-ES',
   '&Exp Excel',
   'src/Forms/inMtoArticulos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoArticulos.TfrmMtoArticulos.tsOtros.Caption',
   'es-ES',
   '&0_Otros',
   'src/Forms/inMtoArticulos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoArticulos.TfrmMtoArticulos.lblUsuarioAlta.Caption',
   'es-ES',
   'Usuario Alta',
   'src/Forms/inMtoArticulos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoArticulos.TfrmMtoArticulos.lblInstanteAlta.Caption',
   'es-ES',
   'Instante Alta',
   'src/Forms/inMtoArticulos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoArticulos.TfrmMtoArticulos.lblInstanteModif.Caption',
   'es-ES',
   'Instante Modificación',
   'src/Forms/inMtoArticulos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoArticulos.TfrmMtoArticulos.lblUsuarioModif.Caption',
   'es-ES',
   'Us Últ. Modif.',
   'src/Forms/inMtoArticulos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoArticulos.TfrmMtoArticulos.chkACTIVO_ARTICULO.Caption',
   'es-ES',
   'Es Activo fijo --Es Maquinaria o Aperos-- (Sólo REAGP)',
   'src/Forms/inMtoArticulos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoArticulos.TfrmMtoArticulos.lblTextoLegal11.Caption',
   'es-ES',
   'Orden en Listados',
   'src/Forms/inMtoArticulos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoArticulos.TfrmMtoArticulos.btnNuevoArticulo.Caption',
   'es-ES',
   '&Nuevo Artículo',
   'src/Forms/inMtoArticulos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoArticulos.TfrmMtoArticulos.actFacturas.Caption',
   'es-ES',
   'actBorradores',
   'src/Forms/inMtoArticulos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoArticulos.TfrmMtoArticulos.actClientes.Caption',
   'es-ES',
   'actClientes',
   'src/Forms/inMtoArticulos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoArticulos.TfrmMtoArticulos.actProveedores.Caption',
   'es-ES',
   'actProveedores',
   'src/Forms/inMtoArticulos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoArticulos.TfrmMtoArticulos.actTarifas.Caption',
   'es-ES',
   'actTarifas',
   'src/Forms/inMtoArticulos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoArticulos.TfrmMtoArticulos.actFamilias.Caption',
   'es-ES',
   'actFamilias',
   'src/Forms/inMtoArticulos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoArticulos.TfrmMtoArticulos.miActivarColor.Caption',
   'es-ES',
   'Activar todos los SKU de este color',
   'src/Forms/inMtoArticulos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoArticulos.TfrmMtoArticulos.miDesactivarColor.Caption',
   'es-ES',
   'Desactivar todos los SKU de este color',
   'src/Forms/inMtoArticulos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAtributosBasicos.TfrmMtoAtributosBasicos.Caption',
   'es-ES',
   'Atributos básicos',
   'src/Forms/inMtoAtributosBasicos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAtributosBasicos.TfrmMtoAtributosBasicos.cxGrdDBTabPrinID_ATB.Caption',
   'es-ES',
   'ID',
   'src/Forms/inMtoAtributosBasicos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoAtributosBasicos.TfrmMtoAtributosBasicos.cxGrdDBTabPrinID_VA_ATB.',
     'Caption'
   ),
   'es-ES',
   'Atributo',
   'src/Forms/inMtoAtributosBasicos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoAtributosBasicos.TfrmMtoAtributosBasicos.cxGrdDBTabPrinID_VA_ATB.',
     'Properties.ListColumns[0].Caption'
   ),
   'es-ES',
   'Cód',
   'src/Forms/inMtoAtributosBasicos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoAtributosBasicos.TfrmMtoAtributosBasicos.cxGrdDBTabPrinID_VA_ATB.',
     'Properties.ListColumns[1].Caption'
   ),
   'es-ES',
   'Nombre',
   'src/Forms/inMtoAtributosBasicos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoAtributosBasicos.TfrmMtoAtributosBasicos.cxGrdDBTabPrinCODIGO_ATB',
     '.Caption'
   ),
   'es-ES',
   'Código',
   'src/Forms/inMtoAtributosBasicos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoAtributosBasicos.TfrmMtoAtributosBasicos.cxGrdDBTabPrinNOMBRE_ATB',
     '.Caption'
   ),
   'es-ES',
   'Nombre',
   'src/Forms/inMtoAtributosBasicos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoAtributosBasicos.TfrmMtoAtributosBasicos.cxGrdDBTabPrinDESCRIPCIO',
     'N_ATB.Caption'
   ),
   'es-ES',
   'Descripción',
   'src/Forms/inMtoAtributosBasicos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoAtributosBasicos.TfrmMtoAtributosBasicos.cxGrdDBTabPrinHEX_ATB.Ca',
     'ption'
   ),
   'es-ES',
   'Paleta',
   'src/Forms/inMtoAtributosBasicos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoAtributosBasicos.TfrmMtoAtributosBasicos.cxGrdDBTabPrinVALOR_NUM_',
     'ATB.Caption'
   ),
   'es-ES',
   'Valor',
   'src/Forms/inMtoAtributosBasicos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoAtributosBasicos.TfrmMtoAtributosBasicos.cxGrdDBTabPrinUNIDAD_ATB',
     '.Caption'
   ),
   'es-ES',
   'Unidad',
   'src/Forms/inMtoAtributosBasicos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoAtributosBasicos.TfrmMtoAtributosBasicos.cxGrdDBTabPrinORDEN_ATB.',
     'Caption'
   ),
   'es-ES',
   'Orden',
   'src/Forms/inMtoAtributosBasicos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoAtributosBasicos.TfrmMtoAtributosBasicos.cxGrdDBTabPrinESACTIVO_A',
     'TB.Caption'
   ),
   'es-ES',
   'Activo',
   'src/Forms/inMtoAtributosBasicos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAtributosBasicos.TfrmMtoAtributosBasicos.lblIdAtb.Caption',
   'es-ES',
   'ID',
   'src/Forms/inMtoAtributosBasicos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAtributosBasicos.TfrmMtoAtributosBasicos.lblIdVaAtb.Caption',
   'es-ES',
   'Atributo (CO, TAL, …)',
   'src/Forms/inMtoAtributosBasicos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoAtributosBasicos.TfrmMtoAtributosBasicos.cbbID_VA_ATB.Properties.',
     'ListColumns[0].Caption'
   ),
   'es-ES',
   'Cód',
   'src/Forms/inMtoAtributosBasicos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoAtributosBasicos.TfrmMtoAtributosBasicos.cbbID_VA_ATB.Properties.',
     'ListColumns[1].Caption'
   ),
   'es-ES',
   'Nombre',
   'src/Forms/inMtoAtributosBasicos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAtributosBasicos.TfrmMtoAtributosBasicos.lblCodigo.Caption',
   'es-ES',
   'Código',
   'src/Forms/inMtoAtributosBasicos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAtributosBasicos.TfrmMtoAtributosBasicos.lblNombre.Caption',
   'es-ES',
   'Nombre',
   'src/Forms/inMtoAtributosBasicos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAtributosBasicos.TfrmMtoAtributosBasicos.lblDescripcion.Caption',
   'es-ES',
   'Descripción',
   'src/Forms/inMtoAtributosBasicos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAtributosBasicos.TfrmMtoAtributosBasicos.lblHex.Caption',
   'es-ES',
   'Paleta (HEX)',
   'src/Forms/inMtoAtributosBasicos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAtributosBasicos.TfrmMtoAtributosBasicos.lblValor.Caption',
   'es-ES',
   'Valor numérico',
   'src/Forms/inMtoAtributosBasicos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAtributosBasicos.TfrmMtoAtributosBasicos.lblUnidad.Caption',
   'es-ES',
   'Unidad',
   'src/Forms/inMtoAtributosBasicos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAtributosBasicos.TfrmMtoAtributosBasicos.lblOrden.Caption',
   'es-ES',
   'Orden',
   'src/Forms/inMtoAtributosBasicos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAtributosBasicos.TfrmMtoAtributosBasicos.chkESACTIVO_ATB.Caption',
   'es-ES',
   'Activo',
   'src/Forms/inMtoAtributosBasicos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAtributosConjuntos.TfrmMtoAtributosConjuntos.Caption',
   'es-ES',
   'Colecciones de Atributos',
   'src/Forms/inMtoAtributosConjuntos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoAtributosConjuntos.TfrmMtoAtributosConjuntos.cxGrdDBTabPrinID_AC.',
     'Caption'
   ),
   'es-ES',
   'ID Conjunto',
   'src/Forms/inMtoAtributosConjuntos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoAtributosConjuntos.TfrmMtoAtributosConjuntos.cxGrdDBTabPrinNOMBRE',
     '_AC.Caption'
   ),
   'es-ES',
   'Nombre',
   'src/Forms/inMtoAtributosConjuntos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoAtributosConjuntos.TfrmMtoAtributosConjuntos.cxGrdDBTabPrinID_VAR',
     '_AC.Caption'
   ),
   'es-ES',
   'Variación',
   'src/Forms/inMtoAtributosConjuntos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoAtributosConjuntos.TfrmMtoAtributosConjuntos.cxGrdDBTabPrinID_VAR',
     '_AC.Properties.ListColumns[0].Caption'
   ),
   'es-ES',
   'Código',
   'src/Forms/inMtoAtributosConjuntos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoAtributosConjuntos.TfrmMtoAtributosConjuntos.cxGrdDBTabPrinID_VAR',
     '_AC.Properties.ListColumns[1].Caption'
   ),
   'es-ES',
   'Nombre',
   'src/Forms/inMtoAtributosConjuntos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoAtributosConjuntos.TfrmMtoAtributosConjuntos.cxGrdDBTabPrinID_VA_',
     'AC.Caption'
   ),
   'es-ES',
   'Atributo',
   'src/Forms/inMtoAtributosConjuntos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoAtributosConjuntos.TfrmMtoAtributosConjuntos.cxGrdDBTabPrinID_VA_',
     'AC.Properties.ListColumns[0].Caption'
   ),
   'es-ES',
   'Variación',
   'src/Forms/inMtoAtributosConjuntos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoAtributosConjuntos.TfrmMtoAtributosConjuntos.cxGrdDBTabPrinID_VA_',
     'AC.Properties.ListColumns[1].Caption'
   ),
   'es-ES',
   'Código',
   'src/Forms/inMtoAtributosConjuntos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoAtributosConjuntos.TfrmMtoAtributosConjuntos.cxGrdDBTabPrinID_VA_',
     'AC.Properties.ListColumns[2].Caption'
   ),
   'es-ES',
   'Nombre',
   'src/Forms/inMtoAtributosConjuntos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoAtributosConjuntos.TfrmMtoAtributosConjuntos.cxGrdDBTabPrinID_VA_',
     'AC.Properties.ListColumns[3].Caption'
   ),
   'es-ES',
   'Orden',
   'src/Forms/inMtoAtributosConjuntos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoAtributosConjuntos.TfrmMtoAtributosConjuntos.cxGrdDBTabPrinESACTI',
     'VO_AC.Caption'
   ),
   'es-ES',
   'Activo',
   'src/Forms/inMtoAtributosConjuntos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoAtributosConjuntos.TfrmMtoAtributosConjuntos.cxGrdDBTabPrinINSTAN',
     'TE_ALTA.Caption'
   ),
   'es-ES',
   'Instante Alta',
   'src/Forms/inMtoAtributosConjuntos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoAtributosConjuntos.TfrmMtoAtributosConjuntos.cxGrdDBTabPrinINSTAN',
     'TE_MODIF.Caption'
   ),
   'es-ES',
   'Instante Modif',
   'src/Forms/inMtoAtributosConjuntos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoAtributosConjuntos.TfrmMtoAtributosConjuntos.cxGrdDBTabPrinUSUARI',
     'O_ALTA.Caption'
   ),
   'es-ES',
   'Usuario Alta',
   'src/Forms/inMtoAtributosConjuntos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoAtributosConjuntos.TfrmMtoAtributosConjuntos.cxGrdDBTabPrinUSUARI',
     'O_MODIF.Caption'
   ),
   'es-ES',
   'Usuario Modif',
   'src/Forms/inMtoAtributosConjuntos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAtributosConjuntos.TfrmMtoAtributosConjuntos.lblNombre.Caption',
   'es-ES',
   'Nombre',
   'src/Forms/inMtoAtributosConjuntos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAtributosConjuntos.TfrmMtoAtributosConjuntos.chkESACTIVO_AC.Caption',
   'es-ES',
   'Activo',
   'src/Forms/inMtoAtributosConjuntos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAtributosConjuntos.TfrmMtoAtributosConjuntos.lblIdVar.Caption',
   'es-ES',
   'Variación',
   'src/Forms/inMtoAtributosConjuntos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoAtributosConjuntos.TfrmMtoAtributosConjuntos.cbbID_VAR_AC.Propert',
     'ies.ListColumns[0].Caption'
   ),
   'es-ES',
   'Código',
   'src/Forms/inMtoAtributosConjuntos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoAtributosConjuntos.TfrmMtoAtributosConjuntos.cbbID_VAR_AC.Propert',
     'ies.ListColumns[1].Caption'
   ),
   'es-ES',
   'Nombre',
   'src/Forms/inMtoAtributosConjuntos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAtributosConjuntos.TfrmMtoAtributosConjuntos.lblIdVa.Caption',
   'es-ES',
   'Atributo',
   'src/Forms/inMtoAtributosConjuntos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoAtributosConjuntos.TfrmMtoAtributosConjuntos.cbbID_VA_AC.Properti',
     'es.ListColumns[0].Caption'
   ),
   'es-ES',
   'Variación',
   'src/Forms/inMtoAtributosConjuntos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoAtributosConjuntos.TfrmMtoAtributosConjuntos.cbbID_VA_AC.Properti',
     'es.ListColumns[1].Caption'
   ),
   'es-ES',
   'Código',
   'src/Forms/inMtoAtributosConjuntos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoAtributosConjuntos.TfrmMtoAtributosConjuntos.cbbID_VA_AC.Properti',
     'es.ListColumns[2].Caption'
   ),
   'es-ES',
   'Nombre',
   'src/Forms/inMtoAtributosConjuntos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoAtributosConjuntos.TfrmMtoAtributosConjuntos.cbbID_VA_AC.Properti',
     'es.ListColumns[3].Caption'
   ),
   'es-ES',
   'Orden',
   'src/Forms/inMtoAtributosConjuntos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAtributosConjuntos.TfrmMtoAtributosConjuntos.lblIdAc.Caption',
   'es-ES',
   'ID Conjunto',
   'src/Forms/inMtoAtributosConjuntos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAtributosConjuntos.TfrmMtoAtributosConjuntos.tsValores.Caption',
   'es-ES',
   '&1_Valores',
   'src/Forms/inMtoAtributosConjuntos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoAtributosConjuntos.TfrmMtoAtributosConjuntos.tvValoresID_AC_ACD.C',
     'aption'
   ),
   'es-ES',
   'ID Conjunto',
   'src/Forms/inMtoAtributosConjuntos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoAtributosConjuntos.TfrmMtoAtributosConjuntos.tvValoresID_AV_ACD.C',
     'aption'
   ),
   'es-ES',
   'Valor',
   'src/Forms/inMtoAtributosConjuntos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoAtributosConjuntos.TfrmMtoAtributosConjuntos.tvValoresID_AV_ACD.P',
     'roperties.ListColumns[0].Caption'
   ),
   'es-ES',
   'Cód',
   'src/Forms/inMtoAtributosConjuntos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoAtributosConjuntos.TfrmMtoAtributosConjuntos.tvValoresID_AV_ACD.P',
     'roperties.ListColumns[1].Caption'
   ),
   'es-ES',
   'Pos',
   'src/Forms/inMtoAtributosConjuntos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoAtributosConjuntos.TfrmMtoAtributosConjuntos.tvValoresID_AV_ACD.P',
     'roperties.ListColumns[2].Caption'
   ),
   'es-ES',
   'Valor',
   'src/Forms/inMtoAtributosConjuntos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoAtributosConjuntos.TfrmMtoAtributosConjuntos.tvValoresID_AV_ACD.P',
     'roperties.ListColumns[3].Caption'
   ),
   'es-ES',
   'Descripción',
   'src/Forms/inMtoAtributosConjuntos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoAtributosConjuntos.TfrmMtoAtributosConjuntos.tvValoresORDEN_ACD.C',
     'aption'
   ),
   'es-ES',
   'Orden',
   'src/Forms/inMtoAtributosConjuntos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoAtributosConjuntos.TfrmMtoAtributosConjuntos.tvValoresID_ATB_ACD.',
     'Caption'
   ),
   'es-ES',
   'Atributo básico',
   'src/Forms/inMtoAtributosConjuntos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoAtributosConjuntos.TfrmMtoAtributosConjuntos.tvValoresID_ATB_ACD.',
     'Properties.ListColumns[0].Caption'
   ),
   'es-ES',
   'Código',
   'src/Forms/inMtoAtributosConjuntos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoAtributosConjuntos.TfrmMtoAtributosConjuntos.tvValoresID_ATB_ACD.',
     'Properties.ListColumns[1].Caption'
   ),
   'es-ES',
   'Nombre',
   'src/Forms/inMtoAtributosConjuntos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoAtributosConjuntos.TfrmMtoAtributosConjuntos.tvValoresID_ATB_ACD.',
     'Properties.ListColumns[2].Caption'
   ),
   'es-ES',
   'Paleta',
   'src/Forms/inMtoAtributosConjuntos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoAtributosConjuntos.TfrmMtoAtributosConjuntos.tvValoresID_ATB_ACD.',
     'Properties.ListColumns[3].Caption'
   ),
   'es-ES',
   'Valor',
   'src/Forms/inMtoAtributosConjuntos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoAtributosConjuntos.TfrmMtoAtributosConjuntos.tvValoresID_ATB_ACD.',
     'Properties.ListColumns[4].Caption'
   ),
   'es-ES',
   'Ud',
   'src/Forms/inMtoAtributosConjuntos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAtributosConjuntos.TfrmMtoAtributosConjuntos.tsArticulos.Caption',
   'es-ES',
   '&2_Artículos',
   'src/Forms/inMtoAtributosConjuntos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoAtributosConjuntos.TfrmMtoAtributosConjuntos.tvArticulosCODIGO_AR',
     'T_ART.Caption'
   ),
   'es-ES',
   'Código Artículo',
   'src/Forms/inMtoAtributosConjuntos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoAtributosConjuntos.TfrmMtoAtributosConjuntos.tvArticulosDESCRIPCI',
     'ON_ART.Caption'
   ),
   'es-ES',
   'Descripción',
   'src/Forms/inMtoAtributosConjuntos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoAtributosConjuntos.TfrmMtoAtributosConjuntos.tvArticulosESACTIVO_',
     'ART.Caption'
   ),
   'es-ES',
   'Activo',
   'src/Forms/inMtoAtributosConjuntos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoAtributosConjuntos.TfrmMtoAtributosConjuntos.tvArticulosCODIGO_FA',
     'M_ART.Caption'
   ),
   'es-ES',
   'Código Familia',
   'src/Forms/inMtoAtributosConjuntos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoAtributosConjuntos.TfrmMtoAtributosConjuntos.tvArticulosNOMBRE_FA',
     'M_FAM.Caption'
   ),
   'es-ES',
   'Familia',
   'src/Forms/inMtoAtributosConjuntos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAtributosConjuntos.TfrmMtoAtributosConjuntos.tsAuditoria.Caption',
   'es-ES',
   '&3_Otros',
   'src/Forms/inMtoAtributosConjuntos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAtributosConjuntos.TfrmMtoAtributosConjuntos.lblUsuarioAlta.Caption',
   'es-ES',
   'Usuario Alta',
   'src/Forms/inMtoAtributosConjuntos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAtributosConjuntos.TfrmMtoAtributosConjuntos.lblInstanteAlta.Caption',
   'es-ES',
   'Instante Alta',
   'src/Forms/inMtoAtributosConjuntos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAtributosConjuntos.TfrmMtoAtributosConjuntos.lblUsuarioModif.Caption',
   'es-ES',
   'Usuario Modificación',
   'src/Forms/inMtoAtributosConjuntos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAtributosConjuntos.TfrmMtoAtributosConjuntos.lblInstanteModif.Caption',
   'es-ES',
   'Instante Modificación',
   'src/Forms/inMtoAtributosConjuntos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoAtributosConjuntos.TfrmMtoAtributosConjuntos.actArticulo.Caption',
   'es-ES',
   'Articulo',
   'src/Forms/inMtoAtributosConjuntos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoBusquedaDatos.TfrmMtoBusquedaDatos.Caption',
   'es-ES',
   'Búsqueda de datos de artículos (Ctrl+E)',
   'src/Forms/inMtoBusquedaDatos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoBusquedaDatos.TfrmMtoBusquedaDatos.lblCampo.Caption',
   'es-ES',
   'Buscar por',
   'src/Forms/inMtoBusquedaDatos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoBusquedaDatos.TfrmMtoBusquedaDatos.lblValor.Caption',
   'es-ES',
   'Texto a buscar',
   'src/Forms/inMtoBusquedaDatos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoBusquedaDatos.TfrmMtoBusquedaDatos.lblCoincidencia.Caption',
   'es-ES',
   'Coincidencia',
   'src/Forms/inMtoBusquedaDatos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoBusquedaDatos.TfrmMtoBusquedaDatos.chkDistinguirMayusculas.Caption',
   'es-ES',
   'Mayúsculas/minúsculas',
   'src/Forms/inMtoBusquedaDatos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoBusquedaDatos.TfrmMtoBusquedaDatos.btnBuscar.Caption',
   'es-ES',
   '&Buscar',
   'src/Forms/inMtoBusquedaDatos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoBusquedaDatos.TfrmMtoBusquedaDatos.btnLimpiar.Caption',
   'es-ES',
   '&Limpiar',
   'src/Forms/inMtoBusquedaDatos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoBusquedaDatos.TfrmMtoBusquedaDatos.lblEstado.Caption',
   'es-ES',
   'Estado',
   'src/Forms/inMtoBusquedaDatos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoBusquedaDatos.TfrmMtoBusquedaDatos.lblStock.Caption',
   'es-ES',
   'Existencias',
   'src/Forms/inMtoBusquedaDatos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoBusquedaDatos.TfrmMtoBusquedaDatos.lblLimite.Caption',
   'es-ES',
   'Máximo de filas',
   'src/Forms/inMtoBusquedaDatos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoBusquedaDatos.TfrmMtoBusquedaDatos.lblAyuda.Caption',
   'es-ES',
   'Los filtros previos reducen la carga antes de consultar SKU.',
   'src/Forms/inMtoBusquedaDatos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoBusquedaDatos.TfrmMtoBusquedaDatos.btnPerfiles.Caption',
   'es-ES',
   '&Perfiles...',
   'src/Forms/inMtoBusquedaDatos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoBusquedaDatos.TfrmMtoBusquedaDatos.lblFamilia.Caption',
   'es-ES',
   'Familia (opcional)',
   'src/Forms/inMtoBusquedaDatos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoBusquedaDatos.TfrmMtoBusquedaDatos.lblProveedor.Caption',
   'es-ES',
   'Proveedor (opcional)',
   'src/Forms/inMtoBusquedaDatos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoBusquedaDatos.TfrmMtoBusquedaDatos.cbbProveedor.Properties.ListCo',
     'lumns[0].Caption'
   ),
   'es-ES',
   'Código',
   'src/Forms/inMtoBusquedaDatos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoBusquedaDatos.TfrmMtoBusquedaDatos.cbbProveedor.Properties.ListCo',
     'lumns[1].Caption'
   ),
   'es-ES',
   'Nombre',
   'src/Forms/inMtoBusquedaDatos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoBusquedaDatos.TfrmMtoBusquedaDatos.lblTemporada.Caption',
   'es-ES',
   'Temporada (opcional)',
   'src/Forms/inMtoBusquedaDatos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoBusquedaDatos.TfrmMtoBusquedaDatos.btnAceptar.Caption',
   'es-ES',
   '&Abrir artículo (F12)',
   'src/Forms/inMtoBusquedaDatos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoBusquedaDatos.TfrmMtoBusquedaDatos.btnCancelar1.Caption',
   'es-ES',
   '&Cerrar (ESC)',
   'src/Forms/inMtoBusquedaDatos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoBusquedaDatos.TfrmMtoBusquedaDatos.lblResultados.Caption',
   'es-ES',
   '0 SKU encontrados',
   'src/Forms/inMtoBusquedaDatos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoBusquedaDatos.TfrmMtoBusquedaDatos.btnOcultar.Caption',
   'es-ES',
   'Ocultar criterios',
   'src/Forms/inMtoBusquedaDatos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema')
ON DUPLICATE KEY UPDATE
  `TEXTO_TRAD` = VALUES(`TEXTO_TRAD`),
  `CONTEXTO_TRAD` = VALUES(`CONTEXTO_TRAD`),
  `ESACTIVO_TRAD` = VALUES(`ESACTIVO_TRAD`),
  `INSTANTE_MODIF` = CURRENT_TIMESTAMP,
  `USUARIO_MODIF` = VALUES(`USUARIO_ALTA`);
