-- Catálogo de textos españoles extraídos de los DFM.
-- Generado por generar_traducciones_dfm.ps1.
INSERT INTO `fza_traducciones` (
  `CLAVE_TRAD`, `IDIOMA_TRAD`, `TEXTO_TRAD`, `CONTEXTO_TRAD`,
  `ESACTIVO_TRAD`, `INSTANTE_ALTA`, `USUARIO_ALTA`
) VALUES
  ('inMtoMovimientosAlmacen.TfrmMtoMovimientosAlmacen.Caption',
   'es-ES',
   'Movimientos de Almacén',
   'src/Forms/inMtoMovimientosAlmacen.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoMovimientosAlmacen.TfrmMtoMovimientosAlmacen.cxGrdDBTabPrinNUMERO',
     '_MOV.Caption'
   ),
   'es-ES',
   'Número Mov.',
   'src/Forms/inMtoMovimientosAlmacen.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoMovimientosAlmacen.TfrmMtoMovimientosAlmacen.cxGrdDBTabPrinFECHA_',
     'MOV.Caption'
   ),
   'es-ES',
   'Fecha',
   'src/Forms/inMtoMovimientosAlmacen.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoMovimientosAlmacen.TfrmMtoMovimientosAlmacen.cxGrdDBTabPrinTIPO_M',
     'OVIMIENTO_MOV.Caption'
   ),
   'es-ES',
   'E/S',
   'src/Forms/inMtoMovimientosAlmacen.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoMovimientosAlmacen.TfrmMtoMovimientosAlmacen.cxGrdDBTabPrinTIPO_D',
     'OC_MOV.Caption'
   ),
   'es-ES',
   'Tipo Doc.',
   'src/Forms/inMtoMovimientosAlmacen.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoMovimientosAlmacen.TfrmMtoMovimientosAlmacen.cxGrdDBTabPrinSERIE_',
     'DOC_MOV.Caption'
   ),
   'es-ES',
   'Serie Doc.',
   'src/Forms/inMtoMovimientosAlmacen.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoMovimientosAlmacen.TfrmMtoMovimientosAlmacen.cxGrdDBTabPrinNRO_DO',
     'C_MOV.Caption'
   ),
   'es-ES',
   'Nro. Doc.',
   'src/Forms/inMtoMovimientosAlmacen.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoMovimientosAlmacen.TfrmMtoMovimientosAlmacen.cxGrdDBTabPrinLINEA_',
     'MOV.Caption'
   ),
   'es-ES',
   'Línea',
   'src/Forms/inMtoMovimientosAlmacen.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoMovimientosAlmacen.TfrmMtoMovimientosAlmacen.cxGrdDBTabPrinCODIGO',
     '_EMPRESA_MOV.Caption'
   ),
   'es-ES',
   'Empresa',
   'src/Forms/inMtoMovimientosAlmacen.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoMovimientosAlmacen.TfrmMtoMovimientosAlmacen.cxGrdDBTabPrinCODIGO',
     '_ALMACEN_MOV.Caption'
   ),
   'es-ES',
   'Almacén',
   'src/Forms/inMtoMovimientosAlmacen.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoMovimientosAlmacen.TfrmMtoMovimientosAlmacen.cxGrdDBTabPrinCODIGO',
     '_ARTICULO_MOV.Caption'
   ),
   'es-ES',
   'Artículo',
   'src/Forms/inMtoMovimientosAlmacen.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoMovimientosAlmacen.TfrmMtoMovimientosAlmacen.cxGrdDBTabPrinCODIGO',
     '_UNIDAD_MOV.Caption'
   ),
   'es-ES',
   'SKU',
   'src/Forms/inMtoMovimientosAlmacen.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoMovimientosAlmacen.TfrmMtoMovimientosAlmacen.cxGrdDBTabPrinDESCRI',
     'PCION_ARTICULO_MOV.Caption'
   ),
   'es-ES',
   'Descripción',
   'src/Forms/inMtoMovimientosAlmacen.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoMovimientosAlmacen.TfrmMtoMovimientosAlmacen.cxGrdDBTabPrinCANTID',
     'AD_MOV.Caption'
   ),
   'es-ES',
   'Cantidad',
   'src/Forms/inMtoMovimientosAlmacen.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoMovimientosAlmacen.TfrmMtoMovimientosAlmacen.cxGrdDBTabPrinPRECIO',
     '_COSTE_UNITARIO_MOV.Caption'
   ),
   'es-ES',
   'Coste Unit.',
   'src/Forms/inMtoMovimientosAlmacen.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoMovimientosAlmacen.TfrmMtoMovimientosAlmacen.cxGrdDBTabPrinTOTAL_',
     'COSTE_MOV.Caption'
   ),
   'es-ES',
   'Total Coste',
   'src/Forms/inMtoMovimientosAlmacen.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoMovimientosAlmacen.TfrmMtoMovimientosAlmacen.cxGrdDBTabPrinPRECIO',
     '_MEDIO_MOV.Caption'
   ),
   'es-ES',
   'Precio Medio',
   'src/Forms/inMtoMovimientosAlmacen.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoMovimientosAlmacen.TfrmMtoMovimientosAlmacen.cxGrdDBTabPrinCODIGO',
     '_ALMACEN_CONTRA_MOV.Caption'
   ),
   'es-ES',
   'Almacén Contra',
   'src/Forms/inMtoMovimientosAlmacen.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoMovimientosAlmacen.TfrmMtoMovimientosAlmacen.cxGrdDBTabPrinCODIGO',
     '_CLIENTE_MOV.Caption'
   ),
   'es-ES',
   'Cliente',
   'src/Forms/inMtoMovimientosAlmacen.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoMovimientosAlmacen.TfrmMtoMovimientosAlmacen.cxGrdDBTabPrinCODIGO',
     '_PROVEEDOR_MOV.Caption'
   ),
   'es-ES',
   'Proveedor',
   'src/Forms/inMtoMovimientosAlmacen.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoMovimientosAlmacen.TfrmMtoMovimientosAlmacen.cxGrdDBTabPrinESACTI',
     'VO_MOV.Caption'
   ),
   'es-ES',
   'Activo',
   'src/Forms/inMtoMovimientosAlmacen.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoMovimientosAlmacen.TfrmMtoMovimientosAlmacen.cxGrdDBTabPrinTIPO_D',
     'OC_REF_MOV.Caption'
   ),
   'es-ES',
   'Tipo Ref.',
   'src/Forms/inMtoMovimientosAlmacen.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoMovimientosAlmacen.TfrmMtoMovimientosAlmacen.cxGrdDBTabPrinSERIE_',
     'DOC_REF_MOV.Caption'
   ),
   'es-ES',
   'Serie Ref.',
   'src/Forms/inMtoMovimientosAlmacen.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoMovimientosAlmacen.TfrmMtoMovimientosAlmacen.cxGrdDBTabPrinNRO_DO',
     'C_REF_MOV.Caption'
   ),
   'es-ES',
   'Nro. Ref.',
   'src/Forms/inMtoMovimientosAlmacen.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoMovimientosAlmacen.TfrmMtoMovimientosAlmacen.cxGrdDBTabPrinLINEA_',
     'REF_MOV.Caption'
   ),
   'es-ES',
   'Línea Ref.',
   'src/Forms/inMtoMovimientosAlmacen.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoMovimientosAlmacen.TfrmMtoMovimientosAlmacen.cxGrdDBTabPrinLOTE_M',
     'OV.Caption'
   ),
   'es-ES',
   'Lote',
   'src/Forms/inMtoMovimientosAlmacen.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoMovimientosAlmacen.TfrmMtoMovimientosAlmacen.cxGrdDBTabPrinFECHA_',
     'CADUCIDAD_MOV.Caption'
   ),
   'es-ES',
   'F. Caducidad',
   'src/Forms/inMtoMovimientosAlmacen.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoMovimientosAlmacen.TfrmMtoMovimientosAlmacen.cxGrdDBTabPrinINSTAN',
     'TEALTA.Caption'
   ),
   'es-ES',
   'Instante Alta',
   'src/Forms/inMtoMovimientosAlmacen.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoMovimientosAlmacen.TfrmMtoMovimientosAlmacen.cxGrdDBTabPrinINSTAN',
     'TEMODIF.Caption'
   ),
   'es-ES',
   'Instante Modif',
   'src/Forms/inMtoMovimientosAlmacen.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoMovimientosAlmacen.TfrmMtoMovimientosAlmacen.cxGrdDBTabPrinUSUARI',
     'OALTA.Caption'
   ),
   'es-ES',
   'Usuario Alta',
   'src/Forms/inMtoMovimientosAlmacen.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoMovimientosAlmacen.TfrmMtoMovimientosAlmacen.cxGrdDBTabPrinUSUARI',
     'OMODIF.Caption'
   ),
   'es-ES',
   'Usuario Modif',
   'src/Forms/inMtoMovimientosAlmacen.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoMovimientosAlmacen.TfrmMtoMovimientosAlmacen.btnToggleFiltros.Caption',
   'es-ES',
   '▶  Filtros de carga',
   'src/Forms/inMtoMovimientosAlmacen.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoMovimientosAlmacen.TfrmMtoMovimientosAlmacen.lblFiltroAnyo.Caption',
   'es-ES',
   'Años:',
   'src/Forms/inMtoMovimientosAlmacen.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoMovimientosAlmacen.TfrmMtoMovimientosAlmacen.lblFiltroAlmacen.Caption',
   'es-ES',
   'Almacenes:',
   'src/Forms/inMtoMovimientosAlmacen.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoMovimientosAlmacen.TfrmMtoMovimientosAlmacen.btnIraArticulo.Caption',
   'es-ES',
   '&Ir a Artículo',
   'src/Forms/inMtoMovimientosAlmacen.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoMovimientosAlmacen.TfrmMtoMovimientosAlmacen.Action1.Caption',
   'es-ES',
   'Artículos',
   'src/Forms/inMtoMovimientosAlmacen.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPaises.TfrmMtoPaises.Caption',
   'es-ES',
   'Paises',
   'src/Forms/inMtoPaises.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPaises.TfrmMtoPaises.dbcGrdDBTabPrinCOD_PAIS.Caption',
   'es-ES',
   'Código Pais',
   'src/Forms/inMtoPaises.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPaises.TfrmMtoPaises.dbcGrdDBTabPrinCOD_PAIS_ALPHA2.Caption',
   'es-ES',
   'Código Alpha2',
   'src/Forms/inMtoPaises.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPaises.TfrmMtoPaises.dbcGrdDBTabPrinCOD_PAIS_ALPHA3.Caption',
   'es-ES',
   'Código Alpha3',
   'src/Forms/inMtoPaises.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPaises.TfrmMtoPaises.dbcGrdDBTabPrinNOMBRE_SPA_PAIS.Caption',
   'es-ES',
   'Nombre Español Pais',
   'src/Forms/inMtoPaises.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPaises.TfrmMtoPaises.dbcGrdDBTabPrinNOMBRE_ENG_PAIS.Caption',
   'es-ES',
   'Nombre Inglés Pais',
   'src/Forms/inMtoPaises.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPaises.TfrmMtoPaises.dbcGrdDBTabPrinESMIEMBRO_UE_PAIS.Caption',
   'es-ES',
   'Miembro UE',
   'src/Forms/inMtoPaises.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPaises.TfrmMtoPaises.dbcGrdDBTabPrinORDEN_PAIS.Caption',
   'es-ES',
   'Orden en Listados',
   'src/Forms/inMtoPaises.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPedidos.TfrmMtoPedidos.Caption',
   'es-ES',
   'Mantenimiento de Pedidos',
   'src/Forms/inMtoPedidos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPedidos.TfrmMtoPedidos.dbcGrdPedNUMERO_PED.Caption',
   'es-ES',
   'Nro Pedido',
   'src/Forms/inMtoPedidos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPedidos.TfrmMtoPedidos.dbcGrdPedSERIE_PED.Caption',
   'es-ES',
   'Serie',
   'src/Forms/inMtoPedidos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPedidos.TfrmMtoPedidos.dbcGrdPedFECHA_PED.Caption',
   'es-ES',
   'Fecha',
   'src/Forms/inMtoPedidos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPedidos.TfrmMtoPedidos.dbcGrdPedESTADO_PED.Caption',
   'es-ES',
   'Estado',
   'src/Forms/inMtoPedidos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPedidos.TfrmMtoPedidos.dbcGrdPedCODIGO_EMP_PED.Caption',
   'es-ES',
   'Empresa',
   'src/Forms/inMtoPedidos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPedidos.TfrmMtoPedidos.dbcGrdPedRSEMP_PED.Caption',
   'es-ES',
   'Razón Social Empresa',
   'src/Forms/inMtoPedidos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPedidos.TfrmMtoPedidos.dbcGrdPedCODIGO_CLI_PED.Caption',
   'es-ES',
   'Cliente',
   'src/Forms/inMtoPedidos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPedidos.TfrmMtoPedidos.dbcGrdPedRSCLI_PED.Caption',
   'es-ES',
   'Razón Social Cliente',
   'src/Forms/inMtoPedidos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPedidos.TfrmMtoPedidos.dbcGrdPedIDPS_PED.Caption',
   'es-ES',
   'ID PrestaShop',
   'src/Forms/inMtoPedidos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPedidos.TfrmMtoPedidos.dbcGrdPedREFPS_PED.Caption',
   'es-ES',
   'Ref. PrestaShop',
   'src/Forms/inMtoPedidos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPedidos.TfrmMtoPedidos.dbcGrdPedFECHAPS_PED.Caption',
   'es-ES',
   'Fecha PrestaShop',
   'src/Forms/inMtoPedidos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPedidos.TfrmMtoPedidos.dbcGrdPedTOTAL_LIQUIDO_PED.Caption',
   'es-ES',
   'Total',
   'src/Forms/inMtoPedidos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPedidos.TfrmMtoPedidos.tsCabecera.Caption',
   'es-ES',
   'Cabecera',
   'src/Forms/inMtoPedidos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPedidos.TfrmMtoPedidos.lblNroPedido.Caption',
   'es-ES',
   'Número',
   'src/Forms/inMtoPedidos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPedidos.TfrmMtoPedidos.lblSerie.Caption',
   'es-ES',
   'Serie',
   'src/Forms/inMtoPedidos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPedidos.TfrmMtoPedidos.lblFecha.Caption',
   'es-ES',
   'Fecha',
   'src/Forms/inMtoPedidos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPedidos.TfrmMtoPedidos.lblFechaEntrega.Caption',
   'es-ES',
   'Fecha entrega',
   'src/Forms/inMtoPedidos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPedidos.TfrmMtoPedidos.lblEstado.Caption',
   'es-ES',
   'Estado',
   'src/Forms/inMtoPedidos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPedidos.TfrmMtoPedidos.lblIDPS.Caption',
   'es-ES',
   'ID PrestaShop',
   'src/Forms/inMtoPedidos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPedidos.TfrmMtoPedidos.lblRefPS.Caption',
   'es-ES',
   'Ref. PrestaShop',
   'src/Forms/inMtoPedidos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPedidos.TfrmMtoPedidos.lblCodigoEmpresa.Caption',
   'es-ES',
   'Empresa Emisora',
   'src/Forms/inMtoPedidos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPedidos.TfrmMtoPedidos.lblCodigoAlmacen.Caption',
   'es-ES',
   'Almacén salida',
   'src/Forms/inMtoPedidos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoPedidos.TfrmMtoPedidos.cbbCODIGO_ALM_PED.Properties.ListColumns[0',
     '].Caption'
   ),
   'es-ES',
   'Código',
   'src/Forms/inMtoPedidos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoPedidos.TfrmMtoPedidos.cbbCODIGO_ALM_PED.Properties.ListColumns[1',
     '].Caption'
   ),
   'es-ES',
   'Almacén',
   'src/Forms/inMtoPedidos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoPedidos.TfrmMtoPedidos.cbbCODIGO_ALM_PED.Properties.ListColumns[2',
     '].Caption'
   ),
   'es-ES',
   'Empresa',
   'src/Forms/inMtoPedidos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPedidos.TfrmMtoPedidos.lblCodigoCliente.Caption',
   'es-ES',
   'Cliente',
   'src/Forms/inMtoPedidos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPedidos.TfrmMtoPedidos.lblTarifaPedido.Caption',
   'es-ES',
   'Tarifa',
   'src/Forms/inMtoPedidos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoPedidos.TfrmMtoPedidos.cbbTarifaPedido.Properties.ListColumns[0].',
     'Caption'
   ),
   'es-ES',
   'Tarifa',
   'src/Forms/inMtoPedidos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoPedidos.TfrmMtoPedidos.cbbTarifaPedido.Properties.ListColumns[1].',
     'Caption'
   ),
   'es-ES',
   'Imp. incl.',
   'src/Forms/inMtoPedidos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPedidos.TfrmMtoPedidos.chkTarifaImpuestosIncluidosPedido.Caption',
   'es-ES',
   'Imp. incl.',
   'src/Forms/inMtoPedidos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPedidos.TfrmMtoPedidos.tsEmpresa.Caption',
   'es-ES',
   'Empresa',
   'src/Forms/inMtoPedidos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPedidos.TfrmMtoPedidos.grpEmpresa.Caption',
   'es-ES',
   'Datos Empresa Emisora',
   'src/Forms/inMtoPedidos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPedidos.TfrmMtoPedidos.lblNIFEmp.Caption',
   'es-ES',
   'NIF',
   'src/Forms/inMtoPedidos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPedidos.TfrmMtoPedidos.lblMovEmp.Caption',
   'es-ES',
   'Móvil',
   'src/Forms/inMtoPedidos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPedidos.TfrmMtoPedidos.lblEmailEmp.Caption',
   'es-ES',
   'Email',
   'src/Forms/inMtoPedidos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPedidos.TfrmMtoPedidos.tsDatosCliente.Caption',
   'es-ES',
   'Cliente Fiscal',
   'src/Forms/inMtoPedidos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPedidos.TfrmMtoPedidos.grpClienteFiscal.Caption',
   'es-ES',
   'Datos Cliente Fiscal',
   'src/Forms/inMtoPedidos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPedidos.TfrmMtoPedidos.tsEnvio.Caption',
   'es-ES',
   'Dirección Envío',
   'src/Forms/inMtoPedidos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPedidos.TfrmMtoPedidos.grpClienteEnvio.Caption',
   'es-ES',
   'Datos Cliente Envío',
   'src/Forms/inMtoPedidos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPedidos.TfrmMtoPedidos.btnAnadirLinea.Caption',
   'es-ES',
   'Añadir línea',
   'src/Forms/inMtoPedidos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPedidos.TfrmMtoPedidos.btnBorrarLinea.Caption',
   'es-ES',
   'Borrar línea',
   'src/Forms/inMtoPedidos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPedidos.TfrmMtoPedidos.btnEntregarTodo.Caption',
   'es-ES',
   'Marcar todo entregado',
   'src/Forms/inMtoPedidos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPedidos.TfrmMtoPedidos.btnCrearAlbaran.Caption',
   'es-ES',
   'Crear albarán',
   'src/Forms/inMtoPedidos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPedidos.TfrmMtoPedidos.btnImportarPS.Caption',
   'es-ES',
   'Importar de PrestaShop',
   'src/Forms/inMtoPedidos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPedidos.TfrmMtoPedidos.btnExpandirFilas.Caption',
   'es-ES',
   'Expandir Filas',
   'src/Forms/inMtoPedidos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPedidos.TfrmMtoPedidos.tsLineasPedido.Caption',
   'es-ES',
   'Líneas Pedido',
   'src/Forms/inMtoPedidos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPedidos.TfrmMtoPedidos.cxgrdcPedLinLINEA.Caption',
   'es-ES',
   'Línea',
   'src/Forms/inMtoPedidos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPedidos.TfrmMtoPedidos.cxgrdcPedLinART.Caption',
   'es-ES',
   'Código Artículo',
   'src/Forms/inMtoPedidos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPedidos.TfrmMtoPedidos.cxgrdcPedLinSKU.Caption',
   'es-ES',
   'SKU',
   'src/Forms/inMtoPedidos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPedidos.TfrmMtoPedidos.cxgrdcPedLinDESCR.Caption',
   'es-ES',
   'Descripción',
   'src/Forms/inMtoPedidos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPedidos.TfrmMtoPedidos.cxgrdcPedLinCANT.Caption',
   'es-ES',
   'Pedida',
   'src/Forms/inMtoPedidos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPedidos.TfrmMtoPedidos.cxgrdcPedLinENT.Caption',
   'es-ES',
   'Entregada',
   'src/Forms/inMtoPedidos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPedidos.TfrmMtoPedidos.cxgrdcPedLinPEND.Caption',
   'es-ES',
   'Pendiente',
   'src/Forms/inMtoPedidos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPedidos.TfrmMtoPedidos.cxgrdcPedLinESEN.Caption',
   'es-ES',
   'Entregada?',
   'src/Forms/inMtoPedidos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPedidos.TfrmMtoPedidos.cxgrdcPedLinPSIVA.Caption',
   'es-ES',
   'PVP S/IVA',
   'src/Forms/inMtoPedidos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPedidos.TfrmMtoPedidos.cxgrdcPedLinPCIVA.Caption',
   'es-ES',
   'PVP C/IVA',
   'src/Forms/inMtoPedidos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPedidos.TfrmMtoPedidos.cxgrdcPedLinTOT.Caption',
   'es-ES',
   'Total',
   'src/Forms/inMtoPedidos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPedidos.TfrmMtoPedidos.cxgrdcPedLinALM.Caption',
   'es-ES',
   'Almacén',
   'src/Forms/inMtoPedidos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPedidos.TfrmMtoPedidos.tsTotales.Caption',
   'es-ES',
   '&2_Totales',
   'src/Forms/inMtoPedidos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPedidos.TfrmMtoPedidos.lblTotalesTotalBase.Caption',
   'es-ES',
   'Total Base Imponible',
   'src/Forms/inMtoPedidos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPedidos.TfrmMtoPedidos.lblTotalesTotalImpuestos.Caption',
   'es-ES',
   'Total Impuestos',
   'src/Forms/inMtoPedidos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPedidos.TfrmMtoPedidos.lblTotalesPorcRetencion.Caption',
   'es-ES',
   '% Retención',
   'src/Forms/inMtoPedidos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPedidos.TfrmMtoPedidos.lblTotalesTotalRetencion.Caption',
   'es-ES',
   'Total Retención',
   'src/Forms/inMtoPedidos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPedidos.TfrmMtoPedidos.lblTotalesTotalPagar.Caption',
   'es-ES',
   'Total a pagar',
   'src/Forms/inMtoPedidos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPedidos.TfrmMtoPedidos.lblTotalesFormaPago.Caption',
   'es-ES',
   'Forma de Pago',
   'src/Forms/inMtoPedidos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoPedidos.TfrmMtoPedidos.cbbTotalesFORMA_PAGO_PED.Properties.ListCo',
     'lumns[0].Caption'
   ),
   'es-ES',
   'Código',
   'src/Forms/inMtoPedidos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoPedidos.TfrmMtoPedidos.cbbTotalesFORMA_PAGO_PED.Properties.ListCo',
     'lumns[1].Caption'
   ),
   'es-ES',
   'Descripción',
   'src/Forms/inMtoPedidos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPedidos.TfrmMtoPedidos.chkTotalesESIVA_RECARGO_CLIENTE_PED.Caption',
   'es-ES',
   'Recargo equivalencia cliente',
   'src/Forms/inMtoPedidos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPedidos.TfrmMtoPedidos.chkTotalesESRETENCIONES_CLIENTE_PED.Caption',
   'es-ES',
   'Cliente sujeto a retención',
   'src/Forms/inMtoPedidos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPedidos.TfrmMtoPedidos.chkTotalesESRETENCIONES_EMPRESA_PED.Caption',
   'es-ES',
   'Empresa aplica retención',
   'src/Forms/inMtoPedidos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPedidos.TfrmMtoPedidos.lblTotalesTotalPrendas.Caption',
   'es-ES',
   'Nº de prendas',
   'src/Forms/inMtoPedidos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPedidos.TfrmMtoPedidos.lblTotalPrendasPed.Caption',
   'es-ES',
   '0',
   'src/Forms/inMtoPedidos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPedidos.TfrmMtoPedidos.grpDesgloseImpuestos.Caption',
   'es-ES',
   'Desglose Impuestos',
   'src/Forms/inMtoPedidos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPedidos.TfrmMtoPedidos.lblTotalesTotalRe.Caption',
   'es-ES',
   'Total R.E.',
   'src/Forms/inMtoPedidos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPedidos.TfrmMtoPedidos.lblTotalesPorRe.Caption',
   'es-ES',
   '%R.E.',
   'src/Forms/inMtoPedidos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPedidos.TfrmMtoPedidos.lblTotalesTotalIva.Caption',
   'es-ES',
   'Total IVA',
   'src/Forms/inMtoPedidos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPedidos.TfrmMtoPedidos.lblTotalesPorIva.Caption',
   'es-ES',
   '%IVA',
   'src/Forms/inMtoPedidos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPedidos.TfrmMtoPedidos.lblTotalesBaseNeta.Caption',
   'es-ES',
   'BaseNeta',
   'src/Forms/inMtoPedidos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPedidos.TfrmMtoPedidos.lblTotalesIVAN.Caption',
   'es-ES',
   'Normal',
   'src/Forms/inMtoPedidos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPedidos.TfrmMtoPedidos.lblTotalesIVAR.Caption',
   'es-ES',
   'Reducido',
   'src/Forms/inMtoPedidos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPedidos.TfrmMtoPedidos.lblTotalesIVAS.Caption',
   'es-ES',
   'Súper Reducido',
   'src/Forms/inMtoPedidos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPedidos.TfrmMtoPedidos.lblTotalesIVAE.Caption',
   'es-ES',
   'Exento',
   'src/Forms/inMtoPedidos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPedidos.TfrmMtoPedidos.tsAlbaranes.Caption',
   'es-ES',
   'Albaranes',
   'src/Forms/inMtoPedidos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPedidos.TfrmMtoPedidos.cxgrdcAlbNUMERO_ALB.Caption',
   'es-ES',
   'Número',
   'src/Forms/inMtoPedidos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPedidos.TfrmMtoPedidos.cxgrdcAlbSERIE_ALB.Caption',
   'es-ES',
   'Serie',
   'src/Forms/inMtoPedidos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPedidos.TfrmMtoPedidos.cxgrdcAlbFECHA_ALB.Caption',
   'es-ES',
   'Fecha',
   'src/Forms/inMtoPedidos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPedidos.TfrmMtoPedidos.cxgrdcAlbESTADO_ALB.Caption',
   'es-ES',
   'Estado',
   'src/Forms/inMtoPedidos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPedidos.TfrmMtoPedidos.cxgrdcAlbTOTAL_LIQUIDO_ALB.Caption',
   'es-ES',
   'Total',
   'src/Forms/inMtoPedidos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPedidos.TfrmMtoPedidos.tsMensajes.Caption',
   'es-ES',
   'Mensajes con el cliente',
   'src/Forms/inMtoPedidos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPedidos.TfrmMtoPedidos.cxgrdcMsgFecha.Caption',
   'es-ES',
   'Fecha',
   'src/Forms/inMtoPedidos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPedidos.TfrmMtoPedidos.cxgrdcMsgEmpleado.Caption',
   'es-ES',
   'Empleado',
   'src/Forms/inMtoPedidos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPedidos.TfrmMtoPedidos.cxgrdcMsgTexto.Caption',
   'es-ES',
   'Mensaje',
   'src/Forms/inMtoPedidos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPedidos.TfrmMtoPedidos.tsObservaciones.Caption',
   'es-ES',
   'Observaciones',
   'src/Forms/inMtoPedidos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPedidos.TfrmMtoPedidos.lblTotalBases.Caption',
   'es-ES',
   'Bases',
   'src/Forms/inMtoPedidos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPedidos.TfrmMtoPedidos.lblTotalImpuestos.Caption',
   'es-ES',
   'IVA',
   'src/Forms/inMtoPedidos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPedidos.TfrmMtoPedidos.lblTotalLiquido.Caption',
   'es-ES',
   'TOTAL',
   'src/Forms/inMtoPedidos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPedidos.TfrmMtoPedidos.btnImprimir.Caption',
   'es-ES',
   'Imprimir',
   'src/Forms/inMtoPedidos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPedidos.TfrmMtoPedidos.actIrDocumento.Caption',
   'es-ES',
   'Ir a documento (Ctrl+May+A)',
   'src/Forms/inMtoPedidos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPedidosCompra.TfrmMtoPedidosCompra.Caption',
   'es-ES',
   'Mantenimiento de Pedidos de Compra',
   'src/Forms/inMtoPedidosCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPedidosCompra.TfrmMtoPedidosCompra.dbcGrdPedcCODIGO_ALM_PEDC.Caption',
   'es-ES',
   'Almacén',
   'src/Forms/inMtoPedidosCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPedidosCompra.TfrmMtoPedidosCompra.dbcGrdPedcSERIE_PEDC.Caption',
   'es-ES',
   'Serie',
   'src/Forms/inMtoPedidosCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPedidosCompra.TfrmMtoPedidosCompra.dbcGrdPedcNUMERO_PEDC.Caption',
   'es-ES',
   'Número',
   'src/Forms/inMtoPedidosCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPedidosCompra.TfrmMtoPedidosCompra.dbcGrdPedcESTADO_PEDC.Caption',
   'es-ES',
   'Estado',
   'src/Forms/inMtoPedidosCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPedidosCompra.TfrmMtoPedidosCompra.dbcGrdPedcFECHA_PEDC.Caption',
   'es-ES',
   'Fecha',
   'src/Forms/inMtoPedidosCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPedidosCompra.TfrmMtoPedidosCompra.dbcGrdPedcCODIGO_PRV_PEDC.Caption',
   'es-ES',
   'Proveedor',
   'src/Forms/inMtoPedidosCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPedidosCompra.TfrmMtoPedidosCompra.dbcGrdPedcRSPRV_PEDC.Caption',
   'es-ES',
   'Razón Social Proveedor',
   'src/Forms/inMtoPedidosCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPedidosCompra.TfrmMtoPedidosCompra.dbcGrdPedcTEMPORADA_PEDC.Caption',
   'es-ES',
   'Temporada',
   'src/Forms/inMtoPedidosCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoPedidosCompra.TfrmMtoPedidosCompra.dbcGrdPedcREF_PROVEEDOR_PEDC.C',
     'aption'
   ),
   'es-ES',
   'Ref. proveedor',
   'src/Forms/inMtoPedidosCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoPedidosCompra.TfrmMtoPedidosCompra.dbcGrdPedcFECHA_EFECTO_STOCK_P',
     'EDC.Caption'
   ),
   'es-ES',
   'F.stock',
   'src/Forms/inMtoPedidosCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoPedidosCompra.TfrmMtoPedidosCompra.dbcGrdPedcFECHA_TOPE_RECEPCION',
     '_PEDC.Caption'
   ),
   'es-ES',
   'F.tope recep.',
   'src/Forms/inMtoPedidosCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoPedidosCompra.TfrmMtoPedidosCompra.dbcGrdPedcFECHA_PREVISTA_PEDC.',
     'Caption'
   ),
   'es-ES',
   'F.prevista',
   'src/Forms/inMtoPedidosCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoPedidosCompra.TfrmMtoPedidosCompra.dbcGrdPedcTOTAL_LINEAS_PEDC.Ca',
     'ption'
   ),
   'es-ES',
   'Neto lineas',
   'src/Forms/inMtoPedidosCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoPedidosCompra.TfrmMtoPedidosCompra.dbcGrdPedcTOTAL_LIQUIDO_PEDC.C',
     'aption'
   ),
   'es-ES',
   'Total líquido',
   'src/Forms/inMtoPedidosCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoPedidosCompra.TfrmMtoPedidosCompra.dbcGrdPedcTOTAL_PRENDAS_PEDC.C',
     'aption'
   ),
   'es-ES',
   'Prendas',
   'src/Forms/inMtoPedidosCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoPedidosCompra.TfrmMtoPedidosCompra.dbcGrdPedcCANTIDAD_PEDIDA_PEDC',
     '.Caption'
   ),
   'es-ES',
   'Pedidas',
   'src/Forms/inMtoPedidosCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoPedidosCompra.TfrmMtoPedidosCompra.dbcGrdPedcCANTIDAD_RECIBIDA_PE',
     'DC.Caption'
   ),
   'es-ES',
   'Recibidas',
   'src/Forms/inMtoPedidosCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoPedidosCompra.TfrmMtoPedidosCompra.dbcGrdPedcCANTIDAD_PENDIENTE_R',
     'ECEPCION_PEDC.Caption'
   ),
   'es-ES',
   'Pte. recibir',
   'src/Forms/inMtoPedidosCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPedidosCompra.TfrmMtoPedidosCompra.dbcGrdPedcCODIGO_EMP_PEDC.Caption',
   'es-ES',
   'Empresa',
   'src/Forms/inMtoPedidosCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPedidosCompra.TfrmMtoPedidosCompra.tsCabecera.Caption',
   'es-ES',
   'Cabecera',
   'src/Forms/inMtoPedidosCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPedidosCompra.TfrmMtoPedidosCompra.lblNroPedido.Caption',
   'es-ES',
   'Número',
   'src/Forms/inMtoPedidosCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPedidosCompra.TfrmMtoPedidosCompra.lblSeriePedido.Caption',
   'es-ES',
   'Serie',
   'src/Forms/inMtoPedidosCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPedidosCompra.TfrmMtoPedidosCompra.lblFechaPedido.Caption',
   'es-ES',
   'Fecha',
   'src/Forms/inMtoPedidosCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPedidosCompra.TfrmMtoPedidosCompra.lblFechaPrevista.Caption',
   'es-ES',
   'F.prevista',
   'src/Forms/inMtoPedidosCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPedidosCompra.TfrmMtoPedidosCompra.lblFechaTopeRecepcionPedc.Caption',
   'es-ES',
   'F.tope recep.',
   'src/Forms/inMtoPedidosCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPedidosCompra.TfrmMtoPedidosCompra.lblEstadoPedido.Caption',
   'es-ES',
   'Estado',
   'src/Forms/inMtoPedidosCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPedidosCompra.TfrmMtoPedidosCompra.lblCodigoEmpresa.Caption',
   'es-ES',
   'Empresa',
   'src/Forms/inMtoPedidosCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPedidosCompra.TfrmMtoPedidosCompra.lblCodigoProveedor.Caption',
   'es-ES',
   'Proveedor',
   'src/Forms/inMtoPedidosCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoPedidosCompra.TfrmMtoPedidosCompra.cbbCODIGO_PRV_PEDC.Properties.',
     'ListColumns[0].Caption'
   ),
   'es-ES',
   'Código',
   'src/Forms/inMtoPedidosCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoPedidosCompra.TfrmMtoPedidosCompra.cbbCODIGO_PRV_PEDC.Properties.',
     'ListColumns[1].Caption'
   ),
   'es-ES',
   'Proveedor',
   'src/Forms/inMtoPedidosCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPedidosCompra.TfrmMtoPedidosCompra.lblRefProveedor.Caption',
   'es-ES',
   'Ref. proveedor',
   'src/Forms/inMtoPedidosCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPedidosCompra.TfrmMtoPedidosCompra.lblCodigoAlmacen.Caption',
   'es-ES',
   'Almacén destino',
   'src/Forms/inMtoPedidosCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoPedidosCompra.TfrmMtoPedidosCompra.cbbCODIGO_ALM_PEDC.Properties.',
     'ListColumns[0].Caption'
   ),
   'es-ES',
   'Código',
   'src/Forms/inMtoPedidosCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoPedidosCompra.TfrmMtoPedidosCompra.cbbCODIGO_ALM_PEDC.Properties.',
     'ListColumns[1].Caption'
   ),
   'es-ES',
   'Almacén',
   'src/Forms/inMtoPedidosCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoPedidosCompra.TfrmMtoPedidosCompra.cbbCODIGO_ALM_PEDC.Properties.',
     'ListColumns[2].Caption'
   ),
   'es-ES',
   'Empresa',
   'src/Forms/inMtoPedidosCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPedidosCompra.TfrmMtoPedidosCompra.lblTemporada.Caption',
   'es-ES',
   'Temporada',
   'src/Forms/inMtoPedidosCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoPedidosCompra.TfrmMtoPedidosCompra.cbbTemporadaPedc.Properties.Li',
     'stColumns[0].Caption'
   ),
   'es-ES',
   'Temporada',
   'src/Forms/inMtoPedidosCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPedidosCompra.TfrmMtoPedidosCompra.lblCabCantidadPedidaPedc.Caption',
   'es-ES',
   'Pedida',
   'src/Forms/inMtoPedidosCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPedidosCompra.TfrmMtoPedidosCompra.lblCabCantidadRecibidaPedc.Caption',
   'es-ES',
   'Recibida',
   'src/Forms/inMtoPedidosCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoPedidosCompra.TfrmMtoPedidosCompra.lblCabCantidadPendientePedc.Ca',
     'ption'
   ),
   'es-ES',
   'Pte. rec.',
   'src/Forms/inMtoPedidosCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoPedidosCompra.TfrmMtoPedidosCompra.lblCabCantidadAAlbaranarPedc.C',
     'aption'
   ),
   'es-ES',
   'A alb.',
   'src/Forms/inMtoPedidosCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPedidosCompra.TfrmMtoPedidosCompra.btnRecibirFilaEntera.Caption',
   'es-ES',
   'Recibir fila entera',
   'src/Forms/inMtoPedidosCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPedidosCompra.TfrmMtoPedidosCompra.btnTallasHorizontal.Caption',
   'es-ES',
   'Tallas en horizontal',
   'src/Forms/inMtoPedidosCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPedidosCompra.TfrmMtoPedidosCompra.btnExpandirRecibidos.Caption',
   'es-ES',
   'Expandir recibidos',
   'src/Forms/inMtoPedidosCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPedidosCompra.TfrmMtoPedidosCompra.btnRecibirTodo.Caption',
   'es-ES',
   'Recibir Todo',
   'src/Forms/inMtoPedidosCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPedidosCompra.TfrmMtoPedidosCompra.tsLineasPedido.Caption',
   'es-ES',
   'Líneas',
   'src/Forms/inMtoPedidosCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPedidosCompra.TfrmMtoPedidosCompra.colLineaPedcLINEA.Caption',
   'es-ES',
   'Línea',
   'src/Forms/inMtoPedidosCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPedidosCompra.TfrmMtoPedidosCompra.colLineaPedcCODIGO_ART.Caption',
   'es-ES',
   'Artículo',
   'src/Forms/inMtoPedidosCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPedidosCompra.TfrmMtoPedidosCompra.colLineaPedcCODIGO_UNIDAD.Caption',
   'es-ES',
   'SKU',
   'src/Forms/inMtoPedidosCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPedidosCompra.TfrmMtoPedidosCompra.colLineaPedcREF_PRV.Caption',
   'es-ES',
   'Modelo prov.',
   'src/Forms/inMtoPedidosCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPedidosCompra.TfrmMtoPedidosCompra.colLineaPedcDESCRIPCION.Caption',
   'es-ES',
   'Descripción',
   'src/Forms/inMtoPedidosCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPedidosCompra.TfrmMtoPedidosCompra.colLineaPedcCANTIDAD.Caption',
   'es-ES',
   'Pedida',
   'src/Forms/inMtoPedidosCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPedidosCompra.TfrmMtoPedidosCompra.colLineaPedcRECIBIDA.Caption',
   'es-ES',
   'Recibida',
   'src/Forms/inMtoPedidosCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPedidosCompra.TfrmMtoPedidosCompra.colLineaPedcARecibir.Caption',
   'es-ES',
   'A recibir',
   'src/Forms/inMtoPedidosCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPedidosCompra.TfrmMtoPedidosCompra.colLineaPedcPRECIO_COMPRA.Caption',
   'es-ES',
   'Precio compra',
   'src/Forms/inMtoPedidosCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPedidosCompra.TfrmMtoPedidosCompra.colLineaPedcPORCENTAJE_IVA.Caption',
   'es-ES',
   '% IVA',
   'src/Forms/inMtoPedidosCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPedidosCompra.TfrmMtoPedidosCompra.colLineaPedcTOTAL.Caption',
   'es-ES',
   'Total',
   'src/Forms/inMtoPedidosCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPedidosCompra.TfrmMtoPedidosCompra.colLineaPedcALMACEN.Caption',
   'es-ES',
   'Almacén',
   'src/Forms/inMtoPedidosCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPedidosCompra.TfrmMtoPedidosCompra.tsTotales.Caption',
   'es-ES',
   '&2_Totales',
   'src/Forms/inMtoPedidosCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPedidosCompra.TfrmMtoPedidosCompra.lblTotalesTotalBase.Caption',
   'es-ES',
   'Total Base Imponible',
   'src/Forms/inMtoPedidosCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPedidosCompra.TfrmMtoPedidosCompra.lblTotalesTotalImpuestos.Caption',
   'es-ES',
   'Total Impuestos',
   'src/Forms/inMtoPedidosCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPedidosCompra.TfrmMtoPedidosCompra.lblTotalesPorcRetencion.Caption',
   'es-ES',
   '% Retención',
   'src/Forms/inMtoPedidosCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPedidosCompra.TfrmMtoPedidosCompra.lblTotalesTotalRetencion.Caption',
   'es-ES',
   'Total Retención',
   'src/Forms/inMtoPedidosCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPedidosCompra.TfrmMtoPedidosCompra.lblTotalesTotalPagar.Caption',
   'es-ES',
   'Total a pagar',
   'src/Forms/inMtoPedidosCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPedidosCompra.TfrmMtoPedidosCompra.lblTotalesFormaPago.Caption',
   'es-ES',
   'Forma de Pago',
   'src/Forms/inMtoPedidosCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoPedidosCompra.TfrmMtoPedidosCompra.cbbTotalesFORMA_PAGO_PEDC.Prop',
     'erties.ListColumns[0].Caption'
   ),
   'es-ES',
   'Código',
   'src/Forms/inMtoPedidosCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoPedidosCompra.TfrmMtoPedidosCompra.cbbTotalesFORMA_PAGO_PEDC.Prop',
     'erties.ListColumns[1].Caption'
   ),
   'es-ES',
   'Descripción',
   'src/Forms/inMtoPedidosCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoPedidosCompra.TfrmMtoPedidosCompra.chkTotalesESIVA_RECARGO_COMPRA',
     'S_PEDC.Caption'
   ),
   'es-ES',
   'Recargo equivalencia compras',
   'src/Forms/inMtoPedidosCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPedidosCompra.TfrmMtoPedidosCompra.lblTotalesDtoComercial.Caption',
   'es-ES',
   'Dto. comercial',
   'src/Forms/inMtoPedidosCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPedidosCompra.TfrmMtoPedidosCompra.lblTotalesDtoFinanciero.Caption',
   'es-ES',
   'Dto. financiero',
   'src/Forms/inMtoPedidosCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPedidosCompra.TfrmMtoPedidosCompra.lblTotalesTotalPrendas.Caption',
   'es-ES',
   'Nº de prendas',
   'src/Forms/inMtoPedidosCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPedidosCompra.TfrmMtoPedidosCompra.grpDesgloseImpuestos.Caption',
   'es-ES',
   'Desglose Impuestos',
   'src/Forms/inMtoPedidosCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPedidosCompra.TfrmMtoPedidosCompra.lblTotalesTotalRe.Caption',
   'es-ES',
   'Total R.E.',
   'src/Forms/inMtoPedidosCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPedidosCompra.TfrmMtoPedidosCompra.lblTotalesPorRe.Caption',
   'es-ES',
   '%R.E.',
   'src/Forms/inMtoPedidosCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPedidosCompra.TfrmMtoPedidosCompra.lblTotalesTotalIva.Caption',
   'es-ES',
   'Total IVA',
   'src/Forms/inMtoPedidosCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPedidosCompra.TfrmMtoPedidosCompra.lblTotalesPorIva.Caption',
   'es-ES',
   '%IVA',
   'src/Forms/inMtoPedidosCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPedidosCompra.TfrmMtoPedidosCompra.lblTotalesBaseNeta.Caption',
   'es-ES',
   'BaseNeta',
   'src/Forms/inMtoPedidosCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPedidosCompra.TfrmMtoPedidosCompra.lblTotalesIVAN.Caption',
   'es-ES',
   'Normal',
   'src/Forms/inMtoPedidosCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPedidosCompra.TfrmMtoPedidosCompra.lblTotalesIVAR.Caption',
   'es-ES',
   'Reducido',
   'src/Forms/inMtoPedidosCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPedidosCompra.TfrmMtoPedidosCompra.lblTotalesIVAS.Caption',
   'es-ES',
   'Súper Reducido',
   'src/Forms/inMtoPedidosCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPedidosCompra.TfrmMtoPedidosCompra.lblTotalesIVAE.Caption',
   'es-ES',
   'Exento',
   'src/Forms/inMtoPedidosCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPedidosCompra.TfrmMtoPedidosCompra.tsObservaciones.Caption',
   'es-ES',
   'Observaciones',
   'src/Forms/inMtoPedidosCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPedidosCompra.TfrmMtoPedidosCompra.tsAlbaranesPedc.Caption',
   'es-ES',
   'Albaranes',
   'src/Forms/inMtoPedidosCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPedidosCompra.TfrmMtoPedidosCompra.colAlbcPedcNUMERO.Caption',
   'es-ES',
   'Número',
   'src/Forms/inMtoPedidosCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPedidosCompra.TfrmMtoPedidosCompra.colAlbcPedcSERIE.Caption',
   'es-ES',
   'Serie',
   'src/Forms/inMtoPedidosCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPedidosCompra.TfrmMtoPedidosCompra.colAlbcPedcFECHA.Caption',
   'es-ES',
   'Fecha',
   'src/Forms/inMtoPedidosCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPedidosCompra.TfrmMtoPedidosCompra.colAlbcPedcESTADO.Caption',
   'es-ES',
   'Estado',
   'src/Forms/inMtoPedidosCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPedidosCompra.TfrmMtoPedidosCompra.colAlbcPedcREFPRV.Caption',
   'es-ES',
   'Modelo prov.',
   'src/Forms/inMtoPedidosCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPedidosCompra.TfrmMtoPedidosCompra.colAlbcPedcTOTAL.Caption',
   'es-ES',
   'Total',
   'src/Forms/inMtoPedidosCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPedidosCompra.TfrmMtoPedidosCompra.btnIraalbaran.Caption',
   'es-ES',
   'Ir a albarán',
   'src/Forms/inMtoPedidosCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPedidosCompra.TfrmMtoPedidosCompra.lblTotalBases.Caption',
   'es-ES',
   'Total bases',
   'src/Forms/inMtoPedidosCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPedidosCompra.TfrmMtoPedidosCompra.lblTotalImpuestos.Caption',
   'es-ES',
   'Total impuestos',
   'src/Forms/inMtoPedidosCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPedidosCompra.TfrmMtoPedidosCompra.lblTotalLiquido.Caption',
   'es-ES',
   'Total líquido',
   'src/Forms/inMtoPedidosCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPedidosCompra.TfrmMtoPedidosCompra.btnCrearAlbaran.Caption',
   'es-ES',
   'Crear albarán',
   'src/Forms/inMtoPedidosCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPedidosCompra.TfrmMtoPedidosCompra.btnPegatinas.Caption',
   'es-ES',
   'Etiquetas',
   'src/Forms/inMtoPedidosCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPedidosCompra.TfrmMtoPedidosCompra.actArticulos.Caption',
   'es-ES',
   'actArticulos',
   'src/Forms/inMtoPedidosCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPedidosCompra.TfrmMtoPedidosCompra.actIrDocumento.Caption',
   'es-ES',
   'Ir a documento (Ctrl+May+A)',
   'src/Forms/inMtoPedidosCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPedidosCompra.TfrmMtoPedidosCompra.actIrProveedor.Caption',
   'es-ES',
   'Ir a proveedor',
   'src/Forms/inMtoPedidosCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPermisos.TfrmMtoPermisos.Caption',
   'es-ES',
   'Permisos',
   'src/Forms/inMtoPermisos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPermisos.TfrmMtoPermisos.cxGrdDBTabPrinUSUARIO_GRUPO_PERM.Caption',
   'es-ES',
   'Usuario / Grupo',
   'src/Forms/inMtoPermisos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPermisos.TfrmMtoPermisos.cxGrdDBTabPrinCODIGO_PERM.Caption',
   'es-ES',
   'Código',
   'src/Forms/inMtoPermisos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPermisos.TfrmMtoPermisos.cxGrdDBTabPrinVALOR_PERM.Caption',
   'es-ES',
   'Valor',
   'src/Forms/inMtoPermisos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPermisos.TfrmMtoPermisos.cxGrdDBTabPrinDESCRIPCION_PERM.Caption',
   'es-ES',
   'Descripción',
   'src/Forms/inMtoPermisos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPermisosArbol.TfrmMtoPermisosArbol.Caption',
   'es-ES',
   'Gestión de Permisos',
   'src/Forms/inMtoPermisosArbol.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPermisosArbol.TfrmMtoPermisosArbol.tsGestion.Caption',
   'es-ES',
   'Gestión',
   'src/Forms/inMtoPermisosArbol.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPermisosArbol.TfrmMtoPermisosArbol.lblSujeto.Caption',
   'es-ES',
   'Permisos de:',
   'src/Forms/inMtoPermisosArbol.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPermisosArbol.TfrmMtoPermisosArbol.btnRecargar.Caption',
   'es-ES',
   'Recargar',
   'src/Forms/inMtoPermisosArbol.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPermisosArbol.TfrmMtoPermisosArbol.lblFiltro.Caption',
   'es-ES',
   'Filtro:',
   'src/Forms/inMtoPermisosArbol.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPermisosArbol.TfrmMtoPermisosArbol.btnExpandir.Caption',
   'es-ES',
   'Expandir',
   'src/Forms/inMtoPermisosArbol.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPermisosArbol.TfrmMtoPermisosArbol.btnContraer.Caption',
   'es-ES',
   'Contraer',
   'src/Forms/inMtoPermisosArbol.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPermisosArbol.TfrmMtoPermisosArbol.btnPermitirRama.Caption',
   'es-ES',
   'Permitir rama',
   'src/Forms/inMtoPermisosArbol.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPermisosArbol.TfrmMtoPermisosArbol.btnDenegarRama.Caption',
   'es-ES',
   'Denegar rama',
   'src/Forms/inMtoPermisosArbol.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPermisosArbol.TfrmMtoPermisosArbol.btnHeredarRama.Caption',
   'es-ES',
   'Heredar (rama)',
   'src/Forms/inMtoPermisosArbol.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPermisosArbol.TfrmMtoPermisosArbol.lblTransfer.Caption',
   'es-ES',
   'Transferir / copiar permisos entre sujetos',
   'src/Forms/inMtoPermisosArbol.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPermisosArbol.TfrmMtoPermisosArbol.lblDe.Caption',
   'es-ES',
   'Copiar de:',
   'src/Forms/inMtoPermisosArbol.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPermisosArbol.TfrmMtoPermisosArbol.lblA.Caption',
   'es-ES',
   'a:',
   'src/Forms/inMtoPermisosArbol.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPermisosArbol.TfrmMtoPermisosArbol.rgModo.Caption',
   'es-ES',
   'Modo de copia',
   'src/Forms/inMtoPermisosArbol.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPermisosArbol.TfrmMtoPermisosArbol.chkSoloMenu.Caption',
   'es-ES',
   'Solo permisos de menú',
   'src/Forms/inMtoPermisosArbol.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPermisosArbol.TfrmMtoPermisosArbol.btnCopiar.Caption',
   'es-ES',
   'Copiar permisos',
   'src/Forms/inMtoPermisosArbol.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPropiedades.TfrmMtoPropiedades.Caption',
   'es-ES',
   'Propiedades',
   'src/Forms/inMtoPropiedades.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPropiedades.TfrmMtoPropiedades.cxgrdbclmnGrdDBTabPrinCODIGO.Caption',
   'es-ES',
   'Código',
   'src/Forms/inMtoPropiedades.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPropiedades.TfrmMtoPropiedades.cxgrdbclmnGrdDBTabPrinNOMBRE.Caption',
   'es-ES',
   'Nombre',
   'src/Forms/inMtoPropiedades.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPropiedades.TfrmMtoPropiedades.cxgrdbclmnGrdDBTabPrinTIPO.Caption',
   'es-ES',
   'Tipo de valor',
   'src/Forms/inMtoPropiedades.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPropiedades.TfrmMtoPropiedades.cxgrdbclmnGrdDBTabPrinNIVEL.Caption',
   'es-ES',
   'Nivel',
   'src/Forms/inMtoPropiedades.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPropiedades.TfrmMtoPropiedades.cxgrdbclmnGrdDBTabPrinACTIVO.Caption',
   'es-ES',
   'Activo',
   'src/Forms/inMtoPropiedades.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoPropiedades.TfrmMtoPropiedades.cxgrdbclmnGrdDBTabPrinNUMARTUSOS.C',
     'aption'
   ),
   'es-ES',
   'Artículos asignados',
   'src/Forms/inMtoPropiedades.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPropiedades.TfrmMtoPropiedades.lblCodigo.Caption',
   'es-ES',
   'Código',
   'src/Forms/inMtoPropiedades.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPropiedades.TfrmMtoPropiedades.lblNombre.Caption',
   'es-ES',
   'Nombre',
   'src/Forms/inMtoPropiedades.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPropiedades.TfrmMtoPropiedades.lblTipo.Caption',
   'es-ES',
   'Tipo de valor',
   'src/Forms/inMtoPropiedades.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPropiedades.TfrmMtoPropiedades.chkACTIVO.Caption',
   'es-ES',
   'Activo',
   'src/Forms/inMtoPropiedades.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPropiedades.TfrmMtoPropiedades.lblNivel.Caption',
   'es-ES',
   'Nivel de desglose',
   'src/Forms/inMtoPropiedades.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPropiedades.TfrmMtoPropiedades.tsValores.Caption',
   'es-ES',
   '&1_Valores Disponibles',
   'src/Forms/inMtoPropiedades.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPropiedades.TfrmMtoPropiedades.tvValoresPV.Caption',
   'es-ES',
   'Valor',
   'src/Forms/inMtoPropiedades.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPropiedades.TfrmMtoPropiedades.tvValoresDESCRIPCION_PV.Caption',
   'es-ES',
   'Descripción',
   'src/Forms/inMtoPropiedades.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPropiedades.TfrmMtoPropiedades.tvValoresESACTIVO_PV.Caption',
   'es-ES',
   'Activo',
   'src/Forms/inMtoPropiedades.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPropiedades.TfrmMtoPropiedades.tsArticulos.Caption',
   'es-ES',
   '&2_Artículos',
   'src/Forms/inMtoPropiedades.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPropiedades.TfrmMtoPropiedades.tvArticulosCODIGO_ART_ART.Caption',
   'es-ES',
   'Código Artículo',
   'src/Forms/inMtoPropiedades.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoPropiedades.TfrmMtoPropiedades.tvArticulosDESCRIPCION_ARTICULO.Ca',
     'ption'
   ),
   'es-ES',
   'Descripción',
   'src/Forms/inMtoPropiedades.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPropiedades.TfrmMtoPropiedades.tvArticulosVALOR_LISTA.Caption',
   'es-ES',
   'Valor (lista)',
   'src/Forms/inMtoPropiedades.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPropiedades.TfrmMtoPropiedades.tvArticulosVALOR_LIBRE_ARTPROP.Caption',
   'es-ES',
   'Valor libre',
   'src/Forms/inMtoPropiedades.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPropiedades.TfrmMtoPropiedades.actGoArticulo.Caption',
   'es-ES',
   'Ir al artículo',
   'src/Forms/inMtoPropiedades.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPropiedades.TfrmMtoPropiedades.actGoArticulo.Hint',
   'es-ES',
   'Abre la ficha del artículo seleccionado en la pestaña Artículos',
   'src/Forms/inMtoPropiedades.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPropiedadesValores.TfrmMtoPropiedadesValores.Caption',
   'es-ES',
   'Valores de Propiedades',
   'src/Forms/inMtoPropiedadesValores.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoPropiedadesValores.TfrmMtoPropiedadesValores.cxGrdDBTabPrinID_PV_',
     'ARTPROP.Caption'
   ),
   'es-ES',
   'ID',
   'src/Forms/inMtoPropiedadesValores.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoPropiedadesValores.TfrmMtoPropiedadesValores.cxGrdDBTabPrinID_PRO',
     'P_PV.Caption'
   ),
   'es-ES',
   'Propiedad',
   'src/Forms/inMtoPropiedadesValores.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoPropiedadesValores.TfrmMtoPropiedadesValores.cxGrdDBTabPrinPV.Caption',
   'es-ES',
   'Valor',
   'src/Forms/inMtoPropiedadesValores.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoPropiedadesValores.TfrmMtoPropiedadesValores.cxGrdDBTabPrinDESCRI',
     'PCION_PV.Caption'
   ),
   'es-ES',
   'Descripción',
   'src/Forms/inMtoPropiedadesValores.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoPropiedadesValores.TfrmMtoPropiedadesValores.cxGrdDBTabPrinESACTI',
     'VO_PV.Caption'
   ),
   'es-ES',
   'Activo',
   'src/Forms/inMtoPropiedadesValores.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoPropiedadesValores.TfrmMtoPropiedadesValores.cxGrdDBTabPrinINSTAN',
     'TE_ALTA.Caption'
   ),
   'es-ES',
   'Instante Alta',
   'src/Forms/inMtoPropiedadesValores.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoPropiedadesValores.TfrmMtoPropiedadesValores.cxGrdDBTabPrinINSTAN',
     'TE_MODIF.Caption'
   ),
   'es-ES',
   'Instante Modif',
   'src/Forms/inMtoPropiedadesValores.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoPropiedadesValores.TfrmMtoPropiedadesValores.cxGrdDBTabPrinUSUARI',
     'O_ALTA.Caption'
   ),
   'es-ES',
   'Usuario Alta',
   'src/Forms/inMtoPropiedadesValores.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoPropiedadesValores.TfrmMtoPropiedadesValores.cxGrdDBTabPrinUSUARI',
     'O_MODIF.Caption'
   ),
   'es-ES',
   'Usuario Modif',
   'src/Forms/inMtoPropiedadesValores.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoProveedores.TfrmMtoProveedores.Caption',
   'es-ES',
   'Proveedores',
   'src/Forms/inMtoProveedores.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoProveedores.TfrmMtoProveedores.cxgrdbclmnGrdDBTabPrinCODIGO_CLIEN',
     'TE.Caption'
   ),
   'es-ES',
   'Código',
   'src/Forms/inMtoProveedores.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoProveedores.TfrmMtoProveedores.cxgrdbclmnGrdDBTabPrinACTIVO_CLIEN',
     'TE.Caption'
   ),
   'es-ES',
   'Activo',
   'src/Forms/inMtoProveedores.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoProveedores.TfrmMtoProveedores.cxgrdbclmnGrdDBTabPrinVARIOS_TIPOS',
     '_IVA_PRV.Caption'
   ),
   'es-ES',
   'Varios IVA art.',
   'src/Forms/inMtoProveedores.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoProveedores.TfrmMtoProveedores.cxgrdbclmnGrdDBTabPrinRAZONSOCIAL_',
     'CLIENTE.Caption'
   ),
   'es-ES',
   'Razón Social',
   'src/Forms/inMtoProveedores.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoProveedores.TfrmMtoProveedores.cxgrdbclmnGrdDBTabPrinNOMBRE_PROVE',
     'EDOR.Caption'
   ),
   'es-ES',
   'Nombre Comercial',
   'src/Forms/inMtoProveedores.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoProveedores.TfrmMtoProveedores.cxgrdbclmnGrdDBTabPrinNIF_CLIENTE.',
     'Caption'
   ),
   'es-ES',
   'Nif Cif',
   'src/Forms/inMtoProveedores.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoProveedores.TfrmMtoProveedores.cxgrdbclmnGrdDBTabPrinMOVIL_CLIENT',
     'E.Caption'
   ),
   'es-ES',
   'Teléfono Móvil',
   'src/Forms/inMtoProveedores.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoProveedores.TfrmMtoProveedores.cxgrdbclmnGrdDBTabPrinTELEFONO_CLI',
     'ENTE.Caption'
   ),
   'es-ES',
   'Teléfono Fijo',
   'src/Forms/inMtoProveedores.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoProveedores.TfrmMtoProveedores.cxgrdbclmnGrdDBTabPrinEMAIL_CLIENT',
     'E.Caption'
   ),
   'es-ES',
   'Email',
   'src/Forms/inMtoProveedores.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoProveedores.TfrmMtoProveedores.cxgrdbclmnGrdDBTabPrinDIRECCION1_C',
     'LIENTE.Caption'
   ),
   'es-ES',
   'Dirección',
   'src/Forms/inMtoProveedores.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoProveedores.TfrmMtoProveedores.cxgrdbclmnGrdDBTabPrinDIRECCION2_C',
     'LIENTE.Caption'
   ),
   'es-ES',
   'Más Dirección',
   'src/Forms/inMtoProveedores.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoProveedores.TfrmMtoProveedores.cxgrdbclmnGrdDBTabPrinPOBLACION_CL',
     'IENTE.Caption'
   ),
   'es-ES',
   'Población',
   'src/Forms/inMtoProveedores.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoProveedores.TfrmMtoProveedores.cxgrdbclmnGrdDBTabPrinPROVINCIA_CL',
     'IENTE.Caption'
   ),
   'es-ES',
   'Provincia',
   'src/Forms/inMtoProveedores.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoProveedores.TfrmMtoProveedores.cxgrdbclmnGrdDBTabPrinCPOSTAL_CLIE',
     'NTE.Caption'
   ),
   'es-ES',
   'Código Postal',
   'src/Forms/inMtoProveedores.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoProveedores.TfrmMtoProveedores.cxgrdbclmnGrdDBTabPrinPAIS_CLIENTE',
     '.Caption'
   ),
   'es-ES',
   'País',
   'src/Forms/inMtoProveedores.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoProveedores.TfrmMtoProveedores.cxgrdbclmnGrdDBTabPrinOBSERVACIONE',
     'S_CLIENTE.Caption'
   ),
   'es-ES',
   'Observaciones',
   'src/Forms/inMtoProveedores.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoProveedores.TfrmMtoProveedores.cxgrdbclmnGrdDBTabPrinREFERENCIA_C',
     'LIENTE.Caption'
   ),
   'es-ES',
   'Referencia',
   'src/Forms/inMtoProveedores.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoProveedores.TfrmMtoProveedores.cxgrdbclmnGrdDBTabPrinCONTACTO_CLI',
     'ENTE.Caption'
   ),
   'es-ES',
   'Contacto',
   'src/Forms/inMtoProveedores.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoProveedores.TfrmMtoProveedores.cxgrdbclmnGrdDBTabPrinTELEFONO_CON',
     'TACTO_CLIENTE.Caption'
   ),
   'es-ES',
   'Teléfono de Contacto',
   'src/Forms/inMtoProveedores.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoProveedores.TfrmMtoProveedores.cxgrdbclmnGrdDBTabPrinIBAN_CLIENTE',
     '.Caption'
   ),
   'es-ES',
   'Nro Cuenta',
   'src/Forms/inMtoProveedores.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoProveedores.TfrmMtoProveedores.lblCodigo.Caption',
   'es-ES',
   'Código',
   'src/Forms/inMtoProveedores.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoProveedores.TfrmMtoProveedores.lblRazonSocial.Caption',
   'es-ES',
   'Razón Social Fiscal',
   'src/Forms/inMtoProveedores.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoProveedores.TfrmMtoProveedores.lblNombreComercial.Caption',
   'es-ES',
   'Nombre Comercial',
   'src/Forms/inMtoProveedores.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoProveedores.TfrmMtoProveedores.lblTeléfonos.Caption',
   'es-ES',
   'Teléfonos',
   'src/Forms/inMtoProveedores.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoProveedores.TfrmMtoProveedores.lblEmail.Caption',
   'es-ES',
   'Email',
   'src/Forms/inMtoProveedores.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoProveedores.TfrmMtoProveedores.lblNif.Caption',
   'es-ES',
   'NIF/CIF',
   'src/Forms/inMtoProveedores.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoProveedores.TfrmMtoProveedores.chkActivo.Caption',
   'es-ES',
   'Activo',
   'src/Forms/inMtoProveedores.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoProveedores.TfrmMtoProveedores.tsDomicilioFiscal.Caption',
   'es-ES',
   '&1_Domicilio fiscal',
   'src/Forms/inMtoProveedores.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoProveedores.TfrmMtoProveedores.lblDireccion1.Caption',
   'es-ES',
   'Dirección 1',
   'src/Forms/inMtoProveedores.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoProveedores.TfrmMtoProveedores.lblCodPostal.Caption',
   'es-ES',
   'Código Postal',
   'src/Forms/inMtoProveedores.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoProveedores.TfrmMtoProveedores.lblPoblacion.Caption',
   'es-ES',
   'Población',
   'src/Forms/inMtoProveedores.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoProveedores.TfrmMtoProveedores.lblProvincia.Caption',
   'es-ES',
   'Provincia',
   'src/Forms/inMtoProveedores.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoProveedores.TfrmMtoProveedores.cbbPaisPrv.Properties.ListColumns[',
     '0].Caption'
   ),
   'es-ES',
   'Nombre Pais',
   'src/Forms/inMtoProveedores.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoProveedores.TfrmMtoProveedores.chkESIVA_EXENTO_INTRACOMUNITARIO_P',
     'RV.Caption'
   ),
   'es-ES',
   'IVA exento intracom.',
   'src/Forms/inMtoProveedores.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoProveedores.TfrmMtoProveedores.lblPais.Caption',
   'es-ES',
   'País',
   'src/Forms/inMtoProveedores.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoProveedores.TfrmMtoProveedores.lblDireccion2.Caption',
   'es-ES',
   'Dirección 2',
   'src/Forms/inMtoProveedores.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoProveedores.TfrmMtoProveedores.tsArticulos.Caption',
   'es-ES',
   '&2_Articulos',
   'src/Forms/inMtoProveedores.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoProveedores.TfrmMtoProveedores.btnIraArticulo.Caption',
   'es-ES',
   'Ir a Artículo',
   'src/Forms/inMtoProveedores.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoProveedores.TfrmMtoProveedores.cxgrdbclmnArticulosCODIGO_ARTICULO',
     '.Caption'
   ),
   'es-ES',
   'Código Artículo',
   'src/Forms/inMtoProveedores.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoProveedores.TfrmMtoProveedores.cxgrdbclmnArticulosDESCRIPCION_ART',
     'ICULO.Caption'
   ),
   'es-ES',
   'Descripción',
   'src/Forms/inMtoProveedores.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoProveedores.TfrmMtoProveedores.cxgrdbclmnArticulosCODIGO_FAMILIA.',
     'Caption'
   ),
   'es-ES',
   'Código Familia',
   'src/Forms/inMtoProveedores.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoProveedores.TfrmMtoProveedores.cxgrdbclmnArticulosDESCRIPCION_FAM',
     'ILIA.Caption'
   ),
   'es-ES',
   'Familia',
   'src/Forms/inMtoProveedores.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoProveedores.TfrmMtoProveedores.cxgrdbclmnArticulosTIPO_CANTIDAD_A',
     'RTICULO.Caption'
   ),
   'es-ES',
   'Tipo Cantidad',
   'src/Forms/inMtoProveedores.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoProveedores.TfrmMtoProveedores.cxgrdbclmnArticulosPRECIO_ULT_COMP',
     'RA.Caption'
   ),
   'es-ES',
   'Precio Últ. Compra',
   'src/Forms/inMtoProveedores.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoProveedores.TfrmMtoProveedores.cxgrdbclmnArticulosFECHA_VALIDEZ.C',
     'aption'
   ),
   'es-ES',
   'Fecha Últ Compra',
   'src/Forms/inMtoProveedores.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoProveedores.TfrmMtoProveedores.cxgrdbclmnArticulosESPROVEEDORPRIN',
     'CIPAL.Caption'
   ),
   'es-ES',
   'Proveedor Principal',
   'src/Forms/inMtoProveedores.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoProveedores.TfrmMtoProveedores.tsVentas.Caption',
   'es-ES',
   '&3_Ventas',
   'src/Forms/inMtoProveedores.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoProveedores.TfrmMtoProveedores.cxgrdbclmnLinFacNRO_FACTURA_LINEA.',
     'Caption'
   ),
   'es-ES',
   'Nro Fact.',
   'src/Forms/inMtoProveedores.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoProveedores.TfrmMtoProveedores.cxgrdbclmnLinFacSERIE_FACTURA_LINE',
     'A.Caption'
   ),
   'es-ES',
   'Serie',
   'src/Forms/inMtoProveedores.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoProveedores.TfrmMtoProveedores.cxgrdbclmnLinFacLINEA_FACTURA_LINE',
     'A.Caption'
   ),
   'es-ES',
   'Nro Linea',
   'src/Forms/inMtoProveedores.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoProveedores.TfrmMtoProveedores.cxgrdbclmnLinFacCANTIDAD_FACTURA_L',
     'INEA.Caption'
   ),
   'es-ES',
   'Cantidad',
   'src/Forms/inMtoProveedores.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoProveedores.TfrmMtoProveedores.cxgrdbclmnLinFacTIPO_CANTIDAD_ARTI',
     'CULO_FACTURA_LINEA.Caption'
   ),
   'es-ES',
   'Tipo Cantidad',
   'src/Forms/inMtoProveedores.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoProveedores.TfrmMtoProveedores.cxgrdbclmnLinFacCODIGO_ARTICULO_FA',
     'CTURA_LINEA.Caption'
   ),
   'es-ES',
   'Código Artículo',
   'src/Forms/inMtoProveedores.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoProveedores.TfrmMtoProveedores.cxgrdbclmnLinFacCODIGO_FAMILIA_FAC',
     'TURA_LINEA.Caption'
   ),
   'es-ES',
   'Código Familia',
   'src/Forms/inMtoProveedores.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoProveedores.TfrmMtoProveedores.cxgrdbclmnLinFacNOMBRE_FAMILIA_FAC',
     'TURA_LINEA.Caption'
   ),
   'es-ES',
   'Nombre Familia',
   'src/Forms/inMtoProveedores.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoProveedores.TfrmMtoProveedores.cxgrdbclmnLinFacDESCRIPCION_ARTICU',
     'LO_FACTURA_LINEA.Caption'
   ),
   'es-ES',
   'Descripción Artículo',
   'src/Forms/inMtoProveedores.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoProveedores.TfrmMtoProveedores.cxgrdbclmnLinFacNOMBRE_TARIFA.Caption',
   'es-ES',
   'Tarifa',
   'src/Forms/inMtoProveedores.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoProveedores.TfrmMtoProveedores.cxgrdbclmnLinFacESIMP_INCL_TARIFA_',
     'FACTURA_LINEA.Caption'
   ),
   'es-ES',
   'Imp Incl',
   'src/Forms/inMtoProveedores.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoProveedores.TfrmMtoProveedores.cxgrdbclmnLinFacPRECIOVENTA_SIVA_A',
     'RTICULO_FACTURA_LINEA.Caption'
   ),
   'es-ES',
   'Precio SIVA',
   'src/Forms/inMtoProveedores.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoProveedores.TfrmMtoProveedores.dbcLinFacNOMBRE_TIPO_IVA.Caption',
   'es-ES',
   'Tipo de IVA',
   'src/Forms/inMtoProveedores.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoProveedores.TfrmMtoProveedores.cxgrdbclmnLinFacPORCEN_IVA_FACTURA',
     '_LINEA.Caption'
   ),
   'es-ES',
   '% IVA',
   'src/Forms/inMtoProveedores.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoProveedores.TfrmMtoProveedores.cxgrdbclmnLinFacPRECIOVENTA_CIVA_A',
     'RTICULO_FACTURA_LINEA.Caption'
   ),
   'es-ES',
   'Precio CIVA',
   'src/Forms/inMtoProveedores.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoProveedores.TfrmMtoProveedores.cxgrdbclmnLinFacTOTAL_FACTURA_LINE',
     'A.Caption'
   ),
   'es-ES',
   'Total Linea',
   'src/Forms/inMtoProveedores.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoProveedores.TfrmMtoProveedores.cxgrdbclmnLinFacFECHA_ENTREGA_FACT',
     'URA_LINEA.Caption'
   ),
   'es-ES',
   'Fecha Entrega',
   'src/Forms/inMtoProveedores.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoProveedores.TfrmMtoProveedores.dbcLinFacCODIGO_TARIFA_FACTURA_LIN',
     'EA.Caption'
   ),
   'es-ES',
   'Tarifa Empleada',
   'src/Forms/inMtoProveedores.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoProveedores.TfrmMtoProveedores.btnIraFactura.Caption',
   'es-ES',
   'Ir a Borrador',
   'src/Forms/inMtoProveedores.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoProveedores.TfrmMtoProveedores.btnIraCliente.Caption',
   'es-ES',
   'Ir a Cliente',
   'src/Forms/inMtoProveedores.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoProveedores.TfrmMtoProveedores.btnExportar.Caption',
   'es-ES',
   '&Exp Excel',
   'src/Forms/inMtoProveedores.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoProveedores.TfrmMtoProveedores.btnIraArticuloVentas.Caption',
   'es-ES',
   'Ir a Artículo',
   'src/Forms/inMtoProveedores.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoProveedores.TfrmMtoProveedores.tsMasDatos.Caption',
   'es-ES',
   '&4_Más datos',
   'src/Forms/inMtoProveedores.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoProveedores.TfrmMtoProveedores.lblObservaciones.Caption',
   'es-ES',
   'Observaciones',
   'src/Forms/inMtoProveedores.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoProveedores.TfrmMtoProveedores.lblReferencia.Caption',
   'es-ES',
   'Referencia',
   'src/Forms/inMtoProveedores.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoProveedores.TfrmMtoProveedores.lblContacto.Caption',
   'es-ES',
   'Contacto',
   'src/Forms/inMtoProveedores.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoProveedores.TfrmMtoProveedores.lblNroCuenta.Caption',
   'es-ES',
   'IBAN Bancario',
   'src/Forms/inMtoProveedores.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoProveedores.TfrmMtoProveedores.lblTelefonoContacto.Caption',
   'es-ES',
   'Teléfono Contacto',
   'src/Forms/inMtoProveedores.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoProveedores.TfrmMtoProveedores.tsOtros.Caption',
   'es-ES',
   '&5_Otros',
   'src/Forms/inMtoProveedores.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoProveedores.TfrmMtoProveedores.lblUsuarioAlta.Caption',
   'es-ES',
   'Usuario Alta',
   'src/Forms/inMtoProveedores.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoProveedores.TfrmMtoProveedores.lblInstanteAlta.Caption',
   'es-ES',
   'Instante Alta',
   'src/Forms/inMtoProveedores.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoProveedores.TfrmMtoProveedores.lblInstanteModif.Caption',
   'es-ES',
   'Instante Modificación',
   'src/Forms/inMtoProveedores.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoProveedores.TfrmMtoProveedores.lblUsuarioModif.Caption',
   'es-ES',
   'Usuario Últ. Modif',
   'src/Forms/inMtoProveedores.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoProveedores.TfrmMtoProveedores.lblTextoLegal11.Caption',
   'es-ES',
   'Orden en Listados',
   'src/Forms/inMtoProveedores.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoProveedores.TfrmMtoProveedores.tsCompras.Caption',
   'es-ES',
   '&6_Compras',
   'src/Forms/inMtoProveedores.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoProveedores.TfrmMtoProveedores.gbDefectosCompras.Caption',
   'es-ES',
   ' Defectos para sesiones de compra ',
   'src/Forms/inMtoProveedores.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoProveedores.TfrmMtoProveedores.lblMargenPrv.Caption',
   'es-ES',
   'Margen %',
   'src/Forms/inMtoProveedores.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoProveedores.TfrmMtoProveedores.chkVariosTiposIvaPrv.Caption',
   'es-ES',
   'Varios tipos IVA artículos',
   'src/Forms/inMtoProveedores.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoProveedores.TfrmMtoProveedores.lblSistemaTallasPrv.Caption',
   'es-ES',
   'Sistema tallas',
   'src/Forms/inMtoProveedores.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoProveedores.TfrmMtoProveedores.lblDefectosInfo.Caption',
   'es-ES',
   CONCAT(
     'Se aplican al elegir este proveedor en una sesión de compra (el ',
     'sistema de tallas solo propone el defecto; cada línea lo puede ',
     'cambiar).'
   ),
   'src/Forms/inMtoProveedores.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoProveedores.TfrmMtoProveedores.gbKitsPrv.Caption',
   'es-ES',
   ' Kits de cantidades por talla ',
   'src/Forms/inMtoProveedores.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoProveedores.TfrmMtoProveedores.btnAddKit.Caption',
   'es-ES',
   '+ Kit',
   'src/Forms/inMtoProveedores.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoProveedores.TfrmMtoProveedores.btnDelKit.Caption',
   'es-ES',
   '- Kit',
   'src/Forms/inMtoProveedores.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoProveedores.TfrmMtoProveedores.btnGenerarTallasKit.Caption',
   'es-ES',
   'Añadir todas las tallas',
   'src/Forms/inMtoProveedores.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoProveedores.TfrmMtoProveedores.btnAddKitDet.Caption',
   'es-ES',
   '+ Talla',
   'src/Forms/inMtoProveedores.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoProveedores.TfrmMtoProveedores.btnDelKitDet.Caption',
   'es-ES',
   '- Talla',
   'src/Forms/inMtoProveedores.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoProveedores.TfrmMtoProveedores.dbcKitCodigo.Caption',
   'es-ES',
   'Código',
   'src/Forms/inMtoProveedores.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoProveedores.TfrmMtoProveedores.dbcKitNombre.Caption',
   'es-ES',
   'Nombre',
   'src/Forms/inMtoProveedores.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoProveedores.TfrmMtoProveedores.dbcKitSistema.Caption',
   'es-ES',
   'Sistema tallas',
   'src/Forms/inMtoProveedores.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoProveedores.TfrmMtoProveedores.dbcKitSistema.Properties.ListColum',
     'ns[0].Caption'
   ),
   'es-ES',
   'Sistema',
   'src/Forms/inMtoProveedores.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoProveedores.TfrmMtoProveedores.dbcKitDetValor.Caption',
   'es-ES',
   'Talla',
   'src/Forms/inMtoProveedores.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoProveedores.TfrmMtoProveedores.dbcKitDetCantidad.Caption',
   'es-ES',
   'Cantidad',
   'src/Forms/inMtoProveedores.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoProveedores.TfrmMtoProveedores.dbcKitDetOrden.Caption',
   'es-ES',
   'Orden',
   'src/Forms/inMtoProveedores.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoProveedores.TfrmMtoProveedores.tsPagos.Caption',
   'es-ES',
   '&7_Pagos',
   'src/Forms/inMtoProveedores.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoProveedores.TfrmMtoProveedores.lblFormaPagoPrv.Caption',
   'es-ES',
   'Forma de pago',
   'src/Forms/inMtoProveedores.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoProveedores.TfrmMtoProveedores.lblEmpBanPrv.Caption',
   'es-ES',
   'Banco para pagos (empresa)',
   'src/Forms/inMtoProveedores.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoProveedores.TfrmMtoProveedores.cbbEmpBanPrv.Properties.ListColumn',
     's[0].Caption'
   ),
   'es-ES',
   'Cuenta',
   'src/Forms/inMtoProveedores.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoProveedores.TfrmMtoProveedores.cbbEmpBanPrv.Properties.ListColumn',
     's[1].Caption'
   ),
   'es-ES',
   'IBAN',
   'src/Forms/inMtoProveedores.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoProveedores.TfrmMtoProveedores.cbbEmpBanPrv.Properties.ListColumn',
     's[2].Caption'
   ),
   'es-ES',
   'Banco',
   'src/Forms/inMtoProveedores.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoProveedores.TfrmMtoProveedores.cbbEmpBanPrv.Properties.ListColumn',
     's[3].Caption'
   ),
   'es-ES',
   'Empresa',
   'src/Forms/inMtoProveedores.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoProveedores.TfrmMtoProveedores.btnNuevoProveedor.Caption',
   'es-ES',
   '&Nuevo Proveedor',
   'src/Forms/inMtoProveedores.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoProveedores.TfrmMtoProveedores.actArticulos.Caption',
   'es-ES',
   'Articulos',
   'src/Forms/inMtoProveedores.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoProveedores.TfrmMtoProveedores.actFacturas.Caption',
   'es-ES',
   'Borradores',
   'src/Forms/inMtoProveedores.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoProveedores.TfrmMtoProveedores.actClientes.Caption',
   'es-ES',
   'Clientes',
   'src/Forms/inMtoProveedores.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema')
ON DUPLICATE KEY UPDATE
  `TEXTO_TRAD` = VALUES(`TEXTO_TRAD`),
  `CONTEXTO_TRAD` = VALUES(`CONTEXTO_TRAD`),
  `ESACTIVO_TRAD` = VALUES(`ESACTIVO_TRAD`),
  `INSTANTE_MODIF` = CURRENT_TIMESTAMP,
  `USUARIO_MODIF` = VALUES(`USUARIO_ALTA`);
