-- Catálogo de textos españoles extraídos de los DFM.
-- Generado por generar_traducciones_dfm.ps1.
INSERT INTO `fza_traducciones` (
  `CLAVE_TRAD`, `IDIOMA_TRAD`, `TEXTO_TRAD`, `CONTEXTO_TRAD`,
  `ESACTIVO_TRAD`, `INSTANTE_ALTA`, `USUARIO_ALTA`
) VALUES
  ('inMtoTraspasoOpe.TfrmMtoOpeTraspaso.Caption',
   'es-ES',
   'Traspasos',
   'src/Caja/Forms/inMtoTraspasoOpe.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoTraspasoOpe.TfrmMtoOpeTraspaso.btnModoTraspaso.Caption',
   'es-ES',
   'Traspaso',
   'src/Caja/Forms/inMtoTraspasoOpe.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoTraspasoOpe.TfrmMtoOpeTraspaso.btnModoSolicitar.Caption',
   'es-ES',
   'F6 Solicitar a otro almacén',
   'src/Caja/Forms/inMtoTraspasoOpe.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoTraspasoOpe.TfrmMtoOpeTraspaso.btnModoAtender.Caption',
   'es-ES',
   'F8 Atender solicitudes',
   'src/Caja/Forms/inMtoTraspasoOpe.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoTraspasoOpe.TfrmMtoOpeTraspaso.lblOrigen.Caption',
   'es-ES',
   'ALMACÉN ORIGEN',
   'src/Caja/Forms/inMtoTraspasoOpe.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoTraspasoOpe.TfrmMtoOpeTraspaso.lblDestino.Caption',
   'es-ES',
   'ALMACÉN DESTINO',
   'src/Caja/Forms/inMtoTraspasoOpe.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoTraspasoOpe.TfrmMtoOpeTraspaso.lblEmpleado.Caption',
   'es-ES',
   'Empleado (responsable)',
   'src/Caja/Forms/inMtoTraspasoOpe.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoTraspasoOpe.TfrmMtoOpeTraspaso.lblTotal.Caption',
   'es-ES',
   'Importe traspaso: 0,00',
   'src/Caja/Forms/inMtoTraspasoOpe.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoTraspasoOpe.TfrmMtoOpeTraspaso.btnF11.Caption',
   'es-ES',
   'F11 Sin ticket',
   'src/Caja/Forms/inMtoTraspasoOpe.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoTraspasoOpe.TfrmMtoOpeTraspaso.btnF12.Caption',
   'es-ES',
   'F12 Con ticket',
   'src/Caja/Forms/inMtoTraspasoOpe.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema')
ON DUPLICATE KEY UPDATE
  `TEXTO_TRAD` = VALUES(`TEXTO_TRAD`),
  `CONTEXTO_TRAD` = VALUES(`CONTEXTO_TRAD`),
  `ESACTIVO_TRAD` = VALUES(`ESACTIVO_TRAD`),
  `INSTANTE_MODIF` = CURRENT_TIMESTAMP,
  `USUARIO_MODIF` = VALUES(`USUARIO_ALTA`);
