-- Catálogo de textos españoles extraídos de los DFM.
-- Generado por generar_traducciones_dfm.ps1.
INSERT INTO `fza_traducciones` (
  `CLAVE_TRAD`, `IDIOMA_TRAD`, `TEXTO_TRAD`, `CONTEXTO_TRAD`,
  `ESACTIVO_TRAD`, `INSTANTE_ALTA`, `USUARIO_ALTA`
) VALUES
  ('inMtoCajaArqueosHist.TfrmMtoCajaArqueosHist.Caption',
   'es-ES',
   'Histórico de Arqueos de Caja',
   'src/Caja/Forms/inMtoCajaArqueosHist.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoCajaArqueosHist.TfrmMtoCajaArqueosHist.cxGrdDBTabPrinCODIGO_ARQ.C',
     'aption'
   ),
   'es-ES',
   'Código Arqueo',
   'src/Caja/Forms/inMtoCajaArqueosHist.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoCajaArqueosHist.TfrmMtoCajaArqueosHist.cxGrdDBTabPrinCODIGO_EMP_A',
     'RQ.Caption'
   ),
   'es-ES',
   'Empresa',
   'src/Caja/Forms/inMtoCajaArqueosHist.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoCajaArqueosHist.TfrmMtoCajaArqueosHist.cxGrdDBTabPrinCODIGO_ALM_A',
     'RQ.Caption'
   ),
   'es-ES',
   'Almacén',
   'src/Caja/Forms/inMtoCajaArqueosHist.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoCajaArqueosHist.TfrmMtoCajaArqueosHist.cxGrdDBTabPrinCODIGO_CAJA_',
     'ARQ.Caption'
   ),
   'es-ES',
   'Caja',
   'src/Caja/Forms/inMtoCajaArqueosHist.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoCajaArqueosHist.TfrmMtoCajaArqueosHist.cxGrdDBTabPrinFECHA_DESDE_',
     'ARQ.Caption'
   ),
   'es-ES',
   'Fecha Desde',
   'src/Caja/Forms/inMtoCajaArqueosHist.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoCajaArqueosHist.TfrmMtoCajaArqueosHist.cxGrdDBTabPrinFECHA_HASTA_',
     'ARQ.Caption'
   ),
   'es-ES',
   'Fecha Hasta',
   'src/Caja/Forms/inMtoCajaArqueosHist.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaArqueosHist.TfrmMtoCajaArqueosHist.cxGrdDBTabPrinFASE_ARQ.Caption',
   'es-ES',
   'Fase',
   'src/Caja/Forms/inMtoCajaArqueosHist.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoCajaArqueosHist.TfrmMtoCajaArqueosHist.cxGrdDBTabPrinCANTIDAD_VEN',
     'TAS_ARQ.Caption'
   ),
   'es-ES',
   'Ventas',
   'src/Caja/Forms/inMtoCajaArqueosHist.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoCajaArqueosHist.TfrmMtoCajaArqueosHist.cxGrdDBTabPrinTOTAL_NETO_A',
     'RQ.Caption'
   ),
   'es-ES',
   'Neto',
   'src/Caja/Forms/inMtoCajaArqueosHist.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoCajaArqueosHist.TfrmMtoCajaArqueosHist.cxGrdDBTabPrinTOTAL_VENTAS',
     '_ARQ.Caption'
   ),
   'es-ES',
   'Total Ventas',
   'src/Caja/Forms/inMtoCajaArqueosHist.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoCajaArqueosHist.TfrmMtoCajaArqueosHist.cxGrdDBTabPrinTOTAL_EFECTI',
     'VO_CAJA_ARQ.Caption'
   ),
   'es-ES',
   'Efectivo Caja',
   'src/Caja/Forms/inMtoCajaArqueosHist.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoCajaArqueosHist.TfrmMtoCajaArqueosHist.cxGrdDBTabPrinTOTAL_OTROS_',
     'INGRESOS_ARQ.Caption'
   ),
   'es-ES',
   'Otros Ingresos',
   'src/Caja/Forms/inMtoCajaArqueosHist.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoCajaArqueosHist.TfrmMtoCajaArqueosHist.cxGrdDBTabPrinTOTAL_SALDO_',
     'RECONTAR_ARQ.Caption'
   ),
   'es-ES',
   'Saldo Teórico',
   'src/Caja/Forms/inMtoCajaArqueosHist.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoCajaArqueosHist.TfrmMtoCajaArqueosHist.cxGrdDBTabPrinTOTAL_RECUEN',
     'TO_ARQ.Caption'
   ),
   'es-ES',
   'Recuento',
   'src/Caja/Forms/inMtoCajaArqueosHist.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoCajaArqueosHist.TfrmMtoCajaArqueosHist.cxGrdDBTabPrinDIFERENCIA_T',
     'OTAL_ARQ.Caption'
   ),
   'es-ES',
   'Diferencia',
   'src/Caja/Forms/inMtoCajaArqueosHist.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoCajaArqueosHist.TfrmMtoCajaArqueosHist.cxGrdDBTabPrinOBSERVACIONE',
     'S_ARQ.Caption'
   ),
   'es-ES',
   'Observaciones',
   'src/Caja/Forms/inMtoCajaArqueosHist.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoCajaArqueosHist.TfrmMtoCajaArqueosHist.cxGrdDBTabPrinINSTANTE_ALT',
     'A.Caption'
   ),
   'es-ES',
   'Instante Alta',
   'src/Caja/Forms/inMtoCajaArqueosHist.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoCajaArqueosHist.TfrmMtoCajaArqueosHist.cxGrdDBTabPrinUSUARIO_ALTA',
     '.Caption'
   ),
   'es-ES',
   'Usuario Alta',
   'src/Caja/Forms/inMtoCajaArqueosHist.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaArqueosHist.TfrmMtoCajaArqueosHist.btnExportarExcel.Caption',
   'es-ES',
   'Exportar Excel',
   'src/Caja/Forms/inMtoCajaArqueosHist.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaArqueosHist.TfrmMtoCajaArqueosHist.btnImprimirInforme.Caption',
   'es-ES',
   'Imprimir Informe A4',
   'src/Caja/Forms/inMtoCajaArqueosHist.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoCajaArqueosHist.TfrmMtoCajaArqueosHist.dlgGuardar.FileTypes[0].Di',
     'splayName'
   ),
   'es-ES',
   'Excel (*.xlsx)',
   'src/Caja/Forms/inMtoCajaArqueosHist.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaFaseCobro.TfrmMtoCajaFaseCobro.Caption',
   'es-ES',
   'Fase de cobro',
   'src/Caja/Forms/inMtoCajaFaseCobro.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaFaseCobro.TfrmMtoCajaFaseCobro.lblImporteDtoLineal.Caption',
   'es-ES',
   'Imp dto. Lineal',
   'src/Caja/Forms/inMtoCajaFaseCobro.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaFaseCobro.TfrmMtoCajaFaseCobro.lblImporteTotalAPagar.Caption',
   'es-ES',
   'Imp TOTAL a pagar',
   'src/Caja/Forms/inMtoCajaFaseCobro.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaFaseCobro.TfrmMtoCajaFaseCobro.lblDescuento.Caption',
   'es-ES',
   '% Descuento',
   'src/Caja/Forms/inMtoCajaFaseCobro.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaFaseCobro.TfrmMtoCajaFaseCobro.lblSuma.Caption',
   'es-ES',
   'Suma',
   'src/Caja/Forms/inMtoCajaFaseCobro.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaFaseCobro.TfrmMtoCajaFaseCobro.lblPendienteCobro.Caption',
   'es-ES',
   'Pendiente de cobro',
   'src/Caja/Forms/inMtoCajaFaseCobro.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaFaseCobro.TfrmMtoCajaFaseCobro.lblImporteACuenta.Caption',
   'es-ES',
   'Importe a dejar A CUENTA',
   'src/Caja/Forms/inMtoCajaFaseCobro.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaFaseCobro.TfrmMtoCajaFaseCobro.lblValeEmitido.Caption',
   'es-ES',
   'Vale Emitido',
   'src/Caja/Forms/inMtoCajaFaseCobro.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaFaseCobro.TfrmMtoCajaFaseCobro.lblValeRecogido.Caption',
   'es-ES',
   'Vale Recogido',
   'src/Caja/Forms/inMtoCajaFaseCobro.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaFaseCobro.TfrmMtoCajaFaseCobro.cxgrdbclmnCodigo.Caption',
   'es-ES',
   'Código',
   'src/Caja/Forms/inMtoCajaFaseCobro.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaFaseCobro.TfrmMtoCajaFaseCobro.dbmDescripcion.Caption',
   'es-ES',
   'Descripción',
   'src/Caja/Forms/inMtoCajaFaseCobro.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaFaseCobro.TfrmMtoCajaFaseCobro.dbmImporte.Caption',
   'es-ES',
   'Importe Entregado',
   'src/Caja/Forms/inMtoCajaFaseCobro.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaFaseCobro.TfrmMtoCajaFaseCobro.lblPendienteCobroAlt.Caption',
   'es-ES',
   'Pendiente de cobro',
   'src/Caja/Forms/inMtoCajaFaseCobro.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaFaseCobro.TfrmMtoCajaFaseCobro.lblDevolucionCambio.Caption',
   'es-ES',
   'Devolución de cambio',
   'src/Caja/Forms/inMtoCajaFaseCobro.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaFaseCobro.TfrmMtoCajaFaseCobro.btnSinTicket.Caption',
   'es-ES',
   'Si&n ticket',
   'src/Caja/Forms/inMtoCajaFaseCobro.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaFaseCobro.TfrmMtoCajaFaseCobro.btnF11.Caption',
   'es-ES',
   'F11',
   'src/Caja/Forms/inMtoCajaFaseCobro.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaFaseCobro.TfrmMtoCajaFaseCobro.btnConTicket.Caption',
   'es-ES',
   '&Con ticket',
   'src/Caja/Forms/inMtoCajaFaseCobro.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaFaseCobro.TfrmMtoCajaFaseCobro.btnF12.Caption',
   'es-ES',
   'F12',
   'src/Caja/Forms/inMtoCajaFaseCobro.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaFaseCobro.TfrmMtoCajaFaseCobro.btnSinPrecios.Caption',
   'es-ES',
   'Sin &precios',
   'src/Caja/Forms/inMtoCajaFaseCobro.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaFaseCobro.TfrmMtoCajaFaseCobro.btnF10.Caption',
   'es-ES',
   'F10',
   'src/Caja/Forms/inMtoCajaFaseCobro.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaFaseCobro.TfrmMtoCajaFaseCobro.btnDeposito.Caption',
   'es-ES',
   '&Préstamo',
   'src/Caja/Forms/inMtoCajaFaseCobro.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaFaseCobro.TfrmMtoCajaFaseCobro.btnF7.Caption',
   'es-ES',
   'F7',
   'src/Caja/Forms/inMtoCajaFaseCobro.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaFaseCobro.TfrmMtoCajaFaseCobro.btnF8.Caption',
   'es-ES',
   'F8',
   'src/Caja/Forms/inMtoCajaFaseCobro.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaFaseCobro.TfrmMtoCajaFaseCobro.btnFactura.Caption',
   'es-ES',
   '&Borrador',
   'src/Caja/Forms/inMtoCajaFaseCobro.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaFaseCobro.TfrmMtoCajaFaseCobro.btnF6.Caption',
   'es-ES',
   'F6',
   'src/Caja/Forms/inMtoCajaFaseCobro.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaFaseCobro.TfrmMtoCajaFaseCobro.btnBuscarVale.Caption',
   'es-ES',
   '&Buscar Vale',
   'src/Caja/Forms/inMtoCajaFaseCobro.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaFaseCobro.TfrmMtoCajaFaseCobro.btnMasDatos.Caption',
   'es-ES',
   '&Más datos',
   'src/Caja/Forms/inMtoCajaFaseCobro.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaFaseCobro.TfrmMtoCajaFaseCobro.btnF2.Caption',
   'es-ES',
   'F2',
   'src/Caja/Forms/inMtoCajaFaseCobro.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaFaseCobro.TfrmMtoCajaFaseCobro.btnBuscarT.Caption',
   'es-ES',
   'Rellenar',
   'src/Caja/Forms/inMtoCajaFaseCobro.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaFaseCobro.TfrmMtoCajaFaseCobro.btnF3.Caption',
   'es-ES',
   'F3',
   'src/Caja/Forms/inMtoCajaFaseCobro.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaFaseCobro.TfrmMtoCajaFaseCobro.btnAtras.Caption',
   'es-ES',
   'Atrás',
   'src/Caja/Forms/inMtoCajaFaseCobro.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaFaseCobro.TfrmMtoCajaFaseCobro.btnESC.Caption',
   'es-ES',
   'ESC',
   'src/Caja/Forms/inMtoCajaFaseCobro.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaFaseCobro.TfrmMtoCajaFaseCobro.lblNumDoc.Caption',
   'es-ES',
   'Nº doc. venta',
   'src/Caja/Forms/inMtoCajaFaseCobro.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaFaseCobro.TfrmMtoCajaFaseCobro.chkEnviarEmail.Caption',
   'es-ES',
   'Enviar por e-mail',
   'src/Caja/Forms/inMtoCajaFaseCobro.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaFaseCobro.TfrmMtoCajaFaseCobro.actSalir.Caption',
   'es-ES',
   'Salir',
   'src/Caja/Forms/inMtoCajaFaseCobro.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaFaseCobro.TfrmMtoCajaFaseCobro.actRellenar.Caption',
   'es-ES',
   'Rellenar',
   'src/Caja/Forms/inMtoCajaFaseCobro.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaFaseCobro.TfrmMtoCajaFaseCobro.actBuscarVale.Caption',
   'es-ES',
   'BuscarVale',
   'src/Caja/Forms/inMtoCajaFaseCobro.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaFaseCobro.TfrmMtoCajaFaseCobro.actSinTicket.Caption',
   'es-ES',
   'SinTicket',
   'src/Caja/Forms/inMtoCajaFaseCobro.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaFaseCobro.TfrmMtoCajaFaseCobro.actConTicket.Caption',
   'es-ES',
   'ConTicket',
   'src/Caja/Forms/inMtoCajaFaseCobro.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaFaseCobro.TfrmMtoCajaFaseCobro.actSinPrecios.Caption',
   'es-ES',
   'SinPrecios',
   'src/Caja/Forms/inMtoCajaFaseCobro.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaFaseCobro.TfrmMtoCajaFaseCobro.actDepositoCliente.Caption',
   'es-ES',
   'DepositoCliente',
   'src/Caja/Forms/inMtoCajaFaseCobro.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaFaseCobro.TfrmMtoCajaFaseCobro.actFactura.Caption',
   'es-ES',
   'Borrador',
   'src/Caja/Forms/inMtoCajaFaseCobro.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaFormasPago.TfrmMtoCajaFormasPago.Caption',
   'es-ES',
   'Formas de Pago Caja',
   'src/Caja/Forms/inMtoCajaFormasPago.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoCajaFormasPago.TfrmMtoCajaFormasPago.cxGrdDBTabPrinCODIGO_FP_CFP.',
     'Caption'
   ),
   'es-ES',
   'Código',
   'src/Caja/Forms/inMtoCajaFormasPago.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoCajaFormasPago.TfrmMtoCajaFormasPago.cxGrdDBTabPrinDESCRIPCION_FO',
     'RMA_PAGO_CFP.Caption'
   ),
   'es-ES',
   'Descripción',
   'src/Caja/Forms/inMtoCajaFormasPago.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoCajaFormasPago.TfrmMtoCajaFormasPago.cxGrdDBTabPrinESACTIVO_FORMA',
     '_PAGO_CFP.Caption'
   ),
   'es-ES',
   'Activo',
   'src/Caja/Forms/inMtoCajaFormasPago.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoCajaFormasPago.TfrmMtoCajaFormasPago.cxGrdDBTabPrinORDEN_VISUAL_F',
     'ORMA_PAGO_CFP.Caption'
   ),
   'es-ES',
   'Orden F12',
   'src/Caja/Forms/inMtoCajaFormasPago.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoCajaFormasPago.TfrmMtoCajaFormasPago.cxGrdDBTabPrinESREQ_REFERENC',
     'IA_FORMA_PAGO_CFP.Caption'
   ),
   'es-ES',
   'Pide Referencia',
   'src/Caja/Forms/inMtoCajaFormasPago.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoCajaFormasPago.TfrmMtoCajaFormasPago.cxGrdDBTabPrinESCRIPTO_FORMA',
     '_PAGO_CFP.Caption'
   ),
   'es-ES',
   'Cripto',
   'src/Caja/Forms/inMtoCajaFormasPago.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoCajaFormasPago.TfrmMtoCajaFormasPago.cxGrdDBTabPrinESDIVISA_FORMA',
     '_PAGO_CFP.Caption'
   ),
   'es-ES',
   'Divisa',
   'src/Caja/Forms/inMtoCajaFormasPago.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoCajaFormasPago.TfrmMtoCajaFormasPago.cxGrdDBTabPrinESDEVUELVE_CAM',
     'BIO_FORMA_PAGO_CFP.Caption'
   ),
   'es-ES',
   'Devuelve Cambio',
   'src/Caja/Forms/inMtoCajaFormasPago.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoCajaFormasPago.TfrmMtoCajaFormasPago.cxGrdDBTabPrinESABRE_CAJON_F',
     'ORMA_PAGO_CFP.Caption'
   ),
   'es-ES',
   'Abre Cajón',
   'src/Caja/Forms/inMtoCajaFormasPago.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoCajaFormasPago.TfrmMtoCajaFormasPago.cxGrdDBTabPrinPORCENTAJE_COM',
     'ISION_FORMA_PAGO_CFP.Caption'
   ),
   'es-ES',
   '% Comisión',
   'src/Caja/Forms/inMtoCajaFormasPago.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoCajaFormasPago.TfrmMtoCajaFormasPago.cxGrdDBTabPrinESCOMISION_INC',
     'L_FORMA_PAGO_CFP.Caption'
   ),
   'es-ES',
   'Comisión Incl.',
   'src/Caja/Forms/inMtoCajaFormasPago.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoCajaFormasPago.TfrmMtoCajaFormasPago.cxGrdDBTabPrinNUM_COD_DIGIT_',
     'FORMA_PAGO_CFP.Caption'
   ),
   'es-ES',
   'Cod. Dígit.',
   'src/Caja/Forms/inMtoCajaFormasPago.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoCajaFormasPago.TfrmMtoCajaFormasPago.cxGrdDBTabPrinRED_BLOCKCHAIN',
     '_FORMA_PAGO_CFP.Caption'
   ),
   'es-ES',
   'Red Blockchain',
   'src/Caja/Forms/inMtoCajaFormasPago.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoCajaFormasPago.TfrmMtoCajaFormasPago.cxGrdDBTabPrinHASH_BLOCKCHAI',
     'N_FORMA_PAGO_CFP.Caption'
   ),
   'es-ES',
   'Hash Blockchain',
   'src/Caja/Forms/inMtoCajaFormasPago.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaFormasPago.TfrmMtoCajaFormasPago.lblCodigo.Caption',
   'es-ES',
   'Código',
   'src/Caja/Forms/inMtoCajaFormasPago.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaFormasPago.TfrmMtoCajaFormasPago.lblDescripcion.Caption',
   'es-ES',
   'Descripción',
   'src/Caja/Forms/inMtoCajaFormasPago.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoCajaFormasPago.TfrmMtoCajaFormasPago.chkESACTIVO_FORMA_PAGO_CFP.C',
     'aption'
   ),
   'es-ES',
   'Activo',
   'src/Caja/Forms/inMtoCajaFormasPago.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaFormasPago.TfrmMtoCajaFormasPago.lblOrdenVisual.Caption',
   'es-ES',
   'Orden F12',
   'src/Caja/Forms/inMtoCajaFormasPago.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaFormasPago.TfrmMtoCajaFormasPago.tsComportamiento.Caption',
   'es-ES',
   '&0_Comportamiento',
   'src/Caja/Forms/inMtoCajaFormasPago.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoCajaFormasPago.TfrmMtoCajaFormasPago.chkESREQ_REFERENCIA_FORMA_PA',
     'GO_CFP.Caption'
   ),
   'es-ES',
   'Pide referencia (bono, autorización tarjeta...)',
   'src/Caja/Forms/inMtoCajaFormasPago.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoCajaFormasPago.TfrmMtoCajaFormasPago.chkESDIVISA_FORMA_PAGO_CFP.C',
     'aption'
   ),
   'es-ES',
   'Es divisa (USD, GBP...)',
   'src/Caja/Forms/inMtoCajaFormasPago.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoCajaFormasPago.TfrmMtoCajaFormasPago.chkESCRIPTO_FORMA_PAGO_CFP.C',
     'aption'
   ),
   'es-ES',
   'Es criptomoneda',
   'src/Caja/Forms/inMtoCajaFormasPago.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoCajaFormasPago.TfrmMtoCajaFormasPago.chkESDEVUELVE_CAMBIO_FORMA_P',
     'AGO_CFP.Caption'
   ),
   'es-ES',
   'Permite dar cambio',
   'src/Caja/Forms/inMtoCajaFormasPago.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoCajaFormasPago.TfrmMtoCajaFormasPago.chkESABRE_CAJON_FORMA_PAGO_C',
     'FP.Caption'
   ),
   'es-ES',
   'Abre cajón al cobrar',
   'src/Caja/Forms/inMtoCajaFormasPago.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaFormasPago.TfrmMtoCajaFormasPago.lblPorcentajeComision.Caption',
   'es-ES',
   '% Comisión',
   'src/Caja/Forms/inMtoCajaFormasPago.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoCajaFormasPago.TfrmMtoCajaFormasPago.chkESCOMISION_INCL_FORMA_PAG',
     'O_CFP.Caption'
   ),
   'es-ES',
   'Comisión incluida en importe',
   'src/Caja/Forms/inMtoCajaFormasPago.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaFormasPago.TfrmMtoCajaFormasPago.lblNumCodDigit.Caption',
   'es-ES',
   'Cod. dig. teclado',
   'src/Caja/Forms/inMtoCajaFormasPago.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaFormasPago.TfrmMtoCajaFormasPago.tsBlockchain.Caption',
   'es-ES',
   '&1_Blockchain',
   'src/Caja/Forms/inMtoCajaFormasPago.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaFormasPago.TfrmMtoCajaFormasPago.lblRedBlockchain.Caption',
   'es-ES',
   'Red blockchain',
   'src/Caja/Forms/inMtoCajaFormasPago.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaFormasPago.TfrmMtoCajaFormasPago.lblHashBlockchain.Caption',
   'es-ES',
   'Hash blockchain',
   'src/Caja/Forms/inMtoCajaFormasPago.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaFormasPago.TfrmMtoCajaFormasPago.tsAuditoria.Caption',
   'es-ES',
   '&2_Auditoría',
   'src/Caja/Forms/inMtoCajaFormasPago.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaFormasPago.TfrmMtoCajaFormasPago.lblUsuarioAlta.Caption',
   'es-ES',
   'Usuario Alta',
   'src/Caja/Forms/inMtoCajaFormasPago.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaFormasPago.TfrmMtoCajaFormasPago.lblInstanteAlta.Caption',
   'es-ES',
   'Instante Alta',
   'src/Caja/Forms/inMtoCajaFormasPago.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaFormasPago.TfrmMtoCajaFormasPago.lblUsuarioModif.Caption',
   'es-ES',
   'Usuario Modificación',
   'src/Caja/Forms/inMtoCajaFormasPago.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaFormasPago.TfrmMtoCajaFormasPago.lblInstanteModif.Caption',
   'es-ES',
   'Instante Modificación',
   'src/Caja/Forms/inMtoCajaFormasPago.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaMenu.TfrmMtoMenuCaja.Caption',
   'es-ES',
   'Menú de Caja',
   'src/Caja/Forms/inMtoCajaMenu.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaMenu.TfrmMtoMenuCaja.lblF5.Caption',
   'es-ES',
   'F5',
   'src/Caja/Forms/inMtoCajaMenu.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaMenu.TfrmMtoMenuCaja.lblF10.Caption',
   'es-ES',
   'F10',
   'src/Caja/Forms/inMtoCajaMenu.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaMenu.TfrmMtoMenuCaja.lblBuscarModificar.Caption',
   'es-ES',
   'Buscar / Modificar',
   'src/Caja/Forms/inMtoCajaMenu.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaMenu.TfrmMtoMenuCaja.lblVentas.Caption',
   'es-ES',
   'Ventas',
   'src/Caja/Forms/inMtoCajaMenu.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaMenu.TfrmMtoMenuCaja.lblF6.Caption',
   'es-ES',
   'F6',
   'src/Caja/Forms/inMtoCajaMenu.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaMenu.TfrmMtoMenuCaja.lblEntradaCambio.Caption',
   'es-ES',
   'Entrada de Cambio',
   'src/Caja/Forms/inMtoCajaMenu.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaMenu.TfrmMtoMenuCaja.lblF7.Caption',
   'es-ES',
   'F7',
   'src/Caja/Forms/inMtoCajaMenu.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaMenu.TfrmMtoMenuCaja.lblGastosCaja.Caption',
   'es-ES',
   'Gastos por caja',
   'src/Caja/Forms/inMtoCajaMenu.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaMenu.TfrmMtoMenuCaja.lblArqueo.Caption',
   'es-ES',
   'Arqueo',
   'src/Caja/Forms/inMtoCajaMenu.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaMenu.TfrmMtoMenuCaja.lblF11.Caption',
   'es-ES',
   'F11',
   'src/Caja/Forms/inMtoCajaMenu.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaMenu.TfrmMtoMenuCaja.lblSalir.Caption',
   'es-ES',
   'Salir',
   'src/Caja/Forms/inMtoCajaMenu.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaMenu.TfrmMtoMenuCaja.lblESC.Caption',
   'es-ES',
   'ESC',
   'src/Caja/Forms/inMtoCajaMenu.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaMenu.TfrmMtoMenuCaja.lblFecha.Caption',
   'es-ES',
   'Fecha de Caja',
   'src/Caja/Forms/inMtoCajaMenu.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaMenu.TfrmMtoMenuCaja.lblF3.Caption',
   'es-ES',
   'F3',
   'src/Caja/Forms/inMtoCajaMenu.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaMenu.TfrmMtoMenuCaja.lblTraspasos.Caption',
   'es-ES',
   'Traspasos',
   'src/Caja/Forms/inMtoCajaMenu.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaMenu.TfrmMtoMenuCaja.lblEmpresa.Caption',
   'es-ES',
   'Empresa',
   'src/Caja/Forms/inMtoCajaMenu.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaMenu.TfrmMtoMenuCaja.actSalirMenu.Caption',
   'es-ES',
   'ESCAPE',
   'src/Caja/Forms/inMtoCajaMenu.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaOpe.TfrmMtoOpeCaja.Caption',
   'es-ES',
   'Operación de Caja',
   'src/Caja/Forms/inMtoCajaOpe.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaOpe.TfrmMtoOpeCaja.lblFecha.Caption',
   'es-ES',
   'Empleado',
   'src/Caja/Forms/inMtoCajaOpe.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaOpe.TfrmMtoOpeCaja.lblNombreEmpleado.Caption',
   'es-ES',
   'NOMBRE EMPLEADO',
   'src/Caja/Forms/inMtoCajaOpe.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaOpe.TfrmMtoOpeCaja.lblNombreCliente.Caption',
   'es-ES',
   'NOMBRE CLIENTE',
   'src/Caja/Forms/inMtoCajaOpe.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaOpe.TfrmMtoOpeCaja.lblFechaCaja.Caption',
   'es-ES',
   'NOMBRE CLIENTE',
   'src/Caja/Forms/inMtoCajaOpe.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaOpe.TfrmMtoOpeCaja.lblTarifa.Caption',
   'es-ES',
   'NOMBRE CLIENTE',
   'src/Caja/Forms/inMtoCajaOpe.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaOpe.TfrmMtoOpeCaja.lblCliente.Caption',
   'es-ES',
   'Cliente',
   'src/Caja/Forms/inMtoCajaOpe.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaOpe.TfrmMtoOpeCaja.lblTipoRectificativa.Caption',
   'es-ES',
   CONCAT(
     'RECTIFICATIVA',
     CHAR(13),
     CHAR(10),
     'POR DIFERENCIAS'
   ),
   'src/Caja/Forms/inMtoCajaOpe.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaOpe.TfrmMtoOpeCaja.lblTotal.Caption',
   'es-ES',
   'Total 0,00 €',
   'src/Caja/Forms/inMtoCajaOpe.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaOpe.TfrmMtoOpeCaja.btnF12.Caption',
   'es-ES',
   'F12',
   'src/Caja/Forms/inMtoCajaOpe.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaOpe.TfrmMtoOpeCaja.btnF3.Caption',
   'es-ES',
   'F3',
   'src/Caja/Forms/inMtoCajaOpe.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaOpe.TfrmMtoOpeCaja.btnF8.Caption',
   'es-ES',
   'F8',
   'src/Caja/Forms/inMtoCajaOpe.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaOpe.TfrmMtoOpeCaja.btnF6.Caption',
   'es-ES',
   'F6',
   'src/Caja/Forms/inMtoCajaOpe.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaOpe.TfrmMtoOpeCaja.btnF61.Caption',
   'es-ES',
   'F4',
   'src/Caja/Forms/inMtoCajaOpe.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaOpe.TfrmMtoOpeCaja.btnF7.Caption',
   'es-ES',
   'F7',
   'src/Caja/Forms/inMtoCajaOpe.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaOpe.TfrmMtoOpeCaja.btnF5.Caption',
   'es-ES',
   'F5',
   'src/Caja/Forms/inMtoCajaOpe.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaOpe.TfrmMtoOpeCaja.btnF2.Caption',
   'es-ES',
   'F2',
   'src/Caja/Forms/inMtoCajaOpe.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaOpe.TfrmMtoOpeCaja.btnF10.Hint',
   'es-ES',
   'Buscar / Modificar operaciones',
   'src/Caja/Forms/inMtoCajaOpe.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaOpe.TfrmMtoOpeCaja.btnF10.Caption',
   'es-ES',
   'F10',
   'src/Caja/Forms/inMtoCajaOpe.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaOpe.TfrmMtoOpeCaja.lblCobro.Caption',
   'es-ES',
   'Cobro',
   'src/Caja/Forms/inMtoCajaOpe.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaOpe.TfrmMtoOpeCaja.lblBuscar.Caption',
   'es-ES',
   'Buscar',
   'src/Caja/Forms/inMtoCajaOpe.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaOpe.TfrmMtoOpeCaja.lblEliminar.Caption',
   'es-ES',
   'Eliminar',
   'src/Caja/Forms/inMtoCajaOpe.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaOpe.TfrmMtoOpeCaja.lblTextoTarifa.Caption',
   'es-ES',
   'Tarifa',
   'src/Caja/Forms/inMtoCajaOpe.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaOpe.TfrmMtoOpeCaja.lblBusqTick.Caption',
   'es-ES',
   'Búsq Tick',
   'src/Caja/Forms/inMtoCajaOpe.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaOpe.TfrmMtoOpeCaja.lblIndIVA.Caption',
   'es-ES',
   'Ind. IVA',
   'src/Caja/Forms/inMtoCajaOpe.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaOpe.TfrmMtoOpeCaja.lblOtro.Caption',
   'es-ES',
   'Otro',
   'src/Caja/Forms/inMtoCajaOpe.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaOpe.TfrmMtoOpeCaja.lblCargarCta.Caption',
   'es-ES',
   'Cargar cta.',
   'src/Caja/Forms/inMtoCajaOpe.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaOpe.TfrmMtoOpeCaja.lblBuscarModificar.Caption',
   'es-ES',
   'Buscar/Mod.',
   'src/Caja/Forms/inMtoCajaOpe.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaOpe.TfrmMtoOpeCaja.tvEmpleado.Caption',
   'es-ES',
   'Vend.',
   'src/Caja/Forms/inMtoCajaOpe.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaOpe.TfrmMtoOpeCaja.tvArticulo.Caption',
   'es-ES',
   'Artículo',
   'src/Caja/Forms/inMtoCajaOpe.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaOpe.TfrmMtoOpeCaja.tvDescripcion.Caption',
   'es-ES',
   'Descripción',
   'src/Caja/Forms/inMtoCajaOpe.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaOpe.TfrmMtoOpeCaja.tvUds.Caption',
   'es-ES',
   'Uds.',
   'src/Caja/Forms/inMtoCajaOpe.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaOpe.TfrmMtoOpeCaja.tvTipoCantidad.Caption',
   'es-ES',
   'Tipo de Cantidad',
   'src/Caja/Forms/inMtoCajaOpe.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaOpe.TfrmMtoOpeCaja.tvPrecioUni.Caption',
   'es-ES',
   'Precio',
   'src/Caja/Forms/inMtoCajaOpe.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaOpe.TfrmMtoOpeCaja.tvDescuento.Caption',
   'es-ES',
   '%',
   'src/Caja/Forms/inMtoCajaOpe.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaOpe.TfrmMtoOpeCaja.tvDescuentoMenos.Caption',
   'es-ES',
   'Menos',
   'src/Caja/Forms/inMtoCajaOpe.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaOpe.TfrmMtoOpeCaja.tvTotal.Caption',
   'es-ES',
   'Total',
   'src/Caja/Forms/inMtoCajaOpe.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaOpe.TfrmMtoOpeCaja.tvFechaOperacion.Caption',
   'es-ES',
   'Fecha op.',
   'src/Caja/Forms/inMtoCajaOpe.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaOpe.TfrmMtoOpeCaja.dbtvBusqCODIGO_ARTICULO.Caption',
   'es-ES',
   'Artículo',
   'src/Caja/Forms/inMtoCajaOpe.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaOpe.TfrmMtoOpeCaja.dbtvBusqDESCRIPCION_ARTICULO.Caption',
   'es-ES',
   'Descripción',
   'src/Caja/Forms/inMtoCajaOpe.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaOpe.TfrmMtoOpeCaja.dbtvBusqTEMPORADA.Caption',
   'es-ES',
   'Temporada',
   'src/Caja/Forms/inMtoCajaOpe.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaOpe.TfrmMtoOpeCaja.dbtvBusqPROVEEDOR.Caption',
   'es-ES',
   'Proveedor',
   'src/Caja/Forms/inMtoCajaOpe.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaOpe.TfrmMtoOpeCaja.dbtvBusqREF_PROVEEDOR.Caption',
   'es-ES',
   'Ref. proveedor',
   'src/Caja/Forms/inMtoCajaOpe.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaOpe.TfrmMtoOpeCaja.actBuscarEmpleados.Caption',
   'es-ES',
   'actBuscarEmpleados',
   'src/Caja/Forms/inMtoCajaOpe.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaOpe.TfrmMtoOpeCaja.actSalir.Caption',
   'es-ES',
   'Salir',
   'src/Caja/Forms/inMtoCajaOpe.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaOpe.TfrmMtoOpeCaja.actEliminarLinea.Caption',
   'es-ES',
   'Eliminar',
   'src/Caja/Forms/inMtoCajaOpe.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaOpe.TfrmMtoOpeCaja.actCobro.Caption',
   'es-ES',
   'actCobro',
   'src/Caja/Forms/inMtoCajaOpe.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaOpe.TfrmMtoOpeCaja.actCargarCta.Caption',
   'es-ES',
   'CargarCta',
   'src/Caja/Forms/inMtoCajaOpe.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaOpe.TfrmMtoOpeCaja.actBuscarModificar.Caption',
   'es-ES',
   'Buscar / Modificar',
   'src/Caja/Forms/inMtoCajaOpe.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaOpe.TfrmMtoOpeCaja.actGuardarLayout.Caption',
   'es-ES',
   'Guardar Layout',
   'src/Caja/Forms/inMtoCajaOpe.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaOpe.TfrmMtoOpeCaja.actAbrirArticulos.Caption',
   'es-ES',
   'Artículos',
   'src/Caja/Forms/inMtoCajaOpe.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaOpe.TfrmMtoOpeCaja.actConsultaStock.Caption',
   'es-ES',
   'Consulta stock',
   'src/Caja/Forms/inMtoCajaOpe.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaOperacionesHist.TfrmMtoCajaOperacionesHist.Caption',
   'es-ES',
   'Histórico de Operaciones de Caja',
   'src/Caja/Forms/inMtoCajaOperacionesHist.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoCajaOperacionesHist.TfrmMtoCajaOperacionesHist.cxGrdDBTabPrinCODI',
     'GO_EMPRESA_OPCAJA.Caption'
   ),
   'es-ES',
   'Empresa',
   'src/Caja/Forms/inMtoCajaOperacionesHist.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoCajaOperacionesHist.TfrmMtoCajaOperacionesHist.cxGrdDBTabPrinCODI',
     'GO_ALMACEN_OPCAJA.Caption'
   ),
   'es-ES',
   'Almacén',
   'src/Caja/Forms/inMtoCajaOperacionesHist.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoCajaOperacionesHist.TfrmMtoCajaOperacionesHist.cxGrdDBTabPrinCODI',
     'GO_CAJA_OPCAJA.Caption'
   ),
   'es-ES',
   'Caja',
   'src/Caja/Forms/inMtoCajaOperacionesHist.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoCajaOperacionesHist.TfrmMtoCajaOperacionesHist.cxGrdDBTabPrinNUME',
     'RO_OPERACION_OPCAJA.Caption'
   ),
   'es-ES',
   'Número Operación',
   'src/Caja/Forms/inMtoCajaOperacionesHist.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoCajaOperacionesHist.TfrmMtoCajaOperacionesHist.cxGrdDBTabPrinFECH',
     'A_OPERACION_OPCAJA.Caption'
   ),
   'es-ES',
   'Fecha/Hora',
   'src/Caja/Forms/inMtoCajaOperacionesHist.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoCajaOperacionesHist.TfrmMtoCajaOperacionesHist.cxGrdDBTabPrinTIPO',
     '_OPERACION_OPCAJA.Caption'
   ),
   'es-ES',
   'Tipos',
   'src/Caja/Forms/inMtoCajaOperacionesHist.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoCajaOperacionesHist.TfrmMtoCajaOperacionesHist.cxGrdDBTabPrinCODI',
     'GO_EMPLEADO_OPCAJA.Caption'
   ),
   'es-ES',
   'Empleado',
   'src/Caja/Forms/inMtoCajaOperacionesHist.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoCajaOperacionesHist.TfrmMtoCajaOperacionesHist.cxGrdDBTabPrinIMPO',
     'RTE_TOTAL_OPCAJA.Caption'
   ),
   'es-ES',
   'Importe',
   'src/Caja/Forms/inMtoCajaOperacionesHist.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoCajaOperacionesHist.TfrmMtoCajaOperacionesHist.cxGrdDBTabPrinCODI',
     'GO_CLIENTE_OPCAJA.Caption'
   ),
   'es-ES',
   'Cliente',
   'src/Caja/Forms/inMtoCajaOperacionesHist.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoCajaOperacionesHist.TfrmMtoCajaOperacionesHist.cxGrdDBTabPrinRAZO',
     'N_SOCIAL_CLI.Caption'
   ),
   'es-ES',
   'Razón social',
   'src/Caja/Forms/inMtoCajaOperacionesHist.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoCajaOperacionesHist.TfrmMtoCajaOperacionesHist.cxGrdDBTabPrinSERI',
     'E_FACTURA_OPCAJA.Caption'
   ),
   'es-ES',
   'Serie',
   'src/Caja/Forms/inMtoCajaOperacionesHist.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoCajaOperacionesHist.TfrmMtoCajaOperacionesHist.cxGrdDBTabPrinNRO_',
     'FACTURA_OPCAJA.Caption'
   ),
   'es-ES',
   'Nº Borrador',
   'src/Caja/Forms/inMtoCajaOperacionesHist.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoCajaOperacionesHist.TfrmMtoCajaOperacionesHist.cxGrdDBTabPrinCONC',
     'EPTO_GASTO_INGRESO_OPCAJA.Caption'
   ),
   'es-ES',
   'Conceptos',
   'src/Caja/Forms/inMtoCajaOperacionesHist.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoCajaOperacionesHist.TfrmMtoCajaOperacionesHist.btnToggleFiltrosCa',
     'ja.Caption'
   ),
   'es-ES',
   '▶  Filtros de carga',
   'src/Caja/Forms/inMtoCajaOperacionesHist.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaOperacionesHist.TfrmMtoCajaOperacionesHist.lblFiltroAnyo.Caption',
   'es-ES',
   'Años:',
   'src/Caja/Forms/inMtoCajaOperacionesHist.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoCajaOperacionesHist.TfrmMtoCajaOperacionesHist.lblFiltroAlmacen.C',
     'aption'
   ),
   'es-ES',
   'Almacenes:',
   'src/Caja/Forms/inMtoCajaOperacionesHist.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoCajaOperacionesHist.TfrmMtoCajaOperacionesHist.btnGuardarPrecarga',
     'Caja.Caption'
   ),
   'es-ES',
   'Guardar precarga',
   'src/Caja/Forms/inMtoCajaOperacionesHist.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoCajaOperacionesHist.TfrmMtoCajaOperacionesHist.btnImprimirInforme',
     '.Caption'
   ),
   'es-ES',
   'Imprimir Informe A4',
   'src/Caja/Forms/inMtoCajaOperacionesHist.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoCajaOperacionesHist.TfrmMtoCajaOperacionesHist.actIrFacturaSimpli',
     'f.Caption'
   ),
   'es-ES',
   'Ir a Borrador Simplificado',
   'src/Caja/Forms/inMtoCajaOperacionesHist.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaPagosHist.TfrmMtoCajaPagosHist.Caption',
   'es-ES',
   'Histórico de Pagos de Caja',
   'src/Caja/Forms/inMtoCajaPagosHist.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoCajaPagosHist.TfrmMtoCajaPagosHist.cxGrdDBTabPrinCODIGO_EMPRESA_P',
     'AGO.Caption'
   ),
   'es-ES',
   'Empresa',
   'src/Caja/Forms/inMtoCajaPagosHist.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoCajaPagosHist.TfrmMtoCajaPagosHist.cxGrdDBTabPrinCODIGO_ALMACEN_P',
     'AGO.Caption'
   ),
   'es-ES',
   'Almacén',
   'src/Caja/Forms/inMtoCajaPagosHist.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoCajaPagosHist.TfrmMtoCajaPagosHist.cxGrdDBTabPrinCODIGO_CAJA_PAGO',
     '.Caption'
   ),
   'es-ES',
   'Caja',
   'src/Caja/Forms/inMtoCajaPagosHist.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoCajaPagosHist.TfrmMtoCajaPagosHist.cxGrdDBTabPrinSERIE_OPERACION_',
     'PAGO.Caption'
   ),
   'es-ES',
   'Serie Op.',
   'src/Caja/Forms/inMtoCajaPagosHist.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoCajaPagosHist.TfrmMtoCajaPagosHist.cxGrdDBTabPrinNUMERO_OPERACION',
     '_PAGO.Caption'
   ),
   'es-ES',
   'Número Op.',
   'src/Caja/Forms/inMtoCajaPagosHist.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoCajaPagosHist.TfrmMtoCajaPagosHist.cxGrdDBTabPrinNUMERO_LINEA_PAG',
     'O.Caption'
   ),
   'es-ES',
   'Línea',
   'src/Caja/Forms/inMtoCajaPagosHist.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaPagosHist.TfrmMtoCajaPagosHist.cxGrdDBTabPrinFECHA_PAGO.Caption',
   'es-ES',
   'Fecha Pago',
   'src/Caja/Forms/inMtoCajaPagosHist.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoCajaPagosHist.TfrmMtoCajaPagosHist.cxGrdDBTabPrinCODIGO_FORMAP.Ca',
     'ption'
   ),
   'es-ES',
   'Forma de Pago',
   'src/Caja/Forms/inMtoCajaPagosHist.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoCajaPagosHist.TfrmMtoCajaPagosHist.cxGrdDBTabPrinCODIGO_DIVISA_PA',
     'GO.Caption'
   ),
   'es-ES',
   'Divisa',
   'src/Caja/Forms/inMtoCajaPagosHist.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoCajaPagosHist.TfrmMtoCajaPagosHist.cxGrdDBTabPrinRED_BLOCKCHAIN.C',
     'aption'
   ),
   'es-ES',
   'Red Blockchain',
   'src/Caja/Forms/inMtoCajaPagosHist.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoCajaPagosHist.TfrmMtoCajaPagosHist.cxGrdDBTabPrinFACTOR_CAMBIO_PA',
     'GO.Caption'
   ),
   'es-ES',
   'Factor Cambio',
   'src/Caja/Forms/inMtoCajaPagosHist.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoCajaPagosHist.TfrmMtoCajaPagosHist.cxGrdDBTabPrinIMPORTE_DIVISA_P',
     'AGO.Caption'
   ),
   'es-ES',
   'Importe Divisa',
   'src/Caja/Forms/inMtoCajaPagosHist.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoCajaPagosHist.TfrmMtoCajaPagosHist.cxGrdDBTabPrinIMPORTE_ENTREGAD',
     'O_PAGO.Caption'
   ),
   'es-ES',
   'Importe Entregado',
   'src/Caja/Forms/inMtoCajaPagosHist.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoCajaPagosHist.TfrmMtoCajaPagosHist.cxGrdDBTabPrinIMPORTE_CAMBIO_P',
     'AGO.Caption'
   ),
   'es-ES',
   'Importe Cambio',
   'src/Caja/Forms/inMtoCajaPagosHist.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoCajaPagosHist.TfrmMtoCajaPagosHist.cxGrdDBTabPrinREFERENCIA_PAGO.',
     'Caption'
   ),
   'es-ES',
   'Referencia',
   'src/Caja/Forms/inMtoCajaPagosHist.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoCajaPagosHist.TfrmMtoCajaPagosHist.cxGrdDBTabPrinOBSERVACIONES_PA',
     'GO.Caption'
   ),
   'es-ES',
   'Observaciones',
   'src/Caja/Forms/inMtoCajaPagosHist.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaPagosHist.TfrmMtoCajaPagosHist.cxGrdDBTabPrinINSTANTEALTA.Caption',
   'es-ES',
   'Instante Alta',
   'src/Caja/Forms/inMtoCajaPagosHist.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoCajaPagosHist.TfrmMtoCajaPagosHist.cxGrdDBTabPrinINSTANTEMODIF.Ca',
     'ption'
   ),
   'es-ES',
   'Instante Modif',
   'src/Caja/Forms/inMtoCajaPagosHist.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaPagosHist.TfrmMtoCajaPagosHist.cxGrdDBTabPrinUSUARIOALTA.Caption',
   'es-ES',
   'Usuario Alta',
   'src/Caja/Forms/inMtoCajaPagosHist.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaPagosHist.TfrmMtoCajaPagosHist.btnToggleFiltrosCaja.Caption',
   'es-ES',
   '▶  Filtros de carga',
   'src/Caja/Forms/inMtoCajaPagosHist.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaPagosHist.TfrmMtoCajaPagosHist.lblFiltroAnyo.Caption',
   'es-ES',
   'Años:',
   'src/Caja/Forms/inMtoCajaPagosHist.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaPagosHist.TfrmMtoCajaPagosHist.btnCargarPagos.Caption',
   'es-ES',
   'Cargar',
   'src/Caja/Forms/inMtoCajaPagosHist.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaPagosHist.TfrmMtoCajaPagosHist.btnGuardarPrecargaCaja.Caption',
   'es-ES',
   'Guardar precarga',
   'src/Caja/Forms/inMtoCajaPagosHist.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaPagosHist.TfrmMtoCajaPagosHist.btnImprimirInforme.Caption',
   'es-ES',
   'Imprimir Informe A4',
   'src/Caja/Forms/inMtoCajaPagosHist.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaParam.TfrmMtoCajaParam.Caption',
   'es-ES',
   'Parámetros de Caja',
   'src/Caja/Forms/inMtoCajaParam.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaParam.TfrmMtoCajaParam.btnGuardar.Caption',
   'es-ES',
   '&Guardar (F12)',
   'src/Caja/Forms/inMtoCajaParam.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaParam.TfrmMtoCajaParam.actGuardar.Caption',
   'es-ES',
   'actGuardar',
   'src/Caja/Forms/inMtoCajaParam.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaParam.TfrmMtoCajaParam.actSalir.Caption',
   'es-ES',
   'actSalir',
   'src/Caja/Forms/inMtoCajaParam.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaParam.TfrmMtoCajaParam.actGuardarLayout.Caption',
   'es-ES',
   'Guardar Layout',
   'src/Caja/Forms/inMtoCajaParam.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaReferenciaPago.TfrmCajaReferenciaPago.Caption',
   'es-ES',
   'Datos de Pago',
   'src/Caja/Forms/inMtoCajaReferenciaPago.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaReferenciaPago.TfrmCajaReferenciaPago.gbInfoPago.Caption',
   'es-ES',
   ' Información del Pago ',
   'src/Caja/Forms/inMtoCajaReferenciaPago.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaReferenciaPago.TfrmCajaReferenciaPago.lblFormaPago.Caption',
   'es-ES',
   'Forma de Pago:',
   'src/Caja/Forms/inMtoCajaReferenciaPago.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaReferenciaPago.TfrmCajaReferenciaPago.lblFormaPagoValor.Caption',
   'es-ES',
   'Tarjeta Bancaria',
   'src/Caja/Forms/inMtoCajaReferenciaPago.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaReferenciaPago.TfrmCajaReferenciaPago.lblImporte.Caption',
   'es-ES',
   'Importe:',
   'src/Caja/Forms/inMtoCajaReferenciaPago.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaReferenciaPago.TfrmCajaReferenciaPago.cxLabel1.Caption',
   'es-ES',
   'Pendiente',
   'src/Caja/Forms/inMtoCajaReferenciaPago.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaReferenciaPago.TfrmCajaReferenciaPago.gbReferencia.Caption',
   'es-ES',
   ' Referencia ',
   'src/Caja/Forms/inMtoCajaReferenciaPago.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaReferenciaPago.TfrmCajaReferenciaPago.lblReferencia.Caption',
   'es-ES',
   'Referencia:',
   'src/Caja/Forms/inMtoCajaReferenciaPago.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaReferenciaPago.TfrmCajaReferenciaPago.lblEjemplo.Caption',
   'es-ES',
   'Ej: 123456',
   'src/Caja/Forms/inMtoCajaReferenciaPago.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaReferenciaPago.TfrmCajaReferenciaPago.gbDivisa.Caption',
   'es-ES',
   ' Otra Divisa ',
   'src/Caja/Forms/inMtoCajaReferenciaPago.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaReferenciaPago.TfrmCajaReferenciaPago.lblDivisa.Caption',
   'es-ES',
   'Divisa:',
   'src/Caja/Forms/inMtoCajaReferenciaPago.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaReferenciaPago.TfrmCajaReferenciaPago.lblFactorCambio.Caption',
   'es-ES',
   'Cotización:',
   'src/Caja/Forms/inMtoCajaReferenciaPago.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaReferenciaPago.TfrmCajaReferenciaPago.lblImporteDivisa.Caption',
   'es-ES',
   'Importe final:',
   'src/Caja/Forms/inMtoCajaReferenciaPago.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaReferenciaPago.TfrmCajaReferenciaPago.lblEquivale.Caption',
   'es-ES',
   '0,00 EUR = 0.00 USD',
   'src/Caja/Forms/inMtoCajaReferenciaPago.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaReferenciaPago.TfrmCajaReferenciaPago.lblEquivale2.Caption',
   'es-ES',
   '0,00 EUR = 0.00 USD',
   'src/Caja/Forms/inMtoCajaReferenciaPago.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaReferenciaPago.TfrmCajaReferenciaPago.gbBlockchain.Caption',
   'es-ES',
   ' Blockchain ',
   'src/Caja/Forms/inMtoCajaReferenciaPago.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaReferenciaPago.TfrmCajaReferenciaPago.lblRedBlockchain.Caption',
   'es-ES',
   'Red:',
   'src/Caja/Forms/inMtoCajaReferenciaPago.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaReferenciaPago.TfrmCajaReferenciaPago.lblTxHash.Caption',
   'es-ES',
   'TX Hash:',
   'src/Caja/Forms/inMtoCajaReferenciaPago.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaReferenciaPago.TfrmCajaReferenciaPago.btnAceptar.Caption',
   'es-ES',
   'Aceptar (F12)',
   'src/Caja/Forms/inMtoCajaReferenciaPago.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaReferenciaPago.TfrmCajaReferenciaPago.btnCancelar.Caption',
   'es-ES',
   'Cancelar (ESC)',
   'src/Caja/Forms/inMtoCajaReferenciaPago.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaReferenciaPago.TfrmCajaReferenciaPago.cxLabel2.Caption',
   'es-ES',
   'Sobra:',
   'src/Caja/Forms/inMtoCajaReferenciaPago.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaSeleccionVale.TfrmMtoCajaSeleccionVale.Caption',
   'es-ES',
   'Seleccionar Vale',
   'src/Caja/Forms/inMtoCajaSeleccionVale.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaSeleccionVale.TfrmMtoCajaSeleccionVale.lblBuscar.Caption',
   'es-ES',
   'Buscar vale:',
   'src/Caja/Forms/inMtoCajaSeleccionVale.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaSeleccionVale.TfrmMtoCajaSeleccionVale.btnBuscar.Caption',
   'es-ES',
   'Buscar [Enter]',
   'src/Caja/Forms/inMtoCajaSeleccionVale.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaSeleccionVale.TfrmMtoCajaSeleccionVale.cxLabel1.Caption',
   'es-ES',
   'El Vale no se canjea hasta que confirme la operación.',
   'src/Caja/Forms/inMtoCajaSeleccionVale.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaSeleccionVale.TfrmMtoCajaSeleccionVale.colCodigo.Caption',
   'es-ES',
   'Código Vale',
   'src/Caja/Forms/inMtoCajaSeleccionVale.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaSeleccionVale.TfrmMtoCajaSeleccionVale.colEstado.Caption',
   'es-ES',
   'Estado',
   'src/Caja/Forms/inMtoCajaSeleccionVale.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaSeleccionVale.TfrmMtoCajaSeleccionVale.colImporte.Caption',
   'es-ES',
   'Importe',
   'src/Caja/Forms/inMtoCajaSeleccionVale.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaSeleccionVale.TfrmMtoCajaSeleccionVale.colFechaEmision.Caption',
   'es-ES',
   'Fecha emisión',
   'src/Caja/Forms/inMtoCajaSeleccionVale.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaSeleccionVale.TfrmMtoCajaSeleccionVale.colCaducidad.Caption',
   'es-ES',
   'Caducidad',
   'src/Caja/Forms/inMtoCajaSeleccionVale.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaSeleccionVale.TfrmMtoCajaSeleccionVale.colObservaciones.Caption',
   'es-ES',
   'Observaciones',
   'src/Caja/Forms/inMtoCajaSeleccionVale.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaSeleccionVale.TfrmMtoCajaSeleccionVale.btnAceptar.Caption',
   'es-ES',
   'Aceptar (F12)',
   'src/Caja/Forms/inMtoCajaSeleccionVale.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaSeleccionVale.TfrmMtoCajaSeleccionVale.btnCancelar.Caption',
   'es-ES',
   'Cancelar (ESC)',
   'src/Caja/Forms/inMtoCajaSeleccionVale.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaSeleccionVale.TfrmMtoCajaSeleccionVale.lblPin.Caption',
   'es-ES',
   'PIN:',
   'src/Caja/Forms/inMtoCajaSeleccionVale.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaValesHist.TfrmMtoCajaValesHist.Caption',
   'es-ES',
   'Histórico de Vales',
   'src/Caja/Forms/inMtoCajaValesHist.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaValesHist.TfrmMtoCajaValesHist.cxGrdDBTabPrinCODIGO_VL.Caption',
   'es-ES',
   'Código Vale',
   'src/Caja/Forms/inMtoCajaValesHist.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaValesHist.TfrmMtoCajaValesHist.cxGrdDBTabPrinESTADO_VL.Caption',
   'es-ES',
   'Estado',
   'src/Caja/Forms/inMtoCajaValesHist.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoCajaValesHist.TfrmMtoCajaValesHist.cxGrdDBTabPrinIMPORTE_NOMINAL_',
     'VL.Caption'
   ),
   'es-ES',
   'Importe Nominal',
   'src/Caja/Forms/inMtoCajaValesHist.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoCajaValesHist.TfrmMtoCajaValesHist.cxGrdDBTabPrinFECHA_EMISION_VL',
     '.Caption'
   ),
   'es-ES',
   'F. Emisión',
   'src/Caja/Forms/inMtoCajaValesHist.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoCajaValesHist.TfrmMtoCajaValesHist.cxGrdDBTabPrinFECHA_CADUCIDAD_',
     'VL.Caption'
   ),
   'es-ES',
   'F. Caducidad',
   'src/Caja/Forms/inMtoCajaValesHist.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoCajaValesHist.TfrmMtoCajaValesHist.cxGrdDBTabPrinCODIGO_PADRE_VL.',
     'Caption'
   ),
   'es-ES',
   'Vale Padre',
   'src/Caja/Forms/inMtoCajaValesHist.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoCajaValesHist.TfrmMtoCajaValesHist.cxGrdDBTabPrinPIN_SEGURIDAD_VL',
     '.Caption'
   ),
   'es-ES',
   'PIN',
   'src/Caja/Forms/inMtoCajaValesHist.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoCajaValesHist.TfrmMtoCajaValesHist.cxGrdDBTabPrinCODIGO_EMPRESA_E',
     'MI_VL.Caption'
   ),
   'es-ES',
   'Empresa Emi.',
   'src/Caja/Forms/inMtoCajaValesHist.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoCajaValesHist.TfrmMtoCajaValesHist.cxGrdDBTabPrinCODIGO_ALMACEN_E',
     'MI_VL.Caption'
   ),
   'es-ES',
   'Almacén Emi.',
   'src/Caja/Forms/inMtoCajaValesHist.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoCajaValesHist.TfrmMtoCajaValesHist.cxGrdDBTabPrinCODIGO_CAJA_EMI_',
     'VL.Caption'
   ),
   'es-ES',
   'Caja Emi.',
   'src/Caja/Forms/inMtoCajaValesHist.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoCajaValesHist.TfrmMtoCajaValesHist.cxGrdDBTabPrinNUMERO_OPERACION',
     '_EMI_VL.Caption'
   ),
   'es-ES',
   'Núm. Op. Emi.',
   'src/Caja/Forms/inMtoCajaValesHist.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoCajaValesHist.TfrmMtoCajaValesHist.cxGrdDBTabPrinSERIE_FACTURA_EM',
     'I_VL.Caption'
   ),
   'es-ES',
   'Serie Fac. Emi.',
   'src/Caja/Forms/inMtoCajaValesHist.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoCajaValesHist.TfrmMtoCajaValesHist.cxGrdDBTabPrinNRO_FACTURA_EMI_',
     'VL.Caption'
   ),
   'es-ES',
   'Nro. Fac. Emi.',
   'src/Caja/Forms/inMtoCajaValesHist.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoCajaValesHist.TfrmMtoCajaValesHist.cxGrdDBTabPrinFECHA_REDENCION_',
     'VL.Caption'
   ),
   'es-ES',
   'F. Redención',
   'src/Caja/Forms/inMtoCajaValesHist.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoCajaValesHist.TfrmMtoCajaValesHist.cxGrdDBTabPrinIMPORTE_REDIMIDO',
     '_VL.Caption'
   ),
   'es-ES',
   'Importe Redimido',
   'src/Caja/Forms/inMtoCajaValesHist.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoCajaValesHist.TfrmMtoCajaValesHist.cxGrdDBTabPrinCODIGO_EMPRESA_R',
     'ED_VL.Caption'
   ),
   'es-ES',
   'Empresa Red.',
   'src/Caja/Forms/inMtoCajaValesHist.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoCajaValesHist.TfrmMtoCajaValesHist.cxGrdDBTabPrinCODIGO_ALMACEN_R',
     'ED_VL.Caption'
   ),
   'es-ES',
   'Almacén Red.',
   'src/Caja/Forms/inMtoCajaValesHist.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoCajaValesHist.TfrmMtoCajaValesHist.cxGrdDBTabPrinCODIGO_CAJA_RED_',
     'VL.Caption'
   ),
   'es-ES',
   'Caja Red.',
   'src/Caja/Forms/inMtoCajaValesHist.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoCajaValesHist.TfrmMtoCajaValesHist.cxGrdDBTabPrinNUMERO_OPERACION',
     '_RED_VL.Caption'
   ),
   'es-ES',
   'Núm. Op. Red.',
   'src/Caja/Forms/inMtoCajaValesHist.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoCajaValesHist.TfrmMtoCajaValesHist.cxGrdDBTabPrinSERIE_FACTURA_RE',
     'D_VL.Caption'
   ),
   'es-ES',
   'Serie Fac. Red.',
   'src/Caja/Forms/inMtoCajaValesHist.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoCajaValesHist.TfrmMtoCajaValesHist.cxGrdDBTabPrinNRO_FACTURA_RED_',
     'VL.Caption'
   ),
   'es-ES',
   'Nro. Fac. Red.',
   'src/Caja/Forms/inMtoCajaValesHist.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoCajaValesHist.TfrmMtoCajaValesHist.cxGrdDBTabPrinCODIGO_CLIENTE_V',
     'L.Caption'
   ),
   'es-ES',
   'Cliente',
   'src/Caja/Forms/inMtoCajaValesHist.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoCajaValesHist.TfrmMtoCajaValesHist.cxGrdDBTabPrinOBSERVACIONES_VL',
     '.Caption'
   ),
   'es-ES',
   'Observaciones',
   'src/Caja/Forms/inMtoCajaValesHist.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaValesHist.TfrmMtoCajaValesHist.cxGrdDBTabPrinINSTANTEALTA.Caption',
   'es-ES',
   'Instante Alta',
   'src/Caja/Forms/inMtoCajaValesHist.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoCajaValesHist.TfrmMtoCajaValesHist.cxGrdDBTabPrinINSTANTEMODIF.Ca',
     'ption'
   ),
   'es-ES',
   'Instante Modif',
   'src/Caja/Forms/inMtoCajaValesHist.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaValesHist.TfrmMtoCajaValesHist.cxGrdDBTabPrinUSUARIOALTA.Caption',
   'es-ES',
   'Usuario Alta',
   'src/Caja/Forms/inMtoCajaValesHist.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoCajaValesHist.TfrmMtoCajaValesHist.cxGrdDBTabPrinUSUARIOMODIF.Caption',
   'es-ES',
   'Usuario Modif',
   'src/Caja/Forms/inMtoCajaValesHist.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema')
ON DUPLICATE KEY UPDATE
  `TEXTO_TRAD` = VALUES(`TEXTO_TRAD`),
  `CONTEXTO_TRAD` = VALUES(`CONTEXTO_TRAD`),
  `ESACTIVO_TRAD` = VALUES(`ESACTIVO_TRAD`),
  `INSTANTE_MODIF` = CURRENT_TIMESTAMP,
  `USUARIO_MODIF` = VALUES(`USUARIO_ALTA`);
