-- Catálogo de textos españoles extraídos de los DFM.
-- Generado por generar_traducciones_dfm.ps1.
INSERT INTO `fza_traducciones` (
  `CLAVE_TRAD`, `IDIOMA_TRAD`, `TEXTO_TRAD`, `CONTEXTO_TRAD`,
  `ESACTIVO_TRAD`, `INSTANTE_ALTA`, `USUARIO_ALTA`
) VALUES
  ('inMtoModalArqueo.TfrmModalArqueo.Caption',
   'es-ES',
   'Arqueo de caja',
   'src/Caja/Modals/inMtoModalArqueo.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalArqueo.TfrmModalArqueo.lblTituloDesde.Caption',
   'es-ES',
   'Fecha desde (F10)',
   'src/Caja/Modals/inMtoModalArqueo.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalArqueo.TfrmModalArqueo.lblTituloHasta.Caption',
   'es-ES',
   'Fecha hasta (F6)',
   'src/Caja/Modals/inMtoModalArqueo.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalArqueo.TfrmModalArqueo.lblTituloVentas.Caption',
   'es-ES',
   'Ventas',
   'src/Caja/Modals/inMtoModalArqueo.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalArqueo.TfrmModalArqueo.lblVentas.Caption',
   'es-ES',
   '0',
   'src/Caja/Modals/inMtoModalArqueo.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalArqueo.TfrmModalArqueo.btnRecalcular.Caption',
   'es-ES',
   'Calc (F5)',
   'src/Caja/Modals/inMtoModalArqueo.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalArqueo.TfrmModalArqueo.btnImprimir.Caption',
   'es-ES',
   'Resumen (F11)',
   'src/Caja/Modals/inMtoModalArqueo.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalArqueo.TfrmModalArqueo.btnHistorico.Caption',
   'es-ES',
   'Histórico (F8)',
   'src/Caja/Modals/inMtoModalArqueo.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalArqueo.TfrmModalArqueo.btnTiraCaja.Caption',
   'es-ES',
   'Tira de Caja (F7)',
   'src/Caja/Modals/inMtoModalArqueo.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalArqueo.TfrmModalArqueo.tsArqueo.Caption',
   'es-ES',
   'Arqueo',
   'src/Caja/Modals/inMtoModalArqueo.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalArqueo.TfrmModalArqueo.lblLineasTitulo.Caption',
   'es-ES',
   'Líneas artículos',
   'src/Caja/Modals/inMtoModalArqueo.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalArqueo.TfrmModalArqueo.lblLinBrutoLbl.Caption',
   'es-ES',
   '+ Bruto',
   'src/Caja/Modals/inMtoModalArqueo.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalArqueo.TfrmModalArqueo.lblLinDescuentoLbl.Caption',
   'es-ES',
   '- Descuento',
   'src/Caja/Modals/inMtoModalArqueo.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalArqueo.TfrmModalArqueo.lblLinNetoLbl.Caption',
   'es-ES',
   '= Bruto',
   'src/Caja/Modals/inMtoModalArqueo.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalArqueo.TfrmModalArqueo.lblOpeTitulo.Caption',
   'es-ES',
   'Operaciones',
   'src/Caja/Modals/inMtoModalArqueo.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalArqueo.TfrmModalArqueo.lblOpeVentasNormLbl.Caption',
   'es-ES',
   'Ventas Normales',
   'src/Caja/Modals/inMtoModalArqueo.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalArqueo.TfrmModalArqueo.lblOpeVentasPrestLbl.Caption',
   'es-ES',
   '+ Ventas Préstamos',
   'src/Caja/Modals/inMtoModalArqueo.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalArqueo.TfrmModalArqueo.lblOpeDevolLbl.Caption',
   'es-ES',
   '- Devoluciones',
   'src/Caja/Modals/inMtoModalArqueo.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalArqueo.TfrmModalArqueo.lblOpeTotalVentasLbl.Caption',
   'es-ES',
   '= Total Ventas',
   'src/Caja/Modals/inMtoModalArqueo.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalArqueo.TfrmModalArqueo.lblCobrosTitulo.Caption',
   'es-ES',
   'Cobros',
   'src/Caja/Modals/inMtoModalArqueo.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalArqueo.TfrmModalArqueo.lblCobValesRecLbl.Caption',
   'es-ES',
   '- Vales recogidos',
   'src/Caja/Modals/inMtoModalArqueo.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalArqueo.TfrmModalArqueo.lblCobValesEmiLbl.Caption',
   'es-ES',
   '+ Vales emitidos',
   'src/Caja/Modals/inMtoModalArqueo.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalArqueo.TfrmModalArqueo.lblCobClientesLbl.Caption',
   'es-ES',
   '+ Cobros clientes',
   'src/Caja/Modals/inMtoModalArqueo.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalArqueo.TfrmModalArqueo.lblCobPendienteLbl.Caption',
   'es-ES',
   '- Pendiente cobro',
   'src/Caja/Modals/inMtoModalArqueo.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalArqueo.TfrmModalArqueo.lblCobIngresosLbl.Caption',
   'es-ES',
   '= Ingresos caja',
   'src/Caja/Modals/inMtoModalArqueo.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalArqueo.TfrmModalArqueo.lblEftIngresosLbl.Caption',
   'es-ES',
   'Eftvo. ingresos',
   'src/Caja/Modals/inMtoModalArqueo.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalArqueo.TfrmModalArqueo.lblEftEntradasLbl.Caption',
   'es-ES',
   '+ Efectivo entradas',
   'src/Caja/Modals/inMtoModalArqueo.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalArqueo.TfrmModalArqueo.lblEftSalidasLbl.Caption',
   'es-ES',
   '- Efectivo salidas',
   'src/Caja/Modals/inMtoModalArqueo.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalArqueo.TfrmModalArqueo.lblEftAnteriorLbl.Caption',
   'es-ES',
   '+ Efectivo anterior',
   'src/Caja/Modals/inMtoModalArqueo.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalArqueo.TfrmModalArqueo.lblEftCajaLbl.Caption',
   'es-ES',
   '= Efectivo en caja',
   'src/Caja/Modals/inMtoModalArqueo.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalArqueo.TfrmModalArqueo.lblTarjetasLbl.Caption',
   'es-ES',
   '+ Otros (tarj, bonos, divisa, cripto)',
   'src/Caja/Modals/inMtoModalArqueo.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalArqueo.TfrmModalArqueo.lblSaldoLbl.Caption',
   'es-ES',
   '= Saldo efectivo + otros (a recontar)',
   'src/Caja/Modals/inMtoModalArqueo.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalArqueo.TfrmModalArqueo.tsResumenes.Caption',
   'es-ES',
   'Resúmenes',
   'src/Caja/Modals/inMtoModalArqueo.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalArqueo.TfrmModalArqueo.lblResEmpleadoTit.Caption',
   'es-ES',
   'Neto ventas por empleado',
   'src/Caja/Modals/inMtoModalArqueo.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalArqueo.TfrmModalArqueo.tvResEmpleadoEMP.Caption',
   'es-ES',
   'Empleado',
   'src/Caja/Modals/inMtoModalArqueo.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalArqueo.TfrmModalArqueo.tvResEmpleadoUDS.Caption',
   'es-ES',
   'Uds',
   'src/Caja/Modals/inMtoModalArqueo.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalArqueo.TfrmModalArqueo.tvResEmpleadoNETO.Caption',
   'es-ES',
   'Neto',
   'src/Caja/Modals/inMtoModalArqueo.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalArqueo.TfrmModalArqueo.lblResFPTit.Caption',
   'es-ES',
   'Neto ventas por forma de pago',
   'src/Caja/Modals/inMtoModalArqueo.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalArqueo.TfrmModalArqueo.tvResFPFP.Caption',
   'es-ES',
   'Forma de pago',
   'src/Caja/Modals/inMtoModalArqueo.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalArqueo.TfrmModalArqueo.tvResFPUDS.Caption',
   'es-ES',
   'Uds',
   'src/Caja/Modals/inMtoModalArqueo.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalArqueo.TfrmModalArqueo.tvResFPNETO.Caption',
   'es-ES',
   'Importe',
   'src/Caja/Modals/inMtoModalArqueo.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalArqueo.TfrmModalArqueo.lblResFamTit.Caption',
   'es-ES',
   'Neto ventas por familia',
   'src/Caja/Modals/inMtoModalArqueo.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalArqueo.TfrmModalArqueo.tvResFamFAM.Caption',
   'es-ES',
   'Familia',
   'src/Caja/Modals/inMtoModalArqueo.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalArqueo.TfrmModalArqueo.tvResFamUDS.Caption',
   'es-ES',
   'Uds',
   'src/Caja/Modals/inMtoModalArqueo.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalArqueo.TfrmModalArqueo.tvResFamNETO.Caption',
   'es-ES',
   'Neto',
   'src/Caja/Modals/inMtoModalArqueo.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalArqueo.TfrmModalArqueo.lblResPropTit.Caption',
   'es-ES',
   'Neto ventas por propiedad',
   'src/Caja/Modals/inMtoModalArqueo.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalArqueo.TfrmModalArqueo.tvResPropPROP.Caption',
   'es-ES',
   'Propiedad',
   'src/Caja/Modals/inMtoModalArqueo.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalArqueo.TfrmModalArqueo.tvResPropVAL.Caption',
   'es-ES',
   'Valor',
   'src/Caja/Modals/inMtoModalArqueo.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalArqueo.TfrmModalArqueo.tvResPropUDS.Caption',
   'es-ES',
   'Uds',
   'src/Caja/Modals/inMtoModalArqueo.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalArqueo.TfrmModalArqueo.tvResPropNETO.Caption',
   'es-ES',
   'Neto',
   'src/Caja/Modals/inMtoModalArqueo.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalArqueo.TfrmModalArqueo.tsMasDatos.Caption',
   'es-ES',
   'Más datos',
   'src/Caja/Modals/inMtoModalArqueo.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalArqueo.TfrmModalArqueo.lblResIVATit.Caption',
   'es-ES',
   'Resumen por IVA',
   'src/Caja/Modals/inMtoModalArqueo.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalArqueo.TfrmModalArqueo.tvResIVABASE.Caption',
   'es-ES',
   'Bases',
   'src/Caja/Modals/inMtoModalArqueo.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalArqueo.TfrmModalArqueo.tvResIVAPORC_IVA.Caption',
   'es-ES',
   '% IVA',
   'src/Caja/Modals/inMtoModalArqueo.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalArqueo.TfrmModalArqueo.tvResIVACUOTA_IVA.Caption',
   'es-ES',
   'Cuota IVA',
   'src/Caja/Modals/inMtoModalArqueo.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalArqueo.TfrmModalArqueo.tvResIVAPORC_RE.Caption',
   'es-ES',
   '% RE',
   'src/Caja/Modals/inMtoModalArqueo.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalArqueo.TfrmModalArqueo.tvResIVACUOTA_RE.Caption',
   'es-ES',
   'Cuota RE',
   'src/Caja/Modals/inMtoModalArqueo.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalArqueo.TfrmModalArqueo.tvResIVABASE_IVAS.Caption',
   'es-ES',
   'Base + IVAS',
   'src/Caja/Modals/inMtoModalArqueo.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalArqueo.TfrmModalArqueo.tsRecuento.Caption',
   'es-ES',
   'Recuento',
   'src/Caja/Modals/inMtoModalArqueo.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalArqueo.TfrmModalArqueo.lblAnteriorTit.Caption',
   'es-ES',
   'Resto día anterior:',
   'src/Caja/Modals/inMtoModalArqueo.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalArqueo.TfrmModalArqueo.lblAnteriorImporte.Caption',
   'es-ES',
   '0,00 EUR',
   'src/Caja/Modals/inMtoModalArqueo.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalArqueo.TfrmModalArqueo.lblOtrasFPTit.Caption',
   'es-ES',
   'Recuento por forma de pago',
   'src/Caja/Modals/inMtoModalArqueo.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalArqueo.TfrmModalArqueo.tvRecuentoFP.Caption',
   'es-ES',
   'Código',
   'src/Caja/Modals/inMtoModalArqueo.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalArqueo.TfrmModalArqueo.tvRecuentoDesc.Caption',
   'es-ES',
   'Forma de pago',
   'src/Caja/Modals/inMtoModalArqueo.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalArqueo.TfrmModalArqueo.tvRecuentoSistema.Caption',
   'es-ES',
   'Sistema',
   'src/Caja/Modals/inMtoModalArqueo.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalArqueo.TfrmModalArqueo.tvRecuentoImporte.Caption',
   'es-ES',
   'Recontado',
   'src/Caja/Modals/inMtoModalArqueo.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalArqueo.TfrmModalArqueo.tvRecuentoDiferencia.Caption',
   'es-ES',
   'Diferencia',
   'src/Caja/Modals/inMtoModalArqueo.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalArqueo.TfrmModalArqueo.lblRecTotalSistemaLbl.Caption',
   'es-ES',
   'Total sistema:',
   'src/Caja/Modals/inMtoModalArqueo.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalArqueo.TfrmModalArqueo.lblRecTotalRecuentoLbl.Caption',
   'es-ES',
   'Total recontado:',
   'src/Caja/Modals/inMtoModalArqueo.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalArqueo.TfrmModalArqueo.lblRecDiferenciaLbl.Caption',
   'es-ES',
   'Diferencia:',
   'src/Caja/Modals/inMtoModalArqueo.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalArqueo.TfrmModalArqueo.lblRetiradaLbl.Caption',
   'es-ES',
   'Retirada:',
   'src/Caja/Modals/inMtoModalArqueo.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoModalArqueo.TfrmModalArqueo.rgRetiradaTipo.Properties.Items[0].Ca',
     'ption'
   ),
   'es-ES',
   'Banco',
   'src/Caja/Modals/inMtoModalArqueo.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoModalArqueo.TfrmModalArqueo.rgRetiradaTipo.Properties.Items[1].Ca',
     'ption'
   ),
   'es-ES',
   'Encargado',
   'src/Caja/Modals/inMtoModalArqueo.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoModalArqueo.TfrmModalArqueo.rgRetiradaTipo.Properties.Items[2].Ca',
     'ption'
   ),
   'es-ES',
   'C. fuerte',
   'src/Caja/Modals/inMtoModalArqueo.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalArqueo.TfrmModalArqueo.lblDejoLbl.Caption',
   'es-ES',
   'Dejo para mañana:',
   'src/Caja/Modals/inMtoModalArqueo.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalArqueo.TfrmModalArqueo.lblDejoImporte.Caption',
   'es-ES',
   '0,00 EUR',
   'src/Caja/Modals/inMtoModalArqueo.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalArqueo.TfrmModalArqueo.lblObservacionesLbl.Caption',
   'es-ES',
   'Obs:',
   'src/Caja/Modals/inMtoModalArqueo.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalArqueo.TfrmModalArqueo.lblVendedorLbl.Caption',
   'es-ES',
   'Vendedor (nº empl.):',
   'src/Caja/Modals/inMtoModalArqueo.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalArqueo.TfrmModalArqueo.btnGrabarArqueo.Caption',
   'es-ES',
   'Grabar Arqueo y emitir justificante (F2)',
   'src/Caja/Modals/inMtoModalArqueo.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalArqueo.TfrmModalArqueo.lblESC.Caption',
   'es-ES',
   'ESC',
   'src/Caja/Modals/inMtoModalArqueo.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalArqueo.TfrmModalArqueo.btnAtras.Caption',
   'es-ES',
   'Atrás (ESC)',
   'src/Caja/Modals/inMtoModalArqueo.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalArqueo.TfrmModalArqueo.actEscape.Caption',
   'es-ES',
   'Escape',
   'src/Caja/Modals/inMtoModalArqueo.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalArqueo.TfrmModalArqueo.actTiraCaja.Caption',
   'es-ES',
   'Tira de Caja',
   'src/Caja/Modals/inMtoModalArqueo.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalArqueo.TfrmModalArqueo.actRecalcular.Caption',
   'es-ES',
   'Recalcular',
   'src/Caja/Modals/inMtoModalArqueo.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalArqueo.TfrmModalArqueo.actImprimir.Caption',
   'es-ES',
   'Imprimir',
   'src/Caja/Modals/inMtoModalArqueo.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalArqueo.TfrmModalArqueo.actGrabar.Caption',
   'es-ES',
   'Grabar',
   'src/Caja/Modals/inMtoModalArqueo.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalArqueo.TfrmModalArqueo.actDesplegarDesde.Caption',
   'es-ES',
   'Desplegar Desde',
   'src/Caja/Modals/inMtoModalArqueo.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalArqueo.TfrmModalArqueo.actDesplegarHasta.Caption',
   'es-ES',
   'Desplegar Hasta',
   'src/Caja/Modals/inMtoModalArqueo.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalArqueo.TfrmModalArqueo.actHistorico.Caption',
   'es-ES',
   'Histórico',
   'src/Caja/Modals/inMtoModalArqueo.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalArqueosHistCaja.TfrmModalArqueosHistCaja.Caption',
   'es-ES',
   'Histórico de Arqueos',
   'src/Caja/Modals/inMtoModalArqueosHistCaja.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalArqueosHistCaja.TfrmModalArqueosHistCaja.lblTitulo.Caption',
   'es-ES',
   'Histórico de Arqueos',
   'src/Caja/Modals/inMtoModalArqueosHistCaja.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalArqueosHistCaja.TfrmModalArqueosHistCaja.lblAyuda.Caption',
   'es-ES',
   'F2 = Duplicado ticket    F3 = Duplicado cierre    ESC = Salir',
   'src/Caja/Modals/inMtoModalArqueosHistCaja.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalArqueosHistCaja.TfrmModalArqueosHistCaja.colCodigo.Caption',
   'es-ES',
   'Código',
   'src/Caja/Modals/inMtoModalArqueosHistCaja.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalArqueosHistCaja.TfrmModalArqueosHistCaja.colDesde.Caption',
   'es-ES',
   'Desde',
   'src/Caja/Modals/inMtoModalArqueosHistCaja.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalArqueosHistCaja.TfrmModalArqueosHistCaja.colHasta.Caption',
   'es-ES',
   'Hasta',
   'src/Caja/Modals/inMtoModalArqueosHistCaja.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalArqueosHistCaja.TfrmModalArqueosHistCaja.colFase.Caption',
   'es-ES',
   'Fase',
   'src/Caja/Modals/inMtoModalArqueosHistCaja.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalArqueosHistCaja.TfrmModalArqueosHistCaja.colVentas.Caption',
   'es-ES',
   'Ventas',
   'src/Caja/Modals/inMtoModalArqueosHistCaja.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalArqueosHistCaja.TfrmModalArqueosHistCaja.colTotalVentas.Caption',
   'es-ES',
   'Total Ventas',
   'src/Caja/Modals/inMtoModalArqueosHistCaja.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalArqueosHistCaja.TfrmModalArqueosHistCaja.colEfectivo.Caption',
   'es-ES',
   'Efectivo Caja',
   'src/Caja/Modals/inMtoModalArqueosHistCaja.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalArqueosHistCaja.TfrmModalArqueosHistCaja.colRecuento.Caption',
   'es-ES',
   'Recuento',
   'src/Caja/Modals/inMtoModalArqueosHistCaja.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalArqueosHistCaja.TfrmModalArqueosHistCaja.colDiferencia.Caption',
   'es-ES',
   'Diferencia',
   'src/Caja/Modals/inMtoModalArqueosHistCaja.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalArqueosHistCaja.TfrmModalArqueosHistCaja.colUsuario.Caption',
   'es-ES',
   'Usuario',
   'src/Caja/Modals/inMtoModalArqueosHistCaja.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalArqueosHistCaja.TfrmModalArqueosHistCaja.btnDupTicket.Caption',
   'es-ES',
   'Duplicado ticket (F2)',
   'src/Caja/Modals/inMtoModalArqueosHistCaja.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalArqueosHistCaja.TfrmModalArqueosHistCaja.btnDupCierre.Caption',
   'es-ES',
   'Duplicado cierre (F3)',
   'src/Caja/Modals/inMtoModalArqueosHistCaja.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalArqueosHistCaja.TfrmModalArqueosHistCaja.btnSalir.Caption',
   'es-ES',
   'Salir (ESC)',
   'src/Caja/Modals/inMtoModalArqueosHistCaja.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalGastoCaja.TfrmModalGastoCaja.Caption',
   'es-ES',
   'Gastos por Caja / Retiradas (F7)',
   'src/Caja/Modals/inMtoModalGastoCaja.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalGastoCaja.TfrmModalGastoCaja.lblTitulo.Caption',
   'es-ES',
   'Registrar gasto o retirada de efectivo',
   'src/Caja/Modals/inMtoModalGastoCaja.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalGastoCaja.TfrmModalGastoCaja.lblTipoLbl.Caption',
   'es-ES',
   'Tipo:',
   'src/Caja/Modals/inMtoModalGastoCaja.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalGastoCaja.TfrmModalGastoCaja.rgTipo.Properties.Items[0].Caption',
   'es-ES',
   'Pago proveedor',
   'src/Caja/Modals/inMtoModalGastoCaja.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalGastoCaja.TfrmModalGastoCaja.rgTipo.Properties.Items[1].Caption',
   'es-ES',
   'Gastos limpieza',
   'src/Caja/Modals/inMtoModalGastoCaja.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalGastoCaja.TfrmModalGastoCaja.rgTipo.Properties.Items[2].Caption',
   'es-ES',
   'Retirada banco',
   'src/Caja/Modals/inMtoModalGastoCaja.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalGastoCaja.TfrmModalGastoCaja.rgTipo.Properties.Items[3].Caption',
   'es-ES',
   'Retirada encargado',
   'src/Caja/Modals/inMtoModalGastoCaja.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalGastoCaja.TfrmModalGastoCaja.rgTipo.Properties.Items[4].Caption',
   'es-ES',
   'Caja fuerte',
   'src/Caja/Modals/inMtoModalGastoCaja.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalGastoCaja.TfrmModalGastoCaja.lblEmpleadoLbl.Caption',
   'es-ES',
   'Empleado:',
   'src/Caja/Modals/inMtoModalGastoCaja.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalGastoCaja.TfrmModalGastoCaja.lblImporteLbl.Caption',
   'es-ES',
   'Importe:',
   'src/Caja/Modals/inMtoModalGastoCaja.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalGastoCaja.TfrmModalGastoCaja.lblConceptoLbl.Caption',
   'es-ES',
   'Concepto:',
   'src/Caja/Modals/inMtoModalGastoCaja.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalGastoCaja.TfrmModalGastoCaja.actAceptar.Caption',
   'es-ES',
   'Aceptar (F12)',
   'src/Caja/Modals/inMtoModalGastoCaja.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalGastoCaja.TfrmModalGastoCaja.actCancelar.Caption',
   'es-ES',
   'Cancelar (ESC)',
   'src/Caja/Modals/inMtoModalGastoCaja.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalImpArqueos.TfrmPrintArqueos.Caption',
   'es-ES',
   'Imprimir Histórico de Arqueos',
   'src/Caja/Modals/inMtoModalImpArqueos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalImpArqueos.TfrmPrintArqueos.lblFechas.Caption',
   'es-ES',
   'Rango de fechas:',
   'src/Caja/Modals/inMtoModalImpArqueos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalImpArqueos.TfrmPrintArqueos.lblDesde.Caption',
   'es-ES',
   'Fecha inicio:',
   'src/Caja/Modals/inMtoModalImpArqueos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalImpArqueos.TfrmPrintArqueos.lblHasta.Caption',
   'es-ES',
   'Fecha fin:',
   'src/Caja/Modals/inMtoModalImpArqueos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalImpArqueos.TfrmPrintArqueos.lblCajaTit.Caption',
   'es-ES',
   'Caja a imprimir:',
   'src/Caja/Modals/inMtoModalImpArqueos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalImpArqueos.TfrmPrintArqueos.lblEmpresa.Caption',
   'es-ES',
   'Empresa:',
   'src/Caja/Modals/inMtoModalImpArqueos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalImpArqueos.TfrmPrintArqueos.lblAlmacen.Caption',
   'es-ES',
   'Almacén:',
   'src/Caja/Modals/inMtoModalImpArqueos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalImpArqueos.TfrmPrintArqueos.lblCaja.Caption',
   'es-ES',
   'Caja:',
   'src/Caja/Modals/inMtoModalImpArqueos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalImpDepositos.TfrmPrintDepositos.Caption',
   'es-ES',
   'Imprimir Histórico de Depósitos',
   'src/Caja/Modals/inMtoModalImpDepositos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalImpDepositos.TfrmPrintDepositos.lblFechas.Caption',
   'es-ES',
   'Rango de fechas:',
   'src/Caja/Modals/inMtoModalImpDepositos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalImpDepositos.TfrmPrintDepositos.lblDesde.Caption',
   'es-ES',
   'Fecha inicio:',
   'src/Caja/Modals/inMtoModalImpDepositos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalImpDepositos.TfrmPrintDepositos.lblHasta.Caption',
   'es-ES',
   'Fecha fin:',
   'src/Caja/Modals/inMtoModalImpDepositos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalImpDepositos.TfrmPrintDepositos.lblCajaTit.Caption',
   'es-ES',
   'Caja a imprimir:',
   'src/Caja/Modals/inMtoModalImpDepositos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalImpDepositos.TfrmPrintDepositos.lblEmpresa.Caption',
   'es-ES',
   'Empresa:',
   'src/Caja/Modals/inMtoModalImpDepositos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalImpDepositos.TfrmPrintDepositos.lblAlmacen.Caption',
   'es-ES',
   'Almacén:',
   'src/Caja/Modals/inMtoModalImpDepositos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalImpDepositos.TfrmPrintDepositos.lblCaja.Caption',
   'es-ES',
   'Caja:',
   'src/Caja/Modals/inMtoModalImpDepositos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalImpOperaciones.TfrmPrintOperaciones.Caption',
   'es-ES',
   'Imprimir Histórico de Operaciones',
   'src/Caja/Modals/inMtoModalImpOperaciones.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalImpOperaciones.TfrmPrintOperaciones.lblFechas.Caption',
   'es-ES',
   'Rango de fechas:',
   'src/Caja/Modals/inMtoModalImpOperaciones.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalImpOperaciones.TfrmPrintOperaciones.lblDesde.Caption',
   'es-ES',
   'Fecha inicio:',
   'src/Caja/Modals/inMtoModalImpOperaciones.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalImpOperaciones.TfrmPrintOperaciones.lblHasta.Caption',
   'es-ES',
   'Fecha fin:',
   'src/Caja/Modals/inMtoModalImpOperaciones.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalImpOperaciones.TfrmPrintOperaciones.lblCajaTit.Caption',
   'es-ES',
   'Caja a imprimir:',
   'src/Caja/Modals/inMtoModalImpOperaciones.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalImpOperaciones.TfrmPrintOperaciones.lblEmpresa.Caption',
   'es-ES',
   'Empresa:',
   'src/Caja/Modals/inMtoModalImpOperaciones.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalImpOperaciones.TfrmPrintOperaciones.lblAlmacen.Caption',
   'es-ES',
   'Almacén:',
   'src/Caja/Modals/inMtoModalImpOperaciones.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalImpOperaciones.TfrmPrintOperaciones.lblCaja.Caption',
   'es-ES',
   'Caja:',
   'src/Caja/Modals/inMtoModalImpOperaciones.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalImpOperacionesVenta.TfrmPrintOperacionesVenta.Caption',
   'es-ES',
   'Listado de operaciones de venta',
   'src/Caja/Modals/inMtoModalImpOperacionesVenta.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalImpOperacionesVenta.TfrmPrintOperacionesVenta.lblFechas.Caption',
   'es-ES',
   'Rango de fechas:',
   'src/Caja/Modals/inMtoModalImpOperacionesVenta.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalImpOperacionesVenta.TfrmPrintOperacionesVenta.lblDesde.Caption',
   'es-ES',
   'Fecha inicio:',
   'src/Caja/Modals/inMtoModalImpOperacionesVenta.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalImpOperacionesVenta.TfrmPrintOperacionesVenta.lblHasta.Caption',
   'es-ES',
   'Fecha fin:',
   'src/Caja/Modals/inMtoModalImpOperacionesVenta.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoModalImpOperacionesVenta.TfrmPrintOperacionesVenta.lblContexto.Ca',
     'ption'
   ),
   'es-ES',
   'TPV activo:',
   'src/Caja/Modals/inMtoModalImpOperacionesVenta.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalImpOperacionesVenta.TfrmPrintOperacionesVenta.lblEmpresa.Caption',
   'es-ES',
   'Empresa:',
   'src/Caja/Modals/inMtoModalImpOperacionesVenta.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalImpOperacionesVenta.TfrmPrintOperacionesVenta.lblAlmacen.Caption',
   'es-ES',
   'Almacén:',
   'src/Caja/Modals/inMtoModalImpOperacionesVenta.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalImpOperacionesVenta.TfrmPrintOperacionesVenta.lblCaja.Caption',
   'es-ES',
   'Caja:',
   'src/Caja/Modals/inMtoModalImpOperacionesVenta.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoModalImpOperacionesVenta.TfrmPrintOperacionesVenta.tsUbicaciones.',
     'Caption'
   ),
   'es-ES',
   'Empresas / almacenes / cajas',
   'src/Caja/Modals/inMtoModalImpOperacionesVenta.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoModalImpOperacionesVenta.TfrmPrintOperacionesVenta.lblUbicaciones',
     '.Caption'
   ),
   'es-ES',
   'Marque las ubicaciones que desea acumular en el listado.',
   'src/Caja/Modals/inMtoModalImpOperacionesVenta.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoModalImpOperacionesVenta.TfrmPrintOperacionesVenta.btnMarcarTodas',
     '.Caption'
   ),
   'es-ES',
   'Marcar todas',
   'src/Caja/Modals/inMtoModalImpOperacionesVenta.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoModalImpOperacionesVenta.TfrmPrintOperacionesVenta.btnDesmarcarTo',
     'das.Caption'
   ),
   'es-ES',
   'Desmarcar todas',
   'src/Caja/Modals/inMtoModalImpOperacionesVenta.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalImpPagos.TfrmPrintPagos.Caption',
   'es-ES',
   'Imprimir Histórico de Pagos',
   'src/Caja/Modals/inMtoModalImpPagos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalImpPagos.TfrmPrintPagos.lblFechas.Caption',
   'es-ES',
   'Rango de fechas:',
   'src/Caja/Modals/inMtoModalImpPagos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalImpPagos.TfrmPrintPagos.lblDesde.Caption',
   'es-ES',
   'Fecha inicio:',
   'src/Caja/Modals/inMtoModalImpPagos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalImpPagos.TfrmPrintPagos.lblHasta.Caption',
   'es-ES',
   'Fecha fin:',
   'src/Caja/Modals/inMtoModalImpPagos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalImpPagos.TfrmPrintPagos.lblCajaTit.Caption',
   'es-ES',
   'Caja a imprimir:',
   'src/Caja/Modals/inMtoModalImpPagos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalImpPagos.TfrmPrintPagos.lblEmpresa.Caption',
   'es-ES',
   'Empresa:',
   'src/Caja/Modals/inMtoModalImpPagos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalImpPagos.TfrmPrintPagos.lblAlmacen.Caption',
   'es-ES',
   'Almacén:',
   'src/Caja/Modals/inMtoModalImpPagos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalImpPagos.TfrmPrintPagos.lblCaja.Caption',
   'es-ES',
   'Caja:',
   'src/Caja/Modals/inMtoModalImpPagos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalImpPagos.TfrmPrintPagos.lblFormasPago.Caption',
   'es-ES',
   'Formas de pago (en el periodo):',
   'src/Caja/Modals/inMtoModalImpPagos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalTiraCaja.TfrmModalTiraCaja.Caption',
   'es-ES',
   'Tira de Caja',
   'src/Caja/Modals/inMtoModalTiraCaja.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalTiraCaja.TfrmModalTiraCaja.lblTitulo.Caption',
   'es-ES',
   'Tira de Caja',
   'src/Caja/Modals/inMtoModalTiraCaja.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalTiraCaja.TfrmModalTiraCaja.lblSerie.Caption',
   'es-ES',
   'Serie de Factura Simplificada:',
   'src/Caja/Modals/inMtoModalTiraCaja.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalTiraCaja.TfrmModalTiraCaja.lblAgrupamiento.Caption',
   'es-ES',
   'Agrupamiento:',
   'src/Caja/Modals/inMtoModalTiraCaja.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalTiraCaja.TfrmModalTiraCaja.chkQR.Caption',
   'es-ES',
   'Imprimir QR Verifactu',
   'src/Caja/Modals/inMtoModalTiraCaja.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalTiraCaja.TfrmModalTiraCaja.chkTraspasos.Caption',
   'es-ES',
   'Incluir traspasos salientes (origen)',
   'src/Caja/Modals/inMtoModalTiraCaja.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalTiraCaja.TfrmModalTiraCaja.chkIngresos.Caption',
   'es-ES',
   'Incluir ingresos por caja',
   'src/Caja/Modals/inMtoModalTiraCaja.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalTiraCaja.TfrmModalTiraCaja.chkGastos.Caption',
   'es-ES',
   'Incluir gastos por caja',
   'src/Caja/Modals/inMtoModalTiraCaja.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalTiraCaja.TfrmModalTiraCaja.chkCredito.Caption',
   'es-ES',
   'Incluir ventas a crédito (depósitos)',
   'src/Caja/Modals/inMtoModalTiraCaja.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalTiraCaja.TfrmModalTiraCaja.btnImprimir.Caption',
   'es-ES',
   'Imprimir',
   'src/Caja/Modals/inMtoModalTiraCaja.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalTiraCaja.TfrmModalTiraCaja.btnExcel.Caption',
   'es-ES',
   'Ver Excel',
   'src/Caja/Modals/inMtoModalTiraCaja.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalTiraCaja.TfrmModalTiraCaja.btnCancelar.Caption',
   'es-ES',
   'Cancelar (ESC)',
   'src/Caja/Modals/inMtoModalTiraCaja.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema')
ON DUPLICATE KEY UPDATE
  `TEXTO_TRAD` = VALUES(`TEXTO_TRAD`),
  `CONTEXTO_TRAD` = VALUES(`CONTEXTO_TRAD`),
  `ESACTIVO_TRAD` = VALUES(`ESACTIVO_TRAD`),
  `INSTANTE_MODIF` = CURRENT_TIMESTAMP,
  `USUARIO_MODIF` = VALUES(`USUARIO_ALTA`);
