-- Catálogo de textos españoles extraídos de los DFM.
-- Generado por generar_traducciones_dfm.ps1.
INSERT INTO `fza_traducciones` (
  `CLAVE_TRAD`, `IDIOMA_TRAD`, `TEXTO_TRAD`, `CONTEXTO_TRAD`,
  `ESACTIVO_TRAD`, `INSTANTE_ALTA`, `USUARIO_ALTA`
) VALUES
  ('inMtoModalGenerarSKUs.TfrmMtoModalGenerarSKUS.Caption',
   'es-ES',
   'Generar SKUS',
   'src/Modals/inMtoModalGenerarSKUs.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalGenerarSKUs.TfrmMtoModalGenerarSKUS.btnAddValue.Caption',
   'es-ES',
   '&Añadir Valor (F3)',
   'src/Modals/inMtoModalGenerarSKUs.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoModalGenerarSKUs.TfrmMtoModalGenerarSKUS.tvMaestroNOMBRE_ATRIBUTO',
     '.Caption'
   ),
   'es-ES',
   'Variación',
   'src/Modals/inMtoModalGenerarSKUs.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalGenerarSKUs.TfrmMtoModalGenerarSKUS.tvMaestroORDEN_ACA.Caption',
   'es-ES',
   'Orden',
   'src/Modals/inMtoModalGenerarSKUs.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalGenerarSKUs.TfrmMtoModalGenerarSKUS.tvDetalleNOMBRE_AC.Caption',
   'es-ES',
   'Nombre Atr',
   'src/Modals/inMtoModalGenerarSKUs.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalGenerarSKUs.TfrmMtoModalGenerarSKUS.tvDetalleASIGNADO.Caption',
   'es-ES',
   'Asignar',
   'src/Modals/inMtoModalGenerarSKUs.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalGenerarSKUs.TfrmMtoModalGenerarSKUS.tvDetalleORDEN_AV.Caption',
   'es-ES',
   'Orden (doble click cambiar orden)',
   'src/Modals/inMtoModalGenerarSKUs.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalGenFilter.TfrmModalGenFilter.Caption',
   'es-ES',
   'Filtrar por grupos de datos',
   'src/Modals/inMtoModalGenFilter.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalGenFilter.TfrmModalGenFilter.btnGuardar.Caption',
   'es-ES',
   '&Aceptar',
   'src/Modals/inMtoModalGenFilter.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalGenFilter.TfrmModalGenFilter.btnCancelar.Caption',
   'es-ES',
   '&Cancelar',
   'src/Modals/inMtoModalGenFilter.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalGenFilter.TfrmModalGenFilter.tsEmpresas.Caption',
   'es-ES',
   '&1_Empresas -',
   'src/Modals/inMtoModalGenFilter.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalGenFilter.TfrmModalGenFilter.tsFamilias.Caption',
   'es-ES',
   '&2_Familias -',
   'src/Modals/inMtoModalGenFilter.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalGenFilter.TfrmModalGenFilter.tsTarifas.Caption',
   'es-ES',
   '&3_Tarifas -',
   'src/Modals/inMtoModalGenFilter.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalGenFilter.TfrmModalGenFilter.tsArticulos.Caption',
   'es-ES',
   '&4_Articulos -',
   'src/Modals/inMtoModalGenFilter.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalGenFilter.TfrmModalGenFilter.tsVentas.Caption',
   'es-ES',
   '&5_Borradores -',
   'src/Modals/inMtoModalGenFilter.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalGenImp.TfrmPrint.Caption',
   'es-ES',
   'Imprimir',
   'src/Modals/inMtoModalGenImp.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalGenImp.TfrmPrint.btnPDF.Caption',
   'es-ES',
   '&PDF',
   'src/Modals/inMtoModalGenImp.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalGenImp.TfrmPrint.btnImprimir.Caption',
   'es-ES',
   '&Imprimir',
   'src/Modals/inMtoModalGenImp.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalGenImp.TfrmPrint.btnVistaPreliminar.Caption',
   'es-ES',
   '&Vista Preliminar',
   'src/Modals/inMtoModalGenImp.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalGenImp.TfrmPrint.btnSalir.Caption',
   'es-ES',
   '&Salir',
   'src/Modals/inMtoModalGenImp.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalGenImp.TfrmPrint.btnEditar.Caption',
   'es-ES',
   '&Editar',
   'src/Modals/inMtoModalGenImp.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalGenImp.TfrmPrint.btnExcel.Caption',
   'es-ES',
   'E&xcel',
   'src/Modals/inMtoModalGenImp.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalGenImp.TfrmPrint.actSalir.Caption',
   'es-ES',
   'Salir',
   'src/Modals/inMtoModalGenImp.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalGenImpEle.TfrmMtoModalGenImpEle.Caption',
   'es-ES',
   'Elección de formulario creados por el usuario',
   'src/Modals/inMtoModalGenImpEle.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalGenImpEle.TfrmMtoModalGenImpEle.btnUsarOriginal.Caption',
   'es-ES',
   'Usar &Original',
   'src/Modals/inMtoModalGenImpEle.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalGenImpEle.TfrmMtoModalGenImpEle.btnSelectFormato.Caption',
   'es-ES',
   'Usar &Formato Elegido',
   'src/Modals/inMtoModalGenImpEle.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalGenImpEle.TfrmMtoModalGenImpEle.btnDeleteFormato.Caption',
   'es-ES',
   '&Borrar Formato Elegido',
   'src/Modals/inMtoModalGenImpEle.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalGenImpEle.TfrmMtoModalGenImpEle.btnSalir.Caption',
   'es-ES',
   '&Volver',
   'src/Modals/inMtoModalGenImpEle.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalGenImpEle.TfrmMtoModalGenImpEle.chkPredeterminado.Caption',
   'es-ES',
   'Guardar selección',
   'src/Modals/inMtoModalGenImpEle.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalGenImpSave.TfrmModalGenImpSave.Caption',
   'es-ES',
   'Guardar Objeto Editado',
   'src/Modals/inMtoModalGenImpSave.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalGenImpSave.TfrmModalGenImpSave.lbl1.Caption',
   'es-ES',
   'Nombre origen',
   'src/Modals/inMtoModalGenImpSave.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalGenImpSave.TfrmModalGenImpSave.lbl2.Caption',
   'es-ES',
   'Nombre del objeto',
   'src/Modals/inMtoModalGenImpSave.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalGenImpSave.TfrmModalGenImpSave.lbl3.Caption',
   'es-ES',
   'Permiso',
   'src/Modals/inMtoModalGenImpSave.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalGenImpSave.TfrmModalGenImpSave.btnGuardar.Caption',
   'es-ES',
   '&Guardar',
   'src/Modals/inMtoModalGenImpSave.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalGenImpSave.TfrmModalGenImpSave.btnCancelar.Caption',
   'es-ES',
   '&Cancelar',
   'src/Modals/inMtoModalGenImpSave.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalGenPass.TfrmModalGenPass.Caption',
   'es-ES',
   'Establecer Password Usuario',
   'src/Modals/inMtoModalGenPass.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalGenPass.TfrmModalGenPass.lbl1.Caption',
   'es-ES',
   'Nombre usuario',
   'src/Modals/inMtoModalGenPass.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalGenPass.TfrmModalGenPass.lbl2.Caption',
   'es-ES',
   'Contraseña',
   'src/Modals/inMtoModalGenPass.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalGenPass.TfrmModalGenPass.lbl3.Caption',
   'es-ES',
   'Repita Contraseña',
   'src/Modals/inMtoModalGenPass.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalGenPass.TfrmModalGenPass.btnGuardar.Caption',
   'es-ES',
   '&Guardar',
   'src/Modals/inMtoModalGenPass.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalGenPass.TfrmModalGenPass.btnCancelar.Caption',
   'es-ES',
   '&Cancelar',
   'src/Modals/inMtoModalGenPass.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalGestionFiltros.TfrmModalGestionFiltros.Caption',
   'es-ES',
   'Filtros guardados',
   'src/Modals/inMtoModalGestionFiltros.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalGestionFiltros.TfrmModalGestionFiltros.lblCompartidoCon.Caption',
   'es-ES',
   'Compartido con',
   'src/Modals/inMtoModalGestionFiltros.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoModalGestionFiltros.TfrmModalGestionFiltros.tvFiltrosNOMBRE_FILT.',
     'Caption'
   ),
   'es-ES',
   'Nombre',
   'src/Modals/inMtoModalGestionFiltros.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoModalGestionFiltros.TfrmModalGestionFiltros.tvFiltrosDESCRIPCION_',
     'FILT.Caption'
   ),
   'es-ES',
   'Descripción',
   'src/Modals/inMtoModalGestionFiltros.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoModalGestionFiltros.TfrmModalGestionFiltros.tvFiltrosUSUARIO_PROP',
     'IETARIO_FILT.Caption'
   ),
   'es-ES',
   'Propietario',
   'src/Modals/inMtoModalGestionFiltros.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalGestionFiltros.TfrmModalGestionFiltros.lblCondiciones.Caption',
   'es-ES',
   'Condiciones del filtro seleccionado (puede editarlas):',
   'src/Modals/inMtoModalGestionFiltros.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoModalGestionFiltros.TfrmModalGestionFiltros.btnCompartirUsuario.C',
     'aption'
   ),
   'es-ES',
   'Compartir con &usuario...',
   'src/Modals/inMtoModalGestionFiltros.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalGestionFiltros.TfrmModalGestionFiltros.btnCompartirGrupo.Caption',
   'es-ES',
   'Compartir con &grupo...',
   'src/Modals/inMtoModalGestionFiltros.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalGestionFiltros.TfrmModalGestionFiltros.btnCompartirTodos.Caption',
   'es-ES',
   'Compartir con &todos',
   'src/Modals/inMtoModalGestionFiltros.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoModalGestionFiltros.TfrmModalGestionFiltros.btnQuitarCompartido.C',
     'aption'
   ),
   'es-ES',
   '&Quitar destino seleccionado',
   'src/Modals/inMtoModalGestionFiltros.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalGestionFiltros.TfrmModalGestionFiltros.btnAplicar.Caption',
   'es-ES',
   '&Aplicar',
   'src/Modals/inMtoModalGestionFiltros.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalGestionFiltros.TfrmModalGestionFiltros.btnGuardarCambios.Caption',
   'es-ES',
   '&Guardar cambios',
   'src/Modals/inMtoModalGestionFiltros.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoModalGestionFiltros.TfrmModalGestionFiltros.btnReemplazarActual.C',
     'aption'
   ),
   'es-ES',
   'Reemplazar por el &actual',
   'src/Modals/inMtoModalGestionFiltros.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalGestionFiltros.TfrmModalGestionFiltros.btnGuardarCopia.Caption',
   'es-ES',
   'Guardar &copia...',
   'src/Modals/inMtoModalGestionFiltros.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalGestionFiltros.TfrmModalGestionFiltros.btnRenombrar.Caption',
   'es-ES',
   'Editar &datos...',
   'src/Modals/inMtoModalGestionFiltros.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalGestionFiltros.TfrmModalGestionFiltros.btnBorrar.Caption',
   'es-ES',
   'Bo&rrar',
   'src/Modals/inMtoModalGestionFiltros.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalGestionFiltros.TfrmModalGestionFiltros.btnCerrar.Caption',
   'es-ES',
   '&Cerrar',
   'src/Modals/inMtoModalGestionFiltros.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalGridGuias.TfrmModalGridGuias.Caption',
   'es-ES',
   'Guías del grid',
   'src/Modals/inMtoModalGridGuias.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalGridGuias.TfrmModalGridGuias.lblCamposMaster.Caption',
   'es-ES',
   'Campos del grid (master):',
   'src/Modals/inMtoModalGridGuias.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalGuardarFiltro.TfrmModalGuardarFiltro.Caption',
   'es-ES',
   'Guardar filtro',
   'src/Modals/inMtoModalGuardarFiltro.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalGuardarFiltro.TfrmModalGuardarFiltro.lblNombre.Caption',
   'es-ES',
   'Nombre',
   'src/Modals/inMtoModalGuardarFiltro.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalGuardarFiltro.TfrmModalGuardarFiltro.lblDescripcion.Caption',
   'es-ES',
   'Descripcion',
   'src/Modals/inMtoModalGuardarFiltro.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalGuardarFiltro.TfrmModalGuardarFiltro.btnGuardar.Caption',
   'es-ES',
   '&Guardar',
   'src/Modals/inMtoModalGuardarFiltro.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalGuardarFiltro.TfrmModalGuardarFiltro.btnCancelar.Caption',
   'es-ES',
   '&Cancelar',
   'src/Modals/inMtoModalGuardarFiltro.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalGuiasBase.TfrmModalGuiasBase.Caption',
   'es-ES',
   'Guías',
   'src/Modals/inMtoModalGuiasBase.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalGuiasBase.TfrmModalGuiasBase.lblTitulo.Caption',
   'es-ES',
   'Guías',
   'src/Modals/inMtoModalGuiasBase.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalGuiasBase.TfrmModalGuiasBase.lblInfo.Caption',
   'es-ES',
   ' ',
   'src/Modals/inMtoModalGuiasBase.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalGuiasBase.TfrmModalGuiasBase.lblCamposMaster.Caption',
   'es-ES',
   'Campos master:',
   'src/Modals/inMtoModalGuiasBase.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalGuiasBase.TfrmModalGuiasBase.lblTabla.Caption',
   'es-ES',
   'Tabla externa:',
   'src/Modals/inMtoModalGuiasBase.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalGuiasBase.TfrmModalGuiasBase.lblCamposTabla.Caption',
   'es-ES',
   'Campos de la tabla (detail):',
   'src/Modals/inMtoModalGuiasBase.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalGuiasBase.TfrmModalGuiasBase.lblCodigo.Caption',
   'es-ES',
   'Código de la guía:',
   'src/Modals/inMtoModalGuiasBase.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalGuiasBase.TfrmModalGuiasBase.lblResumen.Caption',
   'es-ES',
   'Enlace configurado:',
   'src/Modals/inMtoModalGuiasBase.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalGuiasBase.TfrmModalGuiasBase.btnAnadir.Caption',
   'es-ES',
   'Añadir guía',
   'src/Modals/inMtoModalGuiasBase.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalGuiasBase.TfrmModalGuiasBase.btnEliminar.Caption',
   'es-ES',
   'Eliminar seleccionada',
   'src/Modals/inMtoModalGuiasBase.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalGuiasBase.TfrmModalGuiasBase.btnCerrar.Caption',
   'es-ES',
   '&Cerrar',
   'src/Modals/inMtoModalGuiasBase.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalGuiasBase.TfrmModalGuiasBase.tvGuiasCODIGO.Caption',
   'es-ES',
   'Código',
   'src/Modals/inMtoModalGuiasBase.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalGuiasBase.TfrmModalGuiasBase.tvGuiasTABLA.Caption',
   'es-ES',
   'Tabla',
   'src/Modals/inMtoModalGuiasBase.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalGuiasBase.TfrmModalGuiasBase.tvGuiasMASTER_FIELDS.Caption',
   'es-ES',
   'Master fields',
   'src/Modals/inMtoModalGuiasBase.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalGuiasBase.TfrmModalGuiasBase.tvGuiasDETAIL_FIELDS.Caption',
   'es-ES',
   'Detail fields',
   'src/Modals/inMtoModalGuiasBase.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalGuiasBase.TfrmModalGuiasBase.tvGuiasORDEN.Caption',
   'es-ES',
   'Orden',
   'src/Modals/inMtoModalGuiasBase.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalGuiasBase.TfrmModalGuiasBase.tvGuiasACTIVO.Caption',
   'es-ES',
   'Activo',
   'src/Modals/inMtoModalGuiasBase.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalGuiasBase.TfrmModalGuiasBase.actSalir.Caption',
   'es-ES',
   'Salir',
   'src/Modals/inMtoModalGuiasBase.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalImpAlbCompra.TfrmPrintAlbCompra.Caption',
   'es-ES',
   'Imprimir Albarán de Compra',
   'src/Modals/inMtoModalImpAlbCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalImpAlbCompra.TfrmPrintAlbCompra.lblSerie.Caption',
   'es-ES',
   'Serie',
   'src/Modals/inMtoModalImpAlbCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalImpAlbCompra.TfrmPrintAlbCompra.lblNumero.Caption',
   'es-ES',
   'Número',
   'src/Modals/inMtoModalImpAlbCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalImpAlbCompraV.TfrmPrintAlbCompraV.Caption',
   'es-ES',
   'Imprimir Albarán de Compra (Vertical)',
   'src/Modals/inMtoModalImpAlbCompraV.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalImpAlbCompraV.TfrmPrintAlbCompraV.lblSerie.Caption',
   'es-ES',
   'Serie',
   'src/Modals/inMtoModalImpAlbCompraV.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalImpAlbCompraV.TfrmPrintAlbCompraV.lblNumero.Caption',
   'es-ES',
   'Número',
   'src/Modals/inMtoModalImpAlbCompraV.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalImpBalanceSinTallas.TfrmPrintBalanceSinTallas.Caption',
   'es-ES',
   'Balance de almacén sin tallas',
   'src/Modals/inMtoModalImpBalanceSinTallas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalImpBalanceTallas.TfrmPrintBalanceTallas.Caption',
   'es-ES',
   'Balance de almacén por tallas',
   'src/Modals/inMtoModalImpBalanceTallas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalImpDevCompra.TfrmPrintDevCompra.Caption',
   'es-ES',
   'Imprimir Devolución de Compra',
   'src/Modals/inMtoModalImpDevCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalImpDevCompra.TfrmPrintDevCompra.lblSerie.Caption',
   'es-ES',
   'Serie',
   'src/Modals/inMtoModalImpDevCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalImpDevCompra.TfrmPrintDevCompra.lblNumero.Caption',
   'es-ES',
   'Número',
   'src/Modals/inMtoModalImpDevCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalImpDevCompraV.TfrmPrintDevCompraV.Caption',
   'es-ES',
   'Imprimir Devolución de Compra (Vertical)',
   'src/Modals/inMtoModalImpDevCompraV.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalImpDevCompraV.TfrmPrintDevCompraV.lblSerie.Caption',
   'es-ES',
   'Serie',
   'src/Modals/inMtoModalImpDevCompraV.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalImpDevCompraV.TfrmPrintDevCompraV.lblNumero.Caption',
   'es-ES',
   'Número',
   'src/Modals/inMtoModalImpDevCompraV.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalImpDocsProveedor.TfrmPrintDocsProveedor.Caption',
   'es-ES',
   'Listado de documentos proveedor',
   'src/Modals/inMtoModalImpDocsProveedor.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalImpEfectosPago.TfrmPrintEfectosPago.Caption',
   'es-ES',
   'Listado de efectos de pago',
   'src/Modals/inMtoModalImpEfectosPago.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalImpFac.TfrmPrintFac.Caption',
   'es-ES',
   'Imprimir Borrador',
   'src/Modals/inMtoModalImpFac.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalImpFac.TfrmPrintFac.lblcxlbl1.Caption',
   'es-ES',
   'Borrador Número',
   'src/Modals/inMtoModalImpFac.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalImpFac.TfrmPrintFac.cxrdgrp1.Caption',
   'es-ES',
   'Opciones',
   'src/Modals/inMtoModalImpFac.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalImpFac.TfrmPrintFac.rbActual.Caption',
   'es-ES',
   'Imprimir Borrador actual',
   'src/Modals/inMtoModalImpFac.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalImpFac.TfrmPrintFac.rbRangoFechas.Caption',
   'es-ES',
   'Imprimir Rango de Borradores',
   'src/Modals/inMtoModalImpFac.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalImpFac.TfrmPrintFac.lblcxlbl2.Caption',
   'es-ES',
   'Desde',
   'src/Modals/inMtoModalImpFac.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalImpFac.TfrmPrintFac.lblcxlbl3.Caption',
   'es-ES',
   'Hasta',
   'src/Modals/inMtoModalImpFac.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalImpFacCompra.TfrmPrintFacCompra.Caption',
   'es-ES',
   'Imprimir Factura de Compra',
   'src/Modals/inMtoModalImpFacCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalImpFacCompra.TfrmPrintFacCompra.lblSerie.Caption',
   'es-ES',
   'Serie',
   'src/Modals/inMtoModalImpFacCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalImpFacCompra.TfrmPrintFacCompra.lblNumero.Caption',
   'es-ES',
   'Número',
   'src/Modals/inMtoModalImpFacCompra.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalImpFacCompraV.TfrmPrintFacCompraV.Caption',
   'es-ES',
   'Imprimir Factura de Compra (Vertical)',
   'src/Modals/inMtoModalImpFacCompraV.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalImpFacCompraV.TfrmPrintFacCompraV.lblSerie.Caption',
   'es-ES',
   'Serie',
   'src/Modals/inMtoModalImpFacCompraV.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalImpFacCompraV.TfrmPrintFacCompraV.lblNumero.Caption',
   'es-ES',
   'Número',
   'src/Modals/inMtoModalImpFacCompraV.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalImpMovVentasArt.TfrmPrintMovVentasArt.Caption',
   'es-ES',
   'Movimientos de ventas por artículos y fechas',
   'src/Modals/inMtoModalImpMovVentasArt.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalImpMultiFiltro.TfrmPrintMultiFiltro.Caption',
   'es-ES',
   'Informe con filtros',
   'src/Modals/inMtoModalImpMultiFiltro.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalImportarPedidosPS.TfrmModalImportarPedidosPS.Caption',
   'es-ES',
   'Importar pedidos de PrestaShop',
   'src/Modals/inMtoModalImportarPedidosPS.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalImportarPedidosPS.TfrmModalImportarPedidosPS.lblBaseURL.Caption',
   'es-ES',
   'URL base API PrestaShop (ej. http://midominio.com/api)',
   'src/Modals/inMtoModalImportarPedidosPS.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalImportarPedidosPS.TfrmModalImportarPedidosPS.lblApiKey.Caption',
   'es-ES',
   'API Key',
   'src/Modals/inMtoModalImportarPedidosPS.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalImportarPedidosPS.TfrmModalImportarPedidosPS.btnConectar.Caption',
   'es-ES',
   'Conectar y listar',
   'src/Modals/inMtoModalImportarPedidosPS.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalImportarPedidosPS.TfrmModalImportarPedidosPS.colSel.Caption',
   'es-ES',
   'Sel.',
   'src/Modals/inMtoModalImportarPedidosPS.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalImportarPedidosPS.TfrmModalImportarPedidosPS.colId.Caption',
   'es-ES',
   'ID PS',
   'src/Modals/inMtoModalImportarPedidosPS.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalImportarPedidosPS.TfrmModalImportarPedidosPS.colRef.Caption',
   'es-ES',
   'Referencia',
   'src/Modals/inMtoModalImportarPedidosPS.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalImportarPedidosPS.TfrmModalImportarPedidosPS.colFecha.Caption',
   'es-ES',
   'Fecha',
   'src/Modals/inMtoModalImportarPedidosPS.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalImportarPedidosPS.TfrmModalImportarPedidosPS.colCliente.Caption',
   'es-ES',
   'Cliente',
   'src/Modals/inMtoModalImportarPedidosPS.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalImportarPedidosPS.TfrmModalImportarPedidosPS.colTotal.Caption',
   'es-ES',
   'Total',
   'src/Modals/inMtoModalImportarPedidosPS.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalImportarPedidosPS.TfrmModalImportarPedidosPS.colEstado.Caption',
   'es-ES',
   'Estado',
   'src/Modals/inMtoModalImportarPedidosPS.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoModalImportarPedidosPS.TfrmModalImportarPedidosPS.colImportado.Ca',
     'ption'
   ),
   'es-ES',
   'Importado?',
   'src/Modals/inMtoModalImportarPedidosPS.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalImportarPedidosPS.TfrmModalImportarPedidosPS.lblEstado.Caption',
   'es-ES',
   'Listo',
   'src/Modals/inMtoModalImportarPedidosPS.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalImportarPedidosPS.TfrmModalImportarPedidosPS.btnImportar.Caption',
   'es-ES',
   'Importar selección',
   'src/Modals/inMtoModalImportarPedidosPS.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalImportarPedidosPS.TfrmModalImportarPedidosPS.btnCerrar.Caption',
   'es-ES',
   'Cerrar',
   'src/Modals/inMtoModalImportarPedidosPS.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalImpRecFac.TfrmPrintRecFac.Caption',
   'es-ES',
   'Imprimir Recibos',
   'src/Modals/inMtoModalImpRecFac.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalImpRecFac.TfrmPrintRecFac.lblcxlbl1.Caption',
   'es-ES',
   'Recibo Número',
   'src/Modals/inMtoModalImpRecFac.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalImpRecFac.TfrmPrintRecFac.cxrdgrp1.Caption',
   'es-ES',
   'Opciones',
   'src/Modals/inMtoModalImpRecFac.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalImpRecFac.TfrmPrintRecFac.rbActual.Caption',
   'es-ES',
   'Imprimir recibo actual',
   'src/Modals/inMtoModalImpRecFac.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalImpRecFac.TfrmPrintRecFac.rbRangoFechas.Caption',
   'es-ES',
   'Imprimir todos los recibos de este borrador',
   'src/Modals/inMtoModalImpRecFac.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalImpSesion.TfrmPrintSesion.Caption',
   'es-ES',
   'Imprimir Sesión de Compra',
   'src/Modals/inMtoModalImpSesion.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalImpSesion.TfrmPrintSesion.lblSerie.Caption',
   'es-ES',
   'Serie',
   'src/Modals/inMtoModalImpSesion.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalImpSesion.TfrmPrintSesion.lblNumero.Caption',
   'es-ES',
   'Número',
   'src/Modals/inMtoModalImpSesion.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalIncidencias.TfrmModalIncidencias.Caption',
   'es-ES',
   'Incidencias',
   'src/Modals/inMtoModalIncidencias.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalIncidencias.TfrmModalIncidencias.lblTitulo.Caption',
   'es-ES',
   'Se han detectado las siguientes incidencias:',
   'src/Modals/inMtoModalIncidencias.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalIncidencias.TfrmModalIncidencias.btnAceptar.Caption',
   'es-ES',
   '&Aceptar',
   'src/Modals/inMtoModalIncidencias.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalInformesGuias.TfrmModalInformesGuias.Caption',
   'es-ES',
   'Guías del informe',
   'src/Modals/inMtoModalInformesGuias.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalInformesGuias.TfrmModalInformesGuias.lblCamposMaster.Caption',
   'es-ES',
   'Campos del informe (master):',
   'src/Modals/inMtoModalInformesGuias.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoModalListadoVentas.TfrmModalListadoVentas.Caption',
   'es-ES',
   'Listado de ventas',
   'src/Modals/inMtoModalListadoVentas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema')
ON DUPLICATE KEY UPDATE
  `TEXTO_TRAD` = VALUES(`TEXTO_TRAD`),
  `CONTEXTO_TRAD` = VALUES(`CONTEXTO_TRAD`),
  `ESACTIVO_TRAD` = VALUES(`ESACTIVO_TRAD`),
  `INSTANTE_MODIF` = CURRENT_TIMESTAMP,
  `USUARIO_MODIF` = VALUES(`USUARIO_ALTA`);
