-- Catálogo de textos españoles extraídos de los DFM.
-- Generado por generar_traducciones_dfm.ps1.
INSERT INTO `fza_traducciones` (
  `CLAVE_TRAD`, `IDIOMA_TRAD`, `TEXTO_TRAD`, `CONTEXTO_TRAD`,
  `ESACTIVO_TRAD`, `INSTANTE_ALTA`, `USUARIO_ALTA`
) VALUES
  ('inMtoGen.TfrmMtoGen.Caption',
   'es-ES',
   'Ventana Genérica',
   'src/Forms/inMtoGen.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoGen.TfrmMtoGen.tsLista.Caption',
   'es-ES',
   '&Lista',
   'src/Forms/inMtoGen.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoGen.TfrmMtoGen.tsFicha.Caption',
   'es-ES',
   '&Ficha',
   'src/Forms/inMtoGen.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoGen.TfrmMtoGen.tsPerfil.Caption',
   'es-ES',
   'Perfil',
   'src/Forms/inMtoGen.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoGen.TfrmMtoGen.lblTextoaBuscarPerfil.Caption',
   'es-ES',
   'Texto a buscar',
   'src/Forms/inMtoGen.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoGen.TfrmMtoGen.btnCargarColumnas.Caption',
   'es-ES',
   '&Cargar columnas',
   'src/Forms/inMtoGen.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoGen.TfrmMtoGen.btnCargarCaptions.Caption',
   'es-ES',
   '&Cargar captions',
   'src/Forms/inMtoGen.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoGen.TfrmMtoGen.btnCargarVblesGlob.Caption',
   'es-ES',
   '&Cargar Vbles Globales',
   'src/Forms/inMtoGen.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoGen.TfrmMtoGen.pnlPerfilDetail.Caption',
   'es-ES',
   'pnlPerfilDetail',
   'src/Forms/inMtoGen.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoGen.TfrmMtoGen.sbFiltros.Hint',
   'es-ES',
   'Filtros guardados',
   'src/Forms/inMtoGen.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoGen.TfrmMtoGen.sbFiltros.Caption',
   'es-ES',
   '▾',
   'src/Forms/inMtoGen.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoGen.TfrmMtoGen.sbExportExcel.Hint',
   'es-ES',
   'Exportar Excel',
   'src/Forms/inMtoGen.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoGen.TfrmMtoGen.sbGrabarGrid.Hint',
   'es-ES',
   'Grabar Grid',
   'src/Forms/inMtoGen.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoGen.TfrmMtoGen.sbResetGrid.Hint',
   'es-ES',
   'Reset Grid',
   'src/Forms/inMtoGen.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoGen.TfrmMtoGen.sbBestFit.Hint',
   'es-ES',
   'Ajustar anchos de columna',
   'src/Forms/inMtoGen.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoGen.TfrmMtoGen.sbBestFit.Caption',
   'es-ES',
   '↔',
   'src/Forms/inMtoGen.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoGen.TfrmMtoGen.lblTextoaBuscar.Caption',
   'es-ES',
   'Texto a buscar',
   'src/Forms/inMtoGen.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoGen.TfrmMtoGen.rbBBDD.Caption',
   'es-ES',
   'Buscar BBDD',
   'src/Forms/inMtoGen.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoGen.TfrmMtoGen.rbGrid.Caption',
   'es-ES',
   'Buscar Grid',
   'src/Forms/inMtoGen.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoGen.TfrmMtoGen.btnGrabar.Caption',
   'es-ES',
   '&Grabar',
   'src/Forms/inMtoGen.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoGen.TfrmMtoGen.btnCancelar.Caption',
   'es-ES',
   '&Cancelar',
   'src/Forms/inMtoGen.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoGen.TfrmMtoGen.btnSalir.Caption',
   'es-ES',
   '&Salir',
   'src/Forms/inMtoGen.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoGen.TfrmMtoGen.lblEditMode.Caption',
   'es-ES',
   'EditMode',
   'src/Forms/inMtoGen.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoGen.TfrmMtoGen.lblTablaOrigen.Caption',
   'es-ES',
   'TablaOrigen',
   'src/Forms/inMtoGen.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoGen.TfrmMtoGen.actEliminarRegistro.Caption',
   'es-ES',
   'Eliminar registro',
   'src/Forms/inMtoGen.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoGen.TfrmMtoGen.actRegistroAnterior.Caption',
   'es-ES',
   'Registro anterior',
   'src/Forms/inMtoGen.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoGen.TfrmMtoGen.actRegistroSiguiente.Caption',
   'es-ES',
   'Registro siguiente',
   'src/Forms/inMtoGen.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoGen.TfrmMtoGen.actInsertarRegistro.Caption',
   'es-ES',
   'Insertar registro',
   'src/Forms/inMtoGen.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoGen.TfrmMtoGen.actPrimerRegistro.Caption',
   'es-ES',
   'Primer registro',
   'src/Forms/inMtoGen.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoGen.TfrmMtoGen.actUltimoRegistro.Caption',
   'es-ES',
   'Ultimo registro',
   'src/Forms/inMtoGen.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoGen.TfrmMtoGen.actEditarRegistro.Caption',
   'es-ES',
   'Editar registro',
   'src/Forms/inMtoGen.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoGen.TfrmMtoGen.actGrabarRegistro.Caption',
   'es-ES',
   'Grabar registro',
   'src/Forms/inMtoGen.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoGen.TfrmMtoGen.actFotoArticulo.Caption',
   'es-ES',
   'Foto articulo',
   'src/Forms/inMtoGen.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoGen.TfrmMtoGen.actConsultaStock.Caption',
   'es-ES',
   'Consulta stock',
   'src/Forms/inMtoGen.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoGen.TfrmMtoGen.actRetrocederBloque.Caption',
   'es-ES',
   'Retroceder bloque',
   'src/Forms/inMtoGen.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoGen.TfrmMtoGen.actAvanzarBloque.Caption',
   'es-ES',
   'Avanzar bloque',
   'src/Forms/inMtoGen.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoGeneradorProcesos.TfrmMtoGeneradorProcesos.Caption',
   'es-ES',
   'Generador de Procesos',
   'src/Forms/inMtoGeneradorProcesos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoGeneradorProcesos.TfrmMtoGeneradorProcesos.cxgrdbclmnGrdDBTabPrin',
     'CODIGO_GENERADORPROCESO.Caption'
   ),
   'es-ES',
   'Código Proceso',
   'src/Forms/inMtoGeneradorProcesos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoGeneradorProcesos.TfrmMtoGeneradorProcesos.cxgrdbclmnGrdDBTabPrin',
     'NOMBRE_GENERADORPROCESO.Caption'
   ),
   'es-ES',
   'Nombre Proceso',
   'src/Forms/inMtoGeneradorProcesos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoGeneradorProcesos.TfrmMtoGeneradorProcesos.lblCodigo.Caption',
   'es-ES',
   'Código',
   'src/Forms/inMtoGeneradorProcesos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoGeneradorProcesos.TfrmMtoGeneradorProcesos.lblNombre.Caption',
   'es-ES',
   'Nombre',
   'src/Forms/inMtoGeneradorProcesos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoGeneradorProcesos.TfrmMtoGeneradorProcesos.tsSQL.Caption',
   'es-ES',
   '&1_Código SQL',
   'src/Forms/inMtoGeneradorProcesos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoGeneradorProcesos.TfrmMtoGeneradorProcesos.btnBonito.Caption',
   'es-ES',
   '&Bonito',
   'src/Forms/inMtoGeneradorProcesos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoGeneradorProcesos.TfrmMtoGeneradorProcesos.tsMetadatos.Caption',
   'es-ES',
   '&2_Metadatos',
   'src/Forms/inMtoGeneradorProcesos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoGeneradorProcesos.TfrmMtoGeneradorProcesos.pnlTabs.Caption',
   'es-ES',
   'pnlTabs',
   'src/Forms/inMtoGeneradorProcesos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoGeneradorProcesos.TfrmMtoGeneradorProcesos.tsEstructura.Caption',
   'es-ES',
   '&Estructura Metadato',
   'src/Forms/inMtoGeneradorProcesos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoGeneradorProcesos.TfrmMtoGeneradorProcesos.tsContenido.Caption',
   'es-ES',
   '&Vista Contenido',
   'src/Forms/inMtoGeneradorProcesos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoGeneradorProcesos.TfrmMtoGeneradorProcesos.cxgrdbclmncxgrdbtblvwc',
     'xgrd1DBTableView1LINEA_LINEA1.Caption'
   ),
   'es-ES',
   'Nro Linea',
   'src/Forms/inMtoGeneradorProcesos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoGeneradorProcesos.TfrmMtoGeneradorProcesos.cxgrdbclmncxgrdbtblvwc',
     'xgrd1DBTableView1CODIGO_ARTICULO_LINEA1.Caption'
   ),
   'es-ES',
   'Código Artículo',
   'src/Forms/inMtoGeneradorProcesos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoGeneradorProcesos.TfrmMtoGeneradorProcesos.cxgrdbclmncxgrdbtblvwc',
     'xgrd1DBTableView1DESCRIPCION_ARTICULO_LINEA1.Caption'
   ),
   'es-ES',
   'Descripción',
   'src/Forms/inMtoGeneradorProcesos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoGeneradorProcesos.TfrmMtoGeneradorProcesos.cxgrdbclmncxgrdbtblvwc',
     'xgrd1DBTableView1CANTIDAD_LINEA1.Caption'
   ),
   'es-ES',
   'Cantidad',
   'src/Forms/inMtoGeneradorProcesos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoGeneradorProcesos.TfrmMtoGeneradorProcesos.cxgrdbclmnLineasFactur',
     'acionTIPO_CANTIDAD_ARTICULO_FACTURA_LINEA1.Caption'
   ),
   'es-ES',
   'Tipo Cantidad',
   'src/Forms/inMtoGeneradorProcesos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoGeneradorProcesos.TfrmMtoGeneradorProcesos.cxgrdbclmnLineasFactur',
     'acionPRECIOVENTA_SIVA_ARTICULO_FACTURA_LINEA1.Caption'
   ),
   'es-ES',
   'Precio SIVA',
   'src/Forms/inMtoGeneradorProcesos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoGeneradorProcesos.TfrmMtoGeneradorProcesos.cxgrdbclmnLineasFactur',
     'acionPORCEN_IVA_FACTURA_LINEA1.Caption'
   ),
   'es-ES',
   'Porcentaje IVA',
   'src/Forms/inMtoGeneradorProcesos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoGeneradorProcesos.TfrmMtoGeneradorProcesos.cxgrdbclmnLineasFactur',
     'acionTIPOIVA_ARTICULO_FACTURA_LINEA1.Caption'
   ),
   'es-ES',
   'Tipo IVA',
   'src/Forms/inMtoGeneradorProcesos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoGeneradorProcesos.TfrmMtoGeneradorProcesos.cxgrdbclmncxgrdbtblvwc',
     'xgrd1DBTableView1PRECIOVENTA_ARTICULO_LINEA1.Caption'
   ),
   'es-ES',
   'Precio CIVA',
   'src/Forms/inMtoGeneradorProcesos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoGeneradorProcesos.TfrmMtoGeneradorProcesos.cxgrdbclmncxgrdbtblvwc',
     'xgrd1DBTableView1SUM_TOTAL_LINEA1.Caption'
   ),
   'es-ES',
   'Total',
   'src/Forms/inMtoGeneradorProcesos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoGeneradorProcesos.TfrmMtoGeneradorProcesos.cxgrdbclmnLineasFactur',
     'acionFECHA_ENTREGA_FACTURA_LINEA1.Caption'
   ),
   'es-ES',
   'Fecha de Entrega',
   'src/Forms/inMtoGeneradorProcesos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoGeneradorProcesos.TfrmMtoGeneradorProcesos.btnExportarExcelMeta.C',
     'aption'
   ),
   'es-ES',
   'Exp. E&xcel',
   'src/Forms/inMtoGeneradorProcesos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoGeneradorProcesos.TfrmMtoGeneradorProcesos.btnEditarMeta.Caption',
   'es-ES',
   'Editar G&rid',
   'src/Forms/inMtoGeneradorProcesos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoGeneradorProcesos.TfrmMtoGeneradorProcesos.pnlTree.Caption',
   'es-ES',
   'pnlTree',
   'src/Forms/inMtoGeneradorProcesos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoGeneradorProcesos.TfrmMtoGeneradorProcesos.btnRefresh.Caption',
   'es-ES',
   'Refrescar &MetaDatos',
   'src/Forms/inMtoGeneradorProcesos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoGeneradorProcesos.TfrmMtoGeneradorProcesos.lblAyudaSeleccion.Caption',
   'es-ES',
   'Control+A al editor',
   'src/Forms/inMtoGeneradorProcesos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoGeneradorProcesos.TfrmMtoGeneradorProcesos.tsVistaDatos.Caption',
   'es-ES',
   '&3_VistaDatos',
   'src/Forms/inMtoGeneradorProcesos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoGeneradorProcesos.TfrmMtoGeneradorProcesos.cxgrdbclmncxgrdbtblvwc',
     'xgrd1DBTableView1LINEA_LINEA11.Caption'
   ),
   'es-ES',
   'Nro Linea',
   'src/Forms/inMtoGeneradorProcesos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoGeneradorProcesos.TfrmMtoGeneradorProcesos.cxgrdbclmncxgrdbtblvwc',
     'xgrd1DBTableView1CODIGO_ARTICULO_LINEA11.Caption'
   ),
   'es-ES',
   'Código Artículo',
   'src/Forms/inMtoGeneradorProcesos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoGeneradorProcesos.TfrmMtoGeneradorProcesos.cxgrdbclmncxgrdbtblvwc',
     'xgrd1DBTableView1DESCRIPCION_ARTICULO_LINEA11.Caption'
   ),
   'es-ES',
   'Descripción',
   'src/Forms/inMtoGeneradorProcesos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoGeneradorProcesos.TfrmMtoGeneradorProcesos.cxgrdbclmncxgrdbtblvwc',
     'xgrd1DBTableView1CANTIDAD_LINEA11.Caption'
   ),
   'es-ES',
   'Cantidad',
   'src/Forms/inMtoGeneradorProcesos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoGeneradorProcesos.TfrmMtoGeneradorProcesos.cxgrdbclmnLineasFactur',
     'acionTIPO_CANTIDAD_ARTICULO_FACTURA_LINEA11.Caption'
   ),
   'es-ES',
   'Tipo Cantidad',
   'src/Forms/inMtoGeneradorProcesos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoGeneradorProcesos.TfrmMtoGeneradorProcesos.cxgrdbclmnLineasFactur',
     'acionPRECIOVENTA_SIVA_ARTICULO_FACTURA_LINEA11.Caption'
   ),
   'es-ES',
   'Precio SIVA',
   'src/Forms/inMtoGeneradorProcesos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoGeneradorProcesos.TfrmMtoGeneradorProcesos.cxgrdbclmnLineasFactur',
     'acionPORCEN_IVA_FACTURA_LINEA11.Caption'
   ),
   'es-ES',
   'Porcentaje IVA',
   'src/Forms/inMtoGeneradorProcesos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoGeneradorProcesos.TfrmMtoGeneradorProcesos.cxgrdbclmnLineasFactur',
     'acionTIPOIVA_ARTICULO_FACTURA_LINEA11.Caption'
   ),
   'es-ES',
   'Tipo IVA',
   'src/Forms/inMtoGeneradorProcesos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoGeneradorProcesos.TfrmMtoGeneradorProcesos.cxgrdbclmncxgrdbtblvwc',
     'xgrd1DBTableView1PRECIOVENTA_ARTICULO_LINEA11.Caption'
   ),
   'es-ES',
   'Precio CIVA',
   'src/Forms/inMtoGeneradorProcesos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoGeneradorProcesos.TfrmMtoGeneradorProcesos.cxgrdbclmncxgrdbtblvwc',
     'xgrd1DBTableView1SUM_TOTAL_LINEA11.Caption'
   ),
   'es-ES',
   'Total',
   'src/Forms/inMtoGeneradorProcesos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoGeneradorProcesos.TfrmMtoGeneradorProcesos.cxgrdbclmnLineasFactur',
     'acionFECHA_ENTREGA_FACTURA_LINEA11.Caption'
   ),
   'es-ES',
   'Fecha de Entrega',
   'src/Forms/inMtoGeneradorProcesos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoGeneradorProcesos.TfrmMtoGeneradorProcesos.btnExportarExcel.Caption',
   'es-ES',
   'Exp. E&xcel',
   'src/Forms/inMtoGeneradorProcesos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoGeneradorProcesos.TfrmMtoGeneradorProcesos.btnEditar.Caption',
   'es-ES',
   'Editar G&rid',
   'src/Forms/inMtoGeneradorProcesos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoGeneradorProcesos.TfrmMtoGeneradorProcesos.btnCopiarDatos.Caption',
   'es-ES',
   'Copiar &Datos',
   'src/Forms/inMtoGeneradorProcesos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoGeneradorProcesos.TfrmMtoGeneradorProcesos.tsOtros.Caption',
   'es-ES',
   '&4_Otros',
   'src/Forms/inMtoGeneradorProcesos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoGeneradorProcesos.TfrmMtoGeneradorProcesos.cxlblUsuarioAlta.Caption',
   'es-ES',
   'Usuario Alta',
   'src/Forms/inMtoGeneradorProcesos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoGeneradorProcesos.TfrmMtoGeneradorProcesos.cxlblInstanteAlta.Caption',
   'es-ES',
   'Instante Alta',
   'src/Forms/inMtoGeneradorProcesos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoGeneradorProcesos.TfrmMtoGeneradorProcesos.cxlblInstanteModif.Caption',
   'es-ES',
   'Instante Modificación',
   'src/Forms/inMtoGeneradorProcesos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoGeneradorProcesos.TfrmMtoGeneradorProcesos.cxlblUsuarioModif.Caption',
   'es-ES',
   'Usuario Última Modificación',
   'src/Forms/inMtoGeneradorProcesos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoGeneradorProcesos.TfrmMtoGeneradorProcesos.btnEjecutar.Caption',
   'es-ES',
   '&Ejecutar (F5)',
   'src/Forms/inMtoGeneradorProcesos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoGeneradorProcesos.TfrmMtoGeneradorProcesos.btnAbrirScript.Caption',
   'es-ES',
   '&Script (F3)',
   'src/Forms/inMtoGeneradorProcesos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoGeneradorProcesos.TfrmMtoGeneradorProcesos.ActionSeleccionar.Caption',
   'es-ES',
   'Seleccionar Todo',
   'src/Forms/inMtoGeneradorProcesos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoGeneradorProcesos.TfrmMtoGeneradorProcesos.ActionEjecutar.Caption',
   'es-ES',
   'Ejecutar',
   'src/Forms/inMtoGeneradorProcesos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoGeneradorProcesos.TfrmMtoGeneradorProcesos.actComentar.Caption',
   'es-ES',
   'Comentar',
   'src/Forms/inMtoGeneradorProcesos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoGeneradorProcesos.TfrmMtoGeneradorProcesos.actAbrirScript.Caption',
   'es-ES',
   'Abrir Script',
   'src/Forms/inMtoGeneradorProcesos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoGenSearch.TfrmMtoSearch.Caption',
   'es-ES',
   'frmMtoSearch',
   'src/Forms/inMtoGenSearch.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoGenSearch.TfrmMtoSearch.btnAceptar.Caption',
   'es-ES',
   '&Aceptar (F12)',
   'src/Forms/inMtoGenSearch.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoGenSearch.TfrmMtoSearch.btnCancelar1.Caption',
   'es-ES',
   '&Cancelar (ESC)',
   'src/Forms/inMtoGenSearch.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoGenSearch.TfrmMtoSearch.btnAltaRapida.Caption',
   'es-ES',
   'Alta &Rápida',
   'src/Forms/inMtoGenSearch.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoGrupos.TfrmMtoGrupos.Caption',
   'es-ES',
   'Grupos',
   'src/Forms/inMtoGrupos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoGrupos.TfrmMtoGrupos.cxGrdDBTabPrinGRUPO_USUARIO.Caption',
   'es-ES',
   'Nombre Grupo',
   'src/Forms/inMtoGrupos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoGrupos.TfrmMtoGrupos.cxGrdDBTabPrinESGRUPOADMINISTRADOR.Caption',
   'es-ES',
   'Es Grupo Administrador',
   'src/Forms/inMtoGrupos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoGrupos.TfrmMtoGrupos.lblNombreGrupo.Caption',
   'es-ES',
   'Nombre grupo',
   'src/Forms/inMtoGrupos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoGrupos.TfrmMtoGrupos.lblEsGrupoAdmin.Caption',
   'es-ES',
   'Es grupo administradores',
   'src/Forms/inMtoGrupos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoGrupos.TfrmMtoGrupos.tvUsuariosUSUARIO_USUARIO.Caption',
   'es-ES',
   'Usuario',
   'src/Forms/inMtoGrupos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoGrupos.TfrmMtoGrupos.tvUsuariosGRUPO_USUARIO.Caption',
   'es-ES',
   'Grupo',
   'src/Forms/inMtoGrupos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoGrupos.TfrmMtoGrupos.tvUsuariosEMPRESADEF_USUARIO.Caption',
   'es-ES',
   'Empresa por defecto',
   'src/Forms/inMtoGrupos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoGrupos.TfrmMtoGrupos.tvUsuariosULTIMOLOGIN_USUARIO.Caption',
   'es-ES',
   'Última conexión',
   'src/Forms/inMtoGrupos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoInventarios.TfrmMtoInventarios.Caption',
   'es-ES',
   'Mantenimiento de Inventarios',
   'src/Forms/inMtoInventarios.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoInventarios.TfrmMtoInventarios.colCODIGO_EMP_INV.Caption',
   'es-ES',
   'Empresa',
   'src/Forms/inMtoInventarios.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoInventarios.TfrmMtoInventarios.colCODIGO_ALM_INV.Caption',
   'es-ES',
   'Almacén',
   'src/Forms/inMtoInventarios.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoInventarios.TfrmMtoInventarios.colSERIE_INV.Caption',
   'es-ES',
   'Serie',
   'src/Forms/inMtoInventarios.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoInventarios.TfrmMtoInventarios.colNUMERO_INV.Caption',
   'es-ES',
   'Número',
   'src/Forms/inMtoInventarios.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoInventarios.TfrmMtoInventarios.colFECHA_INV.Caption',
   'es-ES',
   'Fecha',
   'src/Forms/inMtoInventarios.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoInventarios.TfrmMtoInventarios.colESTADO_INV.Caption',
   'es-ES',
   'Estado',
   'src/Forms/inMtoInventarios.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoInventarios.TfrmMtoInventarios.colDESCRIPCION_INV.Caption',
   'es-ES',
   'Descripción',
   'src/Forms/inMtoInventarios.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoInventarios.TfrmMtoInventarios.colTOT_UDS_DIF_INV.Caption',
   'es-ES',
   'Uds. diferencia',
   'src/Forms/inMtoInventarios.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoInventarios.TfrmMtoInventarios.colTOT_EUR_DIF_INV.Caption',
   'es-ES',
   '€ diferencia',
   'src/Forms/inMtoInventarios.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoInventarios.TfrmMtoInventarios.lblEmpresa.Caption',
   'es-ES',
   'Empresa',
   'src/Forms/inMtoInventarios.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoInventarios.TfrmMtoInventarios.lblAlmacen.Caption',
   'es-ES',
   'Almacén',
   'src/Forms/inMtoInventarios.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoInventarios.TfrmMtoInventarios.lblSerie.Caption',
   'es-ES',
   'Serie',
   'src/Forms/inMtoInventarios.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoInventarios.TfrmMtoInventarios.lblNumero.Caption',
   'es-ES',
   'Número',
   'src/Forms/inMtoInventarios.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoInventarios.TfrmMtoInventarios.lblFecha.Caption',
   'es-ES',
   'Fecha',
   'src/Forms/inMtoInventarios.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoInventarios.TfrmMtoInventarios.lblEstado.Caption',
   'es-ES',
   'Estado',
   'src/Forms/inMtoInventarios.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoInventarios.TfrmMtoInventarios.lblDescripcion.Caption',
   'es-ES',
   'Descripción',
   'src/Forms/inMtoInventarios.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoInventarios.TfrmMtoInventarios.btnEnviarRecuento.Caption',
   'es-ES',
   'Enviar a recuento móvil',
   'src/Forms/inMtoInventarios.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoInventarios.TfrmMtoInventarios.btnRecogerRecuento.Caption',
   'es-ES',
   'Recoger recuento móvil',
   'src/Forms/inMtoInventarios.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoInventarios.TfrmMtoInventarios.tsDetalle.Caption',
   'es-ES',
   '&1. Detalle del inventario',
   'src/Forms/inMtoInventarios.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoInventarios.TfrmMtoInventarios.btnAnadirLinea.Caption',
   'es-ES',
   '+ Añadir línea',
   'src/Forms/inMtoInventarios.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoInventarios.TfrmMtoInventarios.btnAnadirSkusArt.Hint',
   'es-ES',
   CONCAT(
     'Añade todos los SKUs del artículo de la línea actual que tengan ',
     'movimientos en el almacén del inventario.'
   ),
   'src/Forms/inMtoInventarios.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoInventarios.TfrmMtoInventarios.btnAnadirSkusArt.Caption',
   'es-ES',
   '+ SKUs con mov.',
   'src/Forms/inMtoInventarios.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoInventarios.TfrmMtoInventarios.btnRecalcularDetalle.Caption',
   'es-ES',
   'Recalcular teórico/PMP',
   'src/Forms/inMtoInventarios.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoInventarios.TfrmMtoInventarios.btnCargarExcel.Caption',
   'es-ES',
   'Cargar Excel',
   'src/Forms/inMtoInventarios.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoInventarios.TfrmMtoInventarios.btnExportarInv.Caption',
   'es-ES',
   'Exportar a Excel',
   'src/Forms/inMtoInventarios.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoInventarios.TfrmMtoInventarios.btnIraArticulo.Caption',
   'es-ES',
   'Ir a Artículo',
   'src/Forms/inMtoInventarios.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoInventarios.TfrmMtoInventarios.chkVerColumnasAtributos.Hint',
   'es-ES',
   CONCAT(
     'Activa la construcción de las columnas SKU1..SKU5 con los nombres de ',
     'atributo del artículo. Implica recorrer todas las líneas para ',
     'desempaquetar el SKU. Si hay más de 150 líneas se muestra una barra ',
     'de progreso.'
   ),
   'src/Forms/inMtoInventarios.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoInventarios.TfrmMtoInventarios.chkVerColumnasAtributos.Caption',
   'es-ES',
   'Ver atributos en columnas',
   'src/Forms/inMtoInventarios.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoInventarios.TfrmMtoInventarios.tvLineasLINEA.Caption',
   'es-ES',
   'Línea',
   'src/Forms/inMtoInventarios.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoInventarios.TfrmMtoInventarios.tvLineasARTICULO.Caption',
   'es-ES',
   'Artículo',
   'src/Forms/inMtoInventarios.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoInventarios.TfrmMtoInventarios.tvLineasUNIDAD.Caption',
   'es-ES',
   'SKU/Artículo',
   'src/Forms/inMtoInventarios.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoInventarios.TfrmMtoInventarios.tvLineasSKU1.Caption',
   'es-ES',
   'SKU 1',
   'src/Forms/inMtoInventarios.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoInventarios.TfrmMtoInventarios.tvLineasSKU2.Caption',
   'es-ES',
   'SKU 2',
   'src/Forms/inMtoInventarios.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoInventarios.TfrmMtoInventarios.tvLineasSKU3.Caption',
   'es-ES',
   'SKU 3',
   'src/Forms/inMtoInventarios.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoInventarios.TfrmMtoInventarios.tvLineasSKU4.Caption',
   'es-ES',
   'SKU 4',
   'src/Forms/inMtoInventarios.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoInventarios.TfrmMtoInventarios.tvLineasSKU5.Caption',
   'es-ES',
   'SKU 5',
   'src/Forms/inMtoInventarios.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoInventarios.TfrmMtoInventarios.tvLineasDESCRIPCION.Caption',
   'es-ES',
   'Descripción',
   'src/Forms/inMtoInventarios.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoInventarios.TfrmMtoInventarios.tvLineasLOTE.Caption',
   'es-ES',
   'Lote',
   'src/Forms/inMtoInventarios.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoInventarios.TfrmMtoInventarios.tvLineasCADUCIDAD.Caption',
   'es-ES',
   'Caducidad',
   'src/Forms/inMtoInventarios.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoInventarios.TfrmMtoInventarios.tvLineasUDS_TEORICAS.Caption',
   'es-ES',
   'Uds. teóricas',
   'src/Forms/inMtoInventarios.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoInventarios.TfrmMtoInventarios.tvLineasUDS_FISICAS.Caption',
   'es-ES',
   'Recuento',
   'src/Forms/inMtoInventarios.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoInventarios.TfrmMtoInventarios.tvLineasPMP_ACTUAL.Caption',
   'es-ES',
   'PMP actual',
   'src/Forms/inMtoInventarios.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoInventarios.TfrmMtoInventarios.tvLineasPMP_NUEVO.Caption',
   'es-ES',
   'PMP nuevo',
   'src/Forms/inMtoInventarios.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoInventarios.TfrmMtoInventarios.tvLineasDIF_UNIDADES.Caption',
   'es-ES',
   'Dif. uds.',
   'src/Forms/inMtoInventarios.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoInventarios.TfrmMtoInventarios.tvLineasDIF_COSTE.Caption',
   'es-ES',
   'Dif. coste',
   'src/Forms/inMtoInventarios.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoInventarios.TfrmMtoInventarios.tvLineasUDS_REGULARIZADAS.Caption',
   'es-ES',
   'Uds. regul.',
   'src/Forms/inMtoInventarios.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoInventarios.TfrmMtoInventarios.tvLineasFECHA_RECUENTO.Caption',
   'es-ES',
   'Hora recuento',
   'src/Forms/inMtoInventarios.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoInventarios.TfrmMtoInventarios.tvLineasUSUARIO.Caption',
   'es-ES',
   'Usuario',
   'src/Forms/inMtoInventarios.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoInventarios.TfrmMtoInventarios.tsMovsRegul.Caption',
   'es-ES',
   '&2. Movimientos regularizados',
   'src/Forms/inMtoInventarios.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoInventarios.TfrmMtoInventarios.lblInfoMovs.Caption',
   'es-ES',
   'Movimientos generados al aplicar este inventario en el Kardex',
   'src/Forms/inMtoInventarios.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoInventarios.TfrmMtoInventarios.btnEliminarRegularizacion.Caption',
   'es-ES',
   'Eliminar regularización',
   'src/Forms/inMtoInventarios.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoInventarios.TfrmMtoInventarios.tvMovsNUMERO.Caption',
   'es-ES',
   'Número',
   'src/Forms/inMtoInventarios.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoInventarios.TfrmMtoInventarios.tvMovsTIPO.Caption',
   'es-ES',
   'Tipo',
   'src/Forms/inMtoInventarios.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoInventarios.TfrmMtoInventarios.tvMovsARTICULO.Caption',
   'es-ES',
   'Artículo',
   'src/Forms/inMtoInventarios.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoInventarios.TfrmMtoInventarios.tvMovsUNIDAD.Caption',
   'es-ES',
   'SKU',
   'src/Forms/inMtoInventarios.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoInventarios.TfrmMtoInventarios.tvMovsCANTIDAD.Caption',
   'es-ES',
   'Cantidad',
   'src/Forms/inMtoInventarios.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoInventarios.TfrmMtoInventarios.tvMovsPRECIO.Caption',
   'es-ES',
   'PMP',
   'src/Forms/inMtoInventarios.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoInventarios.TfrmMtoInventarios.tvMovsCOSTE.Caption',
   'es-ES',
   'Coste',
   'src/Forms/inMtoInventarios.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoInventarios.TfrmMtoInventarios.tvMovsFECHA.Caption',
   'es-ES',
   'Fecha',
   'src/Forms/inMtoInventarios.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoInventarios.TfrmMtoInventarios.tvMovsACTIVO.Caption',
   'es-ES',
   'Activo',
   'src/Forms/inMtoInventarios.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoInventarios.TfrmMtoInventarios.btnExportarExcel.Caption',
   'es-ES',
   '&Exp Excel',
   'src/Forms/inMtoInventarios.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoInventarios.TfrmMtoInventarios.btnIraArticuloMov.Caption',
   'es-ES',
   'Ir a Artículo',
   'src/Forms/inMtoInventarios.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoInventarios.TfrmMtoInventarios.tsCabecera.Caption',
   'es-ES',
   '&3.Otros',
   'src/Forms/inMtoInventarios.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoInventarios.TfrmMtoInventarios.lblObservaciones.Caption',
   'es-ES',
   'Observaciones',
   'src/Forms/inMtoInventarios.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoInventarios.TfrmMtoInventarios.pnlTotales.Caption',
   'es-ES',
   '  Totales del descuadre  ',
   'src/Forms/inMtoInventarios.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoInventarios.TfrmMtoInventarios.lblTotalUnidades.Caption',
   'es-ES',
   'Total unidades de descuadre',
   'src/Forms/inMtoInventarios.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoInventarios.TfrmMtoInventarios.lblTotalEuros.Caption',
   'es-ES',
   'Variación económica (€)',
   'src/Forms/inMtoInventarios.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoInventarios.TfrmMtoInventarios.lblUsuarioAlta.Caption',
   'es-ES',
   'Alta',
   'src/Forms/inMtoInventarios.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoInventarios.TfrmMtoInventarios.lblInstanteAlta.Caption',
   'es-ES',
   'Fecha Alta',
   'src/Forms/inMtoInventarios.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoInventarios.TfrmMtoInventarios.lblUsuarioModif.Caption',
   'es-ES',
   'Modif.',
   'src/Forms/inMtoInventarios.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoInventarios.TfrmMtoInventarios.lblInstanteModif.Caption',
   'es-ES',
   'Fecha Modif.',
   'src/Forms/inMtoInventarios.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoInventarios.TfrmMtoInventarios.btnAplicar.Caption',
   'es-ES',
   '&Regularizar',
   'src/Forms/inMtoInventarios.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoInventarios.TfrmMtoInventarios.btnCargar.Caption',
   'es-ES',
   'Car&gar',
   'src/Forms/inMtoInventarios.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoInventarios.TfrmMtoInventarios.actIraArticulo.Caption',
   'es-ES',
   'actIraArticulo',
   'src/Forms/inMtoInventarios.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoIvas.TfrmMtoIvas.Caption',
   'es-ES',
   'IVA',
   'src/Forms/inMtoIvas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoIvas.TfrmMtoIvas.cxGrdDBTabPrinCODIGO_IVA.Caption',
   'es-ES',
   'Código IVA',
   'src/Forms/inMtoIvas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoIvas.TfrmMtoIvas.cxGrdDBTabPrinGRUPO_ZONA_IVA.Caption',
   'es-ES',
   'Zona IVA',
   'src/Forms/inMtoIvas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoIvas.TfrmMtoIvas.cxGrdDBTabPrinDESCRIPCION_ZONA_IVA.Caption',
   'es-ES',
   'Descripción',
   'src/Forms/inMtoIvas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoIvas.TfrmMtoIvas.cxGrdDBTabPrinPORCENNORMAL_IVA.Caption',
   'es-ES',
   '%Normal',
   'src/Forms/inMtoIvas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoIvas.TfrmMtoIvas.cxGrdDBTabPrinPORCENNORMAL_RE_IVA.Caption',
   'es-ES',
   '%RE Normal',
   'src/Forms/inMtoIvas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoIvas.TfrmMtoIvas.cxGrdDBTabPrinPORCENREDUCIDO_IVA.Caption',
   'es-ES',
   '% Reducido',
   'src/Forms/inMtoIvas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoIvas.TfrmMtoIvas.cxGrdDBTabPrinPORCENREDUCIDO_RE_IVA.Caption',
   'es-ES',
   '%RE Reducido',
   'src/Forms/inMtoIvas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoIvas.TfrmMtoIvas.cxGrdDBTabPrinPORCENSUPERREDUCIDO_IVA.Caption',
   'es-ES',
   '%SúperReducido',
   'src/Forms/inMtoIvas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoIvas.TfrmMtoIvas.cxGrdDBTabPrinPORCENSUPERREDUCIDO_RE_IVA.Caption',
   'es-ES',
   '%RE SuperReducido',
   'src/Forms/inMtoIvas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoIvas.TfrmMtoIvas.cxGrdDBTabPrinPORCENEXENTO_IVA.Caption',
   'es-ES',
   '%Exento',
   'src/Forms/inMtoIvas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoIvas.TfrmMtoIvas.cxGrdDBTabPrinPORCENEXENTO_RE_IVA.Caption',
   'es-ES',
   '%RE Exento',
   'src/Forms/inMtoIvas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoIvas.TfrmMtoIvas.cxGrdDBTabPrinFECHA_DESDE_IVA.Caption',
   'es-ES',
   'Validez Desde',
   'src/Forms/inMtoIvas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoIvas.TfrmMtoIvas.cxGrdDBTabPrinFECHA_HASTA_IVA.Caption',
   'es-ES',
   'Validez Hasta',
   'src/Forms/inMtoIvas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoIvas.TfrmMtoIvas.cxGrdDBTabPrinPALABRA_REPORTS_ZONA_IVA.Caption',
   'es-ES',
   'Palabra IVA',
   'src/Forms/inMtoIvas.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoIvasGrupos.TfrmMtoIvasGrupos.Caption',
   'es-ES',
   'IVA',
   'src/Forms/inMtoIvasGrupos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoIvasGrupos.TfrmMtoIvasGrupos.cxGrdDBTabPrinGRUPO_ZONA_IVA.Caption',
   'es-ES',
   'Código Zona',
   'src/Forms/inMtoIvasGrupos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoIvasGrupos.TfrmMtoIvasGrupos.cxGrdDBTabPrinDESCRIPCION_ZONA_IVA.C',
     'aption'
   ),
   'es-ES',
   'Descripción Zona',
   'src/Forms/inMtoIvasGrupos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoIvasGrupos.TfrmMtoIvasGrupos.cxGrdDBTabPrinESIVAAGRICOLA_ZONA_IVA',
     '.Caption'
   ),
   'es-ES',
   'REAGP',
   'src/Forms/inMtoIvasGrupos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoIvasGrupos.TfrmMtoIvasGrupos.cxGrdDBTabPrinESAPLICA_RE_ZONA_IVA.C',
     'aption'
   ),
   'es-ES',
   'Aplica RE',
   'src/Forms/inMtoIvasGrupos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  ('inMtoIvasGrupos.TfrmMtoIvasGrupos.cxGrdDBTabPrinESDEFAULT_ZONA_IVA.Caption',
   'es-ES',
   'Zona por Defecto',
   'src/Forms/inMtoIvasGrupos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoIvasGrupos.TfrmMtoIvasGrupos.cxGrdDBTabPrinPALABRA_REPORTS_ZONA_I',
     'VA.Caption'
   ),
   'es-ES',
   'Palabra IVA',
   'src/Forms/inMtoIvasGrupos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema'),
  (CONCAT(
     'inMtoIvasGrupos.TfrmMtoIvasGrupos.cxGrdDBTabPrinESIRPF_IMP_INCL_ZONA_I',
     'VA.Caption'
   ),
   'es-ES',
   'IRPF Imp Incl',
   'src/Forms/inMtoIvasGrupos.dfm',
   'S', CURRENT_TIMESTAMP, 'Sistema')
ON DUPLICATE KEY UPDATE
  `TEXTO_TRAD` = VALUES(`TEXTO_TRAD`),
  `CONTEXTO_TRAD` = VALUES(`CONTEXTO_TRAD`),
  `ESACTIVO_TRAD` = VALUES(`ESACTIVO_TRAD`),
  `INSTANTE_MODIF` = CURRENT_TIMESTAMP,
  `USUARIO_MODIF` = VALUES(`USUARIO_ALTA`);
