-- D24: textos dinámicos del inspector de parámetros de caja.
-- El formulario crea estas categorías y descripciones en ejecución.
INSERT INTO `fza_traducciones` (
  `CLAVE_TRAD`, `IDIOMA_TRAD`, `TEXTO_TRAD`, `CONTEXTO_TRAD`,
  `ESACTIVO_TRAD`, `INSTANTE_ALTA`, `USUARIO_ALTA`
) VALUES
  ('inMtoCajaParam.Parametros.Categoria.ControldeArticulos',
   'es-ES', 'Control de Artículos',
   'src/Caja/Forms/inMtoCajaParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoCajaParam.Parametros.Categoria.ControldeArticulos',
   'ca-ES', 'Control d''articles',
   'src/Caja/Forms/inMtoCajaParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoCajaParam.Parametros.Categoria.ControldeArticulos',
   'en-GB', 'Article Control',
   'src/Caja/Forms/inMtoCajaParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoCajaParam.Parametros.Categoria.ConfiguraciondeCaja',
   'es-ES', 'Configuración de Caja',
   'src/Caja/Forms/inMtoCajaParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoCajaParam.Parametros.Categoria.ConfiguraciondeCaja',
   'ca-ES', 'Configuració de caixa',
   'src/Caja/Forms/inMtoCajaParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoCajaParam.Parametros.Categoria.ConfiguraciondeCaja',
   'en-GB', 'Register Configuration',
   'src/Caja/Forms/inMtoCajaParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoCajaParam.Parametros.Categoria.Serviciosweb',
   'es-ES', 'Servicios web',
   'src/Caja/Forms/inMtoCajaParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoCajaParam.Parametros.Categoria.Serviciosweb',
   'ca-ES', 'Serveis web',
   'src/Caja/Forms/inMtoCajaParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoCajaParam.Parametros.Categoria.Serviciosweb',
   'en-GB', 'Web Services',
   'src/Caja/Forms/inMtoCajaParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoCajaParam.Parametros.Categoria.DevolucionesyVales',
   'es-ES', 'Devoluciones y Vales',
   'src/Caja/Forms/inMtoCajaParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoCajaParam.Parametros.Categoria.DevolucionesyVales',
   'ca-ES', 'Devolucions i vals',
   'src/Caja/Forms/inMtoCajaParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoCajaParam.Parametros.Categoria.DevolucionesyVales',
   'en-GB', 'Returns and Vouchers',
   'src/Caja/Forms/inMtoCajaParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoCajaParam.Parametros.Categoria.AvisosyBusquedas',
   'es-ES', 'Avisos y Búsquedas',
   'src/Caja/Forms/inMtoCajaParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoCajaParam.Parametros.Categoria.AvisosyBusquedas',
   'ca-ES', 'Avisos i cerques',
   'src/Caja/Forms/inMtoCajaParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoCajaParam.Parametros.Categoria.AvisosyBusquedas',
   'en-GB', 'Alerts and Searches',
   'src/Caja/Forms/inMtoCajaParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoCajaParam.Parametros.Categoria.LectordeCodigodeBarras',
   'es-ES', 'Lector de Código de Barras',
   'src/Caja/Forms/inMtoCajaParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoCajaParam.Parametros.Categoria.LectordeCodigodeBarras',
   'ca-ES', 'Lector de codi de barres',
   'src/Caja/Forms/inMtoCajaParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoCajaParam.Parametros.Categoria.LectordeCodigodeBarras',
   'en-GB', 'Barcode Reader',
   'src/Caja/Forms/inMtoCajaParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoCajaParam.Parametros.Categoria.Impresion',
   'es-ES', 'Impresión',
   'src/Caja/Forms/inMtoCajaParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoCajaParam.Parametros.Categoria.Impresion',
   'ca-ES', 'Impressió',
   'src/Caja/Forms/inMtoCajaParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoCajaParam.Parametros.Categoria.Impresion',
   'en-GB', 'Printing',
   'src/Caja/Forms/inMtoCajaParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoCajaParam.Parametros.Categoria.Empleado',
   'es-ES', 'Empleado',
   'src/Caja/Forms/inMtoCajaParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoCajaParam.Parametros.Categoria.Empleado',
   'ca-ES', 'Empleat',
   'src/Caja/Forms/inMtoCajaParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoCajaParam.Parametros.Categoria.Empleado',
   'en-GB', 'Employee',
   'src/Caja/Forms/inMtoCajaParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoCajaParam.Parametros.Categoria.PermisosExtra',
   'es-ES', 'Permisos Extra',
   'src/Caja/Forms/inMtoCajaParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoCajaParam.Parametros.Categoria.PermisosExtra',
   'ca-ES', 'Permisos addicionals',
   'src/Caja/Forms/inMtoCajaParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoCajaParam.Parametros.Categoria.PermisosExtra',
   'en-GB', 'Extra Permissions',
   'src/Caja/Forms/inMtoCajaParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoCajaParam.Parametros.Categoria.Arqueo',
   'es-ES', 'Arqueo',
   'src/Caja/Forms/inMtoCajaParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoCajaParam.Parametros.Categoria.Arqueo',
   'ca-ES', 'Arqueig',
   'src/Caja/Forms/inMtoCajaParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoCajaParam.Parametros.Categoria.Arqueo',
   'en-GB', 'Cash Count',
   'src/Caja/Forms/inMtoCajaParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoCajaParam.Parametros.vgerChkExistOnly.Descripcion',
   'es-ES', 'Permitir sólo artículos que existan',
   'src/Caja/Forms/inMtoCajaParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoCajaParam.Parametros.vgerChkExistOnly.Descripcion',
   'ca-ES', 'Permetre només articles que existeixin',
   'src/Caja/Forms/inMtoCajaParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoCajaParam.Parametros.vgerChkExistOnly.Descripcion',
   'en-GB', 'Allow only existing items',
   'src/Caja/Forms/inMtoCajaParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoCajaParam.Parametros.vgerChkStockOnly.Descripcion',
   'es-ES', 'Permitir sólo artículos con stock',
   'src/Caja/Forms/inMtoCajaParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoCajaParam.Parametros.vgerChkStockOnly.Descripcion',
   'ca-ES', 'Permetre només articles amb estoc',
   'src/Caja/Forms/inMtoCajaParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoCajaParam.Parametros.vgerChkStockOnly.Descripcion',
   'en-GB', 'Allow only items in stock',
   'src/Caja/Forms/inMtoCajaParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoCajaParam.Parametros.vgerShowCajaSelection.Descripcion',
   'es-ES', 'Presentar selección de caja',
   'src/Caja/Forms/inMtoCajaParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoCajaParam.Parametros.vgerShowCajaSelection.Descripcion',
   'ca-ES', 'Presentar la selecció de caixa',
   'src/Caja/Forms/inMtoCajaParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoCajaParam.Parametros.vgerShowCajaSelection.Descripcion',
   'en-GB', 'Show register selection',
   'src/Caja/Forms/inMtoCajaParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoCajaParam.Parametros.vgerFillEmpleadoDefecto.Descripcion',
   'es-ES', 'Rellenar empleado por defecto al abrir',
   'src/Caja/Forms/inMtoCajaParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoCajaParam.Parametros.vgerFillEmpleadoDefecto.Descripcion',
   'ca-ES', 'Emplenar l''empleat per defecte en obrir',
   'src/Caja/Forms/inMtoCajaParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoCajaParam.Parametros.vgerFillEmpleadoDefecto.Descripcion',
   'en-GB', 'Fill the default employee on opening',
   'src/Caja/Forms/inMtoCajaParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoCajaParam.Parametros.vgerDefTarifa.Descripcion',
   'es-ES', 'Tarifa por defecto en caja',
   'src/Caja/Forms/inMtoCajaParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoCajaParam.Parametros.vgerDefTarifa.Descripcion',
   'ca-ES', 'Tarifa per defecte a caixa',
   'src/Caja/Forms/inMtoCajaParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoCajaParam.Parametros.vgerDefTarifa.Descripcion',
   'en-GB', 'Default price list at the register',
   'src/Caja/Forms/inMtoCajaParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoCajaParam.Parametros.vgerMaxOpPending.Descripcion',
   'es-ES', 'Número de operaciones pendientes',
   'src/Caja/Forms/inMtoCajaParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoCajaParam.Parametros.vgerMaxOpPending.Descripcion',
   'ca-ES', 'Nombre d''operacions pendents',
   'src/Caja/Forms/inMtoCajaParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoCajaParam.Parametros.vgerMaxOpPending.Descripcion',
   'en-GB', 'Number of pending operations',
   'src/Caja/Forms/inMtoCajaParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoCajaParam.Parametros.vgerAutoLoadDepositos.Descripcion',
   'es-ES',
   'Cargar depósitos automáticamente al seleccionar cliente',
   'src/Caja/Forms/inMtoCajaParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoCajaParam.Parametros.vgerAutoLoadDepositos.Descripcion',
   'ca-ES',
   'Carregar els dipòsits automàticament en seleccionar el client',
   'src/Caja/Forms/inMtoCajaParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoCajaParam.Parametros.vgerAutoLoadDepositos.Descripcion',
   'en-GB',
   'Load deposits automatically when selecting a customer',
   'src/Caja/Forms/inMtoCajaParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoCajaParam.Parametros.vgerAgruparUnidadesIguales.Descripcion',
   'es-ES', 'Agrupar unidades iguales en una sola línea',
   'src/Caja/Forms/inMtoCajaParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoCajaParam.Parametros.vgerAgruparUnidadesIguales.Descripcion',
   'ca-ES', 'Agrupar unitats iguals en una sola línia',
   'src/Caja/Forms/inMtoCajaParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoCajaParam.Parametros.vgerAgruparUnidadesIguales.Descripcion',
   'en-GB', 'Group identical units on one line',
   'src/Caja/Forms/inMtoCajaParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoCajaParam.Parametros.vgerEnviarVentasWS.Descripcion',
   'es-ES',
   'Enviar ventas completas al webservice de respaldo',
   'src/Caja/Forms/inMtoCajaParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoCajaParam.Parametros.vgerEnviarVentasWS.Descripcion',
   'ca-ES',
   'Enviar les vendes completes al servei web de còpia de seguretat',
   'src/Caja/Forms/inMtoCajaParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoCajaParam.Parametros.vgerEnviarVentasWS.Descripcion',
   'en-GB',
   'Send complete sales to the backup web service',
   'src/Caja/Forms/inMtoCajaParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoCajaParam.Parametros.vgerReqRefDevolucion.Descripcion',
   'es-ES', 'Pedir referencia en devoluciones',
   'src/Caja/Forms/inMtoCajaParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoCajaParam.Parametros.vgerReqRefDevolucion.Descripcion',
   'ca-ES', 'Demanar referència en les devolucions',
   'src/Caja/Forms/inMtoCajaParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoCajaParam.Parametros.vgerReqRefDevolucion.Descripcion',
   'en-GB', 'Request a reference for returns',
   'src/Caja/Forms/inMtoCajaParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoCajaParam.Parametros.vgerRecuperaValePIN.Descripcion',
   'es-ES', 'Recuperar Vale sólo con PIN',
   'src/Caja/Forms/inMtoCajaParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoCajaParam.Parametros.vgerRecuperaValePIN.Descripcion',
   'ca-ES', 'Recuperar el val només amb PIN',
   'src/Caja/Forms/inMtoCajaParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoCajaParam.Parametros.vgerRecuperaValePIN.Descripcion',
   'en-GB', 'Retrieve a voucher only with a PIN',
   'src/Caja/Forms/inMtoCajaParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoCajaParam.Parametros.vgerCaducidadDefVale.Descripcion',
   'es-ES', 'Caducidad por defecto en vale',
   'src/Caja/Forms/inMtoCajaParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoCajaParam.Parametros.vgerCaducidadDefVale.Descripcion',
   'ca-ES', 'Caducitat per defecte del val',
   'src/Caja/Forms/inMtoCajaParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoCajaParam.Parametros.vgerCaducidadDefVale.Descripcion',
   'en-GB', 'Default voucher expiry',
   'src/Caja/Forms/inMtoCajaParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoCajaParam.Parametros.vgerDiasCaducidadVale.Descripcion',
   'es-ES', 'Días hasta caducidad en vale',
   'src/Caja/Forms/inMtoCajaParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoCajaParam.Parametros.vgerDiasCaducidadVale.Descripcion',
   'ca-ES', 'Dies fins a la caducitat del val',
   'src/Caja/Forms/inMtoCajaParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoCajaParam.Parametros.vgerDiasCaducidadVale.Descripcion',
   'en-GB', 'Days until the voucher expires',
   'src/Caja/Forms/inMtoCajaParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoCajaParam.Parametros.vgerAvisoStockWarning.Descripcion',
   'es-ES', 'Aviso en artículos sin stock',
   'src/Caja/Forms/inMtoCajaParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoCajaParam.Parametros.vgerAvisoStockWarning.Descripcion',
   'ca-ES', 'Avís en articles sense estoc',
   'src/Caja/Forms/inMtoCajaParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoCajaParam.Parametros.vgerAvisoStockWarning.Descripcion',
   'en-GB', 'Out-of-stock item warning',
   'src/Caja/Forms/inMtoCajaParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoCajaParam.Parametros.vgerBusqArtStockOnly.Descripcion',
   'es-ES', 'Búsqueda de artículos sólo con stock',
   'src/Caja/Forms/inMtoCajaParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoCajaParam.Parametros.vgerBusqArtStockOnly.Descripcion',
   'ca-ES', 'Cerca d''articles només amb estoc',
   'src/Caja/Forms/inMtoCajaParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoCajaParam.Parametros.vgerBusqArtStockOnly.Descripcion',
   'en-GB', 'Search only items in stock',
   'src/Caja/Forms/inMtoCajaParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoCajaParam.Parametros.vgerBusqArtTarifaOnly.Descripcion',
   'es-ES', 'Búsqueda de artículos sólo con tarifa',
   'src/Caja/Forms/inMtoCajaParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoCajaParam.Parametros.vgerBusqArtTarifaOnly.Descripcion',
   'ca-ES', 'Cerca d''articles només amb tarifa',
   'src/Caja/Forms/inMtoCajaParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoCajaParam.Parametros.vgerBusqArtTarifaOnly.Descripcion',
   'en-GB', 'Search only items with a price list',
   'src/Caja/Forms/inMtoCajaParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoCajaParam.Parametros.vgerStockTodosColores.Descripcion',
   'es-ES',
   'Mostrar todos los colores por separado en el stock',
   'src/Caja/Forms/inMtoCajaParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoCajaParam.Parametros.vgerStockTodosColores.Descripcion',
   'ca-ES',
   'Mostrar tots els colors per separat a l''estoc',
   'src/Caja/Forms/inMtoCajaParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoCajaParam.Parametros.vgerStockTodosColores.Descripcion',
   'en-GB',
   'Show all colours separately in stock',
   'src/Caja/Forms/inMtoCajaParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoCajaParam.Parametros.vgerMoverLineaIdentif.Descripcion',
   'es-ES', 'Mover linea al identificar artículo',
   'src/Caja/Forms/inMtoCajaParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoCajaParam.Parametros.vgerMoverLineaIdentif.Descripcion',
   'ca-ES', 'Moure la línia en identificar l''article',
   'src/Caja/Forms/inMtoCajaParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoCajaParam.Parametros.vgerMoverLineaIdentif.Descripcion',
   'en-GB', 'Move the line when identifying an item',
   'src/Caja/Forms/inMtoCajaParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoCajaParam.Parametros.vgerScanVelActivo.Descripcion',
   'es-ES',
   'Detectar lecturas por velocidad de tecleo (código + CR)',
   'src/Caja/Forms/inMtoCajaParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoCajaParam.Parametros.vgerScanVelActivo.Descripcion',
   'ca-ES',
   'Detectar lectures per velocitat de tecleig (codi + CR)',
   'src/Caja/Forms/inMtoCajaParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoCajaParam.Parametros.vgerScanVelActivo.Descripcion',
   'en-GB',
   'Detect scans by typing speed (code + CR)',
   'src/Caja/Forms/inMtoCajaParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoCajaParam.Parametros.vgerScanVelMs.Descripcion',
   'es-ES',
   'Máx. ms entre teclas para considerarlo lectura',
   'src/Caja/Forms/inMtoCajaParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoCajaParam.Parametros.vgerScanVelMs.Descripcion',
   'ca-ES',
   'Màx. ms entre tecles per considerar-ho una lectura',
   'src/Caja/Forms/inMtoCajaParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoCajaParam.Parametros.vgerScanVelMs.Descripcion',
   'en-GB',
   'Max. ms between keys to treat it as a scan',
   'src/Caja/Forms/inMtoCajaParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoCajaParam.Parametros.vgerScanMinLong.Descripcion',
   'es-ES',
   'Longitud mínima del código para aceptar la lectura',
   'src/Caja/Forms/inMtoCajaParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoCajaParam.Parametros.vgerScanMinLong.Descripcion',
   'ca-ES',
   'Longitud mínima del codi per acceptar la lectura',
   'src/Caja/Forms/inMtoCajaParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoCajaParam.Parametros.vgerScanMinLong.Descripcion',
   'en-GB',
   'Minimum code length to accept the scan',
   'src/Caja/Forms/inMtoCajaParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoCajaParam.Parametros.vgerDefPrinter.Descripcion',
   'es-ES', 'Nombre impresora de tickets',
   'src/Caja/Forms/inMtoCajaParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoCajaParam.Parametros.vgerDefPrinter.Descripcion',
   'ca-ES', 'Nom de la impressora de tiquets',
   'src/Caja/Forms/inMtoCajaParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoCajaParam.Parametros.vgerDefPrinter.Descripcion',
   'en-GB', 'Receipt printer name',
   'src/Caja/Forms/inMtoCajaParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoCajaParam.Parametros.vgerTipoImpresion.Descripcion',
   'es-ES', 'Tipo de Impresión tickets',
   'src/Caja/Forms/inMtoCajaParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoCajaParam.Parametros.vgerTipoImpresion.Descripcion',
   'ca-ES', 'Tipus d''impressió de tiquets',
   'src/Caja/Forms/inMtoCajaParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoCajaParam.Parametros.vgerTipoImpresion.Descripcion',
   'en-GB', 'Receipt printing type',
   'src/Caja/Forms/inMtoCajaParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoCajaParam.Parametros.vgerFormatoImpPredet.Descripcion',
   'es-ES', 'Formato de impresión predeterminado',
   'src/Caja/Forms/inMtoCajaParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoCajaParam.Parametros.vgerFormatoImpPredet.Descripcion',
   'ca-ES', 'Format d''impressió predeterminat',
   'src/Caja/Forms/inMtoCajaParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoCajaParam.Parametros.vgerFormatoImpPredet.Descripcion',
   'en-GB', 'Default print format',
   'src/Caja/Forms/inMtoCajaParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoCajaParam.Parametros.vgerImprimirCodBarrasTicket.Descripcion',
   'es-ES', 'Imprimir código de barras EAN13 del ticket',
   'src/Caja/Forms/inMtoCajaParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoCajaParam.Parametros.vgerImprimirCodBarrasTicket.Descripcion',
   'ca-ES', 'Imprimir el codi de barres EAN13 del tiquet',
   'src/Caja/Forms/inMtoCajaParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoCajaParam.Parametros.vgerImprimirCodBarrasTicket.Descripcion',
   'en-GB', 'Print the receipt EAN13 barcode',
   'src/Caja/Forms/inMtoCajaParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoCajaParam.Parametros.vgerCodEmpleadoDefecto.Descripcion',
   'es-ES', 'Código de empleado por defecto',
   'src/Caja/Forms/inMtoCajaParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoCajaParam.Parametros.vgerCodEmpleadoDefecto.Descripcion',
   'ca-ES', 'Codi d''empleat per defecte',
   'src/Caja/Forms/inMtoCajaParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoCajaParam.Parametros.vgerCodEmpleadoDefecto.Descripcion',
   'en-GB', 'Default employee code',
   'src/Caja/Forms/inMtoCajaParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoCajaParam.Parametros.vgerShowEmpleadoLinea.Descripcion',
   'es-ES', 'Mostrar empleado en linea de caja',
   'src/Caja/Forms/inMtoCajaParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoCajaParam.Parametros.vgerShowEmpleadoLinea.Descripcion',
   'ca-ES', 'Mostrar l''empleat a la línia de caixa',
   'src/Caja/Forms/inMtoCajaParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoCajaParam.Parametros.vgerShowEmpleadoLinea.Descripcion',
   'en-GB', 'Show the employee on the register line',
   'src/Caja/Forms/inMtoCajaParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoCajaParam.Parametros.vgerArqueoTarjetas.Descripcion',
   'es-ES', 'Permitir Arqueo de Tarjetas',
   'src/Caja/Forms/inMtoCajaParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoCajaParam.Parametros.vgerArqueoTarjetas.Descripcion',
   'ca-ES', 'Permetre l''arqueig de targetes',
   'src/Caja/Forms/inMtoCajaParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoCajaParam.Parametros.vgerArqueoTarjetas.Descripcion',
   'en-GB', 'Allow card reconciliation',
   'src/Caja/Forms/inMtoCajaParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoCajaParam.Parametros.vgerVentasCredito.Descripcion',
   'es-ES', 'Permitir Ventas a Crédito',
   'src/Caja/Forms/inMtoCajaParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoCajaParam.Parametros.vgerVentasCredito.Descripcion',
   'ca-ES', 'Permetre vendes a crèdit',
   'src/Caja/Forms/inMtoCajaParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoCajaParam.Parametros.vgerVentasCredito.Descripcion',
   'en-GB', 'Allow credit sales',
   'src/Caja/Forms/inMtoCajaParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoCajaParam.Parametros.vgerDescuentos.Descripcion',
   'es-ES', 'Permite descuentos en ventas',
   'src/Caja/Forms/inMtoCajaParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoCajaParam.Parametros.vgerDescuentos.Descripcion',
   'ca-ES', 'Permetre descomptes en vendes',
   'src/Caja/Forms/inMtoCajaParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoCajaParam.Parametros.vgerDescuentos.Descripcion',
   'en-GB', 'Allow sales discounts',
   'src/Caja/Forms/inMtoCajaParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoCajaParam.Parametros.vgerArqueoNivelesFamilia.Descripcion',
   'es-ES',
   'Niveles de familia en resumen por sección (1=sección)',
   'src/Caja/Forms/inMtoCajaParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoCajaParam.Parametros.vgerArqueoNivelesFamilia.Descripcion',
   'ca-ES',
   'Nivells de família al resum per secció (1=secció)',
   'src/Caja/Forms/inMtoCajaParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24'),
  ('inMtoCajaParam.Parametros.vgerArqueoNivelesFamilia.Descripcion',
   'en-GB',
   'Family levels in the summary by section (1=section)',
   'src/Caja/Forms/inMtoCajaParam.pas',
   'S', CURRENT_TIMESTAMP, 'D24')
ON DUPLICATE KEY UPDATE
  `TEXTO_TRAD` = VALUES(`TEXTO_TRAD`),
  `CONTEXTO_TRAD` = VALUES(`CONTEXTO_TRAD`),
  `ESACTIVO_TRAD` = VALUES(`ESACTIVO_TRAD`),
  `INSTANTE_MODIF` = CURRENT_TIMESTAMP,
  `USUARIO_MODIF` = VALUES(`USUARIO_ALTA`);
-- Verifica que las 41 claves dinámicas tienen los tres idiomas.
SELECT COUNT(*) AS `PENDIENTES_PARAMETROS_CAJA`
  FROM (
    SELECT `CLAVE_TRAD`
      FROM `fza_traducciones`
     WHERE `CLAVE_TRAD` LIKE 'inMtoCajaParam.Parametros.%'
       AND `IDIOMA_TRAD` IN ('es-ES', 'ca-ES', 'en-GB')
       AND `ESACTIVO_TRAD` = 'S'
     GROUP BY `CLAVE_TRAD`
    HAVING COUNT(DISTINCT `IDIOMA_TRAD`) <> 3
  ) AS `PENDIENTES`;
