-- Cola de eventos de ventas hacia el webservice de Factuzam.
-- Sufijo confirmado: VWSC.
-- Estados: PENDIENTE, PROCESANDO, ENVIADA y ERROR.
SET @sExisteTabla := (
  SELECT COUNT(*)
    FROM INFORMATION_SCHEMA.TABLES
   WHERE TABLE_SCHEMA = DATABASE()
     AND TABLE_NAME = 'fza_ventas_ws_cola'
);
SET @sSql := IF(@sExisteTabla = 0,
  'CREATE TABLE fza_ventas_ws_cola (
     ID_VWSC bigint(20) NOT NULL AUTO_INCREMENT,
     ID_EVENTO_VWSC char(36) NOT NULL,
     CODIGO_EMP_VWSC varchar(20) NOT NULL,
     SERIE_FAC_VWSC varchar(20) NOT NULL,
     NUMERO_FAC_VWSC varchar(20) NOT NULL,
     TIPO_EVENTO_VWSC varchar(30) NOT NULL,
     VERSION_CONTRATO_VWSC int(11) NOT NULL DEFAULT 1,
     ESTADO_VWSC varchar(20) NOT NULL DEFAULT ''PENDIENTE'',
     CONTADOR_INTENTOS_VWSC int(11) NOT NULL DEFAULT 0,
     INSTANTE_PROXIMO_INTENTO_VWSC datetime NULL DEFAULT NULL,
     INSTANTE_ENVIO_VWSC datetime NULL DEFAULT NULL,
     ID_PETICION_VWSC varchar(64) NULL DEFAULT NULL,
     CONTENIDO_JSON_VWSC longtext NULL DEFAULT NULL,
     HUELLA_CONTENIDO_VWSC char(64) NULL DEFAULT NULL,
     NOMBRE_PDF_VWSC varchar(255) NULL DEFAULT NULL,
     TICKET_PDF_VWSC longblob NULL DEFAULT NULL,
     TAMANO_PDF_VWSC bigint(20) NULL DEFAULT NULL,
     HUELLA_PDF_VWSC char(64) NULL DEFAULT NULL,
     NOMBRE_FACTURA_PDF_VWSC varchar(255) NULL DEFAULT NULL,
     FACTURA_PDF_VWSC longblob NULL DEFAULT NULL,
     TAMANO_FACTURA_PDF_VWSC bigint(20) NULL DEFAULT NULL,
     HUELLA_FACTURA_PDF_VWSC char(64) NULL DEFAULT NULL,
     MENSAJE_ERROR_VWSC text NULL DEFAULT NULL,
     INSTANTE_ALTA datetime NOT NULL,
     USUARIO_ALTA varchar(50) NULL DEFAULT NULL,
     INSTANTE_MODIF datetime NULL DEFAULT NULL,
     USUARIO_MODIF varchar(50) NULL DEFAULT NULL,
     PRIMARY KEY (ID_VWSC)
   ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
     COLLATE=utf8mb4_spanish_ci',
  'SELECT ''fza_ventas_ws_cola ya existe, se omite'' AS info'
);
PREPARE stmt FROM @sSql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;
SET @sExisteColumna := (
  SELECT COUNT(*)
    FROM INFORMATION_SCHEMA.COLUMNS
   WHERE TABLE_SCHEMA = DATABASE()
     AND TABLE_NAME = 'fza_ventas_ws_cola'
     AND COLUMN_NAME = 'NOMBRE_PDF_VWSC'
);
SET @sSql := IF(@sExisteColumna = 0,
  'ALTER TABLE fza_ventas_ws_cola
     ADD COLUMN NOMBRE_PDF_VWSC varchar(255) NULL DEFAULT NULL
     AFTER HUELLA_CONTENIDO_VWSC',
  'SELECT ''NOMBRE_PDF_VWSC ya existe, se omite'' AS info'
);
PREPARE stmt FROM @sSql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;
SET @sExisteColumna := (
  SELECT COUNT(*)
    FROM INFORMATION_SCHEMA.COLUMNS
   WHERE TABLE_SCHEMA = DATABASE()
     AND TABLE_NAME = 'fza_ventas_ws_cola'
     AND COLUMN_NAME = 'TICKET_PDF_VWSC'
);
SET @sSql := IF(@sExisteColumna = 0,
  'ALTER TABLE fza_ventas_ws_cola
     ADD COLUMN TICKET_PDF_VWSC longblob NULL DEFAULT NULL
     AFTER NOMBRE_PDF_VWSC',
  'SELECT ''TICKET_PDF_VWSC ya existe, se omite'' AS info'
);
PREPARE stmt FROM @sSql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;
SET @sExisteColumna := (
  SELECT COUNT(*)
    FROM INFORMATION_SCHEMA.COLUMNS
   WHERE TABLE_SCHEMA = DATABASE()
     AND TABLE_NAME = 'fza_ventas_ws_cola'
     AND COLUMN_NAME = 'TAMANO_PDF_VWSC'
);
SET @sSql := IF(@sExisteColumna = 0,
  'ALTER TABLE fza_ventas_ws_cola
     ADD COLUMN TAMANO_PDF_VWSC bigint(20) NULL DEFAULT NULL
     AFTER TICKET_PDF_VWSC',
  'SELECT ''TAMANO_PDF_VWSC ya existe, se omite'' AS info'
);
PREPARE stmt FROM @sSql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;
SET @sExisteColumna := (
  SELECT COUNT(*)
    FROM INFORMATION_SCHEMA.COLUMNS
   WHERE TABLE_SCHEMA = DATABASE()
     AND TABLE_NAME = 'fza_ventas_ws_cola'
     AND COLUMN_NAME = 'HUELLA_PDF_VWSC'
);
SET @sSql := IF(@sExisteColumna = 0,
  'ALTER TABLE fza_ventas_ws_cola
     ADD COLUMN HUELLA_PDF_VWSC char(64) NULL DEFAULT NULL
     AFTER TAMANO_PDF_VWSC',
  'SELECT ''HUELLA_PDF_VWSC ya existe, se omite'' AS info'
);
PREPARE stmt FROM @sSql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;
SET @sExisteColumna := (
  SELECT COUNT(*)
    FROM INFORMATION_SCHEMA.COLUMNS
   WHERE TABLE_SCHEMA = DATABASE()
     AND TABLE_NAME = 'fza_ventas_ws_cola'
     AND COLUMN_NAME = 'NOMBRE_FACTURA_PDF_VWSC'
);
SET @sSql := IF(@sExisteColumna = 0,
  'ALTER TABLE fza_ventas_ws_cola
     ADD COLUMN NOMBRE_FACTURA_PDF_VWSC varchar(255) NULL DEFAULT NULL
     AFTER HUELLA_PDF_VWSC',
  'SELECT ''NOMBRE_FACTURA_PDF_VWSC ya existe, se omite'' AS info'
);
PREPARE stmt FROM @sSql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;
SET @sExisteColumna := (
  SELECT COUNT(*)
    FROM INFORMATION_SCHEMA.COLUMNS
   WHERE TABLE_SCHEMA = DATABASE()
     AND TABLE_NAME = 'fza_ventas_ws_cola'
     AND COLUMN_NAME = 'FACTURA_PDF_VWSC'
);
SET @sSql := IF(@sExisteColumna = 0,
  'ALTER TABLE fza_ventas_ws_cola
     ADD COLUMN FACTURA_PDF_VWSC longblob NULL DEFAULT NULL
     AFTER NOMBRE_FACTURA_PDF_VWSC',
  'SELECT ''FACTURA_PDF_VWSC ya existe, se omite'' AS info'
);
PREPARE stmt FROM @sSql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;
SET @sExisteColumna := (
  SELECT COUNT(*)
    FROM INFORMATION_SCHEMA.COLUMNS
   WHERE TABLE_SCHEMA = DATABASE()
     AND TABLE_NAME = 'fza_ventas_ws_cola'
     AND COLUMN_NAME = 'TAMANO_FACTURA_PDF_VWSC'
);
SET @sSql := IF(@sExisteColumna = 0,
  'ALTER TABLE fza_ventas_ws_cola
     ADD COLUMN TAMANO_FACTURA_PDF_VWSC bigint(20) NULL DEFAULT NULL
     AFTER FACTURA_PDF_VWSC',
  'SELECT ''TAMANO_FACTURA_PDF_VWSC ya existe, se omite'' AS info'
);
PREPARE stmt FROM @sSql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;
SET @sExisteColumna := (
  SELECT COUNT(*)
    FROM INFORMATION_SCHEMA.COLUMNS
   WHERE TABLE_SCHEMA = DATABASE()
     AND TABLE_NAME = 'fza_ventas_ws_cola'
     AND COLUMN_NAME = 'HUELLA_FACTURA_PDF_VWSC'
);
SET @sSql := IF(@sExisteColumna = 0,
  'ALTER TABLE fza_ventas_ws_cola
     ADD COLUMN HUELLA_FACTURA_PDF_VWSC char(64) NULL DEFAULT NULL
     AFTER TAMANO_FACTURA_PDF_VWSC',
  'SELECT ''HUELLA_FACTURA_PDF_VWSC ya existe, se omite'' AS info'
);
PREPARE stmt FROM @sSql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;
SET @sExisteIdx := (
  SELECT COUNT(*)
    FROM INFORMATION_SCHEMA.STATISTICS
   WHERE TABLE_SCHEMA = DATABASE()
     AND TABLE_NAME = 'fza_ventas_ws_cola'
     AND INDEX_NAME = 'UQ_VWSC_EVENTO'
);
SET @sSql := IF(@sExisteIdx = 0,
  'ALTER TABLE fza_ventas_ws_cola
     ADD UNIQUE INDEX UQ_VWSC_EVENTO (ID_EVENTO_VWSC)',
  'SELECT ''UQ_VWSC_EVENTO ya existe, se omite'' AS info'
);
PREPARE stmt FROM @sSql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;
SET @sExisteIdx := (
  SELECT COUNT(*)
    FROM INFORMATION_SCHEMA.STATISTICS
   WHERE TABLE_SCHEMA = DATABASE()
     AND TABLE_NAME = 'fza_ventas_ws_cola'
     AND INDEX_NAME = 'IDX_VWSC_ESTADO_PROXIMO'
);
SET @sSql := IF(@sExisteIdx = 0,
  'ALTER TABLE fza_ventas_ws_cola
     ADD INDEX IDX_VWSC_ESTADO_PROXIMO
       (ESTADO_VWSC, INSTANTE_PROXIMO_INTENTO_VWSC)',
  'SELECT ''IDX_VWSC_ESTADO_PROXIMO ya existe, se omite'' AS info'
);
PREPARE stmt FROM @sSql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;
SET @sExisteIdx := (
  SELECT COUNT(*)
    FROM INFORMATION_SCHEMA.STATISTICS
   WHERE TABLE_SCHEMA = DATABASE()
     AND TABLE_NAME = 'fza_ventas_ws_cola'
     AND INDEX_NAME = 'IDX_VWSC_DOCUMENTO'
);
SET @sSql := IF(@sExisteIdx = 0,
  'ALTER TABLE fza_ventas_ws_cola
     ADD INDEX IDX_VWSC_DOCUMENTO
       (CODIGO_EMP_VWSC, SERIE_FAC_VWSC, NUMERO_FAC_VWSC)',
  'SELECT ''IDX_VWSC_DOCUMENTO ya existe, se omite'' AS info'
);
PREPARE stmt FROM @sSql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;
