USE `factuzam`;
DELIMITER $$
DROP PROCEDURE IF EXISTS `PRC_UPDATE_VERSION_FROM_1.0.0.20231204.alpha` $$
CREATE PROCEDURE `PRC_UPDATE_VERSION_FROM_1.0.0.20231204.alpha` ()
BEGIN
  START TRANSACTION;

  -- Actualizo versión en la bbdd 
  REPLACE INTO           `fza_usuarios_perfiles` (`USUARIO_GRUPO_PERFILES`, 
                                                  `KEY_PERFILES`, 
												  `SUBKEY_PERFILES`, 
												  `VALUE_PERFILES`, 
												  `VALUE_TEXT_PERFILES`, 
												  `TYPE_BLOB_PERFILES`, 
												  `VALUE_BLOB_PERFILES`, 
												  `INSTANTEMODIF`, 
												  `INSTANTEALTA`, 
												  `USUARIOALTA`, 
												  `USUARIOMODIF`) 
										  VALUES ('Todos', 
										          'frmLogon', 
												  'DataBaseVersion', 
												  '1.0.0.20231204.alpha', 
												  NULL, 
												  NULL, 
												  NULL, 
												  '2023-12-01 19:54:58', 
												  '2023-12-01 19:54:49', 
												  'Administrador', 
												  'Administrador');
												  
  -- Modificación de la tabla fza_winforms con una nueva columna y datos con los módulos de datos.
  DROP VIEW IF EXISTS vi_fac_busquedas ;

  CREATE VIEW vi_fac_busquedas AS 

	SELECT
		`fza_facturas`.`FECHA_FACTURA` AS `FECHA_FACTURA`,
		`fza_facturas`.`NRO_FACTURA` AS `NRO_FACTURA`,
		`fza_facturas`.`SERIE_FACTURA` AS `SERIE_FACTURA`,
		`fza_facturas`.`TOTAL_LIQUIDO_FACTURA` AS `TOTAL_LIQUIDO_FACTURA`,
		`fza_facturas`.`PORCEN_RETENCION_FACTURA` AS `PORCEN_RETENCION_FACTURA`,
		`fza_facturas`.`TOTAL_RETENCION_FACTURA` AS `TOTAL_RETENCION_FACTURA`,
		`fza_facturas`.`TOTAL_IMPUESTOS_FACTURA` AS `TOTAL_IMPUESTOS_FACTURA`,
		`fza_facturas`.`TOTAL_BASES_FACTURA` AS `TOTAL_BASES_FACTURA`,
		`fza_facturas`.`FORMA_PAGO_FACTURA` AS `FORMA_PAGO_FACTURA`,
		fza_formapago.DESCRIPCION_FORMAPAGO AS DESCRIPCION_FORMAPAGO,
		`fza_facturas`.`CODIGO_EMPRESA_FACTURA` AS `CODIGO_EMPRESA_FACTURA`,
		`fza_facturas`.`RAZONSOCIAL_EMPRESA_FACTURA` AS `RAZONSOCIAL_EMPRESA_FACTURA`,
		`fza_facturas`.`NIF_EMPRESA_FACTURA` AS `NIF_EMPRESA_FACTURA`,
		`fza_facturas`.`MOVIL_EMPRESA_FACTURA` AS `MOVIL_EMPRESA_FACTURA`,
		`fza_facturas`.`EMAIL_EMPRESA_FACTURA` AS `EMAIL_EMPRESA_FACTURA`,
		`fza_facturas`.`DIRECCION1_EMPRESA_FACTURA` AS `DIRECCION1_EMPRESA_FACTURA`,
		`fza_facturas`.`DIRECCION2_EMPRESA_FACTURA` AS `DIRECCION2_EMPRESA_FACTURA`,
		`fza_facturas`.`POBLACION_EMPRESA_FACTURA` AS `POBLACION_EMPRESA_FACTURA`,
		`fza_facturas`.`PROVINCIA_EMPRESA_FACTURA` AS `PROVINCIA_EMPRESA_FACTURA`,
		`fza_facturas`.`PAIS_EMPRESA_FACTURA` AS `PAIS_EMPRESA_FACTURA`,
		`fza_facturas`.`CPOSTAL_EMPRESA_FACTURA` AS `CPOSTAL_EMPRESA_FACTURA`,
		`fza_facturas`.`ESRETENCIONES_EMPRESA_FACTURA` AS `ESRETENCIONES_EMPRESA_FACTURA`,
		`fza_facturas`.`GRUPO_ZONA_IVA_EMPRESA_FACTURA` AS `GRUPO_ZONA_IVA_EMPRESA_FACTURA`,
		`fza_facturas`.`ESREGIMENESPECIALAGRICOLA_EMPRESA_FACTURA` AS `ESREGIMENESPECIALAGRICOLA_EMPRESA_FACTURA`,
		`fza_facturas`.`CODIGO_CLIENTE_FACTURA` AS `CODIGO_CLIENTE_FACTURA`,
		`fza_facturas`.`RAZONSOCIAL_CLIENTE_FACTURA` AS `RAZONSOCIAL_CLIENTE_FACTURA`,
		`fza_facturas`.`NIF_CLIENTE_FACTURA` AS `NIF_CLIENTE_FACTURA`,
		`fza_facturas`.`MOVIL_CLIENTE_FACTURA` AS `MOVIL_CLIENTE_FACTURA`,
		`fza_facturas`.`EMAIL_CLIENTE_FACTURA` AS `EMAIL_CLIENTE_FACTURA`,
		`fza_facturas`.`DIRECCION1_CLIENTE_FACTURA` AS `DIRECCION1_CLIENTE_FACTURA`,
		`fza_facturas`.`DIRECCION2_CLIENTE_FACTURA` AS `DIRECCION2_CLIENTE_FACTURA`,
		`fza_facturas`.`POBLACION_CLIENTE_FACTURA` AS `POBLACION_CLIENTE_FACTURA`,
		`fza_facturas`.`PROVINCIA_CLIENTE_FACTURA` AS `PROVINCIA_CLIENTE_FACTURA`,
		`fza_facturas`.`CPOSTAL_CLIENTE_FACTURA` AS `CPOSTAL_CLIENTE_FACTURA`,
		`fza_facturas`.`PAIS_CLIENTE_FACTURA` AS `PAIS_CLIENTE_FACTURA`,
		`fza_facturas`.`ESIVA_RECARGO_CLIENTE_FACTURA` AS `ESIVA_RECARGO_CLIENTE_FACTURA`,
		`fza_facturas`.`ESIVA_EXENTO_CLIENTE_FACTURA` AS `ESIVA_EXENTO_CLIENTE_FACTURA`,
		`fza_facturas`.`ESREGIMENESPECIALAGRICOLA_CLIENTE_FACTURA` AS `ESREGIMENESPECIALAGRICOLA_CLIENTE_FACTURA`,
		`fza_facturas`.`ESRETENCIONES_CLIENTE_FACTURA` AS `ESRETENCIONES_CLIENTE_FACTURA`,
		`fza_facturas`.`TARIFA_ARTICULO_CLIENTE_FACTURA` AS `TARIFA_ARTICULO_CLIENTE_FACTURA`,
		`fza_facturas`.`ESIMP_INCL_TARIFA_CLIENTE_FACTURA` AS `ESIMP_INCL_TARIFA_CLIENTE_FACTURA`,
		`fza_facturas`.`ESINTRACOMUNITARIO_CLIENTE_FACTURA` AS `ESINTRACOMUNITARIO_CLIENTE_FACTURA`,
		`fza_facturas`.`ESIRPF_IMP_INCL_ZONA_IVA_FACTURA` AS `ESIRPF_IMP_INCL_ZONA_IVA_FACTURA`,
		`fza_facturas`.`ESAPLICA_RE_ZONA_IVA_FACTURA` AS `ESAPLICA_RE_ZONA_IVA_FACTURA`,
		`fza_facturas`.`ESIVAAGRICOLA_ZONA_IVA_FACTURA` AS `ESIVAAGRICOLA_ZONA_IVA_FACTURA`,
		`fza_facturas`.`PALABRA_REPORTS_ZONA_IVA_FACTURA` AS `PALABRA_REPORTS_ZONA_IVA_FACTURA`,
		`fza_facturas`.`CODIGO_IVA_FACTURA` AS `CODIGO_IVA_FACTURA`,
		`fza_facturas`.`ESVENTA_ACTIVO_FIJO_FACTURA` AS `ESVENTA_ACTIVO_FIJO_FACTURA`,
		`fza_facturas`.`PORCEN_IVAN_FACTURA` AS `PORCEN_IVAN_FACTURA`,
		`fza_facturas`.`TOTAL_IVAN_FACTURA` AS `TOTAL_IVAN_FACTURA`,
		`fza_facturas`.`PORCEN_REN_FACTURA` AS `PORCEN_REN_FACTURA`,
		`fza_facturas`.`TOTAL_REN_FACTURA` AS `TOTAL_REN_FACTURA`,
		`fza_facturas`.`TOTAL_BASEI_IVAN_FACTURA` AS `TOTAL_BASEI_IVAN_FACTURA`,
		`fza_facturas`.`PORCEN_IVAR_FACTURA` AS `PORCEN_IVAR_FACTURA`,
		`fza_facturas`.`TOTAL_IVAR_FACTURA` AS `TOTAL_IVAR_FACTURA`,
		`fza_facturas`.`PORCEN_RER_FACTURA` AS `PORCEN_RER_FACTURA`,
		`fza_facturas`.`TOTAL_RER_FACTURA` AS `TOTAL_RER_FACTURA`,
		`fza_facturas`.`TOTAL_BASEI_IVAR_FACTURA` AS `TOTAL_BASEI_IVAR_FACTURA`,
		`fza_facturas`.`PORCEN_IVAS_FACTURA` AS `PORCEN_IVAS_FACTURA`,
		`fza_facturas`.`TOTAL_IVAS_FACTURA` AS `TOTAL_IVAS_FACTURA`,
		`fza_facturas`.`PORCEN_RES_FACTURA` AS `PORCEN_RES_FACTURA`,
		`fza_facturas`.`TOTAL_RES_FACTURA` AS `TOTAL_RES_FACTURA`,
		`fza_facturas`.`TOTAL_BASEI_IVAS_FACTURA` AS `TOTAL_BASEI_IVAS_FACTURA`,
		`fza_facturas`.`PORCEN_IVAE_FACTURA` AS `PORCEN_IVAE_FACTURA`,
		`fza_facturas`.`TOTAL_IVAE_FACTURA` AS `TOTAL_IVAE_FACTURA`,
		`fza_facturas`.`PORCEN_REE_FACTURA` AS `PORCEN_REE_FACTURA`,
		`fza_facturas`.`TOTAL_REE_FACTURA` AS `TOTAL_REE_FACTURA`,
		`fza_facturas`.`TOTAL_BASEI_IVAE_FACTURA` AS `TOTAL_BASEI_IVAE_FACTURA` 
	FROM
		`fza_facturas`
	LEFT JOIN fza_formapago ON fza_facturas.FORMA_PAGO_FACTURA = fza_formapago.CODIGO_FORMAPAGO;
  COMMIT;
END; $$
DELIMITER ;

CALL `PRC_UPDATE_VERSION_FROM_1.0.0.20231204.alpha`;
DROP PROCEDURE `PRC_UPDATE_VERSION_FROM_1.0.0.20231204.alpha`;