- compras 
en varios tipos de iva, alclarar que es para artículos y 
meter en proveedores que sea exento (extranjero). 

descuentos financieros (sólo a nivel económico)

descuento comercial (imputar descuento artículos)

-> EN SESIONES SI METO CANTIDADES NO SALE BIEN, SÓLO SALE CUANDO CAMBIO DE LINEA

LOS PROVEEDORES TIENEN QUE TENER SISTEMA DE TALLAS POR DEFECTO Y APLICAR EN SESIONES POR DEFECTO 

EN SESIONES, SI CAMBIO EL SISTEMA DE TALLAS DE UNA LINEA, LAS SIGUIENTES ME SALE POR DEFECTO CON 
EL QUE YO METÍ.

METER EN SESIONES Y  PEDIDOS FECHA TOPE DE RECEPCIÓN

QUE EN LA LINEA DE SESIÓN, SALGA POR DEFECTO EN MODELO Y NO EN ARTÍCULO

QUE EN LAS ETIQUETAS SALGA NOMBRE DE PROVEEDOR Y NO LA RAZÓN SOCIAL

BÚSQUEDA INCREMENTAL POR CÓDIGO DE PROVEEDOR EN COMBO EN VEZ DE BUTTÓN

CUANDO RELLENO MODELO NO ME RELLENA BIEN CODIGO, DESCRIPCIÓN Y TALLAJE, PRECIOS Y CANTIDADES

LA BÚSQUEDA INCREMENTAL DE MODELO NO FUNCIONA BIEN. 

SI EN EL MISMO DOCUMENTO, METO EL MISMO MODELO O CÓDIGO DE ARTÍCULO, 
ARBOL DE FAMILIAS F3 LO LLAME EN MODO NO-EDICIÓN

QUE EN LOS TALLAJES BUSQUE POR SISTEMA Y NO POR CÓDIGO


EN SESIONES CREAR ARTICULOS Y DOCUMENTOS Y NO ALBARANES, PORQUE ESTÁ EN CREAR ARTICULOS Y ALBARANES

NUMERO DE PRENDAS EN TOTALES


EN EL GRID DE SESIONES-PEDIDOS-ALBARANES0 QUIERES QUE SALGA LA TEMPORADA, LAS FECHAS
EL TOTAL PRENDAS Y EL TOTAL IMPORTE NETO LINEAS Y TOTAL DOCUMENTO, 
CANTIDADES PEDIDAS - CANTIDADES RECIBIDAS EN PEDIDOS. 
EN CABECERAS DE PEDIDOS PEDIDO/RECIBID/PTE/ALBARÁN. 

ETIQUETAS POR PEDIDO

GUARDAR FILTROS EN LISTA

EN LA BÚSQUEDA DE CONTROL U NO SALE POR MODELO