param(
  [string]$Raiz = (Resolve-Path (Join-Path $PSScriptRoot '..\..')).Path,
  [ValidateRange(0, 45)]
  [int]$MaximoFanOutUi = 45,
  [ValidateRange(0, 47)]
  [int]$MaximoFanOutComposicion = 47,
  [switch]$MostrarTodos
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$codigos = @{
  MainForm = 'ARQ01_MAINFORM'
  DmConn = 'ARQ02_DMCONN'
  DataModuleUi = 'ARQ03_DM_CREATE_UI'
  UniDacContrato = 'ARQ04_UNIDAC_CONTRATO'
  EstadoGlobal = 'ARQ05_ESTADO_GLOBAL'
  FanOutUi = 'ARQ06_FANOUT_UI'
  FanOutRaiz = 'ARQ06_FANOUT_RAIZ'
  ContextoNoUsado = 'ARQ07_CONTEXTO_NO_USADO'
}

function Quitar-ContenidoNoEjecutable {
  param([string]$Contenido)
  $resultado = [regex]::Replace(
    $Contenido,
    "'(?:''|[^'])*'",
    {
      param($coincidencia)
      return [regex]::Replace($coincidencia.Value, '[^\r\n]', ' ')
    })
  $resultado = [regex]::Replace(
    $resultado,
    '(?s)\{.*?\}|\(\*.*?\*\)',
    {
      param($coincidencia)
      return [regex]::Replace($coincidencia.Value, '[^\r\n]', ' ')
    })
  return [regex]::Replace(
    $resultado,
    '(?m)//[^\r\n]*',
    {
      param($coincidencia)
      return ' ' * $coincidencia.Value.Length
    })
}

function Obtener-Linea {
  param(
    [string]$Contenido,
    [int]$Indice
  )
  return ([regex]::Matches(
    $Contenido.Substring(0, $Indice),
    "`n")).Count + 1
}

function Obtener-ArchivosProyecto {
  param([string]$RutaRaiz)
  $proyecto = Join-Path $RutaRaiz 'fzam.dpr'
  if (Test-Path -LiteralPath $proyecto -PathType Leaf) {
    $contenido = Get-Content -LiteralPath $proyecto -Raw
    $rutas = foreach ($coincidencia in [regex]::Matches(
      $contenido,
      "(?is)\b[A-Za-z_][A-Za-z0-9_.]*\s+in\s+'([^']+\.pas)'")) {
      $ruta = Join-Path $RutaRaiz $coincidencia.Groups[1].Value
      if (Test-Path -LiteralPath $ruta -PathType Leaf) {
        (Resolve-Path -LiteralPath $ruta).Path
      }
    }
    return @(
      $rutas |
        Sort-Object -Unique |
        ForEach-Object { Get-Item -LiteralPath $_ }
    )
  }
  return @(
    Get-ChildItem -LiteralPath (Join-Path $RutaRaiz 'src') `
      -Filter '*.pas' -File -Recurse
  )
}

function Obtener-Clasificacion {
  param(
    [string]$RutaRelativa,
    [string]$Contenido
  )
  $ruta = $RutaRelativa.Replace('/', '\')
  $terceros = @(
    'src\3rdpartyComp\',
    'src\Lib3par\',
    'src\Lib\sqlformatter\',
    'src\vcl\',
    'src\vcl37\'
  )
  foreach ($prefijo in $terceros) {
    if ($ruta.StartsWith(
      $prefijo,
      [System.StringComparison]::OrdinalIgnoreCase)) {
      return 'Tercero'
    }
  }
  if ($ruta -match '(?i)\\third_party\\') {
    return 'Tercero'
  }
  $nombre = [System.IO.Path]::GetFileName($ruta)
  if (($nombre -match '(?i)\.(?:g|designer|generated)\.pas$') -or
      ($Contenido -match '(?i)<auto-generated|archivo generado|do not edit')) {
    return 'Generado'
  }
  return 'Propio'
}

function Obtener-NombreUnidad {
  param([string]$ContenidoLimpio)
  $coincidencia = [regex]::Match(
    $ContenidoLimpio,
    '(?im)^\s*unit\s+([A-Za-z_][A-Za-z0-9_.]*)\s*;')
  if ($coincidencia.Success) {
    return $coincidencia.Groups[1].Value
  }
  return ''
}

function Es-RaizComposicion {
  param(
    [string]$Unidad,
    [string]$RutaRelativa
  )
  if ($Unidad -match '(?i)(?:InyeccionRaiz|ComposicionRaiz)$') {
    return $true
  }
  if ($Unidad -match '(?i)^UniData.*(?:Composicion|Inyeccion)') {
    return $true
  }
  return $RutaRelativa -match
    '(?i)\\DataModules\\UniData.*(?:Composicion|Inyeccion).*\.pas$'
}

function Es-UnidadUi {
  param(
    [string]$RutaRelativa,
    [string]$Unidad,
    [bool]$EsComposicion
  )
  if ($EsComposicion) {
    return $false
  }
  $ruta = $RutaRelativa.Replace('/', '\')
  if ($ruta -match
      '(?i)^src\\(?:Core|Forms|Modals|Caja\\Forms|Caja\\Modals)\\') {
    return $true
  }
  return ($ruta -match '(?i)^src\\verifactu\\') -and
    ($Unidad -match '(?i)^inMto')
}

function Obtener-Dependencias {
  param([string]$ContenidoLimpio)
  $dependencias = [System.Collections.Generic.HashSet[string]]::new(
    [System.StringComparer]::OrdinalIgnoreCase)
  foreach ($bloque in [regex]::Matches(
    $ContenidoLimpio,
    '(?is)\buses\b(?<cuerpo>.*?);')) {
    foreach ($coincidencia in [regex]::Matches(
      $bloque.Groups['cuerpo'].Value,
      '\b[A-Za-z_][A-Za-z0-9_.]*\b')) {
      if ($coincidencia.Value -ine 'in') {
        [void]$dependencias.Add($coincidencia.Value)
      }
    }
  }
  Write-Output -NoEnumerate $dependencias
}

function Obtener-Interfaz {
  param([string]$ContenidoLimpio)
  $inicio = [regex]::Match(
    $ContenidoLimpio,
    '(?im)^\s*interface\b')
  $fin = [regex]::Match(
    $ContenidoLimpio,
    '(?im)^\s*implementation\b')
  if ((-not $inicio.Success) -or
      (-not $fin.Success) -or
      ($fin.Index -le $inicio.Index)) {
    return ''
  }
  $desde = $inicio.Index + $inicio.Length
  return $ContenidoLimpio.Substring($desde, $fin.Index - $desde)
}

function Agregar-Infraccion {
  param(
    [System.Collections.Generic.List[object]]$Lista,
    [string]$Codigo,
    [string]$Ruta,
    [int]$Linea,
    [string]$Detalle
  )
  $Lista.Add([pscustomobject]@{
    Codigo = $Codigo
    Detalle = $Detalle
    Linea = $Linea
    Ruta = $Ruta
  })
}

$rutaSrc = Join-Path $Raiz 'src'
if (-not (Test-Path -LiteralPath $rutaSrc -PathType Container)) {
  throw "No existe el directorio de fuentes: $rutaSrc."
}

$unidades = [System.Collections.Generic.List[object]]::new()
foreach ($archivo in (Obtener-ArchivosProyecto -RutaRaiz $Raiz)) {
  $relativa = [System.IO.Path]::GetRelativePath($Raiz, $archivo.FullName)
  $contenido = Get-Content -LiteralPath $archivo.FullName -Raw
  $limpio = Quitar-ContenidoNoEjecutable -Contenido $contenido
  $nombre = Obtener-NombreUnidad -ContenidoLimpio $limpio
  $clasificacion = Obtener-Clasificacion `
    -RutaRelativa $relativa `
    -Contenido $contenido
  $composicion = Es-RaizComposicion `
    -Unidad $nombre `
    -RutaRelativa $relativa
  $unidades.Add([pscustomobject]@{
    Archivo = $archivo
    Clasificacion = $clasificacion
    Composicion = $composicion
    Contenido = $contenido
    Dependencias = Obtener-Dependencias -ContenidoLimpio $limpio
    FanOut = 0
    Interfaz = Obtener-Interfaz -ContenidoLimpio $limpio
    Limpio = $limpio
    Nombre = $nombre
    Relativa = $relativa
    Ui = Es-UnidadUi `
      -RutaRelativa $relativa `
      -Unidad $nombre `
      -EsComposicion $composicion
  })
}

$propias = @($unidades | Where-Object { $_.Clasificacion -eq 'Propio' })
$nombresPropios = [System.Collections.Generic.HashSet[string]]::new(
  [System.StringComparer]::OrdinalIgnoreCase)
foreach ($unidad in $propias) {
  [void]$nombresPropios.Add($unidad.Nombre)
}
foreach ($unidad in $propias) {
  $fanOut = 0
  foreach ($dependencia in $unidad.Dependencias) {
    if ($nombresPropios.Contains($dependencia)) {
      $fanOut++
    }
  }
  $unidad.FanOut = $fanOut
}
$infracciones = [System.Collections.Generic.List[object]]::new()

foreach ($unidad in $propias) {
  $patronMainForm =
    '(?is)\bSupports\s*\(\s*Application\s*\.\s*MainForm\b|' +
    '\b(?:Exigir|Resolver|Obtener)[A-Za-z0-9_]*\s*\(\s*' +
    'Application\s*\.\s*MainForm\b'
  foreach ($coincidencia in [regex]::Matches(
    $unidad.Limpio,
    $patronMainForm)) {
    Agregar-Infraccion `
      -Lista $infracciones `
      -Codigo $codigos.MainForm `
      -Ruta $unidad.Relativa `
      -Linea (Obtener-Linea $unidad.Limpio $coincidencia.Index) `
      -Detalle 'Dependencia resuelta desde Application.MainForm.'
  }
  if (-not $unidad.Composicion) {
    foreach ($coincidencia in [regex]::Matches(
      $unidad.Limpio,
      '(?i)\.\s*DmConn\b')) {
      Agregar-Infraccion `
        -Lista $infracciones `
        -Codigo $codigos.DmConn `
        -Ruta $unidad.Relativa `
        -Linea (Obtener-Linea $unidad.Limpio $coincidencia.Index) `
        -Detalle '.DmConn fuera de una raiz de composicion UniDAC.'
    }
  }
  if ($unidad.Ui) {
    foreach ($coincidencia in [regex]::Matches(
      $unidad.Limpio,
      '(?i)\bTdm[A-Za-z0-9_]*\s*\.\s*Create\s*\(')) {
      Agregar-Infraccion `
        -Lista $infracciones `
        -Codigo $codigos.DataModuleUi `
        -Ruta $unidad.Relativa `
        -Linea (Obtener-Linea $unidad.Limpio $coincidencia.Index) `
        -Detalle 'La UI crea directamente un data module.'
    }
  }
  $esAdaptador = ($unidad.Relativa -match '(?i)\\DataModules\\') -or
    ($unidad.Nombre -match '(?i)^UniData') -or
    ($unidad.Nombre -match '(?i)UniDAC') -or
    $unidad.Composicion
  if (-not $esAdaptador) {
    $patronUniDac =
      '\bTUni(?:Connection|Query|StoredProc|SQL|Table|Transaction)\b'
    foreach ($coincidencia in [regex]::Matches(
      $unidad.Interfaz,
      $patronUniDac,
      [System.Text.RegularExpressions.RegexOptions]::IgnoreCase)) {
      $indice = $unidad.Limpio.IndexOf($unidad.Interfaz) +
        $coincidencia.Index
      Agregar-Infraccion `
        -Lista $infracciones `
        -Codigo $codigos.UniDacContrato `
        -Ruta $unidad.Relativa `
        -Linea (Obtener-Linea $unidad.Limpio $indice) `
        -Detalle ('Tipo UniDAC expuesto por contrato: ' +
          $coincidencia.Value + '.')
    }
  }
  $inicio = [regex]::Match(
    $unidad.Limpio,
    '(?im)^\s*initialization\b')
  if ($inicio.Success) {
    $inicializacion = $unidad.Limpio.Substring($inicio.Index)
    $patronDeclaracion =
      '(?im)^\s*(?<nombre>[A-Za-z_][A-Za-z0-9_]*)\s*:\s*' +
      '(?<tipo>T(?:Object)?Dictionary\s*<[^;]+>)\s*;'
    foreach ($declaracion in [regex]::Matches(
      $unidad.Limpio.Substring(0, $inicio.Index),
      $patronDeclaracion)) {
      $nombreVariable = $declaracion.Groups['nombre'].Value
      $tipoVariable = $declaracion.Groups['tipo'].Value
      $esRegistro = ($nombreVariable + ' ' + $tipoVariable) -match
        '(?i)Fabrica|Factoria|Factor[ií]a|Factory|Registro|' +
        'Pantalla|DataModule'
      $seInicializa = $inicializacion -match
        ('(?i)\b' + [regex]::Escape($nombreVariable) + '\s*:=')
      if ($esRegistro -and $seInicializa) {
        Agregar-Infraccion `
          -Lista $infracciones `
          -Codigo $codigos.EstadoGlobal `
          -Ruta $unidad.Relativa `
          -Linea (Obtener-Linea `
            $unidad.Limpio `
            $declaracion.Index) `
          -Detalle ('Registro o fabrica global: ' + $nombreVariable + '.')
      }
    }
  }
  foreach ($coincidencia in [regex]::Matches(
    $unidad.Limpio,
    '(?is)\bclass\s+var\s+[^;]*(?:Fabrica|Factoria|Factory|Registro)[^;]*;')) {
    Agregar-Infraccion `
      -Lista $infracciones `
      -Codigo $codigos.EstadoGlobal `
      -Ruta $unidad.Relativa `
      -Linea (Obtener-Linea $unidad.Limpio $coincidencia.Index) `
      -Detalle 'Registro o fabrica almacenado en class var.'
  }
}

$unidadesUi = @($propias | Where-Object { $_.Ui })
$raices = @($propias | Where-Object { $_.Composicion })
foreach ($unidad in $unidadesUi) {
  if ($unidad.FanOut -gt $MaximoFanOutUi) {
    Agregar-Infraccion `
      -Lista $infracciones `
      -Codigo $codigos.FanOutUi `
      -Ruta $unidad.Relativa `
      -Linea 1 `
      -Detalle ("Fan-out UI $($unidad.FanOut); maximo $MaximoFanOutUi.")
  }
}
foreach ($unidad in $raices) {
  if ($unidad.FanOut -gt $MaximoFanOutComposicion) {
    Agregar-Infraccion `
      -Lista $infracciones `
      -Codigo $codigos.FanOutRaiz `
      -Ruta $unidad.Relativa `
      -Linea 1 `
      -Detalle ("Fan-out raiz $($unidad.FanOut); " +
        "maximo $MaximoFanOutComposicion.")
  }
}

$usosMiembro = [System.Collections.Generic.HashSet[string]]::new(
  [System.StringComparer]::OrdinalIgnoreCase)
$variablesPorContexto = @{}
foreach ($unidad in $propias) {
  foreach ($cadena in [regex]::Matches(
    $unidad.Limpio,
    '(?i)\b[A-Za-z_][A-Za-z0-9_]*' +
    '(?:\s*\.\s*[A-Za-z_][A-Za-z0-9_]*)+\b')) {
    $miembros = @([regex]::Matches(
      $cadena.Value,
      '[A-Za-z_][A-Za-z0-9_]*') | ForEach-Object { $_.Value })
    for ($indice = 0; $indice -lt ($miembros.Count - 1); $indice++) {
      [void]$usosMiembro.Add(
        $miembros[$indice] + '.' + $miembros[$indice + 1])
    }
  }
  $patronVariableContexto =
    '(?im)\b(?<nombres>[A-Za-z_][A-Za-z0-9_]*' +
    '(?:\s*,\s*[A-Za-z_][A-Za-z0-9_]*)*)\s*:\s*' +
    '(?<tipo>TContexto(?:Dependencias[A-Za-z0-9_]*|' +
    '[A-Za-z0-9_]*(?:Vcl|Pantalla)[A-Za-z0-9_]*))\b'
  foreach ($variable in [regex]::Matches(
    $unidad.Limpio,
    $patronVariableContexto)) {
    $tipo = $variable.Groups['tipo'].Value
    if (-not $variablesPorContexto.ContainsKey($tipo)) {
      $variablesPorContexto[$tipo] =
        [System.Collections.Generic.HashSet[string]]::new(
          [System.StringComparer]::OrdinalIgnoreCase)
    }
    foreach ($nombre in ($variable.Groups['nombres'].Value -split ',')) {
      [void]$variablesPorContexto[$tipo].Add($nombre.Trim())
    }
  }
}

$capacidadesEntregadas = 0
$capacidadesUsadas = 0
$contextosMedidos = 0
foreach ($unidad in $propias) {
  $patronContexto =
    '(?is)\b(?<tipo>TContexto(?:Dependencias[A-Za-z0-9_]*|' +
    '[A-Za-z0-9_]*(?:Vcl|Pantalla)[A-Za-z0-9_]*))\s*=\s*' +
    'record\b(?<cuerpo>.*?)\bend\s*;'
  foreach ($contexto in [regex]::Matches(
    $unidad.Limpio,
    $patronContexto)) {
    $tipoContexto = $contexto.Groups['tipo'].Value
    $cuerpo = $contexto.Groups['cuerpo'].Value
    $primerMetodo = [regex]::Match(
      $cuerpo,
      '(?im)^\s*(?:class\s+)?(?:procedure|function|constructor)\b')
    if ($primerMetodo.Success) {
      $cuerpoCampos = $cuerpo.Substring(0, $primerMetodo.Index)
    }
    else {
      $cuerpoCampos = $cuerpo
    }
    $campos = [System.Collections.Generic.List[object]]::new()
    foreach ($declaracion in [regex]::Matches(
      $cuerpoCampos,
      '(?im)^\s*(?<nombres>[A-Za-z_][A-Za-z0-9_]*' +
      '(?:\s*,\s*[A-Za-z_][A-Za-z0-9_]*)*)\s*:\s*[^;]+;')) {
      foreach ($nombreCampo in ($declaracion.Groups['nombres'].Value -split ',')) {
        $campos.Add([pscustomobject]@{
          Indice = $contexto.Groups['cuerpo'].Index + $declaracion.Index
          Nombre = $nombreCampo.Trim()
        })
      }
    }
    if ($campos.Count -gt 0) {
      $contextosMedidos++
    }
    $variables = @()
    if ($variablesPorContexto.ContainsKey($tipoContexto)) {
      $variables = @($variablesPorContexto[$tipoContexto])
    }
    foreach ($campo in $campos) {
      $capacidadesEntregadas++
      $usada = $false
      foreach ($nombreVariable in $variables) {
        if ($usosMiembro.Contains(
          $nombreVariable + '.' + $campo.Nombre)) {
          $usada = $true
          break
        }
      }
      if ($usada) {
        $capacidadesUsadas++
      }
      else {
        Agregar-Infraccion `
          -Lista $infracciones `
          -Codigo $codigos.ContextoNoUsado `
          -Ruta $unidad.Relativa `
          -Linea (Obtener-Linea $unidad.Limpio $campo.Indice) `
          -Detalle ("$tipoContexto.$($campo.Nombre) se entrega y no se usa.")
      }
    }
  }
}

$fanOutUiMayor = 0
if ($unidadesUi.Count -gt 0) {
  $fanOutUiMayor = ($unidadesUi |
    Measure-Object FanOut -Maximum).Maximum
}
$fanOutRaizMayor = 0
if ($raices.Count -gt 0) {
  $fanOutRaizMayor = ($raices |
    Measure-Object FanOut -Maximum).Maximum
}
$generadas = @($unidades | Where-Object { $_.Clasificacion -eq 'Generado' })
$terceras = @($unidades | Where-Object { $_.Clasificacion -eq 'Tercero' })

Write-Output (
  'Clasificacion: propios=' + $propias.Count +
  '; generados=' + $generadas.Count +
  '; terceros=' + $terceras.Count + '.')
Write-Output (
  "Fan-out UI: $fanOutUiMayor/$MaximoFanOutUi. " +
  "Fan-out composicion: $fanOutRaizMayor/$MaximoFanOutComposicion.")
Write-Output (
  'Contextos de pantalla: ' + $contextosMedidos +
  '; capacidades entregadas=' + $capacidadesEntregadas +
  '; usadas=' + $capacidadesUsadas +
  '; sin usar=' + ($capacidadesEntregadas - $capacidadesUsadas) + '.')

if ($infracciones.Count -gt 0) {
  Write-Output 'Infracciones de arquitectura S31:'
  $ordenadas = @($infracciones | Sort-Object Codigo, Ruta, Linea)
  if (-not $MostrarTodos -and ($ordenadas.Count -gt 80)) {
    $ordenadas = @($ordenadas | Select-Object -First 80)
  }
  foreach ($infraccion in $ordenadas) {
    Write-Output (
      "  [$($infraccion.Codigo)] $($infraccion.Ruta):" +
      "$($infraccion.Linea) $($infraccion.Detalle)")
  }
  if ($ordenadas.Count -lt $infracciones.Count) {
    Write-Output (
      '  ... ' + ($infracciones.Count - $ordenadas.Count) +
      ' infracciones adicionales; use -MostrarTodos.')
  }
  exit 1
}

Write-Output (
  'Arquitectura S31: OK. Sin localizadores MainForm, fugas DmConn, ' +
  'Tdm.Create en UI, tipos UniDAC en contratos, registros globales, ' +
  'excesos de fan-out ni capacidades de contexto sin uso.')
