SELECT NOW() AS ahora;
SELECT "=== cola ventas ws ===" AS x;
SELECT ID_VWSC, ESTADO_VWSC, SERIE_FAC_VWSC, NUMERO_FAC_VWSC, TIPO_EVENTO_VWSC,
       CONTADOR_INTENTOS_VWSC,
       DATE_FORMAT(INSTANTE_ALTA,"%H:%i:%s") AS alta,
       DATE_FORMAT(INSTANTE_ENVIO_VWSC,"%H:%i:%s") AS envio,
       LEFT(MENSAJE_ERROR_VWSC,80) AS err
  FROM fza_ventas_ws_cola ORDER BY ID_VWSC DESC LIMIT 5;
