-- Contazam 1.0.0
-- Esquema multiempresa idempotente para MariaDB.
-- No modifica ninguna tabla de Factuzam.

CREATE DATABASE IF NOT EXISTS alexcontazam
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_spanish_ci;
USE alexcontazam;

CREATE TABLE IF NOT EXISTS cza_empresas (
  CODIGO_EMP VARCHAR(10) NOT NULL,
  RAZON_SOCIAL_EMP VARCHAR(150) NOT NULL,
  NIF_EMP VARCHAR(20) NULL,
  ORDEN_EMP INT NOT NULL DEFAULT 0,
  ESACTIVO_EMP CHAR(1) NOT NULL DEFAULT 'S',
  CODIGO_EMP_FACTUZAM_EMP VARCHAR(10) NULL,
  BASE_DATOS_FACTUZAM_EMP VARCHAR(64) NULL,
  INSTANTE_ALTA DATETIME NOT NULL,
  USUARIO_ALTA VARCHAR(100) NOT NULL,
  INSTANTE_MODIF DATETIME NULL,
  USUARIO_MODIF VARCHAR(100) NULL,
  PRIMARY KEY (CODIGO_EMP),
  KEY IX_CZA_EMPRESAS_ACTIVAS (ESACTIVO_EMP, ORDEN_EMP)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS cza_ejercicios (
  CODIGO_EMP_EJE VARCHAR(10) NOT NULL,
  EJERCICIO_EJE SMALLINT NOT NULL,
  FECHA_INICIO_EJE DATE NOT NULL,
  FECHA_FIN_EJE DATE NOT NULL,
  ESTADO_EJE VARCHAR(15) NOT NULL DEFAULT 'ABIERTO',
  ESACTIVO_EJE CHAR(1) NOT NULL DEFAULT 'S',
  INSTANTE_ALTA DATETIME NOT NULL,
  USUARIO_ALTA VARCHAR(100) NOT NULL,
  INSTANTE_MODIF DATETIME NULL,
  USUARIO_MODIF VARCHAR(100) NULL,
  PRIMARY KEY (CODIGO_EMP_EJE, EJERCICIO_EJE),
  KEY IX_CZA_EJERCICIOS_ACTIVOS (
    CODIGO_EMP_EJE, ESACTIVO_EJE, EJERCICIO_EJE
  )
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS cza_cuentas_modelo (
  CODIGO_MOD VARCHAR(15) NOT NULL,
  CODIGO_PADRE_MOD VARCHAR(15) NULL,
  NOMBRE_MOD VARCHAR(150) NOT NULL,
  NIVEL_MOD TINYINT NOT NULL,
  TIPO_MOD VARCHAR(15) NOT NULL,
  NATURALEZA_MOD CHAR(1) NOT NULL,
  ESIMPUTABLE_MOD CHAR(1) NOT NULL DEFAULT 'N',
  ESACTIVO_MOD CHAR(1) NOT NULL DEFAULT 'S',
  ORDEN_MOD INT NOT NULL DEFAULT 0,
  INSTANTE_ALTA DATETIME NOT NULL,
  USUARIO_ALTA VARCHAR(100) NOT NULL,
  INSTANTE_MODIF DATETIME NULL,
  USUARIO_MODIF VARCHAR(100) NULL,
  PRIMARY KEY (CODIGO_MOD),
  KEY IX_CZA_CUENTAS_MODELO_PADRE (CODIGO_PADRE_MOD, ORDEN_MOD)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS cza_cuentas (
  CODIGO_EMP_CTA VARCHAR(10) NOT NULL,
  EJERCICIO_CTA SMALLINT NOT NULL,
  CODIGO_CTA VARCHAR(15) NOT NULL,
  CODIGO_CTA_PADRE_CTA VARCHAR(15) NULL,
  NOMBRE_CTA VARCHAR(150) NOT NULL,
  NIVEL_CTA TINYINT NOT NULL,
  TIPO_CTA VARCHAR(15) NOT NULL,
  NATURALEZA_CTA CHAR(1) NOT NULL,
  ESIMPUTABLE_CTA CHAR(1) NOT NULL DEFAULT 'N',
  ESACTIVO_CTA CHAR(1) NOT NULL DEFAULT 'S',
  ORDEN_CTA INT NOT NULL DEFAULT 0,
  INSTANTE_ALTA DATETIME NOT NULL,
  USUARIO_ALTA VARCHAR(100) NOT NULL,
  INSTANTE_MODIF DATETIME NULL,
  USUARIO_MODIF VARCHAR(100) NULL,
  PRIMARY KEY (CODIGO_EMP_CTA, EJERCICIO_CTA, CODIGO_CTA),
  KEY IX_CZA_CUENTAS_PADRE (
    CODIGO_EMP_CTA, EJERCICIO_CTA, CODIGO_CTA_PADRE_CTA
  ),
  KEY IX_CZA_CUENTAS_NOMBRE (
    CODIGO_EMP_CTA, EJERCICIO_CTA, NOMBRE_CTA
  )
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS cza_contadores (
  TIPO_DOCUMENTO_CON VARCHAR(30) NOT NULL,
  CODIGO_EMP_CON VARCHAR(10) NOT NULL,
  EJERCICIO_CON SMALLINT NOT NULL,
  SERIE_CON VARCHAR(20) NOT NULL DEFAULT '-',
  CONTADOR_CON VARCHAR(30) NOT NULL DEFAULT '0',
  NUMERO_CEROS_CON TINYINT
    GENERATED ALWAYS AS (
      CHAR_LENGTH(CONTADOR_CON) -
      CHAR_LENGTH(REPLACE(CONTADOR_CON, '0', ''))
    ) STORED,
  NUMERO_DIGITOS_CON TINYINT NOT NULL DEFAULT 8,
  ESACTIVO_CON CHAR(1) NOT NULL DEFAULT 'S',
  ESDEFECTO_CON CHAR(1) NOT NULL DEFAULT 'N',
  INSTANTE_ALTA DATETIME NOT NULL,
  USUARIO_ALTA VARCHAR(100) NOT NULL,
  INSTANTE_MODIF DATETIME NULL,
  USUARIO_MODIF VARCHAR(100) NULL,
  PRIMARY KEY (
    TIPO_DOCUMENTO_CON, CODIGO_EMP_CON, EJERCICIO_CON, SERIE_CON
  ),
  KEY IX_CZA_CONTADORES_DEFECTO (
    CODIGO_EMP_CON, EJERCICIO_CON, TIPO_DOCUMENTO_CON,
    ESACTIVO_CON, ESDEFECTO_CON
  )
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS cza_asientos (
  ID_ASI BIGINT NOT NULL,
  CODIGO_EMP_ASI VARCHAR(10) NOT NULL,
  EJERCICIO_ASI SMALLINT NOT NULL,
  NUMERO_ASI BIGINT NOT NULL,
  FECHA_ASI DATE NOT NULL,
  CONCEPTO_ASI VARCHAR(250) NOT NULL,
  ESTADO_ASI VARCHAR(15) NOT NULL DEFAULT 'BORRADOR',
  SISTEMA_ORIGEN_ASI VARCHAR(30) NULL,
  TIPO_DOCUMENTO_ORIGEN_ASI VARCHAR(30) NULL,
  CLAVE_DOCUMENTO_ORIGEN_ASI VARCHAR(150) NULL,
  INSTANTE_ALTA DATETIME NOT NULL,
  USUARIO_ALTA VARCHAR(100) NOT NULL,
  INSTANTE_MODIF DATETIME NULL,
  USUARIO_MODIF VARCHAR(100) NULL,
  PRIMARY KEY (ID_ASI),
  UNIQUE KEY UX_CZA_ASIENTOS_NUMERO (
    CODIGO_EMP_ASI, EJERCICIO_ASI, NUMERO_ASI
  ),
  KEY IX_CZA_ASIENTOS_FECHA (
    CODIGO_EMP_ASI, EJERCICIO_ASI, FECHA_ASI, NUMERO_ASI
  ),
  KEY IX_CZA_ASIENTOS_ORIGEN (
    SISTEMA_ORIGEN_ASI, TIPO_DOCUMENTO_ORIGEN_ASI,
    CLAVE_DOCUMENTO_ORIGEN_ASI
  )
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS cza_asientos_lineas (
  ID_ASILIN BIGINT NOT NULL,
  ID_ASI_ASILIN BIGINT NOT NULL,
  LINEA_ASILIN INT NOT NULL,
  CODIGO_CTA_ASILIN VARCHAR(15) NOT NULL,
  CONCEPTO_ASILIN VARCHAR(250) NULL,
  IMPORTE_DEBE_ASILIN DECIMAL(19,4) NOT NULL DEFAULT 0,
  IMPORTE_HABER_ASILIN DECIMAL(19,4) NOT NULL DEFAULT 0,
  DOCUMENTO_ASILIN VARCHAR(100) NULL,
  CODIGO_TERCERO_ASILIN VARCHAR(30) NULL,
  INSTANTE_ALTA DATETIME NOT NULL,
  USUARIO_ALTA VARCHAR(100) NOT NULL,
  INSTANTE_MODIF DATETIME NULL,
  USUARIO_MODIF VARCHAR(100) NULL,
  PRIMARY KEY (ID_ASILIN),
  UNIQUE KEY UX_CZA_ASIENTOS_LINEAS (ID_ASI_ASILIN, LINEA_ASILIN),
  KEY IX_CZA_ASIENTOS_LINEAS_CUENTA (
    CODIGO_CTA_ASILIN, ID_ASI_ASILIN
  )
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS cza_mapeos_contables (
  CODIGO_EMP_MAP VARCHAR(10) NOT NULL,
  EJERCICIO_MAP SMALLINT NOT NULL,
  ROL_MAP VARCHAR(30) NOT NULL,
  CODIGO_CTA_MAP VARCHAR(15) NOT NULL,
  ESACTIVO_MAP CHAR(1) NOT NULL DEFAULT 'S',
  INSTANTE_ALTA DATETIME NOT NULL,
  USUARIO_ALTA VARCHAR(100) NOT NULL,
  INSTANTE_MODIF DATETIME NULL,
  USUARIO_MODIF VARCHAR(100) NULL,
  PRIMARY KEY (CODIGO_EMP_MAP, EJERCICIO_MAP, ROL_MAP),
  KEY IX_CZA_MAPEOS_CUENTA (
    CODIGO_EMP_MAP, EJERCICIO_MAP, CODIGO_CTA_MAP
  )
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS cza_reglas_contrapartida (
  CODIGO_EMP_REG VARCHAR(10) NOT NULL,
  EJERCICIO_REG SMALLINT NOT NULL,
  PREFIJO_ORIGEN_REG VARCHAR(15) NOT NULL,
  PREFIJO_DESTINO_REG VARCHAR(15) NOT NULL,
  PRIORIDAD_REG SMALLINT NOT NULL DEFAULT 0,
  ESACTIVO_REG CHAR(1) NOT NULL DEFAULT 'S',
  INSTANTE_ALTA DATETIME NOT NULL,
  USUARIO_ALTA VARCHAR(100) NOT NULL,
  INSTANTE_MODIF DATETIME NULL,
  USUARIO_MODIF VARCHAR(100) NULL,
  PRIMARY KEY (
    CODIGO_EMP_REG, EJERCICIO_REG, PREFIJO_ORIGEN_REG,
    PREFIJO_DESTINO_REG
  ),
  KEY IX_CZA_REGLAS_ORIGEN (
    CODIGO_EMP_REG, EJERCICIO_REG, PREFIJO_ORIGEN_REG,
    ESACTIVO_REG
  )
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS cza_importaciones (
  ID_IMP BIGINT NOT NULL,
  CODIGO_EMP_DESTINO_IMP VARCHAR(10) NOT NULL,
  SISTEMA_ORIGEN_IMP VARCHAR(30) NOT NULL,
  BASE_DATOS_ORIGEN_IMP VARCHAR(64) NOT NULL,
  TIPO_DOCUMENTO_ORIGEN_IMP VARCHAR(30) NOT NULL,
  CLAVE_DOCUMENTO_ORIGEN_IMP VARCHAR(150) NOT NULL,
  ID_ASI_IMP BIGINT NOT NULL,
  ESTADO_IMP VARCHAR(30) NOT NULL,
  MENSAJE_IMP VARCHAR(500) NULL,
  INSTANTE_ALTA DATETIME NOT NULL,
  USUARIO_ALTA VARCHAR(100) NOT NULL,
  INSTANTE_MODIF DATETIME NULL,
  USUARIO_MODIF VARCHAR(100) NULL,
  PRIMARY KEY (ID_IMP),
  UNIQUE KEY UX_CZA_IMPORTACIONES_ORIGEN (
    CODIGO_EMP_DESTINO_IMP, SISTEMA_ORIGEN_IMP,
    BASE_DATOS_ORIGEN_IMP, TIPO_DOCUMENTO_ORIGEN_IMP,
    CLAVE_DOCUMENTO_ORIGEN_IMP
  ),
  KEY IX_CZA_IMPORTACIONES_ASIENTO (ID_ASI_IMP)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS cza_documentos (
  ID_DOC BIGINT NOT NULL,
  CODIGO_EMP_DOC VARCHAR(10) NOT NULL,
  EJERCICIO_DOC SMALLINT NOT NULL,
  REFERENCIA_DOC VARCHAR(100) NOT NULL,
  TIPO_DOC VARCHAR(30) NOT NULL DEFAULT 'OTRO',
  FECHA_DOC DATE NULL,
  DESCRIPCION_DOC VARCHAR(250) NULL,
  NOMBRE_ARCHIVO_DOC VARCHAR(255) NOT NULL,
  MIME_DOC VARCHAR(100) NOT NULL DEFAULT 'application/pdf',
  TAMANO_DOC BIGINT NOT NULL,
  SHA256_DOC CHAR(64) NOT NULL,
  CONTENIDO_PDF_DOC LONGBLOB NOT NULL,
  ORIGEN_DOC VARCHAR(30) NOT NULL DEFAULT 'MANUAL',
  INSTANTE_ALTA DATETIME NOT NULL,
  USUARIO_ALTA VARCHAR(100) NOT NULL,
  INSTANTE_MODIF DATETIME NULL,
  USUARIO_MODIF VARCHAR(100) NULL,
  PRIMARY KEY (ID_DOC),
  UNIQUE KEY UX_CZA_DOCUMENTOS_REFERENCIA (
    CODIGO_EMP_DOC, EJERCICIO_DOC, REFERENCIA_DOC
  ),
  KEY IX_CZA_DOCUMENTOS_FECHA (
    CODIGO_EMP_DOC, EJERCICIO_DOC, FECHA_DOC
  ),
  KEY IX_CZA_DOCUMENTOS_SHA256 (SHA256_DOC)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS cza_usuarios (
  CODIGO_USU VARCHAR(50) NOT NULL,
  NOMBRE_USU VARCHAR(150) NOT NULL,
  EMAIL_USU VARCHAR(150) NULL,
  ESACTIVO_USU CHAR(1) NOT NULL DEFAULT 'S',
  INSTANTE_ALTA DATETIME NOT NULL,
  USUARIO_ALTA VARCHAR(100) NOT NULL,
  INSTANTE_MODIF DATETIME NULL,
  USUARIO_MODIF VARCHAR(100) NULL,
  PRIMARY KEY (CODIGO_USU),
  KEY IX_CZA_USUARIOS_ACTIVOS (ESACTIVO_USU, NOMBRE_USU)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS cza_grupos (
  CODIGO_GRU VARCHAR(30) NOT NULL,
  NOMBRE_GRU VARCHAR(150) NOT NULL,
  ESACTIVO_GRU CHAR(1) NOT NULL DEFAULT 'S',
  INSTANTE_ALTA DATETIME NOT NULL,
  USUARIO_ALTA VARCHAR(100) NOT NULL,
  INSTANTE_MODIF DATETIME NULL,
  USUARIO_MODIF VARCHAR(100) NULL,
  PRIMARY KEY (CODIGO_GRU),
  KEY IX_CZA_GRUPOS_ACTIVOS (ESACTIVO_GRU, NOMBRE_GRU)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS cza_usuarios_grupos (
  CODIGO_USU_UGR VARCHAR(50) NOT NULL,
  CODIGO_GRU_UGR VARCHAR(30) NOT NULL,
  ESACTIVO_UGR CHAR(1) NOT NULL DEFAULT 'S',
  INSTANTE_ALTA DATETIME NOT NULL,
  USUARIO_ALTA VARCHAR(100) NOT NULL,
  INSTANTE_MODIF DATETIME NULL,
  USUARIO_MODIF VARCHAR(100) NULL,
  PRIMARY KEY (CODIGO_USU_UGR, CODIGO_GRU_UGR),
  KEY IX_CZA_USUARIOS_GRUPOS_GRUPO (
    CODIGO_GRU_UGR, ESACTIVO_UGR, CODIGO_USU_UGR
  )
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS cza_grupos_permisos (
  CODIGO_GRU_GPE VARCHAR(30) NOT NULL,
  RECURSO_GPE VARCHAR(50) NOT NULL,
  ACCION_GPE VARCHAR(30) NOT NULL,
  ALCANCE_GPE VARCHAR(15) NOT NULL DEFAULT 'GLOBAL',
  CODIGO_EMP_GPE VARCHAR(10) NOT NULL DEFAULT '*',
  ESACTIVO_GPE CHAR(1) NOT NULL DEFAULT 'S',
  INSTANTE_ALTA DATETIME NOT NULL,
  USUARIO_ALTA VARCHAR(100) NOT NULL,
  INSTANTE_MODIF DATETIME NULL,
  USUARIO_MODIF VARCHAR(100) NULL,
  PRIMARY KEY (
    CODIGO_GRU_GPE, RECURSO_GPE, ACCION_GPE,
    ALCANCE_GPE, CODIGO_EMP_GPE
  ),
  KEY IX_CZA_GRUPOS_PERMISOS_BUSQUEDA (
    RECURSO_GPE, ACCION_GPE, ESACTIVO_GPE,
    ALCANCE_GPE, CODIGO_EMP_GPE
  )
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS cza_auditoria_listados (
  ID_AUL BIGINT NOT NULL,
  CODIGO_USU_AUL VARCHAR(50) NOT NULL,
  CODIGO_GRU_AUL VARCHAR(30) NULL,
  RECURSO_AUL VARCHAR(50) NOT NULL,
  ACCION_AUL VARCHAR(30) NOT NULL,
  ALCANCE_AUL VARCHAR(15) NOT NULL,
  CODIGO_EMP_AUL VARCHAR(10) NOT NULL,
  EJERCICIO_AUL SMALLINT NOT NULL,
  FECHA_DESDE_AUL DATE NULL,
  FECHA_HASTA_AUL DATE NULL,
  FILTRO_CUENTA_AUL VARCHAR(15) NULL,
  NUMERO_REGISTROS_AUL INT NOT NULL DEFAULT 0,
  ARCHIVO_AUL VARCHAR(255) NULL,
  INSTANTE_ALTA DATETIME NOT NULL,
  USUARIO_ALTA VARCHAR(100) NOT NULL,
  INSTANTE_MODIF DATETIME NULL,
  USUARIO_MODIF VARCHAR(100) NULL,
  PRIMARY KEY (ID_AUL),
  KEY IX_CZA_AUDITORIA_LISTADOS_USUARIO (
    CODIGO_USU_AUL, INSTANTE_ALTA
  ),
  KEY IX_CZA_AUDITORIA_LISTADOS_CONTEXTO (
    CODIGO_EMP_AUL, EJERCICIO_AUL, RECURSO_AUL, INSTANTE_ALTA
  )
) ENGINE=InnoDB;

ALTER TABLE cza_asientos
  MODIFY ID_ASI BIGINT NOT NULL;
ALTER TABLE cza_asientos_lineas
  MODIFY ID_ASILIN BIGINT NOT NULL;
ALTER TABLE cza_importaciones
  MODIFY ID_IMP BIGINT NOT NULL;
ALTER TABLE cza_contadores
  MODIFY CONTADOR_CON VARCHAR(30) NOT NULL DEFAULT '0';
ALTER TABLE cza_contadores
  ADD COLUMN IF NOT EXISTS NUMERO_CEROS_CON TINYINT
    GENERATED ALWAYS AS (
      CHAR_LENGTH(CONTADOR_CON) -
      CHAR_LENGTH(REPLACE(CONTADOR_CON, '0', ''))
    ) STORED AFTER CONTADOR_CON;

CREATE OR REPLACE VIEW VI_CZA_LIBRO_DIARIO AS
SELECT A.CODIGO_EMP_ASI AS CODIGO_EMP_DIA,
       A.EJERCICIO_ASI AS EJERCICIO_DIA,
       A.NUMERO_ASI AS NUMERO_ASI_DIA,
       A.FECHA_ASI AS FECHA_DIA,
       L.LINEA_ASILIN AS LINEA_ASILIN_DIA,
       L.CODIGO_CTA_ASILIN AS CODIGO_CTA_DIA,
       C.NOMBRE_CTA AS NOMBRE_CTA_DIA,
       COALESCE(L.CONCEPTO_ASILIN, A.CONCEPTO_ASI) AS CONCEPTO_DIA,
       L.DOCUMENTO_ASILIN AS DOCUMENTO_DIA,
       L.IMPORTE_DEBE_ASILIN AS IMPORTE_DEBE_DIA,
       L.IMPORTE_HABER_ASILIN AS IMPORTE_HABER_DIA
FROM cza_asientos A
JOIN cza_asientos_lineas L ON L.ID_ASI_ASILIN = A.ID_ASI
JOIN cza_cuentas C
  ON C.CODIGO_EMP_CTA = A.CODIGO_EMP_ASI
 AND C.EJERCICIO_CTA = A.EJERCICIO_ASI
 AND C.CODIGO_CTA = L.CODIGO_CTA_ASILIN
WHERE A.ESTADO_ASI = 'CERRADO';

CREATE OR REPLACE VIEW VI_CZA_LIBRO_MAYOR AS
SELECT A.CODIGO_EMP_ASI AS CODIGO_EMP_MAY,
       A.EJERCICIO_ASI AS EJERCICIO_MAY,
       L.CODIGO_CTA_ASILIN AS CODIGO_CTA_MAY,
       C.NOMBRE_CTA AS NOMBRE_CTA_MAY,
       A.FECHA_ASI AS FECHA_MAY,
       A.NUMERO_ASI AS NUMERO_ASI_MAY,
       L.LINEA_ASILIN AS LINEA_ASILIN_MAY,
       COALESCE(L.CONCEPTO_ASILIN, A.CONCEPTO_ASI) AS CONCEPTO_MAY,
       L.DOCUMENTO_ASILIN AS DOCUMENTO_MAY,
       L.IMPORTE_DEBE_ASILIN AS IMPORTE_DEBE_MAY,
       L.IMPORTE_HABER_ASILIN AS IMPORTE_HABER_MAY,
       SUM(L.IMPORTE_DEBE_ASILIN - L.IMPORTE_HABER_ASILIN)
         OVER (
           PARTITION BY A.CODIGO_EMP_ASI, A.EJERCICIO_ASI,
                        L.CODIGO_CTA_ASILIN
           ORDER BY A.FECHA_ASI, A.NUMERO_ASI, L.LINEA_ASILIN,
                    L.ID_ASILIN
           ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
         ) AS SALDO_ACUMULADO_MAY
FROM cza_asientos A
JOIN cza_asientos_lineas L ON L.ID_ASI_ASILIN = A.ID_ASI
JOIN cza_cuentas C
  ON C.CODIGO_EMP_CTA = A.CODIGO_EMP_ASI
 AND C.EJERCICIO_CTA = A.EJERCICIO_ASI
 AND C.CODIGO_CTA = L.CODIGO_CTA_ASILIN
WHERE A.ESTADO_ASI = 'CERRADO';

INSERT IGNORE INTO cza_empresas (
  CODIGO_EMP, RAZON_SOCIAL_EMP, NIF_EMP, ORDEN_EMP, ESACTIVO_EMP,
  CODIGO_EMP_FACTUZAM_EMP, BASE_DATOS_FACTUZAM_EMP,
  INSTANTE_ALTA, USUARIO_ALTA
) VALUES (
  '001', 'Mi sociedad limitada', NULL, 10, 'S', '001', 'factuzam',
  NOW(), 'INSTALADOR'
);

INSERT IGNORE INTO cza_ejercicios (
  CODIGO_EMP_EJE, EJERCICIO_EJE, FECHA_INICIO_EJE, FECHA_FIN_EJE,
  ESTADO_EJE, ESACTIVO_EJE, INSTANTE_ALTA, USUARIO_ALTA
)
SELECT '001', YEAR(CURDATE()),
       STR_TO_DATE(CONCAT(YEAR(CURDATE()), '-01-01'), '%Y-%m-%d'),
       STR_TO_DATE(CONCAT(YEAR(CURDATE()), '-12-31'), '%Y-%m-%d'),
       'ABIERTO', 'S', NOW(), 'INSTALADOR';

INSERT IGNORE INTO cza_contadores (
  TIPO_DOCUMENTO_CON, CODIGO_EMP_CON, EJERCICIO_CON, SERIE_CON,
  CONTADOR_CON, NUMERO_DIGITOS_CON, ESACTIVO_CON, ESDEFECTO_CON,
  INSTANTE_ALTA, USUARIO_ALTA
)
SELECT 'ASIENTO', '001', YEAR(CURDATE()), '-', '00000000', 8, 'S', 'S',
       NOW(), 'INSTALADOR';

INSERT IGNORE INTO cza_contadores (
  TIPO_DOCUMENTO_CON, CODIGO_EMP_CON, EJERCICIO_CON, SERIE_CON,
  CONTADOR_CON, NUMERO_DIGITOS_CON, ESACTIVO_CON, ESDEFECTO_CON,
  INSTANTE_ALTA, USUARIO_ALTA
)
SELECT TIPO, 'GLOBAL', 0, '-', '000000000000000000', 18, 'S', 'S',
       NOW(), 'INSTALADOR'
FROM (
  SELECT 'ID_ASIENTO' AS TIPO
  UNION ALL SELECT 'ID_APUNTE'
  UNION ALL SELECT 'ID_IMPORTACION'
  UNION ALL SELECT 'ID_DOCUMENTO'
  UNION ALL SELECT 'ID_AUDITORIA_LISTADO'
) C;

INSERT IGNORE INTO cza_grupos (
  CODIGO_GRU, NOMBRE_GRU, ESACTIVO_GRU,
  INSTANTE_ALTA, USUARIO_ALTA
) VALUES (
  'ADMIN', 'Administradores de Contazam', 'S', NOW(), 'INSTALADOR'
);

INSERT IGNORE INTO cza_grupos_permisos (
  CODIGO_GRU_GPE, RECURSO_GPE, ACCION_GPE,
  ALCANCE_GPE, CODIGO_EMP_GPE, ESACTIVO_GPE,
  INSTANTE_ALTA, USUARIO_ALTA
) VALUES (
  'ADMIN', '*', '*', 'GLOBAL', '*', 'S', NOW(), 'INSTALADOR'
);

UPDATE cza_contadores
SET CONTADOR_CON = LPAD(
  CONTADOR_CON,
  GREATEST(NUMERO_DIGITOS_CON, CHAR_LENGTH(CONTADOR_CON)),
  '0'
)
WHERE CONTADOR_CON REGEXP '^[0-9]+$'
  AND CHAR_LENGTH(CONTADOR_CON) < NUMERO_DIGITOS_CON;

INSERT IGNORE INTO cza_cuentas_modelo (
  CODIGO_MOD, CODIGO_PADRE_MOD, NOMBRE_MOD, NIVEL_MOD, TIPO_MOD,
  NATURALEZA_MOD, ESIMPUTABLE_MOD, ESACTIVO_MOD, ORDEN_MOD,
  INSTANTE_ALTA, USUARIO_ALTA
) VALUES
('1', NULL, 'Financiación básica', 1, 'GRUPO', 'H', 'N', 'S', 100,
 NOW(), 'INSTALADOR'),
('100', '1', 'Capital social', 3, 'CUENTA', 'H', 'N', 'S', 100,
 NOW(), 'INSTALADOR'),
('100000000000', '100', 'Capital social', 4, 'SUBCUENTA', 'H', 'S', 'S', 100,
 NOW(), 'INSTALADOR'),
('112', '1', 'Reserva legal', 3, 'CUENTA', 'H', 'N', 'S', 112,
 NOW(), 'INSTALADOR'),
('112000000000', '112', 'Reserva legal', 4, 'SUBCUENTA', 'H', 'S', 'S', 112,
 NOW(), 'INSTALADOR'),
('113', '1', 'Reservas voluntarias', 3, 'CUENTA', 'H', 'N', 'S', 113,
 NOW(), 'INSTALADOR'),
('113000000000', '113', 'Reservas voluntarias', 4, 'SUBCUENTA', 'H',
 'S', 'S', 113, NOW(), 'INSTALADOR'),
('129', '1', 'Resultado del ejercicio', 3, 'CUENTA', 'H', 'N', 'S', 129,
 NOW(), 'INSTALADOR'),
('129000000000', '129', 'Resultado del ejercicio', 4, 'SUBCUENTA', 'H',
 'S', 'S', 129, NOW(), 'INSTALADOR'),
('170', '1', 'Deudas a largo plazo con entidades de crédito', 3, 'CUENTA',
 'H', 'N', 'S', 170, NOW(), 'INSTALADOR'),
('170000000000', '170', 'Préstamos bancarios a largo plazo', 4,
 'SUBCUENTA', 'H', 'S', 'S', 170, NOW(), 'INSTALADOR'),
('2', NULL, 'Activo no corriente', 1, 'GRUPO', 'D', 'N', 'S', 200,
 NOW(), 'INSTALADOR'),
('200', '2', 'Investigación', 3, 'CUENTA', 'D', 'N', 'S', 200,
 NOW(), 'INSTALADOR'),
('200000000000', '200', 'Investigación', 4, 'SUBCUENTA', 'D', 'S', 'S',
 200, NOW(), 'INSTALADOR'),
('206', '2', 'Aplicaciones informáticas', 3, 'CUENTA', 'D', 'N', 'S', 206,
 NOW(), 'INSTALADOR'),
('206000000000', '206', 'Aplicaciones informáticas', 4, 'SUBCUENTA', 'D',
 'S', 'S', 206, NOW(), 'INSTALADOR'),
('210', '2', 'Terrenos y bienes naturales', 3, 'CUENTA', 'D', 'N', 'S', 210,
 NOW(), 'INSTALADOR'),
('210000000000', '210', 'Terrenos y bienes naturales', 4, 'SUBCUENTA', 'D',
 'S', 'S', 210, NOW(), 'INSTALADOR'),
('211', '2', 'Construcciones', 3, 'CUENTA', 'D', 'N', 'S', 211,
 NOW(), 'INSTALADOR'),
('211000000000', '211', 'Construcciones', 4, 'SUBCUENTA', 'D', 'S', 'S',
 211, NOW(), 'INSTALADOR'),
('216', '2', 'Mobiliario', 3, 'CUENTA', 'D', 'N', 'S', 216,
 NOW(), 'INSTALADOR'),
('216000000000', '216', 'Mobiliario', 4, 'SUBCUENTA', 'D', 'S', 'S', 216,
 NOW(), 'INSTALADOR'),
('217', '2', 'Equipos para procesos de información', 3, 'CUENTA', 'D', 'N',
 'S', 217, NOW(), 'INSTALADOR'),
('217000000000', '217', 'Equipos informáticos', 4, 'SUBCUENTA', 'D', 'S',
 'S', 217, NOW(), 'INSTALADOR'),
('218', '2', 'Elementos de transporte', 3, 'CUENTA', 'D', 'N', 'S', 218,
 NOW(), 'INSTALADOR'),
('218000000000', '218', 'Elementos de transporte', 4, 'SUBCUENTA', 'D', 'S',
 'S', 218, NOW(), 'INSTALADOR'),
('281', '2', 'Amortización acumulada del inmovilizado material', 3, 'CUENTA',
 'H', 'N', 'S', 281, NOW(), 'INSTALADOR'),
('281000000000', '281', 'Amortización acumulada', 4, 'SUBCUENTA', 'H', 'S',
 'S', 281, NOW(), 'INSTALADOR'),
('3', NULL, 'Existencias', 1, 'GRUPO', 'D', 'N', 'S', 300,
 NOW(), 'INSTALADOR'),
('300', '3', 'Mercaderías', 3, 'CUENTA', 'D', 'N', 'S', 300,
 NOW(), 'INSTALADOR'),
('300000000000', '300', 'Mercaderías', 4, 'SUBCUENTA', 'D', 'S', 'S', 300,
 NOW(), 'INSTALADOR'),
('310', '3', 'Materias primas', 3, 'CUENTA', 'D', 'N', 'S', 310,
 NOW(), 'INSTALADOR'),
('310000000000', '310', 'Materias primas', 4, 'SUBCUENTA', 'D', 'S', 'S',
 310, NOW(), 'INSTALADOR'),
('4', NULL, 'Acreedores y deudores por operaciones comerciales', 1,
 'GRUPO', 'D', 'N', 'S', 400, NOW(), 'INSTALADOR'),
('400', '4', 'Proveedores', 3, 'CUENTA', 'H', 'N', 'S', 400,
 NOW(), 'INSTALADOR'),
('400000000000', '400', 'Proveedores', 4, 'SUBCUENTA', 'H', 'S', 'S', 400,
 NOW(), 'INSTALADOR'),
('410', '4', 'Acreedores por prestaciones de servicios', 3, 'CUENTA', 'H',
 'N', 'S', 410, NOW(), 'INSTALADOR'),
('410000000000', '410', 'Acreedores por servicios', 4, 'SUBCUENTA', 'H', 'S',
 'S', 410, NOW(), 'INSTALADOR'),
('430', '4', 'Clientes', 3, 'CUENTA', 'D', 'N', 'S', 430,
 NOW(), 'INSTALADOR'),
('430000000000', '430', 'Clientes', 4, 'SUBCUENTA', 'D', 'S', 'S', 430,
 NOW(), 'INSTALADOR'),
('431', '4', 'Clientes, efectos comerciales a cobrar', 3, 'CUENTA', 'D',
 'N', 'S', 431, NOW(), 'INSTALADOR'),
('431000000000', '431', 'Efectos comerciales a cobrar', 4, 'SUBCUENTA', 'D',
 'S', 'S', 431, NOW(), 'INSTALADOR'),
('440', '4', 'Deudores', 3, 'CUENTA', 'D', 'N', 'S', 440,
 NOW(), 'INSTALADOR'),
('440000000000', '440', 'Deudores', 4, 'SUBCUENTA', 'D', 'S', 'S', 440,
 NOW(), 'INSTALADOR'),
('465', '4', 'Remuneraciones pendientes de pago', 3, 'CUENTA', 'H', 'N',
 'S', 465, NOW(), 'INSTALADOR'),
('465000000000', '465', 'Remuneraciones pendientes de pago', 4, 'SUBCUENTA',
 'H', 'S', 'S', 465, NOW(), 'INSTALADOR'),
('472', '4', 'Hacienda Pública, IVA soportado', 3, 'CUENTA', 'D', 'N', 'S',
 472, NOW(), 'INSTALADOR'),
('472000000000', '472', 'IVA soportado', 4, 'SUBCUENTA', 'D', 'S', 'S', 472,
 NOW(), 'INSTALADOR'),
('473', '4', 'Hacienda Pública, retenciones y pagos a cuenta', 3, 'CUENTA',
 'D', 'N', 'S', 473, NOW(), 'INSTALADOR'),
('473000000000', '473', 'Retenciones y pagos a cuenta', 4, 'SUBCUENTA', 'D',
 'S', 'S', 473, NOW(), 'INSTALADOR'),
('475', '4', 'Hacienda Pública, acreedora', 3, 'CUENTA', 'H', 'N', 'S', 475,
 NOW(), 'INSTALADOR'),
('475000000000', '475', 'Hacienda Pública, acreedora', 4, 'SUBCUENTA', 'H',
 'S', 'S', 475, NOW(), 'INSTALADOR'),
('4751', '475', 'Hacienda Pública, acreedora por retenciones practicadas', 4,
 'CUENTA', 'H', 'N', 'S', 4751, NOW(), 'INSTALADOR'),
('475100000000', '4751', 'Retenciones practicadas', 5, 'SUBCUENTA', 'H', 'S',
 'S', 4751, NOW(), 'INSTALADOR'),
('476', '4', 'Organismos de la Seguridad Social, acreedores', 3, 'CUENTA', 'H',
 'N', 'S', 476, NOW(), 'INSTALADOR'),
('476000000000', '476', 'Seguridad Social acreedora', 4, 'SUBCUENTA', 'H', 'S',
 'S', 476, NOW(), 'INSTALADOR'),
('477', '4', 'Hacienda Pública, IVA repercutido', 3, 'CUENTA', 'H', 'N', 'S',
 477, NOW(), 'INSTALADOR'),
('477000000000', '477', 'IVA repercutido', 4, 'SUBCUENTA', 'H', 'S', 'S', 477,
 NOW(), 'INSTALADOR'),
('5', NULL, 'Cuentas financieras', 1, 'GRUPO', 'D', 'N', 'S', 500,
 NOW(), 'INSTALADOR'),
('520', '5', 'Deudas a corto plazo con entidades de crédito', 3, 'CUENTA',
 'H', 'N', 'S', 520, NOW(), 'INSTALADOR'),
('520000000000', '520', 'Préstamos bancarios a corto plazo', 4, 'SUBCUENTA',
 'H', 'S', 'S', 520, NOW(), 'INSTALADOR'),
('523', '5', 'Proveedores de inmovilizado a corto plazo', 3, 'CUENTA', 'H',
 'N', 'S', 523, NOW(), 'INSTALADOR'),
('523000000000', '523', 'Proveedores de inmovilizado a corto plazo', 4,
 'SUBCUENTA', 'H', 'S', 'S', 523, NOW(), 'INSTALADOR'),
('555', '5', 'Partidas pendientes de aplicación', 3, 'CUENTA', 'D', 'N', 'S',
 555, NOW(), 'INSTALADOR'),
('555000000000', '555', 'Partidas pendientes de aplicación', 4, 'SUBCUENTA',
 'D', 'S', 'S', 555, NOW(), 'INSTALADOR'),
('570', '5', 'Caja', 3, 'CUENTA', 'D', 'N', 'S', 570,
 NOW(), 'INSTALADOR'),
('570000000000', '570', 'Caja', 4, 'SUBCUENTA', 'D', 'S', 'S', 570,
 NOW(), 'INSTALADOR'),
('572', '5', 'Bancos e instituciones de crédito', 3, 'CUENTA', 'D', 'N', 'S',
 572, NOW(), 'INSTALADOR'),
('572000000000', '572', 'Banco principal', 4, 'SUBCUENTA', 'D', 'S', 'S', 572,
 NOW(), 'INSTALADOR'),
('6', NULL, 'Compras y gastos', 1, 'GRUPO', 'D', 'N', 'S', 600,
 NOW(), 'INSTALADOR'),
('600', '6', 'Compras de mercaderías', 3, 'CUENTA', 'D', 'N', 'S', 600,
 NOW(), 'INSTALADOR'),
('600000000000', '600', 'Compras de mercaderías', 4, 'SUBCUENTA', 'D', 'S',
 'S', 600, NOW(), 'INSTALADOR'),
('602', '6', 'Compras de otros aprovisionamientos', 3, 'CUENTA', 'D', 'N',
 'S', 602, NOW(), 'INSTALADOR'),
('602000000000', '602', 'Otros aprovisionamientos', 4, 'SUBCUENTA', 'D', 'S',
 'S', 602, NOW(), 'INSTALADOR'),
('621', '6', 'Arrendamientos y cánones', 3, 'CUENTA', 'D', 'N', 'S', 621,
 NOW(), 'INSTALADOR'),
('621000000000', '621', 'Arrendamientos y cánones', 4, 'SUBCUENTA', 'D', 'S',
 'S', 621, NOW(), 'INSTALADOR'),
('622', '6', 'Reparaciones y conservación', 3, 'CUENTA', 'D', 'N', 'S', 622,
 NOW(), 'INSTALADOR'),
('622000000000', '622', 'Reparaciones y conservación', 4, 'SUBCUENTA', 'D',
 'S', 'S', 622, NOW(), 'INSTALADOR'),
('623', '6', 'Servicios de profesionales independientes', 3, 'CUENTA', 'D',
 'N', 'S', 623, NOW(), 'INSTALADOR'),
('623000000000', '623', 'Profesionales independientes', 4, 'SUBCUENTA', 'D',
 'S', 'S', 623, NOW(), 'INSTALADOR'),
('625', '6', 'Primas de seguros', 3, 'CUENTA', 'D', 'N', 'S', 625,
 NOW(), 'INSTALADOR'),
('625000000000', '625', 'Primas de seguros', 4, 'SUBCUENTA', 'D', 'S', 'S',
 625, NOW(), 'INSTALADOR'),
('626', '6', 'Servicios bancarios y similares', 3, 'CUENTA', 'D', 'N', 'S',
 626, NOW(), 'INSTALADOR'),
('626000000000', '626', 'Servicios bancarios', 4, 'SUBCUENTA', 'D', 'S', 'S',
 626, NOW(), 'INSTALADOR'),
('627', '6', 'Publicidad, propaganda y relaciones públicas', 3, 'CUENTA',
 'D', 'N', 'S', 627, NOW(), 'INSTALADOR'),
('627000000000', '627', 'Publicidad y propaganda', 4, 'SUBCUENTA', 'D', 'S',
 'S', 627, NOW(), 'INSTALADOR'),
('628', '6', 'Suministros', 3, 'CUENTA', 'D', 'N', 'S', 628,
 NOW(), 'INSTALADOR'),
('628000000000', '628', 'Suministros', 4, 'SUBCUENTA', 'D', 'S', 'S', 628,
 NOW(), 'INSTALADOR'),
('629', '6', 'Otros servicios', 3, 'CUENTA', 'D', 'N', 'S', 629,
 NOW(), 'INSTALADOR'),
('629000000000', '629', 'Otros servicios', 4, 'SUBCUENTA', 'D', 'S', 'S',
 629, NOW(), 'INSTALADOR'),
('630', '6', 'Impuesto sobre beneficios', 3, 'CUENTA', 'D', 'N', 'S', 630,
 NOW(), 'INSTALADOR'),
('630000000000', '630', 'Impuesto corriente', 4, 'SUBCUENTA', 'D', 'S', 'S',
 630, NOW(), 'INSTALADOR'),
('640', '6', 'Sueldos y salarios', 3, 'CUENTA', 'D', 'N', 'S', 640,
 NOW(), 'INSTALADOR'),
('640000000000', '640', 'Sueldos y salarios', 4, 'SUBCUENTA', 'D', 'S', 'S',
 640, NOW(), 'INSTALADOR'),
('642', '6', 'Seguridad Social a cargo de la empresa', 3, 'CUENTA', 'D', 'N',
 'S', 642, NOW(), 'INSTALADOR'),
('642000000000', '642', 'Seguridad Social a cargo de la empresa', 4,
 'SUBCUENTA', 'D', 'S', 'S', 642, NOW(), 'INSTALADOR'),
('650', '6', 'Pérdidas de créditos comerciales incobrables', 3, 'CUENTA', 'D',
 'N', 'S', 650, NOW(), 'INSTALADOR'),
('650000000000', '650', 'Créditos comerciales incobrables', 4, 'SUBCUENTA',
 'D', 'S', 'S', 650, NOW(), 'INSTALADOR'),
('662', '6', 'Intereses de deudas', 3, 'CUENTA', 'D', 'N', 'S', 662,
 NOW(), 'INSTALADOR'),
('662000000000', '662', 'Intereses de deudas', 4, 'SUBCUENTA', 'D', 'S', 'S',
 662, NOW(), 'INSTALADOR'),
('678', '6', 'Gastos excepcionales', 3, 'CUENTA', 'D', 'N', 'S', 678,
 NOW(), 'INSTALADOR'),
('678000000000', '678', 'Gastos excepcionales', 4, 'SUBCUENTA', 'D', 'S',
 'S', 678, NOW(), 'INSTALADOR'),
('7', NULL, 'Ventas e ingresos', 1, 'GRUPO', 'H', 'N', 'S', 700,
 NOW(), 'INSTALADOR'),
('700', '7', 'Ventas de mercaderías', 3, 'CUENTA', 'H', 'N', 'S', 700,
 NOW(), 'INSTALADOR'),
('700000000000', '700', 'Ventas de mercaderías', 4, 'SUBCUENTA', 'H', 'S',
 'S', 700, NOW(), 'INSTALADOR'),
('705', '7', 'Prestaciones de servicios', 3, 'CUENTA', 'H', 'N', 'S', 705,
 NOW(), 'INSTALADOR'),
('705000000000', '705', 'Prestaciones de servicios', 4, 'SUBCUENTA', 'H',
 'S', 'S', 705, NOW(), 'INSTALADOR'),
('740', '7', 'Subvenciones a la explotación', 3, 'CUENTA', 'H', 'N', 'S',
 740, NOW(), 'INSTALADOR'),
('740000000000', '740', 'Subvenciones a la explotación', 4, 'SUBCUENTA', 'H',
 'S', 'S', 740, NOW(), 'INSTALADOR'),
('752', '7', 'Ingresos por arrendamientos', 3, 'CUENTA', 'H', 'N', 'S', 752,
 NOW(), 'INSTALADOR'),
('752000000000', '752', 'Ingresos por arrendamientos', 4, 'SUBCUENTA', 'H',
 'S', 'S', 752, NOW(), 'INSTALADOR'),
('759', '7', 'Ingresos por servicios diversos', 3, 'CUENTA', 'H', 'N', 'S',
 759, NOW(), 'INSTALADOR'),
('759000000000', '759', 'Ingresos por servicios diversos', 4, 'SUBCUENTA',
 'H', 'S', 'S', 759, NOW(), 'INSTALADOR'),
('769', '7', 'Otros ingresos financieros', 3, 'CUENTA', 'H', 'N', 'S', 769,
 NOW(), 'INSTALADOR'),
('769000000000', '769', 'Otros ingresos financieros', 4, 'SUBCUENTA', 'H',
 'S', 'S', 769, NOW(), 'INSTALADOR'),
('778', '7', 'Ingresos excepcionales', 3, 'CUENTA', 'H', 'N', 'S', 778,
 NOW(), 'INSTALADOR'),
('778000000000', '778', 'Ingresos excepcionales', 4, 'SUBCUENTA', 'H', 'S',
 'S', 778, NOW(), 'INSTALADOR');

INSERT IGNORE INTO cza_cuentas (
  CODIGO_EMP_CTA, EJERCICIO_CTA, CODIGO_CTA, CODIGO_CTA_PADRE_CTA,
  NOMBRE_CTA, NIVEL_CTA, TIPO_CTA, NATURALEZA_CTA, ESIMPUTABLE_CTA,
  ESACTIVO_CTA, ORDEN_CTA, INSTANTE_ALTA, USUARIO_ALTA
)
SELECT '001', YEAR(CURDATE()), CODIGO_MOD, CODIGO_PADRE_MOD, NOMBRE_MOD,
       NIVEL_MOD, TIPO_MOD, NATURALEZA_MOD, ESIMPUTABLE_MOD, 'S',
       ORDEN_MOD, NOW(), 'INSTALADOR'
FROM cza_cuentas_modelo
WHERE ESACTIVO_MOD = 'S';

INSERT IGNORE INTO cza_mapeos_contables (
  CODIGO_EMP_MAP, EJERCICIO_MAP, ROL_MAP, CODIGO_CTA_MAP,
  ESACTIVO_MAP, INSTANTE_ALTA, USUARIO_ALTA
)
SELECT '001', YEAR(CURDATE()), ROL, CUENTA, 'S', NOW(), 'INSTALADOR'
FROM (
  SELECT 'CLIENTES' AS ROL, '430000000000' AS CUENTA
  UNION ALL SELECT 'RETENCIONES', '473000000000'
  UNION ALL SELECT 'VENTAS', '700000000000'
  UNION ALL SELECT 'IVA_REPERCUTIDO', '477000000000'
) M;

INSERT IGNORE INTO cza_reglas_contrapartida (
  CODIGO_EMP_REG, EJERCICIO_REG, PREFIJO_ORIGEN_REG,
  PREFIJO_DESTINO_REG, PRIORIDAD_REG, ESACTIVO_REG,
  INSTANTE_ALTA, USUARIO_ALTA
)
SELECT '001', YEAR(CURDATE()), ORIGEN, DESTINO, PRIORIDAD, 'S',
       NOW(), 'INSTALADOR'
FROM (
  SELECT '430' ORIGEN, '700' DESTINO, 100 PRIORIDAD
  UNION ALL SELECT '430', '705', 90
  UNION ALL SELECT '430', '477', 80
  UNION ALL SELECT '700', '430', 100
  UNION ALL SELECT '705', '430', 100
  UNION ALL SELECT '477', '430', 100
  UNION ALL SELECT '400', '600', 100
  UNION ALL SELECT '400', '472', 90
  UNION ALL SELECT '410', '62', 100
  UNION ALL SELECT '410', '472', 90
  UNION ALL SELECT '600', '400', 100
  UNION ALL SELECT '602', '400', 100
  UNION ALL SELECT '62', '410', 100
  UNION ALL SELECT '472', '400', 100
  UNION ALL SELECT '472', '410', 90
  UNION ALL SELECT '572', '430', 100
  UNION ALL SELECT '572', '400', 90
  UNION ALL SELECT '570', '430', 100
  UNION ALL SELECT '570', '400', 90
  UNION ALL SELECT '640', '465', 100
  UNION ALL SELECT '640', '4751', 90
  UNION ALL SELECT '642', '476', 100
  UNION ALL SELECT '465', '572', 100
  UNION ALL SELECT '4751', '572', 100
  UNION ALL SELECT '476', '572', 100
) R;
