USE alexcontazam;

SELECT COUNT(*) AS NUMERO_EMPRESAS
FROM cza_empresas;

SELECT COUNT(*) AS NUMERO_CUENTAS_MODELO,
       MAX(CHAR_LENGTH(CODIGO_MOD)) AS DIGITOS_MAXIMOS_MODELO
FROM cza_cuentas_modelo;

SELECT TIPO_DOCUMENTO_CON,
       CODIGO_EMP_CON,
       EJERCICIO_CON,
       CONTADOR_CON,
       NUMERO_CEROS_CON,
       NUMERO_DIGITOS_CON
FROM cza_contadores
ORDER BY CODIGO_EMP_CON, EJERCICIO_CON, TIPO_DOCUMENTO_CON;

SELECT TABLE_NAME,
       COLUMN_NAME,
       EXTRA
FROM information_schema.COLUMNS
WHERE TABLE_SCHEMA = 'alexcontazam'
  AND COLUMN_NAME IN (
    'ID_ASI', 'ID_ASILIN', 'ID_IMP', 'ID_DOC', 'ID_AUL'
  )
ORDER BY TABLE_NAME, COLUMN_NAME;

SELECT (SELECT COUNT(*) FROM cza_usuarios) AS USUARIOS,
       (SELECT COUNT(*) FROM cza_grupos) AS GRUPOS,
       (SELECT COUNT(*) FROM cza_usuarios_grupos) AS MEMBRESIAS,
       (SELECT COUNT(*) FROM cza_grupos_permisos) AS PERMISOS,
       (SELECT COUNT(*) FROM cza_auditoria_listados) AS USOS_LISTADOS;

SELECT (SELECT COUNT(*) FROM cza_listados_derivados)
         AS LISTADOS_DERIVADOS,
       (SELECT COUNT(*) FROM cza_listados_derivados_versiones)
         AS VERSIONES_LISTADOS;

SELECT ID_LISDER,
       RECURSO_BASE_LISDER,
       NOMBRE_LISDER,
       ALCANCE_LISDER,
       CODIGO_EMP_LISDER,
       CODIGO_GRU_LISDER,
       CODIGO_USU_LISDER,
       VERSION_LISDER,
       OCTET_LENGTH(CONTENIDO_FR3_LISDER) AS BYTES_FR3
FROM cza_listados_derivados
ORDER BY RECURSO_BASE_LISDER, NOMBRE_LISDER;

SELECT UG.*
FROM cza_usuarios_grupos UG
LEFT JOIN cza_usuarios U
  ON U.CODIGO_USU = UG.CODIGO_USU_UGR
LEFT JOIN cza_grupos G
  ON G.CODIGO_GRU = UG.CODIGO_GRU_UGR
WHERE U.CODIGO_USU IS NULL
   OR G.CODIGO_GRU IS NULL;

SELECT P.*
FROM cza_grupos_permisos P
LEFT JOIN cza_grupos G
  ON G.CODIGO_GRU = P.CODIGO_GRU_GPE
WHERE G.CODIGO_GRU IS NULL
   OR P.ALCANCE_GPE NOT IN ('GLOBAL', 'EMPRESA')
   OR (P.ALCANCE_GPE = 'GLOBAL' AND P.CODIGO_EMP_GPE <> '*')
   OR (P.ALCANCE_GPE = 'EMPRESA' AND P.CODIGO_EMP_GPE = '*');

SELECT A.ID_ASI,
       A.CODIGO_EMP_ASI,
       A.EJERCICIO_ASI,
       A.NUMERO_ASI,
       SUM(L.IMPORTE_DEBE_ASILIN) AS TOTAL_DEBE,
       SUM(L.IMPORTE_HABER_ASILIN) AS TOTAL_HABER
FROM cza_asientos A
JOIN cza_asientos_lineas L ON L.ID_ASI_ASILIN = A.ID_ASI
WHERE A.ESTADO_ASI = 'CERRADO'
GROUP BY A.ID_ASI,
         A.CODIGO_EMP_ASI,
         A.EJERCICIO_ASI,
         A.NUMERO_ASI
HAVING ABS(TOTAL_DEBE - TOTAL_HABER) > 0.005;

SELECT L.DOCUMENTO_ASILIN AS REFERENCIA_SIN_PDF,
       A.CODIGO_EMP_ASI,
       A.EJERCICIO_ASI,
       A.NUMERO_ASI
FROM cza_asientos A
JOIN cza_asientos_lineas L ON L.ID_ASI_ASILIN = A.ID_ASI
WHERE COALESCE(TRIM(L.DOCUMENTO_ASILIN), '') <> ''
  AND NOT EXISTS (
    SELECT 1
    FROM cza_documentos D
    WHERE D.CODIGO_EMP_DOC = A.CODIGO_EMP_ASI
      AND D.EJERCICIO_DOC = A.EJERCICIO_ASI
      AND D.REFERENCIA_DOC = L.DOCUMENTO_ASILIN
  );
