USE contazam;

CREATE TABLE IF NOT EXISTS cza_listados_derivados (
  ID_LISDER BIGINT NOT NULL,
  RECURSO_BASE_LISDER VARCHAR(50) NOT NULL,
  NOMBRE_LISDER VARCHAR(100) NOT NULL,
  DESCRIPCION_LISDER VARCHAR(255) NULL,
  ALCANCE_LISDER VARCHAR(15) NOT NULL,
  CODIGO_EMP_LISDER VARCHAR(10) NOT NULL DEFAULT '*',
  CODIGO_GRU_LISDER VARCHAR(30) NOT NULL DEFAULT '',
  CODIGO_USU_LISDER VARCHAR(50) NOT NULL DEFAULT '',
  CONTENIDO_FR3_LISDER LONGBLOB NOT NULL,
  VERSION_LISDER INT NOT NULL DEFAULT 1,
  ESACTIVO_LISDER CHAR(1) NOT NULL DEFAULT 'S',
  INSTANTE_ALTA DATETIME NOT NULL,
  USUARIO_ALTA VARCHAR(100) NOT NULL,
  INSTANTE_MODIF DATETIME NULL,
  USUARIO_MODIF VARCHAR(100) NULL,
  PRIMARY KEY (ID_LISDER),
  UNIQUE KEY UK_CZA_LISTADOS_DERIVADOS_NOMBRE (
    RECURSO_BASE_LISDER,
    ALCANCE_LISDER,
    CODIGO_EMP_LISDER,
    CODIGO_GRU_LISDER,
    CODIGO_USU_LISDER,
    NOMBRE_LISDER
  ),
  KEY IX_CZA_LISTADOS_DERIVADOS_ACCESO (
    RECURSO_BASE_LISDER,
    ESACTIVO_LISDER,
    ALCANCE_LISDER,
    CODIGO_EMP_LISDER,
    CODIGO_GRU_LISDER,
    CODIGO_USU_LISDER
  )
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS cza_listados_derivados_versiones (
  ID_LISDER_LISVER BIGINT NOT NULL,
  VERSION_LISVER INT NOT NULL,
  NOMBRE_LISVER VARCHAR(100) NOT NULL,
  DESCRIPCION_LISVER VARCHAR(255) NULL,
  ALCANCE_LISVER VARCHAR(15) NOT NULL,
  CODIGO_EMP_LISVER VARCHAR(10) NOT NULL DEFAULT '*',
  CODIGO_GRU_LISVER VARCHAR(30) NOT NULL DEFAULT '',
  CODIGO_USU_LISVER VARCHAR(50) NOT NULL DEFAULT '',
  CONTENIDO_FR3_LISVER LONGBLOB NOT NULL,
  INSTANTE_ALTA DATETIME NOT NULL,
  USUARIO_ALTA VARCHAR(100) NOT NULL,
  INSTANTE_MODIF DATETIME NULL,
  USUARIO_MODIF VARCHAR(100) NULL,
  PRIMARY KEY (ID_LISDER_LISVER, VERSION_LISVER),
  KEY IX_CZA_LISTADOS_VERSIONES_FECHA (
    INSTANTE_ALTA,
    USUARIO_ALTA
  )
) ENGINE=InnoDB;

INSERT IGNORE INTO cza_contadores (
  TIPO_DOCUMENTO_CON,
  CODIGO_EMP_CON,
  EJERCICIO_CON,
  SERIE_CON,
  CONTADOR_CON,
  NUMERO_DIGITOS_CON,
  ESACTIVO_CON,
  INSTANTE_ALTA,
  USUARIO_ALTA
) VALUES (
  'ID_LISTADO_DERIVADO',
  'GLOBAL',
  0,
  '-',
  '000000',
  6,
  'S',
  NOW(),
  'SISTEMA'
);
