USE contazam;

CREATE TABLE IF NOT EXISTS cza_literales (
  CONTEXTO_LIT VARCHAR(50) NOT NULL,
  CLAVE_LIT VARCHAR(80) NOT NULL,
  IDIOMA_LIT VARCHAR(35) NOT NULL,
  TEXTO_LIT VARCHAR(255) NOT NULL,
  ESACTIVO_LIT CHAR(1) NOT NULL DEFAULT 'S',
  INSTANTE_ALTA DATETIME NOT NULL,
  USUARIO_ALTA VARCHAR(100) NOT NULL,
  INSTANTE_MODIF DATETIME NULL,
  USUARIO_MODIF VARCHAR(100) NULL,
  PRIMARY KEY (CONTEXTO_LIT, CLAVE_LIT, IDIOMA_LIT),
  KEY IX_CZA_LITERALES_IDIOMA (
    IDIOMA_LIT, ESACTIVO_LIT, CONTEXTO_LIT
  )
) ENGINE=InnoDB;

ALTER TABLE cza_literales
  MODIFY IDIOMA_LIT VARCHAR(35) NOT NULL;

INSERT IGNORE INTO cza_literales (
  CONTEXTO_LIT,
  CLAVE_LIT,
  IDIOMA_LIT,
  TEXTO_LIT,
  ESACTIVO_LIT,
  INSTANTE_ALTA,
  USUARIO_ALTA
) VALUES
('LISTADO_BALANCE', 'TITULO', 'es-ES',
 'Balance de sumas y saldos', 'S', NOW(), 'INSTALADOR'),
('LISTADO_BALANCE', 'CUENTA', 'es-ES',
 'Código de cuenta', 'S', NOW(), 'INSTALADOR'),
('LISTADO_BALANCE', 'NOMBRE', 'es-ES',
 'Nombre de la cuenta', 'S', NOW(), 'INSTALADOR'),
('LISTADO_BALANCE', 'SUMA_DEBE', 'es-ES',
 'Total anotado en el Debe', 'S', NOW(), 'INSTALADOR'),
('LISTADO_BALANCE', 'SUMA_HABER', 'es-ES',
 'Total anotado en el Haber', 'S', NOW(), 'INSTALADOR'),
('LISTADO_BALANCE', 'SALDO_DEUDOR', 'es-ES',
 'Saldo deudor', 'S', NOW(), 'INSTALADOR'),
('LISTADO_BALANCE', 'SALDO_ACREEDOR', 'es-ES',
 'Saldo acreedor', 'S', NOW(), 'INSTALADOR'),
('LISTADO_DIARIO', 'TITULO', 'es-ES',
 'Libro diario', 'S', NOW(), 'INSTALADOR'),
('LISTADO_DIARIO', 'NUMERO', 'es-ES',
 'Nº de asiento', 'S', NOW(), 'INSTALADOR'),
('LISTADO_DIARIO', 'FECHA', 'es-ES',
 'Fecha del asiento', 'S', NOW(), 'INSTALADOR'),
('LISTADO_DIARIO', 'LINEA', 'es-ES',
 'Nº de apunte', 'S', NOW(), 'INSTALADOR'),
('LISTADO_DIARIO', 'CUENTA', 'es-ES',
 'Código de cuenta', 'S', NOW(), 'INSTALADOR'),
('LISTADO_DIARIO', 'NOMBRE', 'es-ES',
 'Nombre de la cuenta', 'S', NOW(), 'INSTALADOR'),
('LISTADO_DIARIO', 'CONCEPTO', 'es-ES',
 'Explicación del movimiento', 'S', NOW(), 'INSTALADOR'),
('LISTADO_DIARIO', 'DOCUMENTO', 'es-ES',
 'Documento relacionado', 'S', NOW(), 'INSTALADOR'),
('LISTADO_DIARIO', 'DEBE', 'es-ES',
 'Importe en el Debe', 'S', NOW(), 'INSTALADOR'),
('LISTADO_DIARIO', 'HABER', 'es-ES',
 'Importe en el Haber', 'S', NOW(), 'INSTALADOR'),
('LISTADO_MAYOR', 'TITULO', 'es-ES',
 'Libro mayor', 'S', NOW(), 'INSTALADOR'),
('LISTADO_MAYOR', 'CUENTA', 'es-ES',
 'Código de cuenta', 'S', NOW(), 'INSTALADOR'),
('LISTADO_MAYOR', 'NOMBRE', 'es-ES',
 'Nombre de la cuenta', 'S', NOW(), 'INSTALADOR'),
('LISTADO_MAYOR', 'FECHA', 'es-ES',
 'Fecha del movimiento', 'S', NOW(), 'INSTALADOR'),
('LISTADO_MAYOR', 'NUMERO', 'es-ES',
 'Nº de asiento', 'S', NOW(), 'INSTALADOR'),
('LISTADO_MAYOR', 'LINEA', 'es-ES',
 'Nº de apunte', 'S', NOW(), 'INSTALADOR'),
('LISTADO_MAYOR', 'CONCEPTO', 'es-ES',
 'Explicación del movimiento', 'S', NOW(), 'INSTALADOR'),
('LISTADO_MAYOR', 'DOCUMENTO', 'es-ES',
 'Documento relacionado', 'S', NOW(), 'INSTALADOR'),
('LISTADO_MAYOR', 'DEBE', 'es-ES',
 'Importe en el Debe', 'S', NOW(), 'INSTALADOR'),
('LISTADO_MAYOR', 'HABER', 'es-ES',
 'Importe en el Haber', 'S', NOW(), 'INSTALADOR'),
('LISTADO_MAYOR', 'SALDO_ACUMULADO', 'es-ES',
 'Saldo después del movimiento', 'S', NOW(), 'INSTALADOR'),
('LISTADO_BORRADORES', 'TITULO', 'es-ES',
 'Asientos pendientes y borradores', 'S', NOW(), 'INSTALADOR'),
('LISTADO_BORRADORES', 'NUMERO', 'es-ES',
 'Nº de asiento', 'S', NOW(), 'INSTALADOR'),
('LISTADO_BORRADORES', 'FECHA', 'es-ES',
 'Fecha del asiento', 'S', NOW(), 'INSTALADOR'),
('LISTADO_BORRADORES', 'CONCEPTO', 'es-ES',
 'Explicación del asiento', 'S', NOW(), 'INSTALADOR'),
('LISTADO_BORRADORES', 'ORIGEN', 'es-ES',
 'Procedencia', 'S', NOW(), 'INSTALADOR'),
('LISTADO_BORRADORES', 'APUNTES', 'es-ES',
 'Nº de apuntes', 'S', NOW(), 'INSTALADOR'),
('LISTADO_BORRADORES', 'TOTAL_DEBE', 'es-ES',
 'Total en el Debe', 'S', NOW(), 'INSTALADOR'),
('LISTADO_BORRADORES', 'TOTAL_HABER', 'es-ES',
 'Total en el Haber', 'S', NOW(), 'INSTALADOR'),
('LISTADO_BORRADORES', 'DIFERENCIA', 'es-ES',
 'Diferencia pendiente de cuadrar', 'S', NOW(), 'INSTALADOR'),
('LISTADO_DOCUMENTOS', 'TITULO', 'es-ES',
 'Archivo documental y referencias PDF', 'S', NOW(), 'INSTALADOR'),
('LISTADO_DOCUMENTOS', 'ESTADO', 'es-ES',
 'Estado del documento', 'S', NOW(), 'INSTALADOR'),
('LISTADO_DOCUMENTOS', 'REFERENCIA', 'es-ES',
 'Referencia del documento', 'S', NOW(), 'INSTALADOR'),
('LISTADO_DOCUMENTOS', 'TIPO', 'es-ES',
 'Tipo de documento', 'S', NOW(), 'INSTALADOR'),
('LISTADO_DOCUMENTOS', 'FECHA', 'es-ES',
 'Fecha del documento', 'S', NOW(), 'INSTALADOR'),
('LISTADO_DOCUMENTOS', 'DESCRIPCION', 'es-ES',
 'Descripción sencilla', 'S', NOW(), 'INSTALADOR'),
('LISTADO_DOCUMENTOS', 'ARCHIVO', 'es-ES',
 'Nombre del archivo PDF', 'S', NOW(), 'INSTALADOR'),
('LISTADO_DOCUMENTOS', 'BYTES', 'es-ES',
 'Tamaño del archivo (bytes)', 'S', NOW(), 'INSTALADOR'),
('LISTADO_DOCUMENTOS', 'SHA256', 'es-ES',
 'Huella digital SHA-256', 'S', NOW(), 'INSTALADOR');
