CREATE TABLE IF NOT EXISTS cza_perfiles_ventanas (
  CODIGO_EMP_PVE VARCHAR(20) NOT NULL,
  CODIGO_USU_PVE VARCHAR(50) NOT NULL,
  FORMULARIO_PVE VARCHAR(100) NOT NULL,
  NOMBRE_PVE VARCHAR(150) NOT NULL,
  POSICION_IZQUIERDA_PVE INT NOT NULL,
  POSICION_SUPERIOR_PVE INT NOT NULL,
  ANCHO_PVE INT NOT NULL,
  ALTO_PVE INT NOT NULL,
  ESTADO_PVE VARCHAR(12) NOT NULL DEFAULT 'NORMAL',
  PESTANA_ACTIVA_PVE VARCHAR(100) NULL,
  INSTANTE_ALTA DATETIME NOT NULL,
  USUARIO_ALTA VARCHAR(50) NOT NULL,
  INSTANTE_MODIF DATETIME NULL,
  USUARIO_MODIF VARCHAR(50) NULL,
  PRIMARY KEY (
    CODIGO_EMP_PVE,
    CODIGO_USU_PVE,
    FORMULARIO_PVE
  )
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
  COLLATE=utf8mb4_spanish_ci;
CREATE TABLE IF NOT EXISTS cza_perfiles_ventanas_columnas (
  CODIGO_EMP_PVC VARCHAR(20) NOT NULL,
  CODIGO_USU_PVC VARCHAR(50) NOT NULL,
  FORMULARIO_PVC VARCHAR(100) NOT NULL,
  GRID_PVC VARCHAR(100) NOT NULL,
  CAMPO_PVC VARCHAR(100) NOT NULL,
  NOMBRE_PVC VARCHAR(150) NOT NULL,
  ORDEN_PVC INT NOT NULL,
  ESVISIBLE_PVC VARCHAR(1) NOT NULL DEFAULT 'S',
  ANCHO_PVC INT NOT NULL,
  INSTANTE_ALTA DATETIME NOT NULL,
  USUARIO_ALTA VARCHAR(50) NOT NULL,
  INSTANTE_MODIF DATETIME NULL,
  USUARIO_MODIF VARCHAR(50) NULL,
  PRIMARY KEY (
    CODIGO_EMP_PVC,
    CODIGO_USU_PVC,
    FORMULARIO_PVC,
    GRID_PVC,
    CAMPO_PVC
  )
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
  COLLATE=utf8mb4_spanish_ci;
