inherited dmPresupuestos: TdmPresupuestos
  Height = 529
  Width = 626
  PixelsPerInch = 120
  inherited unqryTablaG: TUniQuery
    SQLDelete.Strings = (
      'DELETE FROM fza_presupuestos'
      'WHERE'
      '  NUMERO_PRE = :Old_NUMERO_PRE'
      '  AND SERIE_PRE = :Old_SERIE_PRE')
    SQL.Strings = (
      'SELECT NUMERO_PRE, SERIE_PRE, FECHA_PRE, INSTANTE_MOVIMIENTO_PRE, ESCONSOLIDADO_PRE, ESTADO_PRE, NUMERO_PED_PRE, SERIE_PED_PRE, NUMERO_FAC_PRE, SERIE_FAC_PRE, CODIGO_EMP_PRE, CODIGO_ALM_PRE, RAZON_SOCIAL_EMPRESA_PRE, NIF_EMPRESA_PRE, MOVIL_EMPRESA_PRE, EMAIL_EMPRESA_PRE, DIRECCION1_EMPRESA_PRE, DIRECCION2_EMPRESA_PRE, POBLACION_EMPRESA_PRE, PROVINCIA_EMPRESA_PRE, CODIGO_PAI_EMPRESA_PRE, NOMBRE_PAI_EMPRESA_PRE, CODIGO_POSTAL_EMPRESA_PRE, GRUPO_ZONA_IVA_EMPRESA_PRE, CODIGO_CLI_PRE, RAZON_SOCIAL_CLIENTE_PRE, NIF_CLIENTE_PRE, MOVIL_CLIENTE_PRE, EMAIL_CLIENTE_PRE, DIRECCION1_CLIENTE_PRE, DIRECCION2_CLIENTE_PRE, POBLACION_CLIENTE_PRE, PROVINCIA_CLIENTE_PRE, CODIGO_POSTAL_CLIENTE_PRE, CODIGO_PAI_CLIENTE_PRE, NOMBRE_PAI_CLIENTE_PRE, NOMBRE_CLI_ENVIO_PRE, MOVIL_CLIENTE_ENVIO_PRE, DIRECCION1_CLIENTE_ENVIO_PRE, DIRECCION2_CLIENTE_ENVIO_PRE, POBLACION_CLIENTE_ENVIO_PRE, PROVINCIA_CLIENTE_ENVIO_PRE, CODIGO_POSTAL_CLIENTE_ENVIO_PRE, CODIGO_PAI_CLIENTE_ENVIO_PRE, NOMBRE_PAI_CLIENTE_ENVIO_PRE, TRANSPORTISTA_PRE, CODIGO_IVA_PRE, ESIVA_RECARGO_CLIENTE_PRE, ESIVA_EXENTO_CLIENTE_PRE, ESINTRACOMUNITARIO_CLIENTE_PRE, TARIFA_ARTICULO_CLIENTE_PRE, ESIMP_INCL_TARIFA_CLIENTE_PRE, PORCENTAJE_IVAN_PRE, TOTAL_IVAN_PRE, PORCENTAJE_IVAR_PRE, TOTAL_IVAR_PRE, PORCENTAJE_IVAS_PRE, TOTAL_IVAS_PRE, PORCENTAJE_IVAE_PRE, TOTAL_IVAE_PRE, TOTAL_BASES_PRE, TOTAL_IMPUESTOS_PRE, PORCENTAJE_RETENCION_PRE, TOTAL_RETENCION_PRE, TOTAL_LIQUIDO_PRE, FORMA_PAGO_PRE, CONTADOR_LINEAS_PRE, COMENTARIOS_PRE, OBSERVACIONES_PRE, INSTANTE_MODIF, INSTANTE_ALTA, USUARIO_ALTA, USUARIO_MODIF, TIPO_DESTINO_PRE, SERIE_DESTINO_PRE, NUMERO_DESTINO_PRE, FECHA_VALIDEZ_PRE FROM fza_presupuestos')
    AfterInsert = unqryTablaGAfterInsert
    AfterPost = unqryTablaGAfterPost
    BeforeDelete = unqryTablaGBeforeDelete
    Left = 48
    Top = 24
  end
  object unqryAlbaranesLineas: TUniQuery
    SQL.Strings = (
      'SELECT NUMERO_PRE_PRELIN, SERIE_PRE_PRELIN, LINEA_PRELIN, NUMERO_PED_PRELIN, SERIE_PED_PRELIN, LINEA_PED_PRELIN, CODIGO_ART_PRELIN, CODIGO_FAM_PRELIN, NOMBRE_FAM_PRELIN, DESCRIPCION_ARTICULO_PRELIN, TIPO_CANTIDAD_ARTICULO_PRELIN, CANTIDAD_PRELIN, CODIGO_TAR_PRELIN, ESIMP_INCL_TARIFA_PRELIN, TIPO_IVA_ARTICULO_PRELIN, PORCENTAJE_IVA_PRELIN, PRECIO_VENTA_SIVA_ARTICULO_PRELIN, PRECIO_VENTA_CIVA_ARTICULO_PRELIN, TOTAL_PRELIN, CODIGO_ALMACEN_PRELIN, INSTANTE_MODIF, INSTANTE_ALTA, USUARIO_ALTA, USUARIO_MODIF, ESFACTURADA_PRELIN, NUMERO_FAC_PRELIN, SERIE_FAC_PRELIN, LINEA_FAC_PRELIN, CODIGO_UNIDAD_PRELIN, LOTE_PRELIN, FECHA_CADUCIDAD_PRELIN, DESCRIPCION_VARIACION_PRELIN, ATTR1_VALOR_PRELIN, ATTR1_NOMBRE_PRELIN, ATTR2_VALOR_PRELIN, ATTR2_NOMBRE_PRELIN, ATTR3_VALOR_PRELIN, ATTR3_NOMBRE_PRELIN, ATTR4_VALOR_PRELIN, ATTR4_NOMBRE_PRELIN, ATTR5_VALOR_PRELIN, ATTR5_NOMBRE_PRELIN, NUM_ATRIBUTOS_PRELIN, ID_AC_PIVOT_PRELIN FROM fza_presupuestos_lineas')
    MasterFields = 'NUMERO_PRE;SERIE_PRE'
    DetailFields = 'NUMERO_PRE_PRELIN;SERIE_PRE_PRELIN'
    AfterInsert = unqryAlbaranesLineasAfterInsert
    BeforePost = unqryAlbaranesLineasBeforePost
    AfterPost = unqryAlbaranesLineasAfterPost
    AfterDelete = unqryAlbaranesLineasAfterDelete
    Left = 520
    Top = 8
    ParamData = <
      item
        DataType = ftUnknown
        Name = 'NUMERO_PRE'
        Value = nil
      end
      item
        DataType = ftUnknown
        Name = 'SERIE_PRE'
        Value = nil
      end>
  end
  object dsAlbaranesLineas: TDataSource
    DataSet = unqryAlbaranesLineas
    Left = 520
    Top = 72
  end
  object unqryEmpDataAlb: TUniQuery
    SQL.Strings = (
      'SELECT CODIGO_EMP_EMP, ORDEN_EMP, ESACTIVO_EMP, RAZON_SOCIAL_EMP, NIF_EMP, MOVIL_EMP, EMAIL_EMP, DIRECCION1_EMP, DIRECCION2_EMP, CODIGO_POSTAL_EMP, POBLACION_EMP, PROVINCIA_EMP, CODIGO_PAI_EMP, NOMBRE_PAI_EMP, SERIE_CON_EMP, IBAN_EMP, GRUPO_ZONA_IVA_EMP, ESRETENCIONES_EMP, ESIVA_RECARGO_COMPRAS_EMP, ESREGIMENESPECIALAGRICOLA_EMP, CODIGO_CERTIFICADO_EMP, TITULAR_CERTIFICADO_EMP, TIPO_CERTIFICADO_EMP, FECHA_DESDE_CERTIFICADO_EMP, FECHA_HASTA_CERTIFICADO_EMP, NUMERO_INSTALACION_EMP, VERSION_INSTALACION_EMP, CODIGO_SIF_INSTALACION_EMP, INSTANTE_INSTALACION_EMP, TEXTO_LEGAL_FACTURA_EMP, TEXTO_PIE_TICKET_CAJA_1_EMP, TEXTO_PIE_TICKET_CAJA_2_EMP, TEXTO_PIE_TICKET_CAJA_3_EMP, TEXTO_PIE_TICKET_CAJA_4_EMP, FORMATO_DOCUMENTO_EMP, INSTANTE_MODIF, INSTANTE_ALTA, USUARIO_ALTA, USUARIO_MODIF, ESTOKENS_CALENDARIO_NATURAL_EMP FROM fza_empresas')
    Left = 48
    Top = 192
  end
  object unqryCliDataAlb: TUniQuery
    SQL.Strings = (
      'SELECT CODIGO_CLI_CLI, ESACTIVO_CLI, ORDEN_CLI, RAZON_SOCIAL_CLI, NIF_CLI, MOVIL_CLI, EMAIL_CLI, DIRECCION1_CLI, DIRECCION2_CLI, POBLACION_CLI, PROVINCIA_CLI, CODIGO_POSTAL_CLI, CODIGO_PAI_CLI, NOMBRE_PAI_CLI, NOMBRE_PERSONA_CLIENTE_CLI, APELLIDOS_PERSONA_CLIENTE_CLI, CODIGO_OFICINA_CONTABLE_CLI, CODIGO_ORGANO_GESTOR_CLI, CODIGO_UNIDAD_TRAMITADORA_CLI, OBSERVACIONES_CLI, REFERENCIA_CLI, CONTACTO_CLI, TELEFONO_CONTACTO_CLI, TELEFONO_CLI, IBAN_CLI, ID_MANDATO_SEPA_CLI, FECHA_FIRMA_MANDATO_SEPA_CLI, ESIVA_RECARGO_CLI, ESRETENCIONES_CLI, TOTAL_LIMITE_CREDITO_CLI, ESPERMITE_DEUDA_CLI, TOTAL_DEUDA_CLI, ESIVA_EXENTO_CLI, ESINTRACOMUNITARIO_CLI, ESREGIMENESPECIALAGRICOLA_CLI, CODIGO_FP_CLI, CODIGO_EMPBAN_CLI, TARIFA_ARTICULO_CLI, SERIE_CON_CLI, TEXTO_LEGAL_FACTURA_CLI, INSTANTE_MODIF, INSTANTE_ALTA, USUARIO_ALTA, USUARIO_MODIF FROM fza_clientes')
    Left = 48
    Top = 248
  end
  object unqryArtDataLinAlb: TUniQuery
    SQL.Strings = (
      'SELECT CODIGO_ART_ART, ESACTIVO_ART, ESWEB_ART, TIPO_ART, DESCRIPCION_ART, CODIGO_FAM_ART, TIPO_IVA_ART, ESACTIVO_FIJO_ART, TIPO_CANTIDAD_ART, ESVARIACION_ART, ESTRAZABLE_ART, ORDEN_ART, INSTANTE_MODIF, INSTANTE_ALTA, USUARIO_ALTA, USUARIO_MODIF, TIPO_VARIACION_ART FROM fza_articulos')
    Left = 48
    Top = 304
  end
  object unqrySkusAlb: TUniQuery
    SQL.Strings = (
      'SELECT CODIGO_UNIDAD_SKU, CODIGO_ART_SKU '
      '  FROM fza_articulos_skus '
      ' WHERE CODIGO_UNIDAD_SKU = :pSKU')
    Left = 48
    Top = 360
    ParamData = <
      item
        DataType = ftString
        Name = 'pSKU'
        ParamType = ptInput
        Value = nil
      end>
  end
  object unqryAlmacenesAlb: TUniQuery
    SQL.Strings = (
      'SELECT CODIGO_ALM_ALM, NOMBRE_ALM_ALM, CODIGO_EMP_ALM'
      '  FROM fza_almacenes'
      ' WHERE ESACTIVO_ALM = '#39'S'#39
      '   AND CODIGO_EMP_ALM = :EMPRESA'
      ' ORDER BY COALESCE(ORDEN_ALM, 2147483647), CODIGO_ALM_ALM')
    Left = 160
    Top = 360
    ParamData = <
      item
        DataType = ftString
        Name = 'EMPRESA'
        ParamType = ptInput
        Value = nil
      end>
  end
  object dsAlmacenesAlb: TDataSource
    DataSet = unqryAlmacenesAlb
    Left = 160
    Top = 424
  end
  object unstrdprcGetContadorAlbaran: TUniStoredProc
    StoredProcName = 'PRC_GET_NEXT_CONT_FACT_SERIE'
    Left = 256
    Top = 24
  end
  object fxdsPrintAlb: TfrxDBDataset
    UserName = 'frxDBDataset1'
    CloseDataSource = False
    BCDToCurrency = False
    DataSetOptions = []
    Left = 384
    Top = 24
  end
  object fxdstPrintLinAlb: TfrxDBDataset
    UserName = 'frxDBDataset2'
    CloseDataSource = False
    DataSet = unqryAlbaranesLineas
    BCDToCurrency = False
    DataSetOptions = []
    Left = 384
    Top = 80
  end
  object unqryFormasPago: TUniQuery
    SQL.Strings = (
      'SELECT CODIGO_FP_FP, DESCRIPCION_FORMA_PAGO_FP FROM fza_formas_pago')
    ReadOnly = True
    Left = 512
    Top = 312
  end
  object dsFormasPago: TDataSource
    DataSet = unqryFormasPago
    Left = 512
    Top = 368
  end
  object unqryTarifas: TUniQuery
    SQL.Strings = (
      'SELECT CODIGO_TAR_ARTTAR, NOMBRE_TAR_TAR, ESIMP_INCL_TAR'
      '  FROM vi_tarifas'
      ' ORDER BY NOMBRE_TAR_TAR, CODIGO_TAR_ARTTAR')
    ReadOnly = True
    Left = 600
    Top = 312
  end
  object dsTarifas: TDataSource
    DataSet = unqryTarifas
    Left = 600
    Top = 368
  end
end
