inherited dmContadores: TdmContadores
  inherited unqryTablaG: TUniQuery
    SQLInsert.Strings = (
      'INSERT INTO fza_contadores'
      
        '  (TIPODOC_CONTADOR, SERIE_CONTADOR, EMPRESA_CONTADOR, CONTADOR_' +
        'CONTADOR, DEFAULT_CONTADOR, NUMDIGIT_CONTADOR, ACTIVO_CONTADOR, ' +
        'SUBTIPODOC_CONTADOR, INSTANTEMODIF, INSTANTEALTA, USUARIOALTA, U' +
        'SUARIOMODIF)'
      'VALUES'
      
        '  (:TIPODOC_CONTADOR, :SERIE_CONTADOR, :EMPRESA_CONTADOR, :CONTA' +
        'DOR_CONTADOR, :DEFAULT_CONTADOR, :NUMDIGIT_CONTADOR, :ACTIVO_CON' +
        'TADOR, :SUBTIPODOC_CONTADOR, :INSTANTEMODIF, :INSTANTEALTA, :USU' +
        'ARIOALTA, :USUARIOMODIF)')
    SQLDelete.Strings = (
      'DELETE FROM fza_contadores'
      'WHERE'
      
        '  TIPODOC_CONTADOR = :Old_TIPODOC_CONTADOR AND SERIE_CONTADOR = ' +
        ':Old_SERIE_CONTADOR AND EMPRESA_CONTADOR = :Old_EMPRESA_CONTADOR')
    SQLUpdate.Strings = (
      'UPDATE fza_contadores'
      'SET'
      
        '  TIPODOC_CONTADOR = :TIPODOC_CONTADOR, SERIE_CONTADOR = :SERIE_' +
        'CONTADOR, EMPRESA_CONTADOR = :EMPRESA_CONTADOR, CONTADOR_CONTADO' +
        'R = :CONTADOR_CONTADOR, DEFAULT_CONTADOR = :DEFAULT_CONTADOR, NU' +
        'MDIGIT_CONTADOR = :NUMDIGIT_CONTADOR, ACTIVO_CONTADOR = :ACTIVO_' +
        'CONTADOR, SUBTIPODOC_CONTADOR = :SUBTIPODOC_CONTADOR, INSTANTEMO' +
        'DIF = :INSTANTEMODIF, INSTANTEALTA = :INSTANTEALTA, USUARIOALTA ' +
        '= :USUARIOALTA, USUARIOMODIF = :USUARIOMODIF'
      'WHERE'
      
        '  TIPODOC_CONTADOR = :Old_TIPODOC_CONTADOR AND SERIE_CONTADOR = ' +
        ':Old_SERIE_CONTADOR AND EMPRESA_CONTADOR = :Old_EMPRESA_CONTADOR')
    SQLLock.Strings = (
      
        'SELECT TIPODOC_CONTADOR, SERIE_CONTADOR, EMPRESA_CONTADOR, CONTA' +
        'DOR_CONTADOR, DEFAULT_CONTADOR, NUMDIGIT_CONTADOR, ACTIVO_CONTAD' +
        'OR, SUBTIPODOC_CONTADOR, INSTANTEMODIF, INSTANTEALTA, USUARIOALT' +
        'A, USUARIOMODIF FROM fza_contadores'
      'WHERE'
      
        '  TIPODOC_CONTADOR = :Old_TIPODOC_CONTADOR AND SERIE_CONTADOR = ' +
        ':Old_SERIE_CONTADOR AND EMPRESA_CONTADOR = :Old_EMPRESA_CONTADOR'
      'FOR UPDATE')
    SQLRefresh.Strings = (
      
        'SELECT TIPODOC_CONTADOR, SERIE_CONTADOR, EMPRESA_CONTADOR, CONTA' +
        'DOR_CONTADOR, DEFAULT_CONTADOR, NUMDIGIT_CONTADOR, ACTIVO_CONTAD' +
        'OR, SUBTIPODOC_CONTADOR, INSTANTEMODIF, INSTANTEALTA, USUARIOALT' +
        'A, USUARIOMODIF FROM fza_contadores'
      'WHERE'
      
        '  TIPODOC_CONTADOR = :TIPODOC_CONTADOR AND SERIE_CONTADOR = :SER' +
        'IE_CONTADOR AND EMPRESA_CONTADOR = :EMPRESA_CONTADOR')
    SQLRecCount.Strings = (
      'SELECT COUNT(*) FROM fza_contadores')
    Connection = dmConn.conUni
    SQL.Strings = (
      'SELECT *  '
      'FROM vi_contadores'
      '')
    Active = True
    Left = 24
  end
  inherited unqryPerfiles: TUniQuery
    Active = True
  end
end
