object dmPedidos: TdmPedidos
  Left = 0
  Top = 0
  ClientHeight = 372
  ClientWidth = 636
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -12
  Font.Name = 'Segoe UI'
  Font.Style = []
  TextHeight = 15
  object unqryPedidosLineas: TUniQuery
    SQLInsert.Strings = (
      'INSERT INTO fza_pedidos_lineas'
      
        '  (NRO_PEDIDO_LINEA, SERIE_PEDIDO_LINEA, LINEA_PEDIDO_LINEA, IDL' +
        'INEAPS_PEDIDO_LINEA, IDPRODPS_PEDIDO_LINEA, CODIGOPRODPS_PEDIDO_' +
        'LINEA, IDATRIBPRODPS_PEDIDO_LINEA, CODEAN13PRODPS_PEDIDO_LINEA, ' +
        'CODIGO_ARTICULO_PEDIDO_LINEA, CODIGO_FAMILIA_PEDIDO_LINEA, NOMBR' +
        'E_FAMILIA_PEDIDO_LINEA, FECHA_ENTREGA_PEDIDO_LINEA, TIPO_CANTIDA' +
        'D_ARTICULO_PEDIDO_LINEA, ESIMP_INCL_TARIFA_PEDIDO_LINEA, TIPOIVA' +
        '_ARTICULO_PEDIDO_LINEA, DESCRIPCION_ARTICULO_PEDIDO_LINEA, CODIG' +
        'O_TARIFA_PEDIDO_LINEA, CANTIDAD_PEDIDO_LINEA, PRECIOVENTA_SIVA_A' +
        'RTICULO_PEDIDO_LINEA, PORCEN_IVA_PEDIDO_LINEA, PRECIOVENTA_CIVA_' +
        'ARTICULO_PEDIDO_LINEA, TOTAL_PEDIDO_LINEA, INSTANTEMODIF, INSTAN' +
        'TEALTA, USUARIOALTA, USUARIOMODIF)'
      'VALUES'
      
        '  (:NRO_PEDIDO_LINEA, :SERIE_PEDIDO_LINEA, :LINEA_PEDIDO_LINEA, ' +
        ':IDLINEAPS_PEDIDO_LINEA, :IDPRODPS_PEDIDO_LINEA, :CODIGOPRODPS_P' +
        'EDIDO_LINEA, :IDATRIBPRODPS_PEDIDO_LINEA, :CODEAN13PRODPS_PEDIDO' +
        '_LINEA, :CODIGO_ARTICULO_PEDIDO_LINEA, :CODIGO_FAMILIA_PEDIDO_LI' +
        'NEA, :NOMBRE_FAMILIA_PEDIDO_LINEA, :FECHA_ENTREGA_PEDIDO_LINEA, ' +
        ':TIPO_CANTIDAD_ARTICULO_PEDIDO_LINEA, :ESIMP_INCL_TARIFA_PEDIDO_' +
        'LINEA, :TIPOIVA_ARTICULO_PEDIDO_LINEA, :DESCRIPCION_ARTICULO_PED' +
        'IDO_LINEA, :CODIGO_TARIFA_PEDIDO_LINEA, :CANTIDAD_PEDIDO_LINEA, ' +
        ':PRECIOVENTA_SIVA_ARTICULO_PEDIDO_LINEA, :PORCEN_IVA_PEDIDO_LINE' +
        'A, :PRECIOVENTA_CIVA_ARTICULO_PEDIDO_LINEA, :TOTAL_PEDIDO_LINEA,' +
        ' :INSTANTEMODIF, :INSTANTEALTA, :USUARIOALTA, :USUARIOMODIF)')
    SQLDelete.Strings = (
      'DELETE FROM fza_pedidos_lineas'
      'WHERE'
      
        '  NRO_PEDIDO_LINEA = :Old_NRO_PEDIDO_LINEA AND SERIE_PEDIDO_LINE' +
        'A = :Old_SERIE_PEDIDO_LINEA AND LINEA_PEDIDO_LINEA = :Old_LINEA_' +
        'PEDIDO_LINEA')
    SQLUpdate.Strings = (
      'UPDATE fza_pedidos_lineas'
      'SET'
      
        '  NRO_PEDIDO_LINEA = :NRO_PEDIDO_LINEA, SERIE_PEDIDO_LINEA = :SE' +
        'RIE_PEDIDO_LINEA, LINEA_PEDIDO_LINEA = :LINEA_PEDIDO_LINEA, IDLI' +
        'NEAPS_PEDIDO_LINEA = :IDLINEAPS_PEDIDO_LINEA, IDPRODPS_PEDIDO_LI' +
        'NEA = :IDPRODPS_PEDIDO_LINEA, CODIGOPRODPS_PEDIDO_LINEA = :CODIG' +
        'OPRODPS_PEDIDO_LINEA, IDATRIBPRODPS_PEDIDO_LINEA = :IDATRIBPRODP' +
        'S_PEDIDO_LINEA, CODEAN13PRODPS_PEDIDO_LINEA = :CODEAN13PRODPS_PE' +
        'DIDO_LINEA, CODIGO_ARTICULO_PEDIDO_LINEA = :CODIGO_ARTICULO_PEDI' +
        'DO_LINEA, CODIGO_FAMILIA_PEDIDO_LINEA = :CODIGO_FAMILIA_PEDIDO_L' +
        'INEA, NOMBRE_FAMILIA_PEDIDO_LINEA = :NOMBRE_FAMILIA_PEDIDO_LINEA' +
        ', FECHA_ENTREGA_PEDIDO_LINEA = :FECHA_ENTREGA_PEDIDO_LINEA, TIPO' +
        '_CANTIDAD_ARTICULO_PEDIDO_LINEA = :TIPO_CANTIDAD_ARTICULO_PEDIDO' +
        '_LINEA, ESIMP_INCL_TARIFA_PEDIDO_LINEA = :ESIMP_INCL_TARIFA_PEDI' +
        'DO_LINEA, TIPOIVA_ARTICULO_PEDIDO_LINEA = :TIPOIVA_ARTICULO_PEDI' +
        'DO_LINEA, DESCRIPCION_ARTICULO_PEDIDO_LINEA = :DESCRIPCION_ARTIC' +
        'ULO_PEDIDO_LINEA, CODIGO_TARIFA_PEDIDO_LINEA = :CODIGO_TARIFA_PE' +
        'DIDO_LINEA, CANTIDAD_PEDIDO_LINEA = :CANTIDAD_PEDIDO_LINEA, PREC' +
        'IOVENTA_SIVA_ARTICULO_PEDIDO_LINEA = :PRECIOVENTA_SIVA_ARTICULO_' +
        'PEDIDO_LINEA, PORCEN_IVA_PEDIDO_LINEA = :PORCEN_IVA_PEDIDO_LINEA' +
        ', PRECIOVENTA_CIVA_ARTICULO_PEDIDO_LINEA = :PRECIOVENTA_CIVA_ART' +
        'ICULO_PEDIDO_LINEA, TOTAL_PEDIDO_LINEA = :TOTAL_PEDIDO_LINEA, IN' +
        'STANTEMODIF = :INSTANTEMODIF, INSTANTEALTA = :INSTANTEALTA, USUA' +
        'RIOALTA = :USUARIOALTA, USUARIOMODIF = :USUARIOMODIF'
      'WHERE'
      
        '  NRO_PEDIDO_LINEA = :Old_NRO_PEDIDO_LINEA AND SERIE_PEDIDO_LINE' +
        'A = :Old_SERIE_PEDIDO_LINEA AND LINEA_PEDIDO_LINEA = :Old_LINEA_' +
        'PEDIDO_LINEA')
    SQLLock.Strings = (
      
        'SELECT NRO_PEDIDO_LINEA, SERIE_PEDIDO_LINEA, LINEA_PEDIDO_LINEA,' +
        ' IDLINEAPS_PEDIDO_LINEA, IDPRODPS_PEDIDO_LINEA, CODIGOPRODPS_PED' +
        'IDO_LINEA, IDATRIBPRODPS_PEDIDO_LINEA, CODEAN13PRODPS_PEDIDO_LIN' +
        'EA, CODIGO_ARTICULO_PEDIDO_LINEA, CODIGO_FAMILIA_PEDIDO_LINEA, N' +
        'OMBRE_FAMILIA_PEDIDO_LINEA, FECHA_ENTREGA_PEDIDO_LINEA, TIPO_CAN' +
        'TIDAD_ARTICULO_PEDIDO_LINEA, ESIMP_INCL_TARIFA_PEDIDO_LINEA, TIP' +
        'OIVA_ARTICULO_PEDIDO_LINEA, DESCRIPCION_ARTICULO_PEDIDO_LINEA, C' +
        'ODIGO_TARIFA_PEDIDO_LINEA, CANTIDAD_PEDIDO_LINEA, PRECIOVENTA_SI' +
        'VA_ARTICULO_PEDIDO_LINEA, PORCEN_IVA_PEDIDO_LINEA, PRECIOVENTA_C' +
        'IVA_ARTICULO_PEDIDO_LINEA, TOTAL_PEDIDO_LINEA, INSTANTEMODIF, IN' +
        'STANTEALTA, USUARIOALTA, USUARIOMODIF FROM fza_pedidos_lineas'
      'WHERE'
      
        '  NRO_PEDIDO_LINEA = :Old_NRO_PEDIDO_LINEA AND SERIE_PEDIDO_LINE' +
        'A = :Old_SERIE_PEDIDO_LINEA AND LINEA_PEDIDO_LINEA = :Old_LINEA_' +
        'PEDIDO_LINEA'
      'FOR UPDATE')
    SQLRefresh.Strings = (
      
        'SELECT NRO_PEDIDO_LINEA, SERIE_PEDIDO_LINEA, LINEA_PEDIDO_LINEA,' +
        ' IDLINEAPS_PEDIDO_LINEA, IDPRODPS_PEDIDO_LINEA, CODIGOPRODPS_PED' +
        'IDO_LINEA, IDATRIBPRODPS_PEDIDO_LINEA, CODEAN13PRODPS_PEDIDO_LIN' +
        'EA, CODIGO_ARTICULO_PEDIDO_LINEA, CODIGO_FAMILIA_PEDIDO_LINEA, N' +
        'OMBRE_FAMILIA_PEDIDO_LINEA, FECHA_ENTREGA_PEDIDO_LINEA, TIPO_CAN' +
        'TIDAD_ARTICULO_PEDIDO_LINEA, ESIMP_INCL_TARIFA_PEDIDO_LINEA, TIP' +
        'OIVA_ARTICULO_PEDIDO_LINEA, DESCRIPCION_ARTICULO_PEDIDO_LINEA, C' +
        'ODIGO_TARIFA_PEDIDO_LINEA, CANTIDAD_PEDIDO_LINEA, PRECIOVENTA_SI' +
        'VA_ARTICULO_PEDIDO_LINEA, PORCEN_IVA_PEDIDO_LINEA, PRECIOVENTA_C' +
        'IVA_ARTICULO_PEDIDO_LINEA, TOTAL_PEDIDO_LINEA, INSTANTEMODIF, IN' +
        'STANTEALTA, USUARIOALTA, USUARIOMODIF FROM fza_pedidos_lineas'
      'WHERE'
      
        '  NRO_PEDIDO_LINEA = :NRO_PEDIDO_LINEA AND SERIE_PEDIDO_LINEA = ' +
        ':SERIE_PEDIDO_LINEA AND LINEA_PEDIDO_LINEA = :LINEA_PEDIDO_LINEA')
    SQLRecCount.Strings = (
      'SELECT COUNT(*) FROM fza_pedidos_lineas')
    Connection = dmConn.conUni
    SQL.Strings = (
      'SELECT * FROM vi_pedidos_lineas')
    MasterFields = 'NRO_PEDIDO;SERIE_PEDIDO'
    DetailFields = 'NRO_PEDIDO_LINEA;SERIE_PEDIDO_LINEA'
    AfterInsert = unqryPedidosLineasAfterInsert
    BeforePost = unqryPedidosLineasBeforePost
    Left = 48
    Top = 80
    ParamData = <
      item
        DataType = ftUnknown
        Name = 'NRO_PEDIDO'
        Value = nil
      end
      item
        DataType = ftUnknown
        Name = 'SERIE_PEDIDO'
        Value = nil
      end>
  end
  object dsPedidosLineas: TDataSource
    DataSet = unqryPedidosLineas
    Left = 128
    Top = 80
  end
  object unqryLinPedido: TUniQuery
    Connection = dmConn.conUni
    SQL.Strings = (
      'SELECT * FROM fza_pedidos_lineas'
      'WHERE NRO_PEDIDO_LINEA = :NRO_PEDIDO'
      'AND SERIE_PEDIDO_LINEA = :SERIE_PEDIDO')
    Left = 48
    Top = 136
    ParamData = <
      item
        DataType = ftUnknown
        Name = 'NRO_PEDIDO'
        Value = nil
      end
      item
        DataType = ftUnknown
        Name = 'SERIE_PEDIDO'
        Value = nil
      end>
  end
  object dsLinPedido: TDataSource
    DataSet = unqryLinPedido
    Left = 128
    Top = 136
  end
  object unqryEmpDataPedido: TUniQuery
    Connection = dmConn.conUni
    SQL.Strings = (
      'SELECT * FROM fza_empresas')
    Left = 48
    Top = 192
  end
  object unqryCliDataPedido: TUniQuery
    Connection = dmConn.conUni
    SQL.Strings = (
      'SELECT * FROM fza_clientes')
    Left = 48
    Top = 248
  end
  object unqryArtDataLinPedido: TUniQuery
    Connection = dmConn.conUni
    SQL.Strings = (
      'SELECT * FROM fza_articulos')
    Left = 48
    Top = 304
  end
  object unstrdprcCrearPedido: TUniStoredProc
    StoredProcName = 'PRC_CREAR_PEDIDO'
    Connection = dmConn.conUni
    Left = 256
    Top = 24
  end
  object unstrdprcGetContadorPedido: TUniStoredProc
    StoredProcName = 'PRC_GET_CONTADOR_PEDIDO'
    Connection = dmConn.conUni
    Left = 256
    Top = 80
  end
  object unstrdprcGetContador: TUniStoredProc
    StoredProcName = 'PRC_GET_CONTADOR'
    Connection = dmConn.conUni
    Left = 256
    Top = 136
  end
  object fxdsPrintPed: TfrxDBDataset
    UserName = 'frxDBDataset1'
    CloseDataSource = False
    BCDToCurrency = False
    DataSetOptions = []
    Left = 384
    Top = 24
  end
  object fxdstPrintLinPed: TfrxDBDataset
    UserName = 'frxDBDataset2'
    CloseDataSource = False
    DataSet = unqryPedidosLineas
    BCDToCurrency = False
    DataSetOptions = []
    Left = 384
    Top = 80
  end
  object unqryTablaG: TUniQuery
    SQLInsert.Strings = (
      'INSERT INTO fza_pedidos'
      
        '  (NRO_PEDIDO, SERIE_PEDIDO, FECHA_PEDIDO, CODIGO_EMPRESA_PEDIDO' +
        ', RAZONSOCIAL_EMPRESA_PEDIDO, NIF_EMPRESA_PEDIDO, MOVIL_EMPRESA_' +
        'PEDIDO, EMAIL_EMPRESA_PEDIDO, DIRECCION1_EMPRESA_PEDIDO, DIRECCI' +
        'ON2_EMPRESA_PEDIDO, POBLACION_EMPRESA_PEDIDO, PROVINCIA_EMPRESA_' +
        'PEDIDO, CODIGO_PAIS_EMPRESA_PEDIDO, NOMBRE_PAIS_EMPRESA_PEDIDO, ' +
        'CPOSTAL_EMPRESA_PEDIDO, ESRETENCIONES_EMPRESA_PEDIDO, GRUPO_ZONA' +
        '_IVA_EMPRESA_PEDIDO, ESREGIMENESPECIALAGRICOLA_EMPRESA_PEDIDO, C' +
        'ODIGO_CLIENTE_PEDIDO, NIF_CLIENTE_PEDIDO, EMAIL_CLIENTE_PEDIDO, ' +
        'REFERENCIAPS_PEDIDO, IDPS_PEDIDO, FECHAPS_PEDIDO, FORMAPAGOPS_PE' +
        'DIDO, TRANSPORTISTAPS_PEDIDO, ESTADOPEDIDOPS_PEDIDO, ESTADOMENSA' +
        'JEPS_PEDIDO, IDHILOPS_MENSAJES_PEDIDO, NOMBRE_CLIENTE_ENVIO_PEDI' +
        'DO, MOVIL_CLIENTE_ENVIO_PEDIDO, DIRECCION1_CLIENTE_ENVIO_PEDIDO,' +
        ' DIRECCION2_CLIENTE_ENVIO_PEDIDO, POBLACION_CLIENTE_ENVIO_PEDIDO' +
        ', PROVINCIA_CLIENTE_ENVIO_PEDIDO, CPOSTAL_CLIENTE_ENVIO_PEDIDO, ' +
        'CODIGO_PAIS_CLIENTE_ENVIO_PEDIDO, NOMBRE_PAIS_CLIENTE_ENVIO_PEDI' +
        'DO, RAZONSOCIAL_CLIENTE_FISCAL_PEDIDO, MOVIL_CLIENTE_FISCAL_PEDI' +
        'DO, EMAIL_CLIENTE_FISCAL_PEDIDO, DIRECCION1_CLIENTE_FISCAL_PEDID' +
        'O, DIRECCION2_CLIENTE_FISCAL_PEDIDO, POBLACION_CLIENTE_FISCAL_PE' +
        'DIDO, PROVINCIA_CLIENTE_FISCAL_PEDIDO, CPOSTAL_CLIENTE_FISCAL_PE' +
        'DIDO, CODIGO_PAIS_CLIENTE_FISCAL_PEDIDO, NOMBRE_PAIS_CLIENTE_FIS' +
        'CAL_PEDIDO, ESIVA_RECARGO_CLIENTE_PEDIDO, ESIVA_EXENTO_CLIENTE_P' +
        'EDIDO, ESREGIMENESPECIALAGRICOLA_CLIENTE_PEDIDO, ESRETENCIONES_C' +
        'LIENTE_PEDIDO, TARIFA_ARTICULO_CLIENTE_PEDIDO, ESIMP_INCL_TARIFA' +
        '_CLIENTE_PEDIDO, ESINTRACOMUNITARIO_CLIENTE_PEDIDO, ESIRPF_IMP_I' +
        'NCL_ZONA_IVA_PEDIDO, ESAPLICA_RE_ZONA_IVA_PEDIDO, ESIVAAGRICOLA_' +
        'ZONA_IVA_PEDIDO, PALABRA_REPORTS_ZONA_IVA_PEDIDO, CODIGO_IVA_PED' +
        'IDO, ESVENTA_ACTIVO_FIJO_PEDIDO, PORCEN_IVAN_PEDIDO, TOTAL_IVAN_' +
        'PEDIDO, PORCEN_REN_PEDIDO, TOTAL_REN_PEDIDO, TOTAL_BASEI_IVAN_PE' +
        'DIDO, PORCEN_IVAR_PEDIDO, TOTAL_IVAR_PEDIDO, PORCEN_RER_PEDIDO, ' +
        'TOTAL_RER_PEDIDO, TOTAL_BASEI_IVAR_PEDIDO, PORCEN_IVAS_PEDIDO, T' +
        'OTAL_IVAS_PEDIDO, PORCEN_RES_PEDIDO, TOTAL_RES_PEDIDO, TOTAL_BAS' +
        'EI_IVAS_PEDIDO, PORCEN_IVAE_PEDIDO, TOTAL_IVAE_PEDIDO, PORCEN_RE' +
        'E_PEDIDO, TOTAL_REE_PEDIDO, TOTAL_BASEI_IVAE_PEDIDO, TOTAL_BASES' +
        '_PEDIDO, TOTAL_IMPUESTOS_PEDIDO, FORMA_PAGO_PEDIDO, PORCEN_RETEN' +
        'CION_PEDIDO, TOTAL_RETENCION_PEDIDO, TOTAL_LIQUIDO_PEDIDO, TOTAL' +
        '_PAGADOREALPS_PEDIDO, NRO_PEDIDO_ABONO_PEDIDO, SERIE_PEDIDO_ABON' +
        'O_PEDIDO, TEXTO_LEGAL_PEDIDO_CLIENTE_PEDIDO, TEXTO_LEGAL_PEDIDO_' +
        'EMPRESA_PEDIDO, DOCUMENTO_PEDIDO, COMENTARIOS_PEDIDO, CONTADOR_L' +
        'INEAS_PEDIDO, ESCREARARTICULOS_PEDIDO, ESDESCRIPCIONES_AMP_PEDID' +
        'O, ESFECHADEENTREGA_PEDIDO, INSTANTEMODIF, INSTANTEALTA, USUARIO' +
        'ALTA, USUARIOMODIF)'
      'VALUES'
      
        '  (:NRO_PEDIDO, :SERIE_PEDIDO, :FECHA_PEDIDO, :CODIGO_EMPRESA_PE' +
        'DIDO, :RAZONSOCIAL_EMPRESA_PEDIDO, :NIF_EMPRESA_PEDIDO, :MOVIL_E' +
        'MPRESA_PEDIDO, :EMAIL_EMPRESA_PEDIDO, :DIRECCION1_EMPRESA_PEDIDO' +
        ', :DIRECCION2_EMPRESA_PEDIDO, :POBLACION_EMPRESA_PEDIDO, :PROVIN' +
        'CIA_EMPRESA_PEDIDO, :CODIGO_PAIS_EMPRESA_PEDIDO, :NOMBRE_PAIS_EM' +
        'PRESA_PEDIDO, :CPOSTAL_EMPRESA_PEDIDO, :ESRETENCIONES_EMPRESA_PE' +
        'DIDO, :GRUPO_ZONA_IVA_EMPRESA_PEDIDO, :ESREGIMENESPECIALAGRICOLA' +
        '_EMPRESA_PEDIDO, :CODIGO_CLIENTE_PEDIDO, :NIF_CLIENTE_PEDIDO, :E' +
        'MAIL_CLIENTE_PEDIDO, :REFERENCIAPS_PEDIDO, :IDPS_PEDIDO, :FECHAP' +
        'S_PEDIDO, :FORMAPAGOPS_PEDIDO, :TRANSPORTISTAPS_PEDIDO, :ESTADOP' +
        'EDIDOPS_PEDIDO, :ESTADOMENSAJEPS_PEDIDO, :IDHILOPS_MENSAJES_PEDI' +
        'DO, :NOMBRE_CLIENTE_ENVIO_PEDIDO, :MOVIL_CLIENTE_ENVIO_PEDIDO, :' +
        'DIRECCION1_CLIENTE_ENVIO_PEDIDO, :DIRECCION2_CLIENTE_ENVIO_PEDID' +
        'O, :POBLACION_CLIENTE_ENVIO_PEDIDO, :PROVINCIA_CLIENTE_ENVIO_PED' +
        'IDO, :CPOSTAL_CLIENTE_ENVIO_PEDIDO, :CODIGO_PAIS_CLIENTE_ENVIO_P' +
        'EDIDO, :NOMBRE_PAIS_CLIENTE_ENVIO_PEDIDO, :RAZONSOCIAL_CLIENTE_F' +
        'ISCAL_PEDIDO, :MOVIL_CLIENTE_FISCAL_PEDIDO, :EMAIL_CLIENTE_FISCA' +
        'L_PEDIDO, :DIRECCION1_CLIENTE_FISCAL_PEDIDO, :DIRECCION2_CLIENTE' +
        '_FISCAL_PEDIDO, :POBLACION_CLIENTE_FISCAL_PEDIDO, :PROVINCIA_CLI' +
        'ENTE_FISCAL_PEDIDO, :CPOSTAL_CLIENTE_FISCAL_PEDIDO, :CODIGO_PAIS' +
        '_CLIENTE_FISCAL_PEDIDO, :NOMBRE_PAIS_CLIENTE_FISCAL_PEDIDO, :ESI' +
        'VA_RECARGO_CLIENTE_PEDIDO, :ESIVA_EXENTO_CLIENTE_PEDIDO, :ESREGI' +
        'MENESPECIALAGRICOLA_CLIENTE_PEDIDO, :ESRETENCIONES_CLIENTE_PEDID' +
        'O, :TARIFA_ARTICULO_CLIENTE_PEDIDO, :ESIMP_INCL_TARIFA_CLIENTE_P' +
        'EDIDO, :ESINTRACOMUNITARIO_CLIENTE_PEDIDO, :ESIRPF_IMP_INCL_ZONA' +
        '_IVA_PEDIDO, :ESAPLICA_RE_ZONA_IVA_PEDIDO, :ESIVAAGRICOLA_ZONA_I' +
        'VA_PEDIDO, :PALABRA_REPORTS_ZONA_IVA_PEDIDO, :CODIGO_IVA_PEDIDO,' +
        ' :ESVENTA_ACTIVO_FIJO_PEDIDO, :PORCEN_IVAN_PEDIDO, :TOTAL_IVAN_P' +
        'EDIDO, :PORCEN_REN_PEDIDO, :TOTAL_REN_PEDIDO, :TOTAL_BASEI_IVAN_' +
        'PEDIDO, :PORCEN_IVAR_PEDIDO, :TOTAL_IVAR_PEDIDO, :PORCEN_RER_PED' +
        'IDO, :TOTAL_RER_PEDIDO, :TOTAL_BASEI_IVAR_PEDIDO, :PORCEN_IVAS_P' +
        'EDIDO, :TOTAL_IVAS_PEDIDO, :PORCEN_RES_PEDIDO, :TOTAL_RES_PEDIDO' +
        ', :TOTAL_BASEI_IVAS_PEDIDO, :PORCEN_IVAE_PEDIDO, :TOTAL_IVAE_PED' +
        'IDO, :PORCEN_REE_PEDIDO, :TOTAL_REE_PEDIDO, :TOTAL_BASEI_IVAE_PE' +
        'DIDO, :TOTAL_BASES_PEDIDO, :TOTAL_IMPUESTOS_PEDIDO, :FORMA_PAGO_' +
        'PEDIDO, :PORCEN_RETENCION_PEDIDO, :TOTAL_RETENCION_PEDIDO, :TOTA' +
        'L_LIQUIDO_PEDIDO, :TOTAL_PAGADOREALPS_PEDIDO, :NRO_PEDIDO_ABONO_' +
        'PEDIDO, :SERIE_PEDIDO_ABONO_PEDIDO, :TEXTO_LEGAL_PEDIDO_CLIENTE_' +
        'PEDIDO, :TEXTO_LEGAL_PEDIDO_EMPRESA_PEDIDO, :DOCUMENTO_PEDIDO, :' +
        'COMENTARIOS_PEDIDO, :CONTADOR_LINEAS_PEDIDO, :ESCREARARTICULOS_P' +
        'EDIDO, :ESDESCRIPCIONES_AMP_PEDIDO, :ESFECHADEENTREGA_PEDIDO, :I' +
        'NSTANTEMODIF, :INSTANTEALTA, :USUARIOALTA, :USUARIOMODIF)')
    SQLDelete.Strings = (
      'DELETE FROM fza_pedidos'
      'WHERE'
      
        '  NRO_PEDIDO = :Old_NRO_PEDIDO AND SERIE_PEDIDO = :Old_SERIE_PED' +
        'IDO')
    SQLUpdate.Strings = (
      'UPDATE fza_pedidos'
      'SET'
      
        '  NRO_PEDIDO = :NRO_PEDIDO, SERIE_PEDIDO = :SERIE_PEDIDO, FECHA_' +
        'PEDIDO = :FECHA_PEDIDO, CODIGO_EMPRESA_PEDIDO = :CODIGO_EMPRESA_' +
        'PEDIDO, RAZONSOCIAL_EMPRESA_PEDIDO = :RAZONSOCIAL_EMPRESA_PEDIDO' +
        ', NIF_EMPRESA_PEDIDO = :NIF_EMPRESA_PEDIDO, MOVIL_EMPRESA_PEDIDO' +
        ' = :MOVIL_EMPRESA_PEDIDO, EMAIL_EMPRESA_PEDIDO = :EMAIL_EMPRESA_' +
        'PEDIDO, DIRECCION1_EMPRESA_PEDIDO = :DIRECCION1_EMPRESA_PEDIDO, ' +
        'DIRECCION2_EMPRESA_PEDIDO = :DIRECCION2_EMPRESA_PEDIDO, POBLACIO' +
        'N_EMPRESA_PEDIDO = :POBLACION_EMPRESA_PEDIDO, PROVINCIA_EMPRESA_' +
        'PEDIDO = :PROVINCIA_EMPRESA_PEDIDO, CODIGO_PAIS_EMPRESA_PEDIDO =' +
        ' :CODIGO_PAIS_EMPRESA_PEDIDO, NOMBRE_PAIS_EMPRESA_PEDIDO = :NOMB' +
        'RE_PAIS_EMPRESA_PEDIDO, CPOSTAL_EMPRESA_PEDIDO = :CPOSTAL_EMPRES' +
        'A_PEDIDO, ESRETENCIONES_EMPRESA_PEDIDO = :ESRETENCIONES_EMPRESA_' +
        'PEDIDO, GRUPO_ZONA_IVA_EMPRESA_PEDIDO = :GRUPO_ZONA_IVA_EMPRESA_' +
        'PEDIDO, ESREGIMENESPECIALAGRICOLA_EMPRESA_PEDIDO = :ESREGIMENESP' +
        'ECIALAGRICOLA_EMPRESA_PEDIDO, CODIGO_CLIENTE_PEDIDO = :CODIGO_CL' +
        'IENTE_PEDIDO, NIF_CLIENTE_PEDIDO = :NIF_CLIENTE_PEDIDO, EMAIL_CL' +
        'IENTE_PEDIDO = :EMAIL_CLIENTE_PEDIDO, REFERENCIAPS_PEDIDO = :REF' +
        'ERENCIAPS_PEDIDO, IDPS_PEDIDO = :IDPS_PEDIDO, FECHAPS_PEDIDO = :' +
        'FECHAPS_PEDIDO, FORMAPAGOPS_PEDIDO = :FORMAPAGOPS_PEDIDO, TRANSP' +
        'ORTISTAPS_PEDIDO = :TRANSPORTISTAPS_PEDIDO, ESTADOPEDIDOPS_PEDID' +
        'O = :ESTADOPEDIDOPS_PEDIDO, ESTADOMENSAJEPS_PEDIDO = :ESTADOMENS' +
        'AJEPS_PEDIDO, IDHILOPS_MENSAJES_PEDIDO = :IDHILOPS_MENSAJES_PEDI' +
        'DO, NOMBRE_CLIENTE_ENVIO_PEDIDO = :NOMBRE_CLIENTE_ENVIO_PEDIDO, ' +
        'MOVIL_CLIENTE_ENVIO_PEDIDO = :MOVIL_CLIENTE_ENVIO_PEDIDO, DIRECC' +
        'ION1_CLIENTE_ENVIO_PEDIDO = :DIRECCION1_CLIENTE_ENVIO_PEDIDO, DI' +
        'RECCION2_CLIENTE_ENVIO_PEDIDO = :DIRECCION2_CLIENTE_ENVIO_PEDIDO' +
        ', POBLACION_CLIENTE_ENVIO_PEDIDO = :POBLACION_CLIENTE_ENVIO_PEDI' +
        'DO, PROVINCIA_CLIENTE_ENVIO_PEDIDO = :PROVINCIA_CLIENTE_ENVIO_PE' +
        'DIDO, CPOSTAL_CLIENTE_ENVIO_PEDIDO = :CPOSTAL_CLIENTE_ENVIO_PEDI' +
        'DO, CODIGO_PAIS_CLIENTE_ENVIO_PEDIDO = :CODIGO_PAIS_CLIENTE_ENVI' +
        'O_PEDIDO, NOMBRE_PAIS_CLIENTE_ENVIO_PEDIDO = :NOMBRE_PAIS_CLIENT' +
        'E_ENVIO_PEDIDO, RAZONSOCIAL_CLIENTE_FISCAL_PEDIDO = :RAZONSOCIAL' +
        '_CLIENTE_FISCAL_PEDIDO, MOVIL_CLIENTE_FISCAL_PEDIDO = :MOVIL_CLI' +
        'ENTE_FISCAL_PEDIDO, EMAIL_CLIENTE_FISCAL_PEDIDO = :EMAIL_CLIENTE' +
        '_FISCAL_PEDIDO, DIRECCION1_CLIENTE_FISCAL_PEDIDO = :DIRECCION1_C' +
        'LIENTE_FISCAL_PEDIDO, DIRECCION2_CLIENTE_FISCAL_PEDIDO = :DIRECC' +
        'ION2_CLIENTE_FISCAL_PEDIDO, POBLACION_CLIENTE_FISCAL_PEDIDO = :P' +
        'OBLACION_CLIENTE_FISCAL_PEDIDO, PROVINCIA_CLIENTE_FISCAL_PEDIDO ' +
        '= :PROVINCIA_CLIENTE_FISCAL_PEDIDO, CPOSTAL_CLIENTE_FISCAL_PEDID' +
        'O = :CPOSTAL_CLIENTE_FISCAL_PEDIDO, CODIGO_PAIS_CLIENTE_FISCAL_P' +
        'EDIDO = :CODIGO_PAIS_CLIENTE_FISCAL_PEDIDO, NOMBRE_PAIS_CLIENTE_' +
        'FISCAL_PEDIDO = :NOMBRE_PAIS_CLIENTE_FISCAL_PEDIDO, ESIVA_RECARG' +
        'O_CLIENTE_PEDIDO = :ESIVA_RECARGO_CLIENTE_PEDIDO, ESIVA_EXENTO_C' +
        'LIENTE_PEDIDO = :ESIVA_EXENTO_CLIENTE_PEDIDO, ESREGIMENESPECIALA' +
        'GRICOLA_CLIENTE_PEDIDO = :ESREGIMENESPECIALAGRICOLA_CLIENTE_PEDI' +
        'DO, ESRETENCIONES_CLIENTE_PEDIDO = :ESRETENCIONES_CLIENTE_PEDIDO' +
        ', TARIFA_ARTICULO_CLIENTE_PEDIDO = :TARIFA_ARTICULO_CLIENTE_PEDI' +
        'DO, ESIMP_INCL_TARIFA_CLIENTE_PEDIDO = :ESIMP_INCL_TARIFA_CLIENT' +
        'E_PEDIDO, ESINTRACOMUNITARIO_CLIENTE_PEDIDO = :ESINTRACOMUNITARI' +
        'O_CLIENTE_PEDIDO, ESIRPF_IMP_INCL_ZONA_IVA_PEDIDO = :ESIRPF_IMP_' +
        'INCL_ZONA_IVA_PEDIDO, ESAPLICA_RE_ZONA_IVA_PEDIDO = :ESAPLICA_RE' +
        '_ZONA_IVA_PEDIDO, ESIVAAGRICOLA_ZONA_IVA_PEDIDO = :ESIVAAGRICOLA' +
        '_ZONA_IVA_PEDIDO, PALABRA_REPORTS_ZONA_IVA_PEDIDO = :PALABRA_REP' +
        'ORTS_ZONA_IVA_PEDIDO, CODIGO_IVA_PEDIDO = :CODIGO_IVA_PEDIDO, ES' +
        'VENTA_ACTIVO_FIJO_PEDIDO = :ESVENTA_ACTIVO_FIJO_PEDIDO, PORCEN_I' +
        'VAN_PEDIDO = :PORCEN_IVAN_PEDIDO, TOTAL_IVAN_PEDIDO = :TOTAL_IVA' +
        'N_PEDIDO, PORCEN_REN_PEDIDO = :PORCEN_REN_PEDIDO, TOTAL_REN_PEDI' +
        'DO = :TOTAL_REN_PEDIDO, TOTAL_BASEI_IVAN_PEDIDO = :TOTAL_BASEI_I' +
        'VAN_PEDIDO, PORCEN_IVAR_PEDIDO = :PORCEN_IVAR_PEDIDO, TOTAL_IVAR' +
        '_PEDIDO = :TOTAL_IVAR_PEDIDO, PORCEN_RER_PEDIDO = :PORCEN_RER_PE' +
        'DIDO, TOTAL_RER_PEDIDO = :TOTAL_RER_PEDIDO, TOTAL_BASEI_IVAR_PED' +
        'IDO = :TOTAL_BASEI_IVAR_PEDIDO, PORCEN_IVAS_PEDIDO = :PORCEN_IVA' +
        'S_PEDIDO, TOTAL_IVAS_PEDIDO = :TOTAL_IVAS_PEDIDO, PORCEN_RES_PED' +
        'IDO = :PORCEN_RES_PEDIDO, TOTAL_RES_PEDIDO = :TOTAL_RES_PEDIDO, ' +
        'TOTAL_BASEI_IVAS_PEDIDO = :TOTAL_BASEI_IVAS_PEDIDO, PORCEN_IVAE_' +
        'PEDIDO = :PORCEN_IVAE_PEDIDO, TOTAL_IVAE_PEDIDO = :TOTAL_IVAE_PE' +
        'DIDO, PORCEN_REE_PEDIDO = :PORCEN_REE_PEDIDO, TOTAL_REE_PEDIDO =' +
        ' :TOTAL_REE_PEDIDO, TOTAL_BASEI_IVAE_PEDIDO = :TOTAL_BASEI_IVAE_' +
        'PEDIDO, TOTAL_BASES_PEDIDO = :TOTAL_BASES_PEDIDO, TOTAL_IMPUESTO' +
        'S_PEDIDO = :TOTAL_IMPUESTOS_PEDIDO, FORMA_PAGO_PEDIDO = :FORMA_P' +
        'AGO_PEDIDO, PORCEN_RETENCION_PEDIDO = :PORCEN_RETENCION_PEDIDO, ' +
        'TOTAL_RETENCION_PEDIDO = :TOTAL_RETENCION_PEDIDO, TOTAL_LIQUIDO_' +
        'PEDIDO = :TOTAL_LIQUIDO_PEDIDO, TOTAL_PAGADOREALPS_PEDIDO = :TOT' +
        'AL_PAGADOREALPS_PEDIDO, NRO_PEDIDO_ABONO_PEDIDO = :NRO_PEDIDO_AB' +
        'ONO_PEDIDO, SERIE_PEDIDO_ABONO_PEDIDO = :SERIE_PEDIDO_ABONO_PEDI' +
        'DO, TEXTO_LEGAL_PEDIDO_CLIENTE_PEDIDO = :TEXTO_LEGAL_PEDIDO_CLIE' +
        'NTE_PEDIDO, TEXTO_LEGAL_PEDIDO_EMPRESA_PEDIDO = :TEXTO_LEGAL_PED' +
        'IDO_EMPRESA_PEDIDO, DOCUMENTO_PEDIDO = :DOCUMENTO_PEDIDO, COMENT' +
        'ARIOS_PEDIDO = :COMENTARIOS_PEDIDO, CONTADOR_LINEAS_PEDIDO = :CO' +
        'NTADOR_LINEAS_PEDIDO, ESCREARARTICULOS_PEDIDO = :ESCREARARTICULO' +
        'S_PEDIDO, ESDESCRIPCIONES_AMP_PEDIDO = :ESDESCRIPCIONES_AMP_PEDI' +
        'DO, ESFECHADEENTREGA_PEDIDO = :ESFECHADEENTREGA_PEDIDO, INSTANTE' +
        'MODIF = :INSTANTEMODIF, INSTANTEALTA = :INSTANTEALTA, USUARIOALT' +
        'A = :USUARIOALTA, USUARIOMODIF = :USUARIOMODIF'
      'WHERE'
      
        '  NRO_PEDIDO = :Old_NRO_PEDIDO AND SERIE_PEDIDO = :Old_SERIE_PED' +
        'IDO')
    SQLLock.Strings = (
      
        'SELECT NRO_PEDIDO, SERIE_PEDIDO, FECHA_PEDIDO, CODIGO_EMPRESA_PE' +
        'DIDO, RAZONSOCIAL_EMPRESA_PEDIDO, NIF_EMPRESA_PEDIDO, MOVIL_EMPR' +
        'ESA_PEDIDO, EMAIL_EMPRESA_PEDIDO, DIRECCION1_EMPRESA_PEDIDO, DIR' +
        'ECCION2_EMPRESA_PEDIDO, POBLACION_EMPRESA_PEDIDO, PROVINCIA_EMPR' +
        'ESA_PEDIDO, CODIGO_PAIS_EMPRESA_PEDIDO, NOMBRE_PAIS_EMPRESA_PEDI' +
        'DO, CPOSTAL_EMPRESA_PEDIDO, ESRETENCIONES_EMPRESA_PEDIDO, GRUPO_' +
        'ZONA_IVA_EMPRESA_PEDIDO, ESREGIMENESPECIALAGRICOLA_EMPRESA_PEDID' +
        'O, CODIGO_CLIENTE_PEDIDO, NIF_CLIENTE_PEDIDO, EMAIL_CLIENTE_PEDI' +
        'DO, REFERENCIAPS_PEDIDO, IDPS_PEDIDO, FECHAPS_PEDIDO, FORMAPAGOP' +
        'S_PEDIDO, TRANSPORTISTAPS_PEDIDO, ESTADOPEDIDOPS_PEDIDO, ESTADOM' +
        'ENSAJEPS_PEDIDO, IDHILOPS_MENSAJES_PEDIDO, NOMBRE_CLIENTE_ENVIO_' +
        'PEDIDO, MOVIL_CLIENTE_ENVIO_PEDIDO, DIRECCION1_CLIENTE_ENVIO_PED' +
        'IDO, DIRECCION2_CLIENTE_ENVIO_PEDIDO, POBLACION_CLIENTE_ENVIO_PE' +
        'DIDO, PROVINCIA_CLIENTE_ENVIO_PEDIDO, CPOSTAL_CLIENTE_ENVIO_PEDI' +
        'DO, CODIGO_PAIS_CLIENTE_ENVIO_PEDIDO, NOMBRE_PAIS_CLIENTE_ENVIO_' +
        'PEDIDO, RAZONSOCIAL_CLIENTE_FISCAL_PEDIDO, MOVIL_CLIENTE_FISCAL_' +
        'PEDIDO, EMAIL_CLIENTE_FISCAL_PEDIDO, DIRECCION1_CLIENTE_FISCAL_P' +
        'EDIDO, DIRECCION2_CLIENTE_FISCAL_PEDIDO, POBLACION_CLIENTE_FISCA' +
        'L_PEDIDO, PROVINCIA_CLIENTE_FISCAL_PEDIDO, CPOSTAL_CLIENTE_FISCA' +
        'L_PEDIDO, CODIGO_PAIS_CLIENTE_FISCAL_PEDIDO, NOMBRE_PAIS_CLIENTE' +
        '_FISCAL_PEDIDO, ESIVA_RECARGO_CLIENTE_PEDIDO, ESIVA_EXENTO_CLIEN' +
        'TE_PEDIDO, ESREGIMENESPECIALAGRICOLA_CLIENTE_PEDIDO, ESRETENCION' +
        'ES_CLIENTE_PEDIDO, TARIFA_ARTICULO_CLIENTE_PEDIDO, ESIMP_INCL_TA' +
        'RIFA_CLIENTE_PEDIDO, ESINTRACOMUNITARIO_CLIENTE_PEDIDO, ESIRPF_I' +
        'MP_INCL_ZONA_IVA_PEDIDO, ESAPLICA_RE_ZONA_IVA_PEDIDO, ESIVAAGRIC' +
        'OLA_ZONA_IVA_PEDIDO, PALABRA_REPORTS_ZONA_IVA_PEDIDO, CODIGO_IVA' +
        '_PEDIDO, ESVENTA_ACTIVO_FIJO_PEDIDO, PORCEN_IVAN_PEDIDO, TOTAL_I' +
        'VAN_PEDIDO, PORCEN_REN_PEDIDO, TOTAL_REN_PEDIDO, TOTAL_BASEI_IVA' +
        'N_PEDIDO, PORCEN_IVAR_PEDIDO, TOTAL_IVAR_PEDIDO, PORCEN_RER_PEDI' +
        'DO, TOTAL_RER_PEDIDO, TOTAL_BASEI_IVAR_PEDIDO, PORCEN_IVAS_PEDID' +
        'O, TOTAL_IVAS_PEDIDO, PORCEN_RES_PEDIDO, TOTAL_RES_PEDIDO, TOTAL' +
        '_BASEI_IVAS_PEDIDO, PORCEN_IVAE_PEDIDO, TOTAL_IVAE_PEDIDO, PORCE' +
        'N_REE_PEDIDO, TOTAL_REE_PEDIDO, TOTAL_BASEI_IVAE_PEDIDO, TOTAL_B' +
        'ASES_PEDIDO, TOTAL_IMPUESTOS_PEDIDO, FORMA_PAGO_PEDIDO, PORCEN_R' +
        'ETENCION_PEDIDO, TOTAL_RETENCION_PEDIDO, TOTAL_LIQUIDO_PEDIDO, T' +
        'OTAL_PAGADOREALPS_PEDIDO, NRO_PEDIDO_ABONO_PEDIDO, SERIE_PEDIDO_' +
        'ABONO_PEDIDO, TEXTO_LEGAL_PEDIDO_CLIENTE_PEDIDO, TEXTO_LEGAL_PED' +
        'IDO_EMPRESA_PEDIDO, DOCUMENTO_PEDIDO, COMENTARIOS_PEDIDO, CONTAD' +
        'OR_LINEAS_PEDIDO, ESCREARARTICULOS_PEDIDO, ESDESCRIPCIONES_AMP_P' +
        'EDIDO, ESFECHADEENTREGA_PEDIDO, INSTANTEMODIF, INSTANTEALTA, USU' +
        'ARIOALTA, USUARIOMODIF FROM fza_pedidos'
      'WHERE'
      
        '  NRO_PEDIDO = :Old_NRO_PEDIDO AND SERIE_PEDIDO = :Old_SERIE_PED' +
        'IDO'
      'FOR UPDATE')
    SQLRefresh.Strings = (
      
        'SELECT NRO_PEDIDO, SERIE_PEDIDO, FECHA_PEDIDO, CODIGO_EMPRESA_PE' +
        'DIDO, RAZONSOCIAL_EMPRESA_PEDIDO, NIF_EMPRESA_PEDIDO, MOVIL_EMPR' +
        'ESA_PEDIDO, EMAIL_EMPRESA_PEDIDO, DIRECCION1_EMPRESA_PEDIDO, DIR' +
        'ECCION2_EMPRESA_PEDIDO, POBLACION_EMPRESA_PEDIDO, PROVINCIA_EMPR' +
        'ESA_PEDIDO, CODIGO_PAIS_EMPRESA_PEDIDO, NOMBRE_PAIS_EMPRESA_PEDI' +
        'DO, CPOSTAL_EMPRESA_PEDIDO, ESRETENCIONES_EMPRESA_PEDIDO, GRUPO_' +
        'ZONA_IVA_EMPRESA_PEDIDO, ESREGIMENESPECIALAGRICOLA_EMPRESA_PEDID' +
        'O, CODIGO_CLIENTE_PEDIDO, NIF_CLIENTE_PEDIDO, EMAIL_CLIENTE_PEDI' +
        'DO, REFERENCIAPS_PEDIDO, IDPS_PEDIDO, FECHAPS_PEDIDO, FORMAPAGOP' +
        'S_PEDIDO, TRANSPORTISTAPS_PEDIDO, ESTADOPEDIDOPS_PEDIDO, ESTADOM' +
        'ENSAJEPS_PEDIDO, IDHILOPS_MENSAJES_PEDIDO, NOMBRE_CLIENTE_ENVIO_' +
        'PEDIDO, MOVIL_CLIENTE_ENVIO_PEDIDO, DIRECCION1_CLIENTE_ENVIO_PED' +
        'IDO, DIRECCION2_CLIENTE_ENVIO_PEDIDO, POBLACION_CLIENTE_ENVIO_PE' +
        'DIDO, PROVINCIA_CLIENTE_ENVIO_PEDIDO, CPOSTAL_CLIENTE_ENVIO_PEDI' +
        'DO, CODIGO_PAIS_CLIENTE_ENVIO_PEDIDO, NOMBRE_PAIS_CLIENTE_ENVIO_' +
        'PEDIDO, RAZONSOCIAL_CLIENTE_FISCAL_PEDIDO, MOVIL_CLIENTE_FISCAL_' +
        'PEDIDO, EMAIL_CLIENTE_FISCAL_PEDIDO, DIRECCION1_CLIENTE_FISCAL_P' +
        'EDIDO, DIRECCION2_CLIENTE_FISCAL_PEDIDO, POBLACION_CLIENTE_FISCA' +
        'L_PEDIDO, PROVINCIA_CLIENTE_FISCAL_PEDIDO, CPOSTAL_CLIENTE_FISCA' +
        'L_PEDIDO, CODIGO_PAIS_CLIENTE_FISCAL_PEDIDO, NOMBRE_PAIS_CLIENTE' +
        '_FISCAL_PEDIDO, ESIVA_RECARGO_CLIENTE_PEDIDO, ESIVA_EXENTO_CLIEN' +
        'TE_PEDIDO, ESREGIMENESPECIALAGRICOLA_CLIENTE_PEDIDO, ESRETENCION' +
        'ES_CLIENTE_PEDIDO, TARIFA_ARTICULO_CLIENTE_PEDIDO, ESIMP_INCL_TA' +
        'RIFA_CLIENTE_PEDIDO, ESINTRACOMUNITARIO_CLIENTE_PEDIDO, ESIRPF_I' +
        'MP_INCL_ZONA_IVA_PEDIDO, ESAPLICA_RE_ZONA_IVA_PEDIDO, ESIVAAGRIC' +
        'OLA_ZONA_IVA_PEDIDO, PALABRA_REPORTS_ZONA_IVA_PEDIDO, CODIGO_IVA' +
        '_PEDIDO, ESVENTA_ACTIVO_FIJO_PEDIDO, PORCEN_IVAN_PEDIDO, TOTAL_I' +
        'VAN_PEDIDO, PORCEN_REN_PEDIDO, TOTAL_REN_PEDIDO, TOTAL_BASEI_IVA' +
        'N_PEDIDO, PORCEN_IVAR_PEDIDO, TOTAL_IVAR_PEDIDO, PORCEN_RER_PEDI' +
        'DO, TOTAL_RER_PEDIDO, TOTAL_BASEI_IVAR_PEDIDO, PORCEN_IVAS_PEDID' +
        'O, TOTAL_IVAS_PEDIDO, PORCEN_RES_PEDIDO, TOTAL_RES_PEDIDO, TOTAL' +
        '_BASEI_IVAS_PEDIDO, PORCEN_IVAE_PEDIDO, TOTAL_IVAE_PEDIDO, PORCE' +
        'N_REE_PEDIDO, TOTAL_REE_PEDIDO, TOTAL_BASEI_IVAE_PEDIDO, TOTAL_B' +
        'ASES_PEDIDO, TOTAL_IMPUESTOS_PEDIDO, FORMA_PAGO_PEDIDO, PORCEN_R' +
        'ETENCION_PEDIDO, TOTAL_RETENCION_PEDIDO, TOTAL_LIQUIDO_PEDIDO, T' +
        'OTAL_PAGADOREALPS_PEDIDO, NRO_PEDIDO_ABONO_PEDIDO, SERIE_PEDIDO_' +
        'ABONO_PEDIDO, TEXTO_LEGAL_PEDIDO_CLIENTE_PEDIDO, TEXTO_LEGAL_PED' +
        'IDO_EMPRESA_PEDIDO, DOCUMENTO_PEDIDO, COMENTARIOS_PEDIDO, CONTAD' +
        'OR_LINEAS_PEDIDO, ESCREARARTICULOS_PEDIDO, ESDESCRIPCIONES_AMP_P' +
        'EDIDO, ESFECHADEENTREGA_PEDIDO, INSTANTEMODIF, INSTANTEALTA, USU' +
        'ARIOALTA, USUARIOMODIF FROM fza_pedidos'
      'WHERE'
      '  NRO_PEDIDO = :NRO_PEDIDO AND SERIE_PEDIDO = :SERIE_PEDIDO')
    SQLRecCount.Strings = (
      'SELECT COUNT(*) FROM fza_pedidos')
    Connection = dmConn.conUni
    SQL.Strings = (
      'select * from vi_pedidos')
    Active = True
    Left = 48
    Top = 24
  end
  object unqryPerfiles: TUniQuery
    Connection = dmConn.conUni
    SQL.Strings = (
      'select *'
      'from fza_usuarios_perfiles')
    Left = 496
    Top = 96
  end
  object dsPerfiles: TDataSource
    DataSet = unqryPerfiles
    Left = 495
    Top = 32
  end
end
