inherited dmDepositosCliente: TdmDepositosCliente
  inherited unqryTablaG: TUniQuery
    SQLInsert.Strings = (
      'INSERT INTO `fza_depositos_cliente`'
      '  (`ID_DEPOSITO_DEP`, `CODIGO_EMPRESA_DEP`, `CODIGO_CLIENTE_DEP`, `CODIGO_ARTICULO_DEP`, `CODIGO_UNIDAD_DEP`, `PRECIO_VENTA_DEP`, `IMPORTE_ANTICIPO_DEP`, `ESTADO_DEP`, `FECHA_CREACION_DEP`, `INSTANTEMODIF`, `INSTANTEALTA`, `USUARIOALTA`, `USUARIOMODIF`, `TIPO_IVA_DEP`, `PORCEN_IVA_DEP`, `ESIMP_INCL_DEP`, `CANTIDAD_PENDIENTE_DEP`, `FECHA_ENTREGA_DEP`)'
      'VALUES'
      '  (:`ID_DEPOSITO_DEP`, :`CODIGO_EMPRESA_DEP`, :`CODIGO_CLIENTE_DEP`, :`CODIGO_ARTICULO_DEP`, :`CODIGO_UNIDAD_DEP`, :`PRECIO_VENTA_DEP`, :`IMPORTE_ANTICIPO_DEP`, :`ESTADO_DEP`, :`FECHA_CREACION_DEP`, :`INSTANTEMODIF`, :`INSTANTEALTA`, :`USUARIOALTA`, :`USUARIOMODIF`, :`TIPO_IVA_DEP`, :`PORCEN_IVA_DEP`, :`ESIMP_INCL_DEP`, :`CANTIDAD_PENDIENTE_DEP`, :`FECHA_ENTREGA_DEP`)')
    SQLDelete.Strings = (
      'DELETE FROM `fza_depositos_cliente`'
      'WHERE'
      '  `ID_DEPOSITO_DEP` = :`Old_ID_DEPOSITO_DEP`')
    SQLUpdate.Strings = (
      'UPDATE `fza_depositos_cliente`'
      'SET'
      '  `ID_DEPOSITO_DEP` = :`ID_DEPOSITO_DEP`, `CODIGO_EMPRESA_DEP` = :`CODIGO_EMPRESA_DEP`, `CODIGO_CLIENTE_DEP` = :`CODIGO_CLIENTE_DEP`, `CODIGO_ARTICULO_DEP` = :`CODIGO_ARTICULO_DEP`, `CODIGO_UNIDAD_DEP` = :`CODIGO_UNIDAD_DEP`, `PRECIO_VENTA_DEP` = :`PRECIO_VENTA_DEP`, `IMPORTE_ANTICIPO_DEP` = :`IMPORTE_ANTICIPO_DEP`, `ESTADO_DEP` = :`ESTADO_DEP`, `FECHA_CREACION_DEP` = :`FECHA_CREACION_DEP`, `INSTANTEMODIF` = :`INSTANTEMODIF`, `INSTANTEALTA` = :`INSTANTEALTA`, `USUARIOALTA` = :`USUARIOALTA`, `USUARIOMODIF` = :`USUARIOMODIF`, `TIPO_IVA_DEP` = :`TIPO_IVA_DEP`, `PORCEN_IVA_DEP` = :`PORCEN_IVA_DEP`, `ESIMP_INCL_DEP` = :`ESIMP_INCL_DEP`, `CANTIDAD_PENDIENTE_DEP` = :`CANTIDAD_PENDIENTE_DEP`, `FECHA_ENTREGA_DEP` = :`FECHA_ENTREGA_DEP`'
      'WHERE'
      '  `ID_DEPOSITO_DEP` = :`Old_ID_DEPOSITO_DEP`')
    SQLLock.Strings = (
      'SELECT * FROM `fza_depositos_cliente`'
      'WHERE'
      '  `ID_DEPOSITO_DEP` = :`Old_ID_DEPOSITO_DEP`'
      'FOR UPDATE')
    SQLRefresh.Strings = (
      'SELECT * FROM `fza_depositos_cliente`'
      'WHERE'
      '  `ID_DEPOSITO_DEP` = :`ID_DEPOSITO_DEP`')
    SQLRecCount.Strings = (
      'SELECT COUNT(*) FROM fza_depositos_cliente')
    Connection = dmConn.conUni
    SQL.Strings = (
      'SELECT *'
      'FROM fza_depositos_cliente'
      'ORDER BY FECHA_CREACION_DEP DESC'
      '')
    Active = True
    Left = 24
  end
end
