inherited dmEmpresas: TdmEmpresas
  Height = 168
  Width = 970
  PixelsPerInch = 120
  inherited unqryTablaG: TUniQuery
    SQLInsert.Strings = (
      'INSERT INTO fza_empresas'
      
        '  (CODIGO_EMP_EMP, ORDEN_EMP, ESACTIVO_EMP, RAZON_SOCIAL_EMP, NIF_EMP, MOVIL_EMP, EMAIL_EMP, DIRECCION1_EMP, DIRECCION2_EMP, CODIGO_POSTAL_EMP, POBLACION_EMP, PROVINCIA_EMP, CODIGO_PAI_EMP, NOMBRE_PAI' +
        '_EMP, IBAN_EMP, GRUPO_ZONA_IVA_EMP, ESRETENCIONES_EMP, ESREGIMENESPECIALAGRICOLA_EMP, CODIGO_CERTIFICADO_EMP, TITULAR_CERTIFICADO_EMP, TIPO_CERTIFICADO_EMP, FECHA_DESDE_CERTIFICADO_EMP, FECHA_HASTA_CE' +
        'RTIFICADO_EMP, TEXTO_LEGAL_FACTURA_EMP, INSTANTE_MODIF, INSTANTE_ALTA, USUARIO_ALTA, USUARIO_MODIF)'
      'VALUES'
      
        '  (:CODIGO_EMP_EMP, :ORDEN_EMP, :ESACTIVO_EMP, :RAZON_SOCIAL_EMP, :NIF_EMP, :MOVIL_EMP, :EMAIL_EMP, :DIRECCION1_EMP, :DIRECCION2_EMP, :CODIGO_POSTAL_EMP, :POBLACION_EMP, :PROVINCIA_EMP, :CODIGO_PAI_EM' +
        'P, :NOMBRE_PAI_EMP, :IBAN_EMP, :GRUPO_ZONA_IVA_EMP, :ESRETENCIONES_EMP, :ESREGIMENESPECIALAGRICOLA_EMP, :CODIGO_CERTIFICADO_EMP, :TITULAR_CERTIFICADO_EMP, :TIPO_CERTIFICADO_EMP, :FECHA_DESDE_CERTIFICA' +
        'DO_EMP, :FECHA_HASTA_CERTIFICADO_EMP, :TEXTO_LEGAL_FACTURA_EMP, :INSTANTE_MODIF, :INSTANTE_ALTA, :USUARIO_ALTA, :USUARIO_MODIF)')
    SQLDelete.Strings = (
      'DELETE FROM fza_empresas'
      'WHERE'
      '  CODIGO_EMP_EMP = :Old_CODIGO_EMPRESA')
    SQLUpdate.Strings = (
      'UPDATE fza_empresas'
      'SET'
      
        '  CODIGO_EMP_EMP = :CODIGO_EMP_EMP, ORDEN_EMP = :ORDEN_EMP, ESACTIVO_EMP = :ESACTIVO_EMP, RAZON_SOCIAL_EMP = :RAZON_SOCIAL_EMP, NIF_EMP = :NIF_EMP, MOVIL_EMP = :MOVIL_EMP, EMAIL_EMP = :EMAIL_EMP, DIRE' +
        'CCION1_EMP = :DIRECCION1_EMP, DIRECCION2_EMP = :DIRECCION2_EMP, CODIGO_POSTAL_EMP = :CODIGO_POSTAL_EMP, POBLACION_EMP = :POBLACION_EMP, PROVINCIA_EMP = :PROVINCIA_EMP, CODIGO_PAI_EMP = :CODIGO_PAI_EMP' +
        ', NOMBRE_PAI_EMP = :NOMBRE_PAI_EMP, IBAN_EMP = :IBAN_EMP, GRUPO_ZONA_IVA_EMP = :GRUPO_ZONA_IVA_EMP, ESRETENCIONES_EMP = :ESRETENCIONES_EMP, ESREGIMENESPECIALAGRICOLA_EMP = :ESREGIMENESPECIALAGRICOLA_E' +
        'MP, CODIGO_CERTIFICADO_EMP = :CODIGO_CERTIFICADO_EMP, TITULAR_CERTIFICADO_EMP = :TITULAR_CERTIFICADO_EMP, TIPO_CERTIFICADO_EMP = :TIPO_CERTIFICADO_EMP, FECHA_DESDE_CERTIFICADO_EMP = :FECHA_DESDE_CERTI' +
        'FICADO_EMP, FECHA_HASTA_CERTIFICADO_EMP = :FECHA_HASTA_CERTIFICADO_EMP, TEXTO_LEGAL_FACTURA_EMP = :TEXTO_LEGAL_FACTURA_EMP, INSTANTE_MODIF = :INSTANTE_MODIF, INSTANTE_ALTA = :INSTANTE_ALTA, USUARIO_AL' +
        'TA = :USUARIO_ALTA, USUARIO_MODIF = :USUARIO_MODIF'
      'WHERE'
      '  CODIGO_EMP_EMP = :Old_CODIGO_EMPRESA')
    SQLLock.Strings = (
      
        'SELECT CODIGO_EMP_EMP, ORDEN_EMP, ESACTIVO_EMP, RAZON_SOCIAL_EMP, NIF_EMP, MOVIL_EMP, EMAIL_EMP, DIRECCION1_EMP, DIRECCION2_EMP, CODIGO_POSTAL_EMP, POBLACION_EMP, PROVINCIA_EMP, CODIGO_PAI_EMP, NOMBRE' +
        '_PAI_EMP, IBAN_EMP, GRUPO_ZONA_IVA_EMP, ESRETENCIONES_EMP, ESREGIMENESPECIALAGRICOLA_EMP, CODIGO_CERTIFICADO_EMP, TITULAR_CERTIFICADO_EMP, TIPO_CERTIFICADO_EMP, FECHA_DESDE_CERTIFICADO_EMP, FECHA_HAST' +
        'A_CERTIFICADO_EMP, TEXTO_LEGAL_FACTURA_EMP, INSTANTE_MODIF, INSTANTE_ALTA, USUARIO_ALTA, USUARIO_MODIF FROM fza_empresas'
      'WHERE'
      '  CODIGO_EMP_EMP = :Old_CODIGO_EMPRESA'
      'FOR UPDATE')
    SQLRefresh.Strings = (
      
        'SELECT CODIGO_EMP_EMP, ORDEN_EMP, ESACTIVO_EMP, RAZON_SOCIAL_EMP, NIF_EMP, MOVIL_EMP, EMAIL_EMP, DIRECCION1_EMP, DIRECCION2_EMP, CODIGO_POSTAL_EMP, POBLACION_EMP, PROVINCIA_EMP, CODIGO_PAI_EMP, NOMBRE' +
        '_PAI_EMP, IBAN_EMP, GRUPO_ZONA_IVA_EMP, ESRETENCIONES_EMP, ESREGIMENESPECIALAGRICOLA_EMP, CODIGO_CERTIFICADO_EMP, TITULAR_CERTIFICADO_EMP, TIPO_CERTIFICADO_EMP, FECHA_DESDE_CERTIFICADO_EMP, FECHA_HAST' +
        'A_CERTIFICADO_EMP, TEXTO_LEGAL_FACTURA_EMP, INSTANTE_MODIF, INSTANTE_ALTA, USUARIO_ALTA, USUARIO_MODIF FROM fza_empresas'
      'WHERE'
      '  CODIGO_EMP_EMP = :CODIGO_EMP_EMP')
    SQLRecCount.Strings = (
      'SELECT COUNT(*) FROM fza_empresas')
    Connection = dmConn.conUni
    SQL.Strings = (
      'SELECT *  '
      '  FROM vi_empresas '
      ' ORDER BY orden_emp')
    AfterInsert = unqryTablaGAfterInsert
    BeforeDelete = unqryTablaGBeforeDelete
    AfterDelete = unqryTablaGAfterDelete
  end
  inherited unqryPerfiles: TUniQuery
    SQL.Strings = (
      'select *'
      'from fza_usuarios_perfiles'
      'where (KEY_USUPER = '#39'dmEmpresas'#39' '
      'OR KEY_USUPER='#39'frmMtoEmpresas'#39')')
  end
  object unqryRetenciones: TUniQuery
    SQLInsert.Strings = (
      'INSERT INTO fza_empresas_retenciones'
      
        '  (CODIGO_RETENCION_EMPRET, CODIGO_EMP_EMPRET, PORCENTAJE_EMPRET, FECHA_DESDE_EMPRET, FECHA_HASTA_EMPRET, INSTANTE_MODIF, INSTANTE_ALTA, USUARIO_ALTA, USUARIO_MODIF)'
      'VALUES'
      
        '  (:CODIGO_RETENCION_EMPRET, :CODIGO_EMP_EMPRET, :PORCENTAJE_EMPRET, :FECHA_DESDE_EMPRET, :FECHA_HASTA_EMPRET, :INSTANTE_MODIF, :INSTANTE_ALTA, :USUARIO_ALTA, :USUARIO_MODIF)')
    SQLDelete.Strings = (
      'DELETE FROM fza_empresas_retenciones'
      'WHERE'
      '  CODIGO_RETENCION_EMPRET = :Old_CODIGO_RETENCION')
    SQLUpdate.Strings = (
      'UPDATE fza_empresas_retenciones'
      'SET'
      
        '  CODIGO_RETENCION_EMPRET = :CODIGO_RETENCION_EMPRET, CODIGO_EMP_EMPRET = :CODIGO_EMP_EMPRET, PORCENTAJE_EMPRET = :PORCENTAJE_EMPRET, FECHA_DESDE_EMPRET = :FECHA_DESDE_EMPRET, FECHA_HASTA_EMPRET = :FE' +
        'CHA_HASTA_EMPRET, INSTANTE_MODIF = :INSTANTE_MODIF, INSTANTE_ALTA = :INSTANTE_ALTA, USUARIO_ALTA = :USUARIO_ALTA, USUARIO_MODIF = :USUARIO_MODIF'
      'WHERE'
      '  CODIGO_RETENCION_EMPRET = :Old_CODIGO_RETENCION')
    SQLLock.Strings = (
      'SELECT * FROM fza_empresas_retenciones'
      'WHERE'
      '  CODIGO_RETENCION_EMPRET = :Old_CODIGO_RETENCION'
      'FOR UPDATE')
    SQLRefresh.Strings = (
      
        'SELECT CODIGO_RETENCION_EMPRET, CODIGO_EMP_EMPRET, PORCENTAJE_EMPRET, FECHA_DESDE_EMPRET, FECHA_HASTA_EMPRET, INSTANTE_MODIF, INSTANTE_ALTA, USUARIO_ALTA, USUARIO_MODIF FROM fza_empresas_retenciones'
      'WHERE'
      '  CODIGO_RETENCION_EMPRET = :CODIGO_RETENCION_EMPRET')
    SQLRecCount.Strings = (
      'SELECT COUNT(*) FROM fza_empresas_retenciones')
    Connection = dmConn.conUni
    SQL.Strings = (
      'SELECT * '
      'FROM vi_empresas_retenciones'
      'WHERE CODIGO_EMP_EMPRET = :CODIGO_EMP_EMP')
    MasterFields = 'CODIGO_EMP_EMP'
    DetailFields = 'CODIGO_EMP_EMPRET'
    RefreshOptions = [roAfterUpdate]
    BeforeInsert = unqryRetencionesBeforeInsert
    AfterInsert = unqryRetencionesAfterInsert
    BeforePost = unqryRetencionesBeforePost
    Left = 176
    Top = 24
    ParamData = <
      item
        DataType = ftWideString
        Name = 'CODIGO_EMP_EMP'
        ParamType = ptInput
        Value = '007'
      end>
  end
  object dsRetenciones: TDataSource
    DataSet = unqryRetenciones
    Left = 176
    Top = 80
  end
  object unqryIvas: TUniQuery
    Connection = dmConn.conUni
    SQL.Strings = (
      'SELECT * '
      'FROM VI_IVAS_GRUPOS'
      '')
    DetailFields = 'IVA_IVAGRP'
    AfterInsert = unqryRetencionesAfterInsert
    BeforePost = unqryRetencionesBeforePost
    Left = 384
    Top = 24
  end
  object dsIvas: TDataSource
    DataSet = unqryIvas
    Left = 384
    Top = 80
  end
  object dsFacturasEmpresas: TDataSource
    DataSet = unqryFacturasEmpresas
    Left = 480
    Top = 80
  end
  object unqryFacturasEmpresas: TUniQuery
    SQLInsert.Strings = (
      'INSERT INTO fza_facturas'
      
        '  (NUMERO_FAC, SERIE_FAC, FECHA_FAC, CODIGO_EMP_FAC, RAZON_SOCIAL_EMPRESA_FAC, NIF_EMPRESA_FAC, MOVIL_EMPRESA_FAC, EMAIL_EMPRESA_FAC, DIRECCION1_EMPRESA_FAC, DIRECCION2_EMPRESA_FAC, POBLACION_EMPRESA_' +
        'FAC, PROVINCIA_EMPRESA_FAC, CODIGO_PAI_EMPRESA_FAC, NOMBRE_PAI_EMPRESA_FAC, CODIGO_POSTAL_EMPRESA_FAC, ESRETENCIONES_EMPRESA_FAC, GRUPO_ZONA_IVA_EMPRESA_FAC, ESREGIMENESPECIALAGRICOLA_EMPRESA_FAC, COD' +
        'IGO_CLI_FAC, RAZON_SOCIAL_CLIENTE_FAC, NIF_CLIENTE_FAC, MOVIL_CLIENTE_FAC, EMAIL_CLIENTE_FAC, DIRECCION1_CLIENTE_FAC, DIRECCION2_CLIENTE_FAC, POBLACION_CLIENTE_FAC, PROVINCIA_CLIENTE_FAC, CODIGO_POSTA' +
        'L_CLIENTE_FAC, CODIGO_PAI_CLIENTE_FAC, NOMBRE_PAI_CLIENTE_FAC, CODIGO_IVA_FAC, ESIVA_RECARGO_CLIENTE_FAC, ESIVA_EXENTO_CLIENTE_FAC, ESREGIMENESPECIALAGRICOLA_CLIENTE_FAC, ESRETENCIONES_CLIENTE_FAC, TA' +
        'RIFA_ARTICULO_CLIENTE_FAC, ESIMP_INCL_TARIFA_CLIENTE_FAC, ESINTRACOMUNITARIO_CLIENTE_FAC, ESIRPF_IMP_INCL_ZONA_IVA_FAC, ESAPLICA_RE_ZONA_IVA_FAC, ESIVAAGRICOLA_ZONA_IVA_FAC, PALABRA_REPORTS_ZONA_IVA_F' +
        'AC, ESVENTA_ACTIVO_FIJO_FAC, PORCENTAJE_IVAN_FAC, TOTAL_IVAN_FAC, PORCENTAJE_REN_FAC, TOTAL_REN_FAC, TOTAL_BASEI_IVAN_FAC, PORCENTAJE_IVAR_FAC, TOTAL_IVAR_FAC, PORCENTAJE_RER_FAC, TOTAL_RER_FAC, TOTAL' +
        '_BASEI_IVAR_FAC, PORCENTAJE_IVAS_FAC, TOTAL_IVAS_FAC, PORCENTAJE_RES_FAC, TOTAL_RES_FAC, TOTAL_BASEI_IVAS_FAC, PORCENTAJE_IVAE_FAC, TOTAL_IVAE_FAC, PORCENTAJE_REE_FAC, TOTAL_REE_FAC, TOTAL_BASEI_IVAE_' +
        'FAC, TOTAL_BASES_FAC, TOTAL_IMPUESTOS_FAC, FORMA_PAGO_FAC, PORCENTAJE_RETENCION_FAC, TOTAL_RETENCION_FAC, TOTAL_LIQUIDO_FAC, NUMERO_FAC_ABONO_FAC, SERIE_FAC_ABONO_FAC, TEXTO_LEGAL_CLIENTE_FAC, TEXTO_L' +
        'EGAL_EMPRESA_FAC, DOCUMENTO_FAC, COMENTARIOS_FAC, CONTADOR_LINEAS_FAC, ESCREARARTICULOS_FAC, ESDESCRIPCIONES_AMP_FAC, ESFECHADEENTREGA_FAC, INSTANTE_MODIF, INSTANTE_ALTA, USUARIO_ALTA, USUARIO_MODIF)'
      'VALUES'
      
        '  (:NUMERO_FAC, :SERIE_FAC, :FECHA_FAC, :CODIGO_EMP_FAC, :RAZON_SOCIAL_EMPRESA_FAC, :NIF_EMPRESA_FAC, :MOVIL_EMPRESA_FAC, :EMAIL_EMPRESA_FAC, :DIRECCION1_EMPRESA_FAC, :DIRECCION2_EMPRESA_FAC, :POBLACI' +
        'ON_EMPRESA_FAC, :PROVINCIA_EMPRESA_FAC, :CODIGO_PAI_EMPRESA_FAC, :NOMBRE_PAI_EMPRESA_FAC, :CODIGO_POSTAL_EMPRESA_FAC, :ESRETENCIONES_EMPRESA_FAC, :GRUPO_ZONA_IVA_EMPRESA_FAC, :ESREGIMENESPECIALAGRICOL' +
        'A_EMPRESA_FAC, :CODIGO_CLI_FAC, :RAZON_SOCIAL_CLIENTE_FAC, :NIF_CLIENTE_FAC, :MOVIL_CLIENTE_FAC, :EMAIL_CLIENTE_FAC, :DIRECCION1_CLIENTE_FAC, :DIRECCION2_CLIENTE_FAC, :POBLACION_CLIENTE_FAC, :PROVINCI' +
        'A_CLIENTE_FAC, :CODIGO_POSTAL_CLIENTE_FAC, :CODIGO_PAI_CLIENTE_FAC, :NOMBRE_PAI_CLIENTE_FAC, :CODIGO_IVA_FAC, :ESIVA_RECARGO_CLIENTE_FAC, :ESIVA_EXENTO_CLIENTE_FAC, :ESREGIMENESPECIALAGRICOLA_CLIENTE_' +
        'FAC, :ESRETENCIONES_CLIENTE_FAC, :TARIFA_ARTICULO_CLIENTE_FAC, :ESIMP_INCL_TARIFA_CLIENTE_FAC, :ESINTRACOMUNITARIO_CLIENTE_FAC, :ESIRPF_IMP_INCL_ZONA_IVA_FAC, :ESAPLICA_RE_ZONA_IVA_FAC, :ESIVAAGRICOLA' +
        '_ZONA_IVA_FAC, :PALABRA_REPORTS_ZONA_IVA_FAC, :ESVENTA_ACTIVO_FIJO_FAC, :PORCENTAJE_IVAN_FAC, :TOTAL_IVAN_FAC, :PORCENTAJE_REN_FAC, :TOTAL_REN_FAC, :TOTAL_BASEI_IVAN_FAC, :PORCENTAJE_IVAR_FAC, :TOTAL_' +
        'IVAR_FAC, :PORCENTAJE_RER_FAC, :TOTAL_RER_FAC, :TOTAL_BASEI_IVAR_FAC, :PORCENTAJE_IVAS_FAC, :TOTAL_IVAS_FAC, :PORCENTAJE_RES_FAC, :TOTAL_RES_FAC, :TOTAL_BASEI_IVAS_FAC, :PORCENTAJE_IVAE_FAC, :TOTAL_IV' +
        'AE_FAC, :PORCENTAJE_REE_FAC, :TOTAL_REE_FAC, :TOTAL_BASEI_IVAE_FAC, :TOTAL_BASES_FAC, :TOTAL_IMPUESTOS_FAC, :FORMA_PAGO_FAC, :PORCENTAJE_RETENCION_FAC, :TOTAL_RETENCION_FAC, :TOTAL_LIQUIDO_FAC, :NUMER' +
        'O_FAC_ABONO_FAC, :SERIE_FAC_ABONO_FAC, :TEXTO_LEGAL_CLIENTE_FAC, :TEXTO_LEGAL_EMPRESA_FAC, :DOCUMENTO_FAC, :COMENTARIOS_FAC, :CONTADOR_LINEAS_FAC, :ESCREARARTICULOS_FAC, :ESDESCRIPCIONES_AMP_FAC, :ESF' +
        'ECHADEENTREGA_FAC, :INSTANTE_MODIF, :INSTANTE_ALTA, :USUARIO_ALTA, :USUARIO_MODIF)')
    SQLDelete.Strings = (
      'DELETE FROM fza_facturas'
      'WHERE'
      
        '  NUMERO_FAC = :Old_NRO_FACTURA AND SERIE_FAC = :Old_SERIE_FACTURA')
    SQLUpdate.Strings = (
      'UPDATE fza_facturas'
      'SET'
      
        '  NUMERO_FAC = :NUMERO_FAC, SERIE_FAC = :SERIE_FAC, FECHA_FAC = :FECHA_FAC, CODIGO_EMP_FAC = :CODIGO_EMP_FAC, RAZON_SOCIAL_EMPRESA_FAC = :RAZON_SOCIAL_EMPRESA_FAC, NIF_EMPRESA_FAC = :NIF_EMPRESA_FAC, ' +
        'MOVIL_EMPRESA_FAC = :MOVIL_EMPRESA_FAC, EMAIL_EMPRESA_FAC = :EMAIL_EMPRESA_FAC, DIRECCION1_EMPRESA_FAC = :DIRECCION1_EMPRESA_FAC, DIRECCION2_EMPRESA_FAC = :DIRECCION2_EMPRESA_FAC, POBLACION_EMPRESA_FA' +
        'C = :POBLACION_EMPRESA_FAC, PROVINCIA_EMPRESA_FAC = :PROVINCIA_EMPRESA_FAC, CODIGO_PAI_EMPRESA_FAC = :CODIGO_PAI_EMPRESA_FAC, NOMBRE_PAI_EMPRESA_FAC = :NOMBRE_PAI_EMPRESA_FAC, CODIGO_POSTAL_EMPRESA_FA' +
        'C = :CODIGO_POSTAL_EMPRESA_FAC, ESRETENCIONES_EMPRESA_FAC = :ESRETENCIONES_EMPRESA_FAC, GRUPO_ZONA_IVA_EMPRESA_FAC = :GRUPO_ZONA_IVA_EMPRESA_FAC, ESREGIMENESPECIALAGRICOLA_EMPRESA_FAC = :ESREGIMENESPE' +
        'CIALAGRICOLA_EMPRESA_FAC, CODIGO_CLI_FAC = :CODIGO_CLI_FAC, RAZON_SOCIAL_CLIENTE_FAC = :RAZON_SOCIAL_CLIENTE_FAC, NIF_CLIENTE_FAC = :NIF_CLIENTE_FAC, MOVIL_CLIENTE_FAC = :MOVIL_CLIENTE_FAC, EMAIL_CLIE' +
        'NTE_FAC = :EMAIL_CLIENTE_FAC, DIRECCION1_CLIENTE_FAC = :DIRECCION1_CLIENTE_FAC, DIRECCION2_CLIENTE_FAC = :DIRECCION2_CLIENTE_FAC, POBLACION_CLIENTE_FAC = :POBLACION_CLIENTE_FAC, PROVINCIA_CLIENTE_FAC ' +
        '= :PROVINCIA_CLIENTE_FAC, CODIGO_POSTAL_CLIENTE_FAC = :CODIGO_POSTAL_CLIENTE_FAC, CODIGO_PAI_CLIENTE_FAC = :CODIGO_PAI_CLIENTE_FAC, NOMBRE_PAI_CLIENTE_FAC = :NOMBRE_PAI_CLIENTE_FAC, CODIGO_IVA_FAC = :' +
        'CODIGO_IVA_FAC, ESIVA_RECARGO_CLIENTE_FAC = :ESIVA_RECARGO_CLIENTE_FAC, ESIVA_EXENTO_CLIENTE_FAC = :ESIVA_EXENTO_CLIENTE_FAC, ESREGIMENESPECIALAGRICOLA_CLIENTE_FAC = :ESREGIMENESPECIALAGRICOLA_CLIENTE' +
        '_FAC, ESRETENCIONES_CLIENTE_FAC = :ESRETENCIONES_CLIENTE_FAC, TARIFA_ARTICULO_CLIENTE_FAC = :TARIFA_ARTICULO_CLIENTE_FAC, ESIMP_INCL_TARIFA_CLIENTE_FAC = :ESIMP_INCL_TARIFA_CLIENTE_FAC, ESINTRACOMUNIT' +
        'ARIO_CLIENTE_FAC = :ESINTRACOMUNITARIO_CLIENTE_FAC, ESIRPF_IMP_INCL_ZONA_IVA_FAC = :ESIRPF_IMP_INCL_ZONA_IVA_FAC, ESAPLICA_RE_ZONA_IVA_FAC = :ESAPLICA_RE_ZONA_IVA_FAC, ESIVAAGRICOLA_ZONA_IVA_FAC = :ES' +
        'IVAAGRICOLA_ZONA_IVA_FAC, PALABRA_REPORTS_ZONA_IVA_FAC = :PALABRA_REPORTS_ZONA_IVA_FAC, ESVENTA_ACTIVO_FIJO_FAC = :ESVENTA_ACTIVO_FIJO_FAC, PORCENTAJE_IVAN_FAC = :PORCENTAJE_IVAN_FAC, TOTAL_IVAN_FAC =' +
        ' :TOTAL_IVAN_FAC, PORCENTAJE_REN_FAC = :PORCENTAJE_REN_FAC, TOTAL_REN_FAC = :TOTAL_REN_FAC, TOTAL_BASEI_IVAN_FAC = :TOTAL_BASEI_IVAN_FAC, PORCENTAJE_IVAR_FAC = :PORCENTAJE_IVAR_FAC, TOTAL_IVAR_FAC = :' +
        'TOTAL_IVAR_FAC, PORCENTAJE_RER_FAC = :PORCENTAJE_RER_FAC, TOTAL_RER_FAC = :TOTAL_RER_FAC, TOTAL_BASEI_IVAR_FAC = :TOTAL_BASEI_IVAR_FAC, PORCENTAJE_IVAS_FAC = :PORCENTAJE_IVAS_FAC, TOTAL_IVAS_FAC = :TO' +
        'TAL_IVAS_FAC, PORCENTAJE_RES_FAC = :PORCENTAJE_RES_FAC, TOTAL_RES_FAC = :TOTAL_RES_FAC, TOTAL_BASEI_IVAS_FAC = :TOTAL_BASEI_IVAS_FAC, PORCENTAJE_IVAE_FAC = :PORCENTAJE_IVAE_FAC, TOTAL_IVAE_FAC = :TOTA' +
        'L_IVAE_FAC, PORCENTAJE_REE_FAC = :PORCENTAJE_REE_FAC, TOTAL_REE_FAC = :TOTAL_REE_FAC, TOTAL_BASEI_IVAE_FAC = :TOTAL_BASEI_IVAE_FAC, TOTAL_BASES_FAC = :TOTAL_BASES_FAC, TOTAL_IMPUESTOS_FAC = :TOTAL_IMP' +
        'UESTOS_FAC, FORMA_PAGO_FAC = :FORMA_PAGO_FAC, PORCENTAJE_RETENCION_FAC = :PORCENTAJE_RETENCION_FAC, TOTAL_RETENCION_FAC = :TOTAL_RETENCION_FAC, TOTAL_LIQUIDO_FAC = :TOTAL_LIQUIDO_FAC, NUMERO_FAC_ABONO' +
        '_FAC = :NUMERO_FAC_ABONO_FAC, SERIE_FAC_ABONO_FAC = :SERIE_FAC_ABONO_FAC, TEXTO_LEGAL_CLIENTE_FAC = :TEXTO_LEGAL_CLIENTE_FAC, TEXTO_LEGAL_EMPRESA_FAC = :TEXTO_LEGAL_EMPRESA_FAC, DOCUMENTO_FAC = :DOCUM' +
        'ENTO_FAC, COMENTARIOS_FAC = :COMENTARIOS_FAC, CONTADOR_LINEAS_FAC = :CONTADOR_LINEAS_FAC, ESCREARARTICULOS_FAC = :ESCREARARTICULOS_FAC, ESDESCRIPCIONES_AMP_FAC = :ESDESCRIPCIONES_AMP_FAC, ESFECHADEENT' +
        'REGA_FAC = :ESFECHADEENTREGA_FAC, INSTANTE_MODIF = :INSTANTE_MODIF, INSTANTE_ALTA = :INSTANTE_ALTA, USUARIO_ALTA = :USUARIO_ALTA, USUARIO_MODIF = :USUARIO_MODIF'
      'WHERE'
      
        '  NUMERO_FAC = :Old_NRO_FACTURA AND SERIE_FAC = :Old_SERIE_FACTURA')
    SQLLock.Strings = (
      
        'SELECT NUMERO_FAC, SERIE_FAC, FECHA_FAC, CODIGO_EMP_FAC, RAZON_SOCIAL_EMPRESA_FAC, NIF_EMPRESA_FAC, MOVIL_EMPRESA_FAC, EMAIL_EMPRESA_FAC, DIRECCION1_EMPRESA_FAC, DIRECCION2_EMPRESA_FAC, POBLACION_EMPR' +
        'ESA_FAC, PROVINCIA_EMPRESA_FAC, CODIGO_PAI_EMPRESA_FAC, NOMBRE_PAI_EMPRESA_FAC, CODIGO_POSTAL_EMPRESA_FAC, ESRETENCIONES_EMPRESA_FAC, GRUPO_ZONA_IVA_EMPRESA_FAC, ESREGIMENESPECIALAGRICOLA_EMPRESA_FAC,' +
        ' CODIGO_CLI_FAC, RAZON_SOCIAL_CLIENTE_FAC, NIF_CLIENTE_FAC, MOVIL_CLIENTE_FAC, EMAIL_CLIENTE_FAC, DIRECCION1_CLIENTE_FAC, DIRECCION2_CLIENTE_FAC, POBLACION_CLIENTE_FAC, PROVINCIA_CLIENTE_FAC, CODIGO_P' +
        'OSTAL_CLIENTE_FAC, CODIGO_PAI_CLIENTE_FAC, NOMBRE_PAI_CLIENTE_FAC, CODIGO_IVA_FAC, ESIVA_RECARGO_CLIENTE_FAC, ESIVA_EXENTO_CLIENTE_FAC, ESREGIMENESPECIALAGRICOLA_CLIENTE_FAC, ESRETENCIONES_CLIENTE_FAC' +
        ', TARIFA_ARTICULO_CLIENTE_FAC, ESIMP_INCL_TARIFA_CLIENTE_FAC, ESINTRACOMUNITARIO_CLIENTE_FAC, ESIRPF_IMP_INCL_ZONA_IVA_FAC, ESAPLICA_RE_ZONA_IVA_FAC, ESIVAAGRICOLA_ZONA_IVA_FAC, PALABRA_REPORTS_ZONA_I' +
        'VA_FAC, ESVENTA_ACTIVO_FIJO_FAC, PORCENTAJE_IVAN_FAC, TOTAL_IVAN_FAC, PORCENTAJE_REN_FAC, TOTAL_REN_FAC, TOTAL_BASEI_IVAN_FAC, PORCENTAJE_IVAR_FAC, TOTAL_IVAR_FAC, PORCENTAJE_RER_FAC, TOTAL_RER_FAC, T' +
        'OTAL_BASEI_IVAR_FAC, PORCENTAJE_IVAS_FAC, TOTAL_IVAS_FAC, PORCENTAJE_RES_FAC, TOTAL_RES_FAC, TOTAL_BASEI_IVAS_FAC, PORCENTAJE_IVAE_FAC, TOTAL_IVAE_FAC, PORCENTAJE_REE_FAC, TOTAL_REE_FAC, TOTAL_BASEI_I' +
        'VAE_FAC, TOTAL_BASES_FAC, TOTAL_IMPUESTOS_FAC, FORMA_PAGO_FAC, PORCENTAJE_RETENCION_FAC, TOTAL_RETENCION_FAC, TOTAL_LIQUIDO_FAC, NUMERO_FAC_ABONO_FAC, SERIE_FAC_ABONO_FAC, TEXTO_LEGAL_CLIENTE_FAC, TEX' +
        'TO_LEGAL_EMPRESA_FAC, DOCUMENTO_FAC, COMENTARIOS_FAC, CONTADOR_LINEAS_FAC, ESCREARARTICULOS_FAC, ESDESCRIPCIONES_AMP_FAC, ESFECHADEENTREGA_FAC, INSTANTE_MODIF, INSTANTE_ALTA, USUARIO_ALTA, USUARIO_MOD' +
        'IF FROM fza_facturas'
      'WHERE'
      
        '  NUMERO_FAC = :Old_NRO_FACTURA AND SERIE_FAC = :Old_SERIE_FACTURA'
      'FOR UPDATE')
    SQLRefresh.Strings = (
      
        'SELECT NUMERO_FAC, SERIE_FAC, FECHA_FAC, CODIGO_EMP_FAC, RAZON_SOCIAL_EMPRESA_FAC, NIF_EMPRESA_FAC, MOVIL_EMPRESA_FAC, EMAIL_EMPRESA_FAC, DIRECCION1_EMPRESA_FAC, DIRECCION2_EMPRESA_FAC, POBLACION_EMPR' +
        'ESA_FAC, PROVINCIA_EMPRESA_FAC, CODIGO_PAI_EMPRESA_FAC, NOMBRE_PAI_EMPRESA_FAC, CODIGO_POSTAL_EMPRESA_FAC, ESRETENCIONES_EMPRESA_FAC, GRUPO_ZONA_IVA_EMPRESA_FAC, ESREGIMENESPECIALAGRICOLA_EMPRESA_FAC,' +
        ' CODIGO_CLI_FAC, RAZON_SOCIAL_CLIENTE_FAC, NIF_CLIENTE_FAC, MOVIL_CLIENTE_FAC, EMAIL_CLIENTE_FAC, DIRECCION1_CLIENTE_FAC, DIRECCION2_CLIENTE_FAC, POBLACION_CLIENTE_FAC, PROVINCIA_CLIENTE_FAC, CODIGO_P' +
        'OSTAL_CLIENTE_FAC, CODIGO_PAI_CLIENTE_FAC, NOMBRE_PAI_CLIENTE_FAC, CODIGO_IVA_FAC, ESIVA_RECARGO_CLIENTE_FAC, ESIVA_EXENTO_CLIENTE_FAC, ESREGIMENESPECIALAGRICOLA_CLIENTE_FAC, ESRETENCIONES_CLIENTE_FAC' +
        ', TARIFA_ARTICULO_CLIENTE_FAC, ESIMP_INCL_TARIFA_CLIENTE_FAC, ESINTRACOMUNITARIO_CLIENTE_FAC, ESIRPF_IMP_INCL_ZONA_IVA_FAC, ESAPLICA_RE_ZONA_IVA_FAC, ESIVAAGRICOLA_ZONA_IVA_FAC, PALABRA_REPORTS_ZONA_I' +
        'VA_FAC, ESVENTA_ACTIVO_FIJO_FAC, PORCENTAJE_IVAN_FAC, TOTAL_IVAN_FAC, PORCENTAJE_REN_FAC, TOTAL_REN_FAC, TOTAL_BASEI_IVAN_FAC, PORCENTAJE_IVAR_FAC, TOTAL_IVAR_FAC, PORCENTAJE_RER_FAC, TOTAL_RER_FAC, T' +
        'OTAL_BASEI_IVAR_FAC, PORCENTAJE_IVAS_FAC, TOTAL_IVAS_FAC, PORCENTAJE_RES_FAC, TOTAL_RES_FAC, TOTAL_BASEI_IVAS_FAC, PORCENTAJE_IVAE_FAC, TOTAL_IVAE_FAC, PORCENTAJE_REE_FAC, TOTAL_REE_FAC, TOTAL_BASEI_I' +
        'VAE_FAC, TOTAL_BASES_FAC, TOTAL_IMPUESTOS_FAC, FORMA_PAGO_FAC, PORCENTAJE_RETENCION_FAC, TOTAL_RETENCION_FAC, TOTAL_LIQUIDO_FAC, NUMERO_FAC_ABONO_FAC, SERIE_FAC_ABONO_FAC, TEXTO_LEGAL_CLIENTE_FAC, TEX' +
        'TO_LEGAL_EMPRESA_FAC, DOCUMENTO_FAC, COMENTARIOS_FAC, CONTADOR_LINEAS_FAC, ESCREARARTICULOS_FAC, ESDESCRIPCIONES_AMP_FAC, ESFECHADEENTREGA_FAC, INSTANTE_MODIF, INSTANTE_ALTA, USUARIO_ALTA, USUARIO_MOD' +
        'IF FROM fza_facturas'
      'WHERE'
      '  NUMERO_FAC = :NUMERO_FAC AND SERIE_FAC = :SERIE_FAC')
    SQLRecCount.Strings = (
      'SELECT COUNT(*) FROM fza_facturas')
    Connection = dmConn.conUni
    SQL.Strings = (
      'select * from vi_fac_busquedas')
    MasterFields = 'CODIGO_EMP_EMP'
    DetailFields = 'CODIGO_EMP_FAC'
    ReadOnly = True
    Left = 480
    Top = 24
    ParamData = <
      item
        DataType = ftWideString
        Name = 'CODIGO_EMP_EMP'
        ParamType = ptInput
        Value = '007'
      end>
  end
  object dsFacturasLineasEmpresas: TDataSource
    DataSet = unqryFacturasLineasEmpresas
    Left = 625
    Top = 80
  end
  object unqryFacturasLineasEmpresas: TUniQuery
    SQLInsert.Strings = (
      'INSERT INTO fza_facturas_lineas'
      
        '  (NUMERO_FAC_FACLIN, SERIE_FAC_FACLIN, LINEA_FACLIN, CODIGO_ART_FACLIN, CODIGO_FAM_FACLIN, NOMBRE_FAM_FACLIN, PRECIO_ULT_COMPRA_FACLIN, CODIGO_PRV_FACLIN, RAZON_SOCIAL_PROVEEDOR_FACLIN, ESPROVEEDORPR' +
        'INCIPAL_FACLIN, FECHA_ENTREGA_FACLIN, TIPO_CANTIDAD_ARTICULO_FACLIN, ESIMP_INCL_TARIFA_FACLIN, TIPO_IVA_ARTICULO_FACLIN, DESCRIPCION_ARTICULO_FACLIN, CODIGO_TAR_FACLIN, CANTIDAD_FACLIN, PRECIO_SALIDA_' +
        'FACLIN, PORCENTAJE_DTO_FACLIN, PRECIO_DTO_FACLIN, PRECIO_VENTA_SIVA_ARTICULO_FACLIN, PORCENTAJE_IVA_FACLIN, PRECIO_VENTA_CIVA_ARTICULO_FACLIN, TOTAL_FACLIN, TOTAL_FAC_SIVA_FACLIN, INSTANTE_MODIF, INST' +
        'ANTE_ALTA, USUARIO_ALTA, USUARIO_MODIF)'
      'VALUES'
      
        '  (:NUMERO_FAC_FACLIN, :SERIE_FAC_FACLIN, :LINEA_FACLIN, :CODIGO_ART_FACLIN, :CODIGO_FAM_FACLIN, :NOMBRE_FAM_FACLIN, :PRECIO_ULT_COMPRA_FACLIN, :CODIGO_PRV_FACLIN, :RAZON_SOCIAL_PROVEEDOR_FACLIN, :ESP' +
        'ROVEEDORPRINCIPAL_FACLIN, :FECHA_ENTREGA_FACLIN, :TIPO_CANTIDAD_ARTICULO_FACLIN, :ESIMP_INCL_TARIFA_FACLIN, :TIPO_IVA_ARTICULO_FACLIN, :DESCRIPCION_ARTICULO_FACLIN, :CODIGO_TAR_FACLIN, :CANTIDAD_FACLI' +
        'N, :PRECIO_SALIDA_FACLIN, :PORCENTAJE_DTO_FACLIN, :PRECIO_DTO_FACLIN, :PRECIO_VENTA_SIVA_ARTICULO_FACLIN, :PORCENTAJE_IVA_FACLIN, :PRECIO_VENTA_CIVA_ARTICULO_FACLIN, :TOTAL_FACLIN, :TOTAL_FAC_SIVA_FAC' +
        'LIN, :INSTANTE_MODIF, :INSTANTE_ALTA, :USUARIO_ALTA, :USUARIO_MODIF)')
    SQLDelete.Strings = (
      'DELETE FROM fza_facturas_lineas'
      'WHERE'
      
        '  NUMERO_FAC_FACLIN = :Old_NRO_FACTURA_LINEA AND SERIE_FAC_FACLIN = :Old_SERIE_FACTURA_LINEA AND LINEA_FACLIN = :Old_LINEA_FACTURA_LINEA')
    SQLUpdate.Strings = (
      'UPDATE fza_facturas_lineas'
      'SET'
      
        '  NUMERO_FAC_FACLIN = :NUMERO_FAC_FACLIN, SERIE_FAC_FACLIN = :SERIE_FAC_FACLIN, LINEA_FACLIN = :LINEA_FACLIN, CODIGO_ART_FACLIN = :CODIGO_ART_FACLIN, CODIGO_FAM_FACLIN = :CODIGO_FAM_FACLIN, NOMBRE_FAM' +
        '_FACLIN = :NOMBRE_FAM_FACLIN, PRECIO_ULT_COMPRA_FACLIN = :PRECIO_ULT_COMPRA_FACLIN, CODIGO_PRV_FACLIN = :CODIGO_PRV_FACLIN, RAZON_SOCIAL_PROVEEDOR_FACLIN = :RAZON_SOCIAL_PROVEEDOR_FACLIN, ESPROVEEDORP' +
        'RINCIPAL_FACLIN = :ESPROVEEDORPRINCIPAL_FACLIN, FECHA_ENTREGA_FACLIN = :FECHA_ENTREGA_FACLIN, TIPO_CANTIDAD_ARTICULO_FACLIN = :TIPO_CANTIDAD_ARTICULO_FACLIN, ESIMP_INCL_TARIFA_FACLIN = :ESIMP_INCL_TAR' +
        'IFA_FACLIN, TIPO_IVA_ARTICULO_FACLIN = :TIPO_IVA_ARTICULO_FACLIN, DESCRIPCION_ARTICULO_FACLIN = :DESCRIPCION_ARTICULO_FACLIN, CODIGO_TAR_FACLIN = :CODIGO_TAR_FACLIN, CANTIDAD_FACLIN = :CANTIDAD_FACLIN' +
        ', PRECIO_SALIDA_FACLIN = :PRECIO_SALIDA_FACLIN, PORCENTAJE_DTO_FACLIN = :PORCENTAJE_DTO_FACLIN, PRECIO_DTO_FACLIN = :PRECIO_DTO_FACLIN, PRECIO_VENTA_SIVA_ARTICULO_FACLIN = :PRECIO_VENTA_SIVA_ARTICULO_' +
        'FACLIN, PORCENTAJE_IVA_FACLIN = :PORCENTAJE_IVA_FACLIN, PRECIO_VENTA_CIVA_ARTICULO_FACLIN = :PRECIO_VENTA_CIVA_ARTICULO_FACLIN, TOTAL_FACLIN = :TOTAL_FACLIN, TOTAL_FAC_SIVA_FACLIN = :TOTAL_FAC_SIVA_FA' +
        'CLIN, INSTANTE_MODIF = :INSTANTE_MODIF, INSTANTE_ALTA = :INSTANTE_ALTA, USUARIO_ALTA = :USUARIO_ALTA, USUARIO_MODIF = :USUARIO_MODIF'
      'WHERE'
      
        '  NUMERO_FAC_FACLIN = :Old_NRO_FACTURA_LINEA AND SERIE_FAC_FACLIN = :Old_SERIE_FACTURA_LINEA AND LINEA_FACLIN = :Old_LINEA_FACTURA_LINEA')
    SQLLock.Strings = (
      
        'SELECT NUMERO_FAC_FACLIN, SERIE_FAC_FACLIN, LINEA_FACLIN, CODIGO_ART_FACLIN, CODIGO_FAM_FACLIN, NOMBRE_FAM_FACLIN, PRECIO_ULT_COMPRA_FACLIN, CODIGO_PRV_FACLIN, RAZON_SOCIAL_PROVEEDOR_FACLIN, ESPROVEED' +
        'ORPRINCIPAL_FACLIN, FECHA_ENTREGA_FACLIN, TIPO_CANTIDAD_ARTICULO_FACLIN, ESIMP_INCL_TARIFA_FACLIN, TIPO_IVA_ARTICULO_FACLIN, DESCRIPCION_ARTICULO_FACLIN, CODIGO_TAR_FACLIN, CANTIDAD_FACLIN, PRECIO_SAL' +
        'IDA_FACLIN, PORCENTAJE_DTO_FACLIN, PRECIO_DTO_FACLIN, PRECIO_VENTA_SIVA_ARTICULO_FACLIN, PORCENTAJE_IVA_FACLIN, PRECIO_VENTA_CIVA_ARTICULO_FACLIN, TOTAL_FACLIN, TOTAL_FAC_SIVA_FACLIN, INSTANTE_MODIF, ' +
        'INSTANTE_ALTA, USUARIO_ALTA, USUARIO_MODIF FROM fza_facturas_lineas'
      'WHERE'
      
        '  NUMERO_FAC_FACLIN = :Old_NRO_FACTURA_LINEA AND SERIE_FAC_FACLIN = :Old_SERIE_FACTURA_LINEA AND LINEA_FACLIN = :Old_LINEA_FACTURA_LINEA'
      'FOR UPDATE')
    SQLRefresh.Strings = (
      
        'SELECT NUMERO_FAC_FACLIN, SERIE_FAC_FACLIN, LINEA_FACLIN, CODIGO_ART_FACLIN, CODIGO_FAM_FACLIN, NOMBRE_FAM_FACLIN, PRECIO_ULT_COMPRA_FACLIN, CODIGO_PRV_FACLIN, RAZON_SOCIAL_PROVEEDOR_FACLIN, ESPROVEED' +
        'ORPRINCIPAL_FACLIN, FECHA_ENTREGA_FACLIN, TIPO_CANTIDAD_ARTICULO_FACLIN, ESIMP_INCL_TARIFA_FACLIN, TIPO_IVA_ARTICULO_FACLIN, DESCRIPCION_ARTICULO_FACLIN, CODIGO_TAR_FACLIN, CANTIDAD_FACLIN, PRECIO_SAL' +
        'IDA_FACLIN, PORCENTAJE_DTO_FACLIN, PRECIO_DTO_FACLIN, PRECIO_VENTA_SIVA_ARTICULO_FACLIN, PORCENTAJE_IVA_FACLIN, PRECIO_VENTA_CIVA_ARTICULO_FACLIN, TOTAL_FACLIN, TOTAL_FAC_SIVA_FACLIN, INSTANTE_MODIF, ' +
        'INSTANTE_ALTA, USUARIO_ALTA, USUARIO_MODIF FROM fza_facturas_lineas'
      'WHERE'
      
        '  NUMERO_FAC_FACLIN = :NUMERO_FAC_FACLIN AND SERIE_FAC_FACLIN = :SERIE_FAC_FACLIN AND LINEA_FACLIN = :LINEA_FACLIN')
    SQLRecCount.Strings = (
      'SELECT COUNT(*) FROM fza_facturas_lineas')
    Connection = dmConn.conUni
    SQL.Strings = (
      'select *'
      'from vi_fac_lin_busquedas l'
      'inner join vi_fac_busquedas f'
      'on l.NUMERO_FAC_FACLIN = F.NUMERO_FAC'
      'AND l.SERIE_FAC_FACLIN = F.SERIE_FAC'
      '')
    MasterFields = 'CODIGO_EMP_EMP'
    DetailFields = 'CODIGO_EMP_FAC'
    ReadOnly = True
    Left = 625
    Top = 24
    ParamData = <
      item
        DataType = ftWideString
        Name = 'CODIGO_EMP_EMP'
        ParamType = ptInput
        Value = '1'
      end>
  end
  object unqrySeries: TUniQuery
    SQLInsert.Strings = (
      'INSERT INTO fza_empresas_series'
      
        '  (CODIGO_SERIE_EMPSER, CODIGO_EMP_EMPSER, CODIGO_ALM_EMPSER, CODIGO_CAJA_EMPSER, EMPSER, TIPO_DOC_EMPSER, SUBTIPO_EMPSER, FECHA_DESDE_EMPSER, FECHA_HASTA_EMPSER, INSTANTE_MODIF, INSTANTE_ALTA, USUARIO_ALTA, USUARIO_MODIF)'
      'VALUES'
      
        '  (:CODIGO_SERIE_EMPSER, :CODIGO_EMP_EMPSER, :CODIGO_ALM_EMPSER, :CODIGO_CAJA_EMPSER, :EMPSER, :TIPO_DOC_EMPSER, :SUBTIPO_EMPSER, :FECHA_DESDE_EMPSER, :FECHA_HASTA_EMPSER, :INSTANTE_MODIF, :INSTANTE_A' +
        'LTA, :USUARIO_ALTA, :USUARIO_MODIF)')
    SQLDelete.Strings = (
      'DELETE FROM fza_empresas_series'
      'WHERE'
      '  CODIGO_SERIE_EMPSER = :Old_CODIGO_SERIE')
    SQLUpdate.Strings = (
      'UPDATE fza_empresas_series'
      'SET'
      
        '  CODIGO_SERIE_EMPSER = :CODIGO_SERIE_EMPSER, CODIGO_EMP_EMPSER = :CODIGO_EMP_EMPSER, CODIGO_ALM_EMPSER = :CODIGO_ALM_EMPSER, CODIGO_CAJA_EMPSER = :CODIGO_CAJA_EMPSER, EMPSER = :EMPSER, TIPO_DOC_EMPSE' +
        'R = :TIPO_DOC_EMPSER, SUBTIPO_EMPSER = :SUBTIPO_EMPSER, FECHA_DESDE_EMPSER = :FECHA_DESDE_EMPSER, FECHA_HASTA_EMPSER = :FECHA_HASTA_EMPSER, INSTANTE_MODIF = :INSTANTE_MODIF, INSTANTE_ALTA = :INSTANTE_' +
        'ALTA, USUARIO_ALTA = :USUARIO_ALTA, USUARIO_MODIF = :USUARIO_MODIF'
      'WHERE'
      '  CODIGO_SERIE_EMPSER = :Old_CODIGO_SERIE')
    SQLLock.Strings = (
      
        'SELECT CODIGO_SERIE_EMPSER, CODIGO_EMP_EMPSER, CODIGO_ALM_EMPSER, CODIGO_CAJA_EMPSER, EMPSER, TIPO_DOC_EMPSER, SUBTIPO_EMPSER, FECHA_DESDE_EMPSER, FECHA_HASTA_EMPSER, INSTANTE_MODIF, INSTANTE_ALTA, US' +
        'UARIO_ALTA, USUARIO_MODIF FROM fza_empresas_series'
      'WHERE'
      '  CODIGO_SERIE_EMPSER = :Old_CODIGO_SERIE'
      'FOR UPDATE')
    SQLRefresh.Strings = (
      
        'SELECT CODIGO_SERIE_EMPSER, CODIGO_EMP_EMPSER, CODIGO_ALM_EMPSER, CODIGO_CAJA_EMPSER, EMPSER, TIPO_DOC_EMPSER, SUBTIPO_EMPSER, FECHA_DESDE_EMPSER, FECHA_HASTA_EMPSER, INSTANTE_MODIF, INSTANTE_ALTA, US' +
        'UARIO_ALTA, USUARIO_MODIF FROM fza_empresas_series'
      'WHERE'
      '  CODIGO_SERIE_EMPSER = :CODIGO_SERIE_EMPSER')
    SQLRecCount.Strings = (
      'SELECT COUNT(*) FROM fza_empresas_series')
    Connection = dmConn.conUni
    SQL.Strings = (
      'SELECT * '
      'FROM vi_empresas_series'
      'WHERE CODIGO_EMP_EMPSER = :CODIGO_EMP_EMP')
    MasterFields = 'CODIGO_EMP_EMP'
    DetailFields = 'CODIGO_EMP_EMPSER'
    RefreshOptions = [roAfterUpdate]
    BeforeInsert = unqryRetencionesBeforeInsert
    AfterInsert = unqrySeriesAfterInsert
    BeforePost = unqrySeriesBeforePost
    Left = 272
    Top = 24
    ParamData = <
      item
        DataType = ftWideString
        Name = 'CODIGO_EMP_EMP'
        ParamType = ptInput
        Value = '007'
      end>
  end
  object dsSeries: TDataSource
    DataSet = unqrySeries
    Left = 272
    Top = 80
  end
  object dsPaises: TDataSource
    DataSet = unqryPaises
    Left = 760
    Top = 24
  end
  object unqryPaises: TUniQuery
    SQLInsert.Strings = (
      'INSERT INTO fza_historia'
      
        '  (ID, CODIGO_ART_ART, DESCRIPCION_ART, CODIGO_CLI_CLI, PRECIOVENTA_ARTICULO, FECHA, ZONA, DESCRIPCION_HISTORIA, NUMERO_FAC, LINEA_LINEA, ODONTOLOGO, SERIE_FAC)'
      'VALUES'
      
        '  (:ID, :CODIGO_ART_ART, :DESCRIPCION_ART, :CODIGO_CLI_CLI, :PRECIOVENTA_ARTICULO, :FECHA, :ZONA, :DESCRIPCION_HISTORIA, :NUMERO_FAC, :LINEA_LINEA, :ODONTOLOGO, :SERIE_FAC)')
    SQLDelete.Strings = (
      'DELETE FROM fza_historia'
      'WHERE'
      '  ID = :Old_ID')
    SQLUpdate.Strings = (
      'UPDATE fza_historia'
      'SET'
      
        '  ID = :ID, CODIGO_ART_ART = :CODIGO_ART_ART, DESCRIPCION_ART = :DESCRIPCION_ART, CODIGO_CLI_CLI = :CODIGO_CLI_CLI, PRECIOVENTA_ARTICULO = :PRECIOVENTA_ARTICULO, FECHA = :FECHA, ZONA = :ZONA, DESCRIPC' +
        'ION_HISTORIA = :DESCRIPCION_HISTORIA, NUMERO_FAC = :NUMERO_FAC, LINEA_LINEA = :LINEA_LINEA, ODONTOLOGO = :ODONTOLOGO, SERIE_FAC = :SERIE_FAC'
      'WHERE'
      '  ID = :Old_ID')
    SQLLock.Strings = (
      'SELECT * FROM fza_historia'
      'WHERE'
      '  ID = :Old_ID'
      'FOR UPDATE')
    SQLRefresh.Strings = (
      
        'SELECT ID, CODIGO_ART_ART, DESCRIPCION_ART, CODIGO_CLI_CLI, PRECIOVENTA_ARTICULO, FECHA, ZONA, DESCRIPCION_HISTORIA, NUMERO_FAC, LINEA_LINEA, ODONTOLOGO, SERIE_FAC FROM fza_historia'
      'WHERE'
      '  ID = :ID')
    SQLRecCount.Strings = (
      'SELECT COUNT(*) FROM fza_historia')
    Connection = dmConn.conUni
    SQL.Strings = (
      'select * from vi_paises'
      '')
    ReadOnly = True
    Left = 760
    Top = 88
  end
end
