inherited dmCajaValesHist: TdmCajaValesHist
  inherited unqryTablaG: TUniQuery
    SQLInsert.Strings = (
      'INSERT INTO `fza_caja_vales`'
      '  (`CODIGO_VL`, `CODIGO_PADRE_VL`, `PIN_SEGURIDAD_VL`, `ESTADO_VL`, `IMPORTE_NOMINAL_VL`, `FECHA_EMISION_VL`, `FECHA_CADUCIDAD_VL`, `CODIGO_EMPRESA_EMI_VL`, `CODIGO_ALMACEN_EMI_VL`, `CODIGO_CAJA_EMI_VL`, `NUMERO_OPERACION_EMI_VL`, `SERIE_FACTURA_EMI_VL`, `NRO_FACTURA_EMI_VL`, `FECHA_REDENCION_VL`, `IMPORTE_REDIMIDO_VL`, `CODIGO_EMPRESA_RED_VL`, `CODIGO_ALMACEN_RED_VL`, `CODIGO_CAJA_RED_VL`, `NUMERO_OPERACION_RED_VL`, `SERIE_FACTURA_RED_VL`, `NRO_FACTURA_RED_VL`, `CODIGO_CLIENTE_VL`, `OBSERVACIONES_VL`, `INSTANTEMODIF`, `INSTANTEALTA`, `USUARIOALTA`, `USUARIOMODIF`)'
      'VALUES'
      '  (:`CODIGO_VL`, :`CODIGO_PADRE_VL`, :`PIN_SEGURIDAD_VL`, :`ESTADO_VL`, :`IMPORTE_NOMINAL_VL`, :`FECHA_EMISION_VL`, :`FECHA_CADUCIDAD_VL`, :`CODIGO_EMPRESA_EMI_VL`, :`CODIGO_ALMACEN_EMI_VL`, :`CODIGO_CAJA_EMI_VL`, :`NUMERO_OPERACION_EMI_VL`, :`SERIE_FACTURA_EMI_VL`, :`NRO_FACTURA_EMI_VL`, :`FECHA_REDENCION_VL`, :`IMPORTE_REDIMIDO_VL`, :`CODIGO_EMPRESA_RED_VL`, :`CODIGO_ALMACEN_RED_VL`, :`CODIGO_CAJA_RED_VL`, :`NUMERO_OPERACION_RED_VL`, :`SERIE_FACTURA_RED_VL`, :`NRO_FACTURA_RED_VL`, :`CODIGO_CLIENTE_VL`, :`OBSERVACIONES_VL`, :`INSTANTEMODIF`, :`INSTANTEALTA`, :`USUARIOALTA`, :`USUARIOMODIF`)')
    SQLDelete.Strings = (
      'DELETE FROM `fza_caja_vales`'
      'WHERE'
      '  `CODIGO_VL` = :`Old_CODIGO_VL`')
    SQLUpdate.Strings = (
      'UPDATE `fza_caja_vales`'
      'SET'
      '  `CODIGO_VL` = :`CODIGO_VL`, `CODIGO_PADRE_VL` = :`CODIGO_PADRE_VL`, `PIN_SEGURIDAD_VL` = :`PIN_SEGURIDAD_VL`, `ESTADO_VL` = :`ESTADO_VL`, `IMPORTE_NOMINAL_VL` = :`IMPORTE_NOMINAL_VL`, `FECHA_EMISION_VL` = :`FECHA_EMISION_VL`, `FECHA_CADUCIDAD_VL` = :`FECHA_CADUCIDAD_VL`, `CODIGO_EMPRESA_EMI_VL` = :`CODIGO_EMPRESA_EMI_VL`, `CODIGO_ALMACEN_EMI_VL` = :`CODIGO_ALMACEN_EMI_VL`, `CODIGO_CAJA_EMI_VL` = :`CODIGO_CAJA_EMI_VL`, `NUMERO_OPERACION_EMI_VL` = :`NUMERO_OPERACION_EMI_VL`, `SERIE_FACTURA_EMI_VL` = :`SERIE_FACTURA_EMI_VL`, `NRO_FACTURA_EMI_VL` = :`NRO_FACTURA_EMI_VL`, `FECHA_REDENCION_VL` = :`FECHA_REDENCION_VL`, `IMPORTE_REDIMIDO_VL` = :`IMPORTE_REDIMIDO_VL`, `CODIGO_EMPRESA_RED_VL` = :`CODIGO_EMPRESA_RED_VL`, `CODIGO_ALMACEN_RED_VL` = :`CODIGO_ALMACEN_RED_VL`, `CODIGO_CAJA_RED_VL` = :`CODIGO_CAJA_RED_VL`, `NUMERO_OPERACION_RED_VL` = :`NUMERO_OPERACION_RED_VL`, `SERIE_FACTURA_RED_VL` = :`SERIE_FACTURA_RED_VL`, `NRO_FACTURA_RED_VL` = :`NRO_FACTURA_RED_VL`, `CODIGO_CLIENTE_VL` = :`CODIGO_CLIENTE_VL`, `OBSERVACIONES_VL` = :`OBSERVACIONES_VL`, `INSTANTEMODIF` = :`INSTANTEMODIF`, `INSTANTEALTA` = :`INSTANTEALTA`, `USUARIOALTA` = :`USUARIOALTA`, `USUARIOMODIF` = :`USUARIOMODIF`'
      'WHERE'
      '  `CODIGO_VL` = :`Old_CODIGO_VL`')
    SQLLock.Strings = (
      'SELECT * FROM `fza_caja_vales`'
      'WHERE'
      '  `CODIGO_VL` = :`Old_CODIGO_VL`'
      'FOR UPDATE')
    SQLRefresh.Strings = (
      'SELECT * FROM `fza_caja_vales`'
      'WHERE'
      '  `CODIGO_VL` = :`CODIGO_VL`')
    SQLRecCount.Strings = (
      'SELECT COUNT(*) FROM fza_caja_vales')
    Connection = dmConn.conUni
    SQL.Strings = (
      'SELECT *'
      'FROM fza_caja_vales'
      'ORDER BY FECHA_EMISION_VL DESC'
      '')
    Active = True
    Left = 24
  end
end
