inherited dmCajaFormasPago: TdmCajaFormasPago
  inherited unqryTablaG: TUniQuery
    SQLInsert.Strings = (
      'INSERT INTO fza_caja_formas_pago'

        '  (CODIGO_FP_CFP, DESCRIPCION_FORMA_PAGO_CFP, ESREQ_REFERENCIA_FORMA_PAGO_CFP, ESCRIPTO_FORMA_PAGO_CFP, RED_BLOCKCHAIN_FORMA_PAGO_CFP, HASH_BLOCKCHAIN_FORMA_PAGO_CFP, ESDIVISA_FORMA_PAGO_CFP, ESDEVUELVE_CAMBIO_FORMA_PAGO_CFP, ESABRE_CAJON_FORMA_PAGO_CFP, ESACTIVO_FORMA_PAGO_CFP, PORCENTAJE_COMISION_FORMA_PAGO_CFP, ESCOMISION_INCL_FORMA_PAGO_CFP, NUM_COD_DIGIT_FORMA_PAGO_CFP, ORDEN_VISUAL_FORMA_PAGO_CFP)'
      'VALUES'

        '  (:CODIGO_FP_CFP, :DESCRIPCION_FORMA_PAGO_CFP, :ESREQ_REFERENCIA_FORMA_PAGO_CFP, :ESCRIPTO_FORMA_PAGO_CFP, :RED_BLOCKCHAIN_FORMA_PAGO_CFP, :HASH_BLOCKCHAIN_FORMA_PAGO_CFP, :ESDIVISA_FORMA_PAGO_CFP, :ESDEVUELVE_CAMBIO_FORMA_PAGO_CFP, :ESABRE_CAJON_FORMA_PAGO_CFP, :ESACTIVO_FORMA_PAGO_CFP, :PORCENTAJE_COMISION_FORMA_PAGO_CFP, :ESCOMISION_INCL_FORMA_PAGO_CFP, :NUM_COD_DIGIT_FORMA_PAGO_CFP, :ORDEN_VISUAL_FORMA_PAGO_CFP)')
    SQLDelete.Strings = (
      'DELETE FROM fza_caja_formas_pago'
      'WHERE'
      '  CODIGO_FP_CFP = :Old_CODIGO_FP_CFP')
    SQLUpdate.Strings = (
      'UPDATE fza_caja_formas_pago'
      'SET'

        '  CODIGO_FP_CFP = :CODIGO_FP_CFP, DESCRIPCION_FORMA_PAGO_CFP = :DESCRIPCION_FORMA_PAGO_CFP, ESREQ_REFERENCIA_FORMA_PAGO_CFP = :ESREQ_REFERENCIA_FORMA_PAGO_CFP, ESCRIPTO_FORMA_PAGO_CFP = :ESCRIPTO_FORMA_PAGO_CFP, RED_BLOCKCHAIN_FORMA_PAGO_CFP = :RED_BLOCKCHAIN_FORMA_PAGO_CFP, HASH_BLOCKCHAIN_FORMA_PAGO_CFP = :HASH_BLOCKCHAIN_FORMA_PAGO_CFP, ESDIVISA_FORMA_PAGO_CFP = :ESDIVISA_FORMA_PAGO_CFP, ESDEVUELVE_CAMBIO_FORMA_PAGO_CFP = :ESDEVUELVE_CAMBIO_FORMA_PAGO_CFP, ESABRE_CAJON_FORMA_PAGO_CFP = :ESABRE_CAJON_FORMA_PAGO_CFP, ESACTIVO_FORMA_PAGO_CFP = :ESACTIVO_FORMA_PAGO_CFP, PORCENTAJE_COMISION_FORMA_PAGO_CFP = :PORCENTAJE_COMISION_FORMA_PAGO_CFP, ESCOMISION_INCL_FORMA_PAGO_CFP = :ESCOMISION_INCL_FORMA_PAGO_CFP, NUM_COD_DIGIT_FORMA_PAGO_CFP = :NUM_COD_DIGIT_FORMA_PAGO_CFP, ORDEN_VISUAL_FORMA_PAGO_CFP = :ORDEN_VISUAL_FORMA_PAGO_CFP'
      'WHERE'
      '  CODIGO_FP_CFP = :Old_CODIGO_FP_CFP')
    SQLLock.Strings = (
      'SELECT * FROM fza_caja_formas_pago'
      'WHERE'
      '  CODIGO_FP_CFP = :Old_CODIGO_FP_CFP'
      'FOR UPDATE')
    SQLRefresh.Strings = (
      'SELECT * FROM fza_caja_formas_pago'
      'WHERE'
      '  CODIGO_FP_CFP = :CODIGO_FP_CFP')
    SQLRecCount.Strings = (
      'SELECT COUNT(*) FROM fza_caja_formas_pago')
    Connection = dmConn.conUni
    SQL.Strings = (
      'SELECT *'
      '  FROM fza_caja_formas_pago'
      'ORDER BY ORDEN_VISUAL_FORMA_PAGO_CFP, CODIGO_FP_CFP')
    Active = True
    AfterInsert = unqryTablaGAfterInsert
    Left = 16
  end
  inherited unqryPerfiles: TUniQuery
    SQL.Strings = (
      'select *'
      'from fza_usuarios_perfiles'
      'where (KEY_USUPER = '#39'dmCajaFormasPago'#39
      'OR KEY_USUPER = '#39'frmMtoCajaFormasPago'#39')')
  end
end
