inherited dmEmpresas: TdmEmpresas
  Height = 168
  Width = 970
  PixelsPerInch = 120
  inherited unqryTablaG: TUniQuery
    SQLInsert.Strings = (
      'INSERT INTO fza_empresas'
      
        '  (CODIGO_EMP_EMP, ORDEN_EMP, ESACTIVO_EMP, RAZON_SOCIAL_EMP, NI' +
        'F_EMP, MOVIL_EMP, EMAIL_EMP, DIRECCION1_EMP, DIRECCION2_EMP, COD' +
        'IGO_POSTAL_EMP, POBLACION_EMP, PROVINCIA_EMP, CODIGO_PAI_EMP, NO' +
        'MBRE_PAI_EMP, IBAN_EMP, GRUPO_ZONA_IVA_EMP, ESRETENCIONES_EMP, E' +
        'SIVA_RECARGO_COMPRAS_EMP, ESREGIMENESPECIALAGRICOLA_EMP, CODIGO_' +
        'CERTIFICADO_EMP, TITULAR_CE' +
        'RTIFICADO_EMP, TIPO_CERTIFICADO_EMP, FECHA_DESDE_CERTIFICADO_EMP' +
        ', FECHA_HASTA_CERTIFICADO_EMP, TEXTO_LEGAL_FACTURA_EMP, INSTANTE' +
        '_MODIF, INSTANTE_ALTA, USUARIO_ALTA, USUARIO_MODIF)'
      'VALUES'
      
        '  (:CODIGO_EMP_EMP, :ORDEN_EMP, :ESACTIVO_EMP, :RAZON_SOCIAL_EMP' +
        ', :NIF_EMP, :MOVIL_EMP, :EMAIL_EMP, :DIRECCION1_EMP, :DIRECCION2' +
        '_EMP, :CODIGO_POSTAL_EMP, :POBLACION_EMP, :PROVINCIA_EMP, :CODIG' +
        'O_PAI_EMP, :NOMBRE_PAI_EMP, :IBAN_EMP, :GRUPO_ZONA_IVA_EMP, :ESR' +
        'ETENCIONES_EMP, :ESIVA_RECARGO_COMPRAS_EMP, :ESREGIMENESPECIALAG' +
        'RICOLA_EMP, :CODIGO_CERTIFIC' +
        'ADO_EMP, :TITULAR_CERTIFICADO_EMP, :TIPO_CERTIFICADO_EMP, :FECHA' +
        '_DESDE_CERTIFICADO_EMP, :FECHA_HASTA_CERTIFICADO_EMP, :TEXTO_LEG' +
        'AL_FACTURA_EMP, :INSTANTE_MODIF, :INSTANTE_ALTA, :USUARIO_ALTA, ' +
        ':USUARIO_MODIF)')
    SQLDelete.Strings = (
      'DELETE FROM fza_empresas'
      'WHERE'
      '  CODIGO_EMP_EMP = :Old_CODIGO_EMP_EMP')
    SQLUpdate.Strings = (
      'UPDATE fza_empresas'
      'SET'
      
        '  CODIGO_EMP_EMP = :CODIGO_EMP_EMP, ORDEN_EMP = :ORDEN_EMP, ESAC' +
        'TIVO_EMP = :ESACTIVO_EMP, RAZON_SOCIAL_EMP = :RAZON_SOCIAL_EMP, ' +
        'NIF_EMP = :NIF_EMP, MOVIL_EMP = :MOVIL_EMP, EMAIL_EMP = :EMAIL_E' +
        'MP, DIRECCION1_EMP = :DIRECCION1_EMP, DIRECCION2_EMP = :DIRECCIO' +
        'N2_EMP, CODIGO_POSTAL_EMP = :CODIGO_POSTAL_EMP, POBLACION_EMP = ' +
        ':POBLACION_EMP, PROVINCIA_EMP = :PROVINCIA_EMP, CODIGO_PAI_EMP =' +
        ' :CODIGO_PAI_EMP, NOMBRE_PAI_EMP = :NOMBRE_PAI_EMP, IBAN_EMP = :' +
        'IBAN_EMP, GRUPO_ZONA_IVA_EMP = :GRUPO_ZONA_IVA_EMP, ESRETENCIONE' +
        'S_EMP = :ESRETENCIONES_EMP, ESIVA_RECARGO_COMPRAS_EMP = :ESIVA_R' +
        'ECARGO_COMPRAS_EMP, ESREGIMENESPECIALAGRICOLA_EMP = :ESREGIMENE' +
        'SPECIALAGRICOLA_EMP, CODIGO_CERTIFICADO_EMP = :CODIGO_CER' +
        'TIFICADO_EMP, TITULAR_CERTIFICADO_EMP = :TITULAR_CERTIFICADO_EMP' +
        ', TIPO_CERTIFICADO_EMP = :TIPO_CERTIFICADO_EMP, FECHA_DESDE_CERT' +
        'IFICADO_EMP = :FECHA_DESDE_CERTIFICADO_EMP, FECHA_HASTA_CERTIFIC' +
        'ADO_EMP = :FECHA_HASTA_CERTIFICADO_EMP, TEXTO_LEGAL_FACTURA_EMP ' +
        '= :TEXTO_LEGAL_FACTURA_EMP, INSTANTE_MODIF = :INSTANTE_MODIF, IN' +
        'STANTE_ALTA = :INSTANTE_ALTA, USUARIO_ALTA = :USUARIO_ALTA, USUA' +
        'RIO_MODIF = :USUARIO_MODIF'
      'WHERE'
      '  CODIGO_EMP_EMP = :Old_CODIGO_EMP_EMP')
    SQLLock.Strings = (
      
        'SELECT CODIGO_EMP_EMP, ORDEN_EMP, ESACTIVO_EMP, RAZON_SOCIAL_EMP' +
        ', NIF_EMP, MOVIL_EMP, EMAIL_EMP, DIRECCION1_EMP, DIRECCION2_EMP,' +
        ' CODIGO_POSTAL_EMP, POBLACION_EMP, PROVINCIA_EMP, CODIGO_PAI_EMP' +
        ', NOMBRE_PAI_EMP, IBAN_EMP, GRUPO_ZONA_IVA_EMP, ESRETENCIONES_EM' +
        'P, ESIVA_RECARGO_COMPRAS_EMP, ESREGIMENESPECIALAGRICOLA_EMP, COD' +
        'IGO_CERTIFICADO_EMP, TITULA' +
        'R_CERTIFICADO_EMP, TIPO_CERTIFICADO_EMP, FECHA_DESDE_CERTIFICADO' +
        '_EMP, FECHA_HASTA_CERTIFICADO_EMP, TEXTO_LEGAL_FACTURA_EMP, INST' +
        'ANTE_MODIF, INSTANTE_ALTA, USUARIO_ALTA, USUARIO_MODIF FROM fza_' +
        'empresas'
      'WHERE'
      '  CODIGO_EMP_EMP = :Old_CODIGO_EMP_EMP'
      'FOR UPDATE')
    SQLRefresh.Strings = (
      
        'SELECT CODIGO_EMP_EMP, ORDEN_EMP, ESACTIVO_EMP, RAZON_SOCIAL_EMP' +
        ', NIF_EMP, MOVIL_EMP, EMAIL_EMP, DIRECCION1_EMP, DIRECCION2_EMP,' +
        ' CODIGO_POSTAL_EMP, POBLACION_EMP, PROVINCIA_EMP, CODIGO_PAI_EMP' +
        ', NOMBRE_PAI_EMP, IBAN_EMP, GRUPO_ZONA_IVA_EMP, ESRETENCIONES_EM' +
        'P, ESIVA_RECARGO_COMPRAS_EMP, ESREGIMENESPECIALAGRICOLA_EMP, COD' +
        'IGO_CERTIFICADO_EMP, TITULA' +
        'R_CERTIFICADO_EMP, TIPO_CERTIFICADO_EMP, FECHA_DESDE_CERTIFICADO' +
        '_EMP, FECHA_HASTA_CERTIFICADO_EMP, TEXTO_LEGAL_FACTURA_EMP, INST' +
        'ANTE_MODIF, INSTANTE_ALTA, USUARIO_ALTA, USUARIO_MODIF FROM fza_' +
        'empresas'
      'WHERE'
      '  CODIGO_EMP_EMP = :CODIGO_EMP_EMP')
    SQLRecCount.Strings = (
      'SELECT COUNT(*) FROM fza_empresas')
    Connection = dmConn.conUni
    SQL.Strings = (
      'SELECT *  '
      '  FROM vi_empresas '
      ' ORDER BY orden_emp')
    AfterInsert = unqryTablaGAfterInsert
    BeforeDelete = unqryTablaGBeforeDelete
    AfterDelete = unqryTablaGAfterDelete
  end
  inherited unqryPerfiles: TUniQuery
    SQL.Strings = (
      'select *'
      'from fza_usuarios_perfiles'
      'where (KEY_USUPER = '#39'dmEmpresas'#39' '
      'OR KEY_USUPER='#39'frmMtoEmpresas'#39')')
  end
  object unqryRetenciones: TUniQuery
    SQLInsert.Strings = (
      'INSERT INTO fza_empresas_retenciones'
      
        '  (CODIGO_RETENCION_EMPRET, CODIGO_EMP_EMPRET, PORCENTAJE_EMPRET' +
        ', FECHA_DESDE_EMPRET, FECHA_HASTA_EMPRET, INSTANTE_MODIF, INSTAN' +
        'TE_ALTA, USUARIO_ALTA, USUARIO_MODIF)'
      'VALUES'
      
        '  (:CODIGO_RETENCION_EMPRET, :CODIGO_EMP_EMPRET, :PORCENTAJE_EMP' +
        'RET, :FECHA_DESDE_EMPRET, :FECHA_HASTA_EMPRET, :INSTANTE_MODIF, ' +
        ':INSTANTE_ALTA, :USUARIO_ALTA, :USUARIO_MODIF)')
    SQLDelete.Strings = (
      'DELETE FROM fza_empresas_retenciones'
      'WHERE'
      '  CODIGO_RETENCION_EMPRET = :Old_CODIGO_RETENCION_EMPRET')
    SQLUpdate.Strings = (
      'UPDATE fza_empresas_retenciones'
      'SET'
      
        '  CODIGO_RETENCION_EMPRET = :CODIGO_RETENCION_EMPRET, CODIGO_EMP' +
        '_EMPRET = :CODIGO_EMP_EMPRET, PORCENTAJE_EMPRET = :PORCENTAJE_EM' +
        'PRET, FECHA_DESDE_EMPRET = :FECHA_DESDE_EMPRET, FECHA_HASTA_EMPR' +
        'ET = :FECHA_HASTA_EMPRET, INSTANTE_MODIF = :INSTANTE_MODIF, INST' +
        'ANTE_ALTA = :INSTANTE_ALTA, USUARIO_ALTA = :USUARIO_ALTA, USUARI' +
        'O_MODIF = :USUARIO_MODIF'
      'WHERE'
      '  CODIGO_RETENCION_EMPRET = :Old_CODIGO_RETENCION_EMPRET')
    SQLLock.Strings = (
      'SELECT * FROM fza_empresas_retenciones'
      'WHERE'
      '  CODIGO_RETENCION_EMPRET = :Old_CODIGO_RETENCION_EMPRET'
      'FOR UPDATE')
    SQLRefresh.Strings = (
      
        'SELECT CODIGO_RETENCION_EMPRET, CODIGO_EMP_EMPRET, PORCENTAJE_EM' +
        'PRET, FECHA_DESDE_EMPRET, FECHA_HASTA_EMPRET, INSTANTE_MODIF, IN' +
        'STANTE_ALTA, USUARIO_ALTA, USUARIO_MODIF FROM fza_empresas_reten' +
        'ciones'
      'WHERE'
      '  CODIGO_RETENCION_EMPRET = :CODIGO_RETENCION_EMPRET')
    SQLRecCount.Strings = (
      'SELECT COUNT(*) FROM fza_empresas_retenciones')
    Connection = dmConn.conUni
    SQL.Strings = (
      'SELECT * '
      'FROM vi_empresas_retenciones'
      'WHERE CODIGO_EMP_EMPRET = :CODIGO_EMP_EMP')
    MasterFields = 'CODIGO_EMP_EMP'
    DetailFields = 'CODIGO_EMP_EMPRET'
    RefreshOptions = [roAfterUpdate]
    BeforeInsert = unqryRetencionesBeforeInsert
    AfterInsert = unqryRetencionesAfterInsert
    BeforePost = unqryRetencionesBeforePost
    Left = 176
    Top = 24
    ParamData = <
      item
        DataType = ftWideString
        Name = 'CODIGO_EMP_EMP'
        ParamType = ptInput
        Value = '007'
      end>
  end
  object dsRetenciones: TDataSource
    DataSet = unqryRetenciones
    Left = 176
    Top = 80
  end
  object unqryIvas: TUniQuery
    Connection = dmConn.conUni
    SQL.Strings = (
      'SELECT * '
      'FROM VI_IVAS_GRUPOS'
      '')
    DetailFields = 'IVA_IVAGRP'
    AfterInsert = unqryRetencionesAfterInsert
    BeforePost = unqryRetencionesBeforePost
    Left = 384
    Top = 24
  end
  object dsIvas: TDataSource
    DataSet = unqryIvas
    Left = 384
    Top = 80
  end
  object dsFacturasEmpresas: TDataSource
    DataSet = unqryFacturasEmpresas
    Left = 480
    Top = 80
  end
  object unqryFacturasEmpresas: TUniQuery
    SQLInsert.Strings = (
      'INSERT INTO fza_facturas'
      
        '  (NUMERO_FAC, SERIE_FAC, FECHA_FAC, CODIGO_EMP_FAC, RAZON_SOCIA' +
        'L_EMPRESA_FAC, NIF_EMPRESA_FAC, MOVIL_EMPRESA_FAC, EMAIL_EMPRESA' +
        '_FAC, DIRECCION1_EMPRESA_FAC, DIRECCION2_EMPRESA_FAC, POBLACION_' +
        'EMPRESA_FAC, PROVINCIA_EMPRESA_FAC, CODIGO_PAI_EMPRESA_FAC, NOMB' +
        'RE_PAI_EMPRESA_FAC, CODIGO_POSTAL_EMPRESA_FAC, ESRETENCIONES_EMP' +
        'RESA_FAC, GRUPO_ZONA_IVA_EMPRESA_FAC, ESREGIMENESPECIALAGRICOLA_' +
        'EMPRESA_FAC, CODIGO_CLI_FAC, RAZON_SOCIAL_CLIENTE_FAC, NIF_CLIEN' +
        'TE_FAC, MOVIL_CLIENTE_FAC, EMAIL_CLIENTE_FAC, DIRECCION1_CLIENTE' +
        '_FAC, DIRECCION2_CLIENTE_FAC, POBLACION_CLIENTE_FAC, PROVINCIA_C' +
        'LIENTE_FAC, CODIGO_POSTAL_CLIENTE_FAC, CODIGO_PAI_CLIENTE_FAC, N' +
        'OMBRE_PAI_CLIENTE_FAC, CODIGO_IVA_FAC, ESIVA_RECARGO_CLIENTE_FAC' +
        ', ESIVA_EXENTO_CLIENTE_FAC, ESREGIMENESPECIALAGRICOLA_CLIENTE_FA' +
        'C, ESRETENCIONES_CLIENTE_FAC, TARIFA_ARTICULO_CLIENTE_FAC, ESIMP' +
        '_INCL_TARIFA_CLIENTE_FAC, ESINTRACOMUNITARIO_CLIENTE_FAC, ESIRPF' +
        '_IMP_INCL_ZONA_IVA_FAC, ESAPLICA_RE_ZONA_IVA_FAC, ESIVAAGRICOLA_' +
        'ZONA_IVA_FAC, PALABRA_REPORTS_ZONA_IVA_FAC, ESVENTA_ACTIVO_FIJO_' +
        'FAC, PORCENTAJE_IVAN_FAC, TOTAL_IVAN_FAC, PORCENTAJE_REN_FAC, TO' +
        'TAL_REN_FAC, TOTAL_BASEI_IVAN_FAC, PORCENTAJE_IVAR_FAC, TOTAL_IV' +
        'AR_FAC, PORCENTAJE_RER_FAC, TOTAL_RER_FAC, TOTAL_BASEI_IVAR_FAC,' +
        ' PORCENTAJE_IVAS_FAC, TOTAL_IVAS_FAC, PORCENTAJE_RES_FAC, TOTAL_' +
        'RES_FAC, TOTAL_BASEI_IVAS_FAC, PORCENTAJE_IVAE_FAC, TOTAL_IVAE_F' +
        'AC, PORCENTAJE_REE_FAC, TOTAL_REE_FAC, TOTAL_BASEI_IVAE_FAC, TOT' +
        'AL_BASES_FAC, TOTAL_IMPUESTOS_FAC, FORMA_PAGO_FAC, PORCENTAJE_RE' +
        'TENCION_FAC, TOTAL_RETENCION_FAC, TOTAL_LIQUIDO_FAC, NUMERO_FAC_' +
        'ABONO_FAC, SERIE_FAC_ABONO_FAC, TEXTO_LEGAL_CLIENTE_FAC, TEXTO_L' +
        'EGAL_EMPRESA_FAC, DOCUMENTO_FAC, COMENTARIOS_FAC, CONTADOR_LINEA' +
        'S_FAC, ESCREARARTICULOS_FAC, ESDESCRIPCIONES_AMP_FAC, ESFECHADEE' +
        'NTREGA_FAC, INSTANTE_MODIF, INSTANTE_ALTA, USUARIO_ALTA, USUARIO' +
        '_MODIF)'
      'VALUES'
      
        '  (:NUMERO_FAC, :SERIE_FAC, :FECHA_FAC, :CODIGO_EMP_FAC, :RAZON_' +
        'SOCIAL_EMPRESA_FAC, :NIF_EMPRESA_FAC, :MOVIL_EMPRESA_FAC, :EMAIL' +
        '_EMPRESA_FAC, :DIRECCION1_EMPRESA_FAC, :DIRECCION2_EMPRESA_FAC, ' +
        ':POBLACION_EMPRESA_FAC, :PROVINCIA_EMPRESA_FAC, :CODIGO_PAI_EMPR' +
        'ESA_FAC, :NOMBRE_PAI_EMPRESA_FAC, :CODIGO_POSTAL_EMPRESA_FAC, :E' +
        'SRETENCIONES_EMPRESA_FAC, :GRUPO_ZONA_IVA_EMPRESA_FAC, :ESREGIME' +
        'NESPECIALAGRICOLA_EMPRESA_FAC, :CODIGO_CLI_FAC, :RAZON_SOCIAL_CL' +
        'IENTE_FAC, :NIF_CLIENTE_FAC, :MOVIL_CLIENTE_FAC, :EMAIL_CLIENTE_' +
        'FAC, :DIRECCION1_CLIENTE_FAC, :DIRECCION2_CLIENTE_FAC, :POBLACIO' +
        'N_CLIENTE_FAC, :PROVINCIA_CLIENTE_FAC, :CODIGO_POSTAL_CLIENTE_FA' +
        'C, :CODIGO_PAI_CLIENTE_FAC, :NOMBRE_PAI_CLIENTE_FAC, :CODIGO_IVA' +
        '_FAC, :ESIVA_RECARGO_CLIENTE_FAC, :ESIVA_EXENTO_CLIENTE_FAC, :ES' +
        'REGIMENESPECIALAGRICOLA_CLIENTE_FAC, :ESRETENCIONES_CLIENTE_FAC,' +
        ' :TARIFA_ARTICULO_CLIENTE_FAC, :ESIMP_INCL_TARIFA_CLIENTE_FAC, :' +
        'ESINTRACOMUNITARIO_CLIENTE_FAC, :ESIRPF_IMP_INCL_ZONA_IVA_FAC, :' +
        'ESAPLICA_RE_ZONA_IVA_FAC, :ESIVAAGRICOLA_ZONA_IVA_FAC, :PALABRA_' +
        'REPORTS_ZONA_IVA_FAC, :ESVENTA_ACTIVO_FIJO_FAC, :PORCENTAJE_IVAN' +
        '_FAC, :TOTAL_IVAN_FAC, :PORCENTAJE_REN_FAC, :TOTAL_REN_FAC, :TOT' +
        'AL_BASEI_IVAN_FAC, :PORCENTAJE_IVAR_FAC, :TOTAL_IVAR_FAC, :PORCE' +
        'NTAJE_RER_FAC, :TOTAL_RER_FAC, :TOTAL_BASEI_IVAR_FAC, :PORCENTAJ' +
        'E_IVAS_FAC, :TOTAL_IVAS_FAC, :PORCENTAJE_RES_FAC, :TOTAL_RES_FAC' +
        ', :TOTAL_BASEI_IVAS_FAC, :PORCENTAJE_IVAE_FAC, :TOTAL_IVAE_FAC, ' +
        ':PORCENTAJE_REE_FAC, :TOTAL_REE_FAC, :TOTAL_BASEI_IVAE_FAC, :TOT' +
        'AL_BASES_FAC, :TOTAL_IMPUESTOS_FAC, :FORMA_PAGO_FAC, :PORCENTAJE' +
        '_RETENCION_FAC, :TOTAL_RETENCION_FAC, :TOTAL_LIQUIDO_FAC, :NUMER' +
        'O_FAC_ABONO_FAC, :SERIE_FAC_ABONO_FAC, :TEXTO_LEGAL_CLIENTE_FAC,' +
        ' :TEXTO_LEGAL_EMPRESA_FAC, :DOCUMENTO_FAC, :COMENTARIOS_FAC, :CO' +
        'NTADOR_LINEAS_FAC, :ESCREARARTICULOS_FAC, :ESDESCRIPCIONES_AMP_F' +
        'AC, :ESFECHADEENTREGA_FAC, :INSTANTE_MODIF, :INSTANTE_ALTA, :USU' +
        'ARIO_ALTA, :USUARIO_MODIF)')
    SQLDelete.Strings = (
      'DELETE FROM fza_facturas'
      'WHERE'
      '  NUMERO_FAC = :Old_NUMERO_FAC AND SERIE_FAC = :Old_SERIE_FAC')
    SQLUpdate.Strings = (
      'UPDATE fza_facturas'
      'SET'
      
        '  NUMERO_FAC = :NUMERO_FAC, SERIE_FAC = :SERIE_FAC, FECHA_FAC = ' +
        ':FECHA_FAC, CODIGO_EMP_FAC = :CODIGO_EMP_FAC, RAZON_SOCIAL_EMPRE' +
        'SA_FAC = :RAZON_SOCIAL_EMPRESA_FAC, NIF_EMPRESA_FAC = :NIF_EMPRE' +
        'SA_FAC, MOVIL_EMPRESA_FAC = :MOVIL_EMPRESA_FAC, EMAIL_EMPRESA_FA' +
        'C = :EMAIL_EMPRESA_FAC, DIRECCION1_EMPRESA_FAC = :DIRECCION1_EMP' +
        'RESA_FAC, DIRECCION2_EMPRESA_FAC = :DIRECCION2_EMPRESA_FAC, POBL' +
        'ACION_EMPRESA_FAC = :POBLACION_EMPRESA_FAC, PROVINCIA_EMPRESA_FA' +
        'C = :PROVINCIA_EMPRESA_FAC, CODIGO_PAI_EMPRESA_FAC = :CODIGO_PAI' +
        '_EMPRESA_FAC, NOMBRE_PAI_EMPRESA_FAC = :NOMBRE_PAI_EMPRESA_FAC, ' +
        'CODIGO_POSTAL_EMPRESA_FAC = :CODIGO_POSTAL_EMPRESA_FAC, ESRETENC' +
        'IONES_EMPRESA_FAC = :ESRETENCIONES_EMPRESA_FAC, GRUPO_ZONA_IVA_E' +
        'MPRESA_FAC = :GRUPO_ZONA_IVA_EMPRESA_FAC, ESREGIMENESPECIALAGRIC' +
        'OLA_EMPRESA_FAC = :ESREGIMENESPECIALAGRICOLA_EMPRESA_FAC, CODIGO' +
        '_CLI_FAC = :CODIGO_CLI_FAC, RAZON_SOCIAL_CLIENTE_FAC = :RAZON_SO' +
        'CIAL_CLIENTE_FAC, NIF_CLIENTE_FAC = :NIF_CLIENTE_FAC, MOVIL_CLIE' +
        'NTE_FAC = :MOVIL_CLIENTE_FAC, EMAIL_CLIENTE_FAC = :EMAIL_CLIENTE' +
        '_FAC, DIRECCION1_CLIENTE_FAC = :DIRECCION1_CLIENTE_FAC, DIRECCIO' +
        'N2_CLIENTE_FAC = :DIRECCION2_CLIENTE_FAC, POBLACION_CLIENTE_FAC ' +
        '= :POBLACION_CLIENTE_FAC, PROVINCIA_CLIENTE_FAC = :PROVINCIA_CLI' +
        'ENTE_FAC, CODIGO_POSTAL_CLIENTE_FAC = :CODIGO_POSTAL_CLIENTE_FAC' +
        ', CODIGO_PAI_CLIENTE_FAC = :CODIGO_PAI_CLIENTE_FAC, NOMBRE_PAI_C' +
        'LIENTE_FAC = :NOMBRE_PAI_CLIENTE_FAC, CODIGO_IVA_FAC = :CODIGO_I' +
        'VA_FAC, ESIVA_RECARGO_CLIENTE_FAC = :ESIVA_RECARGO_CLIENTE_FAC, ' +
        'ESIVA_EXENTO_CLIENTE_FAC = :ESIVA_EXENTO_CLIENTE_FAC, ESREGIMENE' +
        'SPECIALAGRICOLA_CLIENTE_FAC = :ESREGIMENESPECIALAGRICOLA_CLIENTE' +
        '_FAC, ESRETENCIONES_CLIENTE_FAC = :ESRETENCIONES_CLIENTE_FAC, TA' +
        'RIFA_ARTICULO_CLIENTE_FAC = :TARIFA_ARTICULO_CLIENTE_FAC, ESIMP_' +
        'INCL_TARIFA_CLIENTE_FAC = :ESIMP_INCL_TARIFA_CLIENTE_FAC, ESINTR' +
        'ACOMUNITARIO_CLIENTE_FAC = :ESINTRACOMUNITARIO_CLIENTE_FAC, ESIR' +
        'PF_IMP_INCL_ZONA_IVA_FAC = :ESIRPF_IMP_INCL_ZONA_IVA_FAC, ESAPLI' +
        'CA_RE_ZONA_IVA_FAC = :ESAPLICA_RE_ZONA_IVA_FAC, ESIVAAGRICOLA_ZO' +
        'NA_IVA_FAC = :ESIVAAGRICOLA_ZONA_IVA_FAC, PALABRA_REPORTS_ZONA_I' +
        'VA_FAC = :PALABRA_REPORTS_ZONA_IVA_FAC, ESVENTA_ACTIVO_FIJO_FAC ' +
        '= :ESVENTA_ACTIVO_FIJO_FAC, PORCENTAJE_IVAN_FAC = :PORCENTAJE_IV' +
        'AN_FAC, TOTAL_IVAN_FAC = :TOTAL_IVAN_FAC, PORCENTAJE_REN_FAC = :' +
        'PORCENTAJE_REN_FAC, TOTAL_REN_FAC = :TOTAL_REN_FAC, TOTAL_BASEI_' +
        'IVAN_FAC = :TOTAL_BASEI_IVAN_FAC, PORCENTAJE_IVAR_FAC = :PORCENT' +
        'AJE_IVAR_FAC, TOTAL_IVAR_FAC = :TOTAL_IVAR_FAC, PORCENTAJE_RER_F' +
        'AC = :PORCENTAJE_RER_FAC, TOTAL_RER_FAC = :TOTAL_RER_FAC, TOTAL_' +
        'BASEI_IVAR_FAC = :TOTAL_BASEI_IVAR_FAC, PORCENTAJE_IVAS_FAC = :P' +
        'ORCENTAJE_IVAS_FAC, TOTAL_IVAS_FAC = :TOTAL_IVAS_FAC, PORCENTAJE' +
        '_RES_FAC = :PORCENTAJE_RES_FAC, TOTAL_RES_FAC = :TOTAL_RES_FAC, ' +
        'TOTAL_BASEI_IVAS_FAC = :TOTAL_BASEI_IVAS_FAC, PORCENTAJE_IVAE_FA' +
        'C = :PORCENTAJE_IVAE_FAC, TOTAL_IVAE_FAC = :TOTAL_IVAE_FAC, PORC' +
        'ENTAJE_REE_FAC = :PORCENTAJE_REE_FAC, TOTAL_REE_FAC = :TOTAL_REE' +
        '_FAC, TOTAL_BASEI_IVAE_FAC = :TOTAL_BASEI_IVAE_FAC, TOTAL_BASES_' +
        'FAC = :TOTAL_BASES_FAC, TOTAL_IMPUESTOS_FAC = :TOTAL_IMPUESTOS_F' +
        'AC, FORMA_PAGO_FAC = :FORMA_PAGO_FAC, PORCENTAJE_RETENCION_FAC =' +
        ' :PORCENTAJE_RETENCION_FAC, TOTAL_RETENCION_FAC = :TOTAL_RETENCI' +
        'ON_FAC, TOTAL_LIQUIDO_FAC = :TOTAL_LIQUIDO_FAC, NUMERO_FAC_ABONO' +
        '_FAC = :NUMERO_FAC_ABONO_FAC, SERIE_FAC_ABONO_FAC = :SERIE_FAC_A' +
        'BONO_FAC, TEXTO_LEGAL_CLIENTE_FAC = :TEXTO_LEGAL_CLIENTE_FAC, TE' +
        'XTO_LEGAL_EMPRESA_FAC = :TEXTO_LEGAL_EMPRESA_FAC, DOCUMENTO_FAC ' +
        '= :DOCUMENTO_FAC, COMENTARIOS_FAC = :COMENTARIOS_FAC, CONTADOR_L' +
        'INEAS_FAC = :CONTADOR_LINEAS_FAC, ESCREARARTICULOS_FAC = :ESCREA' +
        'RARTICULOS_FAC, ESDESCRIPCIONES_AMP_FAC = :ESDESCRIPCIONES_AMP_F' +
        'AC, ESFECHADEENTREGA_FAC = :ESFECHADEENTREGA_FAC, INSTANTE_MODIF' +
        ' = :INSTANTE_MODIF, INSTANTE_ALTA = :INSTANTE_ALTA, USUARIO_ALTA' +
        ' = :USUARIO_ALTA, USUARIO_MODIF = :USUARIO_MODIF'
      'WHERE'
      '  NUMERO_FAC = :Old_NUMERO_FAC AND SERIE_FAC = :Old_SERIE_FAC')
    SQLLock.Strings = (
      
        'SELECT NUMERO_FAC, SERIE_FAC, FECHA_FAC, CODIGO_EMP_FAC, RAZON_S' +
        'OCIAL_EMPRESA_FAC, NIF_EMPRESA_FAC, MOVIL_EMPRESA_FAC, EMAIL_EMP' +
        'RESA_FAC, DIRECCION1_EMPRESA_FAC, DIRECCION2_EMPRESA_FAC, POBLAC' +
        'ION_EMPRESA_FAC, PROVINCIA_EMPRESA_FAC, CODIGO_PAI_EMPRESA_FAC, ' +
        'NOMBRE_PAI_EMPRESA_FAC, CODIGO_POSTAL_EMPRESA_FAC, ESRETENCIONES' +
        '_EMPRESA_FAC, GRUPO_ZONA_IVA_EMPRESA_FAC, ESREGIMENESPECIALAGRIC' +
        'OLA_EMPRESA_FAC, CODIGO_CLI_FAC, RAZON_SOCIAL_CLIENTE_FAC, NIF_C' +
        'LIENTE_FAC, MOVIL_CLIENTE_FAC, EMAIL_CLIENTE_FAC, DIRECCION1_CLI' +
        'ENTE_FAC, DIRECCION2_CLIENTE_FAC, POBLACION_CLIENTE_FAC, PROVINC' +
        'IA_CLIENTE_FAC, CODIGO_POSTAL_CLIENTE_FAC, CODIGO_PAI_CLIENTE_FA' +
        'C, NOMBRE_PAI_CLIENTE_FAC, CODIGO_IVA_FAC, ESIVA_RECARGO_CLIENTE' +
        '_FAC, ESIVA_EXENTO_CLIENTE_FAC, ESREGIMENESPECIALAGRICOLA_CLIENT' +
        'E_FAC, ESRETENCIONES_CLIENTE_FAC, TARIFA_ARTICULO_CLIENTE_FAC, E' +
        'SIMP_INCL_TARIFA_CLIENTE_FAC, ESINTRACOMUNITARIO_CLIENTE_FAC, ES' +
        'IRPF_IMP_INCL_ZONA_IVA_FAC, ESAPLICA_RE_ZONA_IVA_FAC, ESIVAAGRIC' +
        'OLA_ZONA_IVA_FAC, PALABRA_REPORTS_ZONA_IVA_FAC, ESVENTA_ACTIVO_F' +
        'IJO_FAC, PORCENTAJE_IVAN_FAC, TOTAL_IVAN_FAC, PORCENTAJE_REN_FAC' +
        ', TOTAL_REN_FAC, TOTAL_BASEI_IVAN_FAC, PORCENTAJE_IVAR_FAC, TOTA' +
        'L_IVAR_FAC, PORCENTAJE_RER_FAC, TOTAL_RER_FAC, TOTAL_BASEI_IVAR_' +
        'FAC, PORCENTAJE_IVAS_FAC, TOTAL_IVAS_FAC, PORCENTAJE_RES_FAC, TO' +
        'TAL_RES_FAC, TOTAL_BASEI_IVAS_FAC, PORCENTAJE_IVAE_FAC, TOTAL_IV' +
        'AE_FAC, PORCENTAJE_REE_FAC, TOTAL_REE_FAC, TOTAL_BASEI_IVAE_FAC,' +
        ' TOTAL_BASES_FAC, TOTAL_IMPUESTOS_FAC, FORMA_PAGO_FAC, PORCENTAJ' +
        'E_RETENCION_FAC, TOTAL_RETENCION_FAC, TOTAL_LIQUIDO_FAC, NUMERO_' +
        'FAC_ABONO_FAC, SERIE_FAC_ABONO_FAC, TEXTO_LEGAL_CLIENTE_FAC, TEX' +
        'TO_LEGAL_EMPRESA_FAC, DOCUMENTO_FAC, COMENTARIOS_FAC, CONTADOR_L' +
        'INEAS_FAC, ESCREARARTICULOS_FAC, ESDESCRIPCIONES_AMP_FAC, ESFECH' +
        'ADEENTREGA_FAC, INSTANTE_MODIF, INSTANTE_ALTA, USUARIO_ALTA, USU' +
        'ARIO_MODIF FROM fza_facturas'
      'WHERE'
      '  NUMERO_FAC = :Old_NUMERO_FAC AND SERIE_FAC = :Old_SERIE_FAC'
      'FOR UPDATE')
    SQLRefresh.Strings = (
      
        'SELECT NUMERO_FAC, SERIE_FAC, FECHA_FAC, CODIGO_EMP_FAC, RAZON_S' +
        'OCIAL_EMPRESA_FAC, NIF_EMPRESA_FAC, MOVIL_EMPRESA_FAC, EMAIL_EMP' +
        'RESA_FAC, DIRECCION1_EMPRESA_FAC, DIRECCION2_EMPRESA_FAC, POBLAC' +
        'ION_EMPRESA_FAC, PROVINCIA_EMPRESA_FAC, CODIGO_PAI_EMPRESA_FAC, ' +
        'NOMBRE_PAI_EMPRESA_FAC, CODIGO_POSTAL_EMPRESA_FAC, ESRETENCIONES' +
        '_EMPRESA_FAC, GRUPO_ZONA_IVA_EMPRESA_FAC, ESREGIMENESPECIALAGRIC' +
        'OLA_EMPRESA_FAC, CODIGO_CLI_FAC, RAZON_SOCIAL_CLIENTE_FAC, NIF_C' +
        'LIENTE_FAC, MOVIL_CLIENTE_FAC, EMAIL_CLIENTE_FAC, DIRECCION1_CLI' +
        'ENTE_FAC, DIRECCION2_CLIENTE_FAC, POBLACION_CLIENTE_FAC, PROVINC' +
        'IA_CLIENTE_FAC, CODIGO_POSTAL_CLIENTE_FAC, CODIGO_PAI_CLIENTE_FA' +
        'C, NOMBRE_PAI_CLIENTE_FAC, CODIGO_IVA_FAC, ESIVA_RECARGO_CLIENTE' +
        '_FAC, ESIVA_EXENTO_CLIENTE_FAC, ESREGIMENESPECIALAGRICOLA_CLIENT' +
        'E_FAC, ESRETENCIONES_CLIENTE_FAC, TARIFA_ARTICULO_CLIENTE_FAC, E' +
        'SIMP_INCL_TARIFA_CLIENTE_FAC, ESINTRACOMUNITARIO_CLIENTE_FAC, ES' +
        'IRPF_IMP_INCL_ZONA_IVA_FAC, ESAPLICA_RE_ZONA_IVA_FAC, ESIVAAGRIC' +
        'OLA_ZONA_IVA_FAC, PALABRA_REPORTS_ZONA_IVA_FAC, ESVENTA_ACTIVO_F' +
        'IJO_FAC, PORCENTAJE_IVAN_FAC, TOTAL_IVAN_FAC, PORCENTAJE_REN_FAC' +
        ', TOTAL_REN_FAC, TOTAL_BASEI_IVAN_FAC, PORCENTAJE_IVAR_FAC, TOTA' +
        'L_IVAR_FAC, PORCENTAJE_RER_FAC, TOTAL_RER_FAC, TOTAL_BASEI_IVAR_' +
        'FAC, PORCENTAJE_IVAS_FAC, TOTAL_IVAS_FAC, PORCENTAJE_RES_FAC, TO' +
        'TAL_RES_FAC, TOTAL_BASEI_IVAS_FAC, PORCENTAJE_IVAE_FAC, TOTAL_IV' +
        'AE_FAC, PORCENTAJE_REE_FAC, TOTAL_REE_FAC, TOTAL_BASEI_IVAE_FAC,' +
        ' TOTAL_BASES_FAC, TOTAL_IMPUESTOS_FAC, FORMA_PAGO_FAC, PORCENTAJ' +
        'E_RETENCION_FAC, TOTAL_RETENCION_FAC, TOTAL_LIQUIDO_FAC, NUMERO_' +
        'FAC_ABONO_FAC, SERIE_FAC_ABONO_FAC, TEXTO_LEGAL_CLIENTE_FAC, TEX' +
        'TO_LEGAL_EMPRESA_FAC, DOCUMENTO_FAC, COMENTARIOS_FAC, CONTADOR_L' +
        'INEAS_FAC, ESCREARARTICULOS_FAC, ESDESCRIPCIONES_AMP_FAC, ESFECH' +
        'ADEENTREGA_FAC, INSTANTE_MODIF, INSTANTE_ALTA, USUARIO_ALTA, USU' +
        'ARIO_MODIF FROM fza_facturas'
      'WHERE'
      '  NUMERO_FAC = :NUMERO_FAC AND SERIE_FAC = :SERIE_FAC')
    SQLRecCount.Strings = (
      'SELECT COUNT(*) FROM fza_facturas')
    Connection = dmConn.conUni
    SQL.Strings = (
      'select * from vi_fac_busquedas')
    MasterFields = 'CODIGO_EMP_EMP'
    DetailFields = 'CODIGO_EMP_FAC'
    ReadOnly = True
    Left = 480
    Top = 24
    ParamData = <
      item
        DataType = ftWideString
        Name = 'CODIGO_EMP_EMP'
        ParamType = ptInput
        Value = '007'
      end>
  end
  object dsFacturasLineasEmpresas: TDataSource
    DataSet = unqryFacturasLineasEmpresas
    Left = 625
    Top = 80
  end
  object unqryFacturasLineasEmpresas: TUniQuery
    SQLInsert.Strings = (
      'INSERT INTO fza_facturas_lineas'
      
        '  (NUMERO_FAC_FACLIN, SERIE_FAC_FACLIN, LINEA_FACLIN, CODIGO_ART' +
        '_FACLIN, CODIGO_FAM_FACLIN, NOMBRE_FAM_FACLIN, PRECIO_ULT_COMPRA' +
        '_FACLIN, CODIGO_PRV_FACLIN, RAZON_SOCIAL_PROVEEDOR_FACLIN, ESPRO' +
        'VEEDORPRINCIPAL_FACLIN, FECHA_ENTREGA_FACLIN, TIPO_CANTIDAD_ARTI' +
        'CULO_FACLIN, ESIMP_INCL_TARIFA_FACLIN, TIPO_IVA_ARTICULO_FACLIN,' +
        ' DESCRIPCION_ARTICULO_FACLIN, CODIGO_TAR_FACLIN, CANTIDAD_FACLIN' +
        ', PRECIO_SALIDA_FACLIN, PORCENTAJE_DTO_FACLIN, PRECIO_DTO_FACLIN' +
        ', PRECIO_VENTA_SIVA_ARTICULO_FACLIN, PORCENTAJE_IVA_FACLIN, PREC' +
        'IO_VENTA_CIVA_ARTICULO_FACLIN, TOTAL_FACLIN, TOTAL_FAC_SIVA_FACL' +
        'IN, INSTANTE_MODIF, INSTANTE_ALTA, USUARIO_ALTA, USUARIO_MODIF)'
      'VALUES'
      
        '  (:NUMERO_FAC_FACLIN, :SERIE_FAC_FACLIN, :LINEA_FACLIN, :CODIGO' +
        '_ART_FACLIN, :CODIGO_FAM_FACLIN, :NOMBRE_FAM_FACLIN, :PRECIO_ULT' +
        '_COMPRA_FACLIN, :CODIGO_PRV_FACLIN, :RAZON_SOCIAL_PROVEEDOR_FACL' +
        'IN, :ESPROVEEDORPRINCIPAL_FACLIN, :FECHA_ENTREGA_FACLIN, :TIPO_C' +
        'ANTIDAD_ARTICULO_FACLIN, :ESIMP_INCL_TARIFA_FACLIN, :TIPO_IVA_AR' +
        'TICULO_FACLIN, :DESCRIPCION_ARTICULO_FACLIN, :CODIGO_TAR_FACLIN,' +
        ' :CANTIDAD_FACLIN, :PRECIO_SALIDA_FACLIN, :PORCENTAJE_DTO_FACLIN' +
        ', :PRECIO_DTO_FACLIN, :PRECIO_VENTA_SIVA_ARTICULO_FACLIN, :PORCE' +
        'NTAJE_IVA_FACLIN, :PRECIO_VENTA_CIVA_ARTICULO_FACLIN, :TOTAL_FAC' +
        'LIN, :TOTAL_FAC_SIVA_FACLIN, :INSTANTE_MODIF, :INSTANTE_ALTA, :U' +
        'SUARIO_ALTA, :USUARIO_MODIF)')
    SQLDelete.Strings = (
      'DELETE FROM fza_facturas_lineas'
      'WHERE'
      
        '  NUMERO_FAC_FACLIN = :Old_NUMERO_FAC_FACLIN AND SERIE_FAC_FACLI' +
        'N = :Old_SERIE_FAC_FACLIN AND LINEA_FACLIN = :Old_LINEA_FACLIN')
    SQLUpdate.Strings = (
      'UPDATE fza_facturas_lineas'
      'SET'
      
        '  NUMERO_FAC_FACLIN = :NUMERO_FAC_FACLIN, SERIE_FAC_FACLIN = :SE' +
        'RIE_FAC_FACLIN, LINEA_FACLIN = :LINEA_FACLIN, CODIGO_ART_FACLIN ' +
        '= :CODIGO_ART_FACLIN, CODIGO_FAM_FACLIN = :CODIGO_FAM_FACLIN, NO' +
        'MBRE_FAM_FACLIN = :NOMBRE_FAM_FACLIN, PRECIO_ULT_COMPRA_FACLIN =' +
        ' :PRECIO_ULT_COMPRA_FACLIN, CODIGO_PRV_FACLIN = :CODIGO_PRV_FACL' +
        'IN, RAZON_SOCIAL_PROVEEDOR_FACLIN = :RAZON_SOCIAL_PROVEEDOR_FACL' +
        'IN, ESPROVEEDORPRINCIPAL_FACLIN = :ESPROVEEDORPRINCIPAL_FACLIN, ' +
        'FECHA_ENTREGA_FACLIN = :FECHA_ENTREGA_FACLIN, TIPO_CANTIDAD_ARTI' +
        'CULO_FACLIN = :TIPO_CANTIDAD_ARTICULO_FACLIN, ESIMP_INCL_TARIFA_' +
        'FACLIN = :ESIMP_INCL_TARIFA_FACLIN, TIPO_IVA_ARTICULO_FACLIN = :' +
        'TIPO_IVA_ARTICULO_FACLIN, DESCRIPCION_ARTICULO_FACLIN = :DESCRIP' +
        'CION_ARTICULO_FACLIN, CODIGO_TAR_FACLIN = :CODIGO_TAR_FACLIN, CA' +
        'NTIDAD_FACLIN = :CANTIDAD_FACLIN, PRECIO_SALIDA_FACLIN = :PRECIO' +
        '_SALIDA_FACLIN, PORCENTAJE_DTO_FACLIN = :PORCENTAJE_DTO_FACLIN, ' +
        'PRECIO_DTO_FACLIN = :PRECIO_DTO_FACLIN, PRECIO_VENTA_SIVA_ARTICU' +
        'LO_FACLIN = :PRECIO_VENTA_SIVA_ARTICULO_FACLIN, PORCENTAJE_IVA_F' +
        'ACLIN = :PORCENTAJE_IVA_FACLIN, PRECIO_VENTA_CIVA_ARTICULO_FACLI' +
        'N = :PRECIO_VENTA_CIVA_ARTICULO_FACLIN, TOTAL_FACLIN = :TOTAL_FA' +
        'CLIN, TOTAL_FAC_SIVA_FACLIN = :TOTAL_FAC_SIVA_FACLIN, INSTANTE_M' +
        'ODIF = :INSTANTE_MODIF, INSTANTE_ALTA = :INSTANTE_ALTA, USUARIO_' +
        'ALTA = :USUARIO_ALTA, USUARIO_MODIF = :USUARIO_MODIF'
      'WHERE'
      
        '  NUMERO_FAC_FACLIN = :Old_NUMERO_FAC_FACLIN AND SERIE_FAC_FACLI' +
        'N = :Old_SERIE_FAC_FACLIN AND LINEA_FACLIN = :Old_LINEA_FACLIN')
    SQLLock.Strings = (
      
        'SELECT NUMERO_FAC_FACLIN, SERIE_FAC_FACLIN, LINEA_FACLIN, CODIGO' +
        '_ART_FACLIN, CODIGO_FAM_FACLIN, NOMBRE_FAM_FACLIN, PRECIO_ULT_CO' +
        'MPRA_FACLIN, CODIGO_PRV_FACLIN, RAZON_SOCIAL_PROVEEDOR_FACLIN, E' +
        'SPROVEEDORPRINCIPAL_FACLIN, FECHA_ENTREGA_FACLIN, TIPO_CANTIDAD_' +
        'ARTICULO_FACLIN, ESIMP_INCL_TARIFA_FACLIN, TIPO_IVA_ARTICULO_FAC' +
        'LIN, DESCRIPCION_ARTICULO_FACLIN, CODIGO_TAR_FACLIN, CANTIDAD_FA' +
        'CLIN, PRECIO_SALIDA_FACLIN, PORCENTAJE_DTO_FACLIN, PRECIO_DTO_FA' +
        'CLIN, PRECIO_VENTA_SIVA_ARTICULO_FACLIN, PORCENTAJE_IVA_FACLIN, ' +
        'PRECIO_VENTA_CIVA_ARTICULO_FACLIN, TOTAL_FACLIN, TOTAL_FAC_SIVA_' +
        'FACLIN, INSTANTE_MODIF, INSTANTE_ALTA, USUARIO_ALTA, USUARIO_MOD' +
        'IF FROM fza_facturas_lineas'
      'WHERE'
      
        '  NUMERO_FAC_FACLIN = :Old_NUMERO_FAC_FACLIN AND SERIE_FAC_FACLI' +
        'N = :Old_SERIE_FAC_FACLIN AND LINEA_FACLIN = :Old_LINEA_FACLIN'
      'FOR UPDATE')
    SQLRefresh.Strings = (
      
        'SELECT NUMERO_FAC_FACLIN, SERIE_FAC_FACLIN, LINEA_FACLIN, CODIGO' +
        '_ART_FACLIN, CODIGO_FAM_FACLIN, NOMBRE_FAM_FACLIN, PRECIO_ULT_CO' +
        'MPRA_FACLIN, CODIGO_PRV_FACLIN, RAZON_SOCIAL_PROVEEDOR_FACLIN, E' +
        'SPROVEEDORPRINCIPAL_FACLIN, FECHA_ENTREGA_FACLIN, TIPO_CANTIDAD_' +
        'ARTICULO_FACLIN, ESIMP_INCL_TARIFA_FACLIN, TIPO_IVA_ARTICULO_FAC' +
        'LIN, DESCRIPCION_ARTICULO_FACLIN, CODIGO_TAR_FACLIN, CANTIDAD_FA' +
        'CLIN, PRECIO_SALIDA_FACLIN, PORCENTAJE_DTO_FACLIN, PRECIO_DTO_FA' +
        'CLIN, PRECIO_VENTA_SIVA_ARTICULO_FACLIN, PORCENTAJE_IVA_FACLIN, ' +
        'PRECIO_VENTA_CIVA_ARTICULO_FACLIN, TOTAL_FACLIN, TOTAL_FAC_SIVA_' +
        'FACLIN, INSTANTE_MODIF, INSTANTE_ALTA, USUARIO_ALTA, USUARIO_MOD' +
        'IF FROM fza_facturas_lineas'
      'WHERE'
      
        '  NUMERO_FAC_FACLIN = :NUMERO_FAC_FACLIN AND SERIE_FAC_FACLIN = ' +
        ':SERIE_FAC_FACLIN AND LINEA_FACLIN = :LINEA_FACLIN')
    SQLRecCount.Strings = (
      'SELECT COUNT(*) FROM fza_facturas_lineas')
    Connection = dmConn.conUni
    SQL.Strings = (
      'select *'
      'from vi_fac_lin_busquedas l'
      'inner join vi_fac_busquedas f'
      'on l.NUMERO_FAC_FACLIN = F.NUMERO_FAC'
      'AND l.SERIE_FAC_FACLIN = F.SERIE_FAC'
      '')
    MasterFields = 'CODIGO_EMP_EMP'
    DetailFields = 'CODIGO_EMP_FAC'
    ReadOnly = True
    Left = 625
    Top = 24
    ParamData = <
      item
        DataType = ftWideString
        Name = 'CODIGO_EMP_EMP'
        ParamType = ptInput
        Value = '1'
      end>
  end
  object unqrySeries: TUniQuery
    SQLInsert.Strings = (
      'INSERT INTO fza_empresas_series'
      
        '  (CODIGO_SERIE_EMPSER, CODIGO_EMP_EMPSER, CODIGO_ALM_EMPSER, CO' +
        'DIGO_CAJA_EMPSER, EMPSER, TIPO_DOC_EMPSER, SUBTIPO_EMPSER, FECHA' +
        '_DESDE_EMPSER, FECHA_HASTA_EMPSER, INSTANTE_MODIF, INSTANTE_ALTA' +
        ', USUARIO_ALTA, USUARIO_MODIF)'
      'VALUES'
      
        '  (:CODIGO_SERIE_EMPSER, :CODIGO_EMP_EMPSER, :CODIGO_ALM_EMPSER,' +
        ' :CODIGO_CAJA_EMPSER, :EMPSER, :TIPO_DOC_EMPSER, :SUBTIPO_EMPSER' +
        ', :FECHA_DESDE_EMPSER, :FECHA_HASTA_EMPSER, :INSTANTE_MODIF, :IN' +
        'STANTE_ALTA, :USUARIO_ALTA, :USUARIO_MODIF)')
    SQLDelete.Strings = (
      'DELETE FROM fza_empresas_series'
      'WHERE'
      '  CODIGO_SERIE_EMPSER = :Old_CODIGO_SERIE_EMPSER')
    SQLUpdate.Strings = (
      'UPDATE fza_empresas_series'
      'SET'
      
        '  CODIGO_SERIE_EMPSER = :CODIGO_SERIE_EMPSER, CODIGO_EMP_EMPSER ' +
        '= :CODIGO_EMP_EMPSER, CODIGO_ALM_EMPSER = :CODIGO_ALM_EMPSER, CO' +
        'DIGO_CAJA_EMPSER = :CODIGO_CAJA_EMPSER, EMPSER = :EMPSER, TIPO_D' +
        'OC_EMPSER = :TIPO_DOC_EMPSER, SUBTIPO_EMPSER = :SUBTIPO_EMPSER, ' +
        'FECHA_DESDE_EMPSER = :FECHA_DESDE_EMPSER, FECHA_HASTA_EMPSER = :' +
        'FECHA_HASTA_EMPSER, INSTANTE_MODIF = :INSTANTE_MODIF, INSTANTE_A' +
        'LTA = :INSTANTE_ALTA, USUARIO_ALTA = :USUARIO_ALTA, USUARIO_MODI' +
        'F = :USUARIO_MODIF'
      'WHERE'
      '  CODIGO_SERIE_EMPSER = :Old_CODIGO_SERIE_EMPSER')
    SQLLock.Strings = (
      
        'SELECT CODIGO_SERIE_EMPSER, CODIGO_EMP_EMPSER, CODIGO_ALM_EMPSER' +
        ', CODIGO_CAJA_EMPSER, EMPSER, TIPO_DOC_EMPSER, SUBTIPO_EMPSER, F' +
        'ECHA_DESDE_EMPSER, FECHA_HASTA_EMPSER, INSTANTE_MODIF, INSTANTE_' +
        'ALTA, USUARIO_ALTA, USUARIO_MODIF FROM fza_empresas_series'
      'WHERE'
      '  CODIGO_SERIE_EMPSER = :Old_CODIGO_SERIE_EMPSER'
      'FOR UPDATE')
    SQLRefresh.Strings = (
      
        'SELECT CODIGO_SERIE_EMPSER, CODIGO_EMP_EMPSER, CODIGO_ALM_EMPSER' +
        ', CODIGO_CAJA_EMPSER, EMPSER, TIPO_DOC_EMPSER, SUBTIPO_EMPSER, F' +
        'ECHA_DESDE_EMPSER, FECHA_HASTA_EMPSER, INSTANTE_MODIF, INSTANTE_' +
        'ALTA, USUARIO_ALTA, USUARIO_MODIF FROM fza_empresas_series'
      'WHERE'
      '  CODIGO_SERIE_EMPSER = :CODIGO_SERIE_EMPSER')
    SQLRecCount.Strings = (
      'SELECT COUNT(*) FROM fza_empresas_series')
    Connection = dmConn.conUni
    SQL.Strings = (
      'SELECT * '
      'FROM vi_empresas_series'
      'WHERE CODIGO_EMP_EMPSER = :CODIGO_EMP_EMP')
    MasterFields = 'CODIGO_EMP_EMP'
    DetailFields = 'CODIGO_EMP_EMPSER'
    RefreshOptions = [roAfterUpdate]
    BeforeInsert = unqryRetencionesBeforeInsert
    AfterInsert = unqrySeriesAfterInsert
    BeforePost = unqrySeriesBeforePost
    Left = 272
    Top = 24
    ParamData = <
      item
        DataType = ftWideString
        Name = 'CODIGO_EMP_EMP'
        ParamType = ptInput
        Value = '007'
      end>
  end
  object dsSeries: TDataSource
    DataSet = unqrySeries
    Left = 272
    Top = 80
  end
  object unqryBancos: TUniQuery
    SQLInsert.Strings = (
      'INSERT INTO fza_empresas_bancos'
      '  (CODIGO_EMPBAN, CODIGO_EMP_EMPBAN, NOMBRE_EMPBAN,'
      '   CODIGO_BAN_EMPBAN, IBAN_EMPBAN, ENTIDAD_EMPBAN, OFICINA_EMPBAN,'
      '   DIGITO_CONTROL_EMPBAN, CUENTA_EMPBAN, BIC_EMPBAN,'
      '   ESDEFECTO_COBRO_EMPBAN, ESDEFECTO_PAGO_EMPBAN, ESACTIVO_EMPBAN,'
      '   ORDEN_EMPBAN, INSTANTE_MODIF, INSTANTE_ALTA, USUARIO_ALTA,'
      '   USUARIO_MODIF)'
      'VALUES'
      '  (:CODIGO_EMPBAN, :CODIGO_EMP_EMPBAN, :NOMBRE_EMPBAN,'
      '   :CODIGO_BAN_EMPBAN, :IBAN_EMPBAN, :ENTIDAD_EMPBAN, :OFICINA_EMPBAN,'
      '   :DIGITO_CONTROL_EMPBAN, :CUENTA_EMPBAN, :BIC_EMPBAN,'
      '   :ESDEFECTO_COBRO_EMPBAN, :ESDEFECTO_PAGO_EMPBAN, :ESACTIVO_EMPBAN,'
      '   :ORDEN_EMPBAN, :INSTANTE_MODIF, :INSTANTE_ALTA, :USUARIO_ALTA,'
      '   :USUARIO_MODIF)')
    SQLDelete.Strings = (
      'DELETE FROM fza_empresas_bancos'
      'WHERE'
      '  CODIGO_EMPBAN = :Old_CODIGO_EMPBAN')
    SQLUpdate.Strings = (
      'UPDATE fza_empresas_bancos'
      'SET'
      '  NOMBRE_EMPBAN = :NOMBRE_EMPBAN,'
      '  CODIGO_BAN_EMPBAN = :CODIGO_BAN_EMPBAN, IBAN_EMPBAN = :IBAN_EMPBAN,'
      '  ENTIDAD_EMPBAN = :ENTIDAD_EMPBAN, OFICINA_EMPBAN = :OFICINA_EMPBAN,'
      '  DIGITO_CONTROL_EMPBAN = :DIGITO_CONTROL_EMPBAN,'
      '  CUENTA_EMPBAN = :CUENTA_EMPBAN, BIC_EMPBAN = :BIC_EMPBAN,'
      '  ESDEFECTO_COBRO_EMPBAN = :ESDEFECTO_COBRO_EMPBAN,'
      '  ESDEFECTO_PAGO_EMPBAN = :ESDEFECTO_PAGO_EMPBAN,'
      '  ESACTIVO_EMPBAN = :ESACTIVO_EMPBAN, ORDEN_EMPBAN = :ORDEN_EMPBAN,'
      '  INSTANTE_MODIF = :INSTANTE_MODIF, USUARIO_MODIF = :USUARIO_MODIF'
      'WHERE'
      '  CODIGO_EMPBAN = :Old_CODIGO_EMPBAN')
    SQLRefresh.Strings = (
      'SELECT * FROM vi_empresas_bancos'
      'WHERE'
      '  CODIGO_EMPBAN = :CODIGO_EMPBAN')
    Connection = dmConn.conUni
    SQL.Strings = (
      'SELECT * '
      'FROM vi_empresas_bancos'
      'WHERE CODIGO_EMP_EMPBAN = :CODIGO_EMP_EMP')
    MasterFields = 'CODIGO_EMP_EMP'
    DetailFields = 'CODIGO_EMP_EMPBAN'
    RefreshOptions = [roAfterUpdate]
    BeforeInsert = unqryRetencionesBeforeInsert
    AfterInsert = unqryBancosAfterInsert
    BeforePost = unqryBancosBeforePost
    Left = 360
    Top = 24
    ParamData = <
      item
        DataType = ftWideString
        Name = 'CODIGO_EMP_EMP'
        ParamType = ptInput
        Value = '007'
      end>
  end
  object dsBancos: TDataSource
    DataSet = unqryBancos
    Left = 360
    Top = 80
  end
  object dsPaises: TDataSource
    DataSet = unqryPaises
    Left = 760
    Top = 24
  end
  object unqryPaises: TUniQuery
    SQLInsert.Strings = (
      'INSERT INTO fza_historia'
      
        '  (ID, CODIGO_ART_ART, DESCRIPCION_ART, CODIGO_CLI_CLI, PRECIOVE' +
        'NTA_ARTICULO, FECHA, ZONA, DESCRIPCION_HISTORIA, NUMERO_FAC, LIN' +
        'EA_LINEA, ODONTOLOGO, SERIE_FAC)'
      'VALUES'
      
        '  (:ID, :CODIGO_ART_ART, :DESCRIPCION_ART, :CODIGO_CLI_CLI, :PRE' +
        'CIOVENTA_ARTICULO, :FECHA, :ZONA, :DESCRIPCION_HISTORIA, :NUMERO' +
        '_FAC, :LINEA_LINEA, :ODONTOLOGO, :SERIE_FAC)')
    SQLDelete.Strings = (
      'DELETE FROM fza_historia'
      'WHERE'
      '  ID = :Old_ID')
    SQLUpdate.Strings = (
      'UPDATE fza_historia'
      'SET'
      
        '  ID = :ID, CODIGO_ART_ART = :CODIGO_ART_ART, DESCRIPCION_ART = ' +
        ':DESCRIPCION_ART, CODIGO_CLI_CLI = :CODIGO_CLI_CLI, PRECIOVENTA_' +
        'ARTICULO = :PRECIOVENTA_ARTICULO, FECHA = :FECHA, ZONA = :ZONA, ' +
        'DESCRIPCION_HISTORIA = :DESCRIPCION_HISTORIA, NUMERO_FAC = :NUME' +
        'RO_FAC, LINEA_LINEA = :LINEA_LINEA, ODONTOLOGO = :ODONTOLOGO, SE' +
        'RIE_FAC = :SERIE_FAC'
      'WHERE'
      '  ID = :Old_ID')
    SQLLock.Strings = (
      'SELECT * FROM fza_historia'
      'WHERE'
      '  ID = :Old_ID'
      'FOR UPDATE')
    SQLRefresh.Strings = (
      
        'SELECT ID, CODIGO_ART_ART, DESCRIPCION_ART, CODIGO_CLI_CLI, PREC' +
        'IOVENTA_ARTICULO, FECHA, ZONA, DESCRIPCION_HISTORIA, NUMERO_FAC,' +
        ' LINEA_LINEA, ODONTOLOGO, SERIE_FAC FROM fza_historia'
      'WHERE'
      '  ID = :ID')
    SQLRecCount.Strings = (
      'SELECT COUNT(*) FROM fza_historia')
    Connection = dmConn.conUni
    SQL.Strings = (
      'select * from vi_paises'
      '')
    ReadOnly = True
    Left = 760
    Top = 88
  end
end
