inherited dmClientes: TdmClientes
  Height = 356
  Width = 989
  PixelsPerInch = 120
  inherited unqryTablaG: TUniQuery
    SQLInsert.Strings = (
      'INSERT INTO fza_clientes'
      
        '  (CODIGO_CLI_CLI, ESACTIVO_CLI, ORDEN_CLI, RAZON_SOCIAL_CLI, NI' +
        'F_CLI, MOVIL_CLI, EMAIL_CLI, DIRECCION1_CLI, DIRECCION2_CLI, POB' +
        'LACION_CLI, PROVINCIA_CLI, CODIGO_POSTAL_CLI, CODIGO_PAI_CLI, NO' +
        'MBRE_PAI_CLI, OBSERVACIONES_CLI, REFERENCIA_CLI, CONTACTO_CLI, T' +
        'ELEFONO_CONTACTO_CLI, TELEFONO_CLI, IBAN_CLI, ESIVA_RECARGO_CLI,' +
        ' ESRETENCIONES_CLI, TOTAL_LIMITE_CREDITO_CLI, ESPERMITE_DEUDA_CL' +
        'I, TOTAL_DEUDA_CLI, ESIVA_EXENTO_CLI, ESINTRACOMUNITARIO_CLI, ES' +
        'REGIMENESPECIALAGRICOLA_CLI, CODIGO_FP_CLI, TARIFA_ARTICULO_CLI,' +
        ' SERIE_CON_CLI, TEXTO_LEGAL_FACTURA_CLI, INSTANTE_MODIF, INSTANT' +
        'E_ALTA, USUARIO_ALTA, USUARIO_MODIF)'
      'VALUES'
      
        '  (:CODIGO_CLI_CLI, :ESACTIVO_CLI, :ORDEN_CLI, :RAZON_SOCIAL_CLI' +
        ', :NIF_CLI, :MOVIL_CLI, :EMAIL_CLI, :DIRECCION1_CLI, :DIRECCION2' +
        '_CLI, :POBLACION_CLI, :PROVINCIA_CLI, :CODIGO_POSTAL_CLI, :CODIG' +
        'O_PAI_CLI, :NOMBRE_PAI_CLI, :OBSERVACIONES_CLI, :REFERENCIA_CLI,' +
        ' :CONTACTO_CLI, :TELEFONO_CONTACTO_CLI, :TELEFONO_CLI, :IBAN_CLI' +
        ', :ESIVA_RECARGO_CLI, :ESRETENCIONES_CLI, :TOTAL_LIMITE_CREDITO_' +
        'CLI, :ESPERMITE_DEUDA_CLI, :TOTAL_DEUDA_CLI, :ESIVA_EXENTO_CLI, ' +
        ':ESINTRACOMUNITARIO_CLI, :ESREGIMENESPECIALAGRICOLA_CLI, :CODIGO' +
        '_FP_CLI, :TARIFA_ARTICULO_CLI, :SERIE_CON_CLI, :TEXTO_LEGAL_FACT' +
        'URA_CLI, :INSTANTE_MODIF, :INSTANTE_ALTA, :USUARIO_ALTA, :USUARI' +
        'O_MODIF)')
    SQLDelete.Strings = (
      'DELETE FROM fza_clientes'
      'WHERE'
      '  CODIGO_CLI_CLI = :Old_CODIGO_CLI_CLI')
    SQLUpdate.Strings = (
      'UPDATE fza_clientes'
      'SET'
      
        '  CODIGO_CLI_CLI = :CODIGO_CLI_CLI, ESACTIVO_CLI = :ESACTIVO_CLI' +
        ', ORDEN_CLI = :ORDEN_CLI, RAZON_SOCIAL_CLI = :RAZON_SOCIAL_CLI, ' +
        'NIF_CLI = :NIF_CLI, MOVIL_CLI = :MOVIL_CLI, EMAIL_CLI = :EMAIL_C' +
        'LI, DIRECCION1_CLI = :DIRECCION1_CLI, DIRECCION2_CLI = :DIRECCIO' +
        'N2_CLI, POBLACION_CLI = :POBLACION_CLI, PROVINCIA_CLI = :PROVINC' +
        'IA_CLI, CODIGO_POSTAL_CLI = :CODIGO_POSTAL_CLI, CODIGO_PAI_CLI =' +
        ' :CODIGO_PAI_CLI, NOMBRE_PAI_CLI = :NOMBRE_PAI_CLI, OBSERVACIONE' +
        'S_CLI = :OBSERVACIONES_CLI, REFERENCIA_CLI = :REFERENCIA_CLI, CO' +
        'NTACTO_CLI = :CONTACTO_CLI, TELEFONO_CONTACTO_CLI = :TELEFONO_CO' +
        'NTACTO_CLI, TELEFONO_CLI = :TELEFONO_CLI, IBAN_CLI = :IBAN_CLI, ' +
        'ESIVA_RECARGO_CLI = :ESIVA_RECARGO_CLI, ESRETENCIONES_CLI = :ESR' +
        'ETENCIONES_CLI, TOTAL_LIMITE_CREDITO_CLI = :TOTAL_LIMITE_CREDITO' +
        '_CLI, ESPERMITE_DEUDA_CLI = :ESPERMITE_DEUDA_CLI, TOTAL_DEUDA_CL' +
        'I = :TOTAL_DEUDA_CLI, ESIVA_EXENTO_CLI = :ESIVA_EXENTO_CLI, ESIN' +
        'TRACOMUNITARIO_CLI = :ESINTRACOMUNITARIO_CLI, ESREGIMENESPECIALA' +
        'GRICOLA_CLI = :ESREGIMENESPECIALAGRICOLA_CLI, CODIGO_FP_CLI = :C' +
        'ODIGO_FP_CLI, TARIFA_ARTICULO_CLI = :TARIFA_ARTICULO_CLI, SERIE_' +
        'CON_CLI = :SERIE_CON_CLI, TEXTO_LEGAL_FACTURA_CLI = :TEXTO_LEGAL' +
        '_FACTURA_CLI, INSTANTE_MODIF = :INSTANTE_MODIF, INSTANTE_ALTA = ' +
        ':INSTANTE_ALTA, USUARIO_ALTA = :USUARIO_ALTA, USUARIO_MODIF = :U' +
        'SUARIO_MODIF'
      'WHERE'
      '  CODIGO_CLI_CLI = :Old_CODIGO_CLI_CLI')
    SQLLock.Strings = (
      
        'SELECT CODIGO_CLI_CLI, ESACTIVO_CLI, ORDEN_CLI, RAZON_SOCIAL_CLI' +
        ', NIF_CLI, MOVIL_CLI, EMAIL_CLI, DIRECCION1_CLI, DIRECCION2_CLI,' +
        ' POBLACION_CLI, PROVINCIA_CLI, CODIGO_POSTAL_CLI, CODIGO_PAI_CLI' +
        ', NOMBRE_PAI_CLI, OBSERVACIONES_CLI, REFERENCIA_CLI, CONTACTO_CL' +
        'I, TELEFONO_CONTACTO_CLI, TELEFONO_CLI, IBAN_CLI, ESIVA_RECARGO_' +
        'CLI, ESRETENCIONES_CLI, TOTAL_LIMITE_CREDITO_CLI, ESPERMITE_DEUD' +
        'A_CLI, TOTAL_DEUDA_CLI, ESIVA_EXENTO_CLI, ESINTRACOMUNITARIO_CLI' +
        ', ESREGIMENESPECIALAGRICOLA_CLI, CODIGO_FP_CLI, TARIFA_ARTICULO_' +
        'CLI, SERIE_CON_CLI, TEXTO_LEGAL_FACTURA_CLI, INSTANTE_MODIF, INS' +
        'TANTE_ALTA, USUARIO_ALTA, USUARIO_MODIF FROM fza_clientes'
      'WHERE'
      '  CODIGO_CLI_CLI = :Old_CODIGO_CLI_CLI'
      'FOR UPDATE')
    SQLRefresh.Strings = (
      
        'SELECT CODIGO_CLI_CLI, ESACTIVO_CLI, ORDEN_CLI, RAZON_SOCIAL_CLI' +
        ', NIF_CLI, MOVIL_CLI, EMAIL_CLI, DIRECCION1_CLI, DIRECCION2_CLI,' +
        ' POBLACION_CLI, PROVINCIA_CLI, CODIGO_POSTAL_CLI, CODIGO_PAI_CLI' +
        ', NOMBRE_PAI_CLI, OBSERVACIONES_CLI, REFERENCIA_CLI, CONTACTO_CL' +
        'I, TELEFONO_CONTACTO_CLI, TELEFONO_CLI, IBAN_CLI, ESIVA_RECARGO_' +
        'CLI, ESRETENCIONES_CLI, TOTAL_LIMITE_CREDITO_CLI, ESPERMITE_DEUD' +
        'A_CLI, TOTAL_DEUDA_CLI, ESIVA_EXENTO_CLI, ESINTRACOMUNITARIO_CLI' +
        ', ESREGIMENESPECIALAGRICOLA_CLI, CODIGO_FP_CLI, TARIFA_ARTICULO_' +
        'CLI, SERIE_CON_CLI, TEXTO_LEGAL_FACTURA_CLI, INSTANTE_MODIF, INS' +
        'TANTE_ALTA, USUARIO_ALTA, USUARIO_MODIF FROM fza_clientes'
      'WHERE'
      '  CODIGO_CLI_CLI = :CODIGO_CLI_CLI')
    SQLRecCount.Strings = (
      'SELECT COUNT(*) FROM fza_clientes')
    Connection = dmConn.conUni
    SQL.Strings = (
      'select * from vi_clientes')
    Active = True
    AfterInsert = unqryTablaGAfterInsert
    BeforeDelete = unqryTablaGBeforeDelete
    Left = 56
    Top = 32
  end
  inherited unqryPerfiles: TUniQuery
    SQL.Strings = (
      'select *'
      'from fza_usuarios_perfiles'
      'where KEY_USUPER = '#39'Nothing'#39)
    Left = 144
    Top = 32
  end
  inherited dsPerfiles: TDataSource
    Left = 144
    Top = 88
  end
  object dsFormasPago: TDataSource
    DataSet = unqryFormaPago
    Left = 224
    Top = 32
  end
  object unqryFormaPago: TUniQuery
    SQLInsert.Strings = (
      'INSERT INTO fza_historia'
      
        '  (ID, CODIGO_ART_ART, DESCRIPCION_ART, CODIGO_CLI_CLI, PRECIOVE' +
        'NTA_ARTICULO, FECHA, ZONA, DESCRIPCION_HISTORIA, NUMERO_FAC, LIN' +
        'EA_LINEA, ODONTOLOGO, SERIE_FAC)'
      'VALUES'
      
        '  (:ID, :CODIGO_ART_ART, :DESCRIPCION_ART, :CODIGO_CLI_CLI, :PRE' +
        'CIOVENTA_ARTICULO, :FECHA, :ZONA, :DESCRIPCION_HISTORIA, :NUMERO' +
        '_FAC, :LINEA_LINEA, :ODONTOLOGO, :SERIE_FAC)')
    SQLDelete.Strings = (
      'DELETE FROM fza_historia'
      'WHERE'
      '  ID = :Old_ID')
    SQLUpdate.Strings = (
      'UPDATE fza_historia'
      'SET'
      
        '  ID = :ID, CODIGO_ART_ART = :CODIGO_ART_ART, DESCRIPCION_ART = ' +
        ':DESCRIPCION_ART, CODIGO_CLI_CLI = :CODIGO_CLI_CLI, PRECIOVENTA_' +
        'ARTICULO = :PRECIOVENTA_ARTICULO, FECHA = :FECHA, ZONA = :ZONA, ' +
        'DESCRIPCION_HISTORIA = :DESCRIPCION_HISTORIA, NUMERO_FAC = :NUME' +
        'RO_FAC, LINEA_LINEA = :LINEA_LINEA, ODONTOLOGO = :ODONTOLOGO, SE' +
        'RIE_FAC = :SERIE_FAC'
      'WHERE'
      '  ID = :Old_ID')
    SQLLock.Strings = (
      'SELECT * FROM fza_historia'
      'WHERE'
      '  ID = :Old_ID'
      'FOR UPDATE')
    SQLRefresh.Strings = (
      
        'SELECT ID, CODIGO_ART_ART, DESCRIPCION_ART, CODIGO_CLI_CLI, PREC' +
        'IOVENTA_ARTICULO, FECHA, ZONA, DESCRIPCION_HISTORIA, NUMERO_FAC,' +
        ' LINEA_LINEA, ODONTOLOGO, SERIE_FAC FROM fza_historia'
      'WHERE'
      '  ID = :ID')
    SQLRecCount.Strings = (
      'SELECT COUNT(*) FROM fza_historia')
    Connection = dmConn.conUni
    SQL.Strings = (
      'select * from vi_formapago'
      '')
    ReadOnly = True
    Left = 224
    Top = 96
  end
  object dsEmpresasBancos: TDataSource
    DataSet = unqryEmpresasBancos
    Left = 128
    Top = 152
  end
  object unqryEmpresasBancos: TUniQuery
    Connection = dmConn.conUni
    SQL.Strings = (
      'select * from vi_empresas_bancos'
      'where ESACTIVO_EMPBAN = '#39'S'#39)
    ReadOnly = True
    Left = 128
    Top = 200
  end
  object dsTarifas: TDataSource
    DataSet = unqryTarifas
    Left = 320
    Top = 32
  end
  object unqryTarifas: TUniQuery
    SQLInsert.Strings = (
      'INSERT INTO fza_historia'
      
        '  (ID, CODIGO_ART_ART, DESCRIPCION_ART, CODIGO_CLI_CLI, PRECIOVE' +
        'NTA_ARTICULO, FECHA, ZONA, DESCRIPCION_HISTORIA, NUMERO_FAC, LIN' +
        'EA_LINEA, ODONTOLOGO, SERIE_FAC)'
      'VALUES'
      
        '  (:ID, :CODIGO_ART_ART, :DESCRIPCION_ART, :CODIGO_CLI_CLI, :PRE' +
        'CIOVENTA_ARTICULO, :FECHA, :ZONA, :DESCRIPCION_HISTORIA, :NUMERO' +
        '_FAC, :LINEA_LINEA, :ODONTOLOGO, :SERIE_FAC)')
    SQLDelete.Strings = (
      'DELETE FROM fza_historia'
      'WHERE'
      '  ID = :Old_ID')
    SQLUpdate.Strings = (
      'UPDATE fza_historia'
      'SET'
      
        '  ID = :ID, CODIGO_ART_ART = :CODIGO_ART_ART, DESCRIPCION_ART = ' +
        ':DESCRIPCION_ART, CODIGO_CLI_CLI = :CODIGO_CLI_CLI, PRECIOVENTA_' +
        'ARTICULO = :PRECIOVENTA_ARTICULO, FECHA = :FECHA, ZONA = :ZONA, ' +
        'DESCRIPCION_HISTORIA = :DESCRIPCION_HISTORIA, NUMERO_FAC = :NUME' +
        'RO_FAC, LINEA_LINEA = :LINEA_LINEA, ODONTOLOGO = :ODONTOLOGO, SE' +
        'RIE_FAC = :SERIE_FAC'
      'WHERE'
      '  ID = :Old_ID')
    SQLLock.Strings = (
      'SELECT * FROM fza_historia'
      'WHERE'
      '  ID = :Old_ID'
      'FOR UPDATE')
    SQLRefresh.Strings = (
      
        'SELECT ID, CODIGO_ART_ART, DESCRIPCION_ART, CODIGO_CLI_CLI, PREC' +
        'IOVENTA_ARTICULO, FECHA, ZONA, DESCRIPCION_HISTORIA, NUMERO_FAC,' +
        ' LINEA_LINEA, ODONTOLOGO, SERIE_FAC FROM fza_historia'
      'WHERE'
      '  ID = :ID')
    SQLRecCount.Strings = (
      'SELECT COUNT(*) FROM fza_historia')
    Connection = dmConn.conUni
    SQL.Strings = (
      'select * from vi_tarifas'
      '')
    ReadOnly = True
    Left = 320
    Top = 96
  end
  object dsFacturasClientes: TDataSource
    DataSet = unqryFacturasClientes
    Left = 408
    Top = 32
  end
  object unqryFacturasClientes: TUniQuery
    SQLInsert.Strings = (
      'INSERT INTO FZA_FACTURAS'
      
        '  (NUMERO_FAC, SERIE_FAC, FECHA_FAC, CODIGO_EMP_FAC, RAZON_SOCIA' +
        'L_EMPRESA_FAC, NIF_EMPRESA_FAC, MOVIL_EMPRESA_FAC, EMAIL_EMPRESA' +
        '_FAC, DIRECCION1_EMPRESA_FAC, DIRECCION2_EMPRESA_FAC, POBLACION_' +
        'EMPRESA_FAC, PROVINCIA_EMPRESA_FAC, CODIGO_PAI_EMPRESA_FAC, NOMB' +
        'RE_PAI_EMPRESA_FAC, CODIGO_POSTAL_EMPRESA_FAC, ESRETENCIONES_EMP' +
        'RESA_FAC, GRUPO_ZONA_IVA_EMPRESA_FAC, ESREGIMENESPECIALAGRICOLA_' +
        'EMPRESA_FAC, CODIGO_CLI_FAC, RAZON_SOCIAL_CLIENTE_FAC, NIF_CLIEN' +
        'TE_FAC, MOVIL_CLIENTE_FAC, EMAIL_CLIENTE_FAC, DIRECCION1_CLIENTE' +
        '_FAC, DIRECCION2_CLIENTE_FAC, POBLACION_CLIENTE_FAC, PROVINCIA_C' +
        'LIENTE_FAC, CODIGO_POSTAL_CLIENTE_FAC, CODIGO_PAI_CLIENTE_FAC, N' +
        'OMBRE_PAI_CLIENTE_FAC, CODIGO_IVA_FAC, ESIVA_RECARGO_CLIENTE_FAC' +
        ', ESIVA_EXENTO_CLIENTE_FAC, ESREGIMENESPECIALAGRICOLA_CLIENTE_FA' +
        'C, ESRETENCIONES_CLIENTE_FAC, TARIFA_ARTICULO_CLIENTE_FAC, ESIMP' +
        '_INCL_TARIFA_CLIENTE_FAC, ESINTRACOMUNITARIO_CLIENTE_FAC, ESIRPF' +
        '_IMP_INCL_ZONA_IVA_FAC, ESAPLICA_RE_ZONA_IVA_FAC, ESIVAAGRICOLA_' +
        'ZONA_IVA_FAC, PALABRA_REPORTS_ZONA_IVA_FAC, ESVENTA_ACTIVO_FIJO_' +
        'FAC, PORCENTAJE_IVAN_FAC, TOTAL_IVAN_FAC, PORCENTAJE_REN_FAC, TO' +
        'TAL_REN_FAC, TOTAL_BASEI_IVAN_FAC, PORCENTAJE_IVAR_FAC, TOTAL_IV' +
        'AR_FAC, PORCENTAJE_RER_FAC, TOTAL_RER_FAC, TOTAL_BASEI_IVAR_FAC,' +
        ' PORCENTAJE_IVAS_FAC, TOTAL_IVAS_FAC, PORCENTAJE_RES_FAC, TOTAL_' +
        'RES_FAC, TOTAL_BASEI_IVAS_FAC, PORCENTAJE_IVAE_FAC, TOTAL_IVAE_F' +
        'AC, PORCENTAJE_REE_FAC, TOTAL_REE_FAC, TOTAL_BASEI_IVAE_FAC, TOT' +
        'AL_BASES_FAC, TOTAL_IMPUESTOS_FAC, FORMA_PAGO_FAC, PORCENTAJE_RE' +
        'TENCION_FAC, TOTAL_RETENCION_FAC, TOTAL_LIQUIDO_FAC, NUMERO_FAC_' +
        'ABONO_FAC, SERIE_FAC_ABONO_FAC, TEXTO_LEGAL_CLIENTE_FAC, TEXTO_L' +
        'EGAL_EMPRESA_FAC, DOCUMENTO_FAC, COMENTARIOS_FAC, CONTADOR_LINEA' +
        'S_FAC, ESCREARARTICULOS_FAC, ESDESCRIPCIONES_AMP_FAC, ESFECHADEE' +
        'NTREGA_FAC, INSTANTE_MODIF, INSTANTE_ALTA, USUARIO_ALTA, USUARIO' +
        '_MODIF)'
      'VALUES'
      
        '  (:NUMERO_FAC, :SERIE_FAC, :FECHA_FAC, :CODIGO_EMP_FAC, :RAZON_' +
        'SOCIAL_EMPRESA_FAC, :NIF_EMPRESA_FAC, :MOVIL_EMPRESA_FAC, :EMAIL' +
        '_EMPRESA_FAC, :DIRECCION1_EMPRESA_FAC, :DIRECCION2_EMPRESA_FAC, ' +
        ':POBLACION_EMPRESA_FAC, :PROVINCIA_EMPRESA_FAC, :CODIGO_PAI_EMPR' +
        'ESA_FAC, :NOMBRE_PAI_EMPRESA_FAC, :CODIGO_POSTAL_EMPRESA_FAC, :E' +
        'SRETENCIONES_EMPRESA_FAC, :GRUPO_ZONA_IVA_EMPRESA_FAC, :ESREGIME' +
        'NESPECIALAGRICOLA_EMPRESA_FAC, :CODIGO_CLI_FAC, :RAZON_SOCIAL_CL' +
        'IENTE_FAC, :NIF_CLIENTE_FAC, :MOVIL_CLIENTE_FAC, :EMAIL_CLIENTE_' +
        'FAC, :DIRECCION1_CLIENTE_FAC, :DIRECCION2_CLIENTE_FAC, :POBLACIO' +
        'N_CLIENTE_FAC, :PROVINCIA_CLIENTE_FAC, :CODIGO_POSTAL_CLIENTE_FA' +
        'C, :CODIGO_PAI_CLIENTE_FAC, :NOMBRE_PAI_CLIENTE_FAC, :CODIGO_IVA' +
        '_FAC, :ESIVA_RECARGO_CLIENTE_FAC, :ESIVA_EXENTO_CLIENTE_FAC, :ES' +
        'REGIMENESPECIALAGRICOLA_CLIENTE_FAC, :ESRETENCIONES_CLIENTE_FAC,' +
        ' :TARIFA_ARTICULO_CLIENTE_FAC, :ESIMP_INCL_TARIFA_CLIENTE_FAC, :' +
        'ESINTRACOMUNITARIO_CLIENTE_FAC, :ESIRPF_IMP_INCL_ZONA_IVA_FAC, :' +
        'ESAPLICA_RE_ZONA_IVA_FAC, :ESIVAAGRICOLA_ZONA_IVA_FAC, :PALABRA_' +
        'REPORTS_ZONA_IVA_FAC, :ESVENTA_ACTIVO_FIJO_FAC, :PORCENTAJE_IVAN' +
        '_FAC, :TOTAL_IVAN_FAC, :PORCENTAJE_REN_FAC, :TOTAL_REN_FAC, :TOT' +
        'AL_BASEI_IVAN_FAC, :PORCENTAJE_IVAR_FAC, :TOTAL_IVAR_FAC, :PORCE' +
        'NTAJE_RER_FAC, :TOTAL_RER_FAC, :TOTAL_BASEI_IVAR_FAC, :PORCENTAJ' +
        'E_IVAS_FAC, :TOTAL_IVAS_FAC, :PORCENTAJE_RES_FAC, :TOTAL_RES_FAC' +
        ', :TOTAL_BASEI_IVAS_FAC, :PORCENTAJE_IVAE_FAC, :TOTAL_IVAE_FAC, ' +
        ':PORCENTAJE_REE_FAC, :TOTAL_REE_FAC, :TOTAL_BASEI_IVAE_FAC, :TOT' +
        'AL_BASES_FAC, :TOTAL_IMPUESTOS_FAC, :FORMA_PAGO_FAC, :PORCENTAJE' +
        '_RETENCION_FAC, :TOTAL_RETENCION_FAC, :TOTAL_LIQUIDO_FAC, :NUMER' +
        'O_FAC_ABONO_FAC, :SERIE_FAC_ABONO_FAC, :TEXTO_LEGAL_CLIENTE_FAC,' +
        ' :TEXTO_LEGAL_EMPRESA_FAC, :DOCUMENTO_FAC, :COMENTARIOS_FAC, :CO' +
        'NTADOR_LINEAS_FAC, :ESCREARARTICULOS_FAC, :ESDESCRIPCIONES_AMP_F' +
        'AC, :ESFECHADEENTREGA_FAC, :INSTANTE_MODIF, :INSTANTE_ALTA, :USU' +
        'ARIO_ALTA, :USUARIO_MODIF)')
    SQLDelete.Strings = (
      'DELETE FROM FZA_FACTURAS'
      'WHERE'
      '  NUMERO_FAC = :Old_NUMERO_FAC AND SERIE_FAC = :Old_SERIE_FAC')
    SQLUpdate.Strings = (
      'UPDATE FZA_FACTURAS'
      'SET'
      
        '  NUMERO_FAC = :NUMERO_FAC, SERIE_FAC = :SERIE_FAC, FECHA_FAC = ' +
        ':FECHA_FAC, CODIGO_EMP_FAC = :CODIGO_EMP_FAC, RAZON_SOCIAL_EMPRE' +
        'SA_FAC = :RAZON_SOCIAL_EMPRESA_FAC, NIF_EMPRESA_FAC = :NIF_EMPRE' +
        'SA_FAC, MOVIL_EMPRESA_FAC = :MOVIL_EMPRESA_FAC, EMAIL_EMPRESA_FA' +
        'C = :EMAIL_EMPRESA_FAC, DIRECCION1_EMPRESA_FAC = :DIRECCION1_EMP' +
        'RESA_FAC, DIRECCION2_EMPRESA_FAC = :DIRECCION2_EMPRESA_FAC, POBL' +
        'ACION_EMPRESA_FAC = :POBLACION_EMPRESA_FAC, PROVINCIA_EMPRESA_FA' +
        'C = :PROVINCIA_EMPRESA_FAC, CODIGO_PAI_EMPRESA_FAC = :CODIGO_PAI' +
        '_EMPRESA_FAC, NOMBRE_PAI_EMPRESA_FAC = :NOMBRE_PAI_EMPRESA_FAC, ' +
        'CODIGO_POSTAL_EMPRESA_FAC = :CODIGO_POSTAL_EMPRESA_FAC, ESRETENC' +
        'IONES_EMPRESA_FAC = :ESRETENCIONES_EMPRESA_FAC, GRUPO_ZONA_IVA_E' +
        'MPRESA_FAC = :GRUPO_ZONA_IVA_EMPRESA_FAC, ESREGIMENESPECIALAGRIC' +
        'OLA_EMPRESA_FAC = :ESREGIMENESPECIALAGRICOLA_EMPRESA_FAC, CODIGO' +
        '_CLI_FAC = :CODIGO_CLI_FAC, RAZON_SOCIAL_CLIENTE_FAC = :RAZON_SO' +
        'CIAL_CLIENTE_FAC, NIF_CLIENTE_FAC = :NIF_CLIENTE_FAC, MOVIL_CLIE' +
        'NTE_FAC = :MOVIL_CLIENTE_FAC, EMAIL_CLIENTE_FAC = :EMAIL_CLIENTE' +
        '_FAC, DIRECCION1_CLIENTE_FAC = :DIRECCION1_CLIENTE_FAC, DIRECCIO' +
        'N2_CLIENTE_FAC = :DIRECCION2_CLIENTE_FAC, POBLACION_CLIENTE_FAC ' +
        '= :POBLACION_CLIENTE_FAC, PROVINCIA_CLIENTE_FAC = :PROVINCIA_CLI' +
        'ENTE_FAC, CODIGO_POSTAL_CLIENTE_FAC = :CODIGO_POSTAL_CLIENTE_FAC' +
        ', CODIGO_PAI_CLIENTE_FAC = :CODIGO_PAI_CLIENTE_FAC, NOMBRE_PAI_C' +
        'LIENTE_FAC = :NOMBRE_PAI_CLIENTE_FAC, CODIGO_IVA_FAC = :CODIGO_I' +
        'VA_FAC, ESIVA_RECARGO_CLIENTE_FAC = :ESIVA_RECARGO_CLIENTE_FAC, ' +
        'ESIVA_EXENTO_CLIENTE_FAC = :ESIVA_EXENTO_CLIENTE_FAC, ESREGIMENE' +
        'SPECIALAGRICOLA_CLIENTE_FAC = :ESREGIMENESPECIALAGRICOLA_CLIENTE' +
        '_FAC, ESRETENCIONES_CLIENTE_FAC = :ESRETENCIONES_CLIENTE_FAC, TA' +
        'RIFA_ARTICULO_CLIENTE_FAC = :TARIFA_ARTICULO_CLIENTE_FAC, ESIMP_' +
        'INCL_TARIFA_CLIENTE_FAC = :ESIMP_INCL_TARIFA_CLIENTE_FAC, ESINTR' +
        'ACOMUNITARIO_CLIENTE_FAC = :ESINTRACOMUNITARIO_CLIENTE_FAC, ESIR' +
        'PF_IMP_INCL_ZONA_IVA_FAC = :ESIRPF_IMP_INCL_ZONA_IVA_FAC, ESAPLI' +
        'CA_RE_ZONA_IVA_FAC = :ESAPLICA_RE_ZONA_IVA_FAC, ESIVAAGRICOLA_ZO' +
        'NA_IVA_FAC = :ESIVAAGRICOLA_ZONA_IVA_FAC, PALABRA_REPORTS_ZONA_I' +
        'VA_FAC = :PALABRA_REPORTS_ZONA_IVA_FAC, ESVENTA_ACTIVO_FIJO_FAC ' +
        '= :ESVENTA_ACTIVO_FIJO_FAC, PORCENTAJE_IVAN_FAC = :PORCENTAJE_IV' +
        'AN_FAC, TOTAL_IVAN_FAC = :TOTAL_IVAN_FAC, PORCENTAJE_REN_FAC = :' +
        'PORCENTAJE_REN_FAC, TOTAL_REN_FAC = :TOTAL_REN_FAC, TOTAL_BASEI_' +
        'IVAN_FAC = :TOTAL_BASEI_IVAN_FAC, PORCENTAJE_IVAR_FAC = :PORCENT' +
        'AJE_IVAR_FAC, TOTAL_IVAR_FAC = :TOTAL_IVAR_FAC, PORCENTAJE_RER_F' +
        'AC = :PORCENTAJE_RER_FAC, TOTAL_RER_FAC = :TOTAL_RER_FAC, TOTAL_' +
        'BASEI_IVAR_FAC = :TOTAL_BASEI_IVAR_FAC, PORCENTAJE_IVAS_FAC = :P' +
        'ORCENTAJE_IVAS_FAC, TOTAL_IVAS_FAC = :TOTAL_IVAS_FAC, PORCENTAJE' +
        '_RES_FAC = :PORCENTAJE_RES_FAC, TOTAL_RES_FAC = :TOTAL_RES_FAC, ' +
        'TOTAL_BASEI_IVAS_FAC = :TOTAL_BASEI_IVAS_FAC, PORCENTAJE_IVAE_FA' +
        'C = :PORCENTAJE_IVAE_FAC, TOTAL_IVAE_FAC = :TOTAL_IVAE_FAC, PORC' +
        'ENTAJE_REE_FAC = :PORCENTAJE_REE_FAC, TOTAL_REE_FAC = :TOTAL_REE' +
        '_FAC, TOTAL_BASEI_IVAE_FAC = :TOTAL_BASEI_IVAE_FAC, TOTAL_BASES_' +
        'FAC = :TOTAL_BASES_FAC, TOTAL_IMPUESTOS_FAC = :TOTAL_IMPUESTOS_F' +
        'AC, FORMA_PAGO_FAC = :FORMA_PAGO_FAC, PORCENTAJE_RETENCION_FAC =' +
        ' :PORCENTAJE_RETENCION_FAC, TOTAL_RETENCION_FAC = :TOTAL_RETENCI' +
        'ON_FAC, TOTAL_LIQUIDO_FAC = :TOTAL_LIQUIDO_FAC, NUMERO_FAC_ABONO' +
        '_FAC = :NUMERO_FAC_ABONO_FAC, SERIE_FAC_ABONO_FAC = :SERIE_FAC_A' +
        'BONO_FAC, TEXTO_LEGAL_CLIENTE_FAC = :TEXTO_LEGAL_CLIENTE_FAC, TE' +
        'XTO_LEGAL_EMPRESA_FAC = :TEXTO_LEGAL_EMPRESA_FAC, DOCUMENTO_FAC ' +
        '= :DOCUMENTO_FAC, COMENTARIOS_FAC = :COMENTARIOS_FAC, CONTADOR_L' +
        'INEAS_FAC = :CONTADOR_LINEAS_FAC, ESCREARARTICULOS_FAC = :ESCREA' +
        'RARTICULOS_FAC, ESDESCRIPCIONES_AMP_FAC = :ESDESCRIPCIONES_AMP_F' +
        'AC, ESFECHADEENTREGA_FAC = :ESFECHADEENTREGA_FAC, INSTANTE_MODIF' +
        ' = :INSTANTE_MODIF, INSTANTE_ALTA = :INSTANTE_ALTA, USUARIO_ALTA' +
        ' = :USUARIO_ALTA, USUARIO_MODIF = :USUARIO_MODIF'
      'WHERE'
      '  NUMERO_FAC = :Old_NUMERO_FAC AND SERIE_FAC = :Old_SERIE_FAC')
    SQLLock.Strings = (
      
        'SELECT NUMERO_FAC, SERIE_FAC, FECHA_FAC, CODIGO_EMP_FAC, RAZON_S' +
        'OCIAL_EMPRESA_FAC, NIF_EMPRESA_FAC, MOVIL_EMPRESA_FAC, EMAIL_EMP' +
        'RESA_FAC, DIRECCION1_EMPRESA_FAC, DIRECCION2_EMPRESA_FAC, POBLAC' +
        'ION_EMPRESA_FAC, PROVINCIA_EMPRESA_FAC, CODIGO_PAI_EMPRESA_FAC, ' +
        'NOMBRE_PAI_EMPRESA_FAC, CODIGO_POSTAL_EMPRESA_FAC, ESRETENCIONES' +
        '_EMPRESA_FAC, GRUPO_ZONA_IVA_EMPRESA_FAC, ESREGIMENESPECIALAGRIC' +
        'OLA_EMPRESA_FAC, CODIGO_CLI_FAC, RAZON_SOCIAL_CLIENTE_FAC, NIF_C' +
        'LIENTE_FAC, MOVIL_CLIENTE_FAC, EMAIL_CLIENTE_FAC, DIRECCION1_CLI' +
        'ENTE_FAC, DIRECCION2_CLIENTE_FAC, POBLACION_CLIENTE_FAC, PROVINC' +
        'IA_CLIENTE_FAC, CODIGO_POSTAL_CLIENTE_FAC, CODIGO_PAI_CLIENTE_FA' +
        'C, NOMBRE_PAI_CLIENTE_FAC, CODIGO_IVA_FAC, ESIVA_RECARGO_CLIENTE' +
        '_FAC, ESIVA_EXENTO_CLIENTE_FAC, ESREGIMENESPECIALAGRICOLA_CLIENT' +
        'E_FAC, ESRETENCIONES_CLIENTE_FAC, TARIFA_ARTICULO_CLIENTE_FAC, E' +
        'SIMP_INCL_TARIFA_CLIENTE_FAC, ESINTRACOMUNITARIO_CLIENTE_FAC, ES' +
        'IRPF_IMP_INCL_ZONA_IVA_FAC, ESAPLICA_RE_ZONA_IVA_FAC, ESIVAAGRIC' +
        'OLA_ZONA_IVA_FAC, PALABRA_REPORTS_ZONA_IVA_FAC, ESVENTA_ACTIVO_F' +
        'IJO_FAC, PORCENTAJE_IVAN_FAC, TOTAL_IVAN_FAC, PORCENTAJE_REN_FAC' +
        ', TOTAL_REN_FAC, TOTAL_BASEI_IVAN_FAC, PORCENTAJE_IVAR_FAC, TOTA' +
        'L_IVAR_FAC, PORCENTAJE_RER_FAC, TOTAL_RER_FAC, TOTAL_BASEI_IVAR_' +
        'FAC, PORCENTAJE_IVAS_FAC, TOTAL_IVAS_FAC, PORCENTAJE_RES_FAC, TO' +
        'TAL_RES_FAC, TOTAL_BASEI_IVAS_FAC, PORCENTAJE_IVAE_FAC, TOTAL_IV' +
        'AE_FAC, PORCENTAJE_REE_FAC, TOTAL_REE_FAC, TOTAL_BASEI_IVAE_FAC,' +
        ' TOTAL_BASES_FAC, TOTAL_IMPUESTOS_FAC, FORMA_PAGO_FAC, PORCENTAJ' +
        'E_RETENCION_FAC, TOTAL_RETENCION_FAC, TOTAL_LIQUIDO_FAC, NUMERO_' +
        'FAC_ABONO_FAC, SERIE_FAC_ABONO_FAC, TEXTO_LEGAL_CLIENTE_FAC, TEX' +
        'TO_LEGAL_EMPRESA_FAC, DOCUMENTO_FAC, COMENTARIOS_FAC, CONTADOR_L' +
        'INEAS_FAC, ESCREARARTICULOS_FAC, ESDESCRIPCIONES_AMP_FAC, ESFECH' +
        'ADEENTREGA_FAC, INSTANTE_MODIF, INSTANTE_ALTA, USUARIO_ALTA, USU' +
        'ARIO_MODIF FROM FZA_FACTURAS'
      'WHERE'
      '  NUMERO_FAC = :Old_NUMERO_FAC AND SERIE_FAC = :Old_SERIE_FAC'
      'FOR UPDATE')
    SQLRefresh.Strings = (
      
        'SELECT NUMERO_FAC, SERIE_FAC, FECHA_FAC, CODIGO_EMP_FAC, RAZON_S' +
        'OCIAL_EMPRESA_FAC, NIF_EMPRESA_FAC, MOVIL_EMPRESA_FAC, EMAIL_EMP' +
        'RESA_FAC, DIRECCION1_EMPRESA_FAC, DIRECCION2_EMPRESA_FAC, POBLAC' +
        'ION_EMPRESA_FAC, PROVINCIA_EMPRESA_FAC, CODIGO_PAI_EMPRESA_FAC, ' +
        'NOMBRE_PAI_EMPRESA_FAC, CODIGO_POSTAL_EMPRESA_FAC, ESRETENCIONES' +
        '_EMPRESA_FAC, GRUPO_ZONA_IVA_EMPRESA_FAC, ESREGIMENESPECIALAGRIC' +
        'OLA_EMPRESA_FAC, CODIGO_CLI_FAC, RAZON_SOCIAL_CLIENTE_FAC, NIF_C' +
        'LIENTE_FAC, MOVIL_CLIENTE_FAC, EMAIL_CLIENTE_FAC, DIRECCION1_CLI' +
        'ENTE_FAC, DIRECCION2_CLIENTE_FAC, POBLACION_CLIENTE_FAC, PROVINC' +
        'IA_CLIENTE_FAC, CODIGO_POSTAL_CLIENTE_FAC, CODIGO_PAI_CLIENTE_FA' +
        'C, NOMBRE_PAI_CLIENTE_FAC, CODIGO_IVA_FAC, ESIVA_RECARGO_CLIENTE' +
        '_FAC, ESIVA_EXENTO_CLIENTE_FAC, ESREGIMENESPECIALAGRICOLA_CLIENT' +
        'E_FAC, ESRETENCIONES_CLIENTE_FAC, TARIFA_ARTICULO_CLIENTE_FAC, E' +
        'SIMP_INCL_TARIFA_CLIENTE_FAC, ESINTRACOMUNITARIO_CLIENTE_FAC, ES' +
        'IRPF_IMP_INCL_ZONA_IVA_FAC, ESAPLICA_RE_ZONA_IVA_FAC, ESIVAAGRIC' +
        'OLA_ZONA_IVA_FAC, PALABRA_REPORTS_ZONA_IVA_FAC, ESVENTA_ACTIVO_F' +
        'IJO_FAC, PORCENTAJE_IVAN_FAC, TOTAL_IVAN_FAC, PORCENTAJE_REN_FAC' +
        ', TOTAL_REN_FAC, TOTAL_BASEI_IVAN_FAC, PORCENTAJE_IVAR_FAC, TOTA' +
        'L_IVAR_FAC, PORCENTAJE_RER_FAC, TOTAL_RER_FAC, TOTAL_BASEI_IVAR_' +
        'FAC, PORCENTAJE_IVAS_FAC, TOTAL_IVAS_FAC, PORCENTAJE_RES_FAC, TO' +
        'TAL_RES_FAC, TOTAL_BASEI_IVAS_FAC, PORCENTAJE_IVAE_FAC, TOTAL_IV' +
        'AE_FAC, PORCENTAJE_REE_FAC, TOTAL_REE_FAC, TOTAL_BASEI_IVAE_FAC,' +
        ' TOTAL_BASES_FAC, TOTAL_IMPUESTOS_FAC, FORMA_PAGO_FAC, PORCENTAJ' +
        'E_RETENCION_FAC, TOTAL_RETENCION_FAC, TOTAL_LIQUIDO_FAC, NUMERO_' +
        'FAC_ABONO_FAC, SERIE_FAC_ABONO_FAC, TEXTO_LEGAL_CLIENTE_FAC, TEX' +
        'TO_LEGAL_EMPRESA_FAC, DOCUMENTO_FAC, COMENTARIOS_FAC, CONTADOR_L' +
        'INEAS_FAC, ESCREARARTICULOS_FAC, ESDESCRIPCIONES_AMP_FAC, ESFECH' +
        'ADEENTREGA_FAC, INSTANTE_MODIF, INSTANTE_ALTA, USUARIO_ALTA, USU' +
        'ARIO_MODIF FROM FZA_FACTURAS'
      'WHERE'
      '  NUMERO_FAC = :NUMERO_FAC AND SERIE_FAC = :SERIE_FAC')
    SQLRecCount.Strings = (
      'SELECT COUNT(*) FROM FZA_FACTURAS')
    Connection = dmConn.conUni
    SQL.Strings = (
      'select * from vi_fac_busquedas')
    MasterFields = 'CODIGO_CLI_CLI'
    DetailFields = 'CODIGO_CLI_FAC'
    ReadOnly = True
    Left = 408
    Top = 96
  end
  object dsFacturasLineasClientes: TDataSource
    DataSet = unqryFacturasLineasClientes
    Left = 544
    Top = 32
  end
  object unqryFacturasLineasClientes: TUniQuery
    SQLInsert.Strings = (
      'INSERT INTO FZA_FACTURAS_LINEAS'
      
        '  (NUMERO_FAC_FACLIN, SERIE_FAC_FACLIN, LINEA_FACLIN, CODIGO_ART' +
        '_FACLIN, CODIGO_FAM_FACLIN, NOMBRE_FAM_FACLIN, PRECIO_ULT_COMPRA' +
        '_FACLIN, CODIGO_PRV_FACLIN, RAZON_SOCIAL_PROVEEDOR_FACLIN, ESPRO' +
        'VEEDORPRINCIPAL_FACLIN, FECHA_ENTREGA_FACLIN, TIPO_CANTIDAD_ARTI' +
        'CULO_FACLIN, ESIMP_INCL_TARIFA_FACLIN, TIPO_IVA_ARTICULO_FACLIN,' +
        ' DESCRIPCION_ARTICULO_FACLIN, CODIGO_TAR_FACLIN, CANTIDAD_FACLIN' +
        ', PRECIO_SALIDA_FACLIN, PORCENTAJE_DTO_FACLIN, PRECIO_DTO_FACLIN' +
        ', PRECIO_VENTA_SIVA_ARTICULO_FACLIN, PORCENTAJE_IVA_FACLIN, PREC' +
        'IO_VENTA_CIVA_ARTICULO_FACLIN, TOTAL_FACLIN, TOTAL_FAC_SIVA_FACL' +
        'IN, INSTANTE_MODIF, INSTANTE_ALTA, USUARIO_ALTA, USUARIO_MODIF)'
      'VALUES'
      
        '  (:NUMERO_FAC_FACLIN, :SERIE_FAC_FACLIN, :LINEA_FACLIN, :CODIGO' +
        '_ART_FACLIN, :CODIGO_FAM_FACLIN, :NOMBRE_FAM_FACLIN, :PRECIO_ULT' +
        '_COMPRA_FACLIN, :CODIGO_PRV_FACLIN, :RAZON_SOCIAL_PROVEEDOR_FACL' +
        'IN, :ESPROVEEDORPRINCIPAL_FACLIN, :FECHA_ENTREGA_FACLIN, :TIPO_C' +
        'ANTIDAD_ARTICULO_FACLIN, :ESIMP_INCL_TARIFA_FACLIN, :TIPO_IVA_AR' +
        'TICULO_FACLIN, :DESCRIPCION_ARTICULO_FACLIN, :CODIGO_TAR_FACLIN,' +
        ' :CANTIDAD_FACLIN, :PRECIO_SALIDA_FACLIN, :PORCENTAJE_DTO_FACLIN' +
        ', :PRECIO_DTO_FACLIN, :PRECIO_VENTA_SIVA_ARTICULO_FACLIN, :PORCE' +
        'NTAJE_IVA_FACLIN, :PRECIO_VENTA_CIVA_ARTICULO_FACLIN, :TOTAL_FAC' +
        'LIN, :TOTAL_FAC_SIVA_FACLIN, :INSTANTE_MODIF, :INSTANTE_ALTA, :U' +
        'SUARIO_ALTA, :USUARIO_MODIF)')
    SQLDelete.Strings = (
      'DELETE FROM FZA_FACTURAS_LINEAS'
      'WHERE'
      
        '  NUMERO_FAC_FACLIN = :Old_NUMERO_FAC_FACLIN AND SERIE_FAC_FACLI' +
        'N = :Old_SERIE_FAC_FACLIN AND LINEA_FACLIN = :Old_LINEA_FACLIN')
    SQLUpdate.Strings = (
      'UPDATE FZA_FACTURAS_LINEAS'
      'SET'
      
        '  NUMERO_FAC_FACLIN = :NUMERO_FAC_FACLIN, SERIE_FAC_FACLIN = :SE' +
        'RIE_FAC_FACLIN, LINEA_FACLIN = :LINEA_FACLIN, CODIGO_ART_FACLIN ' +
        '= :CODIGO_ART_FACLIN, CODIGO_FAM_FACLIN = :CODIGO_FAM_FACLIN, NO' +
        'MBRE_FAM_FACLIN = :NOMBRE_FAM_FACLIN, PRECIO_ULT_COMPRA_FACLIN =' +
        ' :PRECIO_ULT_COMPRA_FACLIN, CODIGO_PRV_FACLIN = :CODIGO_PRV_FACL' +
        'IN, RAZON_SOCIAL_PROVEEDOR_FACLIN = :RAZON_SOCIAL_PROVEEDOR_FACL' +
        'IN, ESPROVEEDORPRINCIPAL_FACLIN = :ESPROVEEDORPRINCIPAL_FACLIN, ' +
        'FECHA_ENTREGA_FACLIN = :FECHA_ENTREGA_FACLIN, TIPO_CANTIDAD_ARTI' +
        'CULO_FACLIN = :TIPO_CANTIDAD_ARTICULO_FACLIN, ESIMP_INCL_TARIFA_' +
        'FACLIN = :ESIMP_INCL_TARIFA_FACLIN, TIPO_IVA_ARTICULO_FACLIN = :' +
        'TIPO_IVA_ARTICULO_FACLIN, DESCRIPCION_ARTICULO_FACLIN = :DESCRIP' +
        'CION_ARTICULO_FACLIN, CODIGO_TAR_FACLIN = :CODIGO_TAR_FACLIN, CA' +
        'NTIDAD_FACLIN = :CANTIDAD_FACLIN, PRECIO_SALIDA_FACLIN = :PRECIO' +
        '_SALIDA_FACLIN, PORCENTAJE_DTO_FACLIN = :PORCENTAJE_DTO_FACLIN, ' +
        'PRECIO_DTO_FACLIN = :PRECIO_DTO_FACLIN, PRECIO_VENTA_SIVA_ARTICU' +
        'LO_FACLIN = :PRECIO_VENTA_SIVA_ARTICULO_FACLIN, PORCENTAJE_IVA_F' +
        'ACLIN = :PORCENTAJE_IVA_FACLIN, PRECIO_VENTA_CIVA_ARTICULO_FACLI' +
        'N = :PRECIO_VENTA_CIVA_ARTICULO_FACLIN, TOTAL_FACLIN = :TOTAL_FA' +
        'CLIN, TOTAL_FAC_SIVA_FACLIN = :TOTAL_FAC_SIVA_FACLIN, INSTANTE_M' +
        'ODIF = :INSTANTE_MODIF, INSTANTE_ALTA = :INSTANTE_ALTA, USUARIO_' +
        'ALTA = :USUARIO_ALTA, USUARIO_MODIF = :USUARIO_MODIF'
      'WHERE'
      
        '  NUMERO_FAC_FACLIN = :Old_NUMERO_FAC_FACLIN AND SERIE_FAC_FACLI' +
        'N = :Old_SERIE_FAC_FACLIN AND LINEA_FACLIN = :Old_LINEA_FACLIN')
    SQLLock.Strings = (
      
        'SELECT NUMERO_FAC_FACLIN, SERIE_FAC_FACLIN, LINEA_FACLIN, CODIGO' +
        '_ART_FACLIN, CODIGO_FAM_FACLIN, NOMBRE_FAM_FACLIN, PRECIO_ULT_CO' +
        'MPRA_FACLIN, CODIGO_PRV_FACLIN, RAZON_SOCIAL_PROVEEDOR_FACLIN, E' +
        'SPROVEEDORPRINCIPAL_FACLIN, FECHA_ENTREGA_FACLIN, TIPO_CANTIDAD_' +
        'ARTICULO_FACLIN, ESIMP_INCL_TARIFA_FACLIN, TIPO_IVA_ARTICULO_FAC' +
        'LIN, DESCRIPCION_ARTICULO_FACLIN, CODIGO_TAR_FACLIN, CANTIDAD_FA' +
        'CLIN, PRECIO_SALIDA_FACLIN, PORCENTAJE_DTO_FACLIN, PRECIO_DTO_FA' +
        'CLIN, PRECIO_VENTA_SIVA_ARTICULO_FACLIN, PORCENTAJE_IVA_FACLIN, ' +
        'PRECIO_VENTA_CIVA_ARTICULO_FACLIN, TOTAL_FACLIN, TOTAL_FAC_SIVA_' +
        'FACLIN, INSTANTE_MODIF, INSTANTE_ALTA, USUARIO_ALTA, USUARIO_MOD' +
        'IF FROM FZA_FACTURAS_LINEAS'
      'WHERE'
      
        '  NUMERO_FAC_FACLIN = :Old_NUMERO_FAC_FACLIN AND SERIE_FAC_FACLI' +
        'N = :Old_SERIE_FAC_FACLIN AND LINEA_FACLIN = :Old_LINEA_FACLIN'
      'FOR UPDATE')
    SQLRefresh.Strings = (
      
        'SELECT NUMERO_FAC_FACLIN, SERIE_FAC_FACLIN, LINEA_FACLIN, CODIGO' +
        '_ART_FACLIN, CODIGO_FAM_FACLIN, NOMBRE_FAM_FACLIN, PRECIO_ULT_CO' +
        'MPRA_FACLIN, CODIGO_PRV_FACLIN, RAZON_SOCIAL_PROVEEDOR_FACLIN, E' +
        'SPROVEEDORPRINCIPAL_FACLIN, FECHA_ENTREGA_FACLIN, TIPO_CANTIDAD_' +
        'ARTICULO_FACLIN, ESIMP_INCL_TARIFA_FACLIN, TIPO_IVA_ARTICULO_FAC' +
        'LIN, DESCRIPCION_ARTICULO_FACLIN, CODIGO_TAR_FACLIN, CANTIDAD_FA' +
        'CLIN, PRECIO_SALIDA_FACLIN, PORCENTAJE_DTO_FACLIN, PRECIO_DTO_FA' +
        'CLIN, PRECIO_VENTA_SIVA_ARTICULO_FACLIN, PORCENTAJE_IVA_FACLIN, ' +
        'PRECIO_VENTA_CIVA_ARTICULO_FACLIN, TOTAL_FACLIN, TOTAL_FAC_SIVA_' +
        'FACLIN, INSTANTE_MODIF, INSTANTE_ALTA, USUARIO_ALTA, USUARIO_MOD' +
        'IF FROM FZA_FACTURAS_LINEAS'
      'WHERE'
      
        '  NUMERO_FAC_FACLIN = :NUMERO_FAC_FACLIN AND SERIE_FAC_FACLIN = ' +
        ':SERIE_FAC_FACLIN AND LINEA_FACLIN = :LINEA_FACLIN')
    SQLRecCount.Strings = (
      'SELECT COUNT(*) FROM FZA_FACTURAS_LINEAS')
    Connection = dmConn.conUni
    SQL.Strings = (
      'select *'
      'from vi_fac_lin_busquedas l'
      'inner join vi_fac_busquedas f'
      'on l.NUMERO_FAC_FACLIN = F.NUMERO_FAC'
      'AND l.SERIE_FAC_FACLIN = F.SERIE_FAC'
      '')
    MasterFields = 'CODIGO_CLI_CLI'
    DetailFields = 'CODIGO_CLI_FAC'
    ReadOnly = True
    Left = 544
    Top = 96
    ParamData = <
      item
        DataType = ftWideString
        Name = 'CODIGO_CLI_CLI'
        ParamType = ptInput
        Value = 'AGRICULTOR'
      end>
  end
  object cdsEtiquetas: TClientDataSet
    Aggregates = <>
    AutoCalcFields = False
    Params = <>
    Left = 800
    Top = 24
  end
  object dtstprvEtiquetas: TDataSetProvider
    DataSet = unqryCliPrint
    Constraints = False
    Options = []
    Left = 800
    Top = 96
  end
  object unqryCliPrint: TUniQuery
    Connection = dmConn.conUni
    SQL.Strings = (
      'select * from vi_clientes')
    BeforeInsert = unqryTablaGBeforeInsert
    AfterInsert = unqryTablaGAfterInsert
    AfterPost = unqryTablaGAfterPost
    BeforePost = unqryTablaGBeforePost
    BeforeDelete = unqryTablaGBeforeDelete
    Left = 712
    Top = 32
  end
  object dsEtiquetas: TDataSource
    DataSet = unqryCliPrint
    Left = 800
    Top = 168
  end
  object fxdsEtiquetas: TfrxDBDataset
    Description = 'Etiquetas'
    UserName = 'Etiquetas'
    CloseDataSource = False
    DataSet = cdsEtiquetas
    BCDToCurrency = False
    DataSetOptions = []
    Left = 800
    Top = 232
  end
  object dsPaises: TDataSource
    DataSet = unqryPaises
    Left = 640
    Top = 32
  end
  object unqryPaises: TUniQuery
    SQLInsert.Strings = (
      'INSERT INTO fza_historia'
      
        '  (ID, CODIGO_ART_ART, DESCRIPCION_ART, CODIGO_CLI_CLI, PRECIOVE' +
        'NTA_ARTICULO, FECHA, ZONA, DESCRIPCION_HISTORIA, NUMERO_FAC, LIN' +
        'EA_LINEA, ODONTOLOGO, SERIE_FAC)'
      'VALUES'
      
        '  (:ID, :CODIGO_ART_ART, :DESCRIPCION_ART, :CODIGO_CLI_CLI, :PRE' +
        'CIOVENTA_ARTICULO, :FECHA, :ZONA, :DESCRIPCION_HISTORIA, :NUMERO' +
        '_FAC, :LINEA_LINEA, :ODONTOLOGO, :SERIE_FAC)')
    SQLDelete.Strings = (
      'DELETE FROM fza_historia'
      'WHERE'
      '  ID = :Old_ID')
    SQLUpdate.Strings = (
      'UPDATE fza_historia'
      'SET'
      
        '  ID = :ID, CODIGO_ART_ART = :CODIGO_ART_ART, DESCRIPCION_ART = ' +
        ':DESCRIPCION_ART, CODIGO_CLI_CLI = :CODIGO_CLI_CLI, PRECIOVENTA_' +
        'ARTICULO = :PRECIOVENTA_ARTICULO, FECHA = :FECHA, ZONA = :ZONA, ' +
        'DESCRIPCION_HISTORIA = :DESCRIPCION_HISTORIA, NUMERO_FAC = :NUME' +
        'RO_FAC, LINEA_LINEA = :LINEA_LINEA, ODONTOLOGO = :ODONTOLOGO, SE' +
        'RIE_FAC = :SERIE_FAC'
      'WHERE'
      '  ID = :Old_ID')
    SQLLock.Strings = (
      'SELECT * FROM fza_historia'
      'WHERE'
      '  ID = :Old_ID'
      'FOR UPDATE')
    SQLRefresh.Strings = (
      
        'SELECT ID, CODIGO_ART_ART, DESCRIPCION_ART, CODIGO_CLI_CLI, PREC' +
        'IOVENTA_ARTICULO, FECHA, ZONA, DESCRIPCION_HISTORIA, NUMERO_FAC,' +
        ' LINEA_LINEA, ODONTOLOGO, SERIE_FAC FROM fza_historia'
      'WHERE'
      '  ID = :ID')
    SQLRecCount.Strings = (
      'SELECT COUNT(*) FROM fza_historia')
    Connection = dmConn.conUni
    SQL.Strings = (
      'select * from vi_paises'
      '')
    ReadOnly = True
    Left = 640
    Top = 96
  end
  object dsDepositos: TDataSource
    DataSet = unqryDepositos
    Left = 152
    Top = 176
  end
  object unqryDepositos: TUniQuery
    SQLInsert.Strings = (
      'INSERT INTO fza_depositos_cliente'
      
        '  (ID_DEPOSITO_DEP, CODIGO_EMP_DEP, CODIGO_CLI_DEP, CODIGO_ART_D' +
        'EP, CODIGO_UNIDAD_DEP, PRECIO_VENTA_DEP, IMPORTE_ANTICIPO_DEP, E' +
        'STADO_DEP, FECHA_CREACION_DEP, INSTANTE_MODIF, INSTANTE_ALTA, US' +
        'UARIO_ALTA, USUARIO_MODIF, TIPO_IVA_DEP, PORCENTAJE_IVA_DEP, ESI' +
        'MP_INCL_DEP, CANTIDAD_PENDIENTE_DEP, FECHA_ENTREGA_DEP)'
      'VALUES'
      
        '  (:ID_DEPOSITO_DEP, :CODIGO_EMP_DEP, :CODIGO_CLI_DEP, :CODIGO_A' +
        'RT_DEP, :CODIGO_UNIDAD_DEP, :PRECIO_VENTA_DEP, :IMPORTE_ANTICIPO' +
        '_DEP, :ESTADO_DEP, :FECHA_CREACION_DEP, :INSTANTE_MODIF, :INSTAN' +
        'TE_ALTA, :USUARIO_ALTA, :USUARIO_MODIF, :TIPO_IVA_DEP, :PORCENTA' +
        'JE_IVA_DEP, :ESIMP_INCL_DEP, :CANTIDAD_PENDIENTE_DEP, :FECHA_ENT' +
        'REGA_DEP)')
    SQLDelete.Strings = (
      'DELETE FROM fza_depositos_cliente'
      'WHERE'
      '  ID_DEPOSITO_DEP = :Old_ID_DEPOSITO_DEP')
    SQLUpdate.Strings = (
      'UPDATE fza_depositos_cliente'
      'SET'
      
        '  ID_DEPOSITO_DEP = :ID_DEPOSITO_DEP, CODIGO_EMP_DEP = :CODIGO_E' +
        'MP_DEP, CODIGO_CLI_DEP = :CODIGO_CLI_DEP, CODIGO_ART_DEP = :CODI' +
        'GO_ART_DEP, CODIGO_UNIDAD_DEP = :CODIGO_UNIDAD_DEP, PRECIO_VENTA' +
        '_DEP = :PRECIO_VENTA_DEP, IMPORTE_ANTICIPO_DEP = :IMPORTE_ANTICI' +
        'PO_DEP, ESTADO_DEP = :ESTADO_DEP, FECHA_CREACION_DEP = :FECHA_CR' +
        'EACION_DEP, INSTANTE_MODIF = :INSTANTE_MODIF, INSTANTE_ALTA = :I' +
        'NSTANTE_ALTA, USUARIO_ALTA = :USUARIO_ALTA, USUARIO_MODIF = :USU' +
        'ARIO_MODIF, TIPO_IVA_DEP = :TIPO_IVA_DEP, PORCENTAJE_IVA_DEP = :' +
        'PORCENTAJE_IVA_DEP, ESIMP_INCL_DEP = :ESIMP_INCL_DEP, CANTIDAD_P' +
        'ENDIENTE_DEP = :CANTIDAD_PENDIENTE_DEP, FECHA_ENTREGA_DEP = :FEC' +
        'HA_ENTREGA_DEP'
      'WHERE'
      '  ID_DEPOSITO_DEP = :Old_ID_DEPOSITO_DEP')
    SQLLock.Strings = (
      
        'SELECT ID_DEPOSITO_DEP, CODIGO_EMP_DEP, CODIGO_CLI_DEP, CODIGO_A' +
        'RT_DEP, CODIGO_UNIDAD_DEP, PRECIO_VENTA_DEP, IMPORTE_ANTICIPO_DE' +
        'P, ESTADO_DEP, FECHA_CREACION_DEP, INSTANTE_MODIF, INSTANTE_ALTA' +
        ', USUARIO_ALTA, USUARIO_MODIF, TIPO_IVA_DEP, PORCENTAJE_IVA_DEP,' +
        ' ESIMP_INCL_DEP, CANTIDAD_PENDIENTE_DEP, FECHA_ENTREGA_DEP FROM ' +
        'fza_depositos_cliente'
      'WHERE'
      '  ID_DEPOSITO_DEP = :Old_ID_DEPOSITO_DEP'
      'FOR UPDATE')
    SQLRefresh.Strings = (
      
        'SELECT ID_DEPOSITO_DEP, CODIGO_EMP_DEP, CODIGO_CLI_DEP, CODIGO_A' +
        'RT_DEP, CODIGO_UNIDAD_DEP, PRECIO_VENTA_DEP, IMPORTE_ANTICIPO_DE' +
        'P, ESTADO_DEP, FECHA_CREACION_DEP, INSTANTE_MODIF, INSTANTE_ALTA' +
        ', USUARIO_ALTA, USUARIO_MODIF, TIPO_IVA_DEP, PORCENTAJE_IVA_DEP,' +
        ' ESIMP_INCL_DEP, CANTIDAD_PENDIENTE_DEP, FECHA_ENTREGA_DEP FROM ' +
        'fza_depositos_cliente'
      'WHERE'
      '  ID_DEPOSITO_DEP = :ID_DEPOSITO_DEP')
    SQLRecCount.Strings = (
      'SELECT COUNT(*) FROM fza_depositos_cliente')
    Connection = dmConn.conUni
    SQL.Strings = (
      'select * from vi_depositos_cliente')
    MasterSource = frmMtoClientes.dsTablaG
    MasterFields = 'CODIGO_CLI_CLI'
    DetailFields = 'CODIGO_CLI_DEP'
    ReadOnly = True
    Left = 152
    Top = 240
    ParamData = <
      item
        DataType = ftWideString
        Name = 'CODIGO_CLI_CLI'
        ParamType = ptInput
        Value = '321'
      end>
  end
end
