inherited dmCajaArqueosHist: TdmCajaArqueosHist
  inherited unqryTablaG: TUniQuery
    SQLInsert.Strings = (
      'INSERT INTO `fza_caja_arqueos`'
      '  (`CODIGO_ARQ`, `CODIGO_EMP_ARQ`, `CODIGO_ALM_ARQ`, `CODIGO_CAJA_ARQ`, `FECHA_DESDE_ARQ`, `FECHA_HASTA_ARQ`, `FASE_ARQ`, `CODIGO_EMPLEADO_ARQ`, `CANTIDAD_VENTAS_ARQ`, `CANTIDAD_OPERACIONES_ARQ`, `TOTAL' +
      '_BRUTO_LINEAS_ARQ`, `TOTAL_DESCUENTOS_LINEAS_ARQ`, `TOTAL_BRUTO_OPERACIONES_ARQ`, `TOTAL_DESCUENTOS_OPERACIONES_ARQ`, `TOTAL_NETO_ARQ`, `TOTAL_PRESTAMOS_ARQ`, `TOTAL_VENTAS_NORMALES_ARQ`, `TOTAL_VENTAS_' +
      'PRESTAMOS_ARQ`, `TOTAL_DEVOLUCIONES_ARQ`, `TOTAL_VENTAS_ARQ`, `TOTAL_VALES_RECOGIDOS_ARQ`, `TOTAL_VALES_EMITIDOS_ARQ`, `TOTAL_COBROS_CLIENTES_ARQ`, `TOTAL_PENDIENTE_COBRO_ARQ`, `TOTAL_INGRESOS_CAJA_ARQ`' +
      ', `TOTAL_EFECTIVO_INGRESOS_ARQ`, `TOTAL_EFECTIVO_ENTRADAS_ARQ`, `TOTAL_EFECTIVO_SALIDAS_ARQ`, `TOTAL_EFECTIVO_ANTERIOR_ARQ`, `TOTAL_EFECTIVO_CAJA_ARQ`, `TOTAL_OTROS_INGRESOS_ARQ`, `TOTAL_SALDO_RECONTAR_' +
      'ARQ`, `TOTAL_RECUENTO_ARQ`, `DIFERENCIA_TOTAL_ARQ`, `OBSERVACIONES_ARQ`, `INSTANTE_MODIF`, `INSTANTE_ALTA`, `USUARIO_ALTA`, `USUARIO_MODIF`)'
      'VALUES'
      '  (:`CODIGO_ARQ`, :`CODIGO_EMP_ARQ`, :`CODIGO_ALM_ARQ`, :`CODIGO_CAJA_ARQ`, :`FECHA_DESDE_ARQ`, :`FECHA_HASTA_ARQ`, :`FASE_ARQ`, :`CODIGO_EMPLEADO_ARQ`, :`CANTIDAD_VENTAS_ARQ`, :`CANTIDAD_OPERACIONES_A' +
      'RQ`, :`TOTAL_BRUTO_LINEAS_ARQ`, :`TOTAL_DESCUENTOS_LINEAS_ARQ`, :`TOTAL_BRUTO_OPERACIONES_ARQ`, :`TOTAL_DESCUENTOS_OPERACIONES_ARQ`, :`TOTAL_NETO_ARQ`, :`TOTAL_PRESTAMOS_ARQ`, :`TOTAL_VENTAS_NORMALES_AR' +
      'Q`, :`TOTAL_VENTAS_PRESTAMOS_ARQ`, :`TOTAL_DEVOLUCIONES_ARQ`, :`TOTAL_VENTAS_ARQ`, :`TOTAL_VALES_RECOGIDOS_ARQ`, :`TOTAL_VALES_EMITIDOS_ARQ`, :`TOTAL_COBROS_CLIENTES_ARQ`, :`TOTAL_PENDIENTE_COBRO_ARQ`, ' +
      ':`TOTAL_INGRESOS_CAJA_ARQ`, :`TOTAL_EFECTIVO_INGRESOS_ARQ`, :`TOTAL_EFECTIVO_ENTRADAS_ARQ`, :`TOTAL_EFECTIVO_SALIDAS_ARQ`, :`TOTAL_EFECTIVO_ANTERIOR_ARQ`, :`TOTAL_EFECTIVO_CAJA_ARQ`, :`TOTAL_OTROS_INGRE' +
      'SOS_ARQ`, :`TOTAL_SALDO_RECONTAR_ARQ`, :`TOTAL_RECUENTO_ARQ`, :`DIFERENCIA_TOTAL_ARQ`, :`OBSERVACIONES_ARQ`, :`INSTANTE_MODIF`, :`INSTANTE_ALTA`, :`USUARIO_ALTA`, :`USUARIO_MODIF`)')
    SQLDelete.Strings = (
      'DELETE FROM `fza_caja_arqueos`'
      'WHERE'
      '  `CODIGO_ARQ` = :`Old_CODIGO_ARQ`')
    SQLUpdate.Strings = (
      'UPDATE `fza_caja_arqueos`'
      'SET'
      '  `CODIGO_ARQ` = :`CODIGO_ARQ`, `CODIGO_EMP_ARQ` = :`CODIGO_EMP_ARQ`, `CODIGO_ALM_ARQ` = :`CODIGO_ALM_ARQ`, `CODIGO_CAJA_ARQ` = :`CODIGO_CAJA_ARQ`, `FECHA_DESDE_ARQ` = :`FECHA_DESDE_ARQ`, `FECHA_HASTA' +
      '_ARQ` = :`FECHA_HASTA_ARQ`, `FASE_ARQ` = :`FASE_ARQ`, `CODIGO_EMPLEADO_ARQ` = :`CODIGO_EMPLEADO_ARQ`, `CANTIDAD_VENTAS_ARQ` = :`CANTIDAD_VENTAS_ARQ`, `CANTIDAD_OPERACIONES_ARQ` = :`CANTIDAD_OPERACIONES_' +
      'ARQ`, `TOTAL_BRUTO_LINEAS_ARQ` = :`TOTAL_BRUTO_LINEAS_ARQ`, `TOTAL_DESCUENTOS_LINEAS_ARQ` = :`TOTAL_DESCUENTOS_LINEAS_ARQ`, `TOTAL_BRUTO_OPERACIONES_ARQ` = :`TOTAL_BRUTO_OPERACIONES_ARQ`, `TOTAL_DESCUE' +
      'NTOS_OPERACIONES_ARQ` = :`TOTAL_DESCUENTOS_OPERACIONES_ARQ`, `TOTAL_NETO_ARQ` = :`TOTAL_NETO_ARQ`, `TOTAL_PRESTAMOS_ARQ` = :`TOTAL_PRESTAMOS_ARQ`, `TOTAL_VENTAS_NORMALES_ARQ` = :`TOTAL_VENTAS_NORMALES_A' +
      'RQ`, `TOTAL_VENTAS_PRESTAMOS_ARQ` = :`TOTAL_VENTAS_PRESTAMOS_ARQ`, `TOTAL_DEVOLUCIONES_ARQ` = :`TOTAL_DEVOLUCIONES_ARQ`, `TOTAL_VENTAS_ARQ` = :`TOTAL_VENTAS_ARQ`, `TOTAL_VALES_RECOGIDOS_ARQ` = :`TOTAL_V' +
      'ALES_RECOGIDOS_ARQ`, `TOTAL_VALES_EMITIDOS_ARQ` = :`TOTAL_VALES_EMITIDOS_ARQ`, `TOTAL_COBROS_CLIENTES_ARQ` = :`TOTAL_COBROS_CLIENTES_ARQ`, `TOTAL_PENDIENTE_COBRO_ARQ` = :`TOTAL_PENDIENTE_COBRO_ARQ`, `TO' +
      'TAL_INGRESOS_CAJA_ARQ` = :`TOTAL_INGRESOS_CAJA_ARQ`, `TOTAL_EFECTIVO_INGRESOS_ARQ` = :`TOTAL_EFECTIVO_INGRESOS_ARQ`, `TOTAL_EFECTIVO_ENTRADAS_ARQ` = :`TOTAL_EFECTIVO_ENTRADAS_ARQ`, `TOTAL_EFECTIVO_SALID' +
      'AS_ARQ` = :`TOTAL_EFECTIVO_SALIDAS_ARQ`, `TOTAL_EFECTIVO_ANTERIOR_ARQ` = :`TOTAL_EFECTIVO_ANTERIOR_ARQ`, `TOTAL_EFECTIVO_CAJA_ARQ` = :`TOTAL_EFECTIVO_CAJA_ARQ`, `TOTAL_OTROS_INGRESOS_ARQ` = :`TOTAL_OTRO' +
      'S_INGRESOS_ARQ`, `TOTAL_SALDO_RECONTAR_ARQ` = :`TOTAL_SALDO_RECONTAR_ARQ`, `TOTAL_RECUENTO_ARQ` = :`TOTAL_RECUENTO_ARQ`, `DIFERENCIA_TOTAL_ARQ` = :`DIFERENCIA_TOTAL_ARQ`, `OBSERVACIONES_ARQ` = :`OBSERVA' +
      'CIONES_ARQ`, `INSTANTE_MODIF` = :`INSTANTE_MODIF`, `INSTANTE_ALTA` = :`INSTANTE_ALTA`, `USUARIO_ALTA` = :`USUARIO_ALTA`, `USUARIO_MODIF` = :`USUARIO_MODIF`'
      'WHERE'
      '  `CODIGO_ARQ` = :`Old_CODIGO_ARQ`')
    SQLLock.Strings = (
      'SELECT * FROM `fza_caja_arqueos`'
      'WHERE'
      '  `CODIGO_ARQ` = :`Old_CODIGO_ARQ`'
      'FOR UPDATE')
    SQLRefresh.Strings = (
      'SELECT * FROM `fza_caja_arqueos`'
      'WHERE'
      '  `CODIGO_ARQ` = :`CODIGO_ARQ`')
    SQLRecCount.Strings = (
      'SELECT COUNT(*) FROM fza_caja_arqueos')
    Connection = dmConn.conUni
    SQL.Strings = (
      'SELECT *'
      'FROM fza_caja_arqueos'
      'ORDER BY FECHA_DESDE_ARQ DESC, CODIGO_ARQ DESC'
      '')
    Active = True
    Left = 24
  end
end
