inherited dmMovimientosAlmacen: TdmMovimientosAlmacen
  inherited unqryTablaG: TUniQuery
    SQLInsert.Strings = (
      'INSERT INTO `fza_movimientos_almacen`'
      '  (`NUMERO_MOV`, `TIPO_DOC_MOV`, `SERIE_DOC_MOV`, `NRO_DOC_MOV`, `LINEA_MOV`, `CODIGO_EMPRESA_MOV`, `CODIGO_ALMACEN_MOV`, `FECHA_MOV`, `CODIGO_ARTICULO_MOV`, `CODIGO_UNIDAD_MOV`, `DESCRIPCION_ARTICULO_MOV`, `TIPO_MOVIMIENTO_MOV`, `CANTIDAD_MOV`, `PRECIO_COSTE_UNITARIO_MOV`, `TOTAL_COSTE_MOV`, `PRECIO_MEDIO_MOV`, `CODIGO_ALMACEN_CONTRA_MOV`, `CODIGO_CLIENTE_MOV`, `CODIGO_PROVEEDOR_MOV`, `ESACTIVO_MOV`, `INSTANTEMODIF`, `INSTANTEALTA`, `USUARIOALTA`, `USUARIOMODIF`, `TIPO_DOC_REF_MOV`, `SERIE_DOC_REF_MOV`, `NRO_DOC_REF_MOV`, `LINEA_REF_MOV`, `LOTE_MOV`, `FECHA_CADUCIDAD_MOV`)'
      'VALUES'
      '  (:`NUMERO_MOV`, :`TIPO_DOC_MOV`, :`SERIE_DOC_MOV`, :`NRO_DOC_MOV`, :`LINEA_MOV`, :`CODIGO_EMPRESA_MOV`, :`CODIGO_ALMACEN_MOV`, :`FECHA_MOV`, :`CODIGO_ARTICULO_MOV`, :`CODIGO_UNIDAD_MOV`, :`DESCRIPCION_ARTICULO_MOV`, :`TIPO_MOVIMIENTO_MOV`, :`CANTIDAD_MOV`, :`PRECIO_COSTE_UNITARIO_MOV`, :`TOTAL_COSTE_MOV`, :`PRECIO_MEDIO_MOV`, :`CODIGO_ALMACEN_CONTRA_MOV`, :`CODIGO_CLIENTE_MOV`, :`CODIGO_PROVEEDOR_MOV`, :`ESACTIVO_MOV`, :`INSTANTEMODIF`, :`INSTANTEALTA`, :`USUARIOALTA`, :`USUARIOMODIF`, :`TIPO_DOC_REF_MOV`, :`SERIE_DOC_REF_MOV`, :`NRO_DOC_REF_MOV`, :`LINEA_REF_MOV`, :`LOTE_MOV`, :`FECHA_CADUCIDAD_MOV`)')
    SQLDelete.Strings = (
      'DELETE FROM `fza_movimientos_almacen`'
      'WHERE'
      '  `NUMERO_MOV` = :`Old_NUMERO_MOV`')
    SQLUpdate.Strings = (
      'UPDATE `fza_movimientos_almacen`'
      'SET'
      '  `NUMERO_MOV` = :`NUMERO_MOV`, `TIPO_DOC_MOV` = :`TIPO_DOC_MOV`, `SERIE_DOC_MOV` = :`SERIE_DOC_MOV`, `NRO_DOC_MOV` = :`NRO_DOC_MOV`, `LINEA_MOV` = :`LINEA_MOV`, `CODIGO_EMPRESA_MOV` = :`CODIGO_EMPRESA_MOV`, `CODIGO_ALMACEN_MOV` = :`CODIGO_ALMACEN_MOV`, `FECHA_MOV` = :`FECHA_MOV`, `CODIGO_ARTICULO_MOV` = :`CODIGO_ARTICULO_MOV`, `CODIGO_UNIDAD_MOV` = :`CODIGO_UNIDAD_MOV`, `DESCRIPCION_ARTICULO_MOV` = :`DESCRIPCION_ARTICULO_MOV`, `TIPO_MOVIMIENTO_MOV` = :`TIPO_MOVIMIENTO_MOV`, `CANTIDAD_MOV` = :`CANTIDAD_MOV`, `PRECIO_COSTE_UNITARIO_MOV` = :`PRECIO_COSTE_UNITARIO_MOV`, `TOTAL_COSTE_MOV` = :`TOTAL_COSTE_MOV`, `PRECIO_MEDIO_MOV` = :`PRECIO_MEDIO_MOV`, `CODIGO_ALMACEN_CONTRA_MOV` = :`CODIGO_ALMACEN_CONTRA_MOV`, `CODIGO_CLIENTE_MOV` = :`CODIGO_CLIENTE_MOV`, `CODIGO_PROVEEDOR_MOV` = :`CODIGO_PROVEEDOR_MOV`, `ESACTIVO_MOV` = :`ESACTIVO_MOV`, `INSTANTEMODIF` = :`INSTANTEMODIF`, `INSTANTEALTA` = :`INSTANTEALTA`, `USUARIOALTA` = :`USUARIOALTA`, `USUARIOMODIF` = :`USUARIOMODIF`, `TIPO_DOC_REF_MOV` = :`TIPO_DOC_REF_MOV`, `SERIE_DOC_REF_MOV` = :`SERIE_DOC_REF_MOV`, `NRO_DOC_REF_MOV` = :`NRO_DOC_REF_MOV`, `LINEA_REF_MOV` = :`LINEA_REF_MOV`, `LOTE_MOV` = :`LOTE_MOV`, `FECHA_CADUCIDAD_MOV` = :`FECHA_CADUCIDAD_MOV`'
      'WHERE'
      '  `NUMERO_MOV` = :`Old_NUMERO_MOV`')
    SQLLock.Strings = (
      'SELECT * FROM `fza_movimientos_almacen`'
      'WHERE'
      '  `NUMERO_MOV` = :`Old_NUMERO_MOV`'
      'FOR UPDATE')
    SQLRefresh.Strings = (
      'SELECT * FROM `fza_movimientos_almacen`'
      'WHERE'
      '  `NUMERO_MOV` = :`NUMERO_MOV`')
    SQLRecCount.Strings = (
      'SELECT COUNT(*) FROM fza_movimientos_almacen')
    Connection = dmConn.conUni
    SQL.Strings = (
      'SELECT *'
      'FROM fza_movimientos_almacen'
      'ORDER BY FECHA_MOV DESC'
      '')
    Active = True
    Left = 24
  end
end
