inherited dmCajaPagosHist: TdmCajaPagosHist
  inherited unqryTablaG: TUniQuery
    SQLInsert.Strings = (
      'INSERT INTO `fza_caja_pagos`'
      '  (`CODIGO_EMPRESA_PAGO`, `CODIGO_ALMACEN_PAGO`, `CODIGO_CAJA_PAGO`, `SERIE_OPERACION_PAGO`, `NUMERO_OPERACION_PAGO`, `NUMERO_LINEA_PAGO`, `CODIGO_FORMAP`, `CODIGO_DIVISA_PAGO`, `RED_BLOCKCHAIN`, `FACTOR_CAMBIO_PAGO`, `IMPORTE_DIVISA_PAGO`, `IMPORTE_ENTREGADO_PAGO`, `IMPORTE_CAMBIO_PAGO`, `REFERENCIA_PAGO`, `OBSERVACIONES_PAGO`, `INSTANTEMODIF`, `INSTANTEALTA`, `USUARIOALTA`)'
      'VALUES'
      '  (:`CODIGO_EMPRESA_PAGO`, :`CODIGO_ALMACEN_PAGO`, :`CODIGO_CAJA_PAGO`, :`SERIE_OPERACION_PAGO`, :`NUMERO_OPERACION_PAGO`, :`NUMERO_LINEA_PAGO`, :`CODIGO_FORMAP`, :`CODIGO_DIVISA_PAGO`, :`RED_BLOCKCHAIN`, :`FACTOR_CAMBIO_PAGO`, :`IMPORTE_DIVISA_PAGO`, :`IMPORTE_ENTREGADO_PAGO`, :`IMPORTE_CAMBIO_PAGO`, :`REFERENCIA_PAGO`, :`OBSERVACIONES_PAGO`, :`INSTANTEMODIF`, :`INSTANTEALTA`, :`USUARIOALTA`)')
    SQLDelete.Strings = (
      'DELETE FROM `fza_caja_pagos`'
      'WHERE'
      '  `CODIGO_EMPRESA_PAGO` = :`Old_CODIGO_EMPRESA_PAGO` AND `CODIGO_ALMACEN_PAGO` = :`Old_CODIGO_ALMACEN_PAGO` AND `CODIGO_CAJA_PAGO` = :`Old_CODIGO_CAJA_PAGO` AND `SERIE_OPERACION_PAGO` = :`Old_SERIE_OPERACION_PAGO` AND `NUMERO_OPERACION_PAGO` = :`Old_NUMERO_OPERACION_PAGO` AND `NUMERO_LINEA_PAGO` = :`Old_NUMERO_LINEA_PAGO`')
    SQLUpdate.Strings = (
      'UPDATE `fza_caja_pagos`'
      'SET'
      '  `CODIGO_EMPRESA_PAGO` = :`CODIGO_EMPRESA_PAGO`, `CODIGO_ALMACEN_PAGO` = :`CODIGO_ALMACEN_PAGO`, `CODIGO_CAJA_PAGO` = :`CODIGO_CAJA_PAGO`, `SERIE_OPERACION_PAGO` = :`SERIE_OPERACION_PAGO`, `NUMERO_OPERACION_PAGO` = :`NUMERO_OPERACION_PAGO`, `NUMERO_LINEA_PAGO` = :`NUMERO_LINEA_PAGO`, `CODIGO_FORMAP` = :`CODIGO_FORMAP`, `CODIGO_DIVISA_PAGO` = :`CODIGO_DIVISA_PAGO`, `RED_BLOCKCHAIN` = :`RED_BLOCKCHAIN`, `FACTOR_CAMBIO_PAGO` = :`FACTOR_CAMBIO_PAGO`, `IMPORTE_DIVISA_PAGO` = :`IMPORTE_DIVISA_PAGO`, `IMPORTE_ENTREGADO_PAGO` = :`IMPORTE_ENTREGADO_PAGO`, `IMPORTE_CAMBIO_PAGO` = :`IMPORTE_CAMBIO_PAGO`, `REFERENCIA_PAGO` = :`REFERENCIA_PAGO`, `OBSERVACIONES_PAGO` = :`OBSERVACIONES_PAGO`, `INSTANTEMODIF` = :`INSTANTEMODIF`, `INSTANTEALTA` = :`INSTANTEALTA`, `USUARIOALTA` = :`USUARIOALTA`'
      'WHERE'
      '  `CODIGO_EMPRESA_PAGO` = :`Old_CODIGO_EMPRESA_PAGO` AND `CODIGO_ALMACEN_PAGO` = :`Old_CODIGO_ALMACEN_PAGO` AND `CODIGO_CAJA_PAGO` = :`Old_CODIGO_CAJA_PAGO` AND `SERIE_OPERACION_PAGO` = :`Old_SERIE_OPERACION_PAGO` AND `NUMERO_OPERACION_PAGO` = :`Old_NUMERO_OPERACION_PAGO` AND `NUMERO_LINEA_PAGO` = :`Old_NUMERO_LINEA_PAGO`')
    SQLLock.Strings = (
      'SELECT * FROM `fza_caja_pagos`'
      'WHERE'
      '  `CODIGO_EMPRESA_PAGO` = :`Old_CODIGO_EMPRESA_PAGO` AND `CODIGO_ALMACEN_PAGO` = :`Old_CODIGO_ALMACEN_PAGO` AND `CODIGO_CAJA_PAGO` = :`Old_CODIGO_CAJA_PAGO` AND `SERIE_OPERACION_PAGO` = :`Old_SERIE_OPERACION_PAGO` AND `NUMERO_OPERACION_PAGO` = :`Old_NUMERO_OPERACION_PAGO` AND `NUMERO_LINEA_PAGO` = :`Old_NUMERO_LINEA_PAGO`'
      'FOR UPDATE')
    SQLRefresh.Strings = (
      'SELECT * FROM `fza_caja_pagos`'
      'WHERE'
      '  `CODIGO_EMPRESA_PAGO` = :`CODIGO_EMPRESA_PAGO` AND `CODIGO_ALMACEN_PAGO` = :`CODIGO_ALMACEN_PAGO` AND `CODIGO_CAJA_PAGO` = :`CODIGO_CAJA_PAGO` AND `SERIE_OPERACION_PAGO` = :`SERIE_OPERACION_PAGO` AND `NUMERO_OPERACION_PAGO` = :`NUMERO_OPERACION_PAGO` AND `NUMERO_LINEA_PAGO` = :`NUMERO_LINEA_PAGO`')
    SQLRecCount.Strings = (
      'SELECT COUNT(*) FROM fza_caja_pagos')
    Connection = dmConn.conUni
    SQL.Strings = (
      'SELECT *'
      'FROM fza_caja_pagos'
      'ORDER BY INSTANTEALTA DESC'
      '')
    Active = True
    Left = 24
  end
end
