object dmPedidos: TdmPedidos
  Left = 0
  Top = 0
  ClientHeight = 371
  ClientWidth = 632
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -12
  Font.Name = 'Segoe UI'
  Font.Style = []
  TextHeight = 15
  object unqryPedidosLineas: TUniQuery
    SQLInsert.Strings = (
      'INSERT INTO fza_pedidos_lineas'
      
        '  (NUMERO_PED_PEDLIN, SERIE_PED_PEDLIN, LINEA_PEDLIN, IDLINEAPS_PEDLIN, IDPRODPS_PEDLIN, CODIGOPRODPS_PEDLIN, IDATRIBPRODPS_PEDLIN, CODBAR_ART_PEDLIN, CODIGO_ART_PEDLIN, CODIGO_FAM_PEDLIN, NOMBRE_FAM_' +
        'PEDLIN, FECHA_ENTREGA_PEDLIN, TIPO_CANTIDAD_ARTICULO_PEDLIN, ESIMP_INCL_TARIFA_PEDLIN, TIPO_IVA_ARTICULO_PEDLIN, DESCRIPCION_ARTICULO_PEDLIN, CODIGO_TAR_PEDLIN, CANTIDAD_PEDLIN, PRECIO_VENTA_SIVA_ARTI' +
        'CULO_PEDLIN, PORCENTAJE_IVA_PEDLIN, PRECIO_VENTA_CIVA_ARTICULO_PEDLIN, TOTAL_PEDLIN, INSTANTE_MODIF, INSTANTE_ALTA, USUARIO_ALTA, USUARIO_MODIF)'
      'VALUES'
      
        '  (:NUMERO_PED_PEDLIN, :SERIE_PED_PEDLIN, :LINEA_PEDLIN, :IDLINEAPS_PEDLIN, :IDPRODPS_PEDLIN, :CODIGOPRODPS_PEDLIN, :IDATRIBPRODPS_PEDLIN, :CODBAR_ART_PEDLIN, :CODIGO_ART_PEDLIN, :CODIGO_FAM_PEDLIN, :' +
        'NOMBRE_FAM_PEDLIN, :FECHA_ENTREGA_PEDLIN, :TIPO_CANTIDAD_ARTICULO_PEDLIN, :ESIMP_INCL_TARIFA_PEDLIN, :TIPO_IVA_ARTICULO_PEDLIN, :DESCRIPCION_ARTICULO_PEDLIN, :CODIGO_TAR_PEDLIN, :CANTIDAD_PEDLIN, :PRE' +
        'CIO_VENTA_SIVA_ARTICULO_PEDLIN, :PORCENTAJE_IVA_PEDLIN, :PRECIO_VENTA_CIVA_ARTICULO_PEDLIN, :TOTAL_PEDLIN, :INSTANTE_MODIF, :INSTANTE_ALTA, :USUARIO_ALTA, :USUARIO_MODIF)')
    SQLDelete.Strings = (
      'DELETE FROM fza_pedidos_lineas'
      'WHERE'
      
        '  NUMERO_PED_PEDLIN = :Old_NUMERO_PED_PEDLIN AND SERIE_PED_PEDLIN = :Old_SERIE_PED_PEDLIN AND LINEA_PEDLIN = :Old_LINEA_PEDLIN')
    SQLUpdate.Strings = (
      'UPDATE fza_pedidos_lineas'
      'SET'
      
        '  NUMERO_PED_PEDLIN = :NUMERO_PED_PEDLIN, SERIE_PED_PEDLIN = :SERIE_PED_PEDLIN, LINEA_PEDLIN = :LINEA_PEDLIN, IDLINEAPS_PEDLIN = :IDLINEAPS_PEDLIN, IDPRODPS_PEDLIN = :IDPRODPS_PEDLIN, CODIGOPRODPS_PED' +
        'LIN = :CODIGOPRODPS_PEDLIN, IDATRIBPRODPS_PEDLIN = :IDATRIBPRODPS_PEDLIN, CODBAR_ART_PEDLIN = :CODBAR_ART_PEDLIN, CODIGO_ART_PEDLIN = :CODIGO_ART_PEDLIN, CODIGO_FAM_PEDLIN = :CODIGO_FAM_PEDLIN, NOMBRE' +
        '_FAM_PEDLIN = :NOMBRE_FAM_PEDLIN, FECHA_ENTREGA_PEDLIN = :FECHA_ENTREGA_PEDLIN, TIPO_CANTIDAD_ARTICULO_PEDLIN = :TIPO_CANTIDAD_ARTICULO_PEDLIN, ESIMP_INCL_TARIFA_PEDLIN = :ESIMP_INCL_TARIFA_PEDLIN, TI' +
        'PO_IVA_ARTICULO_PEDLIN = :TIPO_IVA_ARTICULO_PEDLIN, DESCRIPCION_ARTICULO_PEDLIN = :DESCRIPCION_ARTICULO_PEDLIN, CODIGO_TAR_PEDLIN = :CODIGO_TAR_PEDLIN, CANTIDAD_PEDLIN = :CANTIDAD_PEDLIN, PRECIO_VENTA' +
        '_SIVA_ARTICULO_PEDLIN = :PRECIO_VENTA_SIVA_ARTICULO_PEDLIN, PORCENTAJE_IVA_PEDLIN = :PORCENTAJE_IVA_PEDLIN, PRECIO_VENTA_CIVA_ARTICULO_PEDLIN = :PRECIO_VENTA_CIVA_ARTICULO_PEDLIN, TOTAL_PEDLIN = :TOTA' +
        'L_PEDLIN, INSTANTE_MODIF = :INSTANTE_MODIF, INSTANTE_ALTA = :INSTANTE_ALTA, USUARIO_ALTA = :USUARIO_ALTA, USUARIO_MODIF = :USUARIO_MODIF'
      'WHERE'
      
        '  NUMERO_PED_PEDLIN = :Old_NUMERO_PED_PEDLIN AND SERIE_PED_PEDLIN = :Old_SERIE_PED_PEDLIN AND LINEA_PEDLIN = :Old_LINEA_PEDLIN')
    SQLLock.Strings = (
      
        'SELECT NUMERO_PED_PEDLIN, SERIE_PED_PEDLIN, LINEA_PEDLIN, IDLINEAPS_PEDLIN, IDPRODPS_PEDLIN, CODIGOPRODPS_PEDLIN, IDATRIBPRODPS_PEDLIN, CODBAR_ART_PEDLIN, CODIGO_ART_PEDLIN, CODIGO_FAM_PEDLIN, NOMBRE_' +
        'FAM_PEDLIN, FECHA_ENTREGA_PEDLIN, TIPO_CANTIDAD_ARTICULO_PEDLIN, ESIMP_INCL_TARIFA_PEDLIN, TIPO_IVA_ARTICULO_PEDLIN, DESCRIPCION_ARTICULO_PEDLIN, CODIGO_TAR_PEDLIN, CANTIDAD_PEDLIN, PRECIO_VENTA_SIVA_' +
        'ARTICULO_PEDLIN, PORCENTAJE_IVA_PEDLIN, PRECIO_VENTA_CIVA_ARTICULO_PEDLIN, TOTAL_PEDLIN, INSTANTE_MODIF, INSTANTE_ALTA, USUARIO_ALTA, USUARIO_MODIF FROM fza_pedidos_lineas'
      'WHERE'
      
        '  NUMERO_PED_PEDLIN = :Old_NUMERO_PED_PEDLIN AND SERIE_PED_PEDLIN = :Old_SERIE_PED_PEDLIN AND LINEA_PEDLIN = :Old_LINEA_PEDLIN'
      'FOR UPDATE')
    SQLRefresh.Strings = (
      
        'SELECT NUMERO_PED_PEDLIN, SERIE_PED_PEDLIN, LINEA_PEDLIN, IDLINEAPS_PEDLIN, IDPRODPS_PEDLIN, CODIGOPRODPS_PEDLIN, IDATRIBPRODPS_PEDLIN, CODBAR_ART_PEDLIN, CODIGO_ART_PEDLIN, CODIGO_FAM_PEDLIN, NOMBRE_' +
        'FAM_PEDLIN, FECHA_ENTREGA_PEDLIN, TIPO_CANTIDAD_ARTICULO_PEDLIN, ESIMP_INCL_TARIFA_PEDLIN, TIPO_IVA_ARTICULO_PEDLIN, DESCRIPCION_ARTICULO_PEDLIN, CODIGO_TAR_PEDLIN, CANTIDAD_PEDLIN, PRECIO_VENTA_SIVA_' +
        'ARTICULO_PEDLIN, PORCENTAJE_IVA_PEDLIN, PRECIO_VENTA_CIVA_ARTICULO_PEDLIN, TOTAL_PEDLIN, INSTANTE_MODIF, INSTANTE_ALTA, USUARIO_ALTA, USUARIO_MODIF FROM fza_pedidos_lineas'
      'WHERE'
      
        '  NUMERO_PED_PEDLIN = :NUMERO_PED_PEDLIN AND SERIE_PED_PEDLIN = :SERIE_PED_PEDLIN AND LINEA_PEDLIN = :LINEA_PEDLIN')
    SQLRecCount.Strings = (
      'SELECT COUNT(*) FROM fza_pedidos_lineas')
    Connection = dmConn.conUni
    SQL.Strings = (
      'SELECT * FROM vi_pedidos_lineas')
    MasterFields = 'NUMERO_PED;SERIE_PED'
    DetailFields = 'NUMERO_PED_PEDLIN;SERIE_PED_PEDLIN'
    AfterInsert = unqryPedidosLineasAfterInsert
    BeforePost = unqryPedidosLineasBeforePost
    Left = 48
    Top = 80
    ParamData = <
      item
        DataType = ftUnknown
        Name = 'NUMERO_PED'
        Value = nil
      end
      item
        DataType = ftUnknown
        Name = 'SERIE_PED'
        Value = nil
      end>
  end
  object dsPedidosLineas: TDataSource
    DataSet = unqryPedidosLineas
    Left = 128
    Top = 80
  end
  object unqryLinPedido: TUniQuery
    Connection = dmConn.conUni
    SQL.Strings = (
      'SELECT * FROM fza_pedidos_lineas'
      'WHERE NUMERO_PED_PEDLIN = :NUMERO_PED'
      'AND SERIE_PED_PEDLIN = :SERIE_PED')
    Left = 48
    Top = 136
    ParamData = <
      item
        DataType = ftUnknown
        Name = 'NUMERO_PED'
        Value = nil
      end
      item
        DataType = ftUnknown
        Name = 'SERIE_PED'
        Value = nil
      end>
  end
  object dsLinPedido: TDataSource
    DataSet = unqryLinPedido
    Left = 128
    Top = 136
  end
  object unqryEmpDataPedido: TUniQuery
    Connection = dmConn.conUni
    SQL.Strings = (
      'SELECT * FROM fza_empresas')
    Left = 48
    Top = 192
  end
  object unqryCliDataPedido: TUniQuery
    Connection = dmConn.conUni
    SQL.Strings = (
      'SELECT * FROM fza_clientes')
    Left = 48
    Top = 248
  end
  object unqryArtDataLinPedido: TUniQuery
    Connection = dmConn.conUni
    SQL.Strings = (
      'SELECT * FROM fza_articulos')
    Left = 48
    Top = 304
  end
  object unstrdprcCrearPedido: TUniStoredProc
    StoredProcName = 'PRC_CREAR_PEDIDO'
    Connection = dmConn.conUni
    Left = 256
    Top = 24
  end
  object unstrdprcGetContadorPedido: TUniStoredProc
    StoredProcName = 'PRC_GET_CONTADOR_PEDIDO'
    Connection = dmConn.conUni
    Left = 256
    Top = 80
  end
  object unstrdprcGetContador: TUniStoredProc
    StoredProcName = 'PRC_GET_CONTADOR'
    Connection = dmConn.conUni
    Left = 256
    Top = 136
  end
  object fxdsPrintPed: TfrxDBDataset
    UserName = 'frxDBDataset1'
    CloseDataSource = False
    BCDToCurrency = False
    DataSetOptions = []
    Left = 384
    Top = 24
  end
  object fxdstPrintLinPed: TfrxDBDataset
    UserName = 'frxDBDataset2'
    CloseDataSource = False
    DataSet = unqryPedidosLineas
    BCDToCurrency = False
    DataSetOptions = []
    Left = 384
    Top = 80
  end
  object unqryTablaG: TUniQuery
    SQLInsert.Strings = (
      'INSERT INTO fza_pedidos'
      
        '  (NUMERO_PED, SERIE_PED, FECHA_PED, CODIGO_EMP_PED, RAZON_SOCIAL_EMPRESA_PED, NIF_EMPRESA_PED, MOVIL_EMPRESA_PED, EMAIL_EMPRESA_PED, DIRECCION1_EMPRESA_PED, DIRECCION2_EMPRESA_PED, POBLACION_EMPRESA_' +
        'PED, PROVINCIA_EMPRESA_PED, CODIGO_PAI_EMPRESA_PED, NOMBRE_PAI_EMPRESA_PED, CODIGO_POSTAL_EMPRESA_PED, ESRETENCIONES_EMPRESA_PED, GRUPO_ZONA_IVA_EMPRESA_PED, ESREGIMENESPECIALAGRICOLA_EMPRESA_PED, COD' +
        'IGO_CLI_PED, NIF_CLIENTE_PED, EMAIL_CLIENTE_PED, REFERENCIAPS_PED, IDPS_PED, FECHAPS_PED, FORMAPAGOPS_PED, TRANSPORTISTAPS_PED, ESTADOPEDIDOPS_PED, ESTADOMENSAJEPS_PED, IDHILOPS_MENSAJES_PED, NOMBRE_C' +
        'LI_ENVIO_PED, MOVIL_CLIENTE_ENVIO_PED, DIRECCION1_CLIENTE_ENVIO_PED, DIRECCION2_CLIENTE_ENVIO_PED, POBLACION_CLIENTE_ENVIO_PED, PROVINCIA_CLIENTE_ENVIO_PED, CODIGO_POSTAL_CLIENTE_ENVIO_PED, CODIGO_PAI' +
        '_CLIENTE_ENVIO_PED, NOMBRE_PAI_CLIENTE_ENVIO_PED, RAZON_SOCIAL_CLIENTE_FISCAL_PED, MOVIL_CLIENTE_FISCAL_PED, EMAIL_CLIENTE_FISCAL_PED, DIRECCION1_CLIENTE_FISCAL_PED, DIRECCION2_CLIENTE_FISCAL_PED, POB' +
        'LACION_CLIENTE_FISCAL_PED, PROVINCIA_CLIENTE_FISCAL_PED, CODIGO_POSTAL_CLIENTE_FISCAL_PED, CODIGO_PAI_CLIENTE_FISCAL_PED, NOMBRE_PAI_CLIENTE_FISCAL_PED, ESIVA_RECARGO_CLIENTE_PED, ESIVA_EXENTO_CLIENTE' +
        '_PED, ESREGIMENESPECIALAGRICOLA_CLIENTE_PED, ESRETENCIONES_CLIENTE_PED, TARIFA_ARTICULO_CLIENTE_PED, ESIMP_INCL_TARIFA_CLIENTE_PED, ESINTRACOMUNITARIO_CLIENTE_PED, ESIRPF_IMP_INCL_ZONA_IVA_PED, ESAPLI' +
        'CA_RE_ZONA_IVA_PED, ESIVAAGRICOLA_ZONA_IVA_PED, PALABRA_REPORTS_ZONA_IVA_PED, CODIGO_IVA_PED, ESVENTA_ACTIVO_FIJO_PED, PORCENTAJE_IVAN_PED, TOTAL_IVAN_PED, PORCENTAJE_REN_PED, TOTAL_REN_PED, TOTAL_BAS' +
        'EI_IVAN_PED, PORCENTAJE_IVAR_PED, TOTAL_IVAR_PED, PORCENTAJE_RER_PED, TOTAL_RER_PED, TOTAL_BASEI_IVAR_PED, PORCENTAJE_IVAS_PED, TOTAL_IVAS_PED, PORCENTAJE_RES_PED, TOTAL_RES_PED, TOTAL_BASEI_IVAS_PED,' +
        ' PORCENTAJE_IVAE_PED, TOTAL_IVAE_PED, PORCENTAJE_REE_PED, TOTAL_REE_PED, TOTAL_BASEI_IVAE_PED, TOTAL_BASES_PED, TOTAL_IMPUESTOS_PED, FORMA_PAGO_PED, PORCENTAJE_RETENCION_PED, TOTAL_RETENCION_PED, TOTA' +
        'L_LIQUIDO_PED, TOTAL_PAGADOREALPS_PED, NUMERO_PED_ABONO_PED, SERIE_PED_ABONO_PED, TEXTO_LEGAL_CLIENTE_PED, TEXTO_LEGAL_EMPRESA_PED, DOCUMENTO_PED, COMENTARIOS_PED, CONTADOR_LINEAS_PED, ESCREARARTICULO' +
        'S_PED, ESDESCRIPCIONES_AMP_PED, ESFECHADEENTREGA_PED, INSTANTE_MODIF, INSTANTE_ALTA, USUARIO_ALTA, USUARIO_MODIF)'
      'VALUES'
      
        '  (:NUMERO_PED, :SERIE_PED, :FECHA_PED, :CODIGO_EMP_PED, :RAZON_SOCIAL_EMPRESA_PED, :NIF_EMPRESA_PED, :MOVIL_EMPRESA_PED, :EMAIL_EMPRESA_PED, :DIRECCION1_EMPRESA_PED, :DIRECCION2_EMPRESA_PED, :POBLACI' +
        'ON_EMPRESA_PED, :PROVINCIA_EMPRESA_PED, :CODIGO_PAI_EMPRESA_PED, :NOMBRE_PAI_EMPRESA_PED, :CODIGO_POSTAL_EMPRESA_PED, :ESRETENCIONES_EMPRESA_PED, :GRUPO_ZONA_IVA_EMPRESA_PED, :ESREGIMENESPECIALAGRICOL' +
        'A_EMPRESA_PED, :CODIGO_CLI_PED, :NIF_CLIENTE_PED, :EMAIL_CLIENTE_PED, :REFERENCIAPS_PED, :IDPS_PED, :FECHAPS_PED, :FORMAPAGOPS_PED, :TRANSPORTISTAPS_PED, :ESTADOPEDIDOPS_PED, :ESTADOMENSAJEPS_PED, :ID' +
        'HILOPS_MENSAJES_PED, :NOMBRE_CLI_ENVIO_PED, :MOVIL_CLIENTE_ENVIO_PED, :DIRECCION1_CLIENTE_ENVIO_PED, :DIRECCION2_CLIENTE_ENVIO_PED, :POBLACION_CLIENTE_ENVIO_PED, :PROVINCIA_CLIENTE_ENVIO_PED, :CODIGO_' +
        'POSTAL_CLIENTE_ENVIO_PED, :CODIGO_PAI_CLIENTE_ENVIO_PED, :NOMBRE_PAI_CLIENTE_ENVIO_PED, :RAZON_SOCIAL_CLIENTE_FISCAL_PED, :MOVIL_CLIENTE_FISCAL_PED, :EMAIL_CLIENTE_FISCAL_PED, :DIRECCION1_CLIENTE_FISC' +
        'AL_PED, :DIRECCION2_CLIENTE_FISCAL_PED, :POBLACION_CLIENTE_FISCAL_PED, :PROVINCIA_CLIENTE_FISCAL_PED, :CODIGO_POSTAL_CLIENTE_FISCAL_PED, :CODIGO_PAI_CLIENTE_FISCAL_PED, :NOMBRE_PAI_CLIENTE_FISCAL_PED,' +
        ' :ESIVA_RECARGO_CLIENTE_PED, :ESIVA_EXENTO_CLIENTE_PED, :ESREGIMENESPECIALAGRICOLA_CLIENTE_PED, :ESRETENCIONES_CLIENTE_PED, :TARIFA_ARTICULO_CLIENTE_PED, :ESIMP_INCL_TARIFA_CLIENTE_PED, :ESINTRACOMUNI' +
        'TARIO_CLIENTE_PED, :ESIRPF_IMP_INCL_ZONA_IVA_PED, :ESAPLICA_RE_ZONA_IVA_PED, :ESIVAAGRICOLA_ZONA_IVA_PED, :PALABRA_REPORTS_ZONA_IVA_PED, :CODIGO_IVA_PED, :ESVENTA_ACTIVO_FIJO_PED, :PORCENTAJE_IVAN_PED' +
        ', :TOTAL_IVAN_PED, :PORCENTAJE_REN_PED, :TOTAL_REN_PED, :TOTAL_BASEI_IVAN_PED, :PORCENTAJE_IVAR_PED, :TOTAL_IVAR_PED, :PORCENTAJE_RER_PED, :TOTAL_RER_PED, :TOTAL_BASEI_IVAR_PED, :PORCENTAJE_IVAS_PED, ' +
        ':TOTAL_IVAS_PED, :PORCENTAJE_RES_PED, :TOTAL_RES_PED, :TOTAL_BASEI_IVAS_PED, :PORCENTAJE_IVAE_PED, :TOTAL_IVAE_PED, :PORCENTAJE_REE_PED, :TOTAL_REE_PED, :TOTAL_BASEI_IVAE_PED, :TOTAL_BASES_PED, :TOTAL' +
        '_IMPUESTOS_PED, :FORMA_PAGO_PED, :PORCENTAJE_RETENCION_PED, :TOTAL_RETENCION_PED, :TOTAL_LIQUIDO_PED, :TOTAL_PAGADOREALPS_PED, :NUMERO_PED_ABONO_PED, :SERIE_PED_ABONO_PED, :TEXTO_LEGAL_CLIENTE_PED, :T' +
        'EXTO_LEGAL_EMPRESA_PED, :DOCUMENTO_PED, :COMENTARIOS_PED, :CONTADOR_LINEAS_PED, :ESCREARARTICULOS_PED, :ESDESCRIPCIONES_AMP_PED, :ESFECHADEENTREGA_PED, :INSTANTE_MODIF, :INSTANTE_ALTA, :USUARIO_ALTA, ' +
        ':USUARIO_MODIF)')
    SQLDelete.Strings = (
      'DELETE FROM fza_pedidos'
      'WHERE'
      
        '  NUMERO_PED = :Old_NUMERO_PED AND SERIE_PED = :Old_SERIE_PED')
    SQLUpdate.Strings = (
      'UPDATE fza_pedidos'
      'SET'
      
        '  NUMERO_PED = :NUMERO_PED, SERIE_PED = :SERIE_PED, FECHA_PED = :FECHA_PED, CODIGO_EMP_PED = :CODIGO_EMP_PED, RAZON_SOCIAL_EMPRESA_PED = :RAZON_SOCIAL_EMPRESA_PED, NIF_EMPRESA_PED = :NIF_EMPRESA_PED, ' +
        'MOVIL_EMPRESA_PED = :MOVIL_EMPRESA_PED, EMAIL_EMPRESA_PED = :EMAIL_EMPRESA_PED, DIRECCION1_EMPRESA_PED = :DIRECCION1_EMPRESA_PED, DIRECCION2_EMPRESA_PED = :DIRECCION2_EMPRESA_PED, POBLACION_EMPRESA_PE' +
        'D = :POBLACION_EMPRESA_PED, PROVINCIA_EMPRESA_PED = :PROVINCIA_EMPRESA_PED, CODIGO_PAI_EMPRESA_PED = :CODIGO_PAI_EMPRESA_PED, NOMBRE_PAI_EMPRESA_PED = :NOMBRE_PAI_EMPRESA_PED, CODIGO_POSTAL_EMPRESA_PE' +
        'D = :CODIGO_POSTAL_EMPRESA_PED, ESRETENCIONES_EMPRESA_PED = :ESRETENCIONES_EMPRESA_PED, GRUPO_ZONA_IVA_EMPRESA_PED = :GRUPO_ZONA_IVA_EMPRESA_PED, ESREGIMENESPECIALAGRICOLA_EMPRESA_PED = :ESREGIMENESPE' +
        'CIALAGRICOLA_EMPRESA_PED, CODIGO_CLI_PED = :CODIGO_CLI_PED, NIF_CLIENTE_PED = :NIF_CLIENTE_PED, EMAIL_CLIENTE_PED = :EMAIL_CLIENTE_PED, REFERENCIAPS_PED = :REFERENCIAPS_PED, IDPS_PED = :IDPS_PED, FECH' +
        'APS_PED = :FECHAPS_PED, FORMAPAGOPS_PED = :FORMAPAGOPS_PED, TRANSPORTISTAPS_PED = :TRANSPORTISTAPS_PED, ESTADOPEDIDOPS_PED = :ESTADOPEDIDOPS_PED, ESTADOMENSAJEPS_PED = :ESTADOMENSAJEPS_PED, IDHILOPS_M' +
        'ENSAJES_PED = :IDHILOPS_MENSAJES_PED, NOMBRE_CLI_ENVIO_PED = :NOMBRE_CLI_ENVIO_PED, MOVIL_CLIENTE_ENVIO_PED = :MOVIL_CLIENTE_ENVIO_PED, DIRECCION1_CLIENTE_ENVIO_PED = :DIRECCION1_CLIENTE_ENVIO_PED, DI' +
        'RECCION2_CLIENTE_ENVIO_PED = :DIRECCION2_CLIENTE_ENVIO_PED, POBLACION_CLIENTE_ENVIO_PED = :POBLACION_CLIENTE_ENVIO_PED, PROVINCIA_CLIENTE_ENVIO_PED = :PROVINCIA_CLIENTE_ENVIO_PED, CODIGO_POSTAL_CLIENT' +
        'E_ENVIO_PED = :CODIGO_POSTAL_CLIENTE_ENVIO_PED, CODIGO_PAI_CLIENTE_ENVIO_PED = :CODIGO_PAI_CLIENTE_ENVIO_PED, NOMBRE_PAI_CLIENTE_ENVIO_PED = :NOMBRE_PAI_CLIENTE_ENVIO_PED, RAZON_SOCIAL_CLIENTE_FISCAL_' +
        'PED = :RAZON_SOCIAL_CLIENTE_FISCAL_PED, MOVIL_CLIENTE_FISCAL_PED = :MOVIL_CLIENTE_FISCAL_PED, EMAIL_CLIENTE_FISCAL_PED = :EMAIL_CLIENTE_FISCAL_PED, DIRECCION1_CLIENTE_FISCAL_PED = :DIRECCION1_CLIENTE_' +
        'FISCAL_PED, DIRECCION2_CLIENTE_FISCAL_PED = :DIRECCION2_CLIENTE_FISCAL_PED, POBLACION_CLIENTE_FISCAL_PED = :POBLACION_CLIENTE_FISCAL_PED, PROVINCIA_CLIENTE_FISCAL_PED = :PROVINCIA_CLIENTE_FISCAL_PED, ' +
        'CODIGO_POSTAL_CLIENTE_FISCAL_PED = :CODIGO_POSTAL_CLIENTE_FISCAL_PED, CODIGO_PAI_CLIENTE_FISCAL_PED = :CODIGO_PAI_CLIENTE_FISCAL_PED, NOMBRE_PAI_CLIENTE_FISCAL_PED = :NOMBRE_PAI_CLIENTE_FISCAL_PED, ES' +
        'IVA_RECARGO_CLIENTE_PED = :ESIVA_RECARGO_CLIENTE_PED, ESIVA_EXENTO_CLIENTE_PED = :ESIVA_EXENTO_CLIENTE_PED, ESREGIMENESPECIALAGRICOLA_CLIENTE_PED = :ESREGIMENESPECIALAGRICOLA_CLIENTE_PED, ESRETENCIONE' +
        'S_CLIENTE_PED = :ESRETENCIONES_CLIENTE_PED, TARIFA_ARTICULO_CLIENTE_PED = :TARIFA_ARTICULO_CLIENTE_PED, ESIMP_INCL_TARIFA_CLIENTE_PED = :ESIMP_INCL_TARIFA_CLIENTE_PED, ESINTRACOMUNITARIO_CLIENTE_PED =' +
        ' :ESINTRACOMUNITARIO_CLIENTE_PED, ESIRPF_IMP_INCL_ZONA_IVA_PED = :ESIRPF_IMP_INCL_ZONA_IVA_PED, ESAPLICA_RE_ZONA_IVA_PED = :ESAPLICA_RE_ZONA_IVA_PED, ESIVAAGRICOLA_ZONA_IVA_PED = :ESIVAAGRICOLA_ZONA_I' +
        'VA_PED, PALABRA_REPORTS_ZONA_IVA_PED = :PALABRA_REPORTS_ZONA_IVA_PED, CODIGO_IVA_PED = :CODIGO_IVA_PED, ESVENTA_ACTIVO_FIJO_PED = :ESVENTA_ACTIVO_FIJO_PED, PORCENTAJE_IVAN_PED = :PORCENTAJE_IVAN_PED, ' +
        'TOTAL_IVAN_PED = :TOTAL_IVAN_PED, PORCENTAJE_REN_PED = :PORCENTAJE_REN_PED, TOTAL_REN_PED = :TOTAL_REN_PED, TOTAL_BASEI_IVAN_PED = :TOTAL_BASEI_IVAN_PED, PORCENTAJE_IVAR_PED = :PORCENTAJE_IVAR_PED, TO' +
        'TAL_IVAR_PED = :TOTAL_IVAR_PED, PORCENTAJE_RER_PED = :PORCENTAJE_RER_PED, TOTAL_RER_PED = :TOTAL_RER_PED, TOTAL_BASEI_IVAR_PED = :TOTAL_BASEI_IVAR_PED, PORCENTAJE_IVAS_PED = :PORCENTAJE_IVAS_PED, TOTA' +
        'L_IVAS_PED = :TOTAL_IVAS_PED, PORCENTAJE_RES_PED = :PORCENTAJE_RES_PED, TOTAL_RES_PED = :TOTAL_RES_PED, TOTAL_BASEI_IVAS_PED = :TOTAL_BASEI_IVAS_PED, PORCENTAJE_IVAE_PED = :PORCENTAJE_IVAE_PED, TOTAL_' +
        'IVAE_PED = :TOTAL_IVAE_PED, PORCENTAJE_REE_PED = :PORCENTAJE_REE_PED, TOTAL_REE_PED = :TOTAL_REE_PED, TOTAL_BASEI_IVAE_PED = :TOTAL_BASEI_IVAE_PED, TOTAL_BASES_PED = :TOTAL_BASES_PED, TOTAL_IMPUESTOS_' +
        'PED = :TOTAL_IMPUESTOS_PED, FORMA_PAGO_PED = :FORMA_PAGO_PED, PORCENTAJE_RETENCION_PED = :PORCENTAJE_RETENCION_PED, TOTAL_RETENCION_PED = :TOTAL_RETENCION_PED, TOTAL_LIQUIDO_PED = :TOTAL_LIQUIDO_PED, ' +
        'TOTAL_PAGADOREALPS_PED = :TOTAL_PAGADOREALPS_PED, NUMERO_PED_ABONO_PED = :NUMERO_PED_ABONO_PED, SERIE_PED_ABONO_PED = :SERIE_PED_ABONO_PED, TEXTO_LEGAL_CLIENTE_PED = :TEXTO_LEGAL_CLIENTE_PED, TEXTO_LE' +
        'GAL_EMPRESA_PED = :TEXTO_LEGAL_EMPRESA_PED, DOCUMENTO_PED = :DOCUMENTO_PED, COMENTARIOS_PED = :COMENTARIOS_PED, CONTADOR_LINEAS_PED = :CONTADOR_LINEAS_PED, ESCREARARTICULOS_PED = :ESCREARARTICULOS_PED' +
        ', ESDESCRIPCIONES_AMP_PED = :ESDESCRIPCIONES_AMP_PED, ESFECHADEENTREGA_PED = :ESFECHADEENTREGA_PED, INSTANTE_MODIF = :INSTANTE_MODIF, INSTANTE_ALTA = :INSTANTE_ALTA, USUARIO_ALTA = :USUARIO_ALTA, USUA' +
        'RIO_MODIF = :USUARIO_MODIF'
      'WHERE'
      
        '  NUMERO_PED = :Old_NUMERO_PED AND SERIE_PED = :Old_SERIE_PED')
    SQLLock.Strings = (
      
        'SELECT NUMERO_PED, SERIE_PED, FECHA_PED, CODIGO_EMP_PED, RAZON_SOCIAL_EMPRESA_PED, NIF_EMPRESA_PED, MOVIL_EMPRESA_PED, EMAIL_EMPRESA_PED, DIRECCION1_EMPRESA_PED, DIRECCION2_EMPRESA_PED, POBLACION_EMPR' +
        'ESA_PED, PROVINCIA_EMPRESA_PED, CODIGO_PAI_EMPRESA_PED, NOMBRE_PAI_EMPRESA_PED, CODIGO_POSTAL_EMPRESA_PED, ESRETENCIONES_EMPRESA_PED, GRUPO_ZONA_IVA_EMPRESA_PED, ESREGIMENESPECIALAGRICOLA_EMPRESA_PED,' +
        ' CODIGO_CLI_PED, NIF_CLIENTE_PED, EMAIL_CLIENTE_PED, REFERENCIAPS_PED, IDPS_PED, FECHAPS_PED, FORMAPAGOPS_PED, TRANSPORTISTAPS_PED, ESTADOPEDIDOPS_PED, ESTADOMENSAJEPS_PED, IDHILOPS_MENSAJES_PED, NOMB' +
        'RE_CLI_ENVIO_PED, MOVIL_CLIENTE_ENVIO_PED, DIRECCION1_CLIENTE_ENVIO_PED, DIRECCION2_CLIENTE_ENVIO_PED, POBLACION_CLIENTE_ENVIO_PED, PROVINCIA_CLIENTE_ENVIO_PED, CODIGO_POSTAL_CLIENTE_ENVIO_PED, CODIGO' +
        '_PAI_CLIENTE_ENVIO_PED, NOMBRE_PAI_CLIENTE_ENVIO_PED, RAZON_SOCIAL_CLIENTE_FISCAL_PED, MOVIL_CLIENTE_FISCAL_PED, EMAIL_CLIENTE_FISCAL_PED, DIRECCION1_CLIENTE_FISCAL_PED, DIRECCION2_CLIENTE_FISCAL_PED,' +
        ' POBLACION_CLIENTE_FISCAL_PED, PROVINCIA_CLIENTE_FISCAL_PED, CODIGO_POSTAL_CLIENTE_FISCAL_PED, CODIGO_PAI_CLIENTE_FISCAL_PED, NOMBRE_PAI_CLIENTE_FISCAL_PED, ESIVA_RECARGO_CLIENTE_PED, ESIVA_EXENTO_CLI' +
        'ENTE_PED, ESREGIMENESPECIALAGRICOLA_CLIENTE_PED, ESRETENCIONES_CLIENTE_PED, TARIFA_ARTICULO_CLIENTE_PED, ESIMP_INCL_TARIFA_CLIENTE_PED, ESINTRACOMUNITARIO_CLIENTE_PED, ESIRPF_IMP_INCL_ZONA_IVA_PED, ES' +
        'APLICA_RE_ZONA_IVA_PED, ESIVAAGRICOLA_ZONA_IVA_PED, PALABRA_REPORTS_ZONA_IVA_PED, CODIGO_IVA_PED, ESVENTA_ACTIVO_FIJO_PED, PORCENTAJE_IVAN_PED, TOTAL_IVAN_PED, PORCENTAJE_REN_PED, TOTAL_REN_PED, TOTAL' +
        '_BASEI_IVAN_PED, PORCENTAJE_IVAR_PED, TOTAL_IVAR_PED, PORCENTAJE_RER_PED, TOTAL_RER_PED, TOTAL_BASEI_IVAR_PED, PORCENTAJE_IVAS_PED, TOTAL_IVAS_PED, PORCENTAJE_RES_PED, TOTAL_RES_PED, TOTAL_BASEI_IVAS_' +
        'PED, PORCENTAJE_IVAE_PED, TOTAL_IVAE_PED, PORCENTAJE_REE_PED, TOTAL_REE_PED, TOTAL_BASEI_IVAE_PED, TOTAL_BASES_PED, TOTAL_IMPUESTOS_PED, FORMA_PAGO_PED, PORCENTAJE_RETENCION_PED, TOTAL_RETENCION_PED, ' +
        'TOTAL_LIQUIDO_PED, TOTAL_PAGADOREALPS_PED, NUMERO_PED_ABONO_PED, SERIE_PED_ABONO_PED, TEXTO_LEGAL_CLIENTE_PED, TEXTO_LEGAL_EMPRESA_PED, DOCUMENTO_PED, COMENTARIOS_PED, CONTADOR_LINEAS_PED, ESCREARARTI' +
        'CULOS_PED, ESDESCRIPCIONES_AMP_PED, ESFECHADEENTREGA_PED, INSTANTE_MODIF, INSTANTE_ALTA, USUARIO_ALTA, USUARIO_MODIF FROM fza_pedidos'
      'WHERE'
      
        '  NUMERO_PED = :Old_NUMERO_PED AND SERIE_PED = :Old_SERIE_PED'
      'FOR UPDATE')
    SQLRefresh.Strings = (
      
        'SELECT NUMERO_PED, SERIE_PED, FECHA_PED, CODIGO_EMP_PED, RAZON_SOCIAL_EMPRESA_PED, NIF_EMPRESA_PED, MOVIL_EMPRESA_PED, EMAIL_EMPRESA_PED, DIRECCION1_EMPRESA_PED, DIRECCION2_EMPRESA_PED, POBLACION_EMPR' +
        'ESA_PED, PROVINCIA_EMPRESA_PED, CODIGO_PAI_EMPRESA_PED, NOMBRE_PAI_EMPRESA_PED, CODIGO_POSTAL_EMPRESA_PED, ESRETENCIONES_EMPRESA_PED, GRUPO_ZONA_IVA_EMPRESA_PED, ESREGIMENESPECIALAGRICOLA_EMPRESA_PED,' +
        ' CODIGO_CLI_PED, NIF_CLIENTE_PED, EMAIL_CLIENTE_PED, REFERENCIAPS_PED, IDPS_PED, FECHAPS_PED, FORMAPAGOPS_PED, TRANSPORTISTAPS_PED, ESTADOPEDIDOPS_PED, ESTADOMENSAJEPS_PED, IDHILOPS_MENSAJES_PED, NOMB' +
        'RE_CLI_ENVIO_PED, MOVIL_CLIENTE_ENVIO_PED, DIRECCION1_CLIENTE_ENVIO_PED, DIRECCION2_CLIENTE_ENVIO_PED, POBLACION_CLIENTE_ENVIO_PED, PROVINCIA_CLIENTE_ENVIO_PED, CODIGO_POSTAL_CLIENTE_ENVIO_PED, CODIGO' +
        '_PAI_CLIENTE_ENVIO_PED, NOMBRE_PAI_CLIENTE_ENVIO_PED, RAZON_SOCIAL_CLIENTE_FISCAL_PED, MOVIL_CLIENTE_FISCAL_PED, EMAIL_CLIENTE_FISCAL_PED, DIRECCION1_CLIENTE_FISCAL_PED, DIRECCION2_CLIENTE_FISCAL_PED,' +
        ' POBLACION_CLIENTE_FISCAL_PED, PROVINCIA_CLIENTE_FISCAL_PED, CODIGO_POSTAL_CLIENTE_FISCAL_PED, CODIGO_PAI_CLIENTE_FISCAL_PED, NOMBRE_PAI_CLIENTE_FISCAL_PED, ESIVA_RECARGO_CLIENTE_PED, ESIVA_EXENTO_CLI' +
        'ENTE_PED, ESREGIMENESPECIALAGRICOLA_CLIENTE_PED, ESRETENCIONES_CLIENTE_PED, TARIFA_ARTICULO_CLIENTE_PED, ESIMP_INCL_TARIFA_CLIENTE_PED, ESINTRACOMUNITARIO_CLIENTE_PED, ESIRPF_IMP_INCL_ZONA_IVA_PED, ES' +
        'APLICA_RE_ZONA_IVA_PED, ESIVAAGRICOLA_ZONA_IVA_PED, PALABRA_REPORTS_ZONA_IVA_PED, CODIGO_IVA_PED, ESVENTA_ACTIVO_FIJO_PED, PORCENTAJE_IVAN_PED, TOTAL_IVAN_PED, PORCENTAJE_REN_PED, TOTAL_REN_PED, TOTAL' +
        '_BASEI_IVAN_PED, PORCENTAJE_IVAR_PED, TOTAL_IVAR_PED, PORCENTAJE_RER_PED, TOTAL_RER_PED, TOTAL_BASEI_IVAR_PED, PORCENTAJE_IVAS_PED, TOTAL_IVAS_PED, PORCENTAJE_RES_PED, TOTAL_RES_PED, TOTAL_BASEI_IVAS_' +
        'PED, PORCENTAJE_IVAE_PED, TOTAL_IVAE_PED, PORCENTAJE_REE_PED, TOTAL_REE_PED, TOTAL_BASEI_IVAE_PED, TOTAL_BASES_PED, TOTAL_IMPUESTOS_PED, FORMA_PAGO_PED, PORCENTAJE_RETENCION_PED, TOTAL_RETENCION_PED, ' +
        'TOTAL_LIQUIDO_PED, TOTAL_PAGADOREALPS_PED, NUMERO_PED_ABONO_PED, SERIE_PED_ABONO_PED, TEXTO_LEGAL_CLIENTE_PED, TEXTO_LEGAL_EMPRESA_PED, DOCUMENTO_PED, COMENTARIOS_PED, CONTADOR_LINEAS_PED, ESCREARARTI' +
        'CULOS_PED, ESDESCRIPCIONES_AMP_PED, ESFECHADEENTREGA_PED, INSTANTE_MODIF, INSTANTE_ALTA, USUARIO_ALTA, USUARIO_MODIF FROM fza_pedidos'
      'WHERE'
      '  NUMERO_PED = :NUMERO_PED AND SERIE_PED = :SERIE_PED')
    SQLRecCount.Strings = (
      'SELECT COUNT(*) FROM fza_pedidos')
    Connection = dmConn.conUni
    SQL.Strings = (
      'select * from vi_pedidos')
    Left = 48
    Top = 24
  end
  object unqryPerfiles: TUniQuery
    Connection = dmConn.conUni
    SQL.Strings = (
      'select *'
      'from fza_usuarios_perfiles')
    Left = 496
    Top = 96
  end
  object dsPerfiles: TDataSource
    DataSet = unqryPerfiles
    Left = 495
    Top = 32
  end
end
