inherited dmFacturas: TdmFacturas
  Height = 638
  Width = 1445
  PixelsPerInch = 120
  inherited unqryTablaG: TUniQuery
    SQLInsert.Strings = (
      'INSERT INTO `fza_facturas`'
      
        '  (`NRO_FACTURA`, `SERIE_FACTURA`, `FECHA_FACTURA`, `ESCONSOLIDA' +
        'DA_FACTURA`, `INSTANTECONSO_FACTURA`, `TIPO_FACTURA`, `FASE_FACT' +
        'URA`, `CODIGO_EMPRESA_FACTURA`, `RAZONSOCIAL_EMPRESA_FACTURA`, `' +
        'NIF_EMPRESA_FACTURA`, `MOVIL_EMPRESA_FACTURA`, `EMAIL_EMPRESA_FA' +
        'CTURA`, `DIRECCION1_EMPRESA_FACTURA`, `DIRECCION2_EMPRESA_FACTUR' +
        'A`, `POBLACION_EMPRESA_FACTURA`, `PROVINCIA_EMPRESA_FACTURA`, `C' +
        'ODIGO_PAIS_EMPRESA_FACTURA`, `NOMBRE_PAIS_EMPRESA_FACTURA`, `CPO' +
        'STAL_EMPRESA_FACTURA`, `ESRETENCIONES_EMPRESA_FACTURA`, `GRUPO_Z' +
        'ONA_IVA_EMPRESA_FACTURA`, `ESREGIMENESPECIALAGRICOLA_EMPRESA_FAC' +
        'TURA`, `CODIGO_CLIENTE_FACTURA`, `RAZONSOCIAL_CLIENTE_FACTURA`, ' +
        '`NIF_CLIENTE_FACTURA`, `MOVIL_CLIENTE_FACTURA`, `EMAIL_CLIENTE_F' +
        'ACTURA`, `DIRECCION1_CLIENTE_FACTURA`, `DIRECCION2_CLIENTE_FACTU' +
        'RA`, `POBLACION_CLIENTE_FACTURA`, `PROVINCIA_CLIENTE_FACTURA`, `' +
        'CPOSTAL_CLIENTE_FACTURA`, `CODIGO_PAIS_CLIENTE_FACTURA`, `NOMBRE' +
        '_PAIS_CLIENTE_FACTURA`, `CODIGO_IVA_FACTURA`, `ESIVA_RECARGO_CLI' +
        'ENTE_FACTURA`, `ESIVA_EXENTO_CLIENTE_FACTURA`, `ESREGIMENESPECIA' +
        'LAGRICOLA_CLIENTE_FACTURA`, `ESRETENCIONES_CLIENTE_FACTURA`, `TA' +
        'RIFA_ARTICULO_CLIENTE_FACTURA`, `ESIMP_INCL_TARIFA_CLIENTE_FACTU' +
        'RA`, `ESINTRACOMUNITARIO_CLIENTE_FACTURA`, `ESIRPF_IMP_INCL_ZONA' +
        '_IVA_FACTURA`, `ESAPLICA_RE_ZONA_IVA_FACTURA`, `ESIVAAGRICOLA_ZO' +
        'NA_IVA_FACTURA`, `PALABRA_REPORTS_ZONA_IVA_FACTURA`, `ESVENTA_AC' +
        'TIVO_FIJO_FACTURA`, `PORCEN_IVAN_FACTURA`, `TOTAL_IVAN_FACTURA`,' +
        ' `PORCEN_REN_FACTURA`, `TOTAL_REN_FACTURA`, `TOTAL_BASEI_IVAN_FA' +
        'CTURA`, `PORCEN_IVAR_FACTURA`, `TOTAL_IVAR_FACTURA`, `PORCEN_RER' +
        '_FACTURA`, `TOTAL_RER_FACTURA`, `TOTAL_BASEI_IVAR_FACTURA`, `POR' +
        'CEN_IVAS_FACTURA`, `TOTAL_IVAS_FACTURA`, `PORCEN_RES_FACTURA`, `' +
        'TOTAL_RES_FACTURA`, `TOTAL_BASEI_IVAS_FACTURA`, `PORCEN_IVAE_FAC' +
        'TURA`, `TOTAL_IVAE_FACTURA`, `PORCEN_REE_FACTURA`, `TOTAL_REE_FA' +
        'CTURA`, `TOTAL_BASEI_IVAE_FACTURA`, `TOTAL_BASES_FACTURA`, `TOTA' +
        'L_IMPUESTOS_FACTURA`, `FORMA_PAGO_FACTURA`, `PORCEN_RETENCION_FA' +
        'CTURA`, `TOTAL_RETENCION_FACTURA`, `TOTAL_LIQUIDO_FACTURA`, `NRO' +
        '_FACTURA_ABONO_FACTURA`, `SERIE_FACTURA_ABONO_FACTURA`, `TEXTO_L' +
        'EGAL_FACTURA_CLIENTE_FACTURA`, `TEXTO_LEGAL_FACTURA_EMPRESA_FACT' +
        'URA`, `DOCUMENTO_FACTURA`, `COMENTARIOS_FACTURA`, `CONTADOR_LINE' +
        'AS_FACTURA`, `ESCREARARTICULOS_FACTURA`, `ESDESCRIPCIONES_AMP_FA' +
        'CTURA`, `ESFECHADEENTREGA_FACTURA`, `XML_FACTURA`, `INSTANTEMODI' +
        'F`, `INSTANTEALTA`, `USUARIOALTA`, `USUARIOMODIF`, `CODIGO_CAJER' +
        'O_FACTURA`, `CODIGO_ALMACEN_FACTURA`, `CODIGO_CAJA_FACTURA`, `NU' +
        'MERO_OPERACION_FACTURA`)'
      'VALUES'
      
        '  (:`NRO_FACTURA`, :`SERIE_FACTURA`, :`FECHA_FACTURA`, :`ESCONSO' +
        'LIDADA_FACTURA`, :`INSTANTECONSO_FACTURA`, :`TIPO_FACTURA`, :`FA' +
        'SE_FACTURA`, :`CODIGO_EMPRESA_FACTURA`, :`RAZONSOCIAL_EMPRESA_FA' +
        'CTURA`, :`NIF_EMPRESA_FACTURA`, :`MOVIL_EMPRESA_FACTURA`, :`EMAI' +
        'L_EMPRESA_FACTURA`, :`DIRECCION1_EMPRESA_FACTURA`, :`DIRECCION2_' +
        'EMPRESA_FACTURA`, :`POBLACION_EMPRESA_FACTURA`, :`PROVINCIA_EMPR' +
        'ESA_FACTURA`, :`CODIGO_PAIS_EMPRESA_FACTURA`, :`NOMBRE_PAIS_EMPR' +
        'ESA_FACTURA`, :`CPOSTAL_EMPRESA_FACTURA`, :`ESRETENCIONES_EMPRES' +
        'A_FACTURA`, :`GRUPO_ZONA_IVA_EMPRESA_FACTURA`, :`ESREGIMENESPECI' +
        'ALAGRICOLA_EMPRESA_FACTURA`, :`CODIGO_CLIENTE_FACTURA`, :`RAZONS' +
        'OCIAL_CLIENTE_FACTURA`, :`NIF_CLIENTE_FACTURA`, :`MOVIL_CLIENTE_' +
        'FACTURA`, :`EMAIL_CLIENTE_FACTURA`, :`DIRECCION1_CLIENTE_FACTURA' +
        '`, :`DIRECCION2_CLIENTE_FACTURA`, :`POBLACION_CLIENTE_FACTURA`, ' +
        ':`PROVINCIA_CLIENTE_FACTURA`, :`CPOSTAL_CLIENTE_FACTURA`, :`CODI' +
        'GO_PAIS_CLIENTE_FACTURA`, :`NOMBRE_PAIS_CLIENTE_FACTURA`, :`CODI' +
        'GO_IVA_FACTURA`, :`ESIVA_RECARGO_CLIENTE_FACTURA`, :`ESIVA_EXENT' +
        'O_CLIENTE_FACTURA`, :`ESREGIMENESPECIALAGRICOLA_CLIENTE_FACTURA`' +
        ', :`ESRETENCIONES_CLIENTE_FACTURA`, :`TARIFA_ARTICULO_CLIENTE_FA' +
        'CTURA`, :`ESIMP_INCL_TARIFA_CLIENTE_FACTURA`, :`ESINTRACOMUNITAR' +
        'IO_CLIENTE_FACTURA`, :`ESIRPF_IMP_INCL_ZONA_IVA_FACTURA`, :`ESAP' +
        'LICA_RE_ZONA_IVA_FACTURA`, :`ESIVAAGRICOLA_ZONA_IVA_FACTURA`, :`' +
        'PALABRA_REPORTS_ZONA_IVA_FACTURA`, :`ESVENTA_ACTIVO_FIJO_FACTURA' +
        '`, :`PORCEN_IVAN_FACTURA`, :`TOTAL_IVAN_FACTURA`, :`PORCEN_REN_F' +
        'ACTURA`, :`TOTAL_REN_FACTURA`, :`TOTAL_BASEI_IVAN_FACTURA`, :`PO' +
        'RCEN_IVAR_FACTURA`, :`TOTAL_IVAR_FACTURA`, :`PORCEN_RER_FACTURA`' +
        ', :`TOTAL_RER_FACTURA`, :`TOTAL_BASEI_IVAR_FACTURA`, :`PORCEN_IV' +
        'AS_FACTURA`, :`TOTAL_IVAS_FACTURA`, :`PORCEN_RES_FACTURA`, :`TOT' +
        'AL_RES_FACTURA`, :`TOTAL_BASEI_IVAS_FACTURA`, :`PORCEN_IVAE_FACT' +
        'URA`, :`TOTAL_IVAE_FACTURA`, :`PORCEN_REE_FACTURA`, :`TOTAL_REE_' +
        'FACTURA`, :`TOTAL_BASEI_IVAE_FACTURA`, :`TOTAL_BASES_FACTURA`, :' +
        '`TOTAL_IMPUESTOS_FACTURA`, :`FORMA_PAGO_FACTURA`, :`PORCEN_RETEN' +
        'CION_FACTURA`, :`TOTAL_RETENCION_FACTURA`, :`TOTAL_LIQUIDO_FACTU' +
        'RA`, :`NRO_FACTURA_ABONO_FACTURA`, :`SERIE_FACTURA_ABONO_FACTURA' +
        '`, :`TEXTO_LEGAL_FACTURA_CLIENTE_FACTURA`, :`TEXTO_LEGAL_FACTURA' +
        '_EMPRESA_FACTURA`, :`DOCUMENTO_FACTURA`, :`COMENTARIOS_FACTURA`,' +
        ' :`CONTADOR_LINEAS_FACTURA`, :`ESCREARARTICULOS_FACTURA`, :`ESDE' +
        'SCRIPCIONES_AMP_FACTURA`, :`ESFECHADEENTREGA_FACTURA`, :`XML_FAC' +
        'TURA`, :`INSTANTEMODIF`, :`INSTANTEALTA`, :`USUARIOALTA`, :`USUA' +
        'RIOMODIF`, :`CODIGO_CAJERO_FACTURA`, :`CODIGO_ALMACEN_FACTURA`, ' +
        ':`CODIGO_CAJA_FACTURA`, :`NUMERO_OPERACION_FACTURA`)')
    SQLDelete.Strings = (
      'DELETE FROM `fza_facturas`'
      'WHERE'
      
        '  `NRO_FACTURA` = :`Old_NRO_FACTURA` AND `SERIE_FACTURA` = :`Old' +
        '_SERIE_FACTURA`')
    SQLUpdate.Strings = (
      'UPDATE `fza_facturas`'
      'SET'
      
        '  `NRO_FACTURA` = :`NRO_FACTURA`, `SERIE_FACTURA` = :`SERIE_FACT' +
        'URA`, `FECHA_FACTURA` = :`FECHA_FACTURA`, `ESCONSOLIDADA_FACTURA' +
        '` = :`ESCONSOLIDADA_FACTURA`, `INSTANTECONSO_FACTURA` = :`INSTAN' +
        'TECONSO_FACTURA`, `TIPO_FACTURA` = :`TIPO_FACTURA`, `FASE_FACTUR' +
        'A` = :`FASE_FACTURA`, `CODIGO_EMPRESA_FACTURA` = :`CODIGO_EMPRES' +
        'A_FACTURA`, `RAZONSOCIAL_EMPRESA_FACTURA` = :`RAZONSOCIAL_EMPRES' +
        'A_FACTURA`, `NIF_EMPRESA_FACTURA` = :`NIF_EMPRESA_FACTURA`, `MOV' +
        'IL_EMPRESA_FACTURA` = :`MOVIL_EMPRESA_FACTURA`, `EMAIL_EMPRESA_F' +
        'ACTURA` = :`EMAIL_EMPRESA_FACTURA`, `DIRECCION1_EMPRESA_FACTURA`' +
        ' = :`DIRECCION1_EMPRESA_FACTURA`, `DIRECCION2_EMPRESA_FACTURA` =' +
        ' :`DIRECCION2_EMPRESA_FACTURA`, `POBLACION_EMPRESA_FACTURA` = :`' +
        'POBLACION_EMPRESA_FACTURA`, `PROVINCIA_EMPRESA_FACTURA` = :`PROV' +
        'INCIA_EMPRESA_FACTURA`, `CODIGO_PAIS_EMPRESA_FACTURA` = :`CODIGO' +
        '_PAIS_EMPRESA_FACTURA`, `NOMBRE_PAIS_EMPRESA_FACTURA` = :`NOMBRE' +
        '_PAIS_EMPRESA_FACTURA`, `CPOSTAL_EMPRESA_FACTURA` = :`CPOSTAL_EM' +
        'PRESA_FACTURA`, `ESRETENCIONES_EMPRESA_FACTURA` = :`ESRETENCIONE' +
        'S_EMPRESA_FACTURA`, `GRUPO_ZONA_IVA_EMPRESA_FACTURA` = :`GRUPO_Z' +
        'ONA_IVA_EMPRESA_FACTURA`, `ESREGIMENESPECIALAGRICOLA_EMPRESA_FAC' +
        'TURA` = :`ESREGIMENESPECIALAGRICOLA_EMPRESA_FACTURA`, `CODIGO_CL' +
        'IENTE_FACTURA` = :`CODIGO_CLIENTE_FACTURA`, `RAZONSOCIAL_CLIENTE' +
        '_FACTURA` = :`RAZONSOCIAL_CLIENTE_FACTURA`, `NIF_CLIENTE_FACTURA' +
        '` = :`NIF_CLIENTE_FACTURA`, `MOVIL_CLIENTE_FACTURA` = :`MOVIL_CL' +
        'IENTE_FACTURA`, `EMAIL_CLIENTE_FACTURA` = :`EMAIL_CLIENTE_FACTUR' +
        'A`, `DIRECCION1_CLIENTE_FACTURA` = :`DIRECCION1_CLIENTE_FACTURA`' +
        ', `DIRECCION2_CLIENTE_FACTURA` = :`DIRECCION2_CLIENTE_FACTURA`, ' +
        '`POBLACION_CLIENTE_FACTURA` = :`POBLACION_CLIENTE_FACTURA`, `PRO' +
        'VINCIA_CLIENTE_FACTURA` = :`PROVINCIA_CLIENTE_FACTURA`, `CPOSTAL' +
        '_CLIENTE_FACTURA` = :`CPOSTAL_CLIENTE_FACTURA`, `CODIGO_PAIS_CLI' +
        'ENTE_FACTURA` = :`CODIGO_PAIS_CLIENTE_FACTURA`, `NOMBRE_PAIS_CLI' +
        'ENTE_FACTURA` = :`NOMBRE_PAIS_CLIENTE_FACTURA`, `CODIGO_IVA_FACT' +
        'URA` = :`CODIGO_IVA_FACTURA`, `ESIVA_RECARGO_CLIENTE_FACTURA` = ' +
        ':`ESIVA_RECARGO_CLIENTE_FACTURA`, `ESIVA_EXENTO_CLIENTE_FACTURA`' +
        ' = :`ESIVA_EXENTO_CLIENTE_FACTURA`, `ESREGIMENESPECIALAGRICOLA_C' +
        'LIENTE_FACTURA` = :`ESREGIMENESPECIALAGRICOLA_CLIENTE_FACTURA`, ' +
        '`ESRETENCIONES_CLIENTE_FACTURA` = :`ESRETENCIONES_CLIENTE_FACTUR' +
        'A`, `TARIFA_ARTICULO_CLIENTE_FACTURA` = :`TARIFA_ARTICULO_CLIENT' +
        'E_FACTURA`, `ESIMP_INCL_TARIFA_CLIENTE_FACTURA` = :`ESIMP_INCL_T' +
        'ARIFA_CLIENTE_FACTURA`, `ESINTRACOMUNITARIO_CLIENTE_FACTURA` = :' +
        '`ESINTRACOMUNITARIO_CLIENTE_FACTURA`, `ESIRPF_IMP_INCL_ZONA_IVA_' +
        'FACTURA` = :`ESIRPF_IMP_INCL_ZONA_IVA_FACTURA`, `ESAPLICA_RE_ZON' +
        'A_IVA_FACTURA` = :`ESAPLICA_RE_ZONA_IVA_FACTURA`, `ESIVAAGRICOLA' +
        '_ZONA_IVA_FACTURA` = :`ESIVAAGRICOLA_ZONA_IVA_FACTURA`, `PALABRA' +
        '_REPORTS_ZONA_IVA_FACTURA` = :`PALABRA_REPORTS_ZONA_IVA_FACTURA`' +
        ', `ESVENTA_ACTIVO_FIJO_FACTURA` = :`ESVENTA_ACTIVO_FIJO_FACTURA`' +
        ', `PORCEN_IVAN_FACTURA` = :`PORCEN_IVAN_FACTURA`, `TOTAL_IVAN_FA' +
        'CTURA` = :`TOTAL_IVAN_FACTURA`, `PORCEN_REN_FACTURA` = :`PORCEN_' +
        'REN_FACTURA`, `TOTAL_REN_FACTURA` = :`TOTAL_REN_FACTURA`, `TOTAL' +
        '_BASEI_IVAN_FACTURA` = :`TOTAL_BASEI_IVAN_FACTURA`, `PORCEN_IVAR' +
        '_FACTURA` = :`PORCEN_IVAR_FACTURA`, `TOTAL_IVAR_FACTURA` = :`TOT' +
        'AL_IVAR_FACTURA`, `PORCEN_RER_FACTURA` = :`PORCEN_RER_FACTURA`, ' +
        '`TOTAL_RER_FACTURA` = :`TOTAL_RER_FACTURA`, `TOTAL_BASEI_IVAR_FA' +
        'CTURA` = :`TOTAL_BASEI_IVAR_FACTURA`, `PORCEN_IVAS_FACTURA` = :`' +
        'PORCEN_IVAS_FACTURA`, `TOTAL_IVAS_FACTURA` = :`TOTAL_IVAS_FACTUR' +
        'A`, `PORCEN_RES_FACTURA` = :`PORCEN_RES_FACTURA`, `TOTAL_RES_FAC' +
        'TURA` = :`TOTAL_RES_FACTURA`, `TOTAL_BASEI_IVAS_FACTURA` = :`TOT' +
        'AL_BASEI_IVAS_FACTURA`, `PORCEN_IVAE_FACTURA` = :`PORCEN_IVAE_FA' +
        'CTURA`, `TOTAL_IVAE_FACTURA` = :`TOTAL_IVAE_FACTURA`, `PORCEN_RE' +
        'E_FACTURA` = :`PORCEN_REE_FACTURA`, `TOTAL_REE_FACTURA` = :`TOTA' +
        'L_REE_FACTURA`, `TOTAL_BASEI_IVAE_FACTURA` = :`TOTAL_BASEI_IVAE_' +
        'FACTURA`, `TOTAL_BASES_FACTURA` = :`TOTAL_BASES_FACTURA`, `TOTAL' +
        '_IMPUESTOS_FACTURA` = :`TOTAL_IMPUESTOS_FACTURA`, `FORMA_PAGO_FA' +
        'CTURA` = :`FORMA_PAGO_FACTURA`, `PORCEN_RETENCION_FACTURA` = :`P' +
        'ORCEN_RETENCION_FACTURA`, `TOTAL_RETENCION_FACTURA` = :`TOTAL_RE' +
        'TENCION_FACTURA`, `TOTAL_LIQUIDO_FACTURA` = :`TOTAL_LIQUIDO_FACT' +
        'URA`, `NRO_FACTURA_ABONO_FACTURA` = :`NRO_FACTURA_ABONO_FACTURA`' +
        ', `SERIE_FACTURA_ABONO_FACTURA` = :`SERIE_FACTURA_ABONO_FACTURA`' +
        ', `TEXTO_LEGAL_FACTURA_CLIENTE_FACTURA` = :`TEXTO_LEGAL_FACTURA_' +
        'CLIENTE_FACTURA`, `TEXTO_LEGAL_FACTURA_EMPRESA_FACTURA` = :`TEXT' +
        'O_LEGAL_FACTURA_EMPRESA_FACTURA`, `DOCUMENTO_FACTURA` = :`DOCUME' +
        'NTO_FACTURA`, `COMENTARIOS_FACTURA` = :`COMENTARIOS_FACTURA`, `C' +
        'ONTADOR_LINEAS_FACTURA` = :`CONTADOR_LINEAS_FACTURA`, `ESCREARAR' +
        'TICULOS_FACTURA` = :`ESCREARARTICULOS_FACTURA`, `ESDESCRIPCIONES' +
        '_AMP_FACTURA` = :`ESDESCRIPCIONES_AMP_FACTURA`, `ESFECHADEENTREG' +
        'A_FACTURA` = :`ESFECHADEENTREGA_FACTURA`, `XML_FACTURA` = :`XML_' +
        'FACTURA`, `INSTANTEMODIF` = :`INSTANTEMODIF`, `INSTANTEALTA` = :' +
        '`INSTANTEALTA`, `USUARIOALTA` = :`USUARIOALTA`, `USUARIOMODIF` =' +
        ' :`USUARIOMODIF`, `CODIGO_CAJERO_FACTURA` = :`CODIGO_CAJERO_FACT' +
        'URA`, `CODIGO_ALMACEN_FACTURA` = :`CODIGO_ALMACEN_FACTURA`, `COD' +
        'IGO_CAJA_FACTURA` = :`CODIGO_CAJA_FACTURA`, `NUMERO_OPERACION_FA' +
        'CTURA` = :`NUMERO_OPERACION_FACTURA`'
      'WHERE'
      
        '  `NRO_FACTURA` = :`Old_NRO_FACTURA` AND `SERIE_FACTURA` = :`Old' +
        '_SERIE_FACTURA`')
    SQLLock.Strings = (
      
        'SELECT `NRO_FACTURA`, `SERIE_FACTURA`, `FECHA_FACTURA`, `ESCONSO' +
        'LIDADA_FACTURA`, `INSTANTECONSO_FACTURA`, `TIPO_FACTURA`, `FASE_' +
        'FACTURA`, `CODIGO_EMPRESA_FACTURA`, `RAZONSOCIAL_EMPRESA_FACTURA' +
        '`, `NIF_EMPRESA_FACTURA`, `MOVIL_EMPRESA_FACTURA`, `EMAIL_EMPRES' +
        'A_FACTURA`, `DIRECCION1_EMPRESA_FACTURA`, `DIRECCION2_EMPRESA_FA' +
        'CTURA`, `POBLACION_EMPRESA_FACTURA`, `PROVINCIA_EMPRESA_FACTURA`' +
        ', `CODIGO_PAIS_EMPRESA_FACTURA`, `NOMBRE_PAIS_EMPRESA_FACTURA`, ' +
        '`CPOSTAL_EMPRESA_FACTURA`, `ESRETENCIONES_EMPRESA_FACTURA`, `GRU' +
        'PO_ZONA_IVA_EMPRESA_FACTURA`, `ESREGIMENESPECIALAGRICOLA_EMPRESA' +
        '_FACTURA`, `CODIGO_CLIENTE_FACTURA`, `RAZONSOCIAL_CLIENTE_FACTUR' +
        'A`, `NIF_CLIENTE_FACTURA`, `MOVIL_CLIENTE_FACTURA`, `EMAIL_CLIEN' +
        'TE_FACTURA`, `DIRECCION1_CLIENTE_FACTURA`, `DIRECCION2_CLIENTE_F' +
        'ACTURA`, `POBLACION_CLIENTE_FACTURA`, `PROVINCIA_CLIENTE_FACTURA' +
        '`, `CPOSTAL_CLIENTE_FACTURA`, `CODIGO_PAIS_CLIENTE_FACTURA`, `NO' +
        'MBRE_PAIS_CLIENTE_FACTURA`, `CODIGO_IVA_FACTURA`, `ESIVA_RECARGO' +
        '_CLIENTE_FACTURA`, `ESIVA_EXENTO_CLIENTE_FACTURA`, `ESREGIMENESP' +
        'ECIALAGRICOLA_CLIENTE_FACTURA`, `ESRETENCIONES_CLIENTE_FACTURA`,' +
        ' `TARIFA_ARTICULO_CLIENTE_FACTURA`, `ESIMP_INCL_TARIFA_CLIENTE_F' +
        'ACTURA`, `ESINTRACOMUNITARIO_CLIENTE_FACTURA`, `ESIRPF_IMP_INCL_' +
        'ZONA_IVA_FACTURA`, `ESAPLICA_RE_ZONA_IVA_FACTURA`, `ESIVAAGRICOL' +
        'A_ZONA_IVA_FACTURA`, `PALABRA_REPORTS_ZONA_IVA_FACTURA`, `ESVENT' +
        'A_ACTIVO_FIJO_FACTURA`, `PORCEN_IVAN_FACTURA`, `TOTAL_IVAN_FACTU' +
        'RA`, `PORCEN_REN_FACTURA`, `TOTAL_REN_FACTURA`, `TOTAL_BASEI_IVA' +
        'N_FACTURA`, `PORCEN_IVAR_FACTURA`, `TOTAL_IVAR_FACTURA`, `PORCEN' +
        '_RER_FACTURA`, `TOTAL_RER_FACTURA`, `TOTAL_BASEI_IVAR_FACTURA`, ' +
        '`PORCEN_IVAS_FACTURA`, `TOTAL_IVAS_FACTURA`, `PORCEN_RES_FACTURA' +
        '`, `TOTAL_RES_FACTURA`, `TOTAL_BASEI_IVAS_FACTURA`, `PORCEN_IVAE' +
        '_FACTURA`, `TOTAL_IVAE_FACTURA`, `PORCEN_REE_FACTURA`, `TOTAL_RE' +
        'E_FACTURA`, `TOTAL_BASEI_IVAE_FACTURA`, `TOTAL_BASES_FACTURA`, `' +
        'TOTAL_IMPUESTOS_FACTURA`, `FORMA_PAGO_FACTURA`, `PORCEN_RETENCIO' +
        'N_FACTURA`, `TOTAL_RETENCION_FACTURA`, `TOTAL_LIQUIDO_FACTURA`, ' +
        '`NRO_FACTURA_ABONO_FACTURA`, `SERIE_FACTURA_ABONO_FACTURA`, `TEX' +
        'TO_LEGAL_FACTURA_CLIENTE_FACTURA`, `TEXTO_LEGAL_FACTURA_EMPRESA_' +
        'FACTURA`, `DOCUMENTO_FACTURA`, `COMENTARIOS_FACTURA`, `CONTADOR_' +
        'LINEAS_FACTURA`, `ESCREARARTICULOS_FACTURA`, `ESDESCRIPCIONES_AM' +
        'P_FACTURA`, `ESFECHADEENTREGA_FACTURA`, `XML_FACTURA`, `INSTANTE' +
        'MODIF`, `INSTANTEALTA`, `USUARIOALTA`, `USUARIOMODIF`, `CODIGO_C' +
        'AJERO_FACTURA`, `CODIGO_ALMACEN_FACTURA`, `CODIGO_CAJA_FACTURA`,' +
        ' `NUMERO_OPERACION_FACTURA` FROM `fza_facturas`'
      'WHERE'
      
        '  `NRO_FACTURA` = :`Old_NRO_FACTURA` AND `SERIE_FACTURA` = :`Old' +
        '_SERIE_FACTURA`'
      'FOR UPDATE')
    SQLRefresh.Strings = (
      
        'SELECT `NRO_FACTURA`, `SERIE_FACTURA`, `FECHA_FACTURA`, `ESCONSO' +
        'LIDADA_FACTURA`, `INSTANTECONSO_FACTURA`, `TIPO_FACTURA`, `FASE_' +
        'FACTURA`, `CODIGO_EMPRESA_FACTURA`, `RAZONSOCIAL_EMPRESA_FACTURA' +
        '`, `NIF_EMPRESA_FACTURA`, `MOVIL_EMPRESA_FACTURA`, `EMAIL_EMPRES' +
        'A_FACTURA`, `DIRECCION1_EMPRESA_FACTURA`, `DIRECCION2_EMPRESA_FA' +
        'CTURA`, `POBLACION_EMPRESA_FACTURA`, `PROVINCIA_EMPRESA_FACTURA`' +
        ', `CODIGO_PAIS_EMPRESA_FACTURA`, `NOMBRE_PAIS_EMPRESA_FACTURA`, ' +
        '`CPOSTAL_EMPRESA_FACTURA`, `ESRETENCIONES_EMPRESA_FACTURA`, `GRU' +
        'PO_ZONA_IVA_EMPRESA_FACTURA`, `ESREGIMENESPECIALAGRICOLA_EMPRESA' +
        '_FACTURA`, `CODIGO_CLIENTE_FACTURA`, `RAZONSOCIAL_CLIENTE_FACTUR' +
        'A`, `NIF_CLIENTE_FACTURA`, `MOVIL_CLIENTE_FACTURA`, `EMAIL_CLIEN' +
        'TE_FACTURA`, `DIRECCION1_CLIENTE_FACTURA`, `DIRECCION2_CLIENTE_F' +
        'ACTURA`, `POBLACION_CLIENTE_FACTURA`, `PROVINCIA_CLIENTE_FACTURA' +
        '`, `CPOSTAL_CLIENTE_FACTURA`, `CODIGO_PAIS_CLIENTE_FACTURA`, `NO' +
        'MBRE_PAIS_CLIENTE_FACTURA`, `CODIGO_IVA_FACTURA`, `ESIVA_RECARGO' +
        '_CLIENTE_FACTURA`, `ESIVA_EXENTO_CLIENTE_FACTURA`, `ESREGIMENESP' +
        'ECIALAGRICOLA_CLIENTE_FACTURA`, `ESRETENCIONES_CLIENTE_FACTURA`,' +
        ' `TARIFA_ARTICULO_CLIENTE_FACTURA`, `ESIMP_INCL_TARIFA_CLIENTE_F' +
        'ACTURA`, `ESINTRACOMUNITARIO_CLIENTE_FACTURA`, `ESIRPF_IMP_INCL_' +
        'ZONA_IVA_FACTURA`, `ESAPLICA_RE_ZONA_IVA_FACTURA`, `ESIVAAGRICOL' +
        'A_ZONA_IVA_FACTURA`, `PALABRA_REPORTS_ZONA_IVA_FACTURA`, `ESVENT' +
        'A_ACTIVO_FIJO_FACTURA`, `PORCEN_IVAN_FACTURA`, `TOTAL_IVAN_FACTU' +
        'RA`, `PORCEN_REN_FACTURA`, `TOTAL_REN_FACTURA`, `TOTAL_BASEI_IVA' +
        'N_FACTURA`, `PORCEN_IVAR_FACTURA`, `TOTAL_IVAR_FACTURA`, `PORCEN' +
        '_RER_FACTURA`, `TOTAL_RER_FACTURA`, `TOTAL_BASEI_IVAR_FACTURA`, ' +
        '`PORCEN_IVAS_FACTURA`, `TOTAL_IVAS_FACTURA`, `PORCEN_RES_FACTURA' +
        '`, `TOTAL_RES_FACTURA`, `TOTAL_BASEI_IVAS_FACTURA`, `PORCEN_IVAE' +
        '_FACTURA`, `TOTAL_IVAE_FACTURA`, `PORCEN_REE_FACTURA`, `TOTAL_RE' +
        'E_FACTURA`, `TOTAL_BASEI_IVAE_FACTURA`, `TOTAL_BASES_FACTURA`, `' +
        'TOTAL_IMPUESTOS_FACTURA`, `FORMA_PAGO_FACTURA`, `PORCEN_RETENCIO' +
        'N_FACTURA`, `TOTAL_RETENCION_FACTURA`, `TOTAL_LIQUIDO_FACTURA`, ' +
        '`NRO_FACTURA_ABONO_FACTURA`, `SERIE_FACTURA_ABONO_FACTURA`, `TEX' +
        'TO_LEGAL_FACTURA_CLIENTE_FACTURA`, `TEXTO_LEGAL_FACTURA_EMPRESA_' +
        'FACTURA`, `DOCUMENTO_FACTURA`, `COMENTARIOS_FACTURA`, `CONTADOR_' +
        'LINEAS_FACTURA`, `ESCREARARTICULOS_FACTURA`, `ESDESCRIPCIONES_AM' +
        'P_FACTURA`, `ESFECHADEENTREGA_FACTURA`, `XML_FACTURA`, `INSTANTE' +
        'MODIF`, `INSTANTEALTA`, `USUARIOALTA`, `USUARIOMODIF`, `CODIGO_C' +
        'AJERO_FACTURA`, `CODIGO_ALMACEN_FACTURA`, `CODIGO_CAJA_FACTURA`,' +
        ' `NUMERO_OPERACION_FACTURA` FROM `fza_facturas`'
      'WHERE'
      
        '  `NRO_FACTURA` = :`NRO_FACTURA` AND `SERIE_FACTURA` = :`SERIE_F' +
        'ACTURA`')
    SQLRecCount.Strings = (
      'SELECT COUNT(*) FROM fza_facturas')
    Connection = dmConn.conUni
    SQL.Strings = (
      'select * from vi_facturas')
    BeforeInsert = nil
    AfterInsert = unqryTablaGAfterInsert
    BeforeEdit = unqryTablaGBeforeEdit
    BeforePost = unqryFacBeforePost
    AfterPost = unqryFacAfterPost
    BeforeDelete = unqryTablaGBeforeDelete
    Left = 56
    Top = 136
  end
  inherited unqryPerfiles: TUniQuery
    SQL.Strings = (
      'select *'
      'from fza_usuarios_perfiles')
    Left = 344
    Top = 176
  end
  inherited dsPerfiles: TDataSource
    Left = 343
    Top = 76
  end
  object dsLinFac: TDataSource
    DataSet = unqryLinFac
    OnStateChange = dsLinFacStateChange
    Left = 168
    Top = 48
  end
  object dsFacPrint: TDataSource
    DataSet = unqryFacPrint
    Left = 568
    Top = 496
  end
  object dsLinFacPrint: TDataSource
    DataSet = unqryLinFacPrint
    Left = 648
    Top = 496
  end
  object dsSeries: TDataSource
    DataSet = unqrySeries
    Left = 544
    Top = 48
  end
  object fxdsPrintFac: TfrxDBDataset
    Description = 'Facturas'
    UserName = 'Facturas'
    CloseDataSource = False
    FieldAliases.Strings = (
      'FECHA_FACTURA=FECHA_FACTURA'
      'NRO_FACTURA=NRO_FACTURA'
      'SERIE_FACTURA=SERIE_FACTURA'
      'TOTAL_LIQUIDO_FACTURA=TOTAL_LIQUIDO_FACTURA'
      'PORCEN_RETENCION_FACTURA=PORCEN_RETENCION_FACTURA'
      'TOTAL_RETENCION_FACTURA=TOTAL_RETENCION_FACTURA'
      'TOTAL_IMPUESTOS_FACTURA=TOTAL_IMPUESTOS_FACTURA'
      'TOTAL_BASES_FACTURA=TOTAL_BASES_FACTURA'
      'FORMA_PAGO_FACTURA=FORMA_PAGO_FACTURA'
      'CODIGO_EMPRESA_FACTURA=CODIGO_EMPRESA_FACTURA'
      'RAZONSOCIAL_EMPRESA_FACTURA=RAZONSOCIAL_EMPRESA_FACTURA'
      'NIF_EMPRESA_FACTURA=NIF_EMPRESA_FACTURA'
      'MOVIL_EMPRESA_FACTURA=MOVIL_EMPRESA_FACTURA'
      'EMAIL_EMPRESA_FACTURA=EMAIL_EMPRESA_FACTURA'
      'DIRECCION1_EMPRESA_FACTURA=DIRECCION1_EMPRESA_FACTURA'
      'DIRECCION2_EMPRESA_FACTURA=DIRECCION2_EMPRESA_FACTURA'
      'POBLACION_EMPRESA_FACTURA=POBLACION_EMPRESA_FACTURA'
      'PROVINCIA_EMPRESA_FACTURA=PROVINCIA_EMPRESA_FACTURA'
      'NOMBRE_PAIS_EMPRESA_FACTURA=NOMBRE_PAIS_EMPRESA_FACTURA'
      'CODIGO_PAIS_EMPRESA_FACTURA=CODIGO_PAIS_EMPRESA_FACTURA'
      'CPOSTAL_EMPRESA_FACTURA=CPOSTAL_EMPRESA_FACTURA'
      'ESRETENCIONES_EMPRESA_FACTURA=ESRETENCIONES_EMPRESA_FACTURA'
      'GRUPO_ZONA_IVA_EMPRESA_FACTURA=GRUPO_ZONA_IVA_EMPRESA_FACTURA'
      
        'ESREGIMENESPECIALAGRICOLA_EMPRESA_FACTURA=ESREGIMENESPECIALAGRIC' +
        'OLA_EMPRESA_FACTURA'
      'CODIGO_CLIENTE_FACTURA=CODIGO_CLIENTE_FACTURA'
      'RAZONSOCIAL_CLIENTE_FACTURA=RAZONSOCIAL_CLIENTE_FACTURA'
      'NIF_CLIENTE_FACTURA=NIF_CLIENTE_FACTURA'
      'MOVIL_CLIENTE_FACTURA=MOVIL_CLIENTE_FACTURA'
      'EMAIL_CLIENTE_FACTURA=EMAIL_CLIENTE_FACTURA'
      'DIRECCION1_CLIENTE_FACTURA=DIRECCION1_CLIENTE_FACTURA'
      'DIRECCION2_CLIENTE_FACTURA=DIRECCION2_CLIENTE_FACTURA'
      'POBLACION_CLIENTE_FACTURA=POBLACION_CLIENTE_FACTURA'
      'PROVINCIA_CLIENTE_FACTURA=PROVINCIA_CLIENTE_FACTURA'
      'CPOSTAL_CLIENTE_FACTURA=CPOSTAL_CLIENTE_FACTURA'
      'NOMBRE_PAIS_CLIENTE_FACTURA=NOMBRE_PAIS_CLIENTE_FACTURA'
      'CODIGO_PAIS_CLIENTE_FACTURA=CODIGO_PAIS_CLIENTE_FACTURA'
      'ESIVA_RECARGO_CLIENTE_FACTURA=ESIVA_RECARGO_CLIENTE_FACTURA'
      'ESIVA_EXENTO_CLIENTE_FACTURA=ESIVA_EXENTO_CLIENTE_FACTURA'
      
        'ESREGIMENESPECIALAGRICOLA_CLIENTE_FACTURA=ESREGIMENESPECIALAGRIC' +
        'OLA_CLIENTE_FACTURA'
      'ESRETENCIONES_CLIENTE_FACTURA=ESRETENCIONES_CLIENTE_FACTURA'
      'TARIFA_ARTICULO_CLIENTE_FACTURA=TARIFA_ARTICULO_CLIENTE_FACTURA'
      
        'ESIMP_INCL_TARIFA_CLIENTE_FACTURA=ESIMP_INCL_TARIFA_CLIENTE_FACT' +
        'URA'
      
        'ESINTRACOMUNITARIO_CLIENTE_FACTURA=ESINTRACOMUNITARIO_CLIENTE_FA' +
        'CTURA'
      
        'ESIRPF_IMP_INCL_ZONA_IVA_FACTURA=ESIRPF_IMP_INCL_ZONA_IVA_FACTUR' +
        'A'
      'ESAPLICA_RE_ZONA_IVA_FACTURA=ESAPLICA_RE_ZONA_IVA_FACTURA'
      'ESIVAAGRICOLA_ZONA_IVA_FACTURA=ESIVAAGRICOLA_ZONA_IVA_FACTURA'
      
        'PALABRA_REPORTS_ZONA_IVA_FACTURA=PALABRA_REPORTS_ZONA_IVA_FACTUR' +
        'A'
      'CODIGO_IVA_FACTURA=CODIGO_IVA_FACTURA'
      'ESVENTA_ACTIVO_FIJO_FACTURA=ESVENTA_ACTIVO_FIJO_FACTURA'
      'PORCEN_IVAN_FACTURA=PORCEN_IVAN_FACTURA'
      'TOTAL_IVAN_FACTURA=TOTAL_IVAN_FACTURA'
      'PORCEN_REN_FACTURA=PORCEN_REN_FACTURA'
      'TOTAL_REN_FACTURA=TOTAL_REN_FACTURA'
      'TOTAL_BASEI_IVAN_FACTURA=TOTAL_BASEI_IVAN_FACTURA'
      'PORCEN_IVAR_FACTURA=PORCEN_IVAR_FACTURA'
      'TOTAL_IVAR_FACTURA=TOTAL_IVAR_FACTURA'
      'PORCEN_RER_FACTURA=PORCEN_RER_FACTURA'
      'TOTAL_RER_FACTURA=TOTAL_RER_FACTURA'
      'TOTAL_BASEI_IVAR_FACTURA=TOTAL_BASEI_IVAR_FACTURA'
      'PORCEN_IVAS_FACTURA=PORCEN_IVAS_FACTURA'
      'TOTAL_IVAS_FACTURA=TOTAL_IVAS_FACTURA'
      'PORCEN_RES_FACTURA=PORCEN_RES_FACTURA'
      'TOTAL_RES_FACTURA=TOTAL_RES_FACTURA'
      'TOTAL_BASEI_IVAS_FACTURA=TOTAL_BASEI_IVAS_FACTURA'
      'PORCEN_IVAE_FACTURA=PORCEN_IVAE_FACTURA'
      'TOTAL_IVAE_FACTURA=TOTAL_IVAE_FACTURA'
      'PORCEN_REE_FACTURA=PORCEN_REE_FACTURA'
      'TOTAL_REE_FACTURA=TOTAL_REE_FACTURA'
      'TOTAL_BASEI_IVAE_FACTURA=TOTAL_BASEI_IVAE_FACTURA'
      'NRO_FACTURA_ABONO_FACTURA=NRO_FACTURA_ABONO_FACTURA'
      'SERIE_FACTURA_ABONO_FACTURA=SERIE_FACTURA_ABONO_FACTURA'
      
        'TEXTO_LEGAL_FACTURA_CLIENTE_FACTURA=TEXTO_LEGAL_FACTURA_CLIENTE_' +
        'FACTURA'
      
        'TEXTO_LEGAL_FACTURA_EMPRESA_FACTURA=TEXTO_LEGAL_FACTURA_EMPRESA_' +
        'FACTURA'
      'DOCUMENTO_FACTURA=DOCUMENTO_FACTURA'
      'COMENTARIOS_FACTURA=COMENTARIOS_FACTURA'
      'CONTADOR_LINEAS_FACTURA=CONTADOR_LINEAS_FACTURA'
      'ESCREARARTICULOS_FACTURA=ESCREARARTICULOS_FACTURA'
      'ESDESCRIPCIONES_AMP_FACTURA=ESDESCRIPCIONES_AMP_FACTURA'
      'ESFECHADEENTREGA_FACTURA=ESFECHADEENTREGA_FACTURA'
      'INSTANTEMODIF=INSTANTEMODIF'
      'INSTANTEALTA=INSTANTEALTA'
      'USUARIOALTA=USUARIOALTA'
      'USUARIOMODIF=USUARIOMODIF'
      'DESCRIPCION_FORMAPAGO=DESCRIPCION_FORMAPAGO'
      'ESCONTADO_FORMAPAGO=ESCONTADO_FORMAPAGO'
      'VENCIMIENTOS_RECIBOS=VENCIMIENTOS_RECIBOS'
      'IBAN_EMPRESA=IBAN_EMPRESA'
      'IBAN_CLIENTE=IBAN_CLIENTE'
      'ESVERBANCOEMPRESA_FORMAPAGO=ESVERBANCOEMPRESA_FORMAPAGO')
    DataSource = dsFacPrint
    BCDToCurrency = False
    DataSetOptions = []
    Left = 568
    Top = 432
  end
  object fxdstPrintLinFac: TfrxDBDataset
    Description = 'Lineas Facturas'
    UserName = 'Lineas Facturas'
    CloseDataSource = False
    FieldAliases.Strings = (
      'NRO_FACTURA_LINEA=NRO_FACTURA_LINEA'
      'SERIE_FACTURA_LINEA=SERIE_FACTURA_LINEA'
      'LINEA_FACTURA_LINEA=LINEA_FACTURA_LINEA'
      'CODIGO_ARTICULO_FACTURA_LINEA=CODIGO_ARTICULO_FACTURA_LINEA'
      'CODIGO_FAMILIA_FACTURA_LINEA=CODIGO_FAMILIA_FACTURA_LINEA'
      'NOMBRE_FAMILIA_FACTURA_LINEA=NOMBRE_FAMILIA_FACTURA_LINEA'
      'FECHA_ENTREGA_FACTURA_LINEA=FECHA_ENTREGA_FACTURA_LINEA'
      
        'TIPO_CANTIDAD_ARTICULO_FACTURA_LINEA=TIPO_CANTIDAD_ARTICULO_FACT' +
        'URA_LINEA'
      'ESIMP_INCL_TARIFA_FACTURA_LINEA=ESIMP_INCL_TARIFA_FACTURA_LINEA'
      'TIPOIVA_ARTICULO_FACTURA_LINEA=TIPOIVA_ARTICULO_FACTURA_LINEA'
      
        'DESCRIPCION_ARTICULO_FACTURA_LINEA=DESCRIPCION_ARTICULO_FACTURA_' +
        'LINEA'
      'CODIGO_TARIFA_FACTURA_LINEA=CODIGO_TARIFA_FACTURA_LINEA'
      'CANTIDAD_FACTURA_LINEA=CANTIDAD_FACTURA_LINEA'
      'PRECIOSALIDA_FACTURA_LINEA=PRECIOSALIDA_FACTURA_LINEA'
      'PORCEN_DTO_FACTURA_LINEA=PORCEN_DTO_FACTURA_LINEA'
      'PRECIO_DTO_FACTURA_LINEA=PRECIO_DTO_FACTURA_LINEA'
      
        'PRECIOVENTA_SIVA_ARTICULO_FACTURA_LINEA=PRECIOVENTA_SIVA_ARTICUL' +
        'O_FACTURA_LINEA'
      'PORCEN_IVA_FACTURA_LINEA=PORCEN_IVA_FACTURA_LINEA'
      
        'PRECIOVENTA_CIVA_ARTICULO_FACTURA_LINEA=PRECIOVENTA_CIVA_ARTICUL' +
        'O_FACTURA_LINEA'
      'TOTAL_FACTURA_LINEA=TOTAL_FACTURA_LINEA'
      'INSTANTEMODIF=INSTANTEMODIF'
      'INSTANTEALTA=INSTANTEALTA'
      'USUARIOALTA=USUARIOALTA'
      'USUARIOMODIF=USUARIOMODIF')
    DataSource = dsLinFacPrint
    BCDToCurrency = False
    DataSetOptions = []
    Left = 648
    Top = 432
  end
  object unqryFacPrint: TUniQuery
    Connection = dmConn.conUni
    SQL.Strings = (
      'SELECT *'
      'from VI_FACTURAS_PRINT'
      'where SERIE_FACTURA = '#39'ANA/2023'#39' '
      'AND NRO_FACTURA = '#39'000003'#39
      'order by NRO_FACTURA Asc')
    Left = 568
    Top = 552
  end
  object unqryLinFacPrint: TUniQuery
    SQLInsert.Strings = (
      'INSERT INTO `fza_FACTURAS_LINEAS`'
      
        '  (`SERIE_FACTURA_LINEA`, `NRO_FACTURA_LINEA`, `LINEA_LINEA`, `C' +
        'ODIGO_ARTICULO_LINEA`, `DESCRIPCION_ARTICULO_LINEA`, `ZONA`, `PR' +
        'ECIOVENTA_ARTICULO_LINEA`, `CANTIDAD_LINEA`, `SUM_TOTAL_LINEA`, ' +
        '`ODONTOLOGO`)'
      'VALUES'
      
        '  (:`SERIE_FACTURA_LINEA`, :`NRO_FACTURA_LINEA`, :`LINEA_LINEA`,' +
        ' :`CODIGO_ARTICULO_LINEA`, :`DESCRIPCION_ARTICULO_LINEA`, :`ZONA' +
        '`, :`PRECIOVENTA_ARTICULO_LINEA`, :`CANTIDAD_LINEA`, :`SUM_TOTAL' +
        '_LINEA`, :`ODONTOLOGO`)')
    SQLDelete.Strings = (
      'DELETE FROM `fza_FACTURAS_LINEAS`'
      'WHERE'
      
        '  `SERIE_FACTURA_LINEA` = :`Old_SERIE_FACTURA_LINEA` AND `NRO_FA' +
        'CTURA_LINEA` = :`Old_NRO_FACTURA_LINEA` AND `LINEA_LINEA` = :`Ol' +
        'd_LINEA_LINEA`')
    SQLUpdate.Strings = (
      'UPDATE `fza_FACTURAS_LINEAS`'
      'SET'
      
        '  `SERIE_FACTURA_LINEA` = :`SERIE_FACTURA_LINEA`, `NRO_FACTURA_L' +
        'INEA` = :`NRO_FACTURA_LINEA`, `LINEA_LINEA` = :`LINEA_LINEA`, `C' +
        'ODIGO_ARTICULO_LINEA` = :`CODIGO_ARTICULO_LINEA`, `DESCRIPCION_A' +
        'RTICULO_LINEA` = :`DESCRIPCION_ARTICULO_LINEA`, `ZONA` = :`ZONA`' +
        ', `PRECIOVENTA_ARTICULO_LINEA` = :`PRECIOVENTA_ARTICULO_LINEA`, ' +
        '`CANTIDAD_LINEA` = :`CANTIDAD_LINEA`, `SUM_TOTAL_LINEA` = :`SUM_' +
        'TOTAL_LINEA`, `ODONTOLOGO` = :`ODONTOLOGO`'
      'WHERE'
      
        '  `SERIE_FACTURA_LINEA` = :`Old_SERIE_FACTURA_LINEA` AND `NRO_FA' +
        'CTURA_LINEA` = :`Old_NRO_FACTURA_LINEA` AND `LINEA_LINEA` = :`Ol' +
        'd_LINEA_LINEA`')
    SQLLock.Strings = (
      'SELECT * FROM fza_FACTURAS_LINEAS'
      'WHERE'
      
        '  `SERIE_FACTURA_LINEA` = :`Old_SERIE_FACTURA_LINEA` AND `NRO_FA' +
        'CTURA_LINEA` = :`Old_NRO_FACTURA_LINEA` AND `LINEA_LINEA` = :`Ol' +
        'd_LINEA_LINEA`'
      'FOR UPDATE')
    SQLRefresh.Strings = (
      
        'SELECT `SERIE_FACTURA_LINEA`, `NRO_FACTURA_LINEA`, `LINEA_LINEA`' +
        ', `CODIGO_ARTICULO_LINEA`, `DESCRIPCION_ARTICULO_LINEA`, `ZONA`,' +
        ' `PRECIOVENTA_ARTICULO_LINEA`, `CANTIDAD_LINEA`, `SUM_TOTAL_LINE' +
        'A`, `ODONTOLOGO` FROM `fza_FACTURAS_LINEAS`'
      'WHERE'
      
        '  `SERIE_FACTURA_LINEA` = :`SERIE_FACTURA_LINEA` AND `NRO_FACTUR' +
        'A_LINEA` = :`NRO_FACTURA_LINEA` AND `LINEA_LINEA` = :`LINEA_LINE' +
        'A`')
    SQLRecCount.Strings = (
      'SELECT COUNT(*) FROM fza_FACTURAS_LINEAS')
    Connection = dmConn.conUni
    SQL.Strings = (
      'SELECT *'
      ' FROM vi_FACTURAS_LINEAS_print'
      'WHERE NRO_FACTURA_LINEA = :NRO_FACTURA'
      '  AND SERIE_FACTURA_LINEA = :SERIE_FACTURA'
      'ORDER BY LINEA_FACTURA_LINEA;')
    MasterSource = dsFacPrint
    MasterFields = 'SERIE_FACTURA;NRO_FACTURA'
    DetailFields = 'SERIE_FACTURA_LINEA;NRO_FACTURA_LINEA'
    Left = 648
    Top = 552
    ParamData = <
      item
        DataType = ftWideString
        Name = 'NRO_FACTURA'
        ParamType = ptInput
        Value = '000003'
      end
      item
        DataType = ftWideString
        Name = 'SERIE_FACTURA'
        ParamType = ptInput
        Value = 'ANA/2023'
      end>
  end
  object unqrySeries: TUniQuery
    Connection = dmConn.conUni
    SQL.Strings = (
      'SELECT DISTINCT SERIE_CONTADOR, DEFAULT_CONTADOR'
      'FROM fza_CONTADORES'
      'WHERE TIPODOC_CONTADOR='#39'FC'#39' AND ACTIVO_CONTADOR = '#39'S'#39
      'ORDER BY DEFAULT_CONTADOR DESC')
    Left = 544
    Top = 144
  end
  object unqryCliDataFac: TUniQuery
    SQLInsert.Strings = (
      'INSERT INTO fza_clientes'
      
        '  (CODIGO_CLIENTE, ACTIVO_CLIENTE, RAZONSOCIAL_CLIENTE, NIF_CLIE' +
        'NTE, MOVIL_CLIENTE, EMAIL_CLIENTE, DIRECCION1_CLIENTE, DIRECCION' +
        '2_CLIENTE, POBLACION_CLIENTE, PROVINCIA_CLIENTE, CPOSTAL_CLIENTE' +
        ', PAIS_CLIENTE, OBSERVACIONES_CLIENTE, REFERENCIA_CLIENTE, CONTA' +
        'CTO_CLIENTE, TELEFONO_CONTACTO_CLIENTE, TELEFONO_CLIENTE, IBAN_C' +
        'LIENTE, IVA_RECARGO_CLIENTE, RETENCIONES_CLIENTE, CODIGO_FORMA_P' +
        'AGO, CODIGO_ZONA_IVA_CLIENTE, TEXTO_LEGAL_FACTURA_CLIENTE, INSTA' +
        'NTEMODIF, INSTANTEALTA, USUARIOALTA, USUARIOMODIF)'
      'VALUES'
      
        '  (:CODIGO_CLIENTE, :ACTIVO_CLIENTE, :RAZONSOCIAL_CLIENTE, :NIF_' +
        'CLIENTE, :MOVIL_CLIENTE, :EMAIL_CLIENTE, :DIRECCION1_CLIENTE, :D' +
        'IRECCION2_CLIENTE, :POBLACION_CLIENTE, :PROVINCIA_CLIENTE, :CPOS' +
        'TAL_CLIENTE, :PAIS_CLIENTE, :OBSERVACIONES_CLIENTE, :REFERENCIA_' +
        'CLIENTE, :CONTACTO_CLIENTE, :TELEFONO_CONTACTO_CLIENTE, :TELEFON' +
        'O_CLIENTE, :IBAN_CLIENTE, :IVA_RECARGO_CLIENTE, :RETENCIONES_CLI' +
        'ENTE, :CODIGO_FORMA_PAGO, :CODIGO_ZONA_IVA_CLIENTE, :TEXTO_LEGAL' +
        '_FACTURA_CLIENTE, :INSTANTEMODIF, :INSTANTEALTA, :USUARIOALTA, :' +
        'USUARIOMODIF)')
    SQLDelete.Strings = (
      'DELETE FROM fza_clientes'
      'WHERE'
      '  CODIGO_CLIENTE = :Old_CODIGO_CLIENTE')
    SQLUpdate.Strings = (
      'UPDATE fza_clientes'
      'SET'
      
        '  CODIGO_CLIENTE = :CODIGO_CLIENTE, ACTIVO_CLIENTE = :ACTIVO_CLI' +
        'ENTE, RAZONSOCIAL_CLIENTE = :RAZONSOCIAL_CLIENTE, NIF_CLIENTE = ' +
        ':NIF_CLIENTE, MOVIL_CLIENTE = :MOVIL_CLIENTE, EMAIL_CLIENTE = :E' +
        'MAIL_CLIENTE, DIRECCION1_CLIENTE = :DIRECCION1_CLIENTE, DIRECCIO' +
        'N2_CLIENTE = :DIRECCION2_CLIENTE, POBLACION_CLIENTE = :POBLACION' +
        '_CLIENTE, PROVINCIA_CLIENTE = :PROVINCIA_CLIENTE, CPOSTAL_CLIENT' +
        'E = :CPOSTAL_CLIENTE, PAIS_CLIENTE = :PAIS_CLIENTE, OBSERVACIONE' +
        'S_CLIENTE = :OBSERVACIONES_CLIENTE, REFERENCIA_CLIENTE = :REFERE' +
        'NCIA_CLIENTE, CONTACTO_CLIENTE = :CONTACTO_CLIENTE, TELEFONO_CON' +
        'TACTO_CLIENTE = :TELEFONO_CONTACTO_CLIENTE, TELEFONO_CLIENTE = :' +
        'TELEFONO_CLIENTE, IBAN_CLIENTE = :IBAN_CLIENTE, IVA_RECARGO_CLIE' +
        'NTE = :IVA_RECARGO_CLIENTE, RETENCIONES_CLIENTE = :RETENCIONES_C' +
        'LIENTE, CODIGO_FORMA_PAGO = :CODIGO_FORMA_PAGO, CODIGO_ZONA_IVA_' +
        'CLIENTE = :CODIGO_ZONA_IVA_CLIENTE, TEXTO_LEGAL_FACTURA_CLIENTE ' +
        '= :TEXTO_LEGAL_FACTURA_CLIENTE, INSTANTEMODIF = :INSTANTEMODIF, ' +
        'INSTANTEALTA = :INSTANTEALTA, USUARIOALTA = :USUARIOALTA, USUARI' +
        'OMODIF = :USUARIOMODIF'
      'WHERE'
      '  CODIGO_CLIENTE = :Old_CODIGO_CLIENTE')
    SQLLock.Strings = (
      'SELECT * FROM fza_clientes'
      'WHERE'
      '  CODIGO_CLIENTE = :Old_CODIGO_CLIENTE'
      'FOR UPDATE')
    SQLRefresh.Strings = (
      
        'SELECT CODIGO_CLIENTE, ACTIVO_CLIENTE, RAZONSOCIAL_CLIENTE, NIF_' +
        'CLIENTE, MOVIL_CLIENTE, EMAIL_CLIENTE, DIRECCION1_CLIENTE, DIREC' +
        'CION2_CLIENTE, POBLACION_CLIENTE, PROVINCIA_CLIENTE, CPOSTAL_CLI' +
        'ENTE, PAIS_CLIENTE, OBSERVACIONES_CLIENTE, REFERENCIA_CLIENTE, C' +
        'ONTACTO_CLIENTE, TELEFONO_CONTACTO_CLIENTE, TELEFONO_CLIENTE, IB' +
        'AN_CLIENTE, IVA_RECARGO_CLIENTE, RETENCIONES_CLIENTE, CODIGO_FOR' +
        'MA_PAGO, CODIGO_ZONA_IVA_CLIENTE, TEXTO_LEGAL_FACTURA_CLIENTE, I' +
        'NSTANTEMODIF, INSTANTEALTA, USUARIOALTA, USUARIOMODIF FROM fza_c' +
        'lientes'
      'WHERE'
      '  CODIGO_CLIENTE = :CODIGO_CLIENTE')
    SQLRecCount.Strings = (
      'SELECT COUNT(*) FROM fza_clientes')
    Connection = dmConn.conUni
    SQL.Strings = (
      'select * from vi_cli_busquedas')
    Left = 28
    Top = 536
  end
  object unqryArtDataLinFac: TUniQuery
    Connection = dmConn.conUni
    SQL.Strings = (
      'select * '
      '  from vi_art_busquedas'
      ' where (codigo_tarifa = :tarifa'
      '    or codigo_tarifa is null)'
      '   AND FECHA_DESDE_TARIFA < :FECHA_FACTURA'
      '   AND (FECHA_HASTA_TARIFA IS NULL'
      '        OR FECHA_HASTA_TARIFA > :FECHA_FACTURA)')
    Left = 250
    Top = 536
    ParamData = <
      item
        DataType = ftUnknown
        Name = 'tarifa'
        Value = nil
      end
      item
        DataType = ftUnknown
        Name = 'FECHA_FACTURA'
        Value = nil
      end>
  end
  object unqryLinFac: TUniQuery
    SQLInsert.Strings = (
      'INSERT INTO `fza_facturas_lineas`'
      
        '  (`NRO_FACTURA_LINEA`, `SERIE_FACTURA_LINEA`, `LINEA_FACTURA_LI' +
        'NEA`, `CODIGO_ARTICULO_FACTURA_LINEA`, `CODIGO_FAMILIA_FACTURA_L' +
        'INEA`, `NOMBRE_FAMILIA_FACTURA_LINEA`, `PRECIO_ULT_COMPRA_FACTUR' +
        'A_LINEA`, `CODIGO_PROVEEDOR_FACTURA_LINEA`, `RAZONSOCIAL_PROVEED' +
        'OR_FACTURA_LINEA`, `ESPROVEEDORPRINCIPAL_FACTURA_LINEA`, `FECHA_' +
        'ENTREGA_FACTURA_LINEA`, `TIPO_CANTIDAD_ARTICULO_FACTURA_LINEA`, ' +
        '`ESIMP_INCL_TARIFA_FACTURA_LINEA`, `TIPOIVA_ARTICULO_FACTURA_LIN' +
        'EA`, `DESCRIPCION_ARTICULO_FACTURA_LINEA`, `CODIGO_TARIFA_FACTUR' +
        'A_LINEA`, `CANTIDAD_FACTURA_LINEA`, `PRECIOSALIDA_FACTURA_LINEA`' +
        ', `PORCEN_DTO_FACTURA_LINEA`, `PRECIO_DTO_FACTURA_LINEA`, `PRECI' +
        'OVENTA_SIVA_ARTICULO_FACTURA_LINEA`, `PORCEN_IVA_FACTURA_LINEA`,' +
        ' `PRECIOVENTA_CIVA_ARTICULO_FACTURA_LINEA`, `TOTAL_FACTURA_LINEA' +
        '`, `TOTAL_FACTURASIVA_LINEA`, `INSTANTEMODIF`, `INSTANTEALTA`, `' +
        'USUARIOALTA`, `USUARIOMODIF`)'
      'VALUES'
      
        '  (:`NRO_FACTURA_LINEA`, :`SERIE_FACTURA_LINEA`, :`LINEA_FACTURA' +
        '_LINEA`, :`CODIGO_ARTICULO_FACTURA_LINEA`, :`CODIGO_FAMILIA_FACT' +
        'URA_LINEA`, :`NOMBRE_FAMILIA_FACTURA_LINEA`, :`PRECIO_ULT_COMPRA' +
        '_FACTURA_LINEA`, :`CODIGO_PROVEEDOR_FACTURA_LINEA`, :`RAZONSOCIA' +
        'L_PROVEEDOR_FACTURA_LINEA`, :`ESPROVEEDORPRINCIPAL_FACTURA_LINEA' +
        '`, :`FECHA_ENTREGA_FACTURA_LINEA`, :`TIPO_CANTIDAD_ARTICULO_FACT' +
        'URA_LINEA`, :`ESIMP_INCL_TARIFA_FACTURA_LINEA`, :`TIPOIVA_ARTICU' +
        'LO_FACTURA_LINEA`, :`DESCRIPCION_ARTICULO_FACTURA_LINEA`, :`CODI' +
        'GO_TARIFA_FACTURA_LINEA`, :`CANTIDAD_FACTURA_LINEA`, :`PRECIOSAL' +
        'IDA_FACTURA_LINEA`, :`PORCEN_DTO_FACTURA_LINEA`, :`PRECIO_DTO_FA' +
        'CTURA_LINEA`, :`PRECIOVENTA_SIVA_ARTICULO_FACTURA_LINEA`, :`PORC' +
        'EN_IVA_FACTURA_LINEA`, :`PRECIOVENTA_CIVA_ARTICULO_FACTURA_LINEA' +
        '`, :`TOTAL_FACTURA_LINEA`, :`TOTAL_FACTURASIVA_LINEA`, :`INSTANT' +
        'EMODIF`, :`INSTANTEALTA`, :`USUARIOALTA`, :`USUARIOMODIF`)')
    SQLDelete.Strings = (
      'DELETE FROM `fza_facturas_lineas`'
      'WHERE'
      
        '  `NRO_FACTURA_LINEA` = :`Old_NRO_FACTURA_LINEA` AND `SERIE_FACT' +
        'URA_LINEA` = :`Old_SERIE_FACTURA_LINEA` AND `LINEA_FACTURA_LINEA' +
        '` = :`Old_LINEA_FACTURA_LINEA`')
    SQLUpdate.Strings = (
      'UPDATE `fza_facturas_lineas`'
      'SET'
      
        '  `NRO_FACTURA_LINEA` = :`NRO_FACTURA_LINEA`, `SERIE_FACTURA_LIN' +
        'EA` = :`SERIE_FACTURA_LINEA`, `LINEA_FACTURA_LINEA` = :`LINEA_FA' +
        'CTURA_LINEA`, `CODIGO_ARTICULO_FACTURA_LINEA` = :`CODIGO_ARTICUL' +
        'O_FACTURA_LINEA`, `CODIGO_FAMILIA_FACTURA_LINEA` = :`CODIGO_FAMI' +
        'LIA_FACTURA_LINEA`, `NOMBRE_FAMILIA_FACTURA_LINEA` = :`NOMBRE_FA' +
        'MILIA_FACTURA_LINEA`, `PRECIO_ULT_COMPRA_FACTURA_LINEA` = :`PREC' +
        'IO_ULT_COMPRA_FACTURA_LINEA`, `CODIGO_PROVEEDOR_FACTURA_LINEA` =' +
        ' :`CODIGO_PROVEEDOR_FACTURA_LINEA`, `RAZONSOCIAL_PROVEEDOR_FACTU' +
        'RA_LINEA` = :`RAZONSOCIAL_PROVEEDOR_FACTURA_LINEA`, `ESPROVEEDOR' +
        'PRINCIPAL_FACTURA_LINEA` = :`ESPROVEEDORPRINCIPAL_FACTURA_LINEA`' +
        ', `FECHA_ENTREGA_FACTURA_LINEA` = :`FECHA_ENTREGA_FACTURA_LINEA`' +
        ', `TIPO_CANTIDAD_ARTICULO_FACTURA_LINEA` = :`TIPO_CANTIDAD_ARTIC' +
        'ULO_FACTURA_LINEA`, `ESIMP_INCL_TARIFA_FACTURA_LINEA` = :`ESIMP_' +
        'INCL_TARIFA_FACTURA_LINEA`, `TIPOIVA_ARTICULO_FACTURA_LINEA` = :' +
        '`TIPOIVA_ARTICULO_FACTURA_LINEA`, `DESCRIPCION_ARTICULO_FACTURA_' +
        'LINEA` = :`DESCRIPCION_ARTICULO_FACTURA_LINEA`, `CODIGO_TARIFA_F' +
        'ACTURA_LINEA` = :`CODIGO_TARIFA_FACTURA_LINEA`, `CANTIDAD_FACTUR' +
        'A_LINEA` = :`CANTIDAD_FACTURA_LINEA`, `PRECIOSALIDA_FACTURA_LINE' +
        'A` = :`PRECIOSALIDA_FACTURA_LINEA`, `PORCEN_DTO_FACTURA_LINEA` =' +
        ' :`PORCEN_DTO_FACTURA_LINEA`, `PRECIO_DTO_FACTURA_LINEA` = :`PRE' +
        'CIO_DTO_FACTURA_LINEA`, `PRECIOVENTA_SIVA_ARTICULO_FACTURA_LINEA' +
        '` = :`PRECIOVENTA_SIVA_ARTICULO_FACTURA_LINEA`, `PORCEN_IVA_FACT' +
        'URA_LINEA` = :`PORCEN_IVA_FACTURA_LINEA`, `PRECIOVENTA_CIVA_ARTI' +
        'CULO_FACTURA_LINEA` = :`PRECIOVENTA_CIVA_ARTICULO_FACTURA_LINEA`' +
        ', `TOTAL_FACTURA_LINEA` = :`TOTAL_FACTURA_LINEA`, `TOTAL_FACTURA' +
        'SIVA_LINEA` = :`TOTAL_FACTURASIVA_LINEA`, `INSTANTEMODIF` = :`IN' +
        'STANTEMODIF`, `INSTANTEALTA` = :`INSTANTEALTA`, `USUARIOALTA` = ' +
        ':`USUARIOALTA`, `USUARIOMODIF` = :`USUARIOMODIF`'
      'WHERE'
      
        '  `NRO_FACTURA_LINEA` = :`Old_NRO_FACTURA_LINEA` AND `SERIE_FACT' +
        'URA_LINEA` = :`Old_SERIE_FACTURA_LINEA` AND `LINEA_FACTURA_LINEA' +
        '` = :`Old_LINEA_FACTURA_LINEA`')
    SQLLock.Strings = (
      
        'SELECT `NRO_FACTURA_LINEA`, `SERIE_FACTURA_LINEA`, `LINEA_FACTUR' +
        'A_LINEA`, `CODIGO_ARTICULO_FACTURA_LINEA`, `CODIGO_FAMILIA_FACTU' +
        'RA_LINEA`, `NOMBRE_FAMILIA_FACTURA_LINEA`, `PRECIO_ULT_COMPRA_FA' +
        'CTURA_LINEA`, `CODIGO_PROVEEDOR_FACTURA_LINEA`, `RAZONSOCIAL_PRO' +
        'VEEDOR_FACTURA_LINEA`, `ESPROVEEDORPRINCIPAL_FACTURA_LINEA`, `FE' +
        'CHA_ENTREGA_FACTURA_LINEA`, `TIPO_CANTIDAD_ARTICULO_FACTURA_LINE' +
        'A`, `ESIMP_INCL_TARIFA_FACTURA_LINEA`, `TIPOIVA_ARTICULO_FACTURA' +
        '_LINEA`, `DESCRIPCION_ARTICULO_FACTURA_LINEA`, `CODIGO_TARIFA_FA' +
        'CTURA_LINEA`, `CANTIDAD_FACTURA_LINEA`, `PRECIOSALIDA_FACTURA_LI' +
        'NEA`, `PORCEN_DTO_FACTURA_LINEA`, `PRECIO_DTO_FACTURA_LINEA`, `P' +
        'RECIOVENTA_SIVA_ARTICULO_FACTURA_LINEA`, `PORCEN_IVA_FACTURA_LIN' +
        'EA`, `PRECIOVENTA_CIVA_ARTICULO_FACTURA_LINEA`, `TOTAL_FACTURA_L' +
        'INEA`, `TOTAL_FACTURASIVA_LINEA`, `INSTANTEMODIF`, `INSTANTEALTA' +
        '`, `USUARIOALTA`, `USUARIOMODIF` FROM `fza_facturas_lineas`'
      'WHERE'
      
        '  `NRO_FACTURA_LINEA` = :`Old_NRO_FACTURA_LINEA` AND `SERIE_FACT' +
        'URA_LINEA` = :`Old_SERIE_FACTURA_LINEA` AND `LINEA_FACTURA_LINEA' +
        '` = :`Old_LINEA_FACTURA_LINEA`'
      'FOR UPDATE')
    SQLRefresh.Strings = (
      
        'SELECT `NRO_FACTURA_LINEA`, `SERIE_FACTURA_LINEA`, `LINEA_FACTUR' +
        'A_LINEA`, `CODIGO_ARTICULO_FACTURA_LINEA`, `CODIGO_FAMILIA_FACTU' +
        'RA_LINEA`, `NOMBRE_FAMILIA_FACTURA_LINEA`, `PRECIO_ULT_COMPRA_FA' +
        'CTURA_LINEA`, `CODIGO_PROVEEDOR_FACTURA_LINEA`, `RAZONSOCIAL_PRO' +
        'VEEDOR_FACTURA_LINEA`, `ESPROVEEDORPRINCIPAL_FACTURA_LINEA`, `FE' +
        'CHA_ENTREGA_FACTURA_LINEA`, `TIPO_CANTIDAD_ARTICULO_FACTURA_LINE' +
        'A`, `ESIMP_INCL_TARIFA_FACTURA_LINEA`, `TIPOIVA_ARTICULO_FACTURA' +
        '_LINEA`, `DESCRIPCION_ARTICULO_FACTURA_LINEA`, `CODIGO_TARIFA_FA' +
        'CTURA_LINEA`, `CANTIDAD_FACTURA_LINEA`, `PRECIOSALIDA_FACTURA_LI' +
        'NEA`, `PORCEN_DTO_FACTURA_LINEA`, `PRECIO_DTO_FACTURA_LINEA`, `P' +
        'RECIOVENTA_SIVA_ARTICULO_FACTURA_LINEA`, `PORCEN_IVA_FACTURA_LIN' +
        'EA`, `PRECIOVENTA_CIVA_ARTICULO_FACTURA_LINEA`, `TOTAL_FACTURA_L' +
        'INEA`, `TOTAL_FACTURASIVA_LINEA`, `INSTANTEMODIF`, `INSTANTEALTA' +
        '`, `USUARIOALTA`, `USUARIOMODIF` FROM `fza_facturas_lineas`'
      'WHERE'
      
        '  `NRO_FACTURA_LINEA` = :`NRO_FACTURA_LINEA` AND `SERIE_FACTURA_' +
        'LINEA` = :`SERIE_FACTURA_LINEA` AND `LINEA_FACTURA_LINEA` = :`LI' +
        'NEA_FACTURA_LINEA`')
    SQLRecCount.Strings = (
      'SELECT COUNT(*) FROM fza_facturas_lineas')
    Connection = dmConn.conUni
    SQL.Strings = (
      'SELECT *'
      'FROM vi_FACTURAS_LINEAS'
      'where NRO_FACTURA_LINEA = :NRO_FACTURA'
      'AND SERIE_FACTURA_LINEA = :SERIE_FACTURA'
      
        'order by NRO_FACTURA_LINEA, SERIE_FACTURA_LINEA, LINEA_FACTURA_L' +
        'INEA ASC')
    MasterSource = dsFactura
    MasterFields = 'SERIE_FACTURA;NRO_FACTURA'
    DetailFields = 'SERIE_FACTURA_LINEA;NRO_FACTURA_LINEA'
    BeforeInsert = unqryLinFacBeforeInsert
    AfterInsert = unqryLinFacAfterInsert
    BeforeEdit = unqryLinFacBeforeEdit
    BeforePost = unqryLinFacBeforePost
    AfterPost = unqryLinFacAfterPost
    AfterDelete = unqryLinFacAfterDelete
    Left = 168
    Top = 136
    ParamData = <
      item
        DataType = ftWideString
        Name = 'NRO_FACTURA'
        ParamType = ptInput
        Value = nil
      end
      item
        DataType = ftWideString
        Name = 'SERIE_FACTURA'
        ParamType = ptInput
        Value = nil
      end>
  end
  object unstrdprcCrearFacturaAbono: TUniStoredProc
    StoredProcName = 'PRC_CREAR_FACTURA_ABONO'
    SQL.Strings = (
      
        'CALL PRC_CREAR_FACTURA_ABONO(:pidseriefactura, :pidnumfactura, :' +
        'pidseriefacturaabono, :pidcodigo_empresa, :pfechafacturaabono, @' +
        'pidnumfacturaabono, :pUSUARIO); SELECT @pidnumfacturaabono AS '#39'@' +
        'pidnumfacturaabono'#39)
    Connection = dmConn.conUni
    Left = 1197
    Top = 296
    ParamData = <
      item
        DataType = ftWideString
        Name = 'pidseriefactura'
        ParamType = ptInput
        Size = 200
        Value = nil
      end
      item
        DataType = ftWideString
        Name = 'pidnumfactura'
        ParamType = ptInput
        Size = 200
        Value = nil
      end
      item
        DataType = ftWideString
        Name = 'pidseriefacturaabono'
        ParamType = ptInput
        Size = 200
        Value = nil
      end
      item
        DataType = ftWideString
        Name = 'pidcodigo_empresa'
        ParamType = ptInput
        Size = 200
        Value = nil
      end
      item
        DataType = ftDate
        Name = 'pfechafacturaabono'
        ParamType = ptInput
        Value = nil
      end
      item
        DataType = ftWideString
        Name = 'pidnumfacturaabono'
        ParamType = ptOutput
        Size = 200
        Value = nil
      end
      item
        DataType = ftWideString
        Name = 'pUSUARIO'
        ParamType = ptInput
        Size = 100
        Value = nil
      end>
    CommandStoredProcName = 'PRC_CREAR_FACTURA_ABONO'
  end
  object unstrdprcDuplicarFactura: TUniStoredProc
    StoredProcName = 'PRC_CREAR_FACTURA_DUPLICADA'
    SQL.Strings = (
      
        'CALL PRC_CREAR_FACTURA_DUPLICADA(:pidseriefactura, :pidnumfactur' +
        'a, :pidseriefacturaabono, :pidcodigo_empresa, :pfechafacturaabon' +
        'o, :pUSUARIO, @pidnumfacturaabono); SELECT @pidnumfacturaabono A' +
        'S '#39'@pidnumfacturaabono'#39)
    Connection = dmConn.conUni
    Left = 1048
    Top = 296
    ParamData = <
      item
        DataType = ftWideString
        Name = 'pidseriefactura'
        ParamType = ptInput
        Size = 200
        Value = nil
      end
      item
        DataType = ftWideString
        Name = 'pidnumfactura'
        ParamType = ptInput
        Size = 200
        Value = nil
      end
      item
        DataType = ftWideString
        Name = 'pidseriefacturaabono'
        ParamType = ptInput
        Size = 200
        Value = nil
      end
      item
        DataType = ftWideString
        Name = 'pidcodigo_empresa'
        ParamType = ptInput
        Size = 200
        Value = nil
      end
      item
        DataType = ftDate
        Name = 'pfechafacturaabono'
        ParamType = ptInput
        Value = nil
      end
      item
        DataType = ftWideString
        Name = 'pUSUARIO'
        ParamType = ptInput
        Size = 100
        Value = nil
      end
      item
        DataType = ftWideString
        Name = 'pidnumfacturaabono'
        ParamType = ptOutput
        Size = 200
        Value = nil
      end>
    CommandStoredProcName = 'PRC_CREAR_FACTURA_DUPLICADA'
  end
  object unstrdprcCrearCliente: TUniStoredProc
    StoredProcName = 'PRC_CREAR_ACTUALIZAR_CLIENTE'
    SQL.Strings = (
      
        'CALL PRC_CREAR_ACTUALIZAR_CLIENTE(:pCODIGO_CLIENTE, :pRAZONSOCIA' +
        'L_CLIENTE, :pNIF_CLIENTE, :pMOVIL_CLIENTE, :pEMAIL_CLIENTE, :pDI' +
        'RECCION1_CLIENTE, :pDIRECCION2_CLIENTE, :pPOBLACION_CLIENTE, :pP' +
        'ROVINCIA_CLIENTE, :pCPOSTAL_CLIENTE, :pCOD_PAIS_CLIENTE, :pPAIS_' +
        'CLIENTE, :pESIVA_EXENTO_CLIENTE, :pESRETENCIONES_CLIENTE, :pESIV' +
        'A_RECARGO_CLIENTE, :pESINTRACOMUNITARIO_CLIENTE, :pESREGIMENESPE' +
        'CIALAGRICOLA_CLIENTE, :pTARIFA_ARTICULO_CLIENTE, :pUSUARIO)')
    Connection = dmConn.conUni
    Left = 296
    Top = 264
    ParamData = <
      item
        DataType = ftWideString
        Name = 'pCODIGO_CLIENTE'
        ParamType = ptInput
        Size = 20
        Value = ''
      end
      item
        DataType = ftWideString
        Name = 'pRAZONSOCIAL_CLIENTE'
        ParamType = ptInput
        Size = 200
        Value = ''
      end
      item
        DataType = ftWideString
        Name = 'pNIF_CLIENTE'
        ParamType = ptInput
        Size = 50
        Value = nil
      end
      item
        DataType = ftWideString
        Name = 'pMOVIL_CLIENTE'
        ParamType = ptInput
        Size = 40
        Value = nil
      end
      item
        DataType = ftWideString
        Name = 'pEMAIL_CLIENTE'
        ParamType = ptInput
        Size = 200
        Value = nil
      end
      item
        DataType = ftWideString
        Name = 'pDIRECCION1_CLIENTE'
        ParamType = ptInput
        Size = 200
        Value = nil
      end
      item
        DataType = ftWideString
        Name = 'pDIRECCION2_CLIENTE'
        ParamType = ptInput
        Size = 200
        Value = nil
      end
      item
        DataType = ftWideString
        Name = 'pPOBLACION_CLIENTE'
        ParamType = ptInput
        Size = 200
        Value = nil
      end
      item
        DataType = ftWideString
        Name = 'pPROVINCIA_CLIENTE'
        ParamType = ptInput
        Size = 200
        Value = nil
      end
      item
        DataType = ftWideString
        Name = 'pCPOSTAL_CLIENTE'
        ParamType = ptInput
        Size = 15
        Value = nil
      end
      item
        DataType = ftWideString
        Name = 'pCOD_PAIS_CLIENTE'
        ParamType = ptInput
        Size = 3
        Value = nil
      end
      item
        DataType = ftWideString
        Name = 'pPAIS_CLIENTE'
        ParamType = ptInput
        Size = 150
        Value = nil
      end
      item
        DataType = ftWideString
        Name = 'pESIVA_EXENTO_CLIENTE'
        ParamType = ptInput
        Size = 1
        Value = nil
      end
      item
        DataType = ftWideString
        Name = 'pESRETENCIONES_CLIENTE'
        ParamType = ptInput
        Size = 1
        Value = nil
      end
      item
        DataType = ftWideString
        Name = 'pESIVA_RECARGO_CLIENTE'
        ParamType = ptInput
        Size = 1
        Value = nil
      end
      item
        DataType = ftWideString
        Name = 'pESINTRACOMUNITARIO_CLIENTE'
        ParamType = ptInput
        Size = 1
        Value = nil
      end
      item
        DataType = ftWideString
        Name = 'pESREGIMENESPECIALAGRICOLA_CLIENTE'
        ParamType = ptInput
        Size = 1
        Value = nil
      end
      item
        DataType = ftWideString
        Name = 'pTARIFA_ARTICULO_CLIENTE'
        ParamType = ptInput
        Size = 20
        Value = nil
      end
      item
        DataType = ftWideString
        Name = 'pUSUARIO'
        ParamType = ptInput
        Size = 100
        Value = ''
      end>
    CommandStoredProcName = 'PRC_CREAR_ACTUALIZAR_CLIENTE'
  end
  object unstrdprcGetDataArticulo: TUniStoredProc
    StoredProcName = 'PRC_GET_DATA_ARTICULO'
    SQL.Strings = (
      
        'CALL PRC_GET_DATA_ARTICULO(:pidcodarticulo, @pidnomarticulo, @pt' +
        'ipoiva); SELECT @pidnomarticulo AS '#39'@pidnomarticulo'#39', @ptipoiva ' +
        'AS '#39'@ptipoiva'#39)
    Connection = dmConn.conUni
    Left = 528
    Top = 272
    ParamData = <
      item
        DataType = ftWideString
        Name = 'pidcodarticulo'
        ParamType = ptInput
        Size = 200
        Value = nil
      end
      item
        DataType = ftWideString
        Name = 'pidnomarticulo'
        ParamType = ptOutput
        Size = 1000
        Value = nil
      end
      item
        DataType = ftWideString
        Name = 'ptipoiva'
        ParamType = ptOutput
        Size = 2
        Value = nil
      end>
    CommandStoredProcName = 'PRC_GET_DATA_ARTICULO'
  end
  object unstrdprcGetDataCliente: TUniStoredProc
    StoredProcName = 'PRC_GET_DATA_CLIENTE'
    SQL.Strings = (
      
        'CALL PRC_GET_DATA_CLIENTE(:pCODIGO_CLIENTE, @pRAZONSOCIAL_CLIENT' +
        'E, @pNIF_CLIENTE, @pCODIGO_ZONA_IVA_CLIENTE, @pMOVIL_CLIENTE, @p' +
        'ESIVA_RECARGO_CLIENTE, @pESRETENCIONES_CLIENTE, @pESIVA_EXENTO_C' +
        'LIENTE, @pESINTRACOMUNITARIO_CLIENTE, @pESREGIMENESPECIALAGRICOL' +
        'A_CLIENTE, @pEMAIL_CLIENTE, @pDIRECCION1_CLIENTE, @pDIRECCION2_C' +
        'LIENTE, @pPOBLACION_CLIENTE, @pPROVINCIA_CLIENTE, @pCPOSTAL_CLIE' +
        'NTE, @pTARIFA_ARTICULO_CLIENTE, @pTEXTO_LEGAL_FACTURA_CLIENTE, @' +
        'pPAIS_CLIENTE, @pCOD_PAIS_CLIENTE); SELECT @pRAZONSOCIAL_CLIENTE' +
        ' AS '#39'@pRAZONSOCIAL_CLIENTE'#39', @pNIF_CLIENTE AS '#39'@pNIF_CLIENTE'#39', C' +
        'AST(@pCODIGO_ZONA_IVA_CLIENTE AS SIGNED) AS '#39'@pCODIGO_ZONA_IVA_C' +
        'LIENTE'#39', @pMOVIL_CLIENTE AS '#39'@pMOVIL_CLIENTE'#39', @pESIVA_RECARGO_C' +
        'LIENTE AS '#39'@pESIVA_RECARGO_CLIENTE'#39', @pESRETENCIONES_CLIENTE AS ' +
        #39'@pESRETENCIONES_CLIENTE'#39', @pESIVA_EXENTO_CLIENTE AS '#39'@pESIVA_EX' +
        'ENTO_CLIENTE'#39', @pESINTRACOMUNITARIO_CLIENTE AS '#39'@pESINTRACOMUNIT' +
        'ARIO_CLIENTE'#39', @pESREGIMENESPECIALAGRICOLA_CLIENTE AS '#39'@pESREGIM' +
        'ENESPECIALAGRICOLA_CLIENTE'#39', @pEMAIL_CLIENTE AS '#39'@pEMAIL_CLIENTE' +
        #39', @pDIRECCION1_CLIENTE AS '#39'@pDIRECCION1_CLIENTE'#39', @pDIRECCION2_' +
        'CLIENTE AS '#39'@pDIRECCION2_CLIENTE'#39', @pPOBLACION_CLIENTE AS '#39'@pPOB' +
        'LACION_CLIENTE'#39', @pPROVINCIA_CLIENTE AS '#39'@pPROVINCIA_CLIENTE'#39', @' +
        'pCPOSTAL_CLIENTE AS '#39'@pCPOSTAL_CLIENTE'#39', @pTARIFA_ARTICULO_CLIEN' +
        'TE AS '#39'@pTARIFA_ARTICULO_CLIENTE'#39', @pTEXTO_LEGAL_FACTURA_CLIENTE' +
        ' AS '#39'@pTEXTO_LEGAL_FACTURA_CLIENTE'#39', @pPAIS_CLIENTE AS '#39'@pPAIS_C' +
        'LIENTE'#39', @pCOD_PAIS_CLIENTE AS '#39'@pCOD_PAIS_CLIENTE'#39)
    Connection = dmConn.conUni
    Left = 656
    Top = 296
    ParamData = <
      item
        DataType = ftWideString
        Name = 'pCODIGO_CLIENTE'
        ParamType = ptInput
        Size = 10
        Value = nil
      end
      item
        DataType = ftWideString
        Name = 'pRAZONSOCIAL_CLIENTE'
        ParamType = ptOutput
        Size = 200
        Value = nil
      end
      item
        DataType = ftWideString
        Name = 'pNIF_CLIENTE'
        ParamType = ptOutput
        Size = 50
        Value = nil
      end
      item
        DataType = ftInteger
        Name = 'pCODIGO_ZONA_IVA_CLIENTE'
        ParamType = ptOutput
        Value = nil
      end
      item
        DataType = ftWideString
        Name = 'pMOVIL_CLIENTE'
        ParamType = ptOutput
        Size = 40
        Value = nil
      end
      item
        DataType = ftWideString
        Name = 'pESIVA_RECARGO_CLIENTE'
        ParamType = ptOutput
        Size = 1
        Value = nil
      end
      item
        DataType = ftWideString
        Name = 'pESRETENCIONES_CLIENTE'
        ParamType = ptOutput
        Size = 1
        Value = nil
      end
      item
        DataType = ftWideString
        Name = 'pESIVA_EXENTO_CLIENTE'
        ParamType = ptOutput
        Size = 1
        Value = nil
      end
      item
        DataType = ftWideString
        Name = 'pESINTRACOMUNITARIO_CLIENTE'
        ParamType = ptOutput
        Size = 1
        Value = nil
      end
      item
        DataType = ftWideString
        Name = 'pESREGIMENESPECIALAGRICOLA_CLIENTE'
        ParamType = ptOutput
        Size = 1
        Value = nil
      end
      item
        DataType = ftWideString
        Name = 'pEMAIL_CLIENTE'
        ParamType = ptOutput
        Size = 200
        Value = nil
      end
      item
        DataType = ftWideString
        Name = 'pDIRECCION1_CLIENTE'
        ParamType = ptOutput
        Size = 200
        Value = nil
      end
      item
        DataType = ftWideString
        Name = 'pDIRECCION2_CLIENTE'
        ParamType = ptOutput
        Size = 200
        Value = nil
      end
      item
        DataType = ftWideString
        Name = 'pPOBLACION_CLIENTE'
        ParamType = ptOutput
        Size = 200
        Value = nil
      end
      item
        DataType = ftWideString
        Name = 'pPROVINCIA_CLIENTE'
        ParamType = ptOutput
        Size = 200
        Value = nil
      end
      item
        DataType = ftWideString
        Name = 'pCPOSTAL_CLIENTE'
        ParamType = ptOutput
        Size = 15
        Value = nil
      end
      item
        DataType = ftWideString
        Name = 'pTARIFA_ARTICULO_CLIENTE'
        ParamType = ptOutput
        Size = 10
        Value = nil
      end
      item
        DataType = ftWideString
        Name = 'pTEXTO_LEGAL_FACTURA_CLIENTE'
        ParamType = ptOutput
        Size = 1000
        Value = nil
      end
      item
        DataType = ftWideString
        Name = 'pPAIS_CLIENTE'
        ParamType = ptOutput
        Size = 150
        Value = nil
      end
      item
        DataType = ftWideString
        Name = 'pCOD_PAIS_CLIENTE'
        ParamType = ptOutput
        Size = 150
        Value = nil
      end>
    CommandStoredProcName = 'PRC_GET_DATA_CLIENTE'
  end
  object dsFormasPago: TDataSource
    DataSet = unqryFormaPago
    Left = 456
    Top = 80
  end
  object unqryFormaPago: TUniQuery
    SQLInsert.Strings = (
      'INSERT INTO fza_formapago'
      
        '  (CODIGO_FORMAPAGO, ACTIVO_FORMAPAGO, ORDEN_FORMAPAGO, DESCRIPC' +
        'ION_FORMAPAGO, N_PLAZOS_FORMAPAGO, N_DIAS_ENTRE_PLAZOS_FORMAPAGO' +
        ', PORCEN_ANTICIPO_FORMAPAGO, ESDEFAULT_FORMAPAGO, INSTANTEMODIF,' +
        ' INSTANTEALTA, USUARIOALTA, USUARIOMODIF)'
      'VALUES'
      
        '  (:CODIGO_FORMAPAGO, :ACTIVO_FORMAPAGO, :ORDEN_FORMAPAGO, :DESC' +
        'RIPCION_FORMAPAGO, :N_PLAZOS_FORMAPAGO, :N_DIAS_ENTRE_PLAZOS_FOR' +
        'MAPAGO, :PORCEN_ANTICIPO_FORMAPAGO, :ESDEFAULT_FORMAPAGO, :INSTA' +
        'NTEMODIF, :INSTANTEALTA, :USUARIOALTA, :USUARIOMODIF)')
    SQLDelete.Strings = (
      'DELETE FROM fza_formapago'
      'WHERE'
      '  CODIGO_FORMAPAGO = :Old_CODIGO_FORMAPAGO')
    SQLUpdate.Strings = (
      'UPDATE fza_formapago'
      'SET'
      
        '  CODIGO_FORMAPAGO = :CODIGO_FORMAPAGO, ACTIVO_FORMAPAGO = :ACTI' +
        'VO_FORMAPAGO, ORDEN_FORMAPAGO = :ORDEN_FORMAPAGO, DESCRIPCION_FO' +
        'RMAPAGO = :DESCRIPCION_FORMAPAGO, N_PLAZOS_FORMAPAGO = :N_PLAZOS' +
        '_FORMAPAGO, N_DIAS_ENTRE_PLAZOS_FORMAPAGO = :N_DIAS_ENTRE_PLAZOS' +
        '_FORMAPAGO, PORCEN_ANTICIPO_FORMAPAGO = :PORCEN_ANTICIPO_FORMAPA' +
        'GO, ESDEFAULT_FORMAPAGO = :ESDEFAULT_FORMAPAGO, INSTANTEMODIF = ' +
        ':INSTANTEMODIF, INSTANTEALTA = :INSTANTEALTA, USUARIOALTA = :USU' +
        'ARIOALTA, USUARIOMODIF = :USUARIOMODIF'
      'WHERE'
      '  CODIGO_FORMAPAGO = :Old_CODIGO_FORMAPAGO')
    SQLLock.Strings = (
      'SELECT * FROM fza_formapago'
      'WHERE'
      '  CODIGO_FORMAPAGO = :Old_CODIGO_FORMAPAGO'
      'FOR UPDATE')
    SQLRefresh.Strings = (
      
        'SELECT CODIGO_FORMAPAGO, ACTIVO_FORMAPAGO, ORDEN_FORMAPAGO, DESC' +
        'RIPCION_FORMAPAGO, N_PLAZOS_FORMAPAGO, N_DIAS_ENTRE_PLAZOS_FORMA' +
        'PAGO, PORCEN_ANTICIPO_FORMAPAGO, ESDEFAULT_FORMAPAGO, INSTANTEMO' +
        'DIF, INSTANTEALTA, USUARIOALTA, USUARIOMODIF FROM fza_formapago'
      'WHERE'
      '  CODIGO_FORMAPAGO = :CODIGO_FORMAPAGO')
    SQLRecCount.Strings = (
      'SELECT COUNT(*) FROM fza_formapago')
    Connection = dmConn.conUni
    SQL.Strings = (
      'select * from vi_formapago'
      '')
    ReadOnly = True
    Left = 464
    Top = 176
  end
  object dsRecibos: TDataSource
    DataSet = unqryRecibos
    Left = 736
    Top = 80
  end
  object unqryRecibos: TUniQuery
    SQLInsert.Strings = (
      'INSERT INTO `fza_recibos`'
      
        '  (`NRO_FACTURA_RECIBO`, `SERIE_FACTURA_RECIBO`, `NRO_PLAZO_RECI' +
        'BO`, `FORMA_PAGO_ORIGEN_RECIBO`, `FORMA_PAGO_DESCRIPCION_ORIGEN_' +
        'RECIBO`, `EUROS_RECIBO`, `STADO_RECIBO`, `FECHA_EXPEDICION_RECIB' +
        'O`, `FECHA_VENCIMIENTO_RECIBO`, `IBAN_CLIENTE_RECIBO`, `FECHA_PA' +
        'GO_RECIBO`, `LOCALIDAD_EXPEDICION_RECIBO`, `CODIGO_CLIENTE_RECIB' +
        'O`, `RAZONSOCIAL_CLIENTE_RECIBO`, `DIRECCION1_CLIENTE_RECIBO`, `' +
        'POBLACION_CLIENTE_RECIBO`, `PROVINCIA_CLIENTE_RECIBO`, `CPOSTAL_' +
        'CLIENTE_RECIBO`, `IMPORTE_LETRA_RECIBO`, `INSTANTEMODIF`, `INSTA' +
        'NTEALTA`, `USUARIOALTA`, `USUARIOMODIF`)'
      'VALUES'
      
        '  (:`NRO_FACTURA_RECIBO`, :`SERIE_FACTURA_RECIBO`, :`NRO_PLAZO_R' +
        'ECIBO`, :`FORMA_PAGO_ORIGEN_RECIBO`, :`FORMA_PAGO_DESCRIPCION_OR' +
        'IGEN_RECIBO`, :`EUROS_RECIBO`, :`STADO_RECIBO`, :`FECHA_EXPEDICI' +
        'ON_RECIBO`, :`FECHA_VENCIMIENTO_RECIBO`, :`IBAN_CLIENTE_RECIBO`,' +
        ' :`FECHA_PAGO_RECIBO`, :`LOCALIDAD_EXPEDICION_RECIBO`, :`CODIGO_' +
        'CLIENTE_RECIBO`, :`RAZONSOCIAL_CLIENTE_RECIBO`, :`DIRECCION1_CLI' +
        'ENTE_RECIBO`, :`POBLACION_CLIENTE_RECIBO`, :`PROVINCIA_CLIENTE_R' +
        'ECIBO`, :`CPOSTAL_CLIENTE_RECIBO`, :`IMPORTE_LETRA_RECIBO`, :`IN' +
        'STANTEMODIF`, :`INSTANTEALTA`, :`USUARIOALTA`, :`USUARIOMODIF`)')
    SQLDelete.Strings = (
      'DELETE FROM `fza_recibos`'
      'WHERE'
      
        '  `NRO_FACTURA_RECIBO` = :`Old_NRO_FACTURA_RECIBO` AND `SERIE_FA' +
        'CTURA_RECIBO` = :`Old_SERIE_FACTURA_RECIBO` AND `NRO_PLAZO_RECIB' +
        'O` = :`Old_NRO_PLAZO_RECIBO`')
    SQLUpdate.Strings = (
      'UPDATE `fza_recibos`'
      'SET'
      
        '  `NRO_FACTURA_RECIBO` = :`NRO_FACTURA_RECIBO`, `SERIE_FACTURA_R' +
        'ECIBO` = :`SERIE_FACTURA_RECIBO`, `NRO_PLAZO_RECIBO` = :`NRO_PLA' +
        'ZO_RECIBO`, `FORMA_PAGO_ORIGEN_RECIBO` = :`FORMA_PAGO_ORIGEN_REC' +
        'IBO`, `FORMA_PAGO_DESCRIPCION_ORIGEN_RECIBO` = :`FORMA_PAGO_DESC' +
        'RIPCION_ORIGEN_RECIBO`, `EUROS_RECIBO` = :`EUROS_RECIBO`, `STADO' +
        '_RECIBO` = :`STADO_RECIBO`, `FECHA_EXPEDICION_RECIBO` = :`FECHA_' +
        'EXPEDICION_RECIBO`, `FECHA_VENCIMIENTO_RECIBO` = :`FECHA_VENCIMI' +
        'ENTO_RECIBO`, `IBAN_CLIENTE_RECIBO` = :`IBAN_CLIENTE_RECIBO`, `F' +
        'ECHA_PAGO_RECIBO` = :`FECHA_PAGO_RECIBO`, `LOCALIDAD_EXPEDICION_' +
        'RECIBO` = :`LOCALIDAD_EXPEDICION_RECIBO`, `CODIGO_CLIENTE_RECIBO' +
        '` = :`CODIGO_CLIENTE_RECIBO`, `RAZONSOCIAL_CLIENTE_RECIBO` = :`R' +
        'AZONSOCIAL_CLIENTE_RECIBO`, `DIRECCION1_CLIENTE_RECIBO` = :`DIRE' +
        'CCION1_CLIENTE_RECIBO`, `POBLACION_CLIENTE_RECIBO` = :`POBLACION' +
        '_CLIENTE_RECIBO`, `PROVINCIA_CLIENTE_RECIBO` = :`PROVINCIA_CLIEN' +
        'TE_RECIBO`, `CPOSTAL_CLIENTE_RECIBO` = :`CPOSTAL_CLIENTE_RECIBO`' +
        ', `IMPORTE_LETRA_RECIBO` = :`IMPORTE_LETRA_RECIBO`, `INSTANTEMOD' +
        'IF` = :`INSTANTEMODIF`, `INSTANTEALTA` = :`INSTANTEALTA`, `USUAR' +
        'IOALTA` = :`USUARIOALTA`, `USUARIOMODIF` = :`USUARIOMODIF`'
      'WHERE'
      
        '  `NRO_FACTURA_RECIBO` = :`Old_NRO_FACTURA_RECIBO` AND `SERIE_FA' +
        'CTURA_RECIBO` = :`Old_SERIE_FACTURA_RECIBO` AND `NRO_PLAZO_RECIB' +
        'O` = :`Old_NRO_PLAZO_RECIBO`')
    SQLLock.Strings = (
      'SELECT * FROM fza_recibos'
      'WHERE'
      
        '  `NRO_FACTURA_RECIBO` = :`Old_NRO_FACTURA_RECIBO` AND `SERIE_FA' +
        'CTURA_RECIBO` = :`Old_SERIE_FACTURA_RECIBO` AND `NRO_PLAZO_RECIB' +
        'O` = :`Old_NRO_PLAZO_RECIBO`'
      'FOR UPDATE')
    SQLRefresh.Strings = (
      
        'SELECT `NRO_FACTURA_RECIBO`, `SERIE_FACTURA_RECIBO`, `NRO_PLAZO_' +
        'RECIBO`, `FORMA_PAGO_ORIGEN_RECIBO`, `FORMA_PAGO_DESCRIPCION_ORI' +
        'GEN_RECIBO`, `EUROS_RECIBO`, `STADO_RECIBO`, `FECHA_EXPEDICION_R' +
        'ECIBO`, `FECHA_VENCIMIENTO_RECIBO`, `IBAN_CLIENTE_RECIBO`, `FECH' +
        'A_PAGO_RECIBO`, `LOCALIDAD_EXPEDICION_RECIBO`, `CODIGO_CLIENTE_R' +
        'ECIBO`, `RAZONSOCIAL_CLIENTE_RECIBO`, `DIRECCION1_CLIENTE_RECIBO' +
        '`, `POBLACION_CLIENTE_RECIBO`, `PROVINCIA_CLIENTE_RECIBO`, `CPOS' +
        'TAL_CLIENTE_RECIBO`, `IMPORTE_LETRA_RECIBO`, `INSTANTEMODIF`, `I' +
        'NSTANTEALTA`, `USUARIOALTA`, `USUARIOMODIF` FROM `fza_recibos`'
      'WHERE'
      
        '  `NRO_FACTURA_RECIBO` = :`NRO_FACTURA_RECIBO` AND `SERIE_FACTUR' +
        'A_RECIBO` = :`SERIE_FACTURA_RECIBO` AND `NRO_PLAZO_RECIBO` = :`N' +
        'RO_PLAZO_RECIBO`')
    SQLRecCount.Strings = (
      'SELECT COUNT(*) FROM fza_recibos')
    Connection = dmConn.conUni
    SQL.Strings = (
      'select * from vi_recibos'
      '')
    MasterSource = dsFactura
    MasterFields = 'NRO_FACTURA;SERIE_FACTURA'
    DetailFields = 'NRO_FACTURA_RECIBO;SERIE_FACTURA_RECIBO'
    Left = 736
    Top = 176
    ParamData = <
      item
        DataType = ftWideString
        Name = 'NRO_FACTURA'
        ParamType = ptInput
        Value = '00000021'
      end
      item
        DataType = ftWideString
        Name = 'SERIE_FACTURA'
        ParamType = ptInput
        Value = 'A1'
      end>
  end
  object dsRecibosPrint: TDataSource
    DataSet = unqryRecibosPrint
    Left = 776
    Top = 496
  end
  object fxdsRecibos: TfrxDBDataset
    Description = 'Recibos'
    UserName = 'Recibos'
    CloseDataSource = False
    FieldAliases.Strings = (
      'NRO_FACTURA_RECIBO=NRO_FACTURA_RECIBO'
      'SERIE_FACTURA_RECIBO=SERIE_FACTURA_RECIBO'
      'NRO_PLAZO_RECIBO=NRO_PLAZO_RECIBO'
      'FORMA_PAGO_ORIGEN_RECIBO=FORMA_PAGO_ORIGEN_RECIBO'
      
        'FORMA_PAGO_DESCRIPCION_ORIGEN_RECIBO=FORMA_PAGO_DESCRIPCION_ORIG' +
        'EN_RECIBO'
      'EUROS_RECIBO=EUROS_RECIBO'
      'ESTADO_RECIBO=ESTADO_RECIBO'
      'FECHA_EXPEDICION_RECIBO=FECHA_EXPEDICION_RECIBO'
      'FECHA_VENCIMIENTO_RECIBO=FECHA_VENCIMIENTO_RECIBO'
      'IBAN_CLIENTE_RECIBO=IBAN_CLIENTE_RECIBO'
      'FECHA_PAGO_RECIBO=FECHA_PAGO_RECIBO'
      'LOCALIDAD_EXPEDICION_RECIBO=LOCALIDAD_EXPEDICION_RECIBO'
      'CODIGO_CLIENTE_RECIBO=CODIGO_CLIENTE_RECIBO'
      'RAZONSOCIAL_CLIENTE_RECIBO=RAZONSOCIAL_CLIENTE_RECIBO'
      'DIRECCION1_CLIENTE_RECIBO=DIRECCION1_CLIENTE_RECIBO'
      'POBLACION_CLIENTE_RECIBO=POBLACION_CLIENTE_RECIBO'
      'PROVINCIA_CLIENTE_RECIBO=PROVINCIA_CLIENTE_RECIBO'
      'CPOSTAL_CLIENTE_RECIBO=CPOSTAL_CLIENTE_RECIBO'
      'IMPORTE_LETRA_RECIBO=IMPORTE_LETRA_RECIBO'
      'INSTANTEMODIF=INSTANTEMODIF'
      'INSTANTEALTA=INSTANTEALTA'
      'USUARIOALTA=USUARIOALTA'
      'USUARIOMODIF=USUARIOMODIF')
    DataSource = dsRecibosPrint
    BCDToCurrency = False
    DataSetOptions = []
    Left = 776
    Top = 432
  end
  object unqryRecibosPrint: TUniQuery
    SQLInsert.Strings = (
      'INSERT INTO fza_recibos'
      
        '  (NRO_FACTURA_RECIBO, SERIE_FACTURA_RECIBO, NRO_PLAZO_RECIBO, F' +
        'ORMA_PAGO_ORIGEN_RECIBO, FORMA_PAGO_DESCRIPCION_ORIGEN_RECIBO, E' +
        'UROS_RECIBO, ESTADO_RECIBO, FECHA_EXPEDICION_RECIBO, FECHA_VENCI' +
        'MIENTO_RECIBO, IBAN_CLIENTE_RECIBO, FECHA_PAGO_RECIBO, LOCALIDAD' +
        '_EXPEDICION_RECIBO, CODIGO_CLIENTE_RECIBO, RAZONSOCIAL_CLIENTE_R' +
        'ECIBO, DIRECCION1_CLIENTE_RECIBO, POBLACION_CLIENTE_RECIBO, PROV' +
        'INCIA_CLIENTE_RECIBO, CPOSTAL_CLIENTE_RECIBO, IMPORTE_LETRA_RECI' +
        'BO, INSTANTEMODIF, INSTANTEALTA, USUARIOALTA, USUARIOMODIF)'
      'VALUES'
      
        '  (:NRO_FACTURA_RECIBO, :SERIE_FACTURA_RECIBO, :NRO_PLAZO_RECIBO' +
        ', :FORMA_PAGO_ORIGEN_RECIBO, :FORMA_PAGO_DESCRIPCION_ORIGEN_RECI' +
        'BO, :EUROS_RECIBO, :ESTADO_RECIBO, :FECHA_EXPEDICION_RECIBO, :FE' +
        'CHA_VENCIMIENTO_RECIBO, :IBAN_CLIENTE_RECIBO, :FECHA_PAGO_RECIBO' +
        ', :LOCALIDAD_EXPEDICION_RECIBO, :CODIGO_CLIENTE_RECIBO, :RAZONSO' +
        'CIAL_CLIENTE_RECIBO, :DIRECCION1_CLIENTE_RECIBO, :POBLACION_CLIE' +
        'NTE_RECIBO, :PROVINCIA_CLIENTE_RECIBO, :CPOSTAL_CLIENTE_RECIBO, ' +
        ':IMPORTE_LETRA_RECIBO, :INSTANTEMODIF, :INSTANTEALTA, :USUARIOAL' +
        'TA, :USUARIOMODIF)')
    SQLDelete.Strings = (
      'DELETE FROM fza_recibos'
      'WHERE'
      
        '  NRO_FACTURA_RECIBO = :Old_NRO_FACTURA_RECIBO AND SERIE_FACTURA' +
        '_RECIBO = :Old_SERIE_FACTURA_RECIBO AND NRO_PLAZO_RECIBO = :Old_' +
        'NRO_PLAZO_RECIBO')
    SQLUpdate.Strings = (
      'UPDATE fza_recibos'
      'SET'
      
        '  NRO_FACTURA_RECIBO = :NRO_FACTURA_RECIBO, SERIE_FACTURA_RECIBO' +
        ' = :SERIE_FACTURA_RECIBO, NRO_PLAZO_RECIBO = :NRO_PLAZO_RECIBO, ' +
        'FORMA_PAGO_ORIGEN_RECIBO = :FORMA_PAGO_ORIGEN_RECIBO, FORMA_PAGO' +
        '_DESCRIPCION_ORIGEN_RECIBO = :FORMA_PAGO_DESCRIPCION_ORIGEN_RECI' +
        'BO, EUROS_RECIBO = :EUROS_RECIBO, ESTADO_RECIBO = :ESTADO_RECIBO' +
        ', FECHA_EXPEDICION_RECIBO = :FECHA_EXPEDICION_RECIBO, FECHA_VENC' +
        'IMIENTO_RECIBO = :FECHA_VENCIMIENTO_RECIBO, IBAN_CLIENTE_RECIBO ' +
        '= :IBAN_CLIENTE_RECIBO, FECHA_PAGO_RECIBO = :FECHA_PAGO_RECIBO, ' +
        'LOCALIDAD_EXPEDICION_RECIBO = :LOCALIDAD_EXPEDICION_RECIBO, CODI' +
        'GO_CLIENTE_RECIBO = :CODIGO_CLIENTE_RECIBO, RAZONSOCIAL_CLIENTE_' +
        'RECIBO = :RAZONSOCIAL_CLIENTE_RECIBO, DIRECCION1_CLIENTE_RECIBO ' +
        '= :DIRECCION1_CLIENTE_RECIBO, POBLACION_CLIENTE_RECIBO = :POBLAC' +
        'ION_CLIENTE_RECIBO, PROVINCIA_CLIENTE_RECIBO = :PROVINCIA_CLIENT' +
        'E_RECIBO, CPOSTAL_CLIENTE_RECIBO = :CPOSTAL_CLIENTE_RECIBO, IMPO' +
        'RTE_LETRA_RECIBO = :IMPORTE_LETRA_RECIBO, INSTANTEMODIF = :INSTA' +
        'NTEMODIF, INSTANTEALTA = :INSTANTEALTA, USUARIOALTA = :USUARIOAL' +
        'TA, USUARIOMODIF = :USUARIOMODIF'
      'WHERE'
      
        '  NRO_FACTURA_RECIBO = :Old_NRO_FACTURA_RECIBO AND SERIE_FACTURA' +
        '_RECIBO = :Old_SERIE_FACTURA_RECIBO AND NRO_PLAZO_RECIBO = :Old_' +
        'NRO_PLAZO_RECIBO')
    SQLLock.Strings = (
      'SELECT * FROM fza_recibos'
      'WHERE'
      
        '  NRO_FACTURA_RECIBO = :Old_NRO_FACTURA_RECIBO AND SERIE_FACTURA' +
        '_RECIBO = :Old_SERIE_FACTURA_RECIBO AND NRO_PLAZO_RECIBO = :Old_' +
        'NRO_PLAZO_RECIBO'
      'FOR UPDATE')
    SQLRefresh.Strings = (
      
        'SELECT NRO_FACTURA_RECIBO, SERIE_FACTURA_RECIBO, NRO_PLAZO_RECIB' +
        'O, FORMA_PAGO_ORIGEN_RECIBO, FORMA_PAGO_DESCRIPCION_ORIGEN_RECIB' +
        'O, EUROS_RECIBO, ESTADO_RECIBO, FECHA_EXPEDICION_RECIBO, FECHA_V' +
        'ENCIMIENTO_RECIBO, IBAN_CLIENTE_RECIBO, FECHA_PAGO_RECIBO, LOCAL' +
        'IDAD_EXPEDICION_RECIBO, CODIGO_CLIENTE_RECIBO, RAZONSOCIAL_CLIEN' +
        'TE_RECIBO, DIRECCION1_CLIENTE_RECIBO, POBLACION_CLIENTE_RECIBO, ' +
        'PROVINCIA_CLIENTE_RECIBO, CPOSTAL_CLIENTE_RECIBO, IMPORTE_LETRA_' +
        'RECIBO, INSTANTEMODIF, INSTANTEALTA, USUARIOALTA, USUARIOMODIF F' +
        'ROM fza_recibos'
      'WHERE'
      
        '  NRO_FACTURA_RECIBO = :NRO_FACTURA_RECIBO AND SERIE_FACTURA_REC' +
        'IBO = :SERIE_FACTURA_RECIBO AND NRO_PLAZO_RECIBO = :NRO_PLAZO_RE' +
        'CIBO')
    SQLRecCount.Strings = (
      'SELECT COUNT(*) FROM fza_recibos')
    Connection = dmConn.conUni
    SQL.Strings = (
      'SELECT * '
      'from vi_recibos'
      '')
    DMLRefresh = True
    Left = 776
    Top = 552
  end
  object unstrdprcGetRecibos: TUniStoredProc
    StoredProcName = 'PRC_CREAR_RECIBOS_FACTURA'
    SQL.Strings = (
      
        'CALL PRC_CREAR_RECIBOS_FACTURA(:pSERIE_FACTURA, :pNRO_FACTURA, :' +
        'pUSUARIO)')
    Connection = dmConn.conUni
    Left = 1280
    Top = 296
    ParamData = <
      item
        DataType = ftWideString
        Name = 'pSERIE_FACTURA'
        ParamType = ptInput
        Size = 12
        Value = nil
      end
      item
        DataType = ftWideString
        Name = 'pNRO_FACTURA'
        ParamType = ptInput
        Size = 12
        Value = nil
      end
      item
        DataType = ftWideString
        Name = 'pUSUARIO'
        ParamType = ptInput
        Size = 100
        Value = nil
      end>
    CommandStoredProcName = 'PRC_CREAR_RECIBOS_FACTURA'
  end
  object unqryIvas: TUniQuery
    Connection = dmConn.conUni
    SQL.Strings = (
      'SELECT * '
      'FROM VI_IVAS'
      '')
    Left = 671
    Top = 144
  end
  object dsIvas: TDataSource
    DataSet = unqryIvas
    Left = 672
    Top = 56
  end
  object unqryEmpDataFac: TUniQuery
    SQLInsert.Strings = (
      'INSERT INTO fza_clientes'
      
        '  (CODIGO_CLIENTE, ACTIVO_CLIENTE, RAZONSOCIAL_CLIENTE, NIF_CLIE' +
        'NTE, MOVIL_CLIENTE, EMAIL_CLIENTE, DIRECCION1_CLIENTE, DIRECCION' +
        '2_CLIENTE, POBLACION_CLIENTE, PROVINCIA_CLIENTE, CPOSTAL_CLIENTE' +
        ', PAIS_CLIENTE, OBSERVACIONES_CLIENTE, REFERENCIA_CLIENTE, CONTA' +
        'CTO_CLIENTE, TELEFONO_CONTACTO_CLIENTE, TELEFONO_CLIENTE, IBAN_C' +
        'LIENTE, IVA_RECARGO_CLIENTE, RETENCIONES_CLIENTE, CODIGO_FORMA_P' +
        'AGO, CODIGO_ZONA_IVA_CLIENTE, TEXTO_LEGAL_FACTURA_CLIENTE, INSTA' +
        'NTEMODIF, INSTANTEALTA, USUARIOALTA, USUARIOMODIF)'
      'VALUES'
      
        '  (:CODIGO_CLIENTE, :ACTIVO_CLIENTE, :RAZONSOCIAL_CLIENTE, :NIF_' +
        'CLIENTE, :MOVIL_CLIENTE, :EMAIL_CLIENTE, :DIRECCION1_CLIENTE, :D' +
        'IRECCION2_CLIENTE, :POBLACION_CLIENTE, :PROVINCIA_CLIENTE, :CPOS' +
        'TAL_CLIENTE, :PAIS_CLIENTE, :OBSERVACIONES_CLIENTE, :REFERENCIA_' +
        'CLIENTE, :CONTACTO_CLIENTE, :TELEFONO_CONTACTO_CLIENTE, :TELEFON' +
        'O_CLIENTE, :IBAN_CLIENTE, :IVA_RECARGO_CLIENTE, :RETENCIONES_CLI' +
        'ENTE, :CODIGO_FORMA_PAGO, :CODIGO_ZONA_IVA_CLIENTE, :TEXTO_LEGAL' +
        '_FACTURA_CLIENTE, :INSTANTEMODIF, :INSTANTEALTA, :USUARIOALTA, :' +
        'USUARIOMODIF)')
    SQLDelete.Strings = (
      'DELETE FROM fza_clientes'
      'WHERE'
      '  CODIGO_CLIENTE = :Old_CODIGO_CLIENTE')
    SQLUpdate.Strings = (
      'UPDATE fza_clientes'
      'SET'
      
        '  CODIGO_CLIENTE = :CODIGO_CLIENTE, ACTIVO_CLIENTE = :ACTIVO_CLI' +
        'ENTE, RAZONSOCIAL_CLIENTE = :RAZONSOCIAL_CLIENTE, NIF_CLIENTE = ' +
        ':NIF_CLIENTE, MOVIL_CLIENTE = :MOVIL_CLIENTE, EMAIL_CLIENTE = :E' +
        'MAIL_CLIENTE, DIRECCION1_CLIENTE = :DIRECCION1_CLIENTE, DIRECCIO' +
        'N2_CLIENTE = :DIRECCION2_CLIENTE, POBLACION_CLIENTE = :POBLACION' +
        '_CLIENTE, PROVINCIA_CLIENTE = :PROVINCIA_CLIENTE, CPOSTAL_CLIENT' +
        'E = :CPOSTAL_CLIENTE, PAIS_CLIENTE = :PAIS_CLIENTE, OBSERVACIONE' +
        'S_CLIENTE = :OBSERVACIONES_CLIENTE, REFERENCIA_CLIENTE = :REFERE' +
        'NCIA_CLIENTE, CONTACTO_CLIENTE = :CONTACTO_CLIENTE, TELEFONO_CON' +
        'TACTO_CLIENTE = :TELEFONO_CONTACTO_CLIENTE, TELEFONO_CLIENTE = :' +
        'TELEFONO_CLIENTE, IBAN_CLIENTE = :IBAN_CLIENTE, IVA_RECARGO_CLIE' +
        'NTE = :IVA_RECARGO_CLIENTE, RETENCIONES_CLIENTE = :RETENCIONES_C' +
        'LIENTE, CODIGO_FORMA_PAGO = :CODIGO_FORMA_PAGO, CODIGO_ZONA_IVA_' +
        'CLIENTE = :CODIGO_ZONA_IVA_CLIENTE, TEXTO_LEGAL_FACTURA_CLIENTE ' +
        '= :TEXTO_LEGAL_FACTURA_CLIENTE, INSTANTEMODIF = :INSTANTEMODIF, ' +
        'INSTANTEALTA = :INSTANTEALTA, USUARIOALTA = :USUARIOALTA, USUARI' +
        'OMODIF = :USUARIOMODIF'
      'WHERE'
      '  CODIGO_CLIENTE = :Old_CODIGO_CLIENTE')
    SQLLock.Strings = (
      'SELECT * FROM fza_clientes'
      'WHERE'
      '  CODIGO_CLIENTE = :Old_CODIGO_CLIENTE'
      'FOR UPDATE')
    SQLRefresh.Strings = (
      
        'SELECT CODIGO_CLIENTE, ACTIVO_CLIENTE, RAZONSOCIAL_CLIENTE, NIF_' +
        'CLIENTE, MOVIL_CLIENTE, EMAIL_CLIENTE, DIRECCION1_CLIENTE, DIREC' +
        'CION2_CLIENTE, POBLACION_CLIENTE, PROVINCIA_CLIENTE, CPOSTAL_CLI' +
        'ENTE, PAIS_CLIENTE, OBSERVACIONES_CLIENTE, REFERENCIA_CLIENTE, C' +
        'ONTACTO_CLIENTE, TELEFONO_CONTACTO_CLIENTE, TELEFONO_CLIENTE, IB' +
        'AN_CLIENTE, IVA_RECARGO_CLIENTE, RETENCIONES_CLIENTE, CODIGO_FOR' +
        'MA_PAGO, CODIGO_ZONA_IVA_CLIENTE, TEXTO_LEGAL_FACTURA_CLIENTE, I' +
        'NSTANTEMODIF, INSTANTEALTA, USUARIOALTA, USUARIOMODIF FROM fza_c' +
        'lientes'
      'WHERE'
      '  CODIGO_CLIENTE = :CODIGO_CLIENTE')
    SQLRecCount.Strings = (
      'SELECT COUNT(*) FROM fza_clientes')
    Connection = dmConn.conUni
    SQL.Strings = (
      'SELECT * FROM VI_EMP_BUSQUEDAS')
    Left = 132
    Top = 536
  end
  object unstdCrearEmpresa: TUniStoredProc
    StoredProcName = 'PRC_CREAR_ACTUALIZAR_EMPRESA'
    SQL.Strings = (
      
        'CALL PRC_CREAR_ACTUALIZAR_EMPRESA(:pCODIGO_EMPRESA, :pRAZONSOCIA' +
        'L_EMPRESA, :pNIF_EMPRESA, :pMOVIL_EMPRESA, :pEMAIL_EMPRESA, :pDI' +
        'RECCION1_EMPRESA, :pDIRECCION2_EMPRESA, :pPOBLACION_EMPRESA, :pP' +
        'ROVINCIA_EMPRESA, :pCPOSTAL_EMPRESA, :pPAIS_EMPRESA, :pCODPAIS_E' +
        'MPRESA, :pRETENCIONES_EMPRESA, :pIVA_RECARGO_EMPRESA, :pREGIMENE' +
        'SPECIALAGRICOLA_EMPRESA, :pGRUPO_ZONA_IVA_EMPRESA, :pUSUARIO)')
    Connection = dmConn.conUni
    Left = 416
    Top = 320
    ParamData = <
      item
        DataType = ftWideString
        Name = 'pCODIGO_EMPRESA'
        ParamType = ptInput
        Size = 10
        Value = ''
      end
      item
        DataType = ftWideString
        Name = 'pRAZONSOCIAL_EMPRESA'
        ParamType = ptInput
        Size = 200
        Value = nil
      end
      item
        DataType = ftWideString
        Name = 'pNIF_EMPRESA'
        ParamType = ptInput
        Size = 50
        Value = nil
      end
      item
        DataType = ftWideString
        Name = 'pMOVIL_EMPRESA'
        ParamType = ptInput
        Size = 40
        Value = nil
      end
      item
        DataType = ftWideString
        Name = 'pEMAIL_EMPRESA'
        ParamType = ptInput
        Size = 200
        Value = nil
      end
      item
        DataType = ftWideString
        Name = 'pDIRECCION1_EMPRESA'
        ParamType = ptInput
        Size = 200
        Value = nil
      end
      item
        DataType = ftWideString
        Name = 'pDIRECCION2_EMPRESA'
        ParamType = ptInput
        Size = 200
        Value = nil
      end
      item
        DataType = ftWideString
        Name = 'pPOBLACION_EMPRESA'
        ParamType = ptInput
        Size = 200
        Value = nil
      end
      item
        DataType = ftWideString
        Name = 'pPROVINCIA_EMPRESA'
        ParamType = ptInput
        Size = 200
        Value = nil
      end
      item
        DataType = ftWideString
        Name = 'pCPOSTAL_EMPRESA'
        ParamType = ptInput
        Size = 15
        Value = nil
      end
      item
        DataType = ftWideString
        Name = 'pPAIS_EMPRESA'
        ParamType = ptInput
        Size = 150
        Value = nil
      end
      item
        DataType = ftWideString
        Name = 'pCODPAIS_EMPRESA'
        ParamType = ptInput
        Size = 150
        Value = nil
      end
      item
        DataType = ftWideString
        Name = 'pRETENCIONES_EMPRESA'
        ParamType = ptInput
        Size = 1
        Value = nil
      end
      item
        DataType = ftWideString
        Name = 'pIVA_RECARGO_EMPRESA'
        ParamType = ptInput
        Size = 1
        Value = nil
      end
      item
        DataType = ftWideString
        Name = 'pREGIMENESPECIALAGRICOLA_EMPRESA'
        ParamType = ptInput
        Size = 1
        Value = nil
      end
      item
        DataType = ftWideString
        Name = 'pGRUPO_ZONA_IVA_EMPRESA'
        ParamType = ptInput
        Size = 10
        Value = nil
      end
      item
        DataType = ftWideString
        Name = 'pUSUARIO'
        ParamType = ptInput
        Size = 100
        Value = ''
      end>
    CommandStoredProcName = 'PRC_CREAR_ACTUALIZAR_EMPRESA'
  end
  object dsTarifas: TDataSource
    DataSet = unqryTarifas
    Left = 608
    Top = 80
  end
  object unqryTarifas: TUniQuery
    Connection = dmConn.conUni
    SQL.Strings = (
      'SELECT *'
      'FROM vi_tarifas'
      '')
    Left = 608
    Top = 176
  end
  object unstdGetContadorLinea: TUniStoredProc
    StoredProcName = 'PRC_FNC_GET_NEXT_LINEA_FACTURA'
    SQL.Strings = (
      
        'CALL PRC_FNC_GET_NEXT_LINEA_FACTURA(:pnumfac, :pserie, @presul);' +
        ' SELECT @presul AS '#39'@presul'#39)
    Connection = dmConn.conUni
    Left = 784
    Top = 336
    ParamData = <
      item
        DataType = ftWideString
        Name = 'pnumfac'
        ParamType = ptInput
        Size = 8
        Value = nil
      end
      item
        DataType = ftWideString
        Name = 'pserie'
        ParamType = ptInput
        Size = 8
        Value = nil
      end
      item
        DataType = ftWideString
        Name = 'presul'
        ParamType = ptOutput
        Size = 3
        Value = '010'
      end>
    CommandStoredProcName = 'PRC_FNC_GET_NEXT_LINEA_FACTURA'
  end
  object unstdCalcularFactura: TUniStoredProc
    StoredProcName = 'PRC_CALCULAR_FACTURA_NETOS'
    SQL.Strings = (
      'CALL PRC_CALCULAR_FACTURA_NETOS(:pSERIE_FACTURA, :pNRO_FACTURA)')
    Connection = dmConn.conUni
    Left = 920
    Top = 296
    ParamData = <
      item
        DataType = ftWideString
        Name = 'pSERIE_FACTURA'
        ParamType = ptInput
        Size = 10
        Value = nil
      end
      item
        DataType = ftInteger
        Name = 'pNRO_FACTURA'
        ParamType = ptInput
        Value = nil
      end>
    CommandStoredProcName = 'PRC_CALCULAR_FACTURA_NETOS'
  end
  object dsSeriesEditCombo: TDataSource
    DataSet = unqrySeriesEditCombo
    Left = 848
    Top = 56
  end
  object unqrySeriesEditCombo: TUniQuery
    Connection = dmConn.conUni
    SQL.Strings = (
      'SELECT DISTINCT * FROM tmpfac_comboseries ')
    Left = 848
    Top = 144
  end
  object unstrdprcGetContadorFactura: TUniStoredProc
    StoredProcName = 'PRC_GET_NEXT_CONT_FACT_SERIE'
    SQL.Strings = (
      
        'CALL PRC_GET_NEXT_CONT_FACT_SERIE(:pserie, :pTipoDoc, :pEMPRESA_' +
        'CONTADOR, :pUSUARIOMODIF, @pcont); SELECT @pcont AS '#39'@pcont'#39)
    Connection = dmConn.conUni
    Left = 56
    Top = 296
    ParamData = <
      item
        DataType = ftWideString
        Name = 'pserie'
        ParamType = ptInput
        Size = 10
        Value = nil
      end
      item
        DataType = ftWideString
        Name = 'pTipoDoc'
        ParamType = ptInput
        Size = 2
        Value = nil
      end
      item
        DataType = ftWideString
        Name = 'pEMPRESA_CONTADOR'
        ParamType = ptInput
        Size = 10
        Value = nil
      end
      item
        DataType = ftWideString
        Name = 'pUSUARIOMODIF'
        ParamType = ptInput
        Size = 100
        Value = nil
      end
      item
        DataType = ftWideString
        Name = 'pcont'
        ParamType = ptOutput
        Size = 12
        Value = nil
      end>
    CommandStoredProcName = 'PRC_GET_NEXT_CONT_FACT_SERIE'
  end
  object unqryIvasTipos: TUniQuery
    Connection = dmConn.conUni
    SQL.Strings = (
      'SELECT * '
      'FROM FZA_IVAS_TIPOS'
      '')
    Left = 959
    Top = 176
  end
  object dsIvasTipos: TDataSource
    DataSet = unqryIvasTipos
    Left = 960
    Top = 80
  end
  object dsFactura: TDataSource
    DataSet = unqryTablaG
    Left = 368
    Top = 440
  end
  object unstdCrearArticuloLin: TUniStoredProc
    StoredProcName = 'PRC_CREAR_ACTUALIZAR_ARTICULO'
    SQL.Strings = (
      
        'CALL PRC_CREAR_ACTUALIZAR_ARTICULO(:pCODIGO_ARTICULO, :pDESCRIPC' +
        'ION_ARTICULO, :pTIPOIVA_ARTICULO, :pTIPO_CANTIDAD_ARTICULO, :pES' +
        'ACTIVO_FIJO_ARTICULO, :pCODIGO_FAMILIA, :pNOMBRE_FAMILIA, :pCODI' +
        'GO_PROVEEDOR, :pRAZONSOCIAL_PROVEEDOR, :pESPROVEEDORPRINCIPAL, :' +
        'pPRECIO_ULT_COMPRA, :pCODIGO_TARIFA, :pPRECIOSALIDA_TARIFA, :pPR' +
        'ECIOFINAL_TARIFA, :pPRECIO_DTO_TARIFA, :pPORCEN_DTO_TARIFA, :pUS' +
        'UARIO)')
    Connection = dmConn.conUni
    Left = 1360
    Top = 296
    ParamData = <
      item
        DataType = ftWideString
        Name = 'pCODIGO_ARTICULO'
        ParamType = ptInput
        Size = 20
        Value = nil
      end
      item
        DataType = ftWideString
        Name = 'pDESCRIPCION_ARTICULO'
        ParamType = ptInput
        Size = 1000
        Value = nil
      end
      item
        DataType = ftWideString
        Name = 'pTIPOIVA_ARTICULO'
        ParamType = ptInput
        Size = 2
        Value = nil
      end
      item
        DataType = ftWideString
        Name = 'pTIPO_CANTIDAD_ARTICULO'
        ParamType = ptInput
        Size = 20
        Value = nil
      end
      item
        DataType = ftWideString
        Name = 'pESACTIVO_FIJO_ARTICULO'
        ParamType = ptInput
        Size = 1
        Value = nil
      end
      item
        DataType = ftWideString
        Name = 'pCODIGO_FAMILIA'
        ParamType = ptInput
        Size = 20
        Value = nil
      end
      item
        DataType = ftWideString
        Name = 'pNOMBRE_FAMILIA'
        ParamType = ptInput
        Size = 200
        Value = nil
      end
      item
        DataType = ftWideString
        Name = 'pCODIGO_PROVEEDOR'
        ParamType = ptInput
        Size = 20
        Value = nil
      end
      item
        DataType = ftWideString
        Name = 'pRAZONSOCIAL_PROVEEDOR'
        ParamType = ptInput
        Size = 200
        Value = nil
      end
      item
        DataType = ftWideString
        Name = 'pESPROVEEDORPRINCIPAL'
        ParamType = ptInput
        Size = 1
        Value = nil
      end
      item
        DataType = ftFloat
        Name = 'pPRECIO_ULT_COMPRA'
        ParamType = ptInput
        Value = nil
      end
      item
        DataType = ftWideString
        Name = 'pCODIGO_TARIFA'
        ParamType = ptInput
        Size = 20
        Value = nil
      end
      item
        DataType = ftFloat
        Name = 'pPRECIOSALIDA_TARIFA'
        ParamType = ptInput
        Value = nil
      end
      item
        DataType = ftFloat
        Name = 'pPRECIOFINAL_TARIFA'
        ParamType = ptInput
        Value = nil
      end
      item
        DataType = ftFloat
        Name = 'pPRECIO_DTO_TARIFA'
        ParamType = ptInput
        Value = nil
      end
      item
        DataType = ftFloat
        Name = 'pPORCEN_DTO_TARIFA'
        ParamType = ptInput
        Value = nil
      end
      item
        DataType = ftWideString
        Name = 'pUSUARIO'
        ParamType = ptInput
        Size = 100
        Value = nil
      end>
    CommandStoredProcName = 'PRC_CREAR_ACTUALIZAR_ARTICULO'
  end
  object dsPaisesCli: TDataSource
    DataSet = unqryPaisesCli
    Left = 1048
    Top = 64
  end
  object unqryPaisesCli: TUniQuery
    SQLInsert.Strings = (
      'INSERT INTO fza_historia'
      
        '  (ID, CODIGO_ARTICULO, DESCRIPCION_ARTICULO, CODIGO_CLIENTE, PR' +
        'ECIOVENTA_ARTICULO, FECHA, ZONA, DESCRIPCION_HISTORIA, NRO_FACTU' +
        'RA, LINEA_LINEA, ODONTOLOGO, SERIE_FACTURA)'
      'VALUES'
      
        '  (:ID, :CODIGO_ARTICULO, :DESCRIPCION_ARTICULO, :CODIGO_CLIENTE' +
        ', :PRECIOVENTA_ARTICULO, :FECHA, :ZONA, :DESCRIPCION_HISTORIA, :' +
        'NRO_FACTURA, :LINEA_LINEA, :ODONTOLOGO, :SERIE_FACTURA)')
    SQLDelete.Strings = (
      'DELETE FROM fza_historia'
      'WHERE'
      '  ID = :Old_ID')
    SQLUpdate.Strings = (
      'UPDATE fza_historia'
      'SET'
      
        '  ID = :ID, CODIGO_ARTICULO = :CODIGO_ARTICULO, DESCRIPCION_ARTI' +
        'CULO = :DESCRIPCION_ARTICULO, CODIGO_CLIENTE = :CODIGO_CLIENTE, ' +
        'PRECIOVENTA_ARTICULO = :PRECIOVENTA_ARTICULO, FECHA = :FECHA, ZO' +
        'NA = :ZONA, DESCRIPCION_HISTORIA = :DESCRIPCION_HISTORIA, NRO_FA' +
        'CTURA = :NRO_FACTURA, LINEA_LINEA = :LINEA_LINEA, ODONTOLOGO = :' +
        'ODONTOLOGO, SERIE_FACTURA = :SERIE_FACTURA'
      'WHERE'
      '  ID = :Old_ID')
    SQLLock.Strings = (
      'SELECT * FROM fza_historia'
      'WHERE'
      '  ID = :Old_ID'
      'FOR UPDATE')
    SQLRefresh.Strings = (
      
        'SELECT ID, CODIGO_ARTICULO, DESCRIPCION_ARTICULO, CODIGO_CLIENTE' +
        ', PRECIOVENTA_ARTICULO, FECHA, ZONA, DESCRIPCION_HISTORIA, NRO_F' +
        'ACTURA, LINEA_LINEA, ODONTOLOGO, SERIE_FACTURA FROM fza_historia'
      'WHERE'
      '  ID = :ID')
    SQLRecCount.Strings = (
      'SELECT COUNT(*) FROM fza_historia')
    Connection = dmConn.conUni
    SQL.Strings = (
      'select * from vi_paises'
      '')
    ReadOnly = True
    Left = 1048
    Top = 144
  end
  object unqryPaisesEmp: TUniQuery
    SQLInsert.Strings = (
      'INSERT INTO fza_historia'
      
        '  (ID, CODIGO_ARTICULO, DESCRIPCION_ARTICULO, CODIGO_CLIENTE, PR' +
        'ECIOVENTA_ARTICULO, FECHA, ZONA, DESCRIPCION_HISTORIA, NRO_FACTU' +
        'RA, LINEA_LINEA, ODONTOLOGO, SERIE_FACTURA)'
      'VALUES'
      
        '  (:ID, :CODIGO_ARTICULO, :DESCRIPCION_ARTICULO, :CODIGO_CLIENTE' +
        ', :PRECIOVENTA_ARTICULO, :FECHA, :ZONA, :DESCRIPCION_HISTORIA, :' +
        'NRO_FACTURA, :LINEA_LINEA, :ODONTOLOGO, :SERIE_FACTURA)')
    SQLDelete.Strings = (
      'DELETE FROM fza_historia'
      'WHERE'
      '  ID = :Old_ID')
    SQLUpdate.Strings = (
      'UPDATE fza_historia'
      'SET'
      
        '  ID = :ID, CODIGO_ARTICULO = :CODIGO_ARTICULO, DESCRIPCION_ARTI' +
        'CULO = :DESCRIPCION_ARTICULO, CODIGO_CLIENTE = :CODIGO_CLIENTE, ' +
        'PRECIOVENTA_ARTICULO = :PRECIOVENTA_ARTICULO, FECHA = :FECHA, ZO' +
        'NA = :ZONA, DESCRIPCION_HISTORIA = :DESCRIPCION_HISTORIA, NRO_FA' +
        'CTURA = :NRO_FACTURA, LINEA_LINEA = :LINEA_LINEA, ODONTOLOGO = :' +
        'ODONTOLOGO, SERIE_FACTURA = :SERIE_FACTURA'
      'WHERE'
      '  ID = :Old_ID')
    SQLLock.Strings = (
      'SELECT * FROM fza_historia'
      'WHERE'
      '  ID = :Old_ID'
      'FOR UPDATE')
    SQLRefresh.Strings = (
      
        'SELECT ID, CODIGO_ARTICULO, DESCRIPCION_ARTICULO, CODIGO_CLIENTE' +
        ', PRECIOVENTA_ARTICULO, FECHA, ZONA, DESCRIPCION_HISTORIA, NRO_F' +
        'ACTURA, LINEA_LINEA, ODONTOLOGO, SERIE_FACTURA FROM fza_historia'
      'WHERE'
      '  ID = :ID')
    SQLRecCount.Strings = (
      'SELECT COUNT(*) FROM fza_historia')
    Connection = dmConn.conUni
    SQL.Strings = (
      'select * from vi_paises'
      '')
    ReadOnly = True
    Left = 1120
    Top = 192
  end
  object dsPaisesEmp: TDataSource
    DataSet = unqryPaisesEmp
    Left = 1120
    Top = 80
  end
  object dsConsolidacion: TDataSource
    DataSet = unqryConsolidacion
    Left = 1216
    Top = 48
  end
  object unqryConsolidacion: TUniQuery
    SQLInsert.Strings = (
      'INSERT INTO fza_facturas_consolidaciones'
      
        '  (ID_CONSOLIDACION, SERIE_FACTURA_CONSOLIDACION, NRO_FACTURA_CO' +
        'NSOLIDACION, REQUEST_ID_CONSOLIDACION, QUEUE_ID_CONSOLIDACION, Q' +
        'UEUE_ID_CANCEL_CONSOLIDACION, ISSUER_IRS_ID_CONSOLIDACION, ISSUE' +
        'D_TIME_CONSOLIDACION, CHAIN_NUMBER_CONSOLIDACION, CHAIN_HASH_CON' +
        'SOLIDACION, VERIFACTU_URL_CONSOLIDACION, QRCODE_BASE64_CONSOLIDA' +
        'CION, QRCODE_PNG_CONSOLIDACION, FECHA_PROCESAMIENTO_CONSOLIDACIO' +
        'N, ESTADO_CONSOLIDACION, RESPUESTA_COMPLETA_CONSOLIDACION, PETIC' +
        'ION_COMPLETA_CONSOLIDACION)'
      'VALUES'
      
        '  (:ID_CONSOLIDACION, :SERIE_FACTURA_CONSOLIDACION, :NRO_FACTURA' +
        '_CONSOLIDACION, :REQUEST_ID_CONSOLIDACION, :QUEUE_ID_CONSOLIDACI' +
        'ON, :QUEUE_ID_CANCEL_CONSOLIDACION, :ISSUER_IRS_ID_CONSOLIDACION' +
        ', :ISSUED_TIME_CONSOLIDACION, :CHAIN_NUMBER_CONSOLIDACION, :CHAI' +
        'N_HASH_CONSOLIDACION, :VERIFACTU_URL_CONSOLIDACION, :QRCODE_BASE' +
        '64_CONSOLIDACION, :QRCODE_PNG_CONSOLIDACION, :FECHA_PROCESAMIENT' +
        'O_CONSOLIDACION, :ESTADO_CONSOLIDACION, :RESPUESTA_COMPLETA_CONS' +
        'OLIDACION, :PETICION_COMPLETA_CONSOLIDACION)')
    SQLDelete.Strings = (
      'DELETE FROM fza_facturas_consolidaciones'
      'WHERE'
      '  ID_CONSOLIDACION = :Old_ID_CONSOLIDACION')
    SQLUpdate.Strings = (
      'UPDATE fza_facturas_consolidaciones'
      'SET'
      
        '  ID_CONSOLIDACION = :ID_CONSOLIDACION, SERIE_FACTURA_CONSOLIDAC' +
        'ION = :SERIE_FACTURA_CONSOLIDACION, NRO_FACTURA_CONSOLIDACION = ' +
        ':NRO_FACTURA_CONSOLIDACION, REQUEST_ID_CONSOLIDACION = :REQUEST_' +
        'ID_CONSOLIDACION, QUEUE_ID_CONSOLIDACION = :QUEUE_ID_CONSOLIDACI' +
        'ON, QUEUE_ID_CANCEL_CONSOLIDACION = :QUEUE_ID_CANCEL_CONSOLIDACI' +
        'ON, ISSUER_IRS_ID_CONSOLIDACION = :ISSUER_IRS_ID_CONSOLIDACION, ' +
        'ISSUED_TIME_CONSOLIDACION = :ISSUED_TIME_CONSOLIDACION, CHAIN_NU' +
        'MBER_CONSOLIDACION = :CHAIN_NUMBER_CONSOLIDACION, CHAIN_HASH_CON' +
        'SOLIDACION = :CHAIN_HASH_CONSOLIDACION, VERIFACTU_URL_CONSOLIDAC' +
        'ION = :VERIFACTU_URL_CONSOLIDACION, QRCODE_BASE64_CONSOLIDACION ' +
        '= :QRCODE_BASE64_CONSOLIDACION, QRCODE_PNG_CONSOLIDACION = :QRCO' +
        'DE_PNG_CONSOLIDACION, FECHA_PROCESAMIENTO_CONSOLIDACION = :FECHA' +
        '_PROCESAMIENTO_CONSOLIDACION, ESTADO_CONSOLIDACION = :ESTADO_CON' +
        'SOLIDACION, RESPUESTA_COMPLETA_CONSOLIDACION = :RESPUESTA_COMPLE' +
        'TA_CONSOLIDACION, PETICION_COMPLETA_CONSOLIDACION = :PETICION_CO' +
        'MPLETA_CONSOLIDACION'
      'WHERE'
      '  ID_CONSOLIDACION = :Old_ID_CONSOLIDACION')
    SQLLock.Strings = (
      
        'SELECT ID_CONSOLIDACION, SERIE_FACTURA_CONSOLIDACION, NRO_FACTUR' +
        'A_CONSOLIDACION, REQUEST_ID_CONSOLIDACION, QUEUE_ID_CONSOLIDACIO' +
        'N, QUEUE_ID_CANCEL_CONSOLIDACION, ISSUER_IRS_ID_CONSOLIDACION, I' +
        'SSUED_TIME_CONSOLIDACION, CHAIN_NUMBER_CONSOLIDACION, CHAIN_HASH' +
        '_CONSOLIDACION, VERIFACTU_URL_CONSOLIDACION, QRCODE_BASE64_CONSO' +
        'LIDACION, QRCODE_PNG_CONSOLIDACION, FECHA_PROCESAMIENTO_CONSOLID' +
        'ACION, ESTADO_CONSOLIDACION, RESPUESTA_COMPLETA_CONSOLIDACION, P' +
        'ETICION_COMPLETA_CONSOLIDACION FROM fza_facturas_consolidaciones'
      'WHERE'
      '  ID_CONSOLIDACION = :Old_ID_CONSOLIDACION'
      'FOR UPDATE')
    SQLRefresh.Strings = (
      
        'SELECT ID_CONSOLIDACION, SERIE_FACTURA_CONSOLIDACION, NRO_FACTUR' +
        'A_CONSOLIDACION, REQUEST_ID_CONSOLIDACION, QUEUE_ID_CONSOLIDACIO' +
        'N, QUEUE_ID_CANCEL_CONSOLIDACION, ISSUER_IRS_ID_CONSOLIDACION, I' +
        'SSUED_TIME_CONSOLIDACION, CHAIN_NUMBER_CONSOLIDACION, CHAIN_HASH' +
        '_CONSOLIDACION, VERIFACTU_URL_CONSOLIDACION, QRCODE_BASE64_CONSO' +
        'LIDACION, QRCODE_PNG_CONSOLIDACION, FECHA_PROCESAMIENTO_CONSOLID' +
        'ACION, ESTADO_CONSOLIDACION, RESPUESTA_COMPLETA_CONSOLIDACION, P' +
        'ETICION_COMPLETA_CONSOLIDACION FROM fza_facturas_consolidaciones'
      'WHERE'
      '  ID_CONSOLIDACION = :ID_CONSOLIDACION')
    SQLRecCount.Strings = (
      'SELECT COUNT(*) FROM fza_facturas_consolidaciones')
    Connection = dmConn.conUni
    SQL.Strings = (
      'SELECT * FROM fza_facturas_consolidaciones'
      'WHERE NRO_FACTURA_CONSOLIDACION = :NRO_FACTURA'
      'AND SERIE_FACTURA_CONSOLIDACION = :SERIE_FACTURA'
      'ORDER BY ID_CONSOLIDACION DESC')
    MasterSource = frmMtoFacturas.dsTablaG
    MasterFields = 'SERIE_FACTURA;NRO_FACTURA'
    DetailFields = 'ID_CONSOLIDACION;NRO_FACTURA_CONSOLIDACION'
    ReadOnly = True
    Left = 1216
    Top = 144
    ParamData = <
      item
        DataType = ftWideString
        Name = 'NRO_FACTURA'
        ParamType = ptInput
        Value = '000001'
      end
      item
        DataType = ftWideString
        Name = 'SERIE_FACTURA'
        ParamType = ptInput
        Value = 'A0'
      end>
  end
  object dsErrores: TDataSource
    DataSet = unqryErrores
    Left = 1304
    Top = 80
  end
  object unqryErrores: TUniQuery
    Connection = dmConn.conUni
    SQL.Strings = (
      'select *'
      'FROM fza_verifactu_eventos'
      'order by id_log desc')
    MasterSource = frmMtoFacturas.dsTablaG
    MasterFields = 'NRO_FACTURA;SERIE_FACTURA'
    DetailFields = 'NRO_FACTURA_LOG;SERIE_FACTURA_LOG'
    ReadOnly = True
    AutoCalcFields = False
    Left = 1304
    Top = 168
    ParamData = <
      item
        DataType = ftWideString
        Name = 'NRO_FACTURA'
        ParamType = ptInput
        Value = nil
      end
      item
        DataType = ftWideString
        Name = 'SERIE_FACTURA'
        ParamType = ptInput
        Value = nil
      end>
  end
end
