inherited dmClientes: TdmClientes
  Height = 296
  Width = 866
  inherited unqryTablaG: TUniQuery
    SQLInsert.Strings = (
      'INSERT INTO fza_clientes'
      
        '  (CODIGO_CLIENTE, ACTIVO_CLIENTE, ORDEN_CLIENTE, RAZONSOCIAL_CL' +
        'IENTE, NIF_CLIENTE, MOVIL_CLIENTE, EMAIL_CLIENTE, DIRECCION1_CLI' +
        'ENTE, DIRECCION2_CLIENTE, POBLACION_CLIENTE, PROVINCIA_CLIENTE, ' +
        'CPOSTAL_CLIENTE, CODIGO_PAIS_CLIENTE, NOMBRE_PAIS_CLIENTE, OBSER' +
        'VACIONES_CLIENTE, REFERENCIA_CLIENTE, CONTACTO_CLIENTE, TELEFONO' +
        '_CONTACTO_CLIENTE, TELEFONO_CLIENTE, IBAN_CLIENTE, ESIVA_RECARGO' +
        '_CLIENTE, ESRETENCIONES_CLIENTE, ESIVA_EXENTO_CLIENTE, ESINTRACO' +
        'MUNITARIO_CLIENTE, ESREGIMENESPECIALAGRICOLA_CLIENTE, CODIGO_FOR' +
        'MA_PAGO_CLIENTE, TARIFA_ARTICULO_CLIENTE, SERIE_CONTADOR_CLIENTE' +
        ', TEXTO_LEGAL_FACTURA_CLIENTE, INSTANTEMODIF, INSTANTEALTA, USUA' +
        'RIOALTA, USUARIOMODIF)'
      'VALUES'
      
        '  (:CODIGO_CLIENTE, :ACTIVO_CLIENTE, :ORDEN_CLIENTE, :RAZONSOCIA' +
        'L_CLIENTE, :NIF_CLIENTE, :MOVIL_CLIENTE, :EMAIL_CLIENTE, :DIRECC' +
        'ION1_CLIENTE, :DIRECCION2_CLIENTE, :POBLACION_CLIENTE, :PROVINCI' +
        'A_CLIENTE, :CPOSTAL_CLIENTE, :CODIGO_PAIS_CLIENTE, :NOMBRE_PAIS_' +
        'CLIENTE, :OBSERVACIONES_CLIENTE, :REFERENCIA_CLIENTE, :CONTACTO_' +
        'CLIENTE, :TELEFONO_CONTACTO_CLIENTE, :TELEFONO_CLIENTE, :IBAN_CL' +
        'IENTE, :ESIVA_RECARGO_CLIENTE, :ESRETENCIONES_CLIENTE, :ESIVA_EX' +
        'ENTO_CLIENTE, :ESINTRACOMUNITARIO_CLIENTE, :ESREGIMENESPECIALAGR' +
        'ICOLA_CLIENTE, :CODIGO_FORMA_PAGO_CLIENTE, :TARIFA_ARTICULO_CLIE' +
        'NTE, :SERIE_CONTADOR_CLIENTE, :TEXTO_LEGAL_FACTURA_CLIENTE, :INS' +
        'TANTEMODIF, :INSTANTEALTA, :USUARIOALTA, :USUARIOMODIF)')
    SQLDelete.Strings = (
      'DELETE FROM fza_clientes'
      'WHERE'
      '  CODIGO_CLIENTE = :Old_CODIGO_CLIENTE')
    SQLUpdate.Strings = (
      'UPDATE fza_clientes'
      'SET'
      
        '  CODIGO_CLIENTE = :CODIGO_CLIENTE, ACTIVO_CLIENTE = :ACTIVO_CLI' +
        'ENTE, ORDEN_CLIENTE = :ORDEN_CLIENTE, RAZONSOCIAL_CLIENTE = :RAZ' +
        'ONSOCIAL_CLIENTE, NIF_CLIENTE = :NIF_CLIENTE, MOVIL_CLIENTE = :M' +
        'OVIL_CLIENTE, EMAIL_CLIENTE = :EMAIL_CLIENTE, DIRECCION1_CLIENTE' +
        ' = :DIRECCION1_CLIENTE, DIRECCION2_CLIENTE = :DIRECCION2_CLIENTE' +
        ', POBLACION_CLIENTE = :POBLACION_CLIENTE, PROVINCIA_CLIENTE = :P' +
        'ROVINCIA_CLIENTE, CPOSTAL_CLIENTE = :CPOSTAL_CLIENTE, CODIGO_PAI' +
        'S_CLIENTE = :CODIGO_PAIS_CLIENTE, NOMBRE_PAIS_CLIENTE = :NOMBRE_' +
        'PAIS_CLIENTE, OBSERVACIONES_CLIENTE = :OBSERVACIONES_CLIENTE, RE' +
        'FERENCIA_CLIENTE = :REFERENCIA_CLIENTE, CONTACTO_CLIENTE = :CONT' +
        'ACTO_CLIENTE, TELEFONO_CONTACTO_CLIENTE = :TELEFONO_CONTACTO_CLI' +
        'ENTE, TELEFONO_CLIENTE = :TELEFONO_CLIENTE, IBAN_CLIENTE = :IBAN' +
        '_CLIENTE, ESIVA_RECARGO_CLIENTE = :ESIVA_RECARGO_CLIENTE, ESRETE' +
        'NCIONES_CLIENTE = :ESRETENCIONES_CLIENTE, ESIVA_EXENTO_CLIENTE =' +
        ' :ESIVA_EXENTO_CLIENTE, ESINTRACOMUNITARIO_CLIENTE = :ESINTRACOM' +
        'UNITARIO_CLIENTE, ESREGIMENESPECIALAGRICOLA_CLIENTE = :ESREGIMEN' +
        'ESPECIALAGRICOLA_CLIENTE, CODIGO_FORMA_PAGO_CLIENTE = :CODIGO_FO' +
        'RMA_PAGO_CLIENTE, TARIFA_ARTICULO_CLIENTE = :TARIFA_ARTICULO_CLI' +
        'ENTE, SERIE_CONTADOR_CLIENTE = :SERIE_CONTADOR_CLIENTE, TEXTO_LE' +
        'GAL_FACTURA_CLIENTE = :TEXTO_LEGAL_FACTURA_CLIENTE, INSTANTEMODI' +
        'F = :INSTANTEMODIF, INSTANTEALTA = :INSTANTEALTA, USUARIOALTA = ' +
        ':USUARIOALTA, USUARIOMODIF = :USUARIOMODIF'
      'WHERE'
      '  CODIGO_CLIENTE = :Old_CODIGO_CLIENTE')
    SQLLock.Strings = (
      
        'SELECT CODIGO_CLIENTE, ACTIVO_CLIENTE, ORDEN_CLIENTE, RAZONSOCIA' +
        'L_CLIENTE, NIF_CLIENTE, MOVIL_CLIENTE, EMAIL_CLIENTE, DIRECCION1' +
        '_CLIENTE, DIRECCION2_CLIENTE, POBLACION_CLIENTE, PROVINCIA_CLIEN' +
        'TE, CPOSTAL_CLIENTE, CODIGO_PAIS_CLIENTE, NOMBRE_PAIS_CLIENTE, O' +
        'BSERVACIONES_CLIENTE, REFERENCIA_CLIENTE, CONTACTO_CLIENTE, TELE' +
        'FONO_CONTACTO_CLIENTE, TELEFONO_CLIENTE, IBAN_CLIENTE, ESIVA_REC' +
        'ARGO_CLIENTE, ESRETENCIONES_CLIENTE, ESIVA_EXENTO_CLIENTE, ESINT' +
        'RACOMUNITARIO_CLIENTE, ESREGIMENESPECIALAGRICOLA_CLIENTE, CODIGO' +
        '_FORMA_PAGO_CLIENTE, TARIFA_ARTICULO_CLIENTE, SERIE_CONTADOR_CLI' +
        'ENTE, TEXTO_LEGAL_FACTURA_CLIENTE, INSTANTEMODIF, INSTANTEALTA, ' +
        'USUARIOALTA, USUARIOMODIF FROM fza_clientes'
      'WHERE'
      '  CODIGO_CLIENTE = :Old_CODIGO_CLIENTE'
      'FOR UPDATE')
    SQLRefresh.Strings = (
      
        'SELECT CODIGO_CLIENTE, ACTIVO_CLIENTE, ORDEN_CLIENTE, RAZONSOCIA' +
        'L_CLIENTE, NIF_CLIENTE, MOVIL_CLIENTE, EMAIL_CLIENTE, DIRECCION1' +
        '_CLIENTE, DIRECCION2_CLIENTE, POBLACION_CLIENTE, PROVINCIA_CLIEN' +
        'TE, CPOSTAL_CLIENTE, CODIGO_PAIS_CLIENTE, NOMBRE_PAIS_CLIENTE, O' +
        'BSERVACIONES_CLIENTE, REFERENCIA_CLIENTE, CONTACTO_CLIENTE, TELE' +
        'FONO_CONTACTO_CLIENTE, TELEFONO_CLIENTE, IBAN_CLIENTE, ESIVA_REC' +
        'ARGO_CLIENTE, ESRETENCIONES_CLIENTE, ESIVA_EXENTO_CLIENTE, ESINT' +
        'RACOMUNITARIO_CLIENTE, ESREGIMENESPECIALAGRICOLA_CLIENTE, CODIGO' +
        '_FORMA_PAGO_CLIENTE, TARIFA_ARTICULO_CLIENTE, SERIE_CONTADOR_CLI' +
        'ENTE, TEXTO_LEGAL_FACTURA_CLIENTE, INSTANTEMODIF, INSTANTEALTA, ' +
        'USUARIOALTA, USUARIOMODIF FROM fza_clientes'
      'WHERE'
      '  CODIGO_CLIENTE = :CODIGO_CLIENTE')
    SQLRecCount.Strings = (
      'SELECT COUNT(*) FROM fza_clientes')
    Connection = dmConn.conUni
    SQL.Strings = (
      'select * from vi_clientes')
    AfterInsert = unqryTablaGAfterInsert
    BeforeDelete = unqryTablaGBeforeDelete
    Left = 56
    Top = 32
  end
  inherited unqryPerfiles: TUniQuery
    SQL.Strings = (
      'select *'
      'from fza_usuarios_perfiles'
      'where KEY_PERFILES = '#39'Nothing'#39)
    Left = 144
    Top = 32
  end
  inherited dsPerfiles: TDataSource
    Left = 144
    Top = 88
  end
  object unstrdprcContador: TUniStoredProc
    StoredProcName = 'PRC_GET_NEXT_CONT'
    SQL.Strings = (
      
        'CALL PRC_GET_NEXT_CONT(:pTipoDoc, :pUSUARIO_MODIF, @pcont); SELE' +
        'CT @pcont AS '#39'@pcont'#39)
    Connection = dmConn.conUni
    Left = 56
    Top = 92
    ParamData = <
      item
        DataType = ftWideString
        Name = 'pTipoDoc'
        ParamType = ptInput
        Size = 2
        Value = nil
      end
      item
        DataType = ftWideString
        Name = 'pUSUARIO_MODIF'
        ParamType = ptInput
        Size = 100
        Value = nil
      end
      item
        DataType = ftWideString
        Name = 'pcont'
        ParamType = ptOutput
        Size = 20
        Value = nil
      end>
    CommandStoredProcName = 'PRC_GET_NEXT_CONT'
  end
  object dsFormasPago: TDataSource
    DataSet = unqryFormaPago
    Left = 224
    Top = 32
  end
  object unqryFormaPago: TUniQuery
    SQLInsert.Strings = (
      'INSERT INTO fza_historia'
      
        '  (ID, CODIGO_ARTICULO, DESCRIPCION_ARTICULO, CODIGO_CLIENTE, PR' +
        'ECIOVENTA_ARTICULO, FECHA, ZONA, DESCRIPCION_HISTORIA, NRO_FACTU' +
        'RA, LINEA_LINEA, ODONTOLOGO, SERIE_FACTURA)'
      'VALUES'
      
        '  (:ID, :CODIGO_ARTICULO, :DESCRIPCION_ARTICULO, :CODIGO_CLIENTE' +
        ', :PRECIOVENTA_ARTICULO, :FECHA, :ZONA, :DESCRIPCION_HISTORIA, :' +
        'NRO_FACTURA, :LINEA_LINEA, :ODONTOLOGO, :SERIE_FACTURA)')
    SQLDelete.Strings = (
      'DELETE FROM fza_historia'
      'WHERE'
      '  ID = :Old_ID')
    SQLUpdate.Strings = (
      'UPDATE fza_historia'
      'SET'
      
        '  ID = :ID, CODIGO_ARTICULO = :CODIGO_ARTICULO, DESCRIPCION_ARTI' +
        'CULO = :DESCRIPCION_ARTICULO, CODIGO_CLIENTE = :CODIGO_CLIENTE, ' +
        'PRECIOVENTA_ARTICULO = :PRECIOVENTA_ARTICULO, FECHA = :FECHA, ZO' +
        'NA = :ZONA, DESCRIPCION_HISTORIA = :DESCRIPCION_HISTORIA, NRO_FA' +
        'CTURA = :NRO_FACTURA, LINEA_LINEA = :LINEA_LINEA, ODONTOLOGO = :' +
        'ODONTOLOGO, SERIE_FACTURA = :SERIE_FACTURA'
      'WHERE'
      '  ID = :Old_ID')
    SQLLock.Strings = (
      'SELECT * FROM fza_historia'
      'WHERE'
      '  ID = :Old_ID'
      'FOR UPDATE')
    SQLRefresh.Strings = (
      
        'SELECT ID, CODIGO_ARTICULO, DESCRIPCION_ARTICULO, CODIGO_CLIENTE' +
        ', PRECIOVENTA_ARTICULO, FECHA, ZONA, DESCRIPCION_HISTORIA, NRO_F' +
        'ACTURA, LINEA_LINEA, ODONTOLOGO, SERIE_FACTURA FROM fza_historia'
      'WHERE'
      '  ID = :ID')
    SQLRecCount.Strings = (
      'SELECT COUNT(*) FROM fza_historia')
    Connection = dmConn.conUni
    SQL.Strings = (
      'select * from vi_formapago'
      '')
    ReadOnly = True
    Left = 224
    Top = 96
  end
  object dsTarifas: TDataSource
    DataSet = unqryTarifas
    Left = 320
    Top = 32
  end
  object unqryTarifas: TUniQuery
    SQLInsert.Strings = (
      'INSERT INTO fza_historia'
      
        '  (ID, CODIGO_ARTICULO, DESCRIPCION_ARTICULO, CODIGO_CLIENTE, PR' +
        'ECIOVENTA_ARTICULO, FECHA, ZONA, DESCRIPCION_HISTORIA, NRO_FACTU' +
        'RA, LINEA_LINEA, ODONTOLOGO, SERIE_FACTURA)'
      'VALUES'
      
        '  (:ID, :CODIGO_ARTICULO, :DESCRIPCION_ARTICULO, :CODIGO_CLIENTE' +
        ', :PRECIOVENTA_ARTICULO, :FECHA, :ZONA, :DESCRIPCION_HISTORIA, :' +
        'NRO_FACTURA, :LINEA_LINEA, :ODONTOLOGO, :SERIE_FACTURA)')
    SQLDelete.Strings = (
      'DELETE FROM fza_historia'
      'WHERE'
      '  ID = :Old_ID')
    SQLUpdate.Strings = (
      'UPDATE fza_historia'
      'SET'
      
        '  ID = :ID, CODIGO_ARTICULO = :CODIGO_ARTICULO, DESCRIPCION_ARTI' +
        'CULO = :DESCRIPCION_ARTICULO, CODIGO_CLIENTE = :CODIGO_CLIENTE, ' +
        'PRECIOVENTA_ARTICULO = :PRECIOVENTA_ARTICULO, FECHA = :FECHA, ZO' +
        'NA = :ZONA, DESCRIPCION_HISTORIA = :DESCRIPCION_HISTORIA, NRO_FA' +
        'CTURA = :NRO_FACTURA, LINEA_LINEA = :LINEA_LINEA, ODONTOLOGO = :' +
        'ODONTOLOGO, SERIE_FACTURA = :SERIE_FACTURA'
      'WHERE'
      '  ID = :Old_ID')
    SQLLock.Strings = (
      'SELECT * FROM fza_historia'
      'WHERE'
      '  ID = :Old_ID'
      'FOR UPDATE')
    SQLRefresh.Strings = (
      
        'SELECT ID, CODIGO_ARTICULO, DESCRIPCION_ARTICULO, CODIGO_CLIENTE' +
        ', PRECIOVENTA_ARTICULO, FECHA, ZONA, DESCRIPCION_HISTORIA, NRO_F' +
        'ACTURA, LINEA_LINEA, ODONTOLOGO, SERIE_FACTURA FROM fza_historia'
      'WHERE'
      '  ID = :ID')
    SQLRecCount.Strings = (
      'SELECT COUNT(*) FROM fza_historia')
    Connection = dmConn.conUni
    SQL.Strings = (
      'select * from vi_tarifas'
      '')
    ReadOnly = True
    Left = 320
    Top = 96
  end
  object dsFacturasClientes: TDataSource
    DataSet = unqryFacturasClientes
    Left = 408
    Top = 32
  end
  object unqryFacturasClientes: TUniQuery
    SQLInsert.Strings = (
      'INSERT INTO FZA_FACTURAS'
      
        '  (NRO_FACTURA, SERIE_FACTURA, FECHA_FACTURA, CODIGO_EMPRESA_FAC' +
        'TURA, RAZONSOCIAL_EMPRESA_FACTURA, NIF_EMPRESA_FACTURA, MOVIL_EM' +
        'PRESA_FACTURA, EMAIL_EMPRESA_FACTURA, DIRECCION1_EMPRESA_FACTURA' +
        ', DIRECCION2_EMPRESA_FACTURA, POBLACION_EMPRESA_FACTURA, PROVINC' +
        'IA_EMPRESA_FACTURA, CODIGO_PAIS_EMPRESA_FACTURA, NOMBRE_PAIS_EMP' +
        'RESA_FACTURA, CPOSTAL_EMPRESA_FACTURA, ESRETENCIONES_EMPRESA_FAC' +
        'TURA, GRUPO_ZONA_IVA_EMPRESA_FACTURA, ESREGIMENESPECIALAGRICOLA_' +
        'EMPRESA_FACTURA, CODIGO_CLIENTE_FACTURA, RAZONSOCIAL_CLIENTE_FAC' +
        'TURA, NIF_CLIENTE_FACTURA, MOVIL_CLIENTE_FACTURA, EMAIL_CLIENTE_' +
        'FACTURA, DIRECCION1_CLIENTE_FACTURA, DIRECCION2_CLIENTE_FACTURA,' +
        ' POBLACION_CLIENTE_FACTURA, PROVINCIA_CLIENTE_FACTURA, CPOSTAL_C' +
        'LIENTE_FACTURA, CODIGO_PAIS_CLIENTE_FACTURA, NOMBRE_PAIS_CLIENTE' +
        '_FACTURA, CODIGO_IVA_FACTURA, ESIVA_RECARGO_CLIENTE_FACTURA, ESI' +
        'VA_EXENTO_CLIENTE_FACTURA, ESREGIMENESPECIALAGRICOLA_CLIENTE_FAC' +
        'TURA, ESRETENCIONES_CLIENTE_FACTURA, TARIFA_ARTICULO_CLIENTE_FAC' +
        'TURA, ESIMP_INCL_TARIFA_CLIENTE_FACTURA, ESINTRACOMUNITARIO_CLIE' +
        'NTE_FACTURA, ESIRPF_IMP_INCL_ZONA_IVA_FACTURA, ESAPLICA_RE_ZONA_' +
        'IVA_FACTURA, ESIVAAGRICOLA_ZONA_IVA_FACTURA, PALABRA_REPORTS_ZON' +
        'A_IVA_FACTURA, ESVENTA_ACTIVO_FIJO_FACTURA, PORCEN_IVAN_FACTURA,' +
        ' TOTAL_IVAN_FACTURA, PORCEN_REN_FACTURA, TOTAL_REN_FACTURA, TOTA' +
        'L_BASEI_IVAN_FACTURA, PORCEN_IVAR_FACTURA, TOTAL_IVAR_FACTURA, P' +
        'ORCEN_RER_FACTURA, TOTAL_RER_FACTURA, TOTAL_BASEI_IVAR_FACTURA, ' +
        'PORCEN_IVAS_FACTURA, TOTAL_IVAS_FACTURA, PORCEN_RES_FACTURA, TOT' +
        'AL_RES_FACTURA, TOTAL_BASEI_IVAS_FACTURA, PORCEN_IVAE_FACTURA, T' +
        'OTAL_IVAE_FACTURA, PORCEN_REE_FACTURA, TOTAL_REE_FACTURA, TOTAL_' +
        'BASEI_IVAE_FACTURA, TOTAL_BASES_FACTURA, TOTAL_IMPUESTOS_FACTURA' +
        ', FORMA_PAGO_FACTURA, PORCEN_RETENCION_FACTURA, TOTAL_RETENCION_' +
        'FACTURA, TOTAL_LIQUIDO_FACTURA, NRO_FACTURA_ABONO_FACTURA, SERIE' +
        '_FACTURA_ABONO_FACTURA, TEXTO_LEGAL_FACTURA_CLIENTE_FACTURA, TEX' +
        'TO_LEGAL_FACTURA_EMPRESA_FACTURA, DOCUMENTO_FACTURA, COMENTARIOS' +
        '_FACTURA, CONTADOR_LINEAS_FACTURA, ESCREARARTICULOS_FACTURA, ESD' +
        'ESCRIPCIONES_AMP_FACTURA, ESFECHADEENTREGA_FACTURA, INSTANTEMODI' +
        'F, INSTANTEALTA, USUARIOALTA, USUARIOMODIF)'
      'VALUES'
      
        '  (:NRO_FACTURA, :SERIE_FACTURA, :FECHA_FACTURA, :CODIGO_EMPRESA' +
        '_FACTURA, :RAZONSOCIAL_EMPRESA_FACTURA, :NIF_EMPRESA_FACTURA, :M' +
        'OVIL_EMPRESA_FACTURA, :EMAIL_EMPRESA_FACTURA, :DIRECCION1_EMPRES' +
        'A_FACTURA, :DIRECCION2_EMPRESA_FACTURA, :POBLACION_EMPRESA_FACTU' +
        'RA, :PROVINCIA_EMPRESA_FACTURA, :CODIGO_PAIS_EMPRESA_FACTURA, :N' +
        'OMBRE_PAIS_EMPRESA_FACTURA, :CPOSTAL_EMPRESA_FACTURA, :ESRETENCI' +
        'ONES_EMPRESA_FACTURA, :GRUPO_ZONA_IVA_EMPRESA_FACTURA, :ESREGIME' +
        'NESPECIALAGRICOLA_EMPRESA_FACTURA, :CODIGO_CLIENTE_FACTURA, :RAZ' +
        'ONSOCIAL_CLIENTE_FACTURA, :NIF_CLIENTE_FACTURA, :MOVIL_CLIENTE_F' +
        'ACTURA, :EMAIL_CLIENTE_FACTURA, :DIRECCION1_CLIENTE_FACTURA, :DI' +
        'RECCION2_CLIENTE_FACTURA, :POBLACION_CLIENTE_FACTURA, :PROVINCIA' +
        '_CLIENTE_FACTURA, :CPOSTAL_CLIENTE_FACTURA, :CODIGO_PAIS_CLIENTE' +
        '_FACTURA, :NOMBRE_PAIS_CLIENTE_FACTURA, :CODIGO_IVA_FACTURA, :ES' +
        'IVA_RECARGO_CLIENTE_FACTURA, :ESIVA_EXENTO_CLIENTE_FACTURA, :ESR' +
        'EGIMENESPECIALAGRICOLA_CLIENTE_FACTURA, :ESRETENCIONES_CLIENTE_F' +
        'ACTURA, :TARIFA_ARTICULO_CLIENTE_FACTURA, :ESIMP_INCL_TARIFA_CLI' +
        'ENTE_FACTURA, :ESINTRACOMUNITARIO_CLIENTE_FACTURA, :ESIRPF_IMP_I' +
        'NCL_ZONA_IVA_FACTURA, :ESAPLICA_RE_ZONA_IVA_FACTURA, :ESIVAAGRIC' +
        'OLA_ZONA_IVA_FACTURA, :PALABRA_REPORTS_ZONA_IVA_FACTURA, :ESVENT' +
        'A_ACTIVO_FIJO_FACTURA, :PORCEN_IVAN_FACTURA, :TOTAL_IVAN_FACTURA' +
        ', :PORCEN_REN_FACTURA, :TOTAL_REN_FACTURA, :TOTAL_BASEI_IVAN_FAC' +
        'TURA, :PORCEN_IVAR_FACTURA, :TOTAL_IVAR_FACTURA, :PORCEN_RER_FAC' +
        'TURA, :TOTAL_RER_FACTURA, :TOTAL_BASEI_IVAR_FACTURA, :PORCEN_IVA' +
        'S_FACTURA, :TOTAL_IVAS_FACTURA, :PORCEN_RES_FACTURA, :TOTAL_RES_' +
        'FACTURA, :TOTAL_BASEI_IVAS_FACTURA, :PORCEN_IVAE_FACTURA, :TOTAL' +
        '_IVAE_FACTURA, :PORCEN_REE_FACTURA, :TOTAL_REE_FACTURA, :TOTAL_B' +
        'ASEI_IVAE_FACTURA, :TOTAL_BASES_FACTURA, :TOTAL_IMPUESTOS_FACTUR' +
        'A, :FORMA_PAGO_FACTURA, :PORCEN_RETENCION_FACTURA, :TOTAL_RETENC' +
        'ION_FACTURA, :TOTAL_LIQUIDO_FACTURA, :NRO_FACTURA_ABONO_FACTURA,' +
        ' :SERIE_FACTURA_ABONO_FACTURA, :TEXTO_LEGAL_FACTURA_CLIENTE_FACT' +
        'URA, :TEXTO_LEGAL_FACTURA_EMPRESA_FACTURA, :DOCUMENTO_FACTURA, :' +
        'COMENTARIOS_FACTURA, :CONTADOR_LINEAS_FACTURA, :ESCREARARTICULOS' +
        '_FACTURA, :ESDESCRIPCIONES_AMP_FACTURA, :ESFECHADEENTREGA_FACTUR' +
        'A, :INSTANTEMODIF, :INSTANTEALTA, :USUARIOALTA, :USUARIOMODIF)')
    SQLDelete.Strings = (
      'DELETE FROM FZA_FACTURAS'
      'WHERE'
      
        '  NRO_FACTURA = :Old_NRO_FACTURA AND SERIE_FACTURA = :Old_SERIE_' +
        'FACTURA')
    SQLUpdate.Strings = (
      'UPDATE FZA_FACTURAS'
      'SET'
      
        '  NRO_FACTURA = :NRO_FACTURA, SERIE_FACTURA = :SERIE_FACTURA, FE' +
        'CHA_FACTURA = :FECHA_FACTURA, CODIGO_EMPRESA_FACTURA = :CODIGO_E' +
        'MPRESA_FACTURA, RAZONSOCIAL_EMPRESA_FACTURA = :RAZONSOCIAL_EMPRE' +
        'SA_FACTURA, NIF_EMPRESA_FACTURA = :NIF_EMPRESA_FACTURA, MOVIL_EM' +
        'PRESA_FACTURA = :MOVIL_EMPRESA_FACTURA, EMAIL_EMPRESA_FACTURA = ' +
        ':EMAIL_EMPRESA_FACTURA, DIRECCION1_EMPRESA_FACTURA = :DIRECCION1' +
        '_EMPRESA_FACTURA, DIRECCION2_EMPRESA_FACTURA = :DIRECCION2_EMPRE' +
        'SA_FACTURA, POBLACION_EMPRESA_FACTURA = :POBLACION_EMPRESA_FACTU' +
        'RA, PROVINCIA_EMPRESA_FACTURA = :PROVINCIA_EMPRESA_FACTURA, CODI' +
        'GO_PAIS_EMPRESA_FACTURA = :CODIGO_PAIS_EMPRESA_FACTURA, NOMBRE_P' +
        'AIS_EMPRESA_FACTURA = :NOMBRE_PAIS_EMPRESA_FACTURA, CPOSTAL_EMPR' +
        'ESA_FACTURA = :CPOSTAL_EMPRESA_FACTURA, ESRETENCIONES_EMPRESA_FA' +
        'CTURA = :ESRETENCIONES_EMPRESA_FACTURA, GRUPO_ZONA_IVA_EMPRESA_F' +
        'ACTURA = :GRUPO_ZONA_IVA_EMPRESA_FACTURA, ESREGIMENESPECIALAGRIC' +
        'OLA_EMPRESA_FACTURA = :ESREGIMENESPECIALAGRICOLA_EMPRESA_FACTURA' +
        ', CODIGO_CLIENTE_FACTURA = :CODIGO_CLIENTE_FACTURA, RAZONSOCIAL_' +
        'CLIENTE_FACTURA = :RAZONSOCIAL_CLIENTE_FACTURA, NIF_CLIENTE_FACT' +
        'URA = :NIF_CLIENTE_FACTURA, MOVIL_CLIENTE_FACTURA = :MOVIL_CLIEN' +
        'TE_FACTURA, EMAIL_CLIENTE_FACTURA = :EMAIL_CLIENTE_FACTURA, DIRE' +
        'CCION1_CLIENTE_FACTURA = :DIRECCION1_CLIENTE_FACTURA, DIRECCION2' +
        '_CLIENTE_FACTURA = :DIRECCION2_CLIENTE_FACTURA, POBLACION_CLIENT' +
        'E_FACTURA = :POBLACION_CLIENTE_FACTURA, PROVINCIA_CLIENTE_FACTUR' +
        'A = :PROVINCIA_CLIENTE_FACTURA, CPOSTAL_CLIENTE_FACTURA = :CPOST' +
        'AL_CLIENTE_FACTURA, CODIGO_PAIS_CLIENTE_FACTURA = :CODIGO_PAIS_C' +
        'LIENTE_FACTURA, NOMBRE_PAIS_CLIENTE_FACTURA = :NOMBRE_PAIS_CLIEN' +
        'TE_FACTURA, CODIGO_IVA_FACTURA = :CODIGO_IVA_FACTURA, ESIVA_RECA' +
        'RGO_CLIENTE_FACTURA = :ESIVA_RECARGO_CLIENTE_FACTURA, ESIVA_EXEN' +
        'TO_CLIENTE_FACTURA = :ESIVA_EXENTO_CLIENTE_FACTURA, ESREGIMENESP' +
        'ECIALAGRICOLA_CLIENTE_FACTURA = :ESREGIMENESPECIALAGRICOLA_CLIEN' +
        'TE_FACTURA, ESRETENCIONES_CLIENTE_FACTURA = :ESRETENCIONES_CLIEN' +
        'TE_FACTURA, TARIFA_ARTICULO_CLIENTE_FACTURA = :TARIFA_ARTICULO_C' +
        'LIENTE_FACTURA, ESIMP_INCL_TARIFA_CLIENTE_FACTURA = :ESIMP_INCL_' +
        'TARIFA_CLIENTE_FACTURA, ESINTRACOMUNITARIO_CLIENTE_FACTURA = :ES' +
        'INTRACOMUNITARIO_CLIENTE_FACTURA, ESIRPF_IMP_INCL_ZONA_IVA_FACTU' +
        'RA = :ESIRPF_IMP_INCL_ZONA_IVA_FACTURA, ESAPLICA_RE_ZONA_IVA_FAC' +
        'TURA = :ESAPLICA_RE_ZONA_IVA_FACTURA, ESIVAAGRICOLA_ZONA_IVA_FAC' +
        'TURA = :ESIVAAGRICOLA_ZONA_IVA_FACTURA, PALABRA_REPORTS_ZONA_IVA' +
        '_FACTURA = :PALABRA_REPORTS_ZONA_IVA_FACTURA, ESVENTA_ACTIVO_FIJ' +
        'O_FACTURA = :ESVENTA_ACTIVO_FIJO_FACTURA, PORCEN_IVAN_FACTURA = ' +
        ':PORCEN_IVAN_FACTURA, TOTAL_IVAN_FACTURA = :TOTAL_IVAN_FACTURA, ' +
        'PORCEN_REN_FACTURA = :PORCEN_REN_FACTURA, TOTAL_REN_FACTURA = :T' +
        'OTAL_REN_FACTURA, TOTAL_BASEI_IVAN_FACTURA = :TOTAL_BASEI_IVAN_F' +
        'ACTURA, PORCEN_IVAR_FACTURA = :PORCEN_IVAR_FACTURA, TOTAL_IVAR_F' +
        'ACTURA = :TOTAL_IVAR_FACTURA, PORCEN_RER_FACTURA = :PORCEN_RER_F' +
        'ACTURA, TOTAL_RER_FACTURA = :TOTAL_RER_FACTURA, TOTAL_BASEI_IVAR' +
        '_FACTURA = :TOTAL_BASEI_IVAR_FACTURA, PORCEN_IVAS_FACTURA = :POR' +
        'CEN_IVAS_FACTURA, TOTAL_IVAS_FACTURA = :TOTAL_IVAS_FACTURA, PORC' +
        'EN_RES_FACTURA = :PORCEN_RES_FACTURA, TOTAL_RES_FACTURA = :TOTAL' +
        '_RES_FACTURA, TOTAL_BASEI_IVAS_FACTURA = :TOTAL_BASEI_IVAS_FACTU' +
        'RA, PORCEN_IVAE_FACTURA = :PORCEN_IVAE_FACTURA, TOTAL_IVAE_FACTU' +
        'RA = :TOTAL_IVAE_FACTURA, PORCEN_REE_FACTURA = :PORCEN_REE_FACTU' +
        'RA, TOTAL_REE_FACTURA = :TOTAL_REE_FACTURA, TOTAL_BASEI_IVAE_FAC' +
        'TURA = :TOTAL_BASEI_IVAE_FACTURA, TOTAL_BASES_FACTURA = :TOTAL_B' +
        'ASES_FACTURA, TOTAL_IMPUESTOS_FACTURA = :TOTAL_IMPUESTOS_FACTURA' +
        ', FORMA_PAGO_FACTURA = :FORMA_PAGO_FACTURA, PORCEN_RETENCION_FAC' +
        'TURA = :PORCEN_RETENCION_FACTURA, TOTAL_RETENCION_FACTURA = :TOT' +
        'AL_RETENCION_FACTURA, TOTAL_LIQUIDO_FACTURA = :TOTAL_LIQUIDO_FAC' +
        'TURA, NRO_FACTURA_ABONO_FACTURA = :NRO_FACTURA_ABONO_FACTURA, SE' +
        'RIE_FACTURA_ABONO_FACTURA = :SERIE_FACTURA_ABONO_FACTURA, TEXTO_' +
        'LEGAL_FACTURA_CLIENTE_FACTURA = :TEXTO_LEGAL_FACTURA_CLIENTE_FAC' +
        'TURA, TEXTO_LEGAL_FACTURA_EMPRESA_FACTURA = :TEXTO_LEGAL_FACTURA' +
        '_EMPRESA_FACTURA, DOCUMENTO_FACTURA = :DOCUMENTO_FACTURA, COMENT' +
        'ARIOS_FACTURA = :COMENTARIOS_FACTURA, CONTADOR_LINEAS_FACTURA = ' +
        ':CONTADOR_LINEAS_FACTURA, ESCREARARTICULOS_FACTURA = :ESCREARART' +
        'ICULOS_FACTURA, ESDESCRIPCIONES_AMP_FACTURA = :ESDESCRIPCIONES_A' +
        'MP_FACTURA, ESFECHADEENTREGA_FACTURA = :ESFECHADEENTREGA_FACTURA' +
        ', INSTANTEMODIF = :INSTANTEMODIF, INSTANTEALTA = :INSTANTEALTA, ' +
        'USUARIOALTA = :USUARIOALTA, USUARIOMODIF = :USUARIOMODIF'
      'WHERE'
      
        '  NRO_FACTURA = :Old_NRO_FACTURA AND SERIE_FACTURA = :Old_SERIE_' +
        'FACTURA')
    SQLLock.Strings = (
      
        'SELECT NRO_FACTURA, SERIE_FACTURA, FECHA_FACTURA, CODIGO_EMPRESA' +
        '_FACTURA, RAZONSOCIAL_EMPRESA_FACTURA, NIF_EMPRESA_FACTURA, MOVI' +
        'L_EMPRESA_FACTURA, EMAIL_EMPRESA_FACTURA, DIRECCION1_EMPRESA_FAC' +
        'TURA, DIRECCION2_EMPRESA_FACTURA, POBLACION_EMPRESA_FACTURA, PRO' +
        'VINCIA_EMPRESA_FACTURA, CODIGO_PAIS_EMPRESA_FACTURA, NOMBRE_PAIS' +
        '_EMPRESA_FACTURA, CPOSTAL_EMPRESA_FACTURA, ESRETENCIONES_EMPRESA' +
        '_FACTURA, GRUPO_ZONA_IVA_EMPRESA_FACTURA, ESREGIMENESPECIALAGRIC' +
        'OLA_EMPRESA_FACTURA, CODIGO_CLIENTE_FACTURA, RAZONSOCIAL_CLIENTE' +
        '_FACTURA, NIF_CLIENTE_FACTURA, MOVIL_CLIENTE_FACTURA, EMAIL_CLIE' +
        'NTE_FACTURA, DIRECCION1_CLIENTE_FACTURA, DIRECCION2_CLIENTE_FACT' +
        'URA, POBLACION_CLIENTE_FACTURA, PROVINCIA_CLIENTE_FACTURA, CPOST' +
        'AL_CLIENTE_FACTURA, CODIGO_PAIS_CLIENTE_FACTURA, NOMBRE_PAIS_CLI' +
        'ENTE_FACTURA, CODIGO_IVA_FACTURA, ESIVA_RECARGO_CLIENTE_FACTURA,' +
        ' ESIVA_EXENTO_CLIENTE_FACTURA, ESREGIMENESPECIALAGRICOLA_CLIENTE' +
        '_FACTURA, ESRETENCIONES_CLIENTE_FACTURA, TARIFA_ARTICULO_CLIENTE' +
        '_FACTURA, ESIMP_INCL_TARIFA_CLIENTE_FACTURA, ESINTRACOMUNITARIO_' +
        'CLIENTE_FACTURA, ESIRPF_IMP_INCL_ZONA_IVA_FACTURA, ESAPLICA_RE_Z' +
        'ONA_IVA_FACTURA, ESIVAAGRICOLA_ZONA_IVA_FACTURA, PALABRA_REPORTS' +
        '_ZONA_IVA_FACTURA, ESVENTA_ACTIVO_FIJO_FACTURA, PORCEN_IVAN_FACT' +
        'URA, TOTAL_IVAN_FACTURA, PORCEN_REN_FACTURA, TOTAL_REN_FACTURA, ' +
        'TOTAL_BASEI_IVAN_FACTURA, PORCEN_IVAR_FACTURA, TOTAL_IVAR_FACTUR' +
        'A, PORCEN_RER_FACTURA, TOTAL_RER_FACTURA, TOTAL_BASEI_IVAR_FACTU' +
        'RA, PORCEN_IVAS_FACTURA, TOTAL_IVAS_FACTURA, PORCEN_RES_FACTURA,' +
        ' TOTAL_RES_FACTURA, TOTAL_BASEI_IVAS_FACTURA, PORCEN_IVAE_FACTUR' +
        'A, TOTAL_IVAE_FACTURA, PORCEN_REE_FACTURA, TOTAL_REE_FACTURA, TO' +
        'TAL_BASEI_IVAE_FACTURA, TOTAL_BASES_FACTURA, TOTAL_IMPUESTOS_FAC' +
        'TURA, FORMA_PAGO_FACTURA, PORCEN_RETENCION_FACTURA, TOTAL_RETENC' +
        'ION_FACTURA, TOTAL_LIQUIDO_FACTURA, NRO_FACTURA_ABONO_FACTURA, S' +
        'ERIE_FACTURA_ABONO_FACTURA, TEXTO_LEGAL_FACTURA_CLIENTE_FACTURA,' +
        ' TEXTO_LEGAL_FACTURA_EMPRESA_FACTURA, DOCUMENTO_FACTURA, COMENTA' +
        'RIOS_FACTURA, CONTADOR_LINEAS_FACTURA, ESCREARARTICULOS_FACTURA,' +
        ' ESDESCRIPCIONES_AMP_FACTURA, ESFECHADEENTREGA_FACTURA, INSTANTE' +
        'MODIF, INSTANTEALTA, USUARIOALTA, USUARIOMODIF FROM FZA_FACTURAS'
      'WHERE'
      
        '  NRO_FACTURA = :Old_NRO_FACTURA AND SERIE_FACTURA = :Old_SERIE_' +
        'FACTURA'
      'FOR UPDATE')
    SQLRefresh.Strings = (
      
        'SELECT NRO_FACTURA, SERIE_FACTURA, FECHA_FACTURA, CODIGO_EMPRESA' +
        '_FACTURA, RAZONSOCIAL_EMPRESA_FACTURA, NIF_EMPRESA_FACTURA, MOVI' +
        'L_EMPRESA_FACTURA, EMAIL_EMPRESA_FACTURA, DIRECCION1_EMPRESA_FAC' +
        'TURA, DIRECCION2_EMPRESA_FACTURA, POBLACION_EMPRESA_FACTURA, PRO' +
        'VINCIA_EMPRESA_FACTURA, CODIGO_PAIS_EMPRESA_FACTURA, NOMBRE_PAIS' +
        '_EMPRESA_FACTURA, CPOSTAL_EMPRESA_FACTURA, ESRETENCIONES_EMPRESA' +
        '_FACTURA, GRUPO_ZONA_IVA_EMPRESA_FACTURA, ESREGIMENESPECIALAGRIC' +
        'OLA_EMPRESA_FACTURA, CODIGO_CLIENTE_FACTURA, RAZONSOCIAL_CLIENTE' +
        '_FACTURA, NIF_CLIENTE_FACTURA, MOVIL_CLIENTE_FACTURA, EMAIL_CLIE' +
        'NTE_FACTURA, DIRECCION1_CLIENTE_FACTURA, DIRECCION2_CLIENTE_FACT' +
        'URA, POBLACION_CLIENTE_FACTURA, PROVINCIA_CLIENTE_FACTURA, CPOST' +
        'AL_CLIENTE_FACTURA, CODIGO_PAIS_CLIENTE_FACTURA, NOMBRE_PAIS_CLI' +
        'ENTE_FACTURA, CODIGO_IVA_FACTURA, ESIVA_RECARGO_CLIENTE_FACTURA,' +
        ' ESIVA_EXENTO_CLIENTE_FACTURA, ESREGIMENESPECIALAGRICOLA_CLIENTE' +
        '_FACTURA, ESRETENCIONES_CLIENTE_FACTURA, TARIFA_ARTICULO_CLIENTE' +
        '_FACTURA, ESIMP_INCL_TARIFA_CLIENTE_FACTURA, ESINTRACOMUNITARIO_' +
        'CLIENTE_FACTURA, ESIRPF_IMP_INCL_ZONA_IVA_FACTURA, ESAPLICA_RE_Z' +
        'ONA_IVA_FACTURA, ESIVAAGRICOLA_ZONA_IVA_FACTURA, PALABRA_REPORTS' +
        '_ZONA_IVA_FACTURA, ESVENTA_ACTIVO_FIJO_FACTURA, PORCEN_IVAN_FACT' +
        'URA, TOTAL_IVAN_FACTURA, PORCEN_REN_FACTURA, TOTAL_REN_FACTURA, ' +
        'TOTAL_BASEI_IVAN_FACTURA, PORCEN_IVAR_FACTURA, TOTAL_IVAR_FACTUR' +
        'A, PORCEN_RER_FACTURA, TOTAL_RER_FACTURA, TOTAL_BASEI_IVAR_FACTU' +
        'RA, PORCEN_IVAS_FACTURA, TOTAL_IVAS_FACTURA, PORCEN_RES_FACTURA,' +
        ' TOTAL_RES_FACTURA, TOTAL_BASEI_IVAS_FACTURA, PORCEN_IVAE_FACTUR' +
        'A, TOTAL_IVAE_FACTURA, PORCEN_REE_FACTURA, TOTAL_REE_FACTURA, TO' +
        'TAL_BASEI_IVAE_FACTURA, TOTAL_BASES_FACTURA, TOTAL_IMPUESTOS_FAC' +
        'TURA, FORMA_PAGO_FACTURA, PORCEN_RETENCION_FACTURA, TOTAL_RETENC' +
        'ION_FACTURA, TOTAL_LIQUIDO_FACTURA, NRO_FACTURA_ABONO_FACTURA, S' +
        'ERIE_FACTURA_ABONO_FACTURA, TEXTO_LEGAL_FACTURA_CLIENTE_FACTURA,' +
        ' TEXTO_LEGAL_FACTURA_EMPRESA_FACTURA, DOCUMENTO_FACTURA, COMENTA' +
        'RIOS_FACTURA, CONTADOR_LINEAS_FACTURA, ESCREARARTICULOS_FACTURA,' +
        ' ESDESCRIPCIONES_AMP_FACTURA, ESFECHADEENTREGA_FACTURA, INSTANTE' +
        'MODIF, INSTANTEALTA, USUARIOALTA, USUARIOMODIF FROM FZA_FACTURAS'
      'WHERE'
      '  NRO_FACTURA = :NRO_FACTURA AND SERIE_FACTURA = :SERIE_FACTURA')
    SQLRecCount.Strings = (
      'SELECT COUNT(*) FROM FZA_FACTURAS')
    Connection = dmConn.conUni
    SQL.Strings = (
      'select * from vi_fac_busquedas')
    MasterFields = 'CODIGO_CLIENTE'
    DetailFields = 'CODIGO_CLIENTE_FACTURA'
    ReadOnly = True
    Left = 408
    Top = 96
  end
  object dsFacturasLineasClientes: TDataSource
    DataSet = unqryFacturasLineasClientes
    Left = 544
    Top = 32
  end
  object unqryFacturasLineasClientes: TUniQuery
    SQLInsert.Strings = (
      'INSERT INTO FZA_FACTURAS_LINEAS'
      
        '  (NRO_FACTURA_LINEA, SERIE_FACTURA_LINEA, LINEA_FACTURA_LINEA, ' +
        'CODIGO_ARTICULO_FACTURA_LINEA, CODIGO_FAMILIA_FACTURA_LINEA, NOM' +
        'BRE_FAMILIA_FACTURA_LINEA, PRECIO_ULT_COMPRA_FACTURA_LINEA, CODI' +
        'GO_PROVEEDOR_FACTURA_LINEA, RAZONSOCIAL_PROVEEDOR_FACTURA_LINEA,' +
        ' ESPROVEEDORPRINCIPAL_FACTURA_LINEA, FECHA_ENTREGA_FACTURA_LINEA' +
        ', TIPO_CANTIDAD_ARTICULO_FACTURA_LINEA, ESIMP_INCL_TARIFA_FACTUR' +
        'A_LINEA, TIPOIVA_ARTICULO_FACTURA_LINEA, DESCRIPCION_ARTICULO_FA' +
        'CTURA_LINEA, CODIGO_TARIFA_FACTURA_LINEA, CANTIDAD_FACTURA_LINEA' +
        ', PRECIOSALIDA_FACTURA_LINEA, PORCEN_DTO_FACTURA_LINEA, PRECIO_D' +
        'TO_FACTURA_LINEA, PRECIOVENTA_SIVA_ARTICULO_FACTURA_LINEA, PORCE' +
        'N_IVA_FACTURA_LINEA, PRECIOVENTA_CIVA_ARTICULO_FACTURA_LINEA, TO' +
        'TAL_FACTURA_LINEA, TOTAL_FACTURASIVA_LINEA, INSTANTEMODIF, INSTA' +
        'NTEALTA, USUARIOALTA, USUARIOMODIF)'
      'VALUES'
      
        '  (:NRO_FACTURA_LINEA, :SERIE_FACTURA_LINEA, :LINEA_FACTURA_LINE' +
        'A, :CODIGO_ARTICULO_FACTURA_LINEA, :CODIGO_FAMILIA_FACTURA_LINEA' +
        ', :NOMBRE_FAMILIA_FACTURA_LINEA, :PRECIO_ULT_COMPRA_FACTURA_LINE' +
        'A, :CODIGO_PROVEEDOR_FACTURA_LINEA, :RAZONSOCIAL_PROVEEDOR_FACTU' +
        'RA_LINEA, :ESPROVEEDORPRINCIPAL_FACTURA_LINEA, :FECHA_ENTREGA_FA' +
        'CTURA_LINEA, :TIPO_CANTIDAD_ARTICULO_FACTURA_LINEA, :ESIMP_INCL_' +
        'TARIFA_FACTURA_LINEA, :TIPOIVA_ARTICULO_FACTURA_LINEA, :DESCRIPC' +
        'ION_ARTICULO_FACTURA_LINEA, :CODIGO_TARIFA_FACTURA_LINEA, :CANTI' +
        'DAD_FACTURA_LINEA, :PRECIOSALIDA_FACTURA_LINEA, :PORCEN_DTO_FACT' +
        'URA_LINEA, :PRECIO_DTO_FACTURA_LINEA, :PRECIOVENTA_SIVA_ARTICULO' +
        '_FACTURA_LINEA, :PORCEN_IVA_FACTURA_LINEA, :PRECIOVENTA_CIVA_ART' +
        'ICULO_FACTURA_LINEA, :TOTAL_FACTURA_LINEA, :TOTAL_FACTURASIVA_LI' +
        'NEA, :INSTANTEMODIF, :INSTANTEALTA, :USUARIOALTA, :USUARIOMODIF)')
    SQLDelete.Strings = (
      'DELETE FROM FZA_FACTURAS_LINEAS'
      'WHERE'
      
        '  NRO_FACTURA_LINEA = :Old_NRO_FACTURA_LINEA AND SERIE_FACTURA_L' +
        'INEA = :Old_SERIE_FACTURA_LINEA AND LINEA_FACTURA_LINEA = :Old_L' +
        'INEA_FACTURA_LINEA')
    SQLUpdate.Strings = (
      'UPDATE FZA_FACTURAS_LINEAS'
      'SET'
      
        '  NRO_FACTURA_LINEA = :NRO_FACTURA_LINEA, SERIE_FACTURA_LINEA = ' +
        ':SERIE_FACTURA_LINEA, LINEA_FACTURA_LINEA = :LINEA_FACTURA_LINEA' +
        ', CODIGO_ARTICULO_FACTURA_LINEA = :CODIGO_ARTICULO_FACTURA_LINEA' +
        ', CODIGO_FAMILIA_FACTURA_LINEA = :CODIGO_FAMILIA_FACTURA_LINEA, ' +
        'NOMBRE_FAMILIA_FACTURA_LINEA = :NOMBRE_FAMILIA_FACTURA_LINEA, PR' +
        'ECIO_ULT_COMPRA_FACTURA_LINEA = :PRECIO_ULT_COMPRA_FACTURA_LINEA' +
        ', CODIGO_PROVEEDOR_FACTURA_LINEA = :CODIGO_PROVEEDOR_FACTURA_LIN' +
        'EA, RAZONSOCIAL_PROVEEDOR_FACTURA_LINEA = :RAZONSOCIAL_PROVEEDOR' +
        '_FACTURA_LINEA, ESPROVEEDORPRINCIPAL_FACTURA_LINEA = :ESPROVEEDO' +
        'RPRINCIPAL_FACTURA_LINEA, FECHA_ENTREGA_FACTURA_LINEA = :FECHA_E' +
        'NTREGA_FACTURA_LINEA, TIPO_CANTIDAD_ARTICULO_FACTURA_LINEA = :TI' +
        'PO_CANTIDAD_ARTICULO_FACTURA_LINEA, ESIMP_INCL_TARIFA_FACTURA_LI' +
        'NEA = :ESIMP_INCL_TARIFA_FACTURA_LINEA, TIPOIVA_ARTICULO_FACTURA' +
        '_LINEA = :TIPOIVA_ARTICULO_FACTURA_LINEA, DESCRIPCION_ARTICULO_F' +
        'ACTURA_LINEA = :DESCRIPCION_ARTICULO_FACTURA_LINEA, CODIGO_TARIF' +
        'A_FACTURA_LINEA = :CODIGO_TARIFA_FACTURA_LINEA, CANTIDAD_FACTURA' +
        '_LINEA = :CANTIDAD_FACTURA_LINEA, PRECIOSALIDA_FACTURA_LINEA = :' +
        'PRECIOSALIDA_FACTURA_LINEA, PORCEN_DTO_FACTURA_LINEA = :PORCEN_D' +
        'TO_FACTURA_LINEA, PRECIO_DTO_FACTURA_LINEA = :PRECIO_DTO_FACTURA' +
        '_LINEA, PRECIOVENTA_SIVA_ARTICULO_FACTURA_LINEA = :PRECIOVENTA_S' +
        'IVA_ARTICULO_FACTURA_LINEA, PORCEN_IVA_FACTURA_LINEA = :PORCEN_I' +
        'VA_FACTURA_LINEA, PRECIOVENTA_CIVA_ARTICULO_FACTURA_LINEA = :PRE' +
        'CIOVENTA_CIVA_ARTICULO_FACTURA_LINEA, TOTAL_FACTURA_LINEA = :TOT' +
        'AL_FACTURA_LINEA, TOTAL_FACTURASIVA_LINEA = :TOTAL_FACTURASIVA_L' +
        'INEA, INSTANTEMODIF = :INSTANTEMODIF, INSTANTEALTA = :INSTANTEAL' +
        'TA, USUARIOALTA = :USUARIOALTA, USUARIOMODIF = :USUARIOMODIF'
      'WHERE'
      
        '  NRO_FACTURA_LINEA = :Old_NRO_FACTURA_LINEA AND SERIE_FACTURA_L' +
        'INEA = :Old_SERIE_FACTURA_LINEA AND LINEA_FACTURA_LINEA = :Old_L' +
        'INEA_FACTURA_LINEA')
    SQLLock.Strings = (
      
        'SELECT NRO_FACTURA_LINEA, SERIE_FACTURA_LINEA, LINEA_FACTURA_LIN' +
        'EA, CODIGO_ARTICULO_FACTURA_LINEA, CODIGO_FAMILIA_FACTURA_LINEA,' +
        ' NOMBRE_FAMILIA_FACTURA_LINEA, PRECIO_ULT_COMPRA_FACTURA_LINEA, ' +
        'CODIGO_PROVEEDOR_FACTURA_LINEA, RAZONSOCIAL_PROVEEDOR_FACTURA_LI' +
        'NEA, ESPROVEEDORPRINCIPAL_FACTURA_LINEA, FECHA_ENTREGA_FACTURA_L' +
        'INEA, TIPO_CANTIDAD_ARTICULO_FACTURA_LINEA, ESIMP_INCL_TARIFA_FA' +
        'CTURA_LINEA, TIPOIVA_ARTICULO_FACTURA_LINEA, DESCRIPCION_ARTICUL' +
        'O_FACTURA_LINEA, CODIGO_TARIFA_FACTURA_LINEA, CANTIDAD_FACTURA_L' +
        'INEA, PRECIOSALIDA_FACTURA_LINEA, PORCEN_DTO_FACTURA_LINEA, PREC' +
        'IO_DTO_FACTURA_LINEA, PRECIOVENTA_SIVA_ARTICULO_FACTURA_LINEA, P' +
        'ORCEN_IVA_FACTURA_LINEA, PRECIOVENTA_CIVA_ARTICULO_FACTURA_LINEA' +
        ', TOTAL_FACTURA_LINEA, TOTAL_FACTURASIVA_LINEA, INSTANTEMODIF, I' +
        'NSTANTEALTA, USUARIOALTA, USUARIOMODIF FROM FZA_FACTURAS_LINEAS'
      'WHERE'
      
        '  NRO_FACTURA_LINEA = :Old_NRO_FACTURA_LINEA AND SERIE_FACTURA_L' +
        'INEA = :Old_SERIE_FACTURA_LINEA AND LINEA_FACTURA_LINEA = :Old_L' +
        'INEA_FACTURA_LINEA'
      'FOR UPDATE')
    SQLRefresh.Strings = (
      
        'SELECT NRO_FACTURA_LINEA, SERIE_FACTURA_LINEA, LINEA_FACTURA_LIN' +
        'EA, CODIGO_ARTICULO_FACTURA_LINEA, CODIGO_FAMILIA_FACTURA_LINEA,' +
        ' NOMBRE_FAMILIA_FACTURA_LINEA, PRECIO_ULT_COMPRA_FACTURA_LINEA, ' +
        'CODIGO_PROVEEDOR_FACTURA_LINEA, RAZONSOCIAL_PROVEEDOR_FACTURA_LI' +
        'NEA, ESPROVEEDORPRINCIPAL_FACTURA_LINEA, FECHA_ENTREGA_FACTURA_L' +
        'INEA, TIPO_CANTIDAD_ARTICULO_FACTURA_LINEA, ESIMP_INCL_TARIFA_FA' +
        'CTURA_LINEA, TIPOIVA_ARTICULO_FACTURA_LINEA, DESCRIPCION_ARTICUL' +
        'O_FACTURA_LINEA, CODIGO_TARIFA_FACTURA_LINEA, CANTIDAD_FACTURA_L' +
        'INEA, PRECIOSALIDA_FACTURA_LINEA, PORCEN_DTO_FACTURA_LINEA, PREC' +
        'IO_DTO_FACTURA_LINEA, PRECIOVENTA_SIVA_ARTICULO_FACTURA_LINEA, P' +
        'ORCEN_IVA_FACTURA_LINEA, PRECIOVENTA_CIVA_ARTICULO_FACTURA_LINEA' +
        ', TOTAL_FACTURA_LINEA, TOTAL_FACTURASIVA_LINEA, INSTANTEMODIF, I' +
        'NSTANTEALTA, USUARIOALTA, USUARIOMODIF FROM FZA_FACTURAS_LINEAS'
      'WHERE'
      
        '  NRO_FACTURA_LINEA = :NRO_FACTURA_LINEA AND SERIE_FACTURA_LINEA' +
        ' = :SERIE_FACTURA_LINEA AND LINEA_FACTURA_LINEA = :LINEA_FACTURA' +
        '_LINEA')
    SQLRecCount.Strings = (
      'SELECT COUNT(*) FROM FZA_FACTURAS_LINEAS')
    Connection = dmConn.conUni
    SQL.Strings = (
      'select *'
      'from vi_fac_lin_busquedas l'
      'inner join vi_fac_busquedas f'
      'on l.NRO_FACTURA_LINEA = F.NRO_FACTURA'
      'AND l.SERIE_FACTURA_LINEA = F.SERIE_FACTURA'
      '')
    MasterFields = 'CODIGO_CLIENTE'
    DetailFields = 'CODIGO_CLIENTE_FACTURA'
    ReadOnly = True
    Left = 544
    Top = 96
    ParamData = <
      item
        DataType = ftWideString
        Name = 'CODIGO_CLIENTE'
        ParamType = ptInput
        Value = 'AGRICULTOR'
      end>
  end
  object cdsEtiquetas: TClientDataSet
    Aggregates = <>
    AutoCalcFields = False
    Params = <>
    Left = 800
    Top = 24
  end
  object dtstprvEtiquetas: TDataSetProvider
    DataSet = unqryCliPrint
    Constraints = False
    Options = []
    Left = 800
    Top = 96
  end
  object unqryCliPrint: TUniQuery
    Connection = dmConn.conUni
    SQL.Strings = (
      'select * from vi_clientes')
    BeforeInsert = unqryTablaGBeforeInsert
    AfterInsert = unqryTablaGAfterInsert
    BeforePost = unqryTablaGBeforePost
    BeforeDelete = unqryTablaGBeforeDelete
    Left = 712
    Top = 32
  end
  object dsEtiquetas: TDataSource
    DataSet = unqryCliPrint
    Left = 800
    Top = 168
  end
  object fxdsEtiquetas: TfrxDBDataset
    Description = 'Etiquetas'
    UserName = 'Etiquetas'
    CloseDataSource = False
    DataSet = cdsEtiquetas
    BCDToCurrency = False
    DataSetOptions = []
    Left = 800
    Top = 232
  end
  object dsPaises: TDataSource
    DataSet = unqryPaises
    Left = 640
    Top = 32
  end
  object unqryPaises: TUniQuery
    SQLInsert.Strings = (
      'INSERT INTO fza_historia'
      
        '  (ID, CODIGO_ARTICULO, DESCRIPCION_ARTICULO, CODIGO_CLIENTE, PR' +
        'ECIOVENTA_ARTICULO, FECHA, ZONA, DESCRIPCION_HISTORIA, NRO_FACTU' +
        'RA, LINEA_LINEA, ODONTOLOGO, SERIE_FACTURA)'
      'VALUES'
      
        '  (:ID, :CODIGO_ARTICULO, :DESCRIPCION_ARTICULO, :CODIGO_CLIENTE' +
        ', :PRECIOVENTA_ARTICULO, :FECHA, :ZONA, :DESCRIPCION_HISTORIA, :' +
        'NRO_FACTURA, :LINEA_LINEA, :ODONTOLOGO, :SERIE_FACTURA)')
    SQLDelete.Strings = (
      'DELETE FROM fza_historia'
      'WHERE'
      '  ID = :Old_ID')
    SQLUpdate.Strings = (
      'UPDATE fza_historia'
      'SET'
      
        '  ID = :ID, CODIGO_ARTICULO = :CODIGO_ARTICULO, DESCRIPCION_ARTI' +
        'CULO = :DESCRIPCION_ARTICULO, CODIGO_CLIENTE = :CODIGO_CLIENTE, ' +
        'PRECIOVENTA_ARTICULO = :PRECIOVENTA_ARTICULO, FECHA = :FECHA, ZO' +
        'NA = :ZONA, DESCRIPCION_HISTORIA = :DESCRIPCION_HISTORIA, NRO_FA' +
        'CTURA = :NRO_FACTURA, LINEA_LINEA = :LINEA_LINEA, ODONTOLOGO = :' +
        'ODONTOLOGO, SERIE_FACTURA = :SERIE_FACTURA'
      'WHERE'
      '  ID = :Old_ID')
    SQLLock.Strings = (
      'SELECT * FROM fza_historia'
      'WHERE'
      '  ID = :Old_ID'
      'FOR UPDATE')
    SQLRefresh.Strings = (
      
        'SELECT ID, CODIGO_ARTICULO, DESCRIPCION_ARTICULO, CODIGO_CLIENTE' +
        ', PRECIOVENTA_ARTICULO, FECHA, ZONA, DESCRIPCION_HISTORIA, NRO_F' +
        'ACTURA, LINEA_LINEA, ODONTOLOGO, SERIE_FACTURA FROM fza_historia'
      'WHERE'
      '  ID = :ID')
    SQLRecCount.Strings = (
      'SELECT COUNT(*) FROM fza_historia')
    Connection = dmConn.conUni
    SQL.Strings = (
      'select * from vi_paises'
      '')
    ReadOnly = True
    Left = 640
    Top = 96
  end
end
