inherited dmEmpresas: TdmEmpresas
  Height = 168
  Width = 970
  PixelsPerInch = 120
  inherited unqryTablaG: TUniQuery
    SQLInsert.Strings = (
      'INSERT INTO fza_empresas'
      
        '  (CODIGO_EMPRESA, ORDEN_EMPRESA, ACTIVO_EMPRESA, RAZONSOCIAL_EM' +
        'PRESA, NIF_EMPRESA, MOVIL_EMPRESA, EMAIL_EMPRESA, DIRECCION1_EMP' +
        'RESA, DIRECCION2_EMPRESA, CPOSTAL_EMPRESA, POBLACION_EMPRESA, PR' +
        'OVINCIA_EMPRESA, CODIGO_PAIS_EMPRESA, NOMBRE_PAIS_EMPRESA, IBAN_' +
        'EMPRESA, GRUPO_ZONA_IVA_EMPRESA, ESRETENCIONES_EMPRESA, ESREGIME' +
        'NESPECIALAGRICOLA_EMPRESA, CODIGO_CERTIFICADO_EMPRESA, TITULAR_C' +
        'ERTIFICADO_EMPRESA, TIPO_CERTIFICADO_EMPRESA, FECHA_DESDE_CERTIF' +
        'ICADO_EMPRESA, FECHA_HASTA_CERTIFICADO_EMPRESA, TEXTO_LEGAL_FACT' +
        'URA_EMPRESA, INSTANTEMODIF, INSTANTEALTA, USUARIOALTA, USUARIOMO' +
        'DIF)'
      'VALUES'
      
        '  (:CODIGO_EMPRESA, :ORDEN_EMPRESA, :ACTIVO_EMPRESA, :RAZONSOCIA' +
        'L_EMPRESA, :NIF_EMPRESA, :MOVIL_EMPRESA, :EMAIL_EMPRESA, :DIRECC' +
        'ION1_EMPRESA, :DIRECCION2_EMPRESA, :CPOSTAL_EMPRESA, :POBLACION_' +
        'EMPRESA, :PROVINCIA_EMPRESA, :CODIGO_PAIS_EMPRESA, :NOMBRE_PAIS_' +
        'EMPRESA, :IBAN_EMPRESA, :GRUPO_ZONA_IVA_EMPRESA, :ESRETENCIONES_' +
        'EMPRESA, :ESREGIMENESPECIALAGRICOLA_EMPRESA, :CODIGO_CERTIFICADO' +
        '_EMPRESA, :TITULAR_CERTIFICADO_EMPRESA, :TIPO_CERTIFICADO_EMPRES' +
        'A, :FECHA_DESDE_CERTIFICADO_EMPRESA, :FECHA_HASTA_CERTIFICADO_EM' +
        'PRESA, :TEXTO_LEGAL_FACTURA_EMPRESA, :INSTANTEMODIF, :INSTANTEAL' +
        'TA, :USUARIOALTA, :USUARIOMODIF)')
    SQLDelete.Strings = (
      'DELETE FROM fza_empresas'
      'WHERE'
      '  CODIGO_EMPRESA = :Old_CODIGO_EMPRESA')
    SQLUpdate.Strings = (
      'UPDATE fza_empresas'
      'SET'
      
        '  CODIGO_EMPRESA = :CODIGO_EMPRESA, ORDEN_EMPRESA = :ORDEN_EMPRE' +
        'SA, ACTIVO_EMPRESA = :ACTIVO_EMPRESA, RAZONSOCIAL_EMPRESA = :RAZ' +
        'ONSOCIAL_EMPRESA, NIF_EMPRESA = :NIF_EMPRESA, MOVIL_EMPRESA = :M' +
        'OVIL_EMPRESA, EMAIL_EMPRESA = :EMAIL_EMPRESA, DIRECCION1_EMPRESA' +
        ' = :DIRECCION1_EMPRESA, DIRECCION2_EMPRESA = :DIRECCION2_EMPRESA' +
        ', CPOSTAL_EMPRESA = :CPOSTAL_EMPRESA, POBLACION_EMPRESA = :POBLA' +
        'CION_EMPRESA, PROVINCIA_EMPRESA = :PROVINCIA_EMPRESA, CODIGO_PAI' +
        'S_EMPRESA = :CODIGO_PAIS_EMPRESA, NOMBRE_PAIS_EMPRESA = :NOMBRE_' +
        'PAIS_EMPRESA, IBAN_EMPRESA = :IBAN_EMPRESA, GRUPO_ZONA_IVA_EMPRE' +
        'SA = :GRUPO_ZONA_IVA_EMPRESA, ESRETENCIONES_EMPRESA = :ESRETENCI' +
        'ONES_EMPRESA, ESREGIMENESPECIALAGRICOLA_EMPRESA = :ESREGIMENESPE' +
        'CIALAGRICOLA_EMPRESA, CODIGO_CERTIFICADO_EMPRESA = :CODIGO_CERTI' +
        'FICADO_EMPRESA, TITULAR_CERTIFICADO_EMPRESA = :TITULAR_CERTIFICA' +
        'DO_EMPRESA, TIPO_CERTIFICADO_EMPRESA = :TIPO_CERTIFICADO_EMPRESA' +
        ', FECHA_DESDE_CERTIFICADO_EMPRESA = :FECHA_DESDE_CERTIFICADO_EMP' +
        'RESA, FECHA_HASTA_CERTIFICADO_EMPRESA = :FECHA_HASTA_CERTIFICADO' +
        '_EMPRESA, TEXTO_LEGAL_FACTURA_EMPRESA = :TEXTO_LEGAL_FACTURA_EMP' +
        'RESA, INSTANTEMODIF = :INSTANTEMODIF, INSTANTEALTA = :INSTANTEAL' +
        'TA, USUARIOALTA = :USUARIOALTA, USUARIOMODIF = :USUARIOMODIF'
      'WHERE'
      '  CODIGO_EMPRESA = :Old_CODIGO_EMPRESA')
    SQLLock.Strings = (
      
        'SELECT CODIGO_EMPRESA, ORDEN_EMPRESA, ACTIVO_EMPRESA, RAZONSOCIA' +
        'L_EMPRESA, NIF_EMPRESA, MOVIL_EMPRESA, EMAIL_EMPRESA, DIRECCION1' +
        '_EMPRESA, DIRECCION2_EMPRESA, CPOSTAL_EMPRESA, POBLACION_EMPRESA' +
        ', PROVINCIA_EMPRESA, CODIGO_PAIS_EMPRESA, NOMBRE_PAIS_EMPRESA, I' +
        'BAN_EMPRESA, GRUPO_ZONA_IVA_EMPRESA, ESRETENCIONES_EMPRESA, ESRE' +
        'GIMENESPECIALAGRICOLA_EMPRESA, CODIGO_CERTIFICADO_EMPRESA, TITUL' +
        'AR_CERTIFICADO_EMPRESA, TIPO_CERTIFICADO_EMPRESA, FECHA_DESDE_CE' +
        'RTIFICADO_EMPRESA, FECHA_HASTA_CERTIFICADO_EMPRESA, TEXTO_LEGAL_' +
        'FACTURA_EMPRESA, INSTANTEMODIF, INSTANTEALTA, USUARIOALTA, USUAR' +
        'IOMODIF FROM fza_empresas'
      'WHERE'
      '  CODIGO_EMPRESA = :Old_CODIGO_EMPRESA'
      'FOR UPDATE')
    SQLRefresh.Strings = (
      
        'SELECT CODIGO_EMPRESA, ORDEN_EMPRESA, ACTIVO_EMPRESA, RAZONSOCIA' +
        'L_EMPRESA, NIF_EMPRESA, MOVIL_EMPRESA, EMAIL_EMPRESA, DIRECCION1' +
        '_EMPRESA, DIRECCION2_EMPRESA, CPOSTAL_EMPRESA, POBLACION_EMPRESA' +
        ', PROVINCIA_EMPRESA, CODIGO_PAIS_EMPRESA, NOMBRE_PAIS_EMPRESA, I' +
        'BAN_EMPRESA, GRUPO_ZONA_IVA_EMPRESA, ESRETENCIONES_EMPRESA, ESRE' +
        'GIMENESPECIALAGRICOLA_EMPRESA, CODIGO_CERTIFICADO_EMPRESA, TITUL' +
        'AR_CERTIFICADO_EMPRESA, TIPO_CERTIFICADO_EMPRESA, FECHA_DESDE_CE' +
        'RTIFICADO_EMPRESA, FECHA_HASTA_CERTIFICADO_EMPRESA, TEXTO_LEGAL_' +
        'FACTURA_EMPRESA, INSTANTEMODIF, INSTANTEALTA, USUARIOALTA, USUAR' +
        'IOMODIF FROM fza_empresas'
      'WHERE'
      '  CODIGO_EMPRESA = :CODIGO_EMPRESA')
    SQLRecCount.Strings = (
      'SELECT COUNT(*) FROM fza_empresas')
    Connection = dmConn.conUni
    SQL.Strings = (
      'SELECT *  '
      '  FROM vi_empresas '
      ' ORDER BY orden_empresa')
    AfterInsert = unqryTablaGAfterInsert
    BeforeDelete = unqryTablaGBeforeDelete
    AfterDelete = unqryTablaGAfterDelete
  end
  inherited unqryPerfiles: TUniQuery
    SQL.Strings = (
      'select *'
      'from fza_usuarios_perfiles'
      'where (KEY_PERFILES = '#39'dmEmpresas'#39' '
      'OR KEY_PERFILES='#39'frmMtoEmpresas'#39')')
  end
  object unqryRetenciones: TUniQuery
    SQLInsert.Strings = (
      'INSERT INTO fza_empresas_retenciones'
      
        '  (CODIGO_RETENCION, CODIGO_EMPRESA_RETENCION, PORCENRETENCION_R' +
        'ETENCION, FECHA_DESDE_RETENCION, FECHA_HASTA_RETENCION, INSTANTE' +
        'MODIF, INSTANTEALTA, USUARIOALTA, USUARIOMODIF)'
      'VALUES'
      
        '  (:CODIGO_RETENCION, :CODIGO_EMPRESA_RETENCION, :PORCENRETENCIO' +
        'N_RETENCION, :FECHA_DESDE_RETENCION, :FECHA_HASTA_RETENCION, :IN' +
        'STANTEMODIF, :INSTANTEALTA, :USUARIOALTA, :USUARIOMODIF)')
    SQLDelete.Strings = (
      'DELETE FROM fza_empresas_retenciones'
      'WHERE'
      '  CODIGO_RETENCION = :Old_CODIGO_RETENCION')
    SQLUpdate.Strings = (
      'UPDATE fza_empresas_retenciones'
      'SET'
      
        '  CODIGO_RETENCION = :CODIGO_RETENCION, CODIGO_EMPRESA_RETENCION' +
        ' = :CODIGO_EMPRESA_RETENCION, PORCENRETENCION_RETENCION = :PORCE' +
        'NRETENCION_RETENCION, FECHA_DESDE_RETENCION = :FECHA_DESDE_RETEN' +
        'CION, FECHA_HASTA_RETENCION = :FECHA_HASTA_RETENCION, INSTANTEMO' +
        'DIF = :INSTANTEMODIF, INSTANTEALTA = :INSTANTEALTA, USUARIOALTA ' +
        '= :USUARIOALTA, USUARIOMODIF = :USUARIOMODIF'
      'WHERE'
      '  CODIGO_RETENCION = :Old_CODIGO_RETENCION')
    SQLLock.Strings = (
      'SELECT * FROM fza_empresas_retenciones'
      'WHERE'
      '  CODIGO_RETENCION = :Old_CODIGO_RETENCION'
      'FOR UPDATE')
    SQLRefresh.Strings = (
      
        'SELECT CODIGO_RETENCION, CODIGO_EMPRESA_RETENCION, PORCENRETENCI' +
        'ON_RETENCION, FECHA_DESDE_RETENCION, FECHA_HASTA_RETENCION, INST' +
        'ANTEMODIF, INSTANTEALTA, USUARIOALTA, USUARIOMODIF FROM fza_empr' +
        'esas_retenciones'
      'WHERE'
      '  CODIGO_RETENCION = :CODIGO_RETENCION')
    SQLRecCount.Strings = (
      'SELECT COUNT(*) FROM fza_empresas_retenciones')
    Connection = dmConn.conUni
    SQL.Strings = (
      'SELECT * '
      'FROM vi_empresas_retenciones'
      'WHERE CODIGO_EMPRESA_RETENCION = :CODIGO_EMPRESA')
    MasterFields = 'CODIGO_EMPRESA'
    DetailFields = 'CODIGO_EMPRESA_RETENCION'
    RefreshOptions = [roAfterUpdate]
    BeforeInsert = unqryRetencionesBeforeInsert
    AfterInsert = unqryRetencionesAfterInsert
    BeforePost = unqryRetencionesBeforePost
    Left = 176
    Top = 24
    ParamData = <
      item
        DataType = ftWideString
        Name = 'CODIGO_EMPRESA'
        ParamType = ptInput
        Value = '007'
      end>
  end
  object dsRetenciones: TDataSource
    DataSet = unqryRetenciones
    Left = 176
    Top = 80
  end
  object unqryIvas: TUniQuery
    Connection = dmConn.conUni
    SQL.Strings = (
      'SELECT * '
      'FROM VI_IVAS_GRUPOS'
      '')
    DetailFields = 'GRUPO_ZONA_IVA'
    AfterInsert = unqryRetencionesAfterInsert
    BeforePost = unqryRetencionesBeforePost
    Left = 384
    Top = 24
  end
  object dsIvas: TDataSource
    DataSet = unqryIvas
    Left = 384
    Top = 80
  end
  object dsFacturasEmpresas: TDataSource
    DataSet = unqryFacturasEmpresas
    Left = 480
    Top = 80
  end
  object unqryFacturasEmpresas: TUniQuery
    SQLInsert.Strings = (
      'INSERT INTO fza_facturas'
      
        '  (NRO_FACTURA, SERIE_FACTURA, FECHA_FACTURA, CODIGO_EMPRESA_FAC' +
        'TURA, RAZONSOCIAL_EMPRESA_FACTURA, NIF_EMPRESA_FACTURA, MOVIL_EM' +
        'PRESA_FACTURA, EMAIL_EMPRESA_FACTURA, DIRECCION1_EMPRESA_FACTURA' +
        ', DIRECCION2_EMPRESA_FACTURA, POBLACION_EMPRESA_FACTURA, PROVINC' +
        'IA_EMPRESA_FACTURA, CODIGO_PAIS_EMPRESA_FACTURA, NOMBRE_PAIS_EMP' +
        'RESA_FACTURA, CPOSTAL_EMPRESA_FACTURA, ESRETENCIONES_EMPRESA_FAC' +
        'TURA, GRUPO_ZONA_IVA_EMPRESA_FACTURA, ESREGIMENESPECIALAGRICOLA_' +
        'EMPRESA_FACTURA, CODIGO_CLIENTE_FACTURA, RAZONSOCIAL_CLIENTE_FAC' +
        'TURA, NIF_CLIENTE_FACTURA, MOVIL_CLIENTE_FACTURA, EMAIL_CLIENTE_' +
        'FACTURA, DIRECCION1_CLIENTE_FACTURA, DIRECCION2_CLIENTE_FACTURA,' +
        ' POBLACION_CLIENTE_FACTURA, PROVINCIA_CLIENTE_FACTURA, CPOSTAL_C' +
        'LIENTE_FACTURA, CODIGO_PAIS_CLIENTE_FACTURA, NOMBRE_PAIS_CLIENTE' +
        '_FACTURA, CODIGO_IVA_FACTURA, ESIVA_RECARGO_CLIENTE_FACTURA, ESI' +
        'VA_EXENTO_CLIENTE_FACTURA, ESREGIMENESPECIALAGRICOLA_CLIENTE_FAC' +
        'TURA, ESRETENCIONES_CLIENTE_FACTURA, TARIFA_ARTICULO_CLIENTE_FAC' +
        'TURA, ESIMP_INCL_TARIFA_CLIENTE_FACTURA, ESINTRACOMUNITARIO_CLIE' +
        'NTE_FACTURA, ESIRPF_IMP_INCL_ZONA_IVA_FACTURA, ESAPLICA_RE_ZONA_' +
        'IVA_FACTURA, ESIVAAGRICOLA_ZONA_IVA_FACTURA, PALABRA_REPORTS_ZON' +
        'A_IVA_FACTURA, ESVENTA_ACTIVO_FIJO_FACTURA, PORCEN_IVAN_FACTURA,' +
        ' TOTAL_IVAN_FACTURA, PORCEN_REN_FACTURA, TOTAL_REN_FACTURA, TOTA' +
        'L_BASEI_IVAN_FACTURA, PORCEN_IVAR_FACTURA, TOTAL_IVAR_FACTURA, P' +
        'ORCEN_RER_FACTURA, TOTAL_RER_FACTURA, TOTAL_BASEI_IVAR_FACTURA, ' +
        'PORCEN_IVAS_FACTURA, TOTAL_IVAS_FACTURA, PORCEN_RES_FACTURA, TOT' +
        'AL_RES_FACTURA, TOTAL_BASEI_IVAS_FACTURA, PORCEN_IVAE_FACTURA, T' +
        'OTAL_IVAE_FACTURA, PORCEN_REE_FACTURA, TOTAL_REE_FACTURA, TOTAL_' +
        'BASEI_IVAE_FACTURA, TOTAL_BASES_FACTURA, TOTAL_IMPUESTOS_FACTURA' +
        ', FORMA_PAGO_FACTURA, PORCEN_RETENCION_FACTURA, TOTAL_RETENCION_' +
        'FACTURA, TOTAL_LIQUIDO_FACTURA, NRO_FACTURA_ABONO_FACTURA, SERIE' +
        '_FACTURA_ABONO_FACTURA, TEXTO_LEGAL_FACTURA_CLIENTE_FACTURA, TEX' +
        'TO_LEGAL_FACTURA_EMPRESA_FACTURA, DOCUMENTO_FACTURA, COMENTARIOS' +
        '_FACTURA, CONTADOR_LINEAS_FACTURA, ESCREARARTICULOS_FACTURA, ESD' +
        'ESCRIPCIONES_AMP_FACTURA, ESFECHADEENTREGA_FACTURA, INSTANTEMODI' +
        'F, INSTANTEALTA, USUARIOALTA, USUARIOMODIF)'
      'VALUES'
      
        '  (:NRO_FACTURA, :SERIE_FACTURA, :FECHA_FACTURA, :CODIGO_EMPRESA' +
        '_FACTURA, :RAZONSOCIAL_EMPRESA_FACTURA, :NIF_EMPRESA_FACTURA, :M' +
        'OVIL_EMPRESA_FACTURA, :EMAIL_EMPRESA_FACTURA, :DIRECCION1_EMPRES' +
        'A_FACTURA, :DIRECCION2_EMPRESA_FACTURA, :POBLACION_EMPRESA_FACTU' +
        'RA, :PROVINCIA_EMPRESA_FACTURA, :CODIGO_PAIS_EMPRESA_FACTURA, :N' +
        'OMBRE_PAIS_EMPRESA_FACTURA, :CPOSTAL_EMPRESA_FACTURA, :ESRETENCI' +
        'ONES_EMPRESA_FACTURA, :GRUPO_ZONA_IVA_EMPRESA_FACTURA, :ESREGIME' +
        'NESPECIALAGRICOLA_EMPRESA_FACTURA, :CODIGO_CLIENTE_FACTURA, :RAZ' +
        'ONSOCIAL_CLIENTE_FACTURA, :NIF_CLIENTE_FACTURA, :MOVIL_CLIENTE_F' +
        'ACTURA, :EMAIL_CLIENTE_FACTURA, :DIRECCION1_CLIENTE_FACTURA, :DI' +
        'RECCION2_CLIENTE_FACTURA, :POBLACION_CLIENTE_FACTURA, :PROVINCIA' +
        '_CLIENTE_FACTURA, :CPOSTAL_CLIENTE_FACTURA, :CODIGO_PAIS_CLIENTE' +
        '_FACTURA, :NOMBRE_PAIS_CLIENTE_FACTURA, :CODIGO_IVA_FACTURA, :ES' +
        'IVA_RECARGO_CLIENTE_FACTURA, :ESIVA_EXENTO_CLIENTE_FACTURA, :ESR' +
        'EGIMENESPECIALAGRICOLA_CLIENTE_FACTURA, :ESRETENCIONES_CLIENTE_F' +
        'ACTURA, :TARIFA_ARTICULO_CLIENTE_FACTURA, :ESIMP_INCL_TARIFA_CLI' +
        'ENTE_FACTURA, :ESINTRACOMUNITARIO_CLIENTE_FACTURA, :ESIRPF_IMP_I' +
        'NCL_ZONA_IVA_FACTURA, :ESAPLICA_RE_ZONA_IVA_FACTURA, :ESIVAAGRIC' +
        'OLA_ZONA_IVA_FACTURA, :PALABRA_REPORTS_ZONA_IVA_FACTURA, :ESVENT' +
        'A_ACTIVO_FIJO_FACTURA, :PORCEN_IVAN_FACTURA, :TOTAL_IVAN_FACTURA' +
        ', :PORCEN_REN_FACTURA, :TOTAL_REN_FACTURA, :TOTAL_BASEI_IVAN_FAC' +
        'TURA, :PORCEN_IVAR_FACTURA, :TOTAL_IVAR_FACTURA, :PORCEN_RER_FAC' +
        'TURA, :TOTAL_RER_FACTURA, :TOTAL_BASEI_IVAR_FACTURA, :PORCEN_IVA' +
        'S_FACTURA, :TOTAL_IVAS_FACTURA, :PORCEN_RES_FACTURA, :TOTAL_RES_' +
        'FACTURA, :TOTAL_BASEI_IVAS_FACTURA, :PORCEN_IVAE_FACTURA, :TOTAL' +
        '_IVAE_FACTURA, :PORCEN_REE_FACTURA, :TOTAL_REE_FACTURA, :TOTAL_B' +
        'ASEI_IVAE_FACTURA, :TOTAL_BASES_FACTURA, :TOTAL_IMPUESTOS_FACTUR' +
        'A, :FORMA_PAGO_FACTURA, :PORCEN_RETENCION_FACTURA, :TOTAL_RETENC' +
        'ION_FACTURA, :TOTAL_LIQUIDO_FACTURA, :NRO_FACTURA_ABONO_FACTURA,' +
        ' :SERIE_FACTURA_ABONO_FACTURA, :TEXTO_LEGAL_FACTURA_CLIENTE_FACT' +
        'URA, :TEXTO_LEGAL_FACTURA_EMPRESA_FACTURA, :DOCUMENTO_FACTURA, :' +
        'COMENTARIOS_FACTURA, :CONTADOR_LINEAS_FACTURA, :ESCREARARTICULOS' +
        '_FACTURA, :ESDESCRIPCIONES_AMP_FACTURA, :ESFECHADEENTREGA_FACTUR' +
        'A, :INSTANTEMODIF, :INSTANTEALTA, :USUARIOALTA, :USUARIOMODIF)')
    SQLDelete.Strings = (
      'DELETE FROM fza_facturas'
      'WHERE'
      
        '  NRO_FACTURA = :Old_NRO_FACTURA AND SERIE_FACTURA = :Old_SERIE_' +
        'FACTURA')
    SQLUpdate.Strings = (
      'UPDATE fza_facturas'
      'SET'
      
        '  NRO_FACTURA = :NRO_FACTURA, SERIE_FACTURA = :SERIE_FACTURA, FE' +
        'CHA_FACTURA = :FECHA_FACTURA, CODIGO_EMPRESA_FACTURA = :CODIGO_E' +
        'MPRESA_FACTURA, RAZONSOCIAL_EMPRESA_FACTURA = :RAZONSOCIAL_EMPRE' +
        'SA_FACTURA, NIF_EMPRESA_FACTURA = :NIF_EMPRESA_FACTURA, MOVIL_EM' +
        'PRESA_FACTURA = :MOVIL_EMPRESA_FACTURA, EMAIL_EMPRESA_FACTURA = ' +
        ':EMAIL_EMPRESA_FACTURA, DIRECCION1_EMPRESA_FACTURA = :DIRECCION1' +
        '_EMPRESA_FACTURA, DIRECCION2_EMPRESA_FACTURA = :DIRECCION2_EMPRE' +
        'SA_FACTURA, POBLACION_EMPRESA_FACTURA = :POBLACION_EMPRESA_FACTU' +
        'RA, PROVINCIA_EMPRESA_FACTURA = :PROVINCIA_EMPRESA_FACTURA, CODI' +
        'GO_PAIS_EMPRESA_FACTURA = :CODIGO_PAIS_EMPRESA_FACTURA, NOMBRE_P' +
        'AIS_EMPRESA_FACTURA = :NOMBRE_PAIS_EMPRESA_FACTURA, CPOSTAL_EMPR' +
        'ESA_FACTURA = :CPOSTAL_EMPRESA_FACTURA, ESRETENCIONES_EMPRESA_FA' +
        'CTURA = :ESRETENCIONES_EMPRESA_FACTURA, GRUPO_ZONA_IVA_EMPRESA_F' +
        'ACTURA = :GRUPO_ZONA_IVA_EMPRESA_FACTURA, ESREGIMENESPECIALAGRIC' +
        'OLA_EMPRESA_FACTURA = :ESREGIMENESPECIALAGRICOLA_EMPRESA_FACTURA' +
        ', CODIGO_CLIENTE_FACTURA = :CODIGO_CLIENTE_FACTURA, RAZONSOCIAL_' +
        'CLIENTE_FACTURA = :RAZONSOCIAL_CLIENTE_FACTURA, NIF_CLIENTE_FACT' +
        'URA = :NIF_CLIENTE_FACTURA, MOVIL_CLIENTE_FACTURA = :MOVIL_CLIEN' +
        'TE_FACTURA, EMAIL_CLIENTE_FACTURA = :EMAIL_CLIENTE_FACTURA, DIRE' +
        'CCION1_CLIENTE_FACTURA = :DIRECCION1_CLIENTE_FACTURA, DIRECCION2' +
        '_CLIENTE_FACTURA = :DIRECCION2_CLIENTE_FACTURA, POBLACION_CLIENT' +
        'E_FACTURA = :POBLACION_CLIENTE_FACTURA, PROVINCIA_CLIENTE_FACTUR' +
        'A = :PROVINCIA_CLIENTE_FACTURA, CPOSTAL_CLIENTE_FACTURA = :CPOST' +
        'AL_CLIENTE_FACTURA, CODIGO_PAIS_CLIENTE_FACTURA = :CODIGO_PAIS_C' +
        'LIENTE_FACTURA, NOMBRE_PAIS_CLIENTE_FACTURA = :NOMBRE_PAIS_CLIEN' +
        'TE_FACTURA, CODIGO_IVA_FACTURA = :CODIGO_IVA_FACTURA, ESIVA_RECA' +
        'RGO_CLIENTE_FACTURA = :ESIVA_RECARGO_CLIENTE_FACTURA, ESIVA_EXEN' +
        'TO_CLIENTE_FACTURA = :ESIVA_EXENTO_CLIENTE_FACTURA, ESREGIMENESP' +
        'ECIALAGRICOLA_CLIENTE_FACTURA = :ESREGIMENESPECIALAGRICOLA_CLIEN' +
        'TE_FACTURA, ESRETENCIONES_CLIENTE_FACTURA = :ESRETENCIONES_CLIEN' +
        'TE_FACTURA, TARIFA_ARTICULO_CLIENTE_FACTURA = :TARIFA_ARTICULO_C' +
        'LIENTE_FACTURA, ESIMP_INCL_TARIFA_CLIENTE_FACTURA = :ESIMP_INCL_' +
        'TARIFA_CLIENTE_FACTURA, ESINTRACOMUNITARIO_CLIENTE_FACTURA = :ES' +
        'INTRACOMUNITARIO_CLIENTE_FACTURA, ESIRPF_IMP_INCL_ZONA_IVA_FACTU' +
        'RA = :ESIRPF_IMP_INCL_ZONA_IVA_FACTURA, ESAPLICA_RE_ZONA_IVA_FAC' +
        'TURA = :ESAPLICA_RE_ZONA_IVA_FACTURA, ESIVAAGRICOLA_ZONA_IVA_FAC' +
        'TURA = :ESIVAAGRICOLA_ZONA_IVA_FACTURA, PALABRA_REPORTS_ZONA_IVA' +
        '_FACTURA = :PALABRA_REPORTS_ZONA_IVA_FACTURA, ESVENTA_ACTIVO_FIJ' +
        'O_FACTURA = :ESVENTA_ACTIVO_FIJO_FACTURA, PORCEN_IVAN_FACTURA = ' +
        ':PORCEN_IVAN_FACTURA, TOTAL_IVAN_FACTURA = :TOTAL_IVAN_FACTURA, ' +
        'PORCEN_REN_FACTURA = :PORCEN_REN_FACTURA, TOTAL_REN_FACTURA = :T' +
        'OTAL_REN_FACTURA, TOTAL_BASEI_IVAN_FACTURA = :TOTAL_BASEI_IVAN_F' +
        'ACTURA, PORCEN_IVAR_FACTURA = :PORCEN_IVAR_FACTURA, TOTAL_IVAR_F' +
        'ACTURA = :TOTAL_IVAR_FACTURA, PORCEN_RER_FACTURA = :PORCEN_RER_F' +
        'ACTURA, TOTAL_RER_FACTURA = :TOTAL_RER_FACTURA, TOTAL_BASEI_IVAR' +
        '_FACTURA = :TOTAL_BASEI_IVAR_FACTURA, PORCEN_IVAS_FACTURA = :POR' +
        'CEN_IVAS_FACTURA, TOTAL_IVAS_FACTURA = :TOTAL_IVAS_FACTURA, PORC' +
        'EN_RES_FACTURA = :PORCEN_RES_FACTURA, TOTAL_RES_FACTURA = :TOTAL' +
        '_RES_FACTURA, TOTAL_BASEI_IVAS_FACTURA = :TOTAL_BASEI_IVAS_FACTU' +
        'RA, PORCEN_IVAE_FACTURA = :PORCEN_IVAE_FACTURA, TOTAL_IVAE_FACTU' +
        'RA = :TOTAL_IVAE_FACTURA, PORCEN_REE_FACTURA = :PORCEN_REE_FACTU' +
        'RA, TOTAL_REE_FACTURA = :TOTAL_REE_FACTURA, TOTAL_BASEI_IVAE_FAC' +
        'TURA = :TOTAL_BASEI_IVAE_FACTURA, TOTAL_BASES_FACTURA = :TOTAL_B' +
        'ASES_FACTURA, TOTAL_IMPUESTOS_FACTURA = :TOTAL_IMPUESTOS_FACTURA' +
        ', FORMA_PAGO_FACTURA = :FORMA_PAGO_FACTURA, PORCEN_RETENCION_FAC' +
        'TURA = :PORCEN_RETENCION_FACTURA, TOTAL_RETENCION_FACTURA = :TOT' +
        'AL_RETENCION_FACTURA, TOTAL_LIQUIDO_FACTURA = :TOTAL_LIQUIDO_FAC' +
        'TURA, NRO_FACTURA_ABONO_FACTURA = :NRO_FACTURA_ABONO_FACTURA, SE' +
        'RIE_FACTURA_ABONO_FACTURA = :SERIE_FACTURA_ABONO_FACTURA, TEXTO_' +
        'LEGAL_FACTURA_CLIENTE_FACTURA = :TEXTO_LEGAL_FACTURA_CLIENTE_FAC' +
        'TURA, TEXTO_LEGAL_FACTURA_EMPRESA_FACTURA = :TEXTO_LEGAL_FACTURA' +
        '_EMPRESA_FACTURA, DOCUMENTO_FACTURA = :DOCUMENTO_FACTURA, COMENT' +
        'ARIOS_FACTURA = :COMENTARIOS_FACTURA, CONTADOR_LINEAS_FACTURA = ' +
        ':CONTADOR_LINEAS_FACTURA, ESCREARARTICULOS_FACTURA = :ESCREARART' +
        'ICULOS_FACTURA, ESDESCRIPCIONES_AMP_FACTURA = :ESDESCRIPCIONES_A' +
        'MP_FACTURA, ESFECHADEENTREGA_FACTURA = :ESFECHADEENTREGA_FACTURA' +
        ', INSTANTEMODIF = :INSTANTEMODIF, INSTANTEALTA = :INSTANTEALTA, ' +
        'USUARIOALTA = :USUARIOALTA, USUARIOMODIF = :USUARIOMODIF'
      'WHERE'
      
        '  NRO_FACTURA = :Old_NRO_FACTURA AND SERIE_FACTURA = :Old_SERIE_' +
        'FACTURA')
    SQLLock.Strings = (
      
        'SELECT NRO_FACTURA, SERIE_FACTURA, FECHA_FACTURA, CODIGO_EMPRESA' +
        '_FACTURA, RAZONSOCIAL_EMPRESA_FACTURA, NIF_EMPRESA_FACTURA, MOVI' +
        'L_EMPRESA_FACTURA, EMAIL_EMPRESA_FACTURA, DIRECCION1_EMPRESA_FAC' +
        'TURA, DIRECCION2_EMPRESA_FACTURA, POBLACION_EMPRESA_FACTURA, PRO' +
        'VINCIA_EMPRESA_FACTURA, CODIGO_PAIS_EMPRESA_FACTURA, NOMBRE_PAIS' +
        '_EMPRESA_FACTURA, CPOSTAL_EMPRESA_FACTURA, ESRETENCIONES_EMPRESA' +
        '_FACTURA, GRUPO_ZONA_IVA_EMPRESA_FACTURA, ESREGIMENESPECIALAGRIC' +
        'OLA_EMPRESA_FACTURA, CODIGO_CLIENTE_FACTURA, RAZONSOCIAL_CLIENTE' +
        '_FACTURA, NIF_CLIENTE_FACTURA, MOVIL_CLIENTE_FACTURA, EMAIL_CLIE' +
        'NTE_FACTURA, DIRECCION1_CLIENTE_FACTURA, DIRECCION2_CLIENTE_FACT' +
        'URA, POBLACION_CLIENTE_FACTURA, PROVINCIA_CLIENTE_FACTURA, CPOST' +
        'AL_CLIENTE_FACTURA, CODIGO_PAIS_CLIENTE_FACTURA, NOMBRE_PAIS_CLI' +
        'ENTE_FACTURA, CODIGO_IVA_FACTURA, ESIVA_RECARGO_CLIENTE_FACTURA,' +
        ' ESIVA_EXENTO_CLIENTE_FACTURA, ESREGIMENESPECIALAGRICOLA_CLIENTE' +
        '_FACTURA, ESRETENCIONES_CLIENTE_FACTURA, TARIFA_ARTICULO_CLIENTE' +
        '_FACTURA, ESIMP_INCL_TARIFA_CLIENTE_FACTURA, ESINTRACOMUNITARIO_' +
        'CLIENTE_FACTURA, ESIRPF_IMP_INCL_ZONA_IVA_FACTURA, ESAPLICA_RE_Z' +
        'ONA_IVA_FACTURA, ESIVAAGRICOLA_ZONA_IVA_FACTURA, PALABRA_REPORTS' +
        '_ZONA_IVA_FACTURA, ESVENTA_ACTIVO_FIJO_FACTURA, PORCEN_IVAN_FACT' +
        'URA, TOTAL_IVAN_FACTURA, PORCEN_REN_FACTURA, TOTAL_REN_FACTURA, ' +
        'TOTAL_BASEI_IVAN_FACTURA, PORCEN_IVAR_FACTURA, TOTAL_IVAR_FACTUR' +
        'A, PORCEN_RER_FACTURA, TOTAL_RER_FACTURA, TOTAL_BASEI_IVAR_FACTU' +
        'RA, PORCEN_IVAS_FACTURA, TOTAL_IVAS_FACTURA, PORCEN_RES_FACTURA,' +
        ' TOTAL_RES_FACTURA, TOTAL_BASEI_IVAS_FACTURA, PORCEN_IVAE_FACTUR' +
        'A, TOTAL_IVAE_FACTURA, PORCEN_REE_FACTURA, TOTAL_REE_FACTURA, TO' +
        'TAL_BASEI_IVAE_FACTURA, TOTAL_BASES_FACTURA, TOTAL_IMPUESTOS_FAC' +
        'TURA, FORMA_PAGO_FACTURA, PORCEN_RETENCION_FACTURA, TOTAL_RETENC' +
        'ION_FACTURA, TOTAL_LIQUIDO_FACTURA, NRO_FACTURA_ABONO_FACTURA, S' +
        'ERIE_FACTURA_ABONO_FACTURA, TEXTO_LEGAL_FACTURA_CLIENTE_FACTURA,' +
        ' TEXTO_LEGAL_FACTURA_EMPRESA_FACTURA, DOCUMENTO_FACTURA, COMENTA' +
        'RIOS_FACTURA, CONTADOR_LINEAS_FACTURA, ESCREARARTICULOS_FACTURA,' +
        ' ESDESCRIPCIONES_AMP_FACTURA, ESFECHADEENTREGA_FACTURA, INSTANTE' +
        'MODIF, INSTANTEALTA, USUARIOALTA, USUARIOMODIF FROM fza_facturas'
      'WHERE'
      
        '  NRO_FACTURA = :Old_NRO_FACTURA AND SERIE_FACTURA = :Old_SERIE_' +
        'FACTURA'
      'FOR UPDATE')
    SQLRefresh.Strings = (
      
        'SELECT NRO_FACTURA, SERIE_FACTURA, FECHA_FACTURA, CODIGO_EMPRESA' +
        '_FACTURA, RAZONSOCIAL_EMPRESA_FACTURA, NIF_EMPRESA_FACTURA, MOVI' +
        'L_EMPRESA_FACTURA, EMAIL_EMPRESA_FACTURA, DIRECCION1_EMPRESA_FAC' +
        'TURA, DIRECCION2_EMPRESA_FACTURA, POBLACION_EMPRESA_FACTURA, PRO' +
        'VINCIA_EMPRESA_FACTURA, CODIGO_PAIS_EMPRESA_FACTURA, NOMBRE_PAIS' +
        '_EMPRESA_FACTURA, CPOSTAL_EMPRESA_FACTURA, ESRETENCIONES_EMPRESA' +
        '_FACTURA, GRUPO_ZONA_IVA_EMPRESA_FACTURA, ESREGIMENESPECIALAGRIC' +
        'OLA_EMPRESA_FACTURA, CODIGO_CLIENTE_FACTURA, RAZONSOCIAL_CLIENTE' +
        '_FACTURA, NIF_CLIENTE_FACTURA, MOVIL_CLIENTE_FACTURA, EMAIL_CLIE' +
        'NTE_FACTURA, DIRECCION1_CLIENTE_FACTURA, DIRECCION2_CLIENTE_FACT' +
        'URA, POBLACION_CLIENTE_FACTURA, PROVINCIA_CLIENTE_FACTURA, CPOST' +
        'AL_CLIENTE_FACTURA, CODIGO_PAIS_CLIENTE_FACTURA, NOMBRE_PAIS_CLI' +
        'ENTE_FACTURA, CODIGO_IVA_FACTURA, ESIVA_RECARGO_CLIENTE_FACTURA,' +
        ' ESIVA_EXENTO_CLIENTE_FACTURA, ESREGIMENESPECIALAGRICOLA_CLIENTE' +
        '_FACTURA, ESRETENCIONES_CLIENTE_FACTURA, TARIFA_ARTICULO_CLIENTE' +
        '_FACTURA, ESIMP_INCL_TARIFA_CLIENTE_FACTURA, ESINTRACOMUNITARIO_' +
        'CLIENTE_FACTURA, ESIRPF_IMP_INCL_ZONA_IVA_FACTURA, ESAPLICA_RE_Z' +
        'ONA_IVA_FACTURA, ESIVAAGRICOLA_ZONA_IVA_FACTURA, PALABRA_REPORTS' +
        '_ZONA_IVA_FACTURA, ESVENTA_ACTIVO_FIJO_FACTURA, PORCEN_IVAN_FACT' +
        'URA, TOTAL_IVAN_FACTURA, PORCEN_REN_FACTURA, TOTAL_REN_FACTURA, ' +
        'TOTAL_BASEI_IVAN_FACTURA, PORCEN_IVAR_FACTURA, TOTAL_IVAR_FACTUR' +
        'A, PORCEN_RER_FACTURA, TOTAL_RER_FACTURA, TOTAL_BASEI_IVAR_FACTU' +
        'RA, PORCEN_IVAS_FACTURA, TOTAL_IVAS_FACTURA, PORCEN_RES_FACTURA,' +
        ' TOTAL_RES_FACTURA, TOTAL_BASEI_IVAS_FACTURA, PORCEN_IVAE_FACTUR' +
        'A, TOTAL_IVAE_FACTURA, PORCEN_REE_FACTURA, TOTAL_REE_FACTURA, TO' +
        'TAL_BASEI_IVAE_FACTURA, TOTAL_BASES_FACTURA, TOTAL_IMPUESTOS_FAC' +
        'TURA, FORMA_PAGO_FACTURA, PORCEN_RETENCION_FACTURA, TOTAL_RETENC' +
        'ION_FACTURA, TOTAL_LIQUIDO_FACTURA, NRO_FACTURA_ABONO_FACTURA, S' +
        'ERIE_FACTURA_ABONO_FACTURA, TEXTO_LEGAL_FACTURA_CLIENTE_FACTURA,' +
        ' TEXTO_LEGAL_FACTURA_EMPRESA_FACTURA, DOCUMENTO_FACTURA, COMENTA' +
        'RIOS_FACTURA, CONTADOR_LINEAS_FACTURA, ESCREARARTICULOS_FACTURA,' +
        ' ESDESCRIPCIONES_AMP_FACTURA, ESFECHADEENTREGA_FACTURA, INSTANTE' +
        'MODIF, INSTANTEALTA, USUARIOALTA, USUARIOMODIF FROM fza_facturas'
      'WHERE'
      '  NRO_FACTURA = :NRO_FACTURA AND SERIE_FACTURA = :SERIE_FACTURA')
    SQLRecCount.Strings = (
      'SELECT COUNT(*) FROM fza_facturas')
    Connection = dmConn.conUni
    SQL.Strings = (
      'select * from vi_fac_busquedas')
    MasterFields = 'CODIGO_EMPRESA'
    DetailFields = 'CODIGO_EMPRESA_FACTURA'
    ReadOnly = True
    Left = 480
    Top = 24
    ParamData = <
      item
        DataType = ftWideString
        Name = 'CODIGO_EMPRESA'
        ParamType = ptInput
        Value = '007'
      end>
  end
  object dsFacturasLineasEmpresas: TDataSource
    DataSet = unqryFacturasLineasEmpresas
    Left = 625
    Top = 80
  end
  object unqryFacturasLineasEmpresas: TUniQuery
    SQLInsert.Strings = (
      'INSERT INTO fza_facturas_lineas'
      
        '  (NRO_FACTURA_LINEA, SERIE_FACTURA_LINEA, LINEA_FACTURA_LINEA, ' +
        'CODIGO_ARTICULO_FACTURA_LINEA, CODIGO_FAMILIA_FACTURA_LINEA, NOM' +
        'BRE_FAMILIA_FACTURA_LINEA, PRECIO_ULT_COMPRA_FACTURA_LINEA, CODI' +
        'GO_PROVEEDOR_FACTURA_LINEA, RAZONSOCIAL_PROVEEDOR_FACTURA_LINEA,' +
        ' ESPROVEEDORPRINCIPAL_FACTURA_LINEA, FECHA_ENTREGA_FACTURA_LINEA' +
        ', TIPO_CANTIDAD_ARTICULO_FACTURA_LINEA, ESIMP_INCL_TARIFA_FACTUR' +
        'A_LINEA, TIPOIVA_ARTICULO_FACTURA_LINEA, DESCRIPCION_ARTICULO_FA' +
        'CTURA_LINEA, CODIGO_TARIFA_FACTURA_LINEA, CANTIDAD_FACTURA_LINEA' +
        ', PRECIOSALIDA_FACTURA_LINEA, PORCEN_DTO_FACTURA_LINEA, PRECIO_D' +
        'TO_FACTURA_LINEA, PRECIOVENTA_SIVA_ARTICULO_FACTURA_LINEA, PORCE' +
        'N_IVA_FACTURA_LINEA, PRECIOVENTA_CIVA_ARTICULO_FACTURA_LINEA, TO' +
        'TAL_FACTURA_LINEA, TOTAL_FACTURASIVA_LINEA, INSTANTEMODIF, INSTA' +
        'NTEALTA, USUARIOALTA, USUARIOMODIF)'
      'VALUES'
      
        '  (:NRO_FACTURA_LINEA, :SERIE_FACTURA_LINEA, :LINEA_FACTURA_LINE' +
        'A, :CODIGO_ARTICULO_FACTURA_LINEA, :CODIGO_FAMILIA_FACTURA_LINEA' +
        ', :NOMBRE_FAMILIA_FACTURA_LINEA, :PRECIO_ULT_COMPRA_FACTURA_LINE' +
        'A, :CODIGO_PROVEEDOR_FACTURA_LINEA, :RAZONSOCIAL_PROVEEDOR_FACTU' +
        'RA_LINEA, :ESPROVEEDORPRINCIPAL_FACTURA_LINEA, :FECHA_ENTREGA_FA' +
        'CTURA_LINEA, :TIPO_CANTIDAD_ARTICULO_FACTURA_LINEA, :ESIMP_INCL_' +
        'TARIFA_FACTURA_LINEA, :TIPOIVA_ARTICULO_FACTURA_LINEA, :DESCRIPC' +
        'ION_ARTICULO_FACTURA_LINEA, :CODIGO_TARIFA_FACTURA_LINEA, :CANTI' +
        'DAD_FACTURA_LINEA, :PRECIOSALIDA_FACTURA_LINEA, :PORCEN_DTO_FACT' +
        'URA_LINEA, :PRECIO_DTO_FACTURA_LINEA, :PRECIOVENTA_SIVA_ARTICULO' +
        '_FACTURA_LINEA, :PORCEN_IVA_FACTURA_LINEA, :PRECIOVENTA_CIVA_ART' +
        'ICULO_FACTURA_LINEA, :TOTAL_FACTURA_LINEA, :TOTAL_FACTURASIVA_LI' +
        'NEA, :INSTANTEMODIF, :INSTANTEALTA, :USUARIOALTA, :USUARIOMODIF)')
    SQLDelete.Strings = (
      'DELETE FROM fza_facturas_lineas'
      'WHERE'
      
        '  NRO_FACTURA_LINEA = :Old_NRO_FACTURA_LINEA AND SERIE_FACTURA_L' +
        'INEA = :Old_SERIE_FACTURA_LINEA AND LINEA_FACTURA_LINEA = :Old_L' +
        'INEA_FACTURA_LINEA')
    SQLUpdate.Strings = (
      'UPDATE fza_facturas_lineas'
      'SET'
      
        '  NRO_FACTURA_LINEA = :NRO_FACTURA_LINEA, SERIE_FACTURA_LINEA = ' +
        ':SERIE_FACTURA_LINEA, LINEA_FACTURA_LINEA = :LINEA_FACTURA_LINEA' +
        ', CODIGO_ARTICULO_FACTURA_LINEA = :CODIGO_ARTICULO_FACTURA_LINEA' +
        ', CODIGO_FAMILIA_FACTURA_LINEA = :CODIGO_FAMILIA_FACTURA_LINEA, ' +
        'NOMBRE_FAMILIA_FACTURA_LINEA = :NOMBRE_FAMILIA_FACTURA_LINEA, PR' +
        'ECIO_ULT_COMPRA_FACTURA_LINEA = :PRECIO_ULT_COMPRA_FACTURA_LINEA' +
        ', CODIGO_PROVEEDOR_FACTURA_LINEA = :CODIGO_PROVEEDOR_FACTURA_LIN' +
        'EA, RAZONSOCIAL_PROVEEDOR_FACTURA_LINEA = :RAZONSOCIAL_PROVEEDOR' +
        '_FACTURA_LINEA, ESPROVEEDORPRINCIPAL_FACTURA_LINEA = :ESPROVEEDO' +
        'RPRINCIPAL_FACTURA_LINEA, FECHA_ENTREGA_FACTURA_LINEA = :FECHA_E' +
        'NTREGA_FACTURA_LINEA, TIPO_CANTIDAD_ARTICULO_FACTURA_LINEA = :TI' +
        'PO_CANTIDAD_ARTICULO_FACTURA_LINEA, ESIMP_INCL_TARIFA_FACTURA_LI' +
        'NEA = :ESIMP_INCL_TARIFA_FACTURA_LINEA, TIPOIVA_ARTICULO_FACTURA' +
        '_LINEA = :TIPOIVA_ARTICULO_FACTURA_LINEA, DESCRIPCION_ARTICULO_F' +
        'ACTURA_LINEA = :DESCRIPCION_ARTICULO_FACTURA_LINEA, CODIGO_TARIF' +
        'A_FACTURA_LINEA = :CODIGO_TARIFA_FACTURA_LINEA, CANTIDAD_FACTURA' +
        '_LINEA = :CANTIDAD_FACTURA_LINEA, PRECIOSALIDA_FACTURA_LINEA = :' +
        'PRECIOSALIDA_FACTURA_LINEA, PORCEN_DTO_FACTURA_LINEA = :PORCEN_D' +
        'TO_FACTURA_LINEA, PRECIO_DTO_FACTURA_LINEA = :PRECIO_DTO_FACTURA' +
        '_LINEA, PRECIOVENTA_SIVA_ARTICULO_FACTURA_LINEA = :PRECIOVENTA_S' +
        'IVA_ARTICULO_FACTURA_LINEA, PORCEN_IVA_FACTURA_LINEA = :PORCEN_I' +
        'VA_FACTURA_LINEA, PRECIOVENTA_CIVA_ARTICULO_FACTURA_LINEA = :PRE' +
        'CIOVENTA_CIVA_ARTICULO_FACTURA_LINEA, TOTAL_FACTURA_LINEA = :TOT' +
        'AL_FACTURA_LINEA, TOTAL_FACTURASIVA_LINEA = :TOTAL_FACTURASIVA_L' +
        'INEA, INSTANTEMODIF = :INSTANTEMODIF, INSTANTEALTA = :INSTANTEAL' +
        'TA, USUARIOALTA = :USUARIOALTA, USUARIOMODIF = :USUARIOMODIF'
      'WHERE'
      
        '  NRO_FACTURA_LINEA = :Old_NRO_FACTURA_LINEA AND SERIE_FACTURA_L' +
        'INEA = :Old_SERIE_FACTURA_LINEA AND LINEA_FACTURA_LINEA = :Old_L' +
        'INEA_FACTURA_LINEA')
    SQLLock.Strings = (
      
        'SELECT NRO_FACTURA_LINEA, SERIE_FACTURA_LINEA, LINEA_FACTURA_LIN' +
        'EA, CODIGO_ARTICULO_FACTURA_LINEA, CODIGO_FAMILIA_FACTURA_LINEA,' +
        ' NOMBRE_FAMILIA_FACTURA_LINEA, PRECIO_ULT_COMPRA_FACTURA_LINEA, ' +
        'CODIGO_PROVEEDOR_FACTURA_LINEA, RAZONSOCIAL_PROVEEDOR_FACTURA_LI' +
        'NEA, ESPROVEEDORPRINCIPAL_FACTURA_LINEA, FECHA_ENTREGA_FACTURA_L' +
        'INEA, TIPO_CANTIDAD_ARTICULO_FACTURA_LINEA, ESIMP_INCL_TARIFA_FA' +
        'CTURA_LINEA, TIPOIVA_ARTICULO_FACTURA_LINEA, DESCRIPCION_ARTICUL' +
        'O_FACTURA_LINEA, CODIGO_TARIFA_FACTURA_LINEA, CANTIDAD_FACTURA_L' +
        'INEA, PRECIOSALIDA_FACTURA_LINEA, PORCEN_DTO_FACTURA_LINEA, PREC' +
        'IO_DTO_FACTURA_LINEA, PRECIOVENTA_SIVA_ARTICULO_FACTURA_LINEA, P' +
        'ORCEN_IVA_FACTURA_LINEA, PRECIOVENTA_CIVA_ARTICULO_FACTURA_LINEA' +
        ', TOTAL_FACTURA_LINEA, TOTAL_FACTURASIVA_LINEA, INSTANTEMODIF, I' +
        'NSTANTEALTA, USUARIOALTA, USUARIOMODIF FROM fza_facturas_lineas'
      'WHERE'
      
        '  NRO_FACTURA_LINEA = :Old_NRO_FACTURA_LINEA AND SERIE_FACTURA_L' +
        'INEA = :Old_SERIE_FACTURA_LINEA AND LINEA_FACTURA_LINEA = :Old_L' +
        'INEA_FACTURA_LINEA'
      'FOR UPDATE')
    SQLRefresh.Strings = (
      
        'SELECT NRO_FACTURA_LINEA, SERIE_FACTURA_LINEA, LINEA_FACTURA_LIN' +
        'EA, CODIGO_ARTICULO_FACTURA_LINEA, CODIGO_FAMILIA_FACTURA_LINEA,' +
        ' NOMBRE_FAMILIA_FACTURA_LINEA, PRECIO_ULT_COMPRA_FACTURA_LINEA, ' +
        'CODIGO_PROVEEDOR_FACTURA_LINEA, RAZONSOCIAL_PROVEEDOR_FACTURA_LI' +
        'NEA, ESPROVEEDORPRINCIPAL_FACTURA_LINEA, FECHA_ENTREGA_FACTURA_L' +
        'INEA, TIPO_CANTIDAD_ARTICULO_FACTURA_LINEA, ESIMP_INCL_TARIFA_FA' +
        'CTURA_LINEA, TIPOIVA_ARTICULO_FACTURA_LINEA, DESCRIPCION_ARTICUL' +
        'O_FACTURA_LINEA, CODIGO_TARIFA_FACTURA_LINEA, CANTIDAD_FACTURA_L' +
        'INEA, PRECIOSALIDA_FACTURA_LINEA, PORCEN_DTO_FACTURA_LINEA, PREC' +
        'IO_DTO_FACTURA_LINEA, PRECIOVENTA_SIVA_ARTICULO_FACTURA_LINEA, P' +
        'ORCEN_IVA_FACTURA_LINEA, PRECIOVENTA_CIVA_ARTICULO_FACTURA_LINEA' +
        ', TOTAL_FACTURA_LINEA, TOTAL_FACTURASIVA_LINEA, INSTANTEMODIF, I' +
        'NSTANTEALTA, USUARIOALTA, USUARIOMODIF FROM fza_facturas_lineas'
      'WHERE'
      
        '  NRO_FACTURA_LINEA = :NRO_FACTURA_LINEA AND SERIE_FACTURA_LINEA' +
        ' = :SERIE_FACTURA_LINEA AND LINEA_FACTURA_LINEA = :LINEA_FACTURA' +
        '_LINEA')
    SQLRecCount.Strings = (
      'SELECT COUNT(*) FROM fza_facturas_lineas')
    Connection = dmConn.conUni
    SQL.Strings = (
      'select *'
      'from vi_fac_lin_busquedas l'
      'inner join vi_fac_busquedas f'
      'on l.NRO_FACTURA_LINEA = F.NRO_FACTURA'
      'AND l.SERIE_FACTURA_LINEA = F.SERIE_FACTURA'
      '')
    MasterFields = 'CODIGO_EMPRESA'
    DetailFields = 'CODIGO_EMPRESA_FACTURA'
    ReadOnly = True
    Left = 625
    Top = 24
    ParamData = <
      item
        DataType = ftWideString
        Name = 'CODIGO_EMPRESA'
        ParamType = ptInput
        Value = '1'
      end>
  end
  object unqrySeries: TUniQuery
    SQLInsert.Strings = (
      'INSERT INTO fza_empresas_series'
      
        '  (CODIGO_SERIE, CODIGO_EMPRESA_SERIE, SERIE_SERIE, FECHA_DESDE_' +
        'SERIE, FECHA_HASTA_SERIE, INSTANTEMODIF, INSTANTEALTA, USUARIOAL' +
        'TA, USUARIOMODIF)'
      'VALUES'
      
        '  (:CODIGO_SERIE, :CODIGO_EMPRESA_SERIE, :SERIE_SERIE, :FECHA_DE' +
        'SDE_SERIE, :FECHA_HASTA_SERIE, :INSTANTEMODIF, :INSTANTEALTA, :U' +
        'SUARIOALTA, :USUARIOMODIF)')
    SQLDelete.Strings = (
      'DELETE FROM fza_empresas_series'
      'WHERE'
      '  CODIGO_SERIE = :Old_CODIGO_SERIE')
    SQLUpdate.Strings = (
      'UPDATE fza_empresas_series'
      'SET'
      
        '  CODIGO_SERIE = :CODIGO_SERIE, CODIGO_EMPRESA_SERIE = :CODIGO_E' +
        'MPRESA_SERIE, SERIE_SERIE = :SERIE_SERIE, FECHA_DESDE_SERIE = :F' +
        'ECHA_DESDE_SERIE, FECHA_HASTA_SERIE = :FECHA_HASTA_SERIE, INSTAN' +
        'TEMODIF = :INSTANTEMODIF, INSTANTEALTA = :INSTANTEALTA, USUARIOA' +
        'LTA = :USUARIOALTA, USUARIOMODIF = :USUARIOMODIF'
      'WHERE'
      '  CODIGO_SERIE = :Old_CODIGO_SERIE')
    SQLLock.Strings = (
      'SELECT * FROM fza_empresas_series'
      'WHERE'
      '  CODIGO_SERIE = :Old_CODIGO_SERIE'
      'FOR UPDATE')
    SQLRefresh.Strings = (
      
        'SELECT CODIGO_SERIE, CODIGO_EMPRESA_SERIE, SERIE_SERIE, FECHA_DE' +
        'SDE_SERIE, FECHA_HASTA_SERIE, INSTANTEMODIF, INSTANTEALTA, USUAR' +
        'IOALTA, USUARIOMODIF FROM fza_empresas_series'
      'WHERE'
      '  CODIGO_SERIE = :CODIGO_SERIE')
    SQLRecCount.Strings = (
      'SELECT COUNT(*) FROM fza_empresas_series')
    Connection = dmConn.conUni
    SQL.Strings = (
      'SELECT * '
      'FROM vi_empresas_series'
      'WHERE CODIGO_EMPRESA_SERIE = :CODIGO_EMPRESA')
    MasterFields = 'CODIGO_EMPRESA'
    DetailFields = 'CODIGO_EMPRESA_SERIE'
    RefreshOptions = [roAfterUpdate]
    BeforeInsert = unqryRetencionesBeforeInsert
    AfterInsert = unqrySeriesAfterInsert
    BeforePost = unqrySeriesBeforePost
    Left = 272
    Top = 24
    ParamData = <
      item
        DataType = ftWideString
        Name = 'CODIGO_EMPRESA'
        ParamType = ptInput
        Value = '007'
      end>
  end
  object dsSeries: TDataSource
    DataSet = unqrySeries
    Left = 272
    Top = 80
  end
  object dsPaises: TDataSource
    DataSet = unqryPaises
    Left = 760
    Top = 24
  end
  object unqryPaises: TUniQuery
    SQLInsert.Strings = (
      'INSERT INTO fza_historia'
      
        '  (ID, CODIGO_ARTICULO, DESCRIPCION_ARTICULO, CODIGO_CLIENTE, PR' +
        'ECIOVENTA_ARTICULO, FECHA, ZONA, DESCRIPCION_HISTORIA, NRO_FACTU' +
        'RA, LINEA_LINEA, ODONTOLOGO, SERIE_FACTURA)'
      'VALUES'
      
        '  (:ID, :CODIGO_ARTICULO, :DESCRIPCION_ARTICULO, :CODIGO_CLIENTE' +
        ', :PRECIOVENTA_ARTICULO, :FECHA, :ZONA, :DESCRIPCION_HISTORIA, :' +
        'NRO_FACTURA, :LINEA_LINEA, :ODONTOLOGO, :SERIE_FACTURA)')
    SQLDelete.Strings = (
      'DELETE FROM fza_historia'
      'WHERE'
      '  ID = :Old_ID')
    SQLUpdate.Strings = (
      'UPDATE fza_historia'
      'SET'
      
        '  ID = :ID, CODIGO_ARTICULO = :CODIGO_ARTICULO, DESCRIPCION_ARTI' +
        'CULO = :DESCRIPCION_ARTICULO, CODIGO_CLIENTE = :CODIGO_CLIENTE, ' +
        'PRECIOVENTA_ARTICULO = :PRECIOVENTA_ARTICULO, FECHA = :FECHA, ZO' +
        'NA = :ZONA, DESCRIPCION_HISTORIA = :DESCRIPCION_HISTORIA, NRO_FA' +
        'CTURA = :NRO_FACTURA, LINEA_LINEA = :LINEA_LINEA, ODONTOLOGO = :' +
        'ODONTOLOGO, SERIE_FACTURA = :SERIE_FACTURA'
      'WHERE'
      '  ID = :Old_ID')
    SQLLock.Strings = (
      'SELECT * FROM fza_historia'
      'WHERE'
      '  ID = :Old_ID'
      'FOR UPDATE')
    SQLRefresh.Strings = (
      
        'SELECT ID, CODIGO_ARTICULO, DESCRIPCION_ARTICULO, CODIGO_CLIENTE' +
        ', PRECIOVENTA_ARTICULO, FECHA, ZONA, DESCRIPCION_HISTORIA, NRO_F' +
        'ACTURA, LINEA_LINEA, ODONTOLOGO, SERIE_FACTURA FROM fza_historia'
      'WHERE'
      '  ID = :ID')
    SQLRecCount.Strings = (
      'SELECT COUNT(*) FROM fza_historia')
    Connection = dmConn.conUni
    SQL.Strings = (
      'select * from vi_paises'
      '')
    ReadOnly = True
    Left = 760
    Top = 88
  end
end
