inherited dmClientes: TdmClientes
  Height = 356
  Width = 989
  PixelsPerInch = 120
  inherited unqryTablaG: TUniQuery
    SQLInsert.Strings = (
      'INSERT INTO fza_clientes'
      
        '  (CODIGO_CLI_CLI, ESACTIVO_CLI, ORDEN_CLI, RAZON_SOCIAL_CLI, NIF_CLI, MOVIL_CLI, EMAIL_CLI, DIRECCION1_CLI, DIRECCION2_CLI, POBLACION_CLI, PROVINCIA_CLI, CODIGO_POSTAL_CLI, CODIGO_PAI_CLI, NOMBRE_PAI' +
        '_CLI, OBSERVACIONES_CLI, REFERENCIA_CLI, CONTACTO_CLI, TELEFONO_CONTACTO_CLI, TELEFONO_CLI, IBAN_CLI, ESIVA_RECARGO_CLI, ESRETENCIONES_CLI, TOTAL_LIMITE_CREDITO_CLI, ESPERMITE_DEUDA_CLI, TOTAL_DEUDA_C' +
        'LI, ESIVA_EXENTO_CLI, ESINTRACOMUNITARIO_CLI, ESREGIMENESPECIALAGRICOLA_CLI, CODIGO_FP_CLI, TARIFA_ARTICULO_CLI, SERIE_CON_CLI, TEXTO_LEGAL_FACTURA_CLI, INSTANTE_MODIF, INSTANTE_ALTA, USUARIO_ALTA, US' +
        'UARIO_MODIF)'
      'VALUES'
      
        '  (:CODIGO_CLI_CLI, :ESACTIVO_CLI, :ORDEN_CLI, :RAZON_SOCIAL_CLI, :NIF_CLI, :MOVIL_CLI, :EMAIL_CLI, :DIRECCION1_CLI, :DIRECCION2_CLI, :POBLACION_CLI, :PROVINCIA_CLI, :CODIGO_POSTAL_CLI, :CODIGO_PAI_CL' +
        'I, :NOMBRE_PAI_CLI, :OBSERVACIONES_CLI, :REFERENCIA_CLI, :CONTACTO_CLI, :TELEFONO_CONTACTO_CLI, :TELEFONO_CLI, :IBAN_CLI, :ESIVA_RECARGO_CLI, :ESRETENCIONES_CLI, :TOTAL_LIMITE_CREDITO_CLI, :ESPERMITE_' +
        'DEUDA_CLI, :TOTAL_DEUDA_CLI, :ESIVA_EXENTO_CLI, :ESINTRACOMUNITARIO_CLI, :ESREGIMENESPECIALAGRICOLA_CLI, :CODIGO_FP_CLI, :TARIFA_ARTICULO_CLI, :SERIE_CON_CLI, :TEXTO_LEGAL_FACTURA_CLI, :INSTANTE_MODIF' +
        ', :INSTANTE_ALTA, :USUARIO_ALTA, :USUARIO_MODIF)')
    SQLDelete.Strings = (
      'DELETE FROM fza_clientes'
      'WHERE'
      '  CODIGO_CLI_CLI = :Old_CODIGO_CLI_CLI')
    SQLUpdate.Strings = (
      'UPDATE fza_clientes'
      'SET'
      
        '  CODIGO_CLI_CLI = :CODIGO_CLI_CLI, ESACTIVO_CLI = :ESACTIVO_CLI, ORDEN_CLI = :ORDEN_CLI, RAZON_SOCIAL_CLI = :RAZON_SOCIAL_CLI, NIF_CLI = :NIF_CLI, MOVIL_CLI = :MOVIL_CLI, EMAIL_CLI = :EMAIL_CLI, DIRE' +
        'CCION1_CLI = :DIRECCION1_CLI, DIRECCION2_CLI = :DIRECCION2_CLI, POBLACION_CLI = :POBLACION_CLI, PROVINCIA_CLI = :PROVINCIA_CLI, CODIGO_POSTAL_CLI = :CODIGO_POSTAL_CLI, CODIGO_PAI_CLI = :CODIGO_PAI_CLI' +
        ', NOMBRE_PAI_CLI = :NOMBRE_PAI_CLI, OBSERVACIONES_CLI = :OBSERVACIONES_CLI, REFERENCIA_CLI = :REFERENCIA_CLI, CONTACTO_CLI = :CONTACTO_CLI, TELEFONO_CONTACTO_CLI = :TELEFONO_CONTACTO_CLI, TELEFONO_CLI' +
        ' = :TELEFONO_CLI, IBAN_CLI = :IBAN_CLI, ESIVA_RECARGO_CLI = :ESIVA_RECARGO_CLI, ESRETENCIONES_CLI = :ESRETENCIONES_CLI, TOTAL_LIMITE_CREDITO_CLI = :TOTAL_LIMITE_CREDITO_CLI, ESPERMITE_DEUDA_CLI = :ESP' +
        'ERMITE_DEUDA_CLI, TOTAL_DEUDA_CLI = :TOTAL_DEUDA_CLI, ESIVA_EXENTO_CLI = :ESIVA_EXENTO_CLI, ESINTRACOMUNITARIO_CLI = :ESINTRACOMUNITARIO_CLI, ESREGIMENESPECIALAGRICOLA_CLI = :ESREGIMENESPECIALAGRICOLA' +
        '_CLI, CODIGO_FP_CLI = :CODIGO_FP_CLI, TARIFA_ARTICULO_CLI = :TARIFA_ARTICULO_CLI, SERIE_CON_CLI = :SERIE_CON_CLI, TEXTO_LEGAL_FACTURA_CLI = :TEXTO_LEGAL_FACTURA_CLI, INSTANTE_MODIF = :INSTANTE_MODIF, ' +
        'INSTANTE_ALTA = :INSTANTE_ALTA, USUARIO_ALTA = :USUARIO_ALTA, USUARIO_MODIF = :USUARIO_MODIF'
      'WHERE'
      '  CODIGO_CLI_CLI = :Old_CODIGO_CLI_CLI')
    SQLLock.Strings = (
      
        'SELECT CODIGO_CLI_CLI, ESACTIVO_CLI, ORDEN_CLI, RAZON_SOCIAL_CLI, NIF_CLI, MOVIL_CLI, EMAIL_CLI, DIRECCION1_CLI, DIRECCION2_CLI, POBLACION_CLI, PROVINCIA_CLI, CODIGO_POSTAL_CLI, CODIGO_PAI_CLI, NOMBRE' +
        '_PAI_CLI, OBSERVACIONES_CLI, REFERENCIA_CLI, CONTACTO_CLI, TELEFONO_CONTACTO_CLI, TELEFONO_CLI, IBAN_CLI, ESIVA_RECARGO_CLI, ESRETENCIONES_CLI, TOTAL_LIMITE_CREDITO_CLI, ESPERMITE_DEUDA_CLI, TOTAL_DEU' +
        'DA_CLI, ESIVA_EXENTO_CLI, ESINTRACOMUNITARIO_CLI, ESREGIMENESPECIALAGRICOLA_CLI, CODIGO_FP_CLI, TARIFA_ARTICULO_CLI, SERIE_CON_CLI, TEXTO_LEGAL_FACTURA_CLI, INSTANTE_MODIF, INSTANTE_ALTA, USUARIO_ALTA' +
        ', USUARIO_MODIF FROM fza_clientes'
      'WHERE'
      '  CODIGO_CLI_CLI = :Old_CODIGO_CLI_CLI'
      'FOR UPDATE')
    SQLRefresh.Strings = (
      
        'SELECT CODIGO_CLI_CLI, ESACTIVO_CLI, ORDEN_CLI, RAZON_SOCIAL_CLI, NIF_CLI, MOVIL_CLI, EMAIL_CLI, DIRECCION1_CLI, DIRECCION2_CLI, POBLACION_CLI, PROVINCIA_CLI, CODIGO_POSTAL_CLI, CODIGO_PAI_CLI, NOMBRE' +
        '_PAI_CLI, OBSERVACIONES_CLI, REFERENCIA_CLI, CONTACTO_CLI, TELEFONO_CONTACTO_CLI, TELEFONO_CLI, IBAN_CLI, ESIVA_RECARGO_CLI, ESRETENCIONES_CLI, TOTAL_LIMITE_CREDITO_CLI, ESPERMITE_DEUDA_CLI, TOTAL_DEU' +
        'DA_CLI, ESIVA_EXENTO_CLI, ESINTRACOMUNITARIO_CLI, ESREGIMENESPECIALAGRICOLA_CLI, CODIGO_FP_CLI, TARIFA_ARTICULO_CLI, SERIE_CON_CLI, TEXTO_LEGAL_FACTURA_CLI, INSTANTE_MODIF, INSTANTE_ALTA, USUARIO_ALTA' +
        ', USUARIO_MODIF FROM fza_clientes'
      'WHERE'
      '  CODIGO_CLI_CLI = :CODIGO_CLI_CLI')
    SQLRecCount.Strings = (
      'SELECT COUNT(*) FROM fza_clientes')
    Connection = dmConn.conUni
    SQL.Strings = (
      'select * from vi_clientes')
    Active = True
    AfterInsert = unqryTablaGAfterInsert
    BeforeDelete = unqryTablaGBeforeDelete
    Left = 56
    Top = 32
  end
  inherited unqryPerfiles: TUniQuery
    SQL.Strings = (
      'select *'
      'from fza_usuarios_perfiles'
      'where KEY_USUPER = '#39'Nothing'#39)
    Left = 144
    Top = 32
  end
  inherited dsPerfiles: TDataSource
    Left = 144
    Top = 88
  end
  object dsFormasPago: TDataSource
    DataSet = unqryFormaPago
    Left = 224
    Top = 32
  end
  object unqryFormaPago: TUniQuery
    SQLInsert.Strings = (
      'INSERT INTO fza_historia'
      
        '  (ID, CODIGO_ART_ART, DESCRIPCION_ART, CODIGO_CLI_CLI, PRECIOVENTA_ARTICULO, FECHA, ZONA, DESCRIPCION_HISTORIA, NUMERO_FAC, LINEA_LINEA, ODONTOLOGO, SERIE_FAC)'
      'VALUES'
      
        '  (:ID, :CODIGO_ART_ART, :DESCRIPCION_ART, :CODIGO_CLI_CLI, :PRECIOVENTA_ARTICULO, :FECHA, :ZONA, :DESCRIPCION_HISTORIA, :NUMERO_FAC, :LINEA_LINEA, :ODONTOLOGO, :SERIE_FAC)')
    SQLDelete.Strings = (
      'DELETE FROM fza_historia'
      'WHERE'
      '  ID = :Old_ID')
    SQLUpdate.Strings = (
      'UPDATE fza_historia'
      'SET'
      
        '  ID = :ID, CODIGO_ART_ART = :CODIGO_ART_ART, DESCRIPCION_ART = :DESCRIPCION_ART, CODIGO_CLI_CLI = :CODIGO_CLI_CLI, PRECIOVENTA_ARTICULO = :PRECIOVENTA_ARTICULO, FECHA = :FECHA, ZONA = :ZONA, DESCRIPC' +
        'ION_HISTORIA = :DESCRIPCION_HISTORIA, NUMERO_FAC = :NUMERO_FAC, LINEA_LINEA = :LINEA_LINEA, ODONTOLOGO = :ODONTOLOGO, SERIE_FAC = :SERIE_FAC'
      'WHERE'
      '  ID = :Old_ID')
    SQLLock.Strings = (
      'SELECT * FROM fza_historia'
      'WHERE'
      '  ID = :Old_ID'
      'FOR UPDATE')
    SQLRefresh.Strings = (
      
        'SELECT ID, CODIGO_ART_ART, DESCRIPCION_ART, CODIGO_CLI_CLI, PRECIOVENTA_ARTICULO, FECHA, ZONA, DESCRIPCION_HISTORIA, NUMERO_FAC, LINEA_LINEA, ODONTOLOGO, SERIE_FAC FROM fza_historia'
      'WHERE'
      '  ID = :ID')
    SQLRecCount.Strings = (
      'SELECT COUNT(*) FROM fza_historia')
    Connection = dmConn.conUni
    SQL.Strings = (
      'select * from vi_formapago'
      '')
    ReadOnly = True
    Left = 224
    Top = 96
  end
  object dsTarifas: TDataSource
    DataSet = unqryTarifas
    Left = 320
    Top = 32
  end
  object unqryTarifas: TUniQuery
    SQLInsert.Strings = (
      'INSERT INTO fza_historia'
      
        '  (ID, CODIGO_ART_ART, DESCRIPCION_ART, CODIGO_CLI_CLI, PRECIOVENTA_ARTICULO, FECHA, ZONA, DESCRIPCION_HISTORIA, NUMERO_FAC, LINEA_LINEA, ODONTOLOGO, SERIE_FAC)'
      'VALUES'
      
        '  (:ID, :CODIGO_ART_ART, :DESCRIPCION_ART, :CODIGO_CLI_CLI, :PRECIOVENTA_ARTICULO, :FECHA, :ZONA, :DESCRIPCION_HISTORIA, :NUMERO_FAC, :LINEA_LINEA, :ODONTOLOGO, :SERIE_FAC)')
    SQLDelete.Strings = (
      'DELETE FROM fza_historia'
      'WHERE'
      '  ID = :Old_ID')
    SQLUpdate.Strings = (
      'UPDATE fza_historia'
      'SET'
      
        '  ID = :ID, CODIGO_ART_ART = :CODIGO_ART_ART, DESCRIPCION_ART = :DESCRIPCION_ART, CODIGO_CLI_CLI = :CODIGO_CLI_CLI, PRECIOVENTA_ARTICULO = :PRECIOVENTA_ARTICULO, FECHA = :FECHA, ZONA = :ZONA, DESCRIPC' +
        'ION_HISTORIA = :DESCRIPCION_HISTORIA, NUMERO_FAC = :NUMERO_FAC, LINEA_LINEA = :LINEA_LINEA, ODONTOLOGO = :ODONTOLOGO, SERIE_FAC = :SERIE_FAC'
      'WHERE'
      '  ID = :Old_ID')
    SQLLock.Strings = (
      'SELECT * FROM fza_historia'
      'WHERE'
      '  ID = :Old_ID'
      'FOR UPDATE')
    SQLRefresh.Strings = (
      
        'SELECT ID, CODIGO_ART_ART, DESCRIPCION_ART, CODIGO_CLI_CLI, PRECIOVENTA_ARTICULO, FECHA, ZONA, DESCRIPCION_HISTORIA, NUMERO_FAC, LINEA_LINEA, ODONTOLOGO, SERIE_FAC FROM fza_historia'
      'WHERE'
      '  ID = :ID')
    SQLRecCount.Strings = (
      'SELECT COUNT(*) FROM fza_historia')
    Connection = dmConn.conUni
    SQL.Strings = (
      'select * from vi_tarifas'
      '')
    ReadOnly = True
    Left = 320
    Top = 96
  end
  object dsFacturasClientes: TDataSource
    DataSet = unqryFacturasClientes
    Left = 408
    Top = 32
  end
  object unqryFacturasClientes: TUniQuery
    SQLInsert.Strings = (
      'INSERT INTO FZA_FACTURAS'
      
        '  (NUMERO_FAC, SERIE_FAC, FECHA_FAC, CODIGO_EMP_FAC, RAZON_SOCIAL_EMPRESA_FAC, NIF_EMPRESA_FAC, MOVIL_EMPRESA_FAC, EMAIL_EMPRESA_FAC, DIRECCION1_EMPRESA_FAC, DIRECCION2_EMPRESA_FAC, POBLACION_EMPRESA_' +
        'FAC, PROVINCIA_EMPRESA_FAC, CODIGO_PAI_EMPRESA_FAC, NOMBRE_PAI_EMPRESA_FAC, CODIGO_POSTAL_EMPRESA_FAC, ESRETENCIONES_EMPRESA_FAC, GRUPO_ZONA_IVA_EMPRESA_FAC, ESREGIMENESPECIALAGRICOLA_EMPRESA_FAC, COD' +
        'IGO_CLI_FAC, RAZON_SOCIAL_CLIENTE_FAC, NIF_CLIENTE_FAC, MOVIL_CLIENTE_FAC, EMAIL_CLIENTE_FAC, DIRECCION1_CLIENTE_FAC, DIRECCION2_CLIENTE_FAC, POBLACION_CLIENTE_FAC, PROVINCIA_CLIENTE_FAC, CODIGO_POSTA' +
        'L_CLIENTE_FAC, CODIGO_PAI_CLIENTE_FAC, NOMBRE_PAI_CLIENTE_FAC, CODIGO_IVA_FAC, ESIVA_RECARGO_CLIENTE_FAC, ESIVA_EXENTO_CLIENTE_FAC, ESREGIMENESPECIALAGRICOLA_CLIENTE_FAC, ESRETENCIONES_CLIENTE_FAC, TA' +
        'RIFA_ARTICULO_CLIENTE_FAC, ESIMP_INCL_TARIFA_CLIENTE_FAC, ESINTRACOMUNITARIO_CLIENTE_FAC, ESIRPF_IMP_INCL_ZONA_IVA_FAC, ESAPLICA_RE_ZONA_IVA_FAC, ESIVAAGRICOLA_ZONA_IVA_FAC, PALABRA_REPORTS_ZONA_IVA_F' +
        'AC, ESVENTA_ACTIVO_FIJO_FAC, PORCENTAJE_IVAN_FAC, TOTAL_IVAN_FAC, PORCENTAJE_REN_FAC, TOTAL_REN_FAC, TOTAL_BASEI_IVAN_FAC, PORCENTAJE_IVAR_FAC, TOTAL_IVAR_FAC, PORCENTAJE_RER_FAC, TOTAL_RER_FAC, TOTAL' +
        '_BASEI_IVAR_FAC, PORCENTAJE_IVAS_FAC, TOTAL_IVAS_FAC, PORCENTAJE_RES_FAC, TOTAL_RES_FAC, TOTAL_BASEI_IVAS_FAC, PORCENTAJE_IVAE_FAC, TOTAL_IVAE_FAC, PORCENTAJE_REE_FAC, TOTAL_REE_FAC, TOTAL_BASEI_IVAE_' +
        'FAC, TOTAL_BASES_FAC, TOTAL_IMPUESTOS_FAC, FORMA_PAGO_FAC, PORCENTAJE_RETENCION_FAC, TOTAL_RETENCION_FAC, TOTAL_LIQUIDO_FAC, NUMERO_FAC_ABONO_FAC, SERIE_FAC_ABONO_FAC, TEXTO_LEGAL_CLIENTE_FAC, TEXTO_L' +
        'EGAL_EMPRESA_FAC, DOCUMENTO_FAC, COMENTARIOS_FAC, CONTADOR_LINEAS_FAC, ESCREARARTICULOS_FAC, ESDESCRIPCIONES_AMP_FAC, ESFECHADEENTREGA_FAC, INSTANTE_MODIF, INSTANTE_ALTA, USUARIO_ALTA, USUARIO_MODIF)'
      'VALUES'
      
        '  (:NUMERO_FAC, :SERIE_FAC, :FECHA_FAC, :CODIGO_EMP_FAC, :RAZON_SOCIAL_EMPRESA_FAC, :NIF_EMPRESA_FAC, :MOVIL_EMPRESA_FAC, :EMAIL_EMPRESA_FAC, :DIRECCION1_EMPRESA_FAC, :DIRECCION2_EMPRESA_FAC, :POBLACI' +
        'ON_EMPRESA_FAC, :PROVINCIA_EMPRESA_FAC, :CODIGO_PAI_EMPRESA_FAC, :NOMBRE_PAI_EMPRESA_FAC, :CODIGO_POSTAL_EMPRESA_FAC, :ESRETENCIONES_EMPRESA_FAC, :GRUPO_ZONA_IVA_EMPRESA_FAC, :ESREGIMENESPECIALAGRICOL' +
        'A_EMPRESA_FAC, :CODIGO_CLI_FAC, :RAZON_SOCIAL_CLIENTE_FAC, :NIF_CLIENTE_FAC, :MOVIL_CLIENTE_FAC, :EMAIL_CLIENTE_FAC, :DIRECCION1_CLIENTE_FAC, :DIRECCION2_CLIENTE_FAC, :POBLACION_CLIENTE_FAC, :PROVINCI' +
        'A_CLIENTE_FAC, :CODIGO_POSTAL_CLIENTE_FAC, :CODIGO_PAI_CLIENTE_FAC, :NOMBRE_PAI_CLIENTE_FAC, :CODIGO_IVA_FAC, :ESIVA_RECARGO_CLIENTE_FAC, :ESIVA_EXENTO_CLIENTE_FAC, :ESREGIMENESPECIALAGRICOLA_CLIENTE_' +
        'FAC, :ESRETENCIONES_CLIENTE_FAC, :TARIFA_ARTICULO_CLIENTE_FAC, :ESIMP_INCL_TARIFA_CLIENTE_FAC, :ESINTRACOMUNITARIO_CLIENTE_FAC, :ESIRPF_IMP_INCL_ZONA_IVA_FAC, :ESAPLICA_RE_ZONA_IVA_FAC, :ESIVAAGRICOLA' +
        '_ZONA_IVA_FAC, :PALABRA_REPORTS_ZONA_IVA_FAC, :ESVENTA_ACTIVO_FIJO_FAC, :PORCENTAJE_IVAN_FAC, :TOTAL_IVAN_FAC, :PORCENTAJE_REN_FAC, :TOTAL_REN_FAC, :TOTAL_BASEI_IVAN_FAC, :PORCENTAJE_IVAR_FAC, :TOTAL_' +
        'IVAR_FAC, :PORCENTAJE_RER_FAC, :TOTAL_RER_FAC, :TOTAL_BASEI_IVAR_FAC, :PORCENTAJE_IVAS_FAC, :TOTAL_IVAS_FAC, :PORCENTAJE_RES_FAC, :TOTAL_RES_FAC, :TOTAL_BASEI_IVAS_FAC, :PORCENTAJE_IVAE_FAC, :TOTAL_IV' +
        'AE_FAC, :PORCENTAJE_REE_FAC, :TOTAL_REE_FAC, :TOTAL_BASEI_IVAE_FAC, :TOTAL_BASES_FAC, :TOTAL_IMPUESTOS_FAC, :FORMA_PAGO_FAC, :PORCENTAJE_RETENCION_FAC, :TOTAL_RETENCION_FAC, :TOTAL_LIQUIDO_FAC, :NUMER' +
        'O_FAC_ABONO_FAC, :SERIE_FAC_ABONO_FAC, :TEXTO_LEGAL_CLIENTE_FAC, :TEXTO_LEGAL_EMPRESA_FAC, :DOCUMENTO_FAC, :COMENTARIOS_FAC, :CONTADOR_LINEAS_FAC, :ESCREARARTICULOS_FAC, :ESDESCRIPCIONES_AMP_FAC, :ESF' +
        'ECHADEENTREGA_FAC, :INSTANTE_MODIF, :INSTANTE_ALTA, :USUARIO_ALTA, :USUARIO_MODIF)')
    SQLDelete.Strings = (
      'DELETE FROM FZA_FACTURAS'
      'WHERE'
      
        '  NUMERO_FAC = :Old_NUMERO_FAC AND SERIE_FAC = :Old_SERIE_FAC')
    SQLUpdate.Strings = (
      'UPDATE FZA_FACTURAS'
      'SET'
      
        '  NUMERO_FAC = :NUMERO_FAC, SERIE_FAC = :SERIE_FAC, FECHA_FAC = :FECHA_FAC, CODIGO_EMP_FAC = :CODIGO_EMP_FAC, RAZON_SOCIAL_EMPRESA_FAC = :RAZON_SOCIAL_EMPRESA_FAC, NIF_EMPRESA_FAC = :NIF_EMPRESA_FAC, ' +
        'MOVIL_EMPRESA_FAC = :MOVIL_EMPRESA_FAC, EMAIL_EMPRESA_FAC = :EMAIL_EMPRESA_FAC, DIRECCION1_EMPRESA_FAC = :DIRECCION1_EMPRESA_FAC, DIRECCION2_EMPRESA_FAC = :DIRECCION2_EMPRESA_FAC, POBLACION_EMPRESA_FA' +
        'C = :POBLACION_EMPRESA_FAC, PROVINCIA_EMPRESA_FAC = :PROVINCIA_EMPRESA_FAC, CODIGO_PAI_EMPRESA_FAC = :CODIGO_PAI_EMPRESA_FAC, NOMBRE_PAI_EMPRESA_FAC = :NOMBRE_PAI_EMPRESA_FAC, CODIGO_POSTAL_EMPRESA_FA' +
        'C = :CODIGO_POSTAL_EMPRESA_FAC, ESRETENCIONES_EMPRESA_FAC = :ESRETENCIONES_EMPRESA_FAC, GRUPO_ZONA_IVA_EMPRESA_FAC = :GRUPO_ZONA_IVA_EMPRESA_FAC, ESREGIMENESPECIALAGRICOLA_EMPRESA_FAC = :ESREGIMENESPE' +
        'CIALAGRICOLA_EMPRESA_FAC, CODIGO_CLI_FAC = :CODIGO_CLI_FAC, RAZON_SOCIAL_CLIENTE_FAC = :RAZON_SOCIAL_CLIENTE_FAC, NIF_CLIENTE_FAC = :NIF_CLIENTE_FAC, MOVIL_CLIENTE_FAC = :MOVIL_CLIENTE_FAC, EMAIL_CLIE' +
        'NTE_FAC = :EMAIL_CLIENTE_FAC, DIRECCION1_CLIENTE_FAC = :DIRECCION1_CLIENTE_FAC, DIRECCION2_CLIENTE_FAC = :DIRECCION2_CLIENTE_FAC, POBLACION_CLIENTE_FAC = :POBLACION_CLIENTE_FAC, PROVINCIA_CLIENTE_FAC ' +
        '= :PROVINCIA_CLIENTE_FAC, CODIGO_POSTAL_CLIENTE_FAC = :CODIGO_POSTAL_CLIENTE_FAC, CODIGO_PAI_CLIENTE_FAC = :CODIGO_PAI_CLIENTE_FAC, NOMBRE_PAI_CLIENTE_FAC = :NOMBRE_PAI_CLIENTE_FAC, CODIGO_IVA_FAC = :' +
        'CODIGO_IVA_FAC, ESIVA_RECARGO_CLIENTE_FAC = :ESIVA_RECARGO_CLIENTE_FAC, ESIVA_EXENTO_CLIENTE_FAC = :ESIVA_EXENTO_CLIENTE_FAC, ESREGIMENESPECIALAGRICOLA_CLIENTE_FAC = :ESREGIMENESPECIALAGRICOLA_CLIENTE' +
        '_FAC, ESRETENCIONES_CLIENTE_FAC = :ESRETENCIONES_CLIENTE_FAC, TARIFA_ARTICULO_CLIENTE_FAC = :TARIFA_ARTICULO_CLIENTE_FAC, ESIMP_INCL_TARIFA_CLIENTE_FAC = :ESIMP_INCL_TARIFA_CLIENTE_FAC, ESINTRACOMUNIT' +
        'ARIO_CLIENTE_FAC = :ESINTRACOMUNITARIO_CLIENTE_FAC, ESIRPF_IMP_INCL_ZONA_IVA_FAC = :ESIRPF_IMP_INCL_ZONA_IVA_FAC, ESAPLICA_RE_ZONA_IVA_FAC = :ESAPLICA_RE_ZONA_IVA_FAC, ESIVAAGRICOLA_ZONA_IVA_FAC = :ES' +
        'IVAAGRICOLA_ZONA_IVA_FAC, PALABRA_REPORTS_ZONA_IVA_FAC = :PALABRA_REPORTS_ZONA_IVA_FAC, ESVENTA_ACTIVO_FIJO_FAC = :ESVENTA_ACTIVO_FIJO_FAC, PORCENTAJE_IVAN_FAC = :PORCENTAJE_IVAN_FAC, TOTAL_IVAN_FAC =' +
        ' :TOTAL_IVAN_FAC, PORCENTAJE_REN_FAC = :PORCENTAJE_REN_FAC, TOTAL_REN_FAC = :TOTAL_REN_FAC, TOTAL_BASEI_IVAN_FAC = :TOTAL_BASEI_IVAN_FAC, PORCENTAJE_IVAR_FAC = :PORCENTAJE_IVAR_FAC, TOTAL_IVAR_FAC = :' +
        'TOTAL_IVAR_FAC, PORCENTAJE_RER_FAC = :PORCENTAJE_RER_FAC, TOTAL_RER_FAC = :TOTAL_RER_FAC, TOTAL_BASEI_IVAR_FAC = :TOTAL_BASEI_IVAR_FAC, PORCENTAJE_IVAS_FAC = :PORCENTAJE_IVAS_FAC, TOTAL_IVAS_FAC = :TO' +
        'TAL_IVAS_FAC, PORCENTAJE_RES_FAC = :PORCENTAJE_RES_FAC, TOTAL_RES_FAC = :TOTAL_RES_FAC, TOTAL_BASEI_IVAS_FAC = :TOTAL_BASEI_IVAS_FAC, PORCENTAJE_IVAE_FAC = :PORCENTAJE_IVAE_FAC, TOTAL_IVAE_FAC = :TOTA' +
        'L_IVAE_FAC, PORCENTAJE_REE_FAC = :PORCENTAJE_REE_FAC, TOTAL_REE_FAC = :TOTAL_REE_FAC, TOTAL_BASEI_IVAE_FAC = :TOTAL_BASEI_IVAE_FAC, TOTAL_BASES_FAC = :TOTAL_BASES_FAC, TOTAL_IMPUESTOS_FAC = :TOTAL_IMP' +
        'UESTOS_FAC, FORMA_PAGO_FAC = :FORMA_PAGO_FAC, PORCENTAJE_RETENCION_FAC = :PORCENTAJE_RETENCION_FAC, TOTAL_RETENCION_FAC = :TOTAL_RETENCION_FAC, TOTAL_LIQUIDO_FAC = :TOTAL_LIQUIDO_FAC, NUMERO_FAC_ABONO' +
        '_FAC = :NUMERO_FAC_ABONO_FAC, SERIE_FAC_ABONO_FAC = :SERIE_FAC_ABONO_FAC, TEXTO_LEGAL_CLIENTE_FAC = :TEXTO_LEGAL_CLIENTE_FAC, TEXTO_LEGAL_EMPRESA_FAC = :TEXTO_LEGAL_EMPRESA_FAC, DOCUMENTO_FAC = :DOCUM' +
        'ENTO_FAC, COMENTARIOS_FAC = :COMENTARIOS_FAC, CONTADOR_LINEAS_FAC = :CONTADOR_LINEAS_FAC, ESCREARARTICULOS_FAC = :ESCREARARTICULOS_FAC, ESDESCRIPCIONES_AMP_FAC = :ESDESCRIPCIONES_AMP_FAC, ESFECHADEENT' +
        'REGA_FAC = :ESFECHADEENTREGA_FAC, INSTANTE_MODIF = :INSTANTE_MODIF, INSTANTE_ALTA = :INSTANTE_ALTA, USUARIO_ALTA = :USUARIO_ALTA, USUARIO_MODIF = :USUARIO_MODIF'
      'WHERE'
      
        '  NUMERO_FAC = :Old_NUMERO_FAC AND SERIE_FAC = :Old_SERIE_FAC')
    SQLLock.Strings = (
      
        'SELECT NUMERO_FAC, SERIE_FAC, FECHA_FAC, CODIGO_EMP_FAC, RAZON_SOCIAL_EMPRESA_FAC, NIF_EMPRESA_FAC, MOVIL_EMPRESA_FAC, EMAIL_EMPRESA_FAC, DIRECCION1_EMPRESA_FAC, DIRECCION2_EMPRESA_FAC, POBLACION_EMPR' +
        'ESA_FAC, PROVINCIA_EMPRESA_FAC, CODIGO_PAI_EMPRESA_FAC, NOMBRE_PAI_EMPRESA_FAC, CODIGO_POSTAL_EMPRESA_FAC, ESRETENCIONES_EMPRESA_FAC, GRUPO_ZONA_IVA_EMPRESA_FAC, ESREGIMENESPECIALAGRICOLA_EMPRESA_FAC,' +
        ' CODIGO_CLI_FAC, RAZON_SOCIAL_CLIENTE_FAC, NIF_CLIENTE_FAC, MOVIL_CLIENTE_FAC, EMAIL_CLIENTE_FAC, DIRECCION1_CLIENTE_FAC, DIRECCION2_CLIENTE_FAC, POBLACION_CLIENTE_FAC, PROVINCIA_CLIENTE_FAC, CODIGO_P' +
        'OSTAL_CLIENTE_FAC, CODIGO_PAI_CLIENTE_FAC, NOMBRE_PAI_CLIENTE_FAC, CODIGO_IVA_FAC, ESIVA_RECARGO_CLIENTE_FAC, ESIVA_EXENTO_CLIENTE_FAC, ESREGIMENESPECIALAGRICOLA_CLIENTE_FAC, ESRETENCIONES_CLIENTE_FAC' +
        ', TARIFA_ARTICULO_CLIENTE_FAC, ESIMP_INCL_TARIFA_CLIENTE_FAC, ESINTRACOMUNITARIO_CLIENTE_FAC, ESIRPF_IMP_INCL_ZONA_IVA_FAC, ESAPLICA_RE_ZONA_IVA_FAC, ESIVAAGRICOLA_ZONA_IVA_FAC, PALABRA_REPORTS_ZONA_I' +
        'VA_FAC, ESVENTA_ACTIVO_FIJO_FAC, PORCENTAJE_IVAN_FAC, TOTAL_IVAN_FAC, PORCENTAJE_REN_FAC, TOTAL_REN_FAC, TOTAL_BASEI_IVAN_FAC, PORCENTAJE_IVAR_FAC, TOTAL_IVAR_FAC, PORCENTAJE_RER_FAC, TOTAL_RER_FAC, T' +
        'OTAL_BASEI_IVAR_FAC, PORCENTAJE_IVAS_FAC, TOTAL_IVAS_FAC, PORCENTAJE_RES_FAC, TOTAL_RES_FAC, TOTAL_BASEI_IVAS_FAC, PORCENTAJE_IVAE_FAC, TOTAL_IVAE_FAC, PORCENTAJE_REE_FAC, TOTAL_REE_FAC, TOTAL_BASEI_I' +
        'VAE_FAC, TOTAL_BASES_FAC, TOTAL_IMPUESTOS_FAC, FORMA_PAGO_FAC, PORCENTAJE_RETENCION_FAC, TOTAL_RETENCION_FAC, TOTAL_LIQUIDO_FAC, NUMERO_FAC_ABONO_FAC, SERIE_FAC_ABONO_FAC, TEXTO_LEGAL_CLIENTE_FAC, TEX' +
        'TO_LEGAL_EMPRESA_FAC, DOCUMENTO_FAC, COMENTARIOS_FAC, CONTADOR_LINEAS_FAC, ESCREARARTICULOS_FAC, ESDESCRIPCIONES_AMP_FAC, ESFECHADEENTREGA_FAC, INSTANTE_MODIF, INSTANTE_ALTA, USUARIO_ALTA, USUARIO_MOD' +
        'IF FROM FZA_FACTURAS'
      'WHERE'
      
        '  NUMERO_FAC = :Old_NUMERO_FAC AND SERIE_FAC = :Old_SERIE_FAC'
      'FOR UPDATE')
    SQLRefresh.Strings = (
      
        'SELECT NUMERO_FAC, SERIE_FAC, FECHA_FAC, CODIGO_EMP_FAC, RAZON_SOCIAL_EMPRESA_FAC, NIF_EMPRESA_FAC, MOVIL_EMPRESA_FAC, EMAIL_EMPRESA_FAC, DIRECCION1_EMPRESA_FAC, DIRECCION2_EMPRESA_FAC, POBLACION_EMPR' +
        'ESA_FAC, PROVINCIA_EMPRESA_FAC, CODIGO_PAI_EMPRESA_FAC, NOMBRE_PAI_EMPRESA_FAC, CODIGO_POSTAL_EMPRESA_FAC, ESRETENCIONES_EMPRESA_FAC, GRUPO_ZONA_IVA_EMPRESA_FAC, ESREGIMENESPECIALAGRICOLA_EMPRESA_FAC,' +
        ' CODIGO_CLI_FAC, RAZON_SOCIAL_CLIENTE_FAC, NIF_CLIENTE_FAC, MOVIL_CLIENTE_FAC, EMAIL_CLIENTE_FAC, DIRECCION1_CLIENTE_FAC, DIRECCION2_CLIENTE_FAC, POBLACION_CLIENTE_FAC, PROVINCIA_CLIENTE_FAC, CODIGO_P' +
        'OSTAL_CLIENTE_FAC, CODIGO_PAI_CLIENTE_FAC, NOMBRE_PAI_CLIENTE_FAC, CODIGO_IVA_FAC, ESIVA_RECARGO_CLIENTE_FAC, ESIVA_EXENTO_CLIENTE_FAC, ESREGIMENESPECIALAGRICOLA_CLIENTE_FAC, ESRETENCIONES_CLIENTE_FAC' +
        ', TARIFA_ARTICULO_CLIENTE_FAC, ESIMP_INCL_TARIFA_CLIENTE_FAC, ESINTRACOMUNITARIO_CLIENTE_FAC, ESIRPF_IMP_INCL_ZONA_IVA_FAC, ESAPLICA_RE_ZONA_IVA_FAC, ESIVAAGRICOLA_ZONA_IVA_FAC, PALABRA_REPORTS_ZONA_I' +
        'VA_FAC, ESVENTA_ACTIVO_FIJO_FAC, PORCENTAJE_IVAN_FAC, TOTAL_IVAN_FAC, PORCENTAJE_REN_FAC, TOTAL_REN_FAC, TOTAL_BASEI_IVAN_FAC, PORCENTAJE_IVAR_FAC, TOTAL_IVAR_FAC, PORCENTAJE_RER_FAC, TOTAL_RER_FAC, T' +
        'OTAL_BASEI_IVAR_FAC, PORCENTAJE_IVAS_FAC, TOTAL_IVAS_FAC, PORCENTAJE_RES_FAC, TOTAL_RES_FAC, TOTAL_BASEI_IVAS_FAC, PORCENTAJE_IVAE_FAC, TOTAL_IVAE_FAC, PORCENTAJE_REE_FAC, TOTAL_REE_FAC, TOTAL_BASEI_I' +
        'VAE_FAC, TOTAL_BASES_FAC, TOTAL_IMPUESTOS_FAC, FORMA_PAGO_FAC, PORCENTAJE_RETENCION_FAC, TOTAL_RETENCION_FAC, TOTAL_LIQUIDO_FAC, NUMERO_FAC_ABONO_FAC, SERIE_FAC_ABONO_FAC, TEXTO_LEGAL_CLIENTE_FAC, TEX' +
        'TO_LEGAL_EMPRESA_FAC, DOCUMENTO_FAC, COMENTARIOS_FAC, CONTADOR_LINEAS_FAC, ESCREARARTICULOS_FAC, ESDESCRIPCIONES_AMP_FAC, ESFECHADEENTREGA_FAC, INSTANTE_MODIF, INSTANTE_ALTA, USUARIO_ALTA, USUARIO_MOD' +
        'IF FROM FZA_FACTURAS'
      'WHERE'
      '  NUMERO_FAC = :NUMERO_FAC AND SERIE_FAC = :SERIE_FAC')
    SQLRecCount.Strings = (
      'SELECT COUNT(*) FROM FZA_FACTURAS')
    Connection = dmConn.conUni
    SQL.Strings = (
      'select * from vi_fac_busquedas')
    MasterFields = 'CODIGO_CLI_CLI'
    DetailFields = 'CODIGO_CLI_FAC'
    ReadOnly = True
    Left = 408
    Top = 96
  end
  object dsFacturasLineasClientes: TDataSource
    DataSet = unqryFacturasLineasClientes
    Left = 544
    Top = 32
  end
  object unqryFacturasLineasClientes: TUniQuery
    SQLInsert.Strings = (
      'INSERT INTO FZA_FACTURAS_LINEAS'
      
        '  (NUMERO_FAC_FACLIN, SERIE_FAC_FACLIN, LINEA_FACLIN, CODIGO_ART_FACLIN, CODIGO_FAM_FACLIN, NOMBRE_FAM_FACLIN, PRECIO_ULT_COMPRA_FACLIN, CODIGO_PRV_FACLIN, RAZON_SOCIAL_PROVEEDOR_FACLIN, ESPROVEEDORPR' +
        'INCIPAL_FACLIN, FECHA_ENTREGA_FACLIN, TIPO_CANTIDAD_ARTICULO_FACLIN, ESIMP_INCL_TARIFA_FACLIN, TIPO_IVA_ARTICULO_FACLIN, DESCRIPCION_ARTICULO_FACLIN, CODIGO_TAR_FACLIN, CANTIDAD_FACLIN, PRECIO_SALIDA_' +
        'FACLIN, PORCENTAJE_DTO_FACLIN, PRECIO_DTO_FACLIN, PRECIO_VENTA_SIVA_ARTICULO_FACLIN, PORCENTAJE_IVA_FACLIN, PRECIO_VENTA_CIVA_ARTICULO_FACLIN, TOTAL_FACLIN, TOTAL_FAC_SIVA_FACLIN, INSTANTE_MODIF, INST' +
        'ANTE_ALTA, USUARIO_ALTA, USUARIO_MODIF)'
      'VALUES'
      
        '  (:NUMERO_FAC_FACLIN, :SERIE_FAC_FACLIN, :LINEA_FACLIN, :CODIGO_ART_FACLIN, :CODIGO_FAM_FACLIN, :NOMBRE_FAM_FACLIN, :PRECIO_ULT_COMPRA_FACLIN, :CODIGO_PRV_FACLIN, :RAZON_SOCIAL_PROVEEDOR_FACLIN, :ESP' +
        'ROVEEDORPRINCIPAL_FACLIN, :FECHA_ENTREGA_FACLIN, :TIPO_CANTIDAD_ARTICULO_FACLIN, :ESIMP_INCL_TARIFA_FACLIN, :TIPO_IVA_ARTICULO_FACLIN, :DESCRIPCION_ARTICULO_FACLIN, :CODIGO_TAR_FACLIN, :CANTIDAD_FACLI' +
        'N, :PRECIO_SALIDA_FACLIN, :PORCENTAJE_DTO_FACLIN, :PRECIO_DTO_FACLIN, :PRECIO_VENTA_SIVA_ARTICULO_FACLIN, :PORCENTAJE_IVA_FACLIN, :PRECIO_VENTA_CIVA_ARTICULO_FACLIN, :TOTAL_FACLIN, :TOTAL_FAC_SIVA_FAC' +
        'LIN, :INSTANTE_MODIF, :INSTANTE_ALTA, :USUARIO_ALTA, :USUARIO_MODIF)')
    SQLDelete.Strings = (
      'DELETE FROM FZA_FACTURAS_LINEAS'
      'WHERE'
      
        '  NUMERO_FAC_FACLIN = :Old_NUMERO_FAC_FACLIN AND SERIE_FAC_FACLIN = :Old_SERIE_FAC_FACLIN AND LINEA_FACLIN = :Old_LINEA_FACLIN')
    SQLUpdate.Strings = (
      'UPDATE FZA_FACTURAS_LINEAS'
      'SET'
      
        '  NUMERO_FAC_FACLIN = :NUMERO_FAC_FACLIN, SERIE_FAC_FACLIN = :SERIE_FAC_FACLIN, LINEA_FACLIN = :LINEA_FACLIN, CODIGO_ART_FACLIN = :CODIGO_ART_FACLIN, CODIGO_FAM_FACLIN = :CODIGO_FAM_FACLIN, NOMBRE_FAM' +
        '_FACLIN = :NOMBRE_FAM_FACLIN, PRECIO_ULT_COMPRA_FACLIN = :PRECIO_ULT_COMPRA_FACLIN, CODIGO_PRV_FACLIN = :CODIGO_PRV_FACLIN, RAZON_SOCIAL_PROVEEDOR_FACLIN = :RAZON_SOCIAL_PROVEEDOR_FACLIN, ESPROVEEDORP' +
        'RINCIPAL_FACLIN = :ESPROVEEDORPRINCIPAL_FACLIN, FECHA_ENTREGA_FACLIN = :FECHA_ENTREGA_FACLIN, TIPO_CANTIDAD_ARTICULO_FACLIN = :TIPO_CANTIDAD_ARTICULO_FACLIN, ESIMP_INCL_TARIFA_FACLIN = :ESIMP_INCL_TAR' +
        'IFA_FACLIN, TIPO_IVA_ARTICULO_FACLIN = :TIPO_IVA_ARTICULO_FACLIN, DESCRIPCION_ARTICULO_FACLIN = :DESCRIPCION_ARTICULO_FACLIN, CODIGO_TAR_FACLIN = :CODIGO_TAR_FACLIN, CANTIDAD_FACLIN = :CANTIDAD_FACLIN' +
        ', PRECIO_SALIDA_FACLIN = :PRECIO_SALIDA_FACLIN, PORCENTAJE_DTO_FACLIN = :PORCENTAJE_DTO_FACLIN, PRECIO_DTO_FACLIN = :PRECIO_DTO_FACLIN, PRECIO_VENTA_SIVA_ARTICULO_FACLIN = :PRECIO_VENTA_SIVA_ARTICULO_' +
        'FACLIN, PORCENTAJE_IVA_FACLIN = :PORCENTAJE_IVA_FACLIN, PRECIO_VENTA_CIVA_ARTICULO_FACLIN = :PRECIO_VENTA_CIVA_ARTICULO_FACLIN, TOTAL_FACLIN = :TOTAL_FACLIN, TOTAL_FAC_SIVA_FACLIN = :TOTAL_FAC_SIVA_FA' +
        'CLIN, INSTANTE_MODIF = :INSTANTE_MODIF, INSTANTE_ALTA = :INSTANTE_ALTA, USUARIO_ALTA = :USUARIO_ALTA, USUARIO_MODIF = :USUARIO_MODIF'
      'WHERE'
      
        '  NUMERO_FAC_FACLIN = :Old_NUMERO_FAC_FACLIN AND SERIE_FAC_FACLIN = :Old_SERIE_FAC_FACLIN AND LINEA_FACLIN = :Old_LINEA_FACLIN')
    SQLLock.Strings = (
      
        'SELECT NUMERO_FAC_FACLIN, SERIE_FAC_FACLIN, LINEA_FACLIN, CODIGO_ART_FACLIN, CODIGO_FAM_FACLIN, NOMBRE_FAM_FACLIN, PRECIO_ULT_COMPRA_FACLIN, CODIGO_PRV_FACLIN, RAZON_SOCIAL_PROVEEDOR_FACLIN, ESPROVEED' +
        'ORPRINCIPAL_FACLIN, FECHA_ENTREGA_FACLIN, TIPO_CANTIDAD_ARTICULO_FACLIN, ESIMP_INCL_TARIFA_FACLIN, TIPO_IVA_ARTICULO_FACLIN, DESCRIPCION_ARTICULO_FACLIN, CODIGO_TAR_FACLIN, CANTIDAD_FACLIN, PRECIO_SAL' +
        'IDA_FACLIN, PORCENTAJE_DTO_FACLIN, PRECIO_DTO_FACLIN, PRECIO_VENTA_SIVA_ARTICULO_FACLIN, PORCENTAJE_IVA_FACLIN, PRECIO_VENTA_CIVA_ARTICULO_FACLIN, TOTAL_FACLIN, TOTAL_FAC_SIVA_FACLIN, INSTANTE_MODIF, ' +
        'INSTANTE_ALTA, USUARIO_ALTA, USUARIO_MODIF FROM FZA_FACTURAS_LINEAS'
      'WHERE'
      
        '  NUMERO_FAC_FACLIN = :Old_NUMERO_FAC_FACLIN AND SERIE_FAC_FACLIN = :Old_SERIE_FAC_FACLIN AND LINEA_FACLIN = :Old_LINEA_FACLIN'
      'FOR UPDATE')
    SQLRefresh.Strings = (
      
        'SELECT NUMERO_FAC_FACLIN, SERIE_FAC_FACLIN, LINEA_FACLIN, CODIGO_ART_FACLIN, CODIGO_FAM_FACLIN, NOMBRE_FAM_FACLIN, PRECIO_ULT_COMPRA_FACLIN, CODIGO_PRV_FACLIN, RAZON_SOCIAL_PROVEEDOR_FACLIN, ESPROVEED' +
        'ORPRINCIPAL_FACLIN, FECHA_ENTREGA_FACLIN, TIPO_CANTIDAD_ARTICULO_FACLIN, ESIMP_INCL_TARIFA_FACLIN, TIPO_IVA_ARTICULO_FACLIN, DESCRIPCION_ARTICULO_FACLIN, CODIGO_TAR_FACLIN, CANTIDAD_FACLIN, PRECIO_SAL' +
        'IDA_FACLIN, PORCENTAJE_DTO_FACLIN, PRECIO_DTO_FACLIN, PRECIO_VENTA_SIVA_ARTICULO_FACLIN, PORCENTAJE_IVA_FACLIN, PRECIO_VENTA_CIVA_ARTICULO_FACLIN, TOTAL_FACLIN, TOTAL_FAC_SIVA_FACLIN, INSTANTE_MODIF, ' +
        'INSTANTE_ALTA, USUARIO_ALTA, USUARIO_MODIF FROM FZA_FACTURAS_LINEAS'
      'WHERE'
      
        '  NUMERO_FAC_FACLIN = :NUMERO_FAC_FACLIN AND SERIE_FAC_FACLIN = :SERIE_FAC_FACLIN AND LINEA_FACLIN = :LINEA_FACLIN')
    SQLRecCount.Strings = (
      'SELECT COUNT(*) FROM FZA_FACTURAS_LINEAS')
    Connection = dmConn.conUni
    SQL.Strings = (
      'select *'
      'from vi_fac_lin_busquedas l'
      'inner join vi_fac_busquedas f'
      'on l.NUMERO_FAC_FACLIN = F.NUMERO_FAC'
      'AND l.SERIE_FAC_FACLIN = F.SERIE_FAC'
      '')
    MasterFields = 'CODIGO_CLI_CLI'
    DetailFields = 'CODIGO_CLI_FAC'
    ReadOnly = True
    Left = 544
    Top = 96
    ParamData = <
      item
        DataType = ftWideString
        Name = 'CODIGO_CLI_CLI'
        ParamType = ptInput
        Value = 'AGRICULTOR'
      end>
  end
  object cdsEtiquetas: TClientDataSet
    Aggregates = <>
    AutoCalcFields = False
    Params = <>
    Left = 800
    Top = 24
  end
  object dtstprvEtiquetas: TDataSetProvider
    DataSet = unqryCliPrint
    Constraints = False
    Options = []
    Left = 800
    Top = 96
  end
  object unqryCliPrint: TUniQuery
    Connection = dmConn.conUni
    SQL.Strings = (
      'select * from vi_clientes')
    BeforeInsert = unqryTablaGBeforeInsert
    AfterInsert = unqryTablaGAfterInsert
    BeforePost = unqryTablaGBeforePost
    BeforeDelete = unqryTablaGBeforeDelete
    Left = 712
    Top = 32
  end
  object dsEtiquetas: TDataSource
    DataSet = unqryCliPrint
    Left = 800
    Top = 168
  end
  object fxdsEtiquetas: TfrxDBDataset
    Description = 'Etiquetas'
    UserName = 'Etiquetas'
    CloseDataSource = False
    DataSet = cdsEtiquetas
    BCDToCurrency = False
    DataSetOptions = []
    Left = 800
    Top = 232
  end
  object dsPaises: TDataSource
    DataSet = unqryPaises
    Left = 640
    Top = 32
  end
  object unqryPaises: TUniQuery
    SQLInsert.Strings = (
      'INSERT INTO fza_historia'
      
        '  (ID, CODIGO_ART_ART, DESCRIPCION_ART, CODIGO_CLI_CLI, PRECIOVENTA_ARTICULO, FECHA, ZONA, DESCRIPCION_HISTORIA, NUMERO_FAC, LINEA_LINEA, ODONTOLOGO, SERIE_FAC)'
      'VALUES'
      
        '  (:ID, :CODIGO_ART_ART, :DESCRIPCION_ART, :CODIGO_CLI_CLI, :PRECIOVENTA_ARTICULO, :FECHA, :ZONA, :DESCRIPCION_HISTORIA, :NUMERO_FAC, :LINEA_LINEA, :ODONTOLOGO, :SERIE_FAC)')
    SQLDelete.Strings = (
      'DELETE FROM fza_historia'
      'WHERE'
      '  ID = :Old_ID')
    SQLUpdate.Strings = (
      'UPDATE fza_historia'
      'SET'
      
        '  ID = :ID, CODIGO_ART_ART = :CODIGO_ART_ART, DESCRIPCION_ART = :DESCRIPCION_ART, CODIGO_CLI_CLI = :CODIGO_CLI_CLI, PRECIOVENTA_ARTICULO = :PRECIOVENTA_ARTICULO, FECHA = :FECHA, ZONA = :ZONA, DESCRIPC' +
        'ION_HISTORIA = :DESCRIPCION_HISTORIA, NUMERO_FAC = :NUMERO_FAC, LINEA_LINEA = :LINEA_LINEA, ODONTOLOGO = :ODONTOLOGO, SERIE_FAC = :SERIE_FAC'
      'WHERE'
      '  ID = :Old_ID')
    SQLLock.Strings = (
      'SELECT * FROM fza_historia'
      'WHERE'
      '  ID = :Old_ID'
      'FOR UPDATE')
    SQLRefresh.Strings = (
      
        'SELECT ID, CODIGO_ART_ART, DESCRIPCION_ART, CODIGO_CLI_CLI, PRECIOVENTA_ARTICULO, FECHA, ZONA, DESCRIPCION_HISTORIA, NUMERO_FAC, LINEA_LINEA, ODONTOLOGO, SERIE_FAC FROM fza_historia'
      'WHERE'
      '  ID = :ID')
    SQLRecCount.Strings = (
      'SELECT COUNT(*) FROM fza_historia')
    Connection = dmConn.conUni
    SQL.Strings = (
      'select * from vi_paises'
      '')
    ReadOnly = True
    Left = 640
    Top = 96
  end
  object dsDepositos: TDataSource
    DataSet = unqryDepositos
    Left = 152
    Top = 176
  end
  object unqryDepositos: TUniQuery
    SQLInsert.Strings = (
      'INSERT INTO fza_depositos_cliente'
      
        '  (ID_DEPOSITO_DEP, CODIGO_EMP_DEP, CODIGO_CLI_DEP, CODIGO_ART_DEP, CODIGO_UNIDAD_DEP, PRECIO_VENTA_DEP, IMPORTE_ANTICIPO_DEP, ESTADO_DEP, FECHA_CREACION_DEP, INSTANTE_MODIF, INSTANTE_ALTA, USUARIO_AL' +
        'TA, USUARIO_MODIF, TIPO_IVA_DEP, PORCENTAJE_IVA_DEP, ESIMP_INCL_DEP, CANTIDAD_PENDIENTE_DEP, FECHA_ENTREGA_DEP)'
      'VALUES'
      
        '  (:ID_DEPOSITO_DEP, :CODIGO_EMP_DEP, :CODIGO_CLI_DEP, :CODIGO_ART_DEP, :CODIGO_UNIDAD_DEP, :PRECIO_VENTA_DEP, :IMPORTE_ANTICIPO_DEP, :ESTADO_DEP, :FECHA_CREACION_DEP, :INSTANTE_MODIF, :INSTANTE_ALTA,' +
        ' :USUARIO_ALTA, :USUARIO_MODIF, :TIPO_IVA_DEP, :PORCENTAJE_IVA_DEP, :ESIMP_INCL_DEP, :CANTIDAD_PENDIENTE_DEP, :FECHA_ENTREGA_DEP)')
    SQLDelete.Strings = (
      'DELETE FROM fza_depositos_cliente'
      'WHERE'
      '  ID_DEPOSITO_DEP = :Old_ID_DEPOSITO_DEP')
    SQLUpdate.Strings = (
      'UPDATE fza_depositos_cliente'
      'SET'
      
        '  ID_DEPOSITO_DEP = :ID_DEPOSITO_DEP, CODIGO_EMP_DEP = :CODIGO_EMP_DEP, CODIGO_CLI_DEP = :CODIGO_CLI_DEP, CODIGO_ART_DEP = :CODIGO_ART_DEP, CODIGO_UNIDAD_DEP = :CODIGO_UNIDAD_DEP, PRECIO_VENTA_DEP = :' +
        'PRECIO_VENTA_DEP, IMPORTE_ANTICIPO_DEP = :IMPORTE_ANTICIPO_DEP, ESTADO_DEP = :ESTADO_DEP, FECHA_CREACION_DEP = :FECHA_CREACION_DEP, INSTANTE_MODIF = :INSTANTE_MODIF, INSTANTE_ALTA = :INSTANTE_ALTA, US' +
        'UARIO_ALTA = :USUARIO_ALTA, USUARIO_MODIF = :USUARIO_MODIF, TIPO_IVA_DEP = :TIPO_IVA_DEP, PORCENTAJE_IVA_DEP = :PORCENTAJE_IVA_DEP, ESIMP_INCL_DEP = :ESIMP_INCL_DEP, CANTIDAD_PENDIENTE_DEP = :CANTIDAD' +
        '_PENDIENTE_DEP, FECHA_ENTREGA_DEP = :FECHA_ENTREGA_DEP'
      'WHERE'
      '  ID_DEPOSITO_DEP = :Old_ID_DEPOSITO_DEP')
    SQLLock.Strings = (
      
        'SELECT ID_DEPOSITO_DEP, CODIGO_EMP_DEP, CODIGO_CLI_DEP, CODIGO_ART_DEP, CODIGO_UNIDAD_DEP, PRECIO_VENTA_DEP, IMPORTE_ANTICIPO_DEP, ESTADO_DEP, FECHA_CREACION_DEP, INSTANTE_MODIF, INSTANTE_ALTA, USUARI' +
        'O_ALTA, USUARIO_MODIF, TIPO_IVA_DEP, PORCENTAJE_IVA_DEP, ESIMP_INCL_DEP, CANTIDAD_PENDIENTE_DEP, FECHA_ENTREGA_DEP FROM fza_depositos_cliente'
      'WHERE'
      '  ID_DEPOSITO_DEP = :Old_ID_DEPOSITO_DEP'
      'FOR UPDATE')
    SQLRefresh.Strings = (
      
        'SELECT ID_DEPOSITO_DEP, CODIGO_EMP_DEP, CODIGO_CLI_DEP, CODIGO_ART_DEP, CODIGO_UNIDAD_DEP, PRECIO_VENTA_DEP, IMPORTE_ANTICIPO_DEP, ESTADO_DEP, FECHA_CREACION_DEP, INSTANTE_MODIF, INSTANTE_ALTA, USUARI' +
        'O_ALTA, USUARIO_MODIF, TIPO_IVA_DEP, PORCENTAJE_IVA_DEP, ESIMP_INCL_DEP, CANTIDAD_PENDIENTE_DEP, FECHA_ENTREGA_DEP FROM fza_depositos_cliente'
      'WHERE'
      '  ID_DEPOSITO_DEP = :ID_DEPOSITO_DEP')
    SQLRecCount.Strings = (
      'SELECT COUNT(*) FROM fza_depositos_cliente')
    Connection = dmConn.conUni
    SQL.Strings = (
      'select * from vi_depositos_cliente')
    MasterSource = frmMtoClientes.dsTablaG
    MasterFields = 'CODIGO_CLI_CLI'
    DetailFields = 'CODIGO_CLI_DEP'
    ReadOnly = True
    Active = True
    Left = 152
    Top = 240
    ParamData = <
      item
        DataType = ftWideString
        Name = 'CODIGO_CLI_CLI'
        ParamType = ptInput
        Value = '321'
      end>
  end
end
