inherited dmPedidos: TdmPedidos
  Height = 480
  Width = 632
  PixelsPerInch = 120
  inherited unqryTablaG: TUniQuery
    SQLInsert.Strings = (
      'INSERT INTO fza_pedidos'
      
        '  (NUMERO_PED, SERIE_PED, FECHA_PED, CODIGO_EMP_PED, RAZON_SOCIA' +
        'L_EMPRESA_PED, NIF_EMPRESA_PED, MOVIL_EMPRESA_PED, EMAIL_EMPRESA' +
        '_PED, DIRECCION1_EMPRESA_PED, DIRECCION2_EMPRESA_PED, POBLACION_' +
        'EMPRESA_PED, PROVINCIA_EMPRESA_PED, CODIGO_PAI_EMPRESA_PED, NOMB' +
        'RE_PAI_EMPRESA_PED, CODIGO_POSTAL_EMPRESA_PED, ESRETENCIONES_EMP' +
        'RESA_PED, GRUPO_ZONA_IVA_EMPRESA_PED, ESREGIMENESPECIALAGRICOLA_' +
        'EMPRESA_PED, CODIGO_CLI_PED, NIF_CLIENTE_PED, EMAIL_CLIENTE_PED,' +
        ' REFERENCIAPS_PED, IDPS_PED, FECHAPS_PED, FORMAPAGOPS_PED, TRANS' +
        'PORTISTAPS_PED, ESTADOPEDIDOPS_PED, ESTADOMENSAJEPS_PED, IDHILOP' +
        'S_MENSAJES_PED, NOMBRE_CLI_ENVIO_PED, MOVIL_CLIENTE_ENVIO_PED, D' +
        'IRECCION1_CLIENTE_ENVIO_PED, DIRECCION2_CLIENTE_ENVIO_PED, POBLA' +
        'CION_CLIENTE_ENVIO_PED, PROVINCIA_CLIENTE_ENVIO_PED, CODIGO_POST' +
        'AL_CLIENTE_ENVIO_PED, CODIGO_PAI_CLIENTE_ENVIO_PED, NOMBRE_PAI_C' +
        'LIENTE_ENVIO_PED, RAZON_SOCIAL_CLIENTE_FISCAL_PED, MOVIL_CLIENTE' +
        '_FISCAL_PED, EMAIL_CLIENTE_FISCAL_PED, DIRECCION1_CLIENTE_FISCAL' +
        '_PED, DIRECCION2_CLIENTE_FISCAL_PED, POBLACION_CLIENTE_FISCAL_PE' +
        'D, PROVINCIA_CLIENTE_FISCAL_PED, CODIGO_POSTAL_CLIENTE_FISCAL_PE' +
        'D, CODIGO_PAI_CLIENTE_FISCAL_PED, NOMBRE_PAI_CLIENTE_FISCAL_PED,' +
        ' ESIVA_RECARGO_CLIENTE_PED, ESIVA_EXENTO_CLIENTE_PED, ESREGIMENE' +
        'SPECIALAGRICOLA_CLIENTE_PED, ESRETENCIONES_CLIENTE_PED, TARIFA_A' +
        'RTICULO_CLIENTE_PED, ESIMP_INCL_TARIFA_CLIENTE_PED, ESINTRACOMUN' +
        'ITARIO_CLIENTE_PED, ESIRPF_IMP_INCL_ZONA_IVA_PED, ESAPLICA_RE_ZO' +
        'NA_IVA_PED, ESIVAAGRICOLA_ZONA_IVA_PED, PALABRA_REPORTS_ZONA_IVA' +
        '_PED, CODIGO_IVA_PED, ESVENTA_ACTIVO_FIJO_PED, PORCENTAJE_IVAN_P' +
        'ED, TOTAL_IVAN_PED, PORCENTAJE_REN_PED, TOTAL_REN_PED, TOTAL_BAS' +
        'EI_IVAN_PED, PORCENTAJE_IVAR_PED, TOTAL_IVAR_PED, PORCENTAJE_RER' +
        '_PED, TOTAL_RER_PED, TOTAL_BASEI_IVAR_PED, PORCENTAJE_IVAS_PED, ' +
        'TOTAL_IVAS_PED, PORCENTAJE_RES_PED, TOTAL_RES_PED, TOTAL_BASEI_I' +
        'VAS_PED, PORCENTAJE_IVAE_PED, TOTAL_IVAE_PED, PORCENTAJE_REE_PED' +
        ', TOTAL_REE_PED, TOTAL_BASEI_IVAE_PED, TOTAL_BASES_PED, TOTAL_IM' +
        'PUESTOS_PED, FORMA_PAGO_PED, PORCENTAJE_RETENCION_PED, TOTAL_RET' +
        'ENCION_PED, TOTAL_LIQUIDO_PED, TOTAL_PAGADOREALPS_PED, NUMERO_PE' +
        'D_ABONO_PED, SERIE_PED_ABONO_PED, TEXTO_LEGAL_CLIENTE_PED, TEXTO' +
        '_LEGAL_EMPRESA_PED, DOCUMENTO_PED, COMENTARIOS_PED, CONTADOR_LIN' +
        'EAS_PED, ESCREARARTICULOS_PED, ESDESCRIPCIONES_AMP_PED, ESFECHAD' +
        'EENTREGA_PED, INSTANTE_MODIF, INSTANTE_ALTA, USUARIO_ALTA, USUAR' +
        'IO_MODIF)'
      'VALUES'
      
        '  (:NUMERO_PED, :SERIE_PED, :FECHA_PED, :CODIGO_EMP_PED, :RAZON_' +
        'SOCIAL_EMPRESA_PED, :NIF_EMPRESA_PED, :MOVIL_EMPRESA_PED, :EMAIL' +
        '_EMPRESA_PED, :DIRECCION1_EMPRESA_PED, :DIRECCION2_EMPRESA_PED, ' +
        ':POBLACION_EMPRESA_PED, :PROVINCIA_EMPRESA_PED, :CODIGO_PAI_EMPR' +
        'ESA_PED, :NOMBRE_PAI_EMPRESA_PED, :CODIGO_POSTAL_EMPRESA_PED, :E' +
        'SRETENCIONES_EMPRESA_PED, :GRUPO_ZONA_IVA_EMPRESA_PED, :ESREGIME' +
        'NESPECIALAGRICOLA_EMPRESA_PED, :CODIGO_CLI_PED, :NIF_CLIENTE_PED' +
        ', :EMAIL_CLIENTE_PED, :REFERENCIAPS_PED, :IDPS_PED, :FECHAPS_PED' +
        ', :FORMAPAGOPS_PED, :TRANSPORTISTAPS_PED, :ESTADOPEDIDOPS_PED, :' +
        'ESTADOMENSAJEPS_PED, :IDHILOPS_MENSAJES_PED, :NOMBRE_CLI_ENVIO_P' +
        'ED, :MOVIL_CLIENTE_ENVIO_PED, :DIRECCION1_CLIENTE_ENVIO_PED, :DI' +
        'RECCION2_CLIENTE_ENVIO_PED, :POBLACION_CLIENTE_ENVIO_PED, :PROVI' +
        'NCIA_CLIENTE_ENVIO_PED, :CODIGO_POSTAL_CLIENTE_ENVIO_PED, :CODIG' +
        'O_PAI_CLIENTE_ENVIO_PED, :NOMBRE_PAI_CLIENTE_ENVIO_PED, :RAZON_S' +
        'OCIAL_CLIENTE_FISCAL_PED, :MOVIL_CLIENTE_FISCAL_PED, :EMAIL_CLIE' +
        'NTE_FISCAL_PED, :DIRECCION1_CLIENTE_FISCAL_PED, :DIRECCION2_CLIE' +
        'NTE_FISCAL_PED, :POBLACION_CLIENTE_FISCAL_PED, :PROVINCIA_CLIENT' +
        'E_FISCAL_PED, :CODIGO_POSTAL_CLIENTE_FISCAL_PED, :CODIGO_PAI_CLI' +
        'ENTE_FISCAL_PED, :NOMBRE_PAI_CLIENTE_FISCAL_PED, :ESIVA_RECARGO_' +
        'CLIENTE_PED, :ESIVA_EXENTO_CLIENTE_PED, :ESREGIMENESPECIALAGRICO' +
        'LA_CLIENTE_PED, :ESRETENCIONES_CLIENTE_PED, :TARIFA_ARTICULO_CLI' +
        'ENTE_PED, :ESIMP_INCL_TARIFA_CLIENTE_PED, :ESINTRACOMUNITARIO_CL' +
        'IENTE_PED, :ESIRPF_IMP_INCL_ZONA_IVA_PED, :ESAPLICA_RE_ZONA_IVA_' +
        'PED, :ESIVAAGRICOLA_ZONA_IVA_PED, :PALABRA_REPORTS_ZONA_IVA_PED,' +
        ' :CODIGO_IVA_PED, :ESVENTA_ACTIVO_FIJO_PED, :PORCENTAJE_IVAN_PED' +
        ', :TOTAL_IVAN_PED, :PORCENTAJE_REN_PED, :TOTAL_REN_PED, :TOTAL_B' +
        'ASEI_IVAN_PED, :PORCENTAJE_IVAR_PED, :TOTAL_IVAR_PED, :PORCENTAJ' +
        'E_RER_PED, :TOTAL_RER_PED, :TOTAL_BASEI_IVAR_PED, :PORCENTAJE_IV' +
        'AS_PED, :TOTAL_IVAS_PED, :PORCENTAJE_RES_PED, :TOTAL_RES_PED, :T' +
        'OTAL_BASEI_IVAS_PED, :PORCENTAJE_IVAE_PED, :TOTAL_IVAE_PED, :POR' +
        'CENTAJE_REE_PED, :TOTAL_REE_PED, :TOTAL_BASEI_IVAE_PED, :TOTAL_B' +
        'ASES_PED, :TOTAL_IMPUESTOS_PED, :FORMA_PAGO_PED, :PORCENTAJE_RET' +
        'ENCION_PED, :TOTAL_RETENCION_PED, :TOTAL_LIQUIDO_PED, :TOTAL_PAG' +
        'ADOREALPS_PED, :NUMERO_PED_ABONO_PED, :SERIE_PED_ABONO_PED, :TEX' +
        'TO_LEGAL_CLIENTE_PED, :TEXTO_LEGAL_EMPRESA_PED, :DOCUMENTO_PED, ' +
        ':COMENTARIOS_PED, :CONTADOR_LINEAS_PED, :ESCREARARTICULOS_PED, :' +
        'ESDESCRIPCIONES_AMP_PED, :ESFECHADEENTREGA_PED, :INSTANTE_MODIF,' +
        ' :INSTANTE_ALTA, :USUARIO_ALTA, :USUARIO_MODIF)')
    SQLDelete.Strings = (
      'DELETE FROM fza_pedidos'
      'WHERE'
      '  NUMERO_PED = :Old_NUMERO_PED AND SERIE_PED = :Old_SERIE_PED')
    SQLUpdate.Strings = (
      'UPDATE fza_pedidos'
      'SET'
      
        '  NUMERO_PED = :NUMERO_PED, SERIE_PED = :SERIE_PED, FECHA_PED = ' +
        ':FECHA_PED, CODIGO_EMP_PED = :CODIGO_EMP_PED, RAZON_SOCIAL_EMPRE' +
        'SA_PED = :RAZON_SOCIAL_EMPRESA_PED, NIF_EMPRESA_PED = :NIF_EMPRE' +
        'SA_PED, MOVIL_EMPRESA_PED = :MOVIL_EMPRESA_PED, EMAIL_EMPRESA_PE' +
        'D = :EMAIL_EMPRESA_PED, DIRECCION1_EMPRESA_PED = :DIRECCION1_EMP' +
        'RESA_PED, DIRECCION2_EMPRESA_PED = :DIRECCION2_EMPRESA_PED, POBL' +
        'ACION_EMPRESA_PED = :POBLACION_EMPRESA_PED, PROVINCIA_EMPRESA_PE' +
        'D = :PROVINCIA_EMPRESA_PED, CODIGO_PAI_EMPRESA_PED = :CODIGO_PAI' +
        '_EMPRESA_PED, NOMBRE_PAI_EMPRESA_PED = :NOMBRE_PAI_EMPRESA_PED, ' +
        'CODIGO_POSTAL_EMPRESA_PED = :CODIGO_POSTAL_EMPRESA_PED, ESRETENC' +
        'IONES_EMPRESA_PED = :ESRETENCIONES_EMPRESA_PED, GRUPO_ZONA_IVA_E' +
        'MPRESA_PED = :GRUPO_ZONA_IVA_EMPRESA_PED, ESREGIMENESPECIALAGRIC' +
        'OLA_EMPRESA_PED = :ESREGIMENESPECIALAGRICOLA_EMPRESA_PED, CODIGO' +
        '_CLI_PED = :CODIGO_CLI_PED, NIF_CLIENTE_PED = :NIF_CLIENTE_PED, ' +
        'EMAIL_CLIENTE_PED = :EMAIL_CLIENTE_PED, REFERENCIAPS_PED = :REFE' +
        'RENCIAPS_PED, IDPS_PED = :IDPS_PED, FECHAPS_PED = :FECHAPS_PED, ' +
        'FORMAPAGOPS_PED = :FORMAPAGOPS_PED, TRANSPORTISTAPS_PED = :TRANS' +
        'PORTISTAPS_PED, ESTADOPEDIDOPS_PED = :ESTADOPEDIDOPS_PED, ESTADO' +
        'MENSAJEPS_PED = :ESTADOMENSAJEPS_PED, IDHILOPS_MENSAJES_PED = :I' +
        'DHILOPS_MENSAJES_PED, NOMBRE_CLI_ENVIO_PED = :NOMBRE_CLI_ENVIO_P' +
        'ED, MOVIL_CLIENTE_ENVIO_PED = :MOVIL_CLIENTE_ENVIO_PED, DIRECCIO' +
        'N1_CLIENTE_ENVIO_PED = :DIRECCION1_CLIENTE_ENVIO_PED, DIRECCION2' +
        '_CLIENTE_ENVIO_PED = :DIRECCION2_CLIENTE_ENVIO_PED, POBLACION_CL' +
        'IENTE_ENVIO_PED = :POBLACION_CLIENTE_ENVIO_PED, PROVINCIA_CLIENT' +
        'E_ENVIO_PED = :PROVINCIA_CLIENTE_ENVIO_PED, CODIGO_POSTAL_CLIENT' +
        'E_ENVIO_PED = :CODIGO_POSTAL_CLIENTE_ENVIO_PED, CODIGO_PAI_CLIEN' +
        'TE_ENVIO_PED = :CODIGO_PAI_CLIENTE_ENVIO_PED, NOMBRE_PAI_CLIENTE' +
        '_ENVIO_PED = :NOMBRE_PAI_CLIENTE_ENVIO_PED, RAZON_SOCIAL_CLIENTE' +
        '_FISCAL_PED = :RAZON_SOCIAL_CLIENTE_FISCAL_PED, MOVIL_CLIENTE_FI' +
        'SCAL_PED = :MOVIL_CLIENTE_FISCAL_PED, EMAIL_CLIENTE_FISCAL_PED =' +
        ' :EMAIL_CLIENTE_FISCAL_PED, DIRECCION1_CLIENTE_FISCAL_PED = :DIR' +
        'ECCION1_CLIENTE_FISCAL_PED, DIRECCION2_CLIENTE_FISCAL_PED = :DIR' +
        'ECCION2_CLIENTE_FISCAL_PED, POBLACION_CLIENTE_FISCAL_PED = :POBL' +
        'ACION_CLIENTE_FISCAL_PED, PROVINCIA_CLIENTE_FISCAL_PED = :PROVIN' +
        'CIA_CLIENTE_FISCAL_PED, CODIGO_POSTAL_CLIENTE_FISCAL_PED = :CODI' +
        'GO_POSTAL_CLIENTE_FISCAL_PED, CODIGO_PAI_CLIENTE_FISCAL_PED = :C' +
        'ODIGO_PAI_CLIENTE_FISCAL_PED, NOMBRE_PAI_CLIENTE_FISCAL_PED = :N' +
        'OMBRE_PAI_CLIENTE_FISCAL_PED, ESIVA_RECARGO_CLIENTE_PED = :ESIVA' +
        '_RECARGO_CLIENTE_PED, ESIVA_EXENTO_CLIENTE_PED = :ESIVA_EXENTO_C' +
        'LIENTE_PED, ESREGIMENESPECIALAGRICOLA_CLIENTE_PED = :ESREGIMENES' +
        'PECIALAGRICOLA_CLIENTE_PED, ESRETENCIONES_CLIENTE_PED = :ESRETEN' +
        'CIONES_CLIENTE_PED, TARIFA_ARTICULO_CLIENTE_PED = :TARIFA_ARTICU' +
        'LO_CLIENTE_PED, ESIMP_INCL_TARIFA_CLIENTE_PED = :ESIMP_INCL_TARI' +
        'FA_CLIENTE_PED, ESINTRACOMUNITARIO_CLIENTE_PED = :ESINTRACOMUNIT' +
        'ARIO_CLIENTE_PED, ESIRPF_IMP_INCL_ZONA_IVA_PED = :ESIRPF_IMP_INC' +
        'L_ZONA_IVA_PED, ESAPLICA_RE_ZONA_IVA_PED = :ESAPLICA_RE_ZONA_IVA' +
        '_PED, ESIVAAGRICOLA_ZONA_IVA_PED = :ESIVAAGRICOLA_ZONA_IVA_PED, ' +
        'PALABRA_REPORTS_ZONA_IVA_PED = :PALABRA_REPORTS_ZONA_IVA_PED, CO' +
        'DIGO_IVA_PED = :CODIGO_IVA_PED, ESVENTA_ACTIVO_FIJO_PED = :ESVEN' +
        'TA_ACTIVO_FIJO_PED, PORCENTAJE_IVAN_PED = :PORCENTAJE_IVAN_PED, ' +
        'TOTAL_IVAN_PED = :TOTAL_IVAN_PED, PORCENTAJE_REN_PED = :PORCENTA' +
        'JE_REN_PED, TOTAL_REN_PED = :TOTAL_REN_PED, TOTAL_BASEI_IVAN_PED' +
        ' = :TOTAL_BASEI_IVAN_PED, PORCENTAJE_IVAR_PED = :PORCENTAJE_IVAR' +
        '_PED, TOTAL_IVAR_PED = :TOTAL_IVAR_PED, PORCENTAJE_RER_PED = :PO' +
        'RCENTAJE_RER_PED, TOTAL_RER_PED = :TOTAL_RER_PED, TOTAL_BASEI_IV' +
        'AR_PED = :TOTAL_BASEI_IVAR_PED, PORCENTAJE_IVAS_PED = :PORCENTAJ' +
        'E_IVAS_PED, TOTAL_IVAS_PED = :TOTAL_IVAS_PED, PORCENTAJE_RES_PED' +
        ' = :PORCENTAJE_RES_PED, TOTAL_RES_PED = :TOTAL_RES_PED, TOTAL_BA' +
        'SEI_IVAS_PED = :TOTAL_BASEI_IVAS_PED, PORCENTAJE_IVAE_PED = :POR' +
        'CENTAJE_IVAE_PED, TOTAL_IVAE_PED = :TOTAL_IVAE_PED, PORCENTAJE_R' +
        'EE_PED = :PORCENTAJE_REE_PED, TOTAL_REE_PED = :TOTAL_REE_PED, TO' +
        'TAL_BASEI_IVAE_PED = :TOTAL_BASEI_IVAE_PED, TOTAL_BASES_PED = :T' +
        'OTAL_BASES_PED, TOTAL_IMPUESTOS_PED = :TOTAL_IMPUESTOS_PED, FORM' +
        'A_PAGO_PED = :FORMA_PAGO_PED, PORCENTAJE_RETENCION_PED = :PORCEN' +
        'TAJE_RETENCION_PED, TOTAL_RETENCION_PED = :TOTAL_RETENCION_PED, ' +
        'TOTAL_LIQUIDO_PED = :TOTAL_LIQUIDO_PED, TOTAL_PAGADOREALPS_PED =' +
        ' :TOTAL_PAGADOREALPS_PED, NUMERO_PED_ABONO_PED = :NUMERO_PED_ABO' +
        'NO_PED, SERIE_PED_ABONO_PED = :SERIE_PED_ABONO_PED, TEXTO_LEGAL_' +
        'CLIENTE_PED = :TEXTO_LEGAL_CLIENTE_PED, TEXTO_LEGAL_EMPRESA_PED ' +
        '= :TEXTO_LEGAL_EMPRESA_PED, DOCUMENTO_PED = :DOCUMENTO_PED, COME' +
        'NTARIOS_PED = :COMENTARIOS_PED, CONTADOR_LINEAS_PED = :CONTADOR_' +
        'LINEAS_PED, ESCREARARTICULOS_PED = :ESCREARARTICULOS_PED, ESDESC' +
        'RIPCIONES_AMP_PED = :ESDESCRIPCIONES_AMP_PED, ESFECHADEENTREGA_P' +
        'ED = :ESFECHADEENTREGA_PED, INSTANTE_MODIF = :INSTANTE_MODIF, IN' +
        'STANTE_ALTA = :INSTANTE_ALTA, USUARIO_ALTA = :USUARIO_ALTA, USUA' +
        'RIO_MODIF = :USUARIO_MODIF'
      'WHERE'
      '  NUMERO_PED = :Old_NUMERO_PED AND SERIE_PED = :Old_SERIE_PED')
    SQLLock.Strings = (
      
        'SELECT NUMERO_PED, SERIE_PED, FECHA_PED, CODIGO_EMP_PED, RAZON_S' +
        'OCIAL_EMPRESA_PED, NIF_EMPRESA_PED, MOVIL_EMPRESA_PED, EMAIL_EMP' +
        'RESA_PED, DIRECCION1_EMPRESA_PED, DIRECCION2_EMPRESA_PED, POBLAC' +
        'ION_EMPRESA_PED, PROVINCIA_EMPRESA_PED, CODIGO_PAI_EMPRESA_PED, ' +
        'NOMBRE_PAI_EMPRESA_PED, CODIGO_POSTAL_EMPRESA_PED, ESRETENCIONES' +
        '_EMPRESA_PED, GRUPO_ZONA_IVA_EMPRESA_PED, ESREGIMENESPECIALAGRIC' +
        'OLA_EMPRESA_PED, CODIGO_CLI_PED, NIF_CLIENTE_PED, EMAIL_CLIENTE_' +
        'PED, REFERENCIAPS_PED, IDPS_PED, FECHAPS_PED, FORMAPAGOPS_PED, T' +
        'RANSPORTISTAPS_PED, ESTADOPEDIDOPS_PED, ESTADOMENSAJEPS_PED, IDH' +
        'ILOPS_MENSAJES_PED, NOMBRE_CLI_ENVIO_PED, MOVIL_CLIENTE_ENVIO_PE' +
        'D, DIRECCION1_CLIENTE_ENVIO_PED, DIRECCION2_CLIENTE_ENVIO_PED, P' +
        'OBLACION_CLIENTE_ENVIO_PED, PROVINCIA_CLIENTE_ENVIO_PED, CODIGO_' +
        'POSTAL_CLIENTE_ENVIO_PED, CODIGO_PAI_CLIENTE_ENVIO_PED, NOMBRE_P' +
        'AI_CLIENTE_ENVIO_PED, RAZON_SOCIAL_CLIENTE_FISCAL_PED, MOVIL_CLI' +
        'ENTE_FISCAL_PED, EMAIL_CLIENTE_FISCAL_PED, DIRECCION1_CLIENTE_FI' +
        'SCAL_PED, DIRECCION2_CLIENTE_FISCAL_PED, POBLACION_CLIENTE_FISCA' +
        'L_PED, PROVINCIA_CLIENTE_FISCAL_PED, CODIGO_POSTAL_CLIENTE_FISCA' +
        'L_PED, CODIGO_PAI_CLIENTE_FISCAL_PED, NOMBRE_PAI_CLIENTE_FISCAL_' +
        'PED, ESIVA_RECARGO_CLIENTE_PED, ESIVA_EXENTO_CLIENTE_PED, ESREGI' +
        'MENESPECIALAGRICOLA_CLIENTE_PED, ESRETENCIONES_CLIENTE_PED, TARI' +
        'FA_ARTICULO_CLIENTE_PED, ESIMP_INCL_TARIFA_CLIENTE_PED, ESINTRAC' +
        'OMUNITARIO_CLIENTE_PED, ESIRPF_IMP_INCL_ZONA_IVA_PED, ESAPLICA_R' +
        'E_ZONA_IVA_PED, ESIVAAGRICOLA_ZONA_IVA_PED, PALABRA_REPORTS_ZONA' +
        '_IVA_PED, CODIGO_IVA_PED, ESVENTA_ACTIVO_FIJO_PED, PORCENTAJE_IV' +
        'AN_PED, TOTAL_IVAN_PED, PORCENTAJE_REN_PED, TOTAL_REN_PED, TOTAL' +
        '_BASEI_IVAN_PED, PORCENTAJE_IVAR_PED, TOTAL_IVAR_PED, PORCENTAJE' +
        '_RER_PED, TOTAL_RER_PED, TOTAL_BASEI_IVAR_PED, PORCENTAJE_IVAS_P' +
        'ED, TOTAL_IVAS_PED, PORCENTAJE_RES_PED, TOTAL_RES_PED, TOTAL_BAS' +
        'EI_IVAS_PED, PORCENTAJE_IVAE_PED, TOTAL_IVAE_PED, PORCENTAJE_REE' +
        '_PED, TOTAL_REE_PED, TOTAL_BASEI_IVAE_PED, TOTAL_BASES_PED, TOTA' +
        'L_IMPUESTOS_PED, FORMA_PAGO_PED, PORCENTAJE_RETENCION_PED, TOTAL' +
        '_RETENCION_PED, TOTAL_LIQUIDO_PED, TOTAL_PAGADOREALPS_PED, NUMER' +
        'O_PED_ABONO_PED, SERIE_PED_ABONO_PED, TEXTO_LEGAL_CLIENTE_PED, T' +
        'EXTO_LEGAL_EMPRESA_PED, DOCUMENTO_PED, COMENTARIOS_PED, CONTADOR' +
        '_LINEAS_PED, ESCREARARTICULOS_PED, ESDESCRIPCIONES_AMP_PED, ESFE' +
        'CHADEENTREGA_PED, INSTANTE_MODIF, INSTANTE_ALTA, USUARIO_ALTA, U' +
        'SUARIO_MODIF FROM fza_pedidos'
      'WHERE'
      '  NUMERO_PED = :Old_NUMERO_PED AND SERIE_PED = :Old_SERIE_PED'
      'FOR UPDATE')
    SQLRefresh.Strings = (
      
        'SELECT NUMERO_PED, SERIE_PED, FECHA_PED, CODIGO_EMP_PED, RAZON_S' +
        'OCIAL_EMPRESA_PED, NIF_EMPRESA_PED, MOVIL_EMPRESA_PED, EMAIL_EMP' +
        'RESA_PED, DIRECCION1_EMPRESA_PED, DIRECCION2_EMPRESA_PED, POBLAC' +
        'ION_EMPRESA_PED, PROVINCIA_EMPRESA_PED, CODIGO_PAI_EMPRESA_PED, ' +
        'NOMBRE_PAI_EMPRESA_PED, CODIGO_POSTAL_EMPRESA_PED, ESRETENCIONES' +
        '_EMPRESA_PED, GRUPO_ZONA_IVA_EMPRESA_PED, ESREGIMENESPECIALAGRIC' +
        'OLA_EMPRESA_PED, CODIGO_CLI_PED, NIF_CLIENTE_PED, EMAIL_CLIENTE_' +
        'PED, REFERENCIAPS_PED, IDPS_PED, FECHAPS_PED, FORMAPAGOPS_PED, T' +
        'RANSPORTISTAPS_PED, ESTADOPEDIDOPS_PED, ESTADOMENSAJEPS_PED, IDH' +
        'ILOPS_MENSAJES_PED, NOMBRE_CLI_ENVIO_PED, MOVIL_CLIENTE_ENVIO_PE' +
        'D, DIRECCION1_CLIENTE_ENVIO_PED, DIRECCION2_CLIENTE_ENVIO_PED, P' +
        'OBLACION_CLIENTE_ENVIO_PED, PROVINCIA_CLIENTE_ENVIO_PED, CODIGO_' +
        'POSTAL_CLIENTE_ENVIO_PED, CODIGO_PAI_CLIENTE_ENVIO_PED, NOMBRE_P' +
        'AI_CLIENTE_ENVIO_PED, RAZON_SOCIAL_CLIENTE_FISCAL_PED, MOVIL_CLI' +
        'ENTE_FISCAL_PED, EMAIL_CLIENTE_FISCAL_PED, DIRECCION1_CLIENTE_FI' +
        'SCAL_PED, DIRECCION2_CLIENTE_FISCAL_PED, POBLACION_CLIENTE_FISCA' +
        'L_PED, PROVINCIA_CLIENTE_FISCAL_PED, CODIGO_POSTAL_CLIENTE_FISCA' +
        'L_PED, CODIGO_PAI_CLIENTE_FISCAL_PED, NOMBRE_PAI_CLIENTE_FISCAL_' +
        'PED, ESIVA_RECARGO_CLIENTE_PED, ESIVA_EXENTO_CLIENTE_PED, ESREGI' +
        'MENESPECIALAGRICOLA_CLIENTE_PED, ESRETENCIONES_CLIENTE_PED, TARI' +
        'FA_ARTICULO_CLIENTE_PED, ESIMP_INCL_TARIFA_CLIENTE_PED, ESINTRAC' +
        'OMUNITARIO_CLIENTE_PED, ESIRPF_IMP_INCL_ZONA_IVA_PED, ESAPLICA_R' +
        'E_ZONA_IVA_PED, ESIVAAGRICOLA_ZONA_IVA_PED, PALABRA_REPORTS_ZONA' +
        '_IVA_PED, CODIGO_IVA_PED, ESVENTA_ACTIVO_FIJO_PED, PORCENTAJE_IV' +
        'AN_PED, TOTAL_IVAN_PED, PORCENTAJE_REN_PED, TOTAL_REN_PED, TOTAL' +
        '_BASEI_IVAN_PED, PORCENTAJE_IVAR_PED, TOTAL_IVAR_PED, PORCENTAJE' +
        '_RER_PED, TOTAL_RER_PED, TOTAL_BASEI_IVAR_PED, PORCENTAJE_IVAS_P' +
        'ED, TOTAL_IVAS_PED, PORCENTAJE_RES_PED, TOTAL_RES_PED, TOTAL_BAS' +
        'EI_IVAS_PED, PORCENTAJE_IVAE_PED, TOTAL_IVAE_PED, PORCENTAJE_REE' +
        '_PED, TOTAL_REE_PED, TOTAL_BASEI_IVAE_PED, TOTAL_BASES_PED, TOTA' +
        'L_IMPUESTOS_PED, FORMA_PAGO_PED, PORCENTAJE_RETENCION_PED, TOTAL' +
        '_RETENCION_PED, TOTAL_LIQUIDO_PED, TOTAL_PAGADOREALPS_PED, NUMER' +
        'O_PED_ABONO_PED, SERIE_PED_ABONO_PED, TEXTO_LEGAL_CLIENTE_PED, T' +
        'EXTO_LEGAL_EMPRESA_PED, DOCUMENTO_PED, COMENTARIOS_PED, CONTADOR' +
        '_LINEAS_PED, ESCREARARTICULOS_PED, ESDESCRIPCIONES_AMP_PED, ESFE' +
        'CHADEENTREGA_PED, INSTANTE_MODIF, INSTANTE_ALTA, USUARIO_ALTA, U' +
        'SUARIO_MODIF FROM fza_pedidos'
      'WHERE'
      '  NUMERO_PED = :NUMERO_PED AND SERIE_PED = :SERIE_PED')
    SQLRecCount.Strings = (
      'SELECT COUNT(*) FROM fza_pedidos')
    Connection = dmConn.conUni
    SQL.Strings = (
      'select * from vi_pedidos'
      ' ORDER BY FECHA_PED DESC, NUMERO_PED DESC')
    AfterInsert = unqryTablaGAfterInsert
    BeforeDelete = unqryTablaGBeforeDelete
    Left = 48
    Top = 24
  end
  inherited unqryPerfiles: TUniQuery
    SQL.Strings = (
      'select *'
      'from fza_usuarios_perfiles')
    Left = 496
    Top = 96
  end
  inherited dsPerfiles: TDataSource
    Left = 495
    Top = 32
  end
  object unqryPedidosLineas: TUniQuery
    SQLInsert.Strings = (
      'INSERT INTO fza_pedidos_lineas'
      
        '  (NUMERO_PED_PEDLIN, SERIE_PED_PEDLIN, LINEA_PEDLIN, IDLINEAPS_' +
        'PEDLIN, IDPRODPS_PEDLIN, CODIGOPRODPS_PEDLIN, IDATRIBPRODPS_PEDL' +
        'IN, CODBAR_ART_PEDLIN, CODIGO_ART_PEDLIN, CODIGO_FAM_PEDLIN, NOM' +
        'BRE_FAM_PEDLIN, FECHA_ENTREGA_PEDLIN, TIPO_CANTIDAD_ARTICULO_PED' +
        'LIN, ESIMP_INCL_TARIFA_PEDLIN, TIPO_IVA_ARTICULO_PEDLIN, DESCRIP' +
        'CION_ARTICULO_PEDLIN, CODIGO_TAR_PEDLIN, CANTIDAD_PEDLIN, CANTID' +
        'AD_ENTREGADA_PEDLIN, CANTIDAD_PENDIENTE_PEDLIN, ESENTREGADA_PEDL' +
        'IN, CODIGO_ALMACEN_PEDLIN, PRECIO' +
        '_VENTA_SIVA_ARTICULO_PEDLIN, PORCENTAJE_IVA_PEDLIN, PRECIO_VENTA' +
        '_CIVA_ARTICULO_PEDLIN, TOTAL_PEDLIN, INSTANTE_MODIF, INSTANTE_AL' +
        'TA, USUARIO_ALTA, USUARIO_MODIF)'
      'VALUES'
      
        '  (:NUMERO_PED_PEDLIN, :SERIE_PED_PEDLIN, :LINEA_PEDLIN, :IDLINE' +
        'APS_PEDLIN, :IDPRODPS_PEDLIN, :CODIGOPRODPS_PEDLIN, :IDATRIBPROD' +
        'PS_PEDLIN, :CODBAR_ART_PEDLIN, :CODIGO_ART_PEDLIN, :CODIGO_FAM_P' +
        'EDLIN, :NOMBRE_FAM_PEDLIN, :FECHA_ENTREGA_PEDLIN, :TIPO_CANTIDAD' +
        '_ARTICULO_PEDLIN, :ESIMP_INCL_TARIFA_PEDLIN, :TIPO_IVA_ARTICULO_' +
        'PEDLIN, :DESCRIPCION_ARTICULO_PEDLIN, :CODIGO_TAR_PEDLIN, :CANTI' +
        'DAD_PEDLIN, :CANTIDAD_ENTREGADA_PEDLIN, :CANTIDAD_PENDIENTE_PEDL' +
        'IN, :ESENTREGADA_PEDLIN, :CODIGO_ALMACEN_PEDLIN, :PRECIO_VENTA_S' +
        'IVA_ARTICULO_PEDLIN, :PORCENTAJE_IVA_' +
        'PEDLIN, :PRECIO_VENTA_CIVA_ARTICULO_PEDLIN, :TOTAL_PEDLIN, :INST' +
        'ANTE_MODIF, :INSTANTE_ALTA, :USUARIO_ALTA, :USUARIO_MODIF)')
    SQLDelete.Strings = (
      'DELETE FROM fza_pedidos_lineas'
      'WHERE'
      
        '  NUMERO_PED_PEDLIN = :Old_NUMERO_PED_PEDLIN AND SERIE_PED_PEDLI' +
        'N = :Old_SERIE_PED_PEDLIN AND LINEA_PEDLIN = :Old_LINEA_PEDLIN')
    SQLUpdate.Strings = (
      'UPDATE fza_pedidos_lineas'
      'SET'
      
        '  NUMERO_PED_PEDLIN = :NUMERO_PED_PEDLIN, SERIE_PED_PEDLIN = :SE' +
        'RIE_PED_PEDLIN, LINEA_PEDLIN = :LINEA_PEDLIN, IDLINEAPS_PEDLIN =' +
        ' :IDLINEAPS_PEDLIN, IDPRODPS_PEDLIN = :IDPRODPS_PEDLIN, CODIGOPR' +
        'ODPS_PEDLIN = :CODIGOPRODPS_PEDLIN, IDATRIBPRODPS_PEDLIN = :IDAT' +
        'RIBPRODPS_PEDLIN, CODBAR_ART_PEDLIN = :CODBAR_ART_PEDLIN, CODIGO' +
        '_ART_PEDLIN = :CODIGO_ART_PEDLIN, CODIGO_FAM_PEDLIN = :CODIGO_FA' +
        'M_PEDLIN, NOMBRE_FAM_PEDLIN = :NOMBRE_FAM_PEDLIN, FECHA_ENTREGA_' +
        'PEDLIN = :FECHA_ENTREGA_PEDLIN, TIPO_CANTIDAD_ARTICULO_PEDLIN = ' +
        ':TIPO_CANTIDAD_ARTICULO_PEDLIN, ESIMP_INCL_TARIFA_PEDLIN = :ESIM' +
        'P_INCL_TARIFA_PEDLIN, TIPO_IVA_ARTICULO_PEDLIN = :TIPO_IVA_ARTIC' +
        'ULO_PEDLIN, DESCRIPCION_ARTICULO_PEDLIN = :DESCRIPCION_ARTICULO_' +
        'PEDLIN, CODIGO_TAR_PEDLIN = :CODIGO_TAR_PEDLIN, CANTIDAD_PEDLIN ' +
        '= :CANTIDAD_PEDLIN, CANTIDAD_ENTREGADA_PEDLIN = :CANTIDAD_ENTREG' +
        'ADA_PEDLIN, CANTIDAD_PENDIENTE_PEDLIN = :CANTIDAD_PENDIENTE_PEDL' +
        'IN, ESENTREGADA_PEDLIN = :ESENTREGADA_PEDLIN, CODIGO_ALMACEN_PED' +
        'LIN = :CODIGO_ALMACEN_PEDLIN, PRECIO_VENTA_SIVA_ARTICULO_PEDLIN ' +
        '= :PRECIO_' +
        'VENTA_SIVA_ARTICULO_PEDLIN, PORCENTAJE_IVA_PEDLIN = :PORCENTAJE_' +
        'IVA_PEDLIN, PRECIO_VENTA_CIVA_ARTICULO_PEDLIN = :PRECIO_VENTA_CI' +
        'VA_ARTICULO_PEDLIN, TOTAL_PEDLIN = :TOTAL_PEDLIN, INSTANTE_MODIF' +
        ' = :INSTANTE_MODIF, INSTANTE_ALTA = :INSTANTE_ALTA, USUARIO_ALTA' +
        ' = :USUARIO_ALTA, USUARIO_MODIF = :USUARIO_MODIF'
      'WHERE'
      
        '  NUMERO_PED_PEDLIN = :Old_NUMERO_PED_PEDLIN AND SERIE_PED_PEDLI' +
        'N = :Old_SERIE_PED_PEDLIN AND LINEA_PEDLIN = :Old_LINEA_PEDLIN')
    SQLLock.Strings = (
      
        'SELECT NUMERO_PED_PEDLIN, SERIE_PED_PEDLIN, LINEA_PEDLIN, IDLINE' +
        'APS_PEDLIN, IDPRODPS_PEDLIN, CODIGOPRODPS_PEDLIN, IDATRIBPRODPS_' +
        'PEDLIN, CODBAR_ART_PEDLIN, CODIGO_ART_PEDLIN, CODIGO_FAM_PEDLIN,' +
        ' NOMBRE_FAM_PEDLIN, FECHA_ENTREGA_PEDLIN, TIPO_CANTIDAD_ARTICULO' +
        '_PEDLIN, ESIMP_INCL_TARIFA_PEDLIN, TIPO_IVA_ARTICULO_PEDLIN, DES' +
        'CRIPCION_ARTICULO_PEDLIN, CODIGO_TAR_PEDLIN, CANTIDAD_PEDLIN, CA' +
        'NTIDAD_ENTREGADA_PEDLIN, CANTIDAD_PENDIENTE_PEDLIN, ESENTREGADA_' +
        'PEDLIN, CODIGO_ALMACEN_PEDLIN, PRECIO_VENTA_SIVA_ARTICULO_PEDLIN' +
        ', PORCENTAJE_IVA_PEDLIN, PRECIO_V' +
        'ENTA_CIVA_ARTICULO_PEDLIN, TOTAL_PEDLIN, INSTANTE_MODIF, INSTANT' +
        'E_ALTA, USUARIO_ALTA, USUARIO_MODIF FROM fza_pedidos_lineas'
      'WHERE'
      
        '  NUMERO_PED_PEDLIN = :Old_NUMERO_PED_PEDLIN AND SERIE_PED_PEDLI' +
        'N = :Old_SERIE_PED_PEDLIN AND LINEA_PEDLIN = :Old_LINEA_PEDLIN'
      'FOR UPDATE')
    SQLRefresh.Strings = (
      
        'SELECT NUMERO_PED_PEDLIN, SERIE_PED_PEDLIN, LINEA_PEDLIN, IDLINE' +
        'APS_PEDLIN, IDPRODPS_PEDLIN, CODIGOPRODPS_PEDLIN, IDATRIBPRODPS_' +
        'PEDLIN, CODBAR_ART_PEDLIN, CODIGO_ART_PEDLIN, CODIGO_FAM_PEDLIN,' +
        ' NOMBRE_FAM_PEDLIN, FECHA_ENTREGA_PEDLIN, TIPO_CANTIDAD_ARTICULO' +
        '_PEDLIN, ESIMP_INCL_TARIFA_PEDLIN, TIPO_IVA_ARTICULO_PEDLIN, DES' +
        'CRIPCION_ARTICULO_PEDLIN, CODIGO_TAR_PEDLIN, CANTIDAD_PEDLIN, CA' +
        'NTIDAD_ENTREGADA_PEDLIN, CANTIDAD_PENDIENTE_PEDLIN, ESENTREGADA_' +
        'PEDLIN, CODIGO_ALMACEN_PEDLIN, PRECIO_VENTA_SIVA_ARTICULO_PEDLIN' +
        ', PORCENTAJE_IVA_PEDLIN, PRECIO_V' +
        'ENTA_CIVA_ARTICULO_PEDLIN, TOTAL_PEDLIN, INSTANTE_MODIF, INSTANT' +
        'E_ALTA, USUARIO_ALTA, USUARIO_MODIF FROM fza_pedidos_lineas'
      'WHERE'
      
        '  NUMERO_PED_PEDLIN = :NUMERO_PED_PEDLIN AND SERIE_PED_PEDLIN = ' +
        ':SERIE_PED_PEDLIN AND LINEA_PEDLIN = :LINEA_PEDLIN')
    SQLRecCount.Strings = (
      'SELECT COUNT(*) FROM fza_pedidos_lineas')
    Connection = dmConn.conUni
    SQL.Strings = (
      'SELECT * FROM vi_pedidos_lineas')
    MasterFields = 'NUMERO_PED;SERIE_PED'
    DetailFields = 'NUMERO_PED_PEDLIN;SERIE_PED_PEDLIN'
    AfterInsert = unqryPedidosLineasAfterInsert
    BeforePost = unqryPedidosLineasBeforePost
    AfterPost = unqryPedidosLineasAfterPost
    BeforeDelete = unqryPedidosLineasBeforeDelete
    Left = 48
    Top = 80
    ParamData = <
      item
        DataType = ftUnknown
        Name = 'NUMERO_PED'
        Value = nil
      end
      item
        DataType = ftUnknown
        Name = 'SERIE_PED'
        Value = nil
      end>
  end
  object dsPedidosLineas: TDataSource
    DataSet = unqryPedidosLineas
    Left = 128
    Top = 80
  end
  object unqryLinPedido: TUniQuery
    Connection = dmConn.conUni
    SQL.Strings = (
      'SELECT * FROM fza_pedidos_lineas'
      'WHERE NUMERO_PED_PEDLIN = :NUMERO_PED'
      'AND SERIE_PED_PEDLIN = :SERIE_PED')
    Left = 48
    Top = 136
    ParamData = <
      item
        DataType = ftUnknown
        Name = 'NUMERO_PED'
        Value = nil
      end
      item
        DataType = ftUnknown
        Name = 'SERIE_PED'
        Value = nil
      end>
  end
  object dsLinPedido: TDataSource
    DataSet = unqryLinPedido
    Left = 128
    Top = 136
  end
  object unqryEmpDataPedido: TUniQuery
    Connection = dmConn.conUni
    SQL.Strings = (
      'SELECT * FROM fza_empresas')
    Left = 48
    Top = 192
  end
  object unqryCliDataPedido: TUniQuery
    Connection = dmConn.conUni
    SQL.Strings = (
      'SELECT * FROM fza_clientes')
    Left = 48
    Top = 248
  end
  object unqryArtDataLinPedido: TUniQuery
    Connection = dmConn.conUni
    SQL.Strings = (
      'SELECT * FROM fza_articulos')
    Left = 48
    Top = 304
  end
  object unstrdprcCrearPedido: TUniStoredProc
    StoredProcName = 'PRC_CREAR_PEDIDO'
    Connection = dmConn.conUni
    Left = 256
    Top = 24
  end
  object unstrdprcGetContadorPedido: TUniStoredProc
    StoredProcName = 'PRC_GET_NEXT_CONT_FACT_SERIE'
    Connection = dmConn.conUni
    Left = 256
    Top = 80
  end
  object unstrdprcGetContador: TUniStoredProc
    StoredProcName = 'PRC_GET_NEXT_CONT'
    Connection = dmConn.conUni
    Left = 256
    Top = 136
  end
  object fxdsPrintPed: TfrxDBDataset
    UserName = 'frxDBDataset1'
    CloseDataSource = False
    BCDToCurrency = False
    DataSetOptions = []
    Left = 384
    Top = 24
  end
  object fxdstPrintLinPed: TfrxDBDataset
    UserName = 'frxDBDataset2'
    CloseDataSource = False
    DataSet = unqryPedidosLineas
    BCDToCurrency = False
    DataSetOptions = []
    Left = 384
    Top = 80
  end
  object unqryAlbaranes: TUniQuery
    Connection = dmConn.conUni
    SQL.Strings = (
      'SELECT * FROM fza_albaranes'
      'WHERE NUMERO_PED_ALB = :NUMERO_PED'
      '  AND SERIE_PED_ALB  = :SERIE_PED'
      'ORDER BY FECHA_ALB DESC, NUMERO_ALB DESC')
    MasterFields = 'NUMERO_PED;SERIE_PED'
    DetailFields = 'NUMERO_PED_ALB;SERIE_PED_ALB'
    Left = 384
    Top = 200
    ParamData = <
      item
        DataType = ftUnknown
        Name = 'NUMERO_PED'
        Value = nil
      end
      item
        DataType = ftUnknown
        Name = 'SERIE_PED'
        Value = nil
      end>
  end
  object dsAlbaranes: TDataSource
    DataSet = unqryAlbaranes
    Left = 464
    Top = 200
  end
  object unqryMensajes: TUniQuery
    Connection = dmConn.conUni
    SQL.Strings = (
      'SELECT * FROM fza_pedidos_mensajes M'
      'WHERE M.IDPS_MENSAJES_PEDMSG = :IDHILO')
    Left = 384
    Top = 256
    ParamData = <
      item
        DataType = ftUnknown
        Name = 'IDHILO'
        Value = nil
      end>
  end
  object dsMensajes: TDataSource
    DataSet = unqryMensajes
    Left = 464
    Top = 256
  end
  object unstrdprcCrearAlbaranInicio: TUniStoredProc
    StoredProcName = 'PRC_PED_CREAR_ALBARAN_INICIO'
    Connection = dmConn.conUni
    Left = 256
    Top = 200
  end
  object unstrdprcCrearAlbaranLinea: TUniStoredProc
    StoredProcName = 'PRC_PED_CREAR_ALBARAN_LINEA'
    Connection = dmConn.conUni
    Left = 256
    Top = 256
  end
  object unstrdprcCrearAlbaranFin: TUniStoredProc
    StoredProcName = 'PRC_PED_CREAR_ALBARAN_FIN'
    Connection = dmConn.conUni
    Left = 256
    Top = 312
  end
  object unqryFormasPago: TUniQuery
    Connection = dmConn.conUni
    SQL.Strings = (
      'SELECT * FROM vi_formapago')
    ReadOnly = True
    Left = 512
    Top = 312
  end
  object dsFormasPago: TDataSource
    DataSet = unqryFormasPago
    Left = 512
    Top = 368
  end
  object unqryAlmacenesPed: TUniQuery
    Connection = dmConn.conUni
    SQL.Strings = (
      'SELECT CODIGO_ALM_ALM, NOMBRE_ALM_ALM, CODIGO_EMP_ALM'
      '  FROM fza_almacenes'
      ' WHERE ESACTIVO_ALM = '#39'S'#39
      '   AND CODIGO_EMP_ALM = :EMPRESA'
      ' ORDER BY COALESCE(ORDEN_ALM, 2147483647), CODIGO_ALM_ALM')
    ReadOnly = True
    Left = 600
    Top = 312
    ParamData = <
      item
        DataType = ftString
        Name = 'EMPRESA'
        ParamType = ptInput
        Value = nil
      end>
  end
  object dsAlmacenesPed: TDataSource
    DataSet = unqryAlmacenesPed
    Left = 600
    Top = 368
  end
  object unqryTarifas: TUniQuery
    Connection = dmConn.conUni
    SQL.Strings = (
      'SELECT CODIGO_TAR_ARTTAR, NOMBRE_TAR_TAR, ESIMP_INCL_TAR'
      '  FROM vi_tarifas'
      ' ORDER BY NOMBRE_TAR_TAR, CODIGO_TAR_ARTTAR')
    ReadOnly = True
    Left = 688
    Top = 312
  end
  object dsTarifas: TDataSource
    DataSet = unqryTarifas
    Left = 688
    Top = 368
  end
end
