inherited dmEmpleados: TdmEmpleados
  Height = 187
  Width = 399
  inherited unqryTablaG: TUniQuery
    SQLInsert.Strings = (
      'INSERT INTO fza_empleados'

        '  (CODIGO_EMPL, NOMBRE_EMPL, RAZON_SOCIAL_EMPL, NIF_EMPL, DIRECCI' +
        'ON_EMPL, DIRECCION2_EMPL, CODIGO_POSTAL_EMPL, POBLACION_EMPL, PRO' +
        'VINCIA_EMPL, TELEFONO_EMPL, TELEFONO2_EMPL, FAX_EMPL, EMAIL_EMPL,' +
        ' WEB_EMPL, IBAN_EMPL, BIC_EMPL, DIMINUTIVO_TICKET_EMPL, ESACTIVO' +
        '_EMPL, INSTANTE_MODIF, INSTANTE_ALTA, USUARIO_ALTA, USUARIO_MODIF)'
      'VALUES'

        '  (:CODIGO_EMPL, :NOMBRE_EMPL, :RAZON_SOCIAL_EMPL, :NIF_EMPL, :DI' +
        'RECCION_EMPL, :DIRECCION2_EMPL, :CODIGO_POSTAL_EMPL, :POBLACION_E' +
        'MPL, :PROVINCIA_EMPL, :TELEFONO_EMPL, :TELEFONO2_EMPL, :FAX_EMPL,' +
        ' :EMAIL_EMPL, :WEB_EMPL, :IBAN_EMPL, :BIC_EMPL, :DIMINUTIVO_TICK' +
        'ET_EMPL, :ESACTIVO_EMPL, :INSTANTE_MODIF, :INSTANTE_ALTA, :USUARI' +
        'O_ALTA, :USUARIO_MODIF)')
    SQLDelete.Strings = (
      'DELETE FROM fza_empleados'
      'WHERE'
      '  CODIGO_EMPL = :Old_CODIGO_EMPL')
    SQLUpdate.Strings = (
      'UPDATE fza_empleados'
      'SET'

        '  CODIGO_EMPL = :CODIGO_EMPL, NOMBRE_EMPL = :NOMBRE_EMPL, RAZON_S' +
        'OCIAL_EMPL = :RAZON_SOCIAL_EMPL, NIF_EMPL = :NIF_EMPL, DIRECCION_' +
        'EMPL = :DIRECCION_EMPL, DIRECCION2_EMPL = :DIRECCION2_EMPL, CODIG' +
        'O_POSTAL_EMPL = :CODIGO_POSTAL_EMPL, POBLACION_EMPL = :POBLACION_' +
        'EMPL, PROVINCIA_EMPL = :PROVINCIA_EMPL, TELEFONO_EMPL = :TELEFONO' +
        '_EMPL, TELEFONO2_EMPL = :TELEFONO2_EMPL, FAX_EMPL = :FAX_EMPL, EM' +
        'AIL_EMPL = :EMAIL_EMPL, WEB_EMPL = :WEB_EMPL, IBAN_EMPL = :IBAN_E' +
        'MPL, BIC_EMPL = :BIC_EMPL, DIMINUTIVO_TICKET_EMPL = :DIMINUTIVO_T' +
        'ICKET_EMPL, ESACTIVO_EMPL = :ESACTIVO_EMPL, INSTANTE_MODIF = :INS' +
        'TANTE_MODIF, INSTANTE_ALTA = :INSTANTE_ALTA, USUARIO_ALTA = :USUA' +
        'RIO_ALTA, USUARIO_MODIF = :USUARIO_MODIF'
      'WHERE'
      '  CODIGO_EMPL = :Old_CODIGO_EMPL')
    SQLLock.Strings = (

        'SELECT CODIGO_EMPL, NOMBRE_EMPL, RAZON_SOCIAL_EMPL, NIF_EMPL, DIR' +
        'ECCION_EMPL, DIRECCION2_EMPL, CODIGO_POSTAL_EMPL, POBLACION_EMPL,' +
        ' PROVINCIA_EMPL, TELEFONO_EMPL, TELEFONO2_EMPL, FAX_EMPL, EMAIL_E' +
        'MPL, WEB_EMPL, IBAN_EMPL, BIC_EMPL, DIMINUTIVO_TICKET_EMPL, ESACT' +
        'IVO_EMPL, INSTANTE_MODIF, INSTANTE_ALTA, USUARIO_ALTA, USUARIO_MO' +
        'DIF FROM fza_empleados'
      'WHERE'
      '  CODIGO_EMPL = :Old_CODIGO_EMPL'
      'FOR UPDATE')
    SQLRefresh.Strings = (
      'SELECT * FROM vi_empleados'
      'WHERE'
      '  CODIGO_EMPL = :CODIGO_EMPL')
    SQLRecCount.Strings = (
      'SELECT COUNT(*) FROM fza_empleados')
    Connection = dmConn.conUni
    SQL.Strings = (
      'SELECT *  '
      'FROM vi_empleados'
      '')
    AfterInsert = unqryTablaGAfterInsert
    Left = 24
  end
end
