inherited dmCajaOperacionesHist: TdmCajaOperacionesHist
  inherited unqryTablaG: TUniQuery
    SQLInsert.Strings = (
      'INSERT INTO `fza_caja_operaciones`'
      '  (`CODIGO_EMPRESA_OPCAJA`, `CODIGO_ALMACEN_OPCAJA`, `CODIGO_CAJA_OPCAJA`, `NUMERO_OPERACION_OPCAJA`, `NRO_FACTURA_OPCAJA`, `SERIE_FACTURA_OPCAJA`, `FECHA_OPERACION_OPCAJA`, `CODIGO_EMPLEADO_OPCAJA`, `TIPO_OPERACION_OPCAJA`, `IMPORTE_TOTAL_OPCAJA`, `CODIGO_CLIENTE_OPCAJA`, `ESTADO_DEVOLUCION_OPCAJA`, `IMPORTE_DEVUELTO_ACUM_OPCAJA`, `CONCEPTO_GASTO_INGRESO_OPCAJA`, `SERIE_REF_ORIGEN_OPCAJA`, `NUMERO_REF_ORIGEN_OPCAJA`, `MOTIVO_DEVOLUCION_OPCAJA`, `CODIGO_EMPRESA_CONTRA_OPCAJA`, `CODIGO_ALMACEN_CONTRA_OPCAJA`, `ES_TRASPASO_OPCAJA`, `CODIGO_ARQUEO_OPCAJA`, `INSTANTEMODIF`, `INSTANTEALTA`, `USUARIOALTA`, `USUARIOMODIF`)'
      'VALUES'
      '  (:`CODIGO_EMPRESA_OPCAJA`, :`CODIGO_ALMACEN_OPCAJA`, :`CODIGO_CAJA_OPCAJA`, :`NUMERO_OPERACION_OPCAJA`, :`NRO_FACTURA_OPCAJA`, :`SERIE_FACTURA_OPCAJA`, :`FECHA_OPERACION_OPCAJA`, :`CODIGO_EMPLEADO_OPCAJA`, :`TIPO_OPERACION_OPCAJA`, :`IMPORTE_TOTAL_OPCAJA`, :`CODIGO_CLIENTE_OPCAJA`, :`ESTADO_DEVOLUCION_OPCAJA`, :`IMPORTE_DEVUELTO_ACUM_OPCAJA`, :`CONCEPTO_GASTO_INGRESO_OPCAJA`, :`SERIE_REF_ORIGEN_OPCAJA`, :`NUMERO_REF_ORIGEN_OPCAJA`, :`MOTIVO_DEVOLUCION_OPCAJA`, :`CODIGO_EMPRESA_CONTRA_OPCAJA`, :`CODIGO_ALMACEN_CONTRA_OPCAJA`, :`ES_TRASPASO_OPCAJA`, :`CODIGO_ARQUEO_OPCAJA`, :`INSTANTEMODIF`, :`INSTANTEALTA`, :`USUARIOALTA`, :`USUARIOMODIF`)')
    SQLDelete.Strings = (
      'DELETE FROM `fza_caja_operaciones`'
      'WHERE'
      '  `CODIGO_EMPRESA_OPCAJA` = :`Old_CODIGO_EMPRESA_OPCAJA` AND `CODIGO_ALMACEN_OPCAJA` = :`Old_CODIGO_ALMACEN_OPCAJA` AND `CODIGO_CAJA_OPCAJA` = :`Old_CODIGO_CAJA_OPCAJA` AND `NUMERO_OPERACION_OPCAJA` = :`Old_NUMERO_OPERACION_OPCAJA`')
    SQLUpdate.Strings = (
      'UPDATE `fza_caja_operaciones`'
      'SET'
      '  `CODIGO_EMPRESA_OPCAJA` = :`CODIGO_EMPRESA_OPCAJA`, `CODIGO_ALMACEN_OPCAJA` = :`CODIGO_ALMACEN_OPCAJA`, `CODIGO_CAJA_OPCAJA` = :`CODIGO_CAJA_OPCAJA`, `NUMERO_OPERACION_OPCAJA` = :`NUMERO_OPERACION_OPCAJA`, `NRO_FACTURA_OPCAJA` = :`NRO_FACTURA_OPCAJA`, `SERIE_FACTURA_OPCAJA` = :`SERIE_FACTURA_OPCAJA`, `FECHA_OPERACION_OPCAJA` = :`FECHA_OPERACION_OPCAJA`, `CODIGO_EMPLEADO_OPCAJA` = :`CODIGO_EMPLEADO_OPCAJA`, `TIPO_OPERACION_OPCAJA` = :`TIPO_OPERACION_OPCAJA`, `IMPORTE_TOTAL_OPCAJA` = :`IMPORTE_TOTAL_OPCAJA`, `CODIGO_CLIENTE_OPCAJA` = :`CODIGO_CLIENTE_OPCAJA`, `ESTADO_DEVOLUCION_OPCAJA` = :`ESTADO_DEVOLUCION_OPCAJA`, `IMPORTE_DEVUELTO_ACUM_OPCAJA` = :`IMPORTE_DEVUELTO_ACUM_OPCAJA`, `CONCEPTO_GASTO_INGRESO_OPCAJA` = :`CONCEPTO_GASTO_INGRESO_OPCAJA`, `SERIE_REF_ORIGEN_OPCAJA` = :`SERIE_REF_ORIGEN_OPCAJA`, `NUMERO_REF_ORIGEN_OPCAJA` = :`NUMERO_REF_ORIGEN_OPCAJA`, `MOTIVO_DEVOLUCION_OPCAJA` = :`MOTIVO_DEVOLUCION_OPCAJA`, `CODIGO_EMPRESA_CONTRA_OPCAJA` = :`CODIGO_EMPRESA_CONTRA_OPCAJA`, `CODIGO_ALMACEN_CONTRA_OPCAJA` = :`CODIGO_ALMACEN_CONTRA_OPCAJA`, `ES_TRASPASO_OPCAJA` = :`ES_TRASPASO_OPCAJA`, `CODIGO_ARQUEO_OPCAJA` = :`CODIGO_ARQUEO_OPCAJA`, `INSTANTEMODIF` = :`INSTANTEMODIF`, `INSTANTEALTA` = :`INSTANTEALTA`, `USUARIOALTA` = :`USUARIOALTA`, `USUARIOMODIF` = :`USUARIOMODIF`'
      'WHERE'
      '  `CODIGO_EMPRESA_OPCAJA` = :`Old_CODIGO_EMPRESA_OPCAJA` AND `CODIGO_ALMACEN_OPCAJA` = :`Old_CODIGO_ALMACEN_OPCAJA` AND `CODIGO_CAJA_OPCAJA` = :`Old_CODIGO_CAJA_OPCAJA` AND `NUMERO_OPERACION_OPCAJA` = :`Old_NUMERO_OPERACION_OPCAJA`')
    SQLLock.Strings = (
      'SELECT * FROM `fza_caja_operaciones`'
      'WHERE'
      '  `CODIGO_EMPRESA_OPCAJA` = :`Old_CODIGO_EMPRESA_OPCAJA` AND `CODIGO_ALMACEN_OPCAJA` = :`Old_CODIGO_ALMACEN_OPCAJA` AND `CODIGO_CAJA_OPCAJA` = :`Old_CODIGO_CAJA_OPCAJA` AND `NUMERO_OPERACION_OPCAJA` = :`Old_NUMERO_OPERACION_OPCAJA`'
      'FOR UPDATE')
    SQLRefresh.Strings = (
      'SELECT * FROM `fza_caja_operaciones`'
      'WHERE'
      '  `CODIGO_EMPRESA_OPCAJA` = :`CODIGO_EMPRESA_OPCAJA` AND `CODIGO_ALMACEN_OPCAJA` = :`CODIGO_ALMACEN_OPCAJA` AND `CODIGO_CAJA_OPCAJA` = :`CODIGO_CAJA_OPCAJA` AND `NUMERO_OPERACION_OPCAJA` = :`NUMERO_OPERACION_OPCAJA`')
    SQLRecCount.Strings = (
      'SELECT COUNT(*) FROM fza_caja_operaciones')
    Connection = dmConn.conUni
    SQL.Strings = (
      'SELECT *'
      'FROM fza_caja_operaciones'
      'ORDER BY FECHA_OPERACION_OPCAJA DESC'
      '')
    Active = True
    Left = 24
  end
end
