inherited dmCajaValesHist: TdmCajaValesHist
  inherited unqryTablaG: TUniQuery
    SQLInsert.Strings = (
      'INSERT INTO `fza_caja_vales`'
      '  (`CODIGO_VL`, `CODIGO_PADRE_VL`, `PIN_SEGURIDAD_VL`, `ESTADO_VL`, `IMPORTE_NOMINAL_VL`, `FECHA_EMISION_VL`, `FECHA_CADUCIDAD_VL`, `CODIGO_EMP_EMI_VL`, `CODIGO_ALM_EMI_VL`, `CODIGO_CAJA_EMI_VL`, `NUM' +
      'ERO_OPERACION_EMI_VL`, `SERIE_FAC_EMI_VL`, `NUMERO_FAC_EMI_VL`, `FECHA_REDENCION_VL`, `IMPORTE_REDIMIDO_VL`, `CODIGO_EMP_RED_VL`, `CODIGO_ALM_RED_VL`, `CODIGO_CAJA_RED_VL`, `NUMERO_OPERACION_RED_VL`, ' +
      '`SERIE_FAC_RED_VL`, `NUMERO_FAC_RED_VL`, `CODIGO_CLI_VL`, `OBSERVACIONES_VL`, `INSTANTE_MODIF`, `INSTANTE_ALTA`, `USUARIO_ALTA`, `USUARIO_MODIF`)'
      'VALUES'
      '  (:`CODIGO_VL`, :`CODIGO_PADRE_VL`, :`PIN_SEGURIDAD_VL`, :`ESTADO_VL`, :`IMPORTE_NOMINAL_VL`, :`FECHA_EMISION_VL`, :`FECHA_CADUCIDAD_VL`, :`CODIGO_EMP_EMI_VL`, :`CODIGO_ALM_EMI_VL`, :`CODIGO_CAJA_EMI' +
      '_VL`, :`NUMERO_OPERACION_EMI_VL`, :`SERIE_FAC_EMI_VL`, :`NUMERO_FAC_EMI_VL`, :`FECHA_REDENCION_VL`, :`IMPORTE_REDIMIDO_VL`, :`CODIGO_EMP_RED_VL`, :`CODIGO_ALM_RED_VL`, :`CODIGO_CAJA_RED_VL`, :`NUMERO_' +
      'OPERACION_RED_VL`, :`SERIE_FAC_RED_VL`, :`NUMERO_FAC_RED_VL`, :`CODIGO_CLI_VL`, :`OBSERVACIONES_VL`, :`INSTANTE_MODIF`, :`INSTANTE_ALTA`, :`USUARIO_ALTA`, :`USUARIO_MODIF`)')
    SQLDelete.Strings = (
      'DELETE FROM `fza_caja_vales`'
      'WHERE'
      '  `CODIGO_VL` = :`Old_CODIGO_VL`')
    SQLUpdate.Strings = (
      'UPDATE `fza_caja_vales`'
      'SET'
      '  `CODIGO_VL` = :`CODIGO_VL`, `CODIGO_PADRE_VL` = :`CODIGO_PADRE_VL`, `PIN_SEGURIDAD_VL` = :`PIN_SEGURIDAD_VL`, `ESTADO_VL` = :`ESTADO_VL`, `IMPORTE_NOMINAL_VL` = :`IMPORTE_NOMINAL_VL`, `FECHA_EMISION' +
      '_VL` = :`FECHA_EMISION_VL`, `FECHA_CADUCIDAD_VL` = :`FECHA_CADUCIDAD_VL`, `CODIGO_EMP_EMI_VL` = :`CODIGO_EMP_EMI_VL`, `CODIGO_ALM_EMI_VL` = :`CODIGO_ALM_EMI_VL`, `CODIGO_CAJA_EMI_VL` = :`CODIGO_CAJA_E' +
      'MI_VL`, `NUMERO_OPERACION_EMI_VL` = :`NUMERO_OPERACION_EMI_VL`, `SERIE_FAC_EMI_VL` = :`SERIE_FAC_EMI_VL`, `NUMERO_FAC_EMI_VL` = :`NUMERO_FAC_EMI_VL`, `FECHA_REDENCION_VL` = :`FECHA_REDENCION_VL`, `IMP' +
      'ORTE_REDIMIDO_VL` = :`IMPORTE_REDIMIDO_VL`, `CODIGO_EMP_RED_VL` = :`CODIGO_EMP_RED_VL`, `CODIGO_ALM_RED_VL` = :`CODIGO_ALM_RED_VL`, `CODIGO_CAJA_RED_VL` = :`CODIGO_CAJA_RED_VL`, `NUMERO_OPERACION_RED_' +
      'VL` = :`NUMERO_OPERACION_RED_VL`, `SERIE_FAC_RED_VL` = :`SERIE_FAC_RED_VL`, `NUMERO_FAC_RED_VL` = :`NUMERO_FAC_RED_VL`, `CODIGO_CLI_VL` = :`CODIGO_CLI_VL`, `OBSERVACIONES_VL` = :`OBSERVACIONES_VL`, `I' +
      'NSTANTE_MODIF` = :`INSTANTE_MODIF`, `INSTANTE_ALTA` = :`INSTANTE_ALTA`, `USUARIO_ALTA` = :`USUARIO_ALTA`, `USUARIO_MODIF` = :`USUARIO_MODIF`'
      'WHERE'
      '  `CODIGO_VL` = :`Old_CODIGO_VL`')
    SQLLock.Strings = (
      'SELECT * FROM `fza_caja_vales`'
      'WHERE'
      '  `CODIGO_VL` = :`Old_CODIGO_VL`'
      'FOR UPDATE')
    SQLRefresh.Strings = (
      'SELECT * FROM `fza_caja_vales`'
      'WHERE'
      '  `CODIGO_VL` = :`CODIGO_VL`')
    SQLRecCount.Strings = (
      'SELECT COUNT(*) FROM fza_caja_vales')
    Connection = dmConn.conUni
    SQL.Strings = (
      'SELECT *'
      'FROM fza_caja_vales'
      'ORDER BY FECHA_EMISION_VL DESC'
      '')
    Active = True
    Left = 24
  end
end
