inherited dmCajaOperacionesHist: TdmCajaOperacionesHist
  inherited unqryTablaG: TUniQuery
    SQLInsert.Strings = (
      'INSERT INTO `fza_caja_operaciones`'
      '  (`CODIGO_EMP_OPCAJA`, `CODIGO_ALM_OPCAJA`, `CODIGO_CAJA_OPCAJA`, `NUMERO_OPERACION_OPCAJA`, `NUMERO_FAC_OPCAJA`, `SERIE_FAC_OPCAJA`, `FECHA_OPERACION_OPCAJA`, `CODIGO_EMPLEADO_OPCAJA`, `TIPO_OPERACI' +
      'ON_OPCAJA`, `IMPORTE_TOTAL_OPCAJA`, `CODIGO_CLI_OPCAJA`, `ESTADO_DEVOLUCION_OPCAJA`, `IMPORTE_DEVUELTO_ACUM_OPCAJA`, `CONCEPTO_GASTO_INGRESO_OPCAJA`, `SERIE_REF_ORIGEN_OPCAJA`, `NUMERO_REF_ORIGEN_OPCA' +
      'JA`, `MOTIVO_DEVOLUCION_OPCAJA`, `CODIGO_EMP_CONTRA_OPCAJA`, `CODIGO_ALM_CONTRA_OPCAJA`, `ESTRASPASO_OPCAJA`, `CODIGO_ARQUEO_OPCAJA`, `INSTANTE_MODIF`, `INSTANTE_ALTA`, `USUARIO_ALTA`, `USUARIO_MODIF`' +
      ')'
      'VALUES'
      '  (:`CODIGO_EMP_OPCAJA`, :`CODIGO_ALM_OPCAJA`, :`CODIGO_CAJA_OPCAJA`, :`NUMERO_OPERACION_OPCAJA`, :`NUMERO_FAC_OPCAJA`, :`SERIE_FAC_OPCAJA`, :`FECHA_OPERACION_OPCAJA`, :`CODIGO_EMPLEADO_OPCAJA`, :`TIP' +
      'O_OPERACION_OPCAJA`, :`IMPORTE_TOTAL_OPCAJA`, :`CODIGO_CLI_OPCAJA`, :`ESTADO_DEVOLUCION_OPCAJA`, :`IMPORTE_DEVUELTO_ACUM_OPCAJA`, :`CONCEPTO_GASTO_INGRESO_OPCAJA`, :`SERIE_REF_ORIGEN_OPCAJA`, :`NUMERO' +
      '_REF_ORIGEN_OPCAJA`, :`MOTIVO_DEVOLUCION_OPCAJA`, :`CODIGO_EMP_CONTRA_OPCAJA`, :`CODIGO_ALM_CONTRA_OPCAJA`, :`ESTRASPASO_OPCAJA`, :`CODIGO_ARQUEO_OPCAJA`, :`INSTANTE_MODIF`, :`INSTANTE_ALTA`, :`USUARI' +
      'O_ALTA`, :`USUARIO_MODIF`)')
    SQLDelete.Strings = (
      'DELETE FROM `fza_caja_operaciones`'
      'WHERE'
      '  `CODIGO_EMP_OPCAJA` = :`Old_CODIGO_EMPRESA_OPCAJA` AND `CODIGO_ALM_OPCAJA` = :`Old_CODIGO_ALMACEN_OPCAJA` AND `CODIGO_CAJA_OPCAJA` = :`Old_CODIGO_CAJA_OPCAJA` AND `NUMERO_OPERACION_OPCAJA` = :`Old_NUMERO_OPERACION_OPCAJA`')
    SQLUpdate.Strings = (
      'UPDATE `fza_caja_operaciones`'
      'SET'
      '  `CODIGO_EMP_OPCAJA` = :`CODIGO_EMP_OPCAJA`, `CODIGO_ALM_OPCAJA` = :`CODIGO_ALM_OPCAJA`, `CODIGO_CAJA_OPCAJA` = :`CODIGO_CAJA_OPCAJA`, `NUMERO_OPERACION_OPCAJA` = :`NUMERO_OPERACION_OPCAJA`, `NUMERO_' +
      'FAC_OPCAJA` = :`NUMERO_FAC_OPCAJA`, `SERIE_FAC_OPCAJA` = :`SERIE_FAC_OPCAJA`, `FECHA_OPERACION_OPCAJA` = :`FECHA_OPERACION_OPCAJA`, `CODIGO_EMPLEADO_OPCAJA` = :`CODIGO_EMPLEADO_OPCAJA`, `TIPO_OPERACIO' +
      'N_OPCAJA` = :`TIPO_OPERACION_OPCAJA`, `IMPORTE_TOTAL_OPCAJA` = :`IMPORTE_TOTAL_OPCAJA`, `CODIGO_CLI_OPCAJA` = :`CODIGO_CLI_OPCAJA`, `ESTADO_DEVOLUCION_OPCAJA` = :`ESTADO_DEVOLUCION_OPCAJA`, `IMPORTE_D' +
      'EVUELTO_ACUM_OPCAJA` = :`IMPORTE_DEVUELTO_ACUM_OPCAJA`, `CONCEPTO_GASTO_INGRESO_OPCAJA` = :`CONCEPTO_GASTO_INGRESO_OPCAJA`, `SERIE_REF_ORIGEN_OPCAJA` = :`SERIE_REF_ORIGEN_OPCAJA`, `NUMERO_REF_ORIGEN_O' +
      'PCAJA` = :`NUMERO_REF_ORIGEN_OPCAJA`, `MOTIVO_DEVOLUCION_OPCAJA` = :`MOTIVO_DEVOLUCION_OPCAJA`, `CODIGO_EMP_CONTRA_OPCAJA` = :`CODIGO_EMP_CONTRA_OPCAJA`, `CODIGO_ALM_CONTRA_OPCAJA` = :`CODIGO_ALM_CONT' +
      'RA_OPCAJA`, `ESTRASPASO_OPCAJA` = :`ESTRASPASO_OPCAJA`, `CODIGO_ARQUEO_OPCAJA` = :`CODIGO_ARQUEO_OPCAJA`, `INSTANTE_MODIF` = :`INSTANTE_MODIF`, `INSTANTE_ALTA` = :`INSTANTE_ALTA`, `USUARIO_ALTA` = :`U' +
      'SUARIO_ALTA`, `USUARIO_MODIF` = :`USUARIO_MODIF`'
      'WHERE'
      '  `CODIGO_EMP_OPCAJA` = :`Old_CODIGO_EMPRESA_OPCAJA` AND `CODIGO_ALM_OPCAJA` = :`Old_CODIGO_ALMACEN_OPCAJA` AND `CODIGO_CAJA_OPCAJA` = :`Old_CODIGO_CAJA_OPCAJA` AND `NUMERO_OPERACION_OPCAJA` = :`Old_NUMERO_OPERACION_OPCAJA`')
    SQLLock.Strings = (
      'SELECT * FROM `fza_caja_operaciones`'
      'WHERE'
      '  `CODIGO_EMP_OPCAJA` = :`Old_CODIGO_EMPRESA_OPCAJA` AND `CODIGO_ALM_OPCAJA` = :`Old_CODIGO_ALMACEN_OPCAJA` AND `CODIGO_CAJA_OPCAJA` = :`Old_CODIGO_CAJA_OPCAJA` AND `NUMERO_OPERACION_OPCAJA` = :`Old_NUMERO_OPERACION_OPCAJA`'
      'FOR UPDATE')
    SQLRefresh.Strings = (
      'SELECT * FROM `fza_caja_operaciones`'
      'WHERE'
      '  `CODIGO_EMP_OPCAJA` = :`CODIGO_EMP_OPCAJA` AND `CODIGO_ALM_OPCAJA` = :`CODIGO_ALM_OPCAJA` AND `CODIGO_CAJA_OPCAJA` = :`CODIGO_CAJA_OPCAJA` AND `NUMERO_OPERACION_OPCAJA` = :`NUMERO_OPERACION_OPCAJA`')
    SQLRecCount.Strings = (
      'SELECT COUNT(*) FROM fza_caja_operaciones')
    Connection = dmConn.conUni
    SQL.Strings = (
      'SELECT *'
      'FROM fza_caja_operaciones'
      'ORDER BY FECHA_OPERACION_OPCAJA DESC'
      '')
    Active = False
    Left = 24
  end
end
