inherited dmCajaPagosHist: TdmCajaPagosHist
  inherited unqryTablaG: TUniQuery
    SQLInsert.Strings = (
      'INSERT INTO `fza_caja_pagos`'
      '  (`CODIGO_EMP_PAGO`, `CODIGO_ALM_PAGO`, `CODIGO_CAJA_PAGO`, `SERIE_OPERACION_PAGO`, `NUMERO_OPERACION_PAGO`, `NUMERO_LINEA_PAGO`, `CODIGO_FP_CFP`, `CODIGO_DIVISA_PAGO`, `RED_BLOCKCHAIN_PAGO`, `FACTOR' +
      '_CAMBIO_PAGO`, `IMPORTE_DIVISA_PAGO`, `IMPORTE_ENTREGADO_PAGO`, `IMPORTE_CAMBIO_PAGO`, `REFERENCIA_FACPAG`, `OBSERVACIONES_PAGO`, `INSTANTE_MODIF`, `INSTANTE_ALTA`, `USUARIO_ALTA`)'
      'VALUES'
      '  (:`CODIGO_EMP_PAGO`, :`CODIGO_ALM_PAGO`, :`CODIGO_CAJA_PAGO`, :`SERIE_OPERACION_PAGO`, :`NUMERO_OPERACION_PAGO`, :`NUMERO_LINEA_PAGO`, :`CODIGO_FP_CFP`, :`CODIGO_DIVISA_PAGO`, :`RED_BLOCKCHAIN_PAGO`' +
      ', :`FACTOR_CAMBIO_PAGO`, :`IMPORTE_DIVISA_PAGO`, :`IMPORTE_ENTREGADO_PAGO`, :`IMPORTE_CAMBIO_PAGO`, :`REFERENCIA_FACPAG`, :`OBSERVACIONES_PAGO`, :`INSTANTE_MODIF`, :`INSTANTE_ALTA`, :`USUARIO_ALTA`)')
    SQLDelete.Strings = (
      'DELETE FROM `fza_caja_pagos`'
      'WHERE'
      '  `CODIGO_EMP_PAGO` = :`Old_CODIGO_EMPRESA_PAGO` AND `CODIGO_ALM_PAGO` = :`Old_CODIGO_ALMACEN_PAGO` AND `CODIGO_CAJA_PAGO` = :`Old_CODIGO_CAJA_PAGO` AND `SERIE_OPERACION_PAGO` = :`Old_SERIE_OPERACION_' +
      'PAGO` AND `NUMERO_OPERACION_PAGO` = :`Old_NUMERO_OPERACION_PAGO` AND `NUMERO_LINEA_PAGO` = :`Old_NUMERO_LINEA_PAGO`')
    SQLUpdate.Strings = (
      'UPDATE `fza_caja_pagos`'
      'SET'
      '  `CODIGO_EMP_PAGO` = :`CODIGO_EMP_PAGO`, `CODIGO_ALM_PAGO` = :`CODIGO_ALM_PAGO`, `CODIGO_CAJA_PAGO` = :`CODIGO_CAJA_PAGO`, `SERIE_OPERACION_PAGO` = :`SERIE_OPERACION_PAGO`, `NUMERO_OPERACION_PAGO` = ' +
      ':`NUMERO_OPERACION_PAGO`, `NUMERO_LINEA_PAGO` = :`NUMERO_LINEA_PAGO`, `CODIGO_FP_CFP` = :`CODIGO_FP_CFP`, `CODIGO_DIVISA_PAGO` = :`CODIGO_DIVISA_PAGO`, `RED_BLOCKCHAIN_PAGO` = :`RED_BLOCKCHAIN_PAGO`, ' +
      '`FACTOR_CAMBIO_PAGO` = :`FACTOR_CAMBIO_PAGO`, `IMPORTE_DIVISA_PAGO` = :`IMPORTE_DIVISA_PAGO`, `IMPORTE_ENTREGADO_PAGO` = :`IMPORTE_ENTREGADO_PAGO`, `IMPORTE_CAMBIO_PAGO` = :`IMPORTE_CAMBIO_PAGO`, `REF' +
      'ERENCIA_FACPAG` = :`REFERENCIA_FACPAG`, `OBSERVACIONES_PAGO` = :`OBSERVACIONES_PAGO`, `INSTANTE_MODIF` = :`INSTANTE_MODIF`, `INSTANTE_ALTA` = :`INSTANTE_ALTA`, `USUARIO_ALTA` = :`USUARIO_ALTA`'
      'WHERE'
      '  `CODIGO_EMP_PAGO` = :`Old_CODIGO_EMPRESA_PAGO` AND `CODIGO_ALM_PAGO` = :`Old_CODIGO_ALMACEN_PAGO` AND `CODIGO_CAJA_PAGO` = :`Old_CODIGO_CAJA_PAGO` AND `SERIE_OPERACION_PAGO` = :`Old_SERIE_OPERACION_' +
      'PAGO` AND `NUMERO_OPERACION_PAGO` = :`Old_NUMERO_OPERACION_PAGO` AND `NUMERO_LINEA_PAGO` = :`Old_NUMERO_LINEA_PAGO`')
    SQLLock.Strings = (
      'SELECT * FROM `fza_caja_pagos`'
      'WHERE'
      '  `CODIGO_EMP_PAGO` = :`Old_CODIGO_EMPRESA_PAGO` AND `CODIGO_ALM_PAGO` = :`Old_CODIGO_ALMACEN_PAGO` AND `CODIGO_CAJA_PAGO` = :`Old_CODIGO_CAJA_PAGO` AND `SERIE_OPERACION_PAGO` = :`Old_SERIE_OPERACION_' +
      'PAGO` AND `NUMERO_OPERACION_PAGO` = :`Old_NUMERO_OPERACION_PAGO` AND `NUMERO_LINEA_PAGO` = :`Old_NUMERO_LINEA_PAGO`'
      'FOR UPDATE')
    SQLRefresh.Strings = (
      'SELECT * FROM `vi_caja_pagos`'
      'WHERE'
      '  `CODIGO_EMP_PAGO` = :`CODIGO_EMP_PAGO` AND `CODIGO_ALM_PAGO` = :`CODIGO_ALM_PAGO` AND `CODIGO_CAJA_PAGO` = :`CODIGO_CAJA_PAGO` AND `SERIE_OPERACION_PAGO` = :`SERIE_OPERACION_PAGO` AND `NUMERO_OPERAC' +
      'ION_PAGO` = :`NUMERO_OPERACION_PAGO` AND `NUMERO_LINEA_PAGO` = :`NUMERO_LINEA_PAGO`')
    SQLRecCount.Strings = (
      'SELECT COUNT(*) FROM fza_caja_pagos')
    Connection = dmConn.conUni
    SQL.Strings = (
      'SELECT *'
      'FROM vi_caja_pagos'
      'ORDER BY FECHA_PAGO DESC'
      '')
    Active = False
    Left = 24
  end
end
