-- D26: revisión visual de las pantallas de caja en chino simplificado.
-- Los atajos de teclado se conservan literalmente.
SET NAMES utf8mb4;
START TRANSACTION;
INSERT INTO fza_traducciones (
  CLAVE_TRAD, IDIOMA_TRAD, TEXTO_TRAD,
  CONTEXTO_TRAD, ESACTIVO_TRAD,
  ESDESCARGADA_TRAD, INSTANTE_ALTA, USUARIO_ALTA
) VALUES
  ('inMtoCajaMenu.TfrmMtoMenuCaja.Caption',
   'zh-CN', '现金菜单', 'src/Caja/Forms/inMtoCajaMenu.dfm',
   'S', 'S', CURRENT_TIMESTAMP, 'Webservice'),
  ('inMtoCajaMenu.TfrmMtoMenuCaja.lblF5.Caption',
   'zh-CN', 'F5', 'src/Caja/Forms/inMtoCajaMenu.dfm',
   'S', 'S', CURRENT_TIMESTAMP, 'Webservice'),
  ('inMtoCajaMenu.TfrmMtoMenuCaja.lblF10.Caption',
   'zh-CN', 'F10', 'src/Caja/Forms/inMtoCajaMenu.dfm',
   'S', 'S', CURRENT_TIMESTAMP, 'Webservice'),
  ('inMtoCajaMenu.TfrmMtoMenuCaja.lblBuscarModificar.Caption',
   'zh-CN', '查询/修改', 'src/Caja/Forms/inMtoCajaMenu.dfm',
   'S', 'S', CURRENT_TIMESTAMP, 'Webservice'),
  ('inMtoCajaMenu.TfrmMtoMenuCaja.lblVentas.Caption',
   'zh-CN', '销售', 'src/Caja/Forms/inMtoCajaMenu.dfm',
   'S', 'S', CURRENT_TIMESTAMP, 'Webservice'),
  ('inMtoCajaMenu.TfrmMtoMenuCaja.lblF6.Caption',
   'zh-CN', 'F6', 'src/Caja/Forms/inMtoCajaMenu.dfm',
   'S', 'S', CURRENT_TIMESTAMP, 'Webservice'),
  ('inMtoCajaMenu.TfrmMtoMenuCaja.lblEntradaCambio.Caption',
   'zh-CN', '零钱入账', 'src/Caja/Forms/inMtoCajaMenu.dfm',
   'S', 'S', CURRENT_TIMESTAMP, 'Webservice'),
  ('inMtoCajaMenu.TfrmMtoMenuCaja.lblF7.Caption',
   'zh-CN', 'F7', 'src/Caja/Forms/inMtoCajaMenu.dfm',
   'S', 'S', CURRENT_TIMESTAMP, 'Webservice'),
  ('inMtoCajaMenu.TfrmMtoMenuCaja.lblGastosCaja.Caption',
   'zh-CN', '现金支出', 'src/Caja/Forms/inMtoCajaMenu.dfm',
   'S', 'S', CURRENT_TIMESTAMP, 'Webservice'),
  ('inMtoCajaMenu.TfrmMtoMenuCaja.lblArqueo.Caption',
   'zh-CN', '现金盘点', 'src/Caja/Forms/inMtoCajaMenu.dfm',
   'S', 'S', CURRENT_TIMESTAMP, 'Webservice'),
  ('inMtoCajaMenu.TfrmMtoMenuCaja.lblF11.Caption',
   'zh-CN', 'F11', 'src/Caja/Forms/inMtoCajaMenu.dfm',
   'S', 'S', CURRENT_TIMESTAMP, 'Webservice'),
  ('inMtoCajaMenu.TfrmMtoMenuCaja.lblSalir.Caption',
   'zh-CN', '退出', 'src/Caja/Forms/inMtoCajaMenu.dfm',
   'S', 'S', CURRENT_TIMESTAMP, 'Webservice'),
  ('inMtoCajaMenu.TfrmMtoMenuCaja.lblESC.Caption',
   'zh-CN', 'ESC', 'src/Caja/Forms/inMtoCajaMenu.dfm',
   'S', 'S', CURRENT_TIMESTAMP, 'Webservice'),
  ('inMtoCajaMenu.TfrmMtoMenuCaja.lblFecha.Caption',
   'zh-CN', '收银日期', 'src/Caja/Forms/inMtoCajaMenu.dfm',
   'S', 'S', CURRENT_TIMESTAMP, 'Webservice'),
  ('inMtoCajaMenu.TfrmMtoMenuCaja.lblF3.Caption',
   'zh-CN', 'F3', 'src/Caja/Forms/inMtoCajaMenu.dfm',
   'S', 'S', CURRENT_TIMESTAMP, 'Webservice'),
  ('inMtoCajaMenu.TfrmMtoMenuCaja.lblTraspasos.Caption',
   'zh-CN', '调拨', 'src/Caja/Forms/inMtoCajaMenu.dfm',
   'S', 'S', CURRENT_TIMESTAMP, 'Webservice'),
  ('inMtoCajaMenu.TfrmMtoMenuCaja.lblEmpresa.Caption',
   'zh-CN', '公司', 'src/Caja/Forms/inMtoCajaMenu.dfm',
   'S', 'S', CURRENT_TIMESTAMP, 'Webservice'),
  ('inMtoCajaMenu.TfrmMtoMenuCaja.actSalirMenu.Caption',
   'zh-CN', 'ESCAPE', 'src/Caja/Forms/inMtoCajaMenu.dfm',
   'S', 'S', CURRENT_TIMESTAMP, 'Webservice'),
  ('inMtoCajaOpe.TfrmMtoOpeCaja.Caption',
   'zh-CN', '收银操作', 'src/Caja/Forms/inMtoCajaOpe.dfm',
   'S', 'S', CURRENT_TIMESTAMP, 'Webservice'),
  ('inMtoCajaOpe.TfrmMtoOpeCaja.lblFecha.Caption',
   'zh-CN', '员工', 'src/Caja/Forms/inMtoCajaOpe.dfm',
   'S', 'S', CURRENT_TIMESTAMP, 'Webservice'),
  ('inMtoCajaOpe.TfrmMtoOpeCaja.lblNombreEmpleado.Caption',
   'zh-CN', '员工姓名', 'src/Caja/Forms/inMtoCajaOpe.dfm',
   'S', 'S', CURRENT_TIMESTAMP, 'Webservice'),
  ('inMtoCajaOpe.TfrmMtoOpeCaja.lblNombreCliente.Caption',
   'zh-CN', '客户姓名', 'src/Caja/Forms/inMtoCajaOpe.dfm',
   'S', 'S', CURRENT_TIMESTAMP, 'Webservice'),
  ('inMtoCajaOpe.TfrmMtoOpeCaja.lblFechaCaja.Caption',
   'zh-CN', '收银日期', 'src/Caja/Forms/inMtoCajaOpe.dfm',
   'S', 'S', CURRENT_TIMESTAMP, 'Webservice'),
  ('inMtoCajaOpe.TfrmMtoOpeCaja.lblTarifa.Caption',
   'zh-CN', '价目', 'src/Caja/Forms/inMtoCajaOpe.dfm',
   'S', 'S', CURRENT_TIMESTAMP, 'Webservice'),
  ('inMtoCajaOpe.TfrmMtoOpeCaja.lblCliente.Caption',
   'zh-CN', '客户', 'src/Caja/Forms/inMtoCajaOpe.dfm',
   'S', 'S', CURRENT_TIMESTAMP, 'Webservice'),
  ('inMtoCajaOpe.TfrmMtoOpeCaja.lblTipoRectificativa.Caption',
   'zh-CN', '差额更正', 'src/Caja/Forms/inMtoCajaOpe.dfm',
   'S', 'S', CURRENT_TIMESTAMP, 'Webservice'),
  ('inMtoCajaOpe.TfrmMtoOpeCaja.lblTotal.Caption',
   'zh-CN', '合计 0,00 €', 'src/Caja/Forms/inMtoCajaOpe.dfm',
   'S', 'S', CURRENT_TIMESTAMP, 'Webservice'),
  ('inMtoCajaOpe.TfrmMtoOpeCaja.btnF12.Caption',
   'zh-CN', 'F12', 'src/Caja/Forms/inMtoCajaOpe.dfm',
   'S', 'S', CURRENT_TIMESTAMP, 'Webservice'),
  ('inMtoCajaOpe.TfrmMtoOpeCaja.btnF3.Caption',
   'zh-CN', 'F3', 'src/Caja/Forms/inMtoCajaOpe.dfm',
   'S', 'S', CURRENT_TIMESTAMP, 'Webservice'),
  ('inMtoCajaOpe.TfrmMtoOpeCaja.btnF8.Caption',
   'zh-CN', 'F8', 'src/Caja/Forms/inMtoCajaOpe.dfm',
   'S', 'S', CURRENT_TIMESTAMP, 'Webservice'),
  ('inMtoCajaOpe.TfrmMtoOpeCaja.btnF6.Caption',
   'zh-CN', 'F6', 'src/Caja/Forms/inMtoCajaOpe.dfm',
   'S', 'S', CURRENT_TIMESTAMP, 'Webservice'),
  ('inMtoCajaOpe.TfrmMtoOpeCaja.btnF61.Caption',
   'zh-CN', 'F4', 'src/Caja/Forms/inMtoCajaOpe.dfm',
   'S', 'S', CURRENT_TIMESTAMP, 'Webservice'),
  ('inMtoCajaOpe.TfrmMtoOpeCaja.btnF7.Caption',
   'zh-CN', 'F7', 'src/Caja/Forms/inMtoCajaOpe.dfm',
   'S', 'S', CURRENT_TIMESTAMP, 'Webservice'),
  ('inMtoCajaOpe.TfrmMtoOpeCaja.btnF5.Caption',
   'zh-CN', 'F5', 'src/Caja/Forms/inMtoCajaOpe.dfm',
   'S', 'S', CURRENT_TIMESTAMP, 'Webservice'),
  ('inMtoCajaOpe.TfrmMtoOpeCaja.btnF2.Caption',
   'zh-CN', 'F2', 'src/Caja/Forms/inMtoCajaOpe.dfm',
   'S', 'S', CURRENT_TIMESTAMP, 'Webservice'),
  ('inMtoCajaOpe.TfrmMtoOpeCaja.btnF10.Caption',
   'zh-CN', 'F10', 'src/Caja/Forms/inMtoCajaOpe.dfm',
   'S', 'S', CURRENT_TIMESTAMP, 'Webservice'),
  ('inMtoCajaOpe.TfrmMtoOpeCaja.btnF10.Hint',
   'zh-CN', '查询/修改交易', 'src/Caja/Forms/inMtoCajaOpe.dfm',
   'S', 'S', CURRENT_TIMESTAMP, 'Webservice'),
  ('inMtoCajaOpe.TfrmMtoOpeCaja.lblCobro.Caption',
   'zh-CN', '收款', 'src/Caja/Forms/inMtoCajaOpe.dfm',
   'S', 'S', CURRENT_TIMESTAMP, 'Webservice'),
  ('inMtoCajaOpe.TfrmMtoOpeCaja.lblBuscar.Caption',
   'zh-CN', '查找', 'src/Caja/Forms/inMtoCajaOpe.dfm',
   'S', 'S', CURRENT_TIMESTAMP, 'Webservice'),
  ('inMtoCajaOpe.TfrmMtoOpeCaja.lblEliminar.Caption',
   'zh-CN', '删除', 'src/Caja/Forms/inMtoCajaOpe.dfm',
   'S', 'S', CURRENT_TIMESTAMP, 'Webservice'),
  ('inMtoCajaOpe.TfrmMtoOpeCaja.lblTextoTarifa.Caption',
   'zh-CN', '价目', 'src/Caja/Forms/inMtoCajaOpe.dfm',
   'S', 'S', CURRENT_TIMESTAMP, 'Webservice'),
  ('inMtoCajaOpe.TfrmMtoOpeCaja.lblBusqTick.Caption',
   'zh-CN', '退货', 'src/Caja/Forms/inMtoCajaOpe.dfm',
   'S', 'S', CURRENT_TIMESTAMP, 'Webservice'),
  ('inMtoCajaOpe.TfrmMtoOpeCaja.lblIndIVA.Caption',
   'zh-CN', '含税', 'src/Caja/Forms/inMtoCajaOpe.dfm',
   'S', 'S', CURRENT_TIMESTAMP, 'Webservice'),
  ('inMtoCajaOpe.TfrmMtoOpeCaja.lblOtro.Caption',
   'zh-CN', '其他', 'src/Caja/Forms/inMtoCajaOpe.dfm',
   'S', 'S', CURRENT_TIMESTAMP, 'Webservice'),
  ('inMtoCajaOpe.TfrmMtoOpeCaja.lblCargarCta.Caption',
   'zh-CN', '加载账户', 'src/Caja/Forms/inMtoCajaOpe.dfm',
   'S', 'S', CURRENT_TIMESTAMP, 'Webservice'),
  ('inMtoCajaOpe.TfrmMtoOpeCaja.lblBuscarModificar.Caption',
   'zh-CN', '查改', 'src/Caja/Forms/inMtoCajaOpe.dfm',
   'S', 'S', CURRENT_TIMESTAMP, 'Webservice'),
  ('inMtoCajaOpe.TfrmMtoOpeCaja.tvEmpleado.Caption',
   'zh-CN', '销售员', 'src/Caja/Forms/inMtoCajaOpe.dfm',
   'S', 'S', CURRENT_TIMESTAMP, 'Webservice'),
  ('inMtoCajaOpe.TfrmMtoOpeCaja.tvArticulo.Caption',
   'zh-CN', '商品', 'src/Caja/Forms/inMtoCajaOpe.dfm',
   'S', 'S', CURRENT_TIMESTAMP, 'Webservice'),
  ('inMtoCajaOpe.TfrmMtoOpeCaja.tvDescripcion.Caption',
   'zh-CN', '说明', 'src/Caja/Forms/inMtoCajaOpe.dfm',
   'S', 'S', CURRENT_TIMESTAMP, 'Webservice'),
  ('inMtoCajaOpe.TfrmMtoOpeCaja.tvUds.Caption',
   'zh-CN', '数量', 'src/Caja/Forms/inMtoCajaOpe.dfm',
   'S', 'S', CURRENT_TIMESTAMP, 'Webservice'),
  ('inMtoCajaOpe.TfrmMtoOpeCaja.tvTipoCantidad.Caption',
   'zh-CN', '数量类型', 'src/Caja/Forms/inMtoCajaOpe.dfm',
   'S', 'S', CURRENT_TIMESTAMP, 'Webservice'),
  ('inMtoCajaOpe.TfrmMtoOpeCaja.tvPrecioUni.Caption',
   'zh-CN', '单价', 'src/Caja/Forms/inMtoCajaOpe.dfm',
   'S', 'S', CURRENT_TIMESTAMP, 'Webservice'),
  ('inMtoCajaOpe.TfrmMtoOpeCaja.tvDescuento.Caption',
   'zh-CN', '%', 'src/Caja/Forms/inMtoCajaOpe.dfm',
   'S', 'S', CURRENT_TIMESTAMP, 'Webservice'),
  ('inMtoCajaOpe.TfrmMtoOpeCaja.tvDescuentoMenos.Caption',
   'zh-CN', '折扣额', 'src/Caja/Forms/inMtoCajaOpe.dfm',
   'S', 'S', CURRENT_TIMESTAMP, 'Webservice'),
  ('inMtoCajaOpe.TfrmMtoOpeCaja.tvTotal.Caption',
   'zh-CN', '合计', 'src/Caja/Forms/inMtoCajaOpe.dfm',
   'S', 'S', CURRENT_TIMESTAMP, 'Webservice'),
  ('inMtoCajaOpe.TfrmMtoOpeCaja.tvFechaOperacion.Caption',
   'zh-CN', '交易日期', 'src/Caja/Forms/inMtoCajaOpe.dfm',
   'S', 'S', CURRENT_TIMESTAMP, 'Webservice'),
  ('inMtoCajaOpe.TfrmMtoOpeCaja.dbtvBusqCODIGO_ARTICULO.Caption',
   'zh-CN', '商品', 'src/Caja/Forms/inMtoCajaOpe.dfm',
   'S', 'S', CURRENT_TIMESTAMP, 'Webservice'),
  ('inMtoCajaOpe.TfrmMtoOpeCaja.dbtvBusqDESCRIPCION_ARTICULO.Caption',
   'zh-CN', '说明', 'src/Caja/Forms/inMtoCajaOpe.dfm',
   'S', 'S', CURRENT_TIMESTAMP, 'Webservice'),
  ('inMtoCajaOpe.TfrmMtoOpeCaja.dbtvBusqTEMPORADA.Caption',
   'zh-CN', '季节', 'src/Caja/Forms/inMtoCajaOpe.dfm',
   'S', 'S', CURRENT_TIMESTAMP, 'Webservice'),
  ('inMtoCajaOpe.TfrmMtoOpeCaja.dbtvBusqPROVEEDOR.Caption',
   'zh-CN', '供应商', 'src/Caja/Forms/inMtoCajaOpe.dfm',
   'S', 'S', CURRENT_TIMESTAMP, 'Webservice'),
  ('inMtoCajaOpe.TfrmMtoOpeCaja.dbtvBusqREF_PROVEEDOR.Caption',
   'zh-CN', '供应商货号', 'src/Caja/Forms/inMtoCajaOpe.dfm',
   'S', 'S', CURRENT_TIMESTAMP, 'Webservice')
ON DUPLICATE KEY UPDATE
  TEXTO_TRAD = VALUES(TEXTO_TRAD),
  CONTEXTO_TRAD = VALUES(CONTEXTO_TRAD),
  ESACTIVO_TRAD = 'S',
  ESDESCARGADA_TRAD = 'S',
  INSTANTE_MODIF = CURRENT_TIMESTAMP,
  USUARIO_MODIF = VALUES(USUARIO_ALTA);
COMMIT;
