name: Calidad

on:
  pull_request:
  merge_group:
  push:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  compilacion-delphi:
    name: fzam Release Win32 y Win64
    runs-on:
      - self-hosted
      - Windows
      - Delphi
    timeout-minutes: 90
    steps:
      - name: Obtener el repositorio
        uses: actions/checkout@v6
      - name: Compilar fzam
        shell: pwsh
        run: >-
          .\eng\compilar.ps1
          -Configuracion Release
          -Plataforma Ambas
